In [1]:
import torch
from torch import nn, optim
import torch.nn.functional as F
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.decomposition import PCA
from scipy.stats import chi2
from sklearn.mixture import GaussianMixture
from collections import deque, defaultdict

# CAE

In [2]:
train = pd.read_csv('../../train_CADE_cod.csv')
val = pd.read_csv('../../val_CADE_cod.csv')
test = pd.read_csv('../../test_CADE_cod.csv')

In [3]:
classes_out = ['Infilteration','DoS attacks-SlowHTTPTest']
train = train.drop(index=train[train['Label'].isin(classes_out)].index)
val = val.drop(index=val[val['Label'].isin(classes_out)].index)
test = test.drop(index=test[test['Label'].isin(classes_out)].index)

In [5]:
train['Label'] = train['Label'].replace('FTP-BruteForce','BruteForce')
train['Label'] = train['Label'].replace('SSH-Bruteforce','BruteForce')
train['Label'] = train['Label'].replace('DoS attacks-GoldenEye','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Slowloris','DoS')
# train['Label'] = train['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Hulk','DoS')
train['Label'] = train['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
train['Label'] = train['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
train['Label'] = train['Label'].replace('DDOS attack-HOIC','DDoS')
train['Label'] = train['Label'].replace('Brute Force -Web','Web')
train['Label'] = train['Label'].replace('Brute Force -XSS','Web')
train['Label'] = train['Label'].replace('SQL Injection','Web')


val['Label'] = val['Label'].replace('FTP-BruteForce','BruteForce')
val['Label'] = val['Label'].replace('SSH-Bruteforce','BruteForce')
val['Label'] = val['Label'].replace('DoS attacks-GoldenEye','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Slowloris','DoS')
# val['Label'] = val['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Hulk','DoS')
val['Label'] = val['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
val['Label'] = val['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
val['Label'] = val['Label'].replace('DDOS attack-HOIC','DDoS')
val['Label'] = val['Label'].replace('Brute Force -Web','Web')
val['Label'] = val['Label'].replace('Brute Force -XSS','Web')
val['Label'] = val['Label'].replace('SQL Injection','Web')


test['Label'] = test['Label'].replace('FTP-BruteForce','BruteForce')
test['Label'] = test['Label'].replace('SSH-Bruteforce','BruteForce')
test['Label'] = test['Label'].replace('DoS attacks-GoldenEye','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Slowloris','DoS')
# test['Label'] = test['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Hulk','DoS')
test['Label'] = test['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
test['Label'] = test['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
test['Label'] = test['Label'].replace('DDOS attack-HOIC','DDoS')
test['Label'] = test['Label'].replace('Brute Force -Web','Web')
test['Label'] = test['Label'].replace('Brute Force -XSS','Web')
test['Label'] = test['Label'].replace('SQL Injection','Web')

In [20]:
len(test['Label'].values)

649947

In [9]:
labels_str = [i for i in train['Label'].value_counts().index]
print(labels_str)

for i, l in enumerate(labels_str):
    train['Label'] = train['Label'].replace(l, i)
    val['Label'] = val['Label'].replace(l, i)
    test['Label'] = test['Label'].replace(l, i)

['DDoS', 'Benign', 'DoS', 'BruteForce', 'Bot', 'Web']

C:\Users\linco\AppData\Local\Temp\ipykernel_38892\2307520911.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train['Label'] = train['Label'].replace(l, i)
C:\Users\linco\AppData\Local\Temp\ipykernel_38892\2307520911.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  val['Label'] = val['Label'].replace(l, i)
C:\Users\linco\AppData\Local\Temp\ipykernel_38892\2307520911.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['Label'] = test['Label'].replace(l, i)

In [16]:
test['Label']

0         0
1         0
2         1
3         1
5         0
         ..
710046    1
710047    0
710048    0
710049    3
710050    2
Name: Label, Length: 649947, dtype: int64

# CAE CADE (margin 10 e lambda 0.1)

In [6]:
def pick_pair(embeddings, labels, pick_embeddings, pick_labels):
    """
    Gera todos os pares entre embeddings e pick_embeddings,
    com labels_pair indicando se os pares são positivos (0) ou negativos (1).
    """
    N, D = embeddings.shape
    M = pick_embeddings.shape[0]

    # Expande para todas as combinações possíveis
    A = embeddings.unsqueeze(0).expand(M, N, D).reshape(M * N, D)
    B = pick_embeddings.unsqueeze(1).expand(M, N, D).reshape(M * N, D)

    labels_exp = labels.unsqueeze(0).expand(M, N)
    pick_labels_exp = pick_labels.unsqueeze(1).expand(M, N)
    labels_pair = (labels_exp != pick_labels_exp).reshape(-1).float()

    return A, B, labels_pair

def ContrastiveLoss(input1, input2, y, margin=1.0):
    # y = 0 quando input1 e input2 são da mesma classe e y = 1 caso contrário
    diff = input1 - input2
    dist_sq = torch.sum(torch.pow(diff,2),1)
    dist = torch.sqrt(dist_sq + 1e-10) # Soma 1e-10 pois se o sqrt der 0 o gradiente da NaN
    mdist = margin - dist
    mdist = F.relu(mdist)
    loss = ((1-y) * dist * dist) + (y * mdist * mdist)
    return torch.mean(loss)

def AEContrastive(input, output, embeddings, labels, pick_encoded, pick_labels, margin=1.0, lambda1=1.0):
    mseloss = nn.MSELoss()
    ae_loss = mseloss(input,output)

    A, B, labels_pair = pick_pair(embeddings, labels, pick_encoded, pick_labels)
    contrastive_loss = ContrastiveLoss(A, B, labels_pair, margin=margin)
    return ae_loss + contrastive_loss * lambda1, ae_loss, contrastive_loss

In [7]:
class contrastive_ae(nn.Module):
    def __init__(self, input_neurons, neurons):
        super().__init__()
        self.encoder0 = nn.Linear(input_neurons,64)
        self.encoder1 = nn.Linear(64,32)
        self.encoder2 = nn.Linear(32,16)
        self.encoder3 = nn.Linear(16,neurons)

        self.decoder0 = nn.Linear(neurons,16)
        self.decoder1 = nn.Linear(16,32)
        self.decoder2 = nn.Linear(32,64)
        self.decoder3 = nn.Linear(64,input_neurons)

        self.activation0 = nn.ReLU()
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X)
        encoded = X
        X = self.activation0(self.decoder0(X))
        X = self.activation0(self.decoder1(X))
        X = self.activation0(self.decoder2(X))
        X = self.decoder3(X)


        return X, encoded

In [8]:
class encoder(nn.Module):
    def __init__(self, model):
        super().__init__()
        self.encoder0 = list(model.children())[0]
        self.encoder1 = list(model.children())[1]
        self.encoder2 = list(model.children())[2]
        self.encoder3 = list(model.children())[3]
        self.activation0 = list(model.children())[8]
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X)
        return X

In [9]:
from torch.utils.data import Dataset, DataLoader,TensorDataset
import random
def build_class_reference_batches(X_train, y_train, batch_size=512):
    classes = torch.unique(y_train).tolist()
    n_classes = len(classes)
    total_samples = len(X_train)
    dataset = TensorDataset(X_train, y_train)
    train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    

    print(classes)

    # Mapeia cada classe para seus índices
    class_to_indices = {
        int(cls.item()): (y_train == cls).nonzero(as_tuple=True)[0].tolist()
        for cls in torch.unique(y_train)
    }

    reference_list = []
    total_batches = len(train_loader)

    for batch_idx in range(total_batches):
        start = batch_idx * batch_size
        end = min(start + batch_size, total_samples)
        batch_indices = set(range(start, end))

        class_samples = []
        for cls in classes:
            candidates = [i for i in class_to_indices[cls] if i not in batch_indices]
            if not candidates:
                raise ValueError(f"Classe {cls} não possui amostras fora do batch {batch_idx}")
            chosen = candidates[torch.randint(len(candidates), (1,)).item()]
            class_samples.append(chosen)

        reference_list.append(class_samples)


    return train_loader, reference_list

In [10]:
def normalize(t):
    t_norm = (t - t.mean()) / t.std()
    return t_norm

In [11]:
array_hidden_classes = [[0],[2],[3],[4],[5]]
filenames = ['0','2','3','4','5']
# array_hidden_classes = [[0]]
# filenames = ['0']
total_classes = len(labels_str)
for i in range(len(array_hidden_classes)):
    filename = f'{filenames[i]}_hidden'
    print(filename)
    hidden_classes = array_hidden_classes[i] #Classes ocultas do treinamento

    hidden_classes_index = list(train[train['Label'].isin(hidden_classes)].index)

    train_hidden = train.loc[hidden_classes_index]

    train_not_hidden = train.drop(hidden_classes_index)

    X_train = train_not_hidden.drop(columns=['Label'])
    y_train = train_not_hidden['Label']
    X_val = val.drop(columns=['Label'])
    y_val = val['Label']
    X_test = test.drop(columns=['Label'])
    y_test = test['Label']

    torch.manual_seed(123)
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(device)
    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_loader, pick_list = build_class_reference_batches(X_train,y_train, batch_size=512)
    pick_samples = []
    pick_labels = []
    for l in pick_list:
        pick_samples.append(X_train[l])
        pick_labels.append(y_train[l])

    pick_samples = torch.stack(pick_samples)    
    pick_labels = torch.stack(pick_labels)

    print('pick completo')

    neurons = total_classes - len(hidden_classes)
    print(f'{X_train.shape[1]} {neurons}')
    model = contrastive_ae(input_neurons=X_train.shape[1],neurons=neurons)
    model.to(device)

    learning_rate = 0.0001
    opt = optim.Adam(model.parameters(),lr=learning_rate)
    margin = 10 # Parametro de afastamento das classes
    cae_lambda_1 = 1.0 # Parametro de influencia na distancia das classes
    
    
    for epoch in range(250):
        running_loss = 0
        running_ael = 0
        running_cl = 0
        contador = 0
        for data in train_loader:
            inputs, labels = data
            inputs = inputs.to(device)
            labels = labels.to(device)
            ps = pick_samples[contador]
            pl = pick_labels[contador]
            ps = ps.to(device)
            pl = pl.to(device)
            contador += 1
            #print(f'{contador}/{len(train_loader)}')
            opt.zero_grad()
            outputs, encoded = model(inputs)
            _, pick_encoded = model(ps)
            tam_pe = pick_encoded.shape[0]
            enc_total = torch.cat((encoded,pick_encoded), dim=0)
            enc_total_norm = normalize(enc_total)
            encoded_norm = enc_total_norm[:-tam_pe]
            pick_encoded_norm = enc_total_norm[-tam_pe:]
            loss, ael, cl = AEContrastive(input=inputs, output=outputs, embeddings = encoded_norm, labels=labels, pick_encoded = pick_encoded_norm, pick_labels = pl, margin=margin, lambda1=cae_lambda_1)
            #loss = dummyMSELoss(inputs,outputs)
            loss.backward()
            opt.step()
            running_loss += loss.item()
            running_ael += ael.item()
            running_cl += cl.item()
            #print(f'loss = {loss.item()} batch_size = {size}')
        print(f'filename: {filename} Epoch {epoch+1} loss:{running_loss/len(train_loader)} ael:{running_ael/len(train_loader)} cl:{running_cl/len(train_loader)}')

    model_e = encoder(model=model)
    model_e.to(device)

    model_e.eval()

    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_encoded = model_e(X_train.to(device))

    train_encoded = train_encoded.detach().cpu().numpy()

    train_encoded_df = pd.DataFrame(train_encoded)
    train_encoded_df['Label'] = y_train.detach().cpu().numpy().astype(int)
    display(train_encoded_df)

    score = davies_bouldin_score(train_encoded_df.drop(columns=['Label']), train_encoded_df['Label'])
    print("Davies-Bouldin Score:", score)

    X_val = torch.tensor(np.array(X_val), dtype=torch.float)

    val_encoded = model_e(X_val.to(device))

    val_encoded = val_encoded.detach().cpu().numpy()

    val_encoded_df = pd.DataFrame(val_encoded)

    val_encoded_df['Label'] = y_val

    display(val_encoded_df)

    X_test = torch.tensor(np.array(X_test), dtype=torch.float)

    test_encoded = model_e(X_test.to(device))

    test_encoded = test_encoded.detach().cpu().numpy()

    test_encoded_df = pd.DataFrame(test_encoded)

    test_encoded_df['Label'] = y_test

    display(test_encoded_df)

    train_encoded_df.to_csv(f'train_encoded_CADE_cod_joined_attacks_pick_class_squared_normalized_{filename}.csv',index=False)
    val_encoded_df.to_csv(f'val_encoded_CADE_cod_joined_attacks_pick_class_squared_normalized_{filename}.csv',index=False)
    test_encoded_df.to_csv(f'test_encoded_CADE_cod_joined_attacks_pick_class_squared_normalized_{filename}.csv',index=False)

0_hidden
cuda
[1.0, 2.0, 3.0, 4.0, 5.0]
pick completo
82 5
filename: 0_hidden Epoch 1 loss:36.66079628261116 ael:0.028509390227229568 cl:36.6322869021615
filename: 0_hidden Epoch 2 loss:30.694707895832778 ael:0.01753701650407398 cl:30.677170902118537
filename: 0_hidden Epoch 3 loss:30.01515641828914 ael:0.017441102261930717 cl:29.997715300530423
filename: 0_hidden Epoch 4 loss:29.471845354901365 ael:0.016938386875438416 cl:29.45490697521958
filename: 0_hidden Epoch 5 loss:28.991102726383648 ael:0.016045884436286725 cl:28.97505681379351
filename: 0_hidden Epoch 6 loss:28.623722558822355 ael:0.015482432378491255 cl:28.6082401229545
filename: 0_hidden Epoch 7 loss:28.346569040538895 ael:0.015017922065981059 cl:28.33155111127739
filename: 0_hidden Epoch 8 loss:28.12438474064434 ael:0.014380771299562313 cl:28.110003972600843
filename: 0_hidden Epoch 9 loss:27.975184663764132 ael:0.013924302094050751 cl:27.961260358124456
filename: 0_hidden Epoch 10 loss:27.846286585481714 ael:0.01382462572954532 cl:27.832461949754425
filename: 0_hidden Epoch 11 loss:27.75291432039996 ael:0.013769444488919147 cl:27.7391448633545
filename: 0_hidden Epoch 12 loss:27.704393608839915 ael:0.013710303867083497 cl:27.690683303415128
filename: 0_hidden Epoch 13 loss:27.66102488406762 ael:0.013801953501765328 cl:27.647222943715015
filename: 0_hidden Epoch 14 loss:27.596483073117412 ael:0.013701092412802561 cl:27.5827819910253
filename: 0_hidden Epoch 15 loss:27.547208433423943 ael:0.013575378527089899 cl:27.53363305351881
filename: 0_hidden Epoch 16 loss:27.5060060672399 ael:0.013531000411533272 cl:27.492475049513942
filename: 0_hidden Epoch 17 loss:27.46534868195035 ael:0.013476544646812551 cl:27.451872150023235
filename: 0_hidden Epoch 18 loss:27.438810903892563 ael:0.013441331974525895 cl:27.425369584555593
filename: 0_hidden Epoch 19 loss:27.40096479224621 ael:0.013464282947940135 cl:27.38750048947344
filename: 0_hidden Epoch 20 loss:27.371140460453347 ael:0.013456761678722036 cl:27.35768367569148
filename: 0_hidden Epoch 21 loss:27.33431736596208 ael:0.013453914670620985 cl:27.320863449520704
filename: 0_hidden Epoch 22 loss:27.292718195982438 ael:0.013518277340783523 cl:27.279199939747755
filename: 0_hidden Epoch 23 loss:27.246333661119735 ael:0.013533230985736491 cl:27.232800403430584
filename: 0_hidden Epoch 24 loss:27.202301871138044 ael:0.01357319959009121 cl:27.18872867435205
filename: 0_hidden Epoch 25 loss:27.168000481275605 ael:0.013551963563742919 cl:27.154448492700805
filename: 0_hidden Epoch 26 loss:27.14167995429836 ael:0.013554732589050378 cl:27.128125216468323
filename: 0_hidden Epoch 27 loss:27.116288438997486 ael:0.013533789298804331 cl:27.102754656653033
filename: 0_hidden Epoch 28 loss:27.09484997709768 ael:0.013514600536646115 cl:27.08133537347788
filename: 0_hidden Epoch 29 loss:27.07145880577404 ael:0.013493187002390564 cl:27.057965633132696
filename: 0_hidden Epoch 30 loss:27.029418201730753 ael:0.013488332219226823 cl:27.015929857761783
filename: 0_hidden Epoch 31 loss:26.98970445394036 ael:0.013461291984674842 cl:26.97624317619333
filename: 0_hidden Epoch 32 loss:26.971606622911775 ael:0.013442862841915421 cl:26.95816375111746
filename: 0_hidden Epoch 33 loss:26.939182178560305 ael:0.013421977082124123 cl:26.925760194653233
filename: 0_hidden Epoch 34 loss:26.911226284105453 ael:0.013403675692966879 cl:26.897822627798472
filename: 0_hidden Epoch 35 loss:26.890017463754752 ael:0.013390514283976246 cl:26.876626943802574
filename: 0_hidden Epoch 36 loss:26.87841327527431 ael:0.013375122992804201 cl:26.865038157757663
filename: 0_hidden Epoch 37 loss:26.863195150454487 ael:0.013336759877919647 cl:26.84985839269164
filename: 0_hidden Epoch 38 loss:26.832553462544325 ael:0.013332695492434132 cl:26.81922076452273
filename: 0_hidden Epoch 39 loss:26.8161958109886 ael:0.013301689474439481 cl:26.80289413369187
filename: 0_hidden Epoch 40 loss:26.795487898950658 ael:0.013289742282037768 cl:26.78219815737002
filename: 0_hidden Epoch 41 loss:26.776095666474408 ael:0.013273713615900367 cl:26.76282195875926
filename: 0_hidden Epoch 42 loss:26.761952004987677 ael:0.013235143252674294 cl:26.74871686135767
filename: 0_hidden Epoch 43 loss:26.7427349405523 ael:0.013203974589300381 cl:26.729530961293634
filename: 0_hidden Epoch 44 loss:26.731159061949626 ael:0.013236891927645421 cl:26.717922160762768
filename: 0_hidden Epoch 45 loss:26.71537366107352 ael:0.013193752659027898 cl:26.702179892236938
filename: 0_hidden Epoch 46 loss:26.69016146650249 ael:0.013147328118709273 cl:26.67701413695773
filename: 0_hidden Epoch 47 loss:26.687464154443575 ael:0.013174621504590821 cl:26.674289512864725
filename: 0_hidden Epoch 48 loss:26.670479882401995 ael:0.013105845065323087 cl:26.657374051324886
filename: 0_hidden Epoch 49 loss:26.66068400407193 ael:0.013044432504383897 cl:26.64763956534685
filename: 0_hidden Epoch 50 loss:26.630519351506013 ael:0.01302825700247115 cl:26.617491099510854
filename: 0_hidden Epoch 51 loss:26.61938721376036 ael:0.01296676213819679 cl:26.606420466269018
filename: 0_hidden Epoch 52 loss:26.607767877106316 ael:0.012966179793780843 cl:26.594801700360055
filename: 0_hidden Epoch 53 loss:26.588846173634032 ael:0.012920337494731286 cl:26.575925834708
filename: 0_hidden Epoch 54 loss:26.57325567874609 ael:0.012861178936590554 cl:26.560394507572145
filename: 0_hidden Epoch 55 loss:26.554833449426315 ael:0.012774047932759726 cl:26.542059398686458
filename: 0_hidden Epoch 56 loss:26.547074758473588 ael:0.012773665541387641 cl:26.53430108874256
filename: 0_hidden Epoch 57 loss:26.528400812137527 ael:0.012711803580360862 cl:26.515689029455473
filename: 0_hidden Epoch 58 loss:26.512816928060026 ael:0.012683967135897626 cl:26.5001329751539
filename: 0_hidden Epoch 59 loss:26.498568770293023 ael:0.012666564220596335 cl:26.485902192464913
filename: 0_hidden Epoch 60 loss:26.475938220106688 ael:0.012569459692315857 cl:26.463368721177297
filename: 0_hidden Epoch 61 loss:26.45844411216241 ael:0.012515508166566472 cl:26.445928598957778
filename: 0_hidden Epoch 62 loss:26.441295163649684 ael:0.012503363618171844 cl:26.428791802783095
filename: 0_hidden Epoch 63 loss:26.418835281605592 ael:0.012537089980646602 cl:26.406298227575196
filename: 0_hidden Epoch 64 loss:26.407880160869055 ael:0.012512476609939536 cl:26.395367684212605
filename: 0_hidden Epoch 65 loss:26.380628553552587 ael:0.012488524656423243 cl:26.368140020535638
filename: 0_hidden Epoch 66 loss:26.3580338919398 ael:0.012441661893763323 cl:26.345592226849607
filename: 0_hidden Epoch 67 loss:26.34476366477103 ael:0.012447679499363016 cl:26.33231598726934
filename: 0_hidden Epoch 68 loss:26.31988759142614 ael:0.01240582496791994 cl:26.307481758833603
filename: 0_hidden Epoch 69 loss:26.299749969715943 ael:0.012440058478483187 cl:26.287309906245525
filename: 0_hidden Epoch 70 loss:26.27503876411478 ael:0.012426499674937632 cl:26.262612253343487
filename: 0_hidden Epoch 71 loss:26.263072292314053 ael:0.012517211511296056 cl:26.250555065337853
filename: 0_hidden Epoch 72 loss:26.243606057322605 ael:0.012491629338938407 cl:26.23111441478199
filename: 0_hidden Epoch 73 loss:26.22718138662116 ael:0.012463281911573148 cl:26.214718109266055
filename: 0_hidden Epoch 74 loss:26.208985518026488 ael:0.012485958662437686 cl:26.196499564500762
filename: 0_hidden Epoch 75 loss:26.192675257516495 ael:0.012397388696964594 cl:26.18027787702102
filename: 0_hidden Epoch 76 loss:26.17815434735867 ael:0.012580177912873412 cl:26.165574162514325
filename: 0_hidden Epoch 77 loss:26.157114981452736 ael:0.012507633219067603 cl:26.144607361122528
filename: 0_hidden Epoch 78 loss:26.144687135614216 ael:0.012422207201314558 cl:26.13226492886
filename: 0_hidden Epoch 79 loss:26.144867802165567 ael:0.01249755856791452 cl:26.132370251683618
filename: 0_hidden Epoch 80 loss:26.117237976756346 ael:0.012465553505228403 cl:26.10477243255234
filename: 0_hidden Epoch 81 loss:26.102417224172715 ael:0.012532980113762476 cl:26.089884246783154
filename: 0_hidden Epoch 82 loss:26.089483003005643 ael:0.012470755780485551 cl:26.07701223759799
filename: 0_hidden Epoch 83 loss:26.060254048206517 ael:0.012502925530484113 cl:26.047751112134044
filename: 0_hidden Epoch 84 loss:26.04263380559951 ael:0.012460972646051028 cl:26.03017282812431
filename: 0_hidden Epoch 85 loss:26.028340121886444 ael:0.012480817548405533 cl:26.015859290471347
filename: 0_hidden Epoch 86 loss:26.01716135357639 ael:0.012462945403684976 cl:26.00469841267666
filename: 0_hidden Epoch 87 loss:26.00268873167864 ael:0.012440933108530816 cl:25.990247797879586
filename: 0_hidden Epoch 88 loss:25.982336218684516 ael:0.01245716664838097 cl:25.969879053602092
filename: 0_hidden Epoch 89 loss:25.96671117566739 ael:0.012375029321929475 cl:25.95433615639572
filename: 0_hidden Epoch 90 loss:25.95344347345027 ael:0.012331195534598886 cl:25.941112264048606
filename: 0_hidden Epoch 91 loss:25.929244244621973 ael:0.01235231444647703 cl:25.916891933783763
filename: 0_hidden Epoch 92 loss:25.93251616715713 ael:0.012289801698014519 cl:25.920226360202747
filename: 0_hidden Epoch 93 loss:25.904839586741108 ael:0.012303492000331765 cl:25.892536094963575
filename: 0_hidden Epoch 94 loss:25.901875478626977 ael:0.012249456252715207 cl:25.88962603018642
filename: 0_hidden Epoch 95 loss:25.89222058047703 ael:0.01229448013601767 cl:25.879926096178377
filename: 0_hidden Epoch 96 loss:25.882899075038384 ael:0.012290183283340604 cl:25.870608896293135
filename: 0_hidden Epoch 97 loss:25.867635854443762 ael:0.012263435308539815 cl:25.85537242313282
filename: 0_hidden Epoch 98 loss:25.859685759557816 ael:0.01217067385174145 cl:25.847515111578314
filename: 0_hidden Epoch 99 loss:25.85113745392497 ael:0.01211500362512977 cl:25.83902245627936
filename: 0_hidden Epoch 100 loss:25.831843722217084 ael:0.01216020203745754 cl:25.819683500513452
filename: 0_hidden Epoch 101 loss:25.82758973483064 ael:0.012131586728637803 cl:25.81545813564711
filename: 0_hidden Epoch 102 loss:25.82061788318525 ael:0.012107944390929687 cl:25.808509938811948
filename: 0_hidden Epoch 103 loss:25.80200300934907 ael:0.01202318539668176 cl:25.789979818699777
filename: 0_hidden Epoch 104 loss:25.800495673128545 ael:0.012079294399627264 cl:25.788416359725137
filename: 0_hidden Epoch 105 loss:25.808040245569284 ael:0.01198823497778062 cl:25.796052017089007
filename: 0_hidden Epoch 106 loss:25.789888116173625 ael:0.011967305700132264 cl:25.77792081245241
filename: 0_hidden Epoch 107 loss:25.787924161612196 ael:0.01194498960777931 cl:25.77597916764787
filename: 0_hidden Epoch 108 loss:25.773817119221988 ael:0.011896012504324408 cl:25.761921115618676
filename: 0_hidden Epoch 109 loss:25.751807118729626 ael:0.011893709610654037 cl:25.73991342499234
filename: 0_hidden Epoch 110 loss:25.762704691001595 ael:0.011857972454851283 cl:25.750846723755473
filename: 0_hidden Epoch 111 loss:25.75281298895109 ael:0.01182779805015351 cl:25.740985186696292
filename: 0_hidden Epoch 112 loss:25.752323923406706 ael:0.011797896518844225 cl:25.74052602266334
filename: 0_hidden Epoch 113 loss:25.753558250669986 ael:0.011838624640201014 cl:25.74171963421702
filename: 0_hidden Epoch 114 loss:25.73155125523113 ael:0.011839419099615915 cl:25.719711831438893
filename: 0_hidden Epoch 115 loss:25.72145056599722 ael:0.011849936360040956 cl:25.709600646794442
filename: 0_hidden Epoch 116 loss:25.71637343669005 ael:0.011725191852476176 cl:25.704648257934227
filename: 0_hidden Epoch 117 loss:25.719573315525555 ael:0.011769449506727645 cl:25.70780385601583
filename: 0_hidden Epoch 118 loss:25.705076827572757 ael:0.01176016882626078 cl:25.693316662834864
filename: 0_hidden Epoch 119 loss:25.69418907011895 ael:0.011715995150824924 cl:25.682473091650913
filename: 0_hidden Epoch 120 loss:25.69320023928829 ael:0.011675988943242902 cl:25.681524255224836
filename: 0_hidden Epoch 121 loss:25.69704391703796 ael:0.011655577830145113 cl:25.685388343832543
filename: 0_hidden Epoch 122 loss:25.680374880639768 ael:0.011611082400951087 cl:25.66876378483797
filename: 0_hidden Epoch 123 loss:25.67600031932227 ael:0.011648308488371941 cl:25.66435199757521
filename: 0_hidden Epoch 124 loss:25.67420303922385 ael:0.011652621925942392 cl:25.662550418068697
filename: 0_hidden Epoch 125 loss:25.668480296601608 ael:0.011621095965520009 cl:25.65685921007234
filename: 0_hidden Epoch 126 loss:25.66128255588318 ael:0.011632545783281614 cl:25.649650020653137
filename: 0_hidden Epoch 127 loss:25.65021330456651 ael:0.011612249156096339 cl:25.638601051911298
filename: 0_hidden Epoch 128 loss:25.64270987109316 ael:0.011646306593431684 cl:25.63106355732408
filename: 0_hidden Epoch 129 loss:25.64726915255795 ael:0.01158877817424036 cl:25.635680368049368
filename: 0_hidden Epoch 130 loss:25.64221261385896 ael:0.011540997417083297 cl:25.63067161600003
filename: 0_hidden Epoch 131 loss:25.638245685898486 ael:0.01154470301195349 cl:25.626700983957758
filename: 0_hidden Epoch 132 loss:25.62979758251496 ael:0.011519352217181238 cl:25.618278212284206
filename: 0_hidden Epoch 133 loss:25.63335576251395 ael:0.011490574397635806 cl:25.62186517765385
filename: 0_hidden Epoch 134 loss:25.60408682176004 ael:0.011476797068606352 cl:25.592610015438968
filename: 0_hidden Epoch 135 loss:25.607939994772067 ael:0.01153860764635747 cl:25.59640138052281
filename: 0_hidden Epoch 136 loss:25.625255517886618 ael:0.011462748173715797 cl:25.61379276817958
filename: 0_hidden Epoch 137 loss:25.59769801962918 ael:0.011462041802113208 cl:25.586236005822258
filename: 0_hidden Epoch 138 loss:25.601832897203177 ael:0.01142849840307807 cl:25.590404406796047
filename: 0_hidden Epoch 139 loss:25.586126106283714 ael:0.01143847037807401 cl:25.57468762284462
filename: 0_hidden Epoch 140 loss:25.603693043758348 ael:0.011408299648780953 cl:25.592284722237927
filename: 0_hidden Epoch 141 loss:25.581384642682053 ael:0.011333557460539604 cl:25.570051069563068
filename: 0_hidden Epoch 142 loss:25.5843664246896 ael:0.011490433254443107 cl:25.57287597886699
filename: 0_hidden Epoch 143 loss:25.578284264763084 ael:0.011280412552409412 cl:25.567003866956927
filename: 0_hidden Epoch 144 loss:25.566561031764042 ael:0.0113374395986124 cl:25.55522363088902
filename: 0_hidden Epoch 145 loss:25.56993603178248 ael:0.0113479335737226 cl:25.558588083261835
filename: 0_hidden Epoch 146 loss:25.571134484299144 ael:0.011222467494830699 cl:25.559912023648014
filename: 0_hidden Epoch 147 loss:25.557978257890962 ael:0.01129311365587393 cl:25.546685138538006
filename: 0_hidden Epoch 148 loss:25.551752719579568 ael:0.01130943971397629 cl:25.540443297504083
filename: 0_hidden Epoch 149 loss:25.56910768018055 ael:0.011338065794331146 cl:25.557769602553957
filename: 0_hidden Epoch 150 loss:25.551194845069766 ael:0.011223772655462863 cl:25.539971096977514
filename: 0_hidden Epoch 151 loss:25.54827867877421 ael:0.011273006111926553 cl:25.537005674536555
filename: 0_hidden Epoch 152 loss:25.550734714687806 ael:0.01118787267611805 cl:25.53954683596503
filename: 0_hidden Epoch 153 loss:25.56005913376856 ael:0.011283799061837501 cl:25.54877531840539
filename: 0_hidden Epoch 154 loss:25.535270156276546 ael:0.011250999680391324 cl:25.52401914838529
filename: 0_hidden Epoch 155 loss:25.52785068455119 ael:0.011204325157790428 cl:25.516646341791663
filename: 0_hidden Epoch 156 loss:25.530008743138644 ael:0.011321874392795386 cl:25.518686872982375
filename: 0_hidden Epoch 157 loss:25.525234148668464 ael:0.011155725885865263 cl:25.514078416029292
filename: 0_hidden Epoch 158 loss:25.53347510231439 ael:0.011204709075361287 cl:25.522270397750113
filename: 0_hidden Epoch 159 loss:25.514336046364054 ael:0.011154231245536094 cl:25.503181805497352
filename: 0_hidden Epoch 160 loss:25.521980499193834 ael:0.011205237152139674 cl:25.510775273046903
filename: 0_hidden Epoch 161 loss:25.514046362893406 ael:0.011219790029072061 cl:25.502826557013474
filename: 0_hidden Epoch 162 loss:25.507840167693537 ael:0.011197502166707934 cl:25.49664265620723
filename: 0_hidden Epoch 163 loss:25.506797743669402 ael:0.011153976512495976 cl:25.495643771659736
filename: 0_hidden Epoch 164 loss:25.501932173355232 ael:0.011112806314480219 cl:25.490819377184778
filename: 0_hidden Epoch 165 loss:25.501102359171025 ael:0.01120243698397544 cl:25.489899909165036
filename: 0_hidden Epoch 166 loss:25.4936414389086 ael:0.011082273417730461 cl:25.48255915647546
filename: 0_hidden Epoch 167 loss:25.48683553965304 ael:0.011160780658080507 cl:25.475674769401166
filename: 0_hidden Epoch 168 loss:25.484593583843278 ael:0.011256838837384193 cl:25.47333673330454
filename: 0_hidden Epoch 169 loss:25.485822412596082 ael:0.011147911341930656 cl:25.474674496783205
filename: 0_hidden Epoch 170 loss:25.483457787306712 ael:0.01120913112697357 cl:25.47224865889194
filename: 0_hidden Epoch 171 loss:25.474803158702073 ael:0.011130859297439547 cl:25.463672306093052
filename: 0_hidden Epoch 172 loss:25.47072473111961 ael:0.0111045965514522 cl:25.45962014584305
filename: 0_hidden Epoch 173 loss:25.466990289983855 ael:0.011108878374315777 cl:25.45588139224043
filename: 0_hidden Epoch 174 loss:25.478472892862627 ael:0.0111766951833786 cl:25.46729619321543
filename: 0_hidden Epoch 175 loss:25.46096456391745 ael:0.011160857494255851 cl:25.449803713008468
filename: 0_hidden Epoch 176 loss:25.465270658102046 ael:0.011081107822331243 cl:25.45418953636314
filename: 0_hidden Epoch 177 loss:25.46089632416079 ael:0.011068653661879233 cl:25.449827688910815
filename: 0_hidden Epoch 178 loss:25.44639653925256 ael:0.01128091922002097 cl:25.435115616791105
filename: 0_hidden Epoch 179 loss:25.466816813437823 ael:0.011477752991149706 cl:25.45533904153591
filename: 0_hidden Epoch 180 loss:25.444235959554266 ael:0.011353620257869249 cl:25.432882354281574
filename: 0_hidden Epoch 181 loss:25.441953398650373 ael:0.01108015235175877 cl:25.43087324863761
filename: 0_hidden Epoch 182 loss:25.445221375132395 ael:0.011106897690125257 cl:25.43411447538083
filename: 0_hidden Epoch 183 loss:25.437056817597455 ael:0.01132359486928437 cl:25.425733229828804
filename: 0_hidden Epoch 184 loss:25.441268933957208 ael:0.011100447733679871 cl:25.430168479861052
filename: 0_hidden Epoch 185 loss:25.440202151485572 ael:0.011106331677048907 cl:25.429095831697044
filename: 0_hidden Epoch 186 loss:25.430143579858665 ael:0.01115466015952768 cl:25.41898891573417
filename: 0_hidden Epoch 187 loss:25.4400334168095 ael:0.011282788975178547 cl:25.428750642307143
filename: 0_hidden Epoch 188 loss:25.426102457342253 ael:0.0112013708161692 cl:25.414901096591343
filename: 0_hidden Epoch 189 loss:25.43553875321301 ael:0.011231473275354155 cl:25.42430727279239
filename: 0_hidden Epoch 190 loss:25.41673422301435 ael:0.011272028655314873 cl:25.40546221892487
filename: 0_hidden Epoch 191 loss:25.425278127073426 ael:0.011167310649754897 cl:25.41411081898659
filename: 0_hidden Epoch 192 loss:25.40943597815856 ael:0.011207579644835744 cl:25.39822841295541
filename: 0_hidden Epoch 193 loss:25.400136157192147 ael:0.011094445935433616 cl:25.389041713971167
filename: 0_hidden Epoch 194 loss:25.40452934799778 ael:0.011218744578035763 cl:25.39331059066029
filename: 0_hidden Epoch 195 loss:25.394577178463454 ael:0.011174132175401507 cl:25.38340304832136
filename: 0_hidden Epoch 196 loss:25.401245852319455 ael:0.011134187301956162 cl:25.39011167356481
filename: 0_hidden Epoch 197 loss:25.39731534680579 ael:0.011264104209690266 cl:25.386051252490322
filename: 0_hidden Epoch 198 loss:25.397353053621067 ael:0.011217789544055912 cl:25.386135261864418
filename: 0_hidden Epoch 199 loss:25.391367330409036 ael:0.011129219885022829 cl:25.380238111682637
filename: 0_hidden Epoch 200 loss:25.39071238545031 ael:0.01123313992829979 cl:25.379479247334018
filename: 0_hidden Epoch 201 loss:25.394402194781694 ael:0.011209224141080967 cl:25.38319295728778
filename: 0_hidden Epoch 202 loss:25.378459303598945 ael:0.011006879964952166 cl:25.367452434796363

C:\Users\linco\AppData\Local\Temp\ipykernel_38868\726915545.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
C:\Users\linco\AppData\Local\Temp\ipykernel_38868\726915545.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3         4  Label
0       -0.056876 -0.058695 -0.066288 -0.054355 -0.049887      1
1       -0.039527 -0.049560 -0.047279 -0.039025 -0.053211      2
2       -0.054719 -0.058096 -0.066181 -0.052889 -0.049440      1
3       -0.067235 -0.062746 -0.041639 -0.058062 -0.079823      4
4       -0.039529 -0.049560 -0.047284 -0.039032 -0.053210      2
...           ...       ...       ...       ...       ...    ...
1270932 -0.056106 -0.039502 -0.043716 -0.068137 -0.039419      3
1270933 -0.039526 -0.049560 -0.047276 -0.039021 -0.053211      2
1270934 -0.039526 -0.049560 -0.047278 -0.039023 -0.053211      2
1270935 -0.039526 -0.049560 -0.047277 -0.039022 -0.053211      2
1270936 -0.039484 -0.049566 -0.047176 -0.038878 -0.053227      2

[1270937 rows x 6 columns]

Davies-Bouldin Score: 0.42706652143618723

               0         1         2         3         4  Label
0      -0.057158 -0.058714 -0.067022 -0.054915 -0.049446    0.0
1      -0.039530 -0.049561 -0.047285 -0.039031 -0.053211    2.0
2      -0.056584 -0.058587 -0.066772 -0.054367 -0.049437    1.0
3      -0.056683 -0.039186 -0.043751 -0.069169 -0.038851    3.0
4      -0.056084 -0.058378 -0.065573 -0.053539 -0.050079    1.0
...          ...       ...       ...       ...       ...    ...
519951 -0.057205 -0.059297 -0.067697 -0.054504 -0.049743    2.0
519952 -0.065364 -0.060277 -0.041019 -0.058997 -0.077670    1.0
519953 -0.054702 -0.057364 -0.059966 -0.051848 -0.053948    3.0
519954 -0.056686 -0.058989 -0.066424 -0.053864 -0.050219    0.0
519955 -0.056106 -0.039502 -0.043716 -0.068137 -0.039419    0.0

[519956 rows x 6 columns]

               0         1         2         3         4  Label
0      -0.054664 -0.057356 -0.059961 -0.051794 -0.053932    0.0
1      -0.057272 -0.058869 -0.067210 -0.054924 -0.049517    0.0
2      -0.055428 -0.058185 -0.066316 -0.053363 -0.049285    1.0
3      -0.054406 -0.056841 -0.062575 -0.052534 -0.050330    1.0
4      -0.051619 -0.047852 -0.053332 -0.057087 -0.045315    NaN
...          ...       ...       ...       ...       ...    ...
649942 -0.056213 -0.058523 -0.065786 -0.053591 -0.050103    3.0
649943 -0.051295 -0.046767 -0.051944 -0.057934 -0.045340    1.0
649944 -0.051372 -0.047080 -0.052169 -0.057649 -0.045530    0.0
649945 -0.056592 -0.039794 -0.044681 -0.068662 -0.039024    4.0
649946 -0.040456 -0.051043 -0.048988 -0.038669 -0.053834    0.0

[649947 rows x 6 columns]

2_hidden
cuda
[0.0, 1.0, 3.0, 4.0, 5.0]
pick completo
82 5
filename: 2_hidden Epoch 1 loss:33.308468532004554 ael:0.02510401504985683 cl:33.28336449617531
filename: 2_hidden Epoch 2 loss:29.827054394058315 ael:0.01758231140662268 cl:29.809472091295564
filename: 2_hidden Epoch 3 loss:28.971749136182996 ael:0.017085365281162553 cl:28.95466374793248
filename: 2_hidden Epoch 4 loss:28.422957384098343 ael:0.016562346034078745 cl:28.40639502095897
filename: 2_hidden Epoch 5 loss:27.984553402348567 ael:0.016334887271017184 cl:27.96821852566903
filename: 2_hidden Epoch 6 loss:27.63004721033643 ael:0.016027694517931745 cl:27.614019516058136
filename: 2_hidden Epoch 7 loss:27.37298664238021 ael:0.015554998119563212 cl:27.357431621997677
filename: 2_hidden Epoch 8 loss:27.163580320034807 ael:0.015136348750790831 cl:27.1484439911201
filename: 2_hidden Epoch 9 loss:26.9869563604656 ael:0.014892538444939674 cl:26.97206381691827
filename: 2_hidden Epoch 10 loss:26.8396393000731 ael:0.014727459049222675 cl:26.82491184870402
filename: 2_hidden Epoch 11 loss:26.700101613161856 ael:0.014579053352211128 cl:26.685522563555086
filename: 2_hidden Epoch 12 loss:26.559703000386556 ael:0.014449638680266271 cl:26.545253362153705
filename: 2_hidden Epoch 13 loss:26.409851821542482 ael:0.014348720510528363 cl:26.395503106033594
filename: 2_hidden Epoch 14 loss:26.24180090775964 ael:0.014322957602650887 cl:26.22747795038056
filename: 2_hidden Epoch 15 loss:26.105599878545394 ael:0.014329671393262975 cl:26.091270239311353
filename: 2_hidden Epoch 16 loss:25.977149497695834 ael:0.014335099028216468 cl:25.96281440578706
filename: 2_hidden Epoch 17 loss:25.864885104887666 ael:0.014353953401302124 cl:25.850531153093304
filename: 2_hidden Epoch 18 loss:25.768581948642844 ael:0.01434315837489452 cl:25.754238779503
filename: 2_hidden Epoch 19 loss:25.681123219874866 ael:0.014336078889580847 cl:25.66678713134855
filename: 2_hidden Epoch 20 loss:25.59522274530422 ael:0.01432860317879645 cl:25.580894153996518
filename: 2_hidden Epoch 21 loss:25.524638155887 ael:0.014296732673269004 cl:25.51034143180178
filename: 2_hidden Epoch 22 loss:25.455368533887363 ael:0.014246059895073722 cl:25.44112246663947
filename: 2_hidden Epoch 23 loss:25.399065357899804 ael:0.014204495377860397 cl:25.384860866948177
filename: 2_hidden Epoch 24 loss:25.338216235066017 ael:0.014143098286510995 cl:25.32407312058566
filename: 2_hidden Epoch 25 loss:25.282455507914225 ael:0.01407847366627981 cl:25.268377045302362
filename: 2_hidden Epoch 26 loss:25.23342785026595 ael:0.014009198932554465 cl:25.21941865229467
filename: 2_hidden Epoch 27 loss:25.164297858455726 ael:0.013953278758100164 cl:25.150344576473124
filename: 2_hidden Epoch 28 loss:25.109335430881433 ael:0.0139042401163463 cl:25.09543120066325
filename: 2_hidden Epoch 29 loss:25.059040772845172 ael:0.013860812007139126 cl:25.045179967155235
filename: 2_hidden Epoch 30 loss:25.000840197669135 ael:0.013840725933806154 cl:24.986999454832915
filename: 2_hidden Epoch 31 loss:24.947731959471227 ael:0.013825077542828189 cl:24.93390686525936
filename: 2_hidden Epoch 32 loss:24.894510421976012 ael:0.013831148110874738 cl:24.8806793000963
filename: 2_hidden Epoch 33 loss:24.83166089253119 ael:0.013818561690124243 cl:24.817842327921014
filename: 2_hidden Epoch 34 loss:24.769257454565395 ael:0.013844241309987262 cl:24.755413214365642
filename: 2_hidden Epoch 35 loss:24.71721957301536 ael:0.013868246647414931 cl:24.70335132978116
filename: 2_hidden Epoch 36 loss:24.66167260052865 ael:0.013862466585838742 cl:24.64781013678389
filename: 2_hidden Epoch 37 loss:24.624934455804656 ael:0.013854196428304964 cl:24.611080256121898
filename: 2_hidden Epoch 38 loss:24.58425435685275 ael:0.01383667241847306 cl:24.57041770589282
filename: 2_hidden Epoch 39 loss:24.550959005411606 ael:0.013829629789024854 cl:24.537129372044614
filename: 2_hidden Epoch 40 loss:24.520505457314833 ael:0.013843522860249232 cl:24.506661928188034
filename: 2_hidden Epoch 41 loss:24.48956967348244 ael:0.013836499073199535 cl:24.475733165852507
filename: 2_hidden Epoch 42 loss:24.461301469524006 ael:0.013827115484671287 cl:24.4474743631151
filename: 2_hidden Epoch 43 loss:24.438976586213585 ael:0.013839033778419184 cl:24.425137540471486
filename: 2_hidden Epoch 44 loss:24.410993422123425 ael:0.01383529606286153 cl:24.397158114115395
filename: 2_hidden Epoch 45 loss:24.38567777377123 ael:0.013852828447788693 cl:24.371824961099012
filename: 2_hidden Epoch 46 loss:24.37516142861885 ael:0.013846039886134323 cl:24.36131540209229
filename: 2_hidden Epoch 47 loss:24.35090977016248 ael:0.013840575858798118 cl:24.337069174002487
filename: 2_hidden Epoch 48 loss:24.353860213184916 ael:0.013841013335867932 cl:24.340019209900795
filename: 2_hidden Epoch 49 loss:24.345308867672035 ael:0.013842294245892972 cl:24.331466585014297
filename: 2_hidden Epoch 50 loss:24.298239778217518 ael:0.013787907319230555 cl:24.28445185834204
filename: 2_hidden Epoch 51 loss:24.285867717809843 ael:0.013789892185762612 cl:24.272077820314998
filename: 2_hidden Epoch 52 loss:24.267625481901113 ael:0.013782873119592493 cl:24.253842601999203
filename: 2_hidden Epoch 53 loss:24.250522755182278 ael:0.01379392463741116 cl:24.23672882213927
filename: 2_hidden Epoch 54 loss:24.235064387182046 ael:0.01379143092645147 cl:24.221272944288643
filename: 2_hidden Epoch 55 loss:24.221353868294877 ael:0.013795837793466553 cl:24.207558028460944
filename: 2_hidden Epoch 56 loss:24.199500668397423 ael:0.013766349368450934 cl:24.18573431606181
filename: 2_hidden Epoch 57 loss:24.175310787959404 ael:0.013758914211862965 cl:24.161551877071982
filename: 2_hidden Epoch 58 loss:24.1682254690873 ael:0.013766507951989334 cl:24.15445894999811
filename: 2_hidden Epoch 59 loss:24.151941190128436 ael:0.013760812023425835 cl:24.138180381373356
filename: 2_hidden Epoch 60 loss:24.14184860709118 ael:0.013765183154068756 cl:24.128083418126693
filename: 2_hidden Epoch 61 loss:24.124585320099055 ael:0.01373099505068048 cl:24.110854339041904
filename: 2_hidden Epoch 62 loss:24.121098036515086 ael:0.013729593290658723 cl:24.10736843633373
filename: 2_hidden Epoch 63 loss:24.092536161656966 ael:0.013722334718821864 cl:24.078813840631852
filename: 2_hidden Epoch 64 loss:24.07826750236645 ael:0.013722227477299714 cl:24.064545257746826
filename: 2_hidden Epoch 65 loss:24.074578241716353 ael:0.013711331878674396 cl:24.060866923081246
filename: 2_hidden Epoch 66 loss:24.065921317206488 ael:0.01368074336209013 cl:24.05224058251632
filename: 2_hidden Epoch 67 loss:24.04959225124783 ael:0.013661424808302208 cl:24.035930829856827
filename: 2_hidden Epoch 68 loss:24.046756590458386 ael:0.01365693065539351 cl:24.033099658029123
filename: 2_hidden Epoch 69 loss:24.02841147205286 ael:0.013629284705857784 cl:24.014782181120754
filename: 2_hidden Epoch 70 loss:24.022595255556162 ael:0.01362688341178 cl:24.008968383387515
filename: 2_hidden Epoch 71 loss:24.025354721671658 ael:0.013630626609069649 cl:24.011724107307302
filename: 2_hidden Epoch 72 loss:24.000177745930632 ael:0.013605285817158152 cl:23.98657245970609
filename: 2_hidden Epoch 73 loss:24.00409380427578 ael:0.01359265250867309 cl:23.990501156745598
filename: 2_hidden Epoch 74 loss:23.996376537858396 ael:0.013600606703858452 cl:23.982775922964887
filename: 2_hidden Epoch 75 loss:23.992167623419512 ael:0.013562742667545003 cl:23.978604867723252
filename: 2_hidden Epoch 76 loss:23.972569102014017 ael:0.013557570604934243 cl:23.95901153687148
filename: 2_hidden Epoch 77 loss:23.98036580448262 ael:0.013524975191954284 cl:23.966840823770266
filename: 2_hidden Epoch 78 loss:23.952848450621666 ael:0.01357938038533804 cl:23.93926907812643
filename: 2_hidden Epoch 79 loss:23.957661461969565 ael:0.01354485674930072 cl:23.944116610253765
filename: 2_hidden Epoch 80 loss:23.951128289852925 ael:0.013544714858766361 cl:23.93758357198615
filename: 2_hidden Epoch 81 loss:23.944980263849448 ael:0.013480950722863016 cl:23.931499307755143
filename: 2_hidden Epoch 82 loss:23.938167102992185 ael:0.013531973991510376 cl:23.92463512866818
filename: 2_hidden Epoch 83 loss:23.930860043129726 ael:0.013505870710829633 cl:23.91735418163545
filename: 2_hidden Epoch 84 loss:23.931737645467123 ael:0.013486399476508997 cl:23.918251264025592
filename: 2_hidden Epoch 85 loss:23.91764238870632 ael:0.013511502595988718 cl:23.904130886033265
filename: 2_hidden Epoch 86 loss:23.913064219937688 ael:0.013452219872120006 cl:23.899612013498942
filename: 2_hidden Epoch 87 loss:23.913465148524235 ael:0.013454848057073024 cl:23.900010300798026
filename: 2_hidden Epoch 88 loss:23.89609980164913 ael:0.013467990411227645 cl:23.88263180715996
filename: 2_hidden Epoch 89 loss:23.905461456343446 ael:0.013460981192840645 cl:23.8920004777741
filename: 2_hidden Epoch 90 loss:23.888784156487002 ael:0.01343305076238269 cl:23.875351097709252
filename: 2_hidden Epoch 91 loss:23.885110724042033 ael:0.013429868008059107 cl:23.87168086871766
filename: 2_hidden Epoch 92 loss:23.873731543446144 ael:0.013390669985864943 cl:23.860340862943413
filename: 2_hidden Epoch 93 loss:23.869370481703015 ael:0.01336132313958124 cl:23.85600916488826
filename: 2_hidden Epoch 94 loss:23.86672500420732 ael:0.01336388593397991 cl:23.853361137010896
filename: 2_hidden Epoch 95 loss:23.879338302946927 ael:0.013374554792865674 cl:23.86596372448213
filename: 2_hidden Epoch 96 loss:23.849173963000204 ael:0.013349450802245335 cl:23.835824510228566
filename: 2_hidden Epoch 97 loss:23.84721868972332 ael:0.013350459761721523 cl:23.833868221372192
filename: 2_hidden Epoch 98 loss:23.841793760779307 ael:0.013318586145794531 cl:23.828475186978167
filename: 2_hidden Epoch 99 loss:23.842836730800872 ael:0.013280184489636741 cl:23.82955655438161
filename: 2_hidden Epoch 100 loss:23.83500215853864 ael:0.013308831181496991 cl:23.821693334523697
filename: 2_hidden Epoch 101 loss:23.825163891440944 ael:0.013294020723769366 cl:23.811869870570668
filename: 2_hidden Epoch 102 loss:23.820907413750366 ael:0.01326711943552813 cl:23.80764028649581
filename: 2_hidden Epoch 103 loss:23.822080674087793 ael:0.013230868325737572 cl:23.80884979426512
filename: 2_hidden Epoch 104 loss:23.809248116699575 ael:0.013252756586134956 cl:23.795995365945917
filename: 2_hidden Epoch 105 loss:23.80282995603238 ael:0.013210070250305342 cl:23.789619878579302
filename: 2_hidden Epoch 106 loss:23.81893389517801 ael:0.013232233783513394 cl:23.80570166013394
filename: 2_hidden Epoch 107 loss:23.789860347837035 ael:0.013148560887474937 cl:23.776711790185225
filename: 2_hidden Epoch 108 loss:23.804553097172786 ael:0.013153204601530357 cl:23.791399897748267
filename: 2_hidden Epoch 109 loss:23.782166696291917 ael:0.013044237306243494 cl:23.769122452206084
filename: 2_hidden Epoch 110 loss:23.78745870869062 ael:0.01309824087684266 cl:23.774360481061432
filename: 2_hidden Epoch 111 loss:23.77856661032515 ael:0.013076218739642124 cl:23.765490383014345
filename: 2_hidden Epoch 112 loss:23.7867313803288 ael:0.013059486063981527 cl:23.77367189697355
filename: 2_hidden Epoch 113 loss:23.78313989471971 ael:0.013055838101505362 cl:23.77008405707733
filename: 2_hidden Epoch 114 loss:23.773485857980294 ael:0.013030232841486645 cl:23.76045562398364
filename: 2_hidden Epoch 115 loss:23.78463678694608 ael:0.013014324173897678 cl:23.77162246369479
filename: 2_hidden Epoch 116 loss:23.7597756748311 ael:0.013065550821337696 cl:23.746710125884118
filename: 2_hidden Epoch 117 loss:23.819258235351384 ael:0.013062408252766259 cl:23.806195820144744
filename: 2_hidden Epoch 118 loss:23.929147825185318 ael:0.013045596417137666 cl:23.916102233128242
filename: 2_hidden Epoch 119 loss:23.73924329043829 ael:0.012865128414705395 cl:23.726378156985454
filename: 2_hidden Epoch 120 loss:23.75172507023951 ael:0.01294041625686992 cl:23.738784653959218
filename: 2_hidden Epoch 121 loss:23.7468737356844 ael:0.012890998211999734 cl:23.733982744830392
filename: 2_hidden Epoch 122 loss:23.740911778790213 ael:0.012893477427005246 cl:23.728018306152165
filename: 2_hidden Epoch 123 loss:23.726675344768324 ael:0.012900524242231023 cl:23.713774825536717
filename: 2_hidden Epoch 124 loss:23.80249538979335 ael:0.012979243676673774 cl:23.789516129410057
filename: 2_hidden Epoch 125 loss:23.87756507215444 ael:0.012910935581983094 cl:23.864654119948895
filename: 2_hidden Epoch 126 loss:23.815654151202644 ael:0.012858320245715349 cl:23.80279583233839
filename: 2_hidden Epoch 127 loss:23.787954386214764 ael:0.012866840398276758 cl:23.775087550648472
filename: 2_hidden Epoch 128 loss:23.78306078827172 ael:0.01288543988035567 cl:23.770175355498555
filename: 2_hidden Epoch 129 loss:23.755480110993858 ael:0.012989288944565849 cl:23.74249081974141
filename: 2_hidden Epoch 130 loss:23.740933045727466 ael:0.012926074932193199 cl:23.728006968024182
filename: 2_hidden Epoch 131 loss:23.748397375407972 ael:0.0130490348922165 cl:23.73534833896927
filename: 2_hidden Epoch 132 loss:23.736652020683067 ael:0.012958887965848659 cl:23.723693137698703
filename: 2_hidden Epoch 133 loss:23.71987791786417 ael:0.012823158123786425 cl:23.707054760581567
filename: 2_hidden Epoch 134 loss:23.72305163556372 ael:0.012912386097286267 cl:23.710139250615885
filename: 2_hidden Epoch 135 loss:23.731477802120455 ael:0.012863324968721609 cl:23.71861449236061
filename: 2_hidden Epoch 136 loss:23.70853266018873 ael:0.012827890974398681 cl:23.695704764092874
filename: 2_hidden Epoch 137 loss:23.699845754054554 ael:0.012856385375138873 cl:23.68698937321267
filename: 2_hidden Epoch 138 loss:23.703362182148716 ael:0.012825434985271061 cl:23.69053674552873
filename: 2_hidden Epoch 139 loss:23.702836994818078 ael:0.012888390375628021 cl:23.689948594500446
filename: 2_hidden Epoch 140 loss:23.726378908213118 ael:0.012751838440424082 cl:23.71362706513433
filename: 2_hidden Epoch 141 loss:23.724162648853504 ael:0.012871579678282577 cl:23.711291093993605
filename: 2_hidden Epoch 142 loss:23.714472044559948 ael:0.012850795666365857 cl:23.70162125916509
filename: 2_hidden Epoch 143 loss:23.715821250000893 ael:0.012814464477538975 cl:23.703006765577527
filename: 2_hidden Epoch 144 loss:23.70127745901632 ael:0.012764221172485697 cl:23.68851323713336
filename: 2_hidden Epoch 145 loss:23.704105374408744 ael:0.012801945000636385 cl:23.691303440562464
filename: 2_hidden Epoch 146 loss:23.686178671965123 ael:0.012735413312258428 cl:23.673443264989128
filename: 2_hidden Epoch 147 loss:23.67441726428026 ael:0.012735130990534062 cl:23.66168213950263
filename: 2_hidden Epoch 148 loss:23.67249530881469 ael:0.012777058555259865 cl:23.65971825192546
filename: 2_hidden Epoch 149 loss:23.670133471349526 ael:0.01274007983064573 cl:23.657393400292648
filename: 2_hidden Epoch 150 loss:23.665521288196942 ael:0.012788847673749715 cl:23.652732457054984
filename: 2_hidden Epoch 151 loss:23.697550266667417 ael:0.012726548131370143 cl:23.684823737228125
filename: 2_hidden Epoch 152 loss:23.67168007175825 ael:0.012653812855939594 cl:23.659026244648715
filename: 2_hidden Epoch 153 loss:23.66824507462351 ael:0.012651111318713479 cl:23.655593981380353
filename: 2_hidden Epoch 154 loss:23.677972419917236 ael:0.012639146040286325 cl:23.6653332699112
filename: 2_hidden Epoch 155 loss:23.67111476597033 ael:0.012888270625245501 cl:23.658226496713205
filename: 2_hidden Epoch 156 loss:23.675066580409894 ael:0.012628836249279088 cl:23.66243772395173
filename: 2_hidden Epoch 157 loss:23.65914371668944 ael:0.012782105027932172 cl:23.646361613691898
filename: 2_hidden Epoch 158 loss:23.663829276436253 ael:0.01268785237389132 cl:23.6511414260195
filename: 2_hidden Epoch 159 loss:23.665935652437266 ael:0.012581110943642537 cl:23.653354550523368
filename: 2_hidden Epoch 160 loss:23.659620828795852 ael:0.012814502318918009 cl:23.646806320391203
filename: 2_hidden Epoch 161 loss:23.63814417576929 ael:0.012574778167171436 cl:23.625569406029772
filename: 2_hidden Epoch 162 loss:23.650966016869795 ael:0.012568161538012369 cl:23.638397853137455
filename: 2_hidden Epoch 163 loss:23.648905068670796 ael:0.012519948805644237 cl:23.636385116242526
filename: 2_hidden Epoch 164 loss:23.63602834277683 ael:0.012548770086175342 cl:23.6234795631721
filename: 2_hidden Epoch 165 loss:23.646968608432346 ael:0.01253742785274721 cl:23.634431170859532
filename: 2_hidden Epoch 166 loss:23.64132989638033 ael:0.012525132326790464 cl:23.628804756744564
filename: 2_hidden Epoch 167 loss:23.62886785206042 ael:0.012447205215300385 cl:23.6164206404435
filename: 2_hidden Epoch 168 loss:23.630491535566005 ael:0.0125104927555903 cl:23.617981042360004
filename: 2_hidden Epoch 169 loss:23.640721007118447 ael:0.012503935586203609 cl:23.628217080880326
filename: 2_hidden Epoch 170 loss:23.632279682159425 ael:0.012426464496539873 cl:23.619853232199684
filename: 2_hidden Epoch 171 loss:23.64311550151535 ael:0.012376433437178183 cl:23.63073906703302
filename: 2_hidden Epoch 172 loss:23.639174688350387 ael:0.012423864715563797 cl:23.626750818888347
filename: 2_hidden Epoch 173 loss:23.62901180390029 ael:0.012439358733017106 cl:23.61657244810584
filename: 2_hidden Epoch 174 loss:23.625023396809897 ael:0.012541472640879757 cl:23.61248193149678
filename: 2_hidden Epoch 175 loss:23.62111287981446 ael:0.012459990811910023 cl:23.608652904019717
filename: 2_hidden Epoch 176 loss:23.62134753500509 ael:0.012413478255467979 cl:23.608934061708506
filename: 2_hidden Epoch 177 loss:23.61060326224879 ael:0.012461582411690588 cl:23.598141673015572
filename: 2_hidden Epoch 178 loss:23.616729173604508 ael:0.012308993885478778 cl:23.604420177281252
filename: 2_hidden Epoch 179 loss:23.614554845241077 ael:0.01239300196206099 cl:23.602161856422647
filename: 2_hidden Epoch 180 loss:23.605076991744905 ael:0.012368000014712326 cl:23.5927089936552
filename: 2_hidden Epoch 181 loss:23.613749343470523 ael:0.012240113587015204 cl:23.601509238125985
filename: 2_hidden Epoch 182 loss:23.611099143334997 ael:0.012438272548926592 cl:23.598660867813734
filename: 2_hidden Epoch 183 loss:23.604225111844247 ael:0.0122824223025849 cl:23.591942688456754
filename: 2_hidden Epoch 184 loss:23.596679239663466 ael:0.012130409067126306 cl:23.584548811884652
filename: 2_hidden Epoch 185 loss:23.61633884976482 ael:0.012434575912591658 cl:23.603904281303898
filename: 2_hidden Epoch 186 loss:23.600933638232494 ael:0.012398806747256054 cl:23.58853483423155
filename: 2_hidden Epoch 187 loss:23.60906998093365 ael:0.01229211666773765 cl:23.596777870222837
filename: 2_hidden Epoch 188 loss:23.58963987506621 ael:0.012359250572166944 cl:23.5772806357222
filename: 2_hidden Epoch 189 loss:23.61629346434833 ael:0.0121545248063096 cl:23.604138947090906
filename: 2_hidden Epoch 190 loss:23.617535492969534 ael:0.012428515411270729 cl:23.605106984523303
filename: 2_hidden Epoch 191 loss:23.59930671000341 ael:0.012157579480087635 cl:23.587149124814754
filename: 2_hidden Epoch 192 loss:23.59112304163258 ael:0.012027082889346265 cl:23.579095945302505
filename: 2_hidden Epoch 193 loss:23.586548558731526 ael:0.012348807281514967 cl:23.574199752361455
filename: 2_hidden Epoch 194 loss:23.611415394565515 ael:0.012084156233403419 cl:23.599331231702838
filename: 2_hidden Epoch 195 loss:23.60847257257205 ael:0.012236320553347469 cl:23.59623623396221
filename: 2_hidden Epoch 196 loss:23.586667332454034 ael:0.012287071300670504 cl:23.574380264505308
filename: 2_hidden Epoch 197 loss:23.595309982522885 ael:0.012018062083366495 cl:23.583291922117535
filename: 2_hidden Epoch 198 loss:23.583934769435235 ael:0.011974923287066277 cl:23.571959850244355
filename: 2_hidden Epoch 199 loss:23.58094328216642 ael:0.011788355906858866 cl:23.569154943499647
filename: 2_hidden Epoch 200 loss:23.577562168188262 ael:0.011780486649381574 cl:23.56578170486361
filename: 2_hidden Epoch 201 loss:23.56496587106359 ael:0.01158438312701271 cl:23.553381494332474
filename: 2_hidden Epoch 202 loss:23.58383188693844 ael:0.011711038313860521 cl:23.572120844969277

C:\Users\linco\AppData\Local\Temp\ipykernel_38868\726915545.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
C:\Users\linco\AppData\Local\Temp\ipykernel_38868\726915545.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3         4  Label
0        0.041855  0.025228  0.047769  0.013874  0.012435      1
1        0.035497  0.050104  0.027629  0.029716  0.053897      0
2        0.051992  0.034971  0.050782  0.019758  0.020184      1
3        0.023518  0.072727  0.065618  0.091620  0.022415      4
4        0.055129 -0.001285  0.030912  0.068354  0.053408      3
...           ...       ...       ...       ...       ...    ...
1750627  0.035182  0.049502  0.027084  0.029165  0.054035      0
1750628  0.033120  0.048345  0.027900  0.029738  0.052397      0
1750629  0.035140  0.048912  0.027773  0.028711  0.053920      0
1750630  0.035168  0.049461  0.027052  0.029125  0.054042      0
1750631  0.035684  0.050417  0.027928  0.029999  0.053819      0

[1750632 rows x 6 columns]

Davies-Bouldin Score: 1.564302242419672

               0         1         2         3         4  Label
0       0.032964  0.048294  0.027817  0.029763  0.052420    0.0
1       0.024283  0.000150  0.035260  0.005090  0.003479    2.0
2       0.042839  0.023788  0.047777  0.015283  0.012066    1.0
3       0.058047 -0.005196  0.029979  0.071594  0.055912    3.0
4       0.043504  0.028962  0.046508  0.016994  0.017758    1.0
...          ...       ...       ...       ...       ...    ...
519951  0.045661  0.027126  0.049318  0.014531  0.012939    2.0
519952  0.018773  0.067152  0.064711  0.087231  0.016754    1.0
519953  0.035241  0.049676  0.027221  0.029329  0.054004    3.0
519954  0.042959  0.029083  0.048225  0.016752  0.015360    0.0
519955  0.055223 -0.003509  0.031795  0.077713  0.054269    0.0

[519956 rows x 6 columns]

               0         1         2         3         4  Label
0       0.035461  0.050044  0.027572  0.029662  0.053912    0.0
1       0.033319  0.048409  0.028006  0.029706  0.052367    0.0
2       0.041508  0.026569  0.044031  0.019821  0.019403    1.0
3       0.049014  0.024504  0.061097  0.013251 -0.002660    1.0
4       0.035106  0.048913  0.027752  0.028704  0.053928    NaN
...          ...       ...       ...       ...       ...    ...
649942  0.043820  0.029056  0.047004  0.017408  0.017481    3.0
649943  0.035721  0.048969  0.028212  0.028753  0.053673    1.0
649944  0.035310  0.049247  0.028012  0.028566  0.053769    0.0
649945  0.056489 -0.003892  0.030137  0.070611  0.054966    4.0
649946  0.047649  0.007850  0.037159  0.069117  0.043510    0.0

[649947 rows x 6 columns]

3_hidden
cuda
[0.0, 1.0, 2.0, 4.0, 5.0]
pick completo
82 5
filename: 3_hidden Epoch 1 loss:37.59710555692087 ael:0.023681747655176274 cl:37.57342377485324
filename: 3_hidden Epoch 2 loss:30.681926417822687 ael:0.01561951015564162 cl:30.666306903244628
filename: 3_hidden Epoch 3 loss:29.43174887328285 ael:0.014644338568640862 cl:29.41710453815104
filename: 3_hidden Epoch 4 loss:28.73143635588434 ael:0.014356007463274591 cl:28.717080338273103
filename: 3_hidden Epoch 5 loss:28.221707513945862 ael:0.014367296943840356 cl:28.207340219208945
filename: 3_hidden Epoch 6 loss:27.854602084174473 ael:0.014351654028484158 cl:27.840250435332784
filename: 3_hidden Epoch 7 loss:27.597131229291097 ael:0.01427254774967317 cl:27.582858683041355
filename: 3_hidden Epoch 8 loss:27.381851817360488 ael:0.014240711201465259 cl:27.367611095703907
filename: 3_hidden Epoch 9 loss:27.193925359304284 ael:0.014163816464815111 cl:27.17976155425966
filename: 3_hidden Epoch 10 loss:27.038537769620717 ael:0.014064935626940356 cl:27.024472839891462
filename: 3_hidden Epoch 11 loss:26.887285775449705 ael:0.013976088303118188 cl:26.87330969402908
filename: 3_hidden Epoch 12 loss:26.767739272828816 ael:0.01387843027698452 cl:26.75386085063593
filename: 3_hidden Epoch 13 loss:26.668431548710682 ael:0.01380466036799727 cl:26.654626895765226
filename: 3_hidden Epoch 14 loss:26.586558172089294 ael:0.013742776188541413 cl:26.572815396043296
filename: 3_hidden Epoch 15 loss:26.51158894554034 ael:0.013705484798073701 cl:26.497883470469873
filename: 3_hidden Epoch 16 loss:26.450965236347965 ael:0.013678934501189607 cl:26.437286302509634
filename: 3_hidden Epoch 17 loss:26.419860023624025 ael:0.013658210395539093 cl:26.406201824957126
filename: 3_hidden Epoch 18 loss:26.41662609567209 ael:0.013658526705088292 cl:26.402967571580778
filename: 3_hidden Epoch 19 loss:26.330017024439826 ael:0.013628674335860843 cl:26.316388355379555
filename: 3_hidden Epoch 20 loss:26.27707904489186 ael:0.013575761347120107 cl:26.263503275909297
filename: 3_hidden Epoch 21 loss:26.25068694434526 ael:0.013535962808240596 cl:26.23715097125872
filename: 3_hidden Epoch 22 loss:26.20249556325291 ael:0.013487037932819598 cl:26.18900852134243
filename: 3_hidden Epoch 23 loss:26.188007160119767 ael:0.01344545244841372 cl:26.174561728399578
filename: 3_hidden Epoch 24 loss:26.164839913926816 ael:0.01336708974538738 cl:26.15147281696712
filename: 3_hidden Epoch 25 loss:26.101139984790215 ael:0.013361117433614308 cl:26.087778863516032
filename: 3_hidden Epoch 26 loss:26.09143112188998 ael:0.013382131535251442 cl:26.07804898840822
filename: 3_hidden Epoch 27 loss:26.034730970277938 ael:0.013400348018390624 cl:26.021330608775234
filename: 3_hidden Epoch 28 loss:25.990263809425304 ael:0.01349220391838563 cl:25.976771626128173
filename: 3_hidden Epoch 29 loss:25.95110458233644 ael:0.013540699204068049 cl:25.937563876770717
filename: 3_hidden Epoch 30 loss:25.84961330295772 ael:0.01356973164100309 cl:25.83604358091373
filename: 3_hidden Epoch 31 loss:25.782962227984328 ael:0.01357525293794488 cl:25.769386965749256
filename: 3_hidden Epoch 32 loss:25.72587602039483 ael:0.013559109387763004 cl:25.71231691824682
filename: 3_hidden Epoch 33 loss:25.701624733909178 ael:0.013540205951538098 cl:25.68808453828138
filename: 3_hidden Epoch 34 loss:25.64324135377542 ael:0.013506802861898896 cl:25.629734549244567
filename: 3_hidden Epoch 35 loss:25.57113453429291 ael:0.013500909218452985 cl:25.55763360760755
filename: 3_hidden Epoch 36 loss:25.537742272837765 ael:0.01348289510467307 cl:25.524259385405923
filename: 3_hidden Epoch 37 loss:25.494212440637483 ael:0.0134782094683925 cl:25.480734227725247
filename: 3_hidden Epoch 38 loss:25.45110986144356 ael:0.013476243280268975 cl:25.43763362341084
filename: 3_hidden Epoch 39 loss:25.41987557221097 ael:0.013460926417389104 cl:25.40641463816515
filename: 3_hidden Epoch 40 loss:25.378839421013055 ael:0.013474120734587149 cl:25.36536529238988
filename: 3_hidden Epoch 41 loss:25.338007336976236 ael:0.013484047071508189 cl:25.32452329247982
filename: 3_hidden Epoch 42 loss:25.303350868682394 ael:0.01352948006678706 cl:25.289821403552338
filename: 3_hidden Epoch 43 loss:25.2699449085611 ael:0.01354950346605157 cl:25.256395410687137
filename: 3_hidden Epoch 44 loss:25.231930297498486 ael:0.0135318044648883 cl:25.21839848899363
filename: 3_hidden Epoch 45 loss:25.19286823352466 ael:0.0135695840893373 cl:25.179298646010693
filename: 3_hidden Epoch 46 loss:25.14468268880214 ael:0.013578325847554812 cl:25.13110436906647
filename: 3_hidden Epoch 47 loss:25.096167047275685 ael:0.013626131826011058 cl:25.082540917801996
filename: 3_hidden Epoch 48 loss:25.05749386068769 ael:0.013629980808254285 cl:25.04386389312021
filename: 3_hidden Epoch 49 loss:25.03357972931257 ael:0.013631105105435994 cl:25.01994863818009
filename: 3_hidden Epoch 50 loss:24.988843416416582 ael:0.013658822858397148 cl:24.97518458923391
filename: 3_hidden Epoch 51 loss:24.98620919248072 ael:0.013653577332119275 cl:24.972555623667333
filename: 3_hidden Epoch 52 loss:24.92157838575216 ael:0.013595486528691655 cl:24.907982887117054
filename: 3_hidden Epoch 53 loss:24.897643843566538 ael:0.013549151849848068 cl:24.88409468228351
filename: 3_hidden Epoch 54 loss:24.860957910597808 ael:0.013597280659967556 cl:24.847360616279307
filename: 3_hidden Epoch 55 loss:24.838600231539683 ael:0.013637955194058228 cl:24.824962277780642
filename: 3_hidden Epoch 56 loss:24.826539111130742 ael:0.013646124970143989 cl:24.812892997301418
filename: 3_hidden Epoch 57 loss:24.786306319543836 ael:0.013570054620660162 cl:24.77273625186934
filename: 3_hidden Epoch 58 loss:24.772927499860984 ael:0.013617409536511678 cl:24.759310089847254
filename: 3_hidden Epoch 59 loss:24.74165545820625 ael:0.013602088535256976 cl:24.728053383020296
filename: 3_hidden Epoch 60 loss:24.723688671706544 ael:0.013596748910607536 cl:24.71009194953946
filename: 3_hidden Epoch 61 loss:24.688835373222577 ael:0.013614670767889967 cl:24.67522069103112
filename: 3_hidden Epoch 62 loss:24.668407699142556 ael:0.013613319885144585 cl:24.65479439202876
filename: 3_hidden Epoch 63 loss:24.63810370950138 ael:0.013605027200702441 cl:24.62449867305963
filename: 3_hidden Epoch 64 loss:24.580446157144376 ael:0.013557241700957305 cl:24.5668889203376
filename: 3_hidden Epoch 65 loss:24.573927121339217 ael:0.01352806956745354 cl:24.56039903979465
filename: 3_hidden Epoch 66 loss:24.547351459623346 ael:0.013490450468796074 cl:24.53386101351829
filename: 3_hidden Epoch 67 loss:24.536140952895934 ael:0.013512936410353164 cl:24.52262800358649
filename: 3_hidden Epoch 68 loss:24.507521461569766 ael:0.013474957057585665 cl:24.494046511409472
filename: 3_hidden Epoch 69 loss:24.485433918804322 ael:0.013464457205628366 cl:24.4719694704939
filename: 3_hidden Epoch 70 loss:24.474459274053775 ael:0.01342373739477275 cl:24.461035529849987
filename: 3_hidden Epoch 71 loss:24.441528283090754 ael:0.013378061492287884 cl:24.42815022007283
filename: 3_hidden Epoch 72 loss:24.44044110872701 ael:0.013357235753562395 cl:24.427083867554018
filename: 3_hidden Epoch 73 loss:24.436249291361758 ael:0.013297546387771843 cl:24.422951746957363
filename: 3_hidden Epoch 74 loss:24.3998583412649 ael:0.013273086615118652 cl:24.386585242508314
filename: 3_hidden Epoch 75 loss:24.382905671880344 ael:0.013235559609646182 cl:24.369670088921943
filename: 3_hidden Epoch 76 loss:24.365980102585855 ael:0.013204816294455465 cl:24.35277526798041
filename: 3_hidden Epoch 77 loss:24.356846420419956 ael:0.013258962402577715 cl:24.343587484006136
filename: 3_hidden Epoch 78 loss:24.346331567926462 ael:0.013154075411933775 cl:24.333177501124396
filename: 3_hidden Epoch 79 loss:24.33715638404508 ael:0.013186255541318782 cl:24.32397013851152
filename: 3_hidden Epoch 80 loss:24.33400883659999 ael:0.013093940263802556 cl:24.320914891426167
filename: 3_hidden Epoch 81 loss:24.312711144610304 ael:0.013084635626631657 cl:24.299626500087427
filename: 3_hidden Epoch 82 loss:24.328850498098433 ael:0.013110182360998595 cl:24.31574031998927
filename: 3_hidden Epoch 83 loss:24.307906872122143 ael:0.01303678879772417 cl:24.29487008625729
filename: 3_hidden Epoch 84 loss:24.28312012901338 ael:0.013074630830651926 cl:24.270045483315062
filename: 3_hidden Epoch 85 loss:24.264399967454157 ael:0.012979077694536186 cl:24.251420865724903
filename: 3_hidden Epoch 86 loss:24.286048440903983 ael:0.012940574935106454 cl:24.27310786527746
filename: 3_hidden Epoch 87 loss:24.263352234848103 ael:0.012975153200907863 cl:24.250377081814403
filename: 3_hidden Epoch 88 loss:24.243582299867647 ael:0.012875368161236538 cl:24.23070692132036
filename: 3_hidden Epoch 89 loss:24.229878362055306 ael:0.012874923938543129 cl:24.217003442930718
filename: 3_hidden Epoch 90 loss:24.229784513802656 ael:0.012869155319765364 cl:24.21691536245354
filename: 3_hidden Epoch 91 loss:24.24122643982563 ael:0.012811891059021216 cl:24.22841456370464
filename: 3_hidden Epoch 92 loss:24.21478118715693 ael:0.012820100613771323 cl:24.201961105236077
filename: 3_hidden Epoch 93 loss:24.21866989880177 ael:0.012848232780612543 cl:24.20582165597108
filename: 3_hidden Epoch 94 loss:24.182571785477233 ael:0.01276985954509901 cl:24.16980192951748
filename: 3_hidden Epoch 95 loss:24.237503320286127 ael:0.012767918919404469 cl:24.224735383373268
filename: 3_hidden Epoch 96 loss:24.222975808795795 ael:0.012771798918817679 cl:24.21020401783697
filename: 3_hidden Epoch 97 loss:24.190309562289617 ael:0.012697046230060828 cl:24.177612516851454
filename: 3_hidden Epoch 98 loss:24.161850239860335 ael:0.012696394066170277 cl:24.149153843675776
filename: 3_hidden Epoch 99 loss:24.168677439289503 ael:0.012733175071355672 cl:24.15594426855125
filename: 3_hidden Epoch 100 loss:24.157861833489967 ael:0.012707638534282887 cl:24.14515420271887
filename: 3_hidden Epoch 101 loss:24.179889277491956 ael:0.012651387364521793 cl:24.167237891438347
filename: 3_hidden Epoch 102 loss:24.13110908346652 ael:0.012700743575489285 cl:24.118408330210677
filename: 3_hidden Epoch 103 loss:24.13094425919264 ael:0.012699765597730003 cl:24.118244500820904
filename: 3_hidden Epoch 104 loss:24.151157806668735 ael:0.01270677259408409 cl:24.138451024021716
filename: 3_hidden Epoch 105 loss:24.13658641977898 ael:0.012637185793788546 cl:24.123949249242056
filename: 3_hidden Epoch 106 loss:24.113387140019345 ael:0.01263003695054135 cl:24.10075709372468
filename: 3_hidden Epoch 107 loss:24.113633357086055 ael:0.01271040931007541 cl:24.100922943723543
filename: 3_hidden Epoch 108 loss:24.115299161044806 ael:0.012631062483910917 cl:24.10266811082647
filename: 3_hidden Epoch 109 loss:24.122944998548395 ael:0.012581926270444927 cl:24.110363084225725
filename: 3_hidden Epoch 110 loss:24.1028342043619 ael:0.01260233864163269 cl:24.09023187976047
filename: 3_hidden Epoch 111 loss:24.090653829731448 ael:0.012606592621453831 cl:24.07804724058136
filename: 3_hidden Epoch 112 loss:24.089630186507918 ael:0.012713713441869742 cl:24.076916479020852
filename: 3_hidden Epoch 113 loss:24.070474775115994 ael:0.012602747891566648 cl:24.057872025123174
filename: 3_hidden Epoch 114 loss:24.072683271605356 ael:0.01254116751955667 cl:24.06014209542063
filename: 3_hidden Epoch 115 loss:24.078895178551058 ael:0.012555071633596804 cl:24.066340109615364
filename: 3_hidden Epoch 116 loss:24.06183363289962 ael:0.012496101048912366 cl:24.04933753544021
filename: 3_hidden Epoch 117 loss:24.054727522948674 ael:0.012572275028868592 cl:24.042155258097885
filename: 3_hidden Epoch 118 loss:24.049524197712696 ael:0.012546636193267874 cl:24.036977567478644
filename: 3_hidden Epoch 119 loss:24.05968009485054 ael:0.012485951858208909 cl:24.04719413287267
filename: 3_hidden Epoch 120 loss:24.02761482109025 ael:0.0124283799645082 cl:24.015186433709694
filename: 3_hidden Epoch 121 loss:24.05150226340973 ael:0.012553900306312727 cl:24.03894835791948
filename: 3_hidden Epoch 122 loss:24.031056421395295 ael:0.012365134494705788 cl:24.01869128971403
filename: 3_hidden Epoch 123 loss:24.034085983348685 ael:0.012399122468942316 cl:24.021686862363833
filename: 3_hidden Epoch 124 loss:24.035146915317746 ael:0.012400032379925418 cl:24.022746891971416
filename: 3_hidden Epoch 125 loss:24.016866410645996 ael:0.01234767863000913 cl:24.004518730114654
filename: 3_hidden Epoch 126 loss:24.03189541232064 ael:0.012383721097171773 cl:24.019511697416622
filename: 3_hidden Epoch 127 loss:24.031267536228203 ael:0.012310168912812365 cl:24.01895737681244
filename: 3_hidden Epoch 128 loss:24.008544403960986 ael:0.01235319567719126 cl:23.996191214079442
filename: 3_hidden Epoch 129 loss:24.01733175532413 ael:0.012347908327078168 cl:24.004983827002306
filename: 3_hidden Epoch 130 loss:24.01111636974036 ael:0.01234304070408327 cl:23.998773348308188
filename: 3_hidden Epoch 131 loss:24.016477983111553 ael:0.012348884637180663 cl:24.00412910350824
filename: 3_hidden Epoch 132 loss:24.00317416046202 ael:0.012399261596903167 cl:23.990774884741054
filename: 3_hidden Epoch 133 loss:23.99473947929678 ael:0.012353688529618594 cl:23.982385801278618
filename: 3_hidden Epoch 134 loss:23.988660275853043 ael:0.012328295373641617 cl:23.97633199529592
filename: 3_hidden Epoch 135 loss:23.99226314469171 ael:0.012322523872878747 cl:23.97994062340223
filename: 3_hidden Epoch 136 loss:23.988767473950904 ael:0.01220628728657537 cl:23.97656117915974
filename: 3_hidden Epoch 137 loss:23.99207124904168 ael:0.012266566276400742 cl:23.97980469490181
filename: 3_hidden Epoch 138 loss:23.974949064379718 ael:0.012240094709118446 cl:23.962708973306317
filename: 3_hidden Epoch 139 loss:23.99096878451626 ael:0.012292600782073521 cl:23.97867616611435
filename: 3_hidden Epoch 140 loss:23.98363934834089 ael:0.01220703404604483 cl:23.971432315495676
filename: 3_hidden Epoch 141 loss:23.975665886089068 ael:0.01212172087459535 cl:23.963544172399185
filename: 3_hidden Epoch 142 loss:23.955990129571322 ael:0.012147015894565587 cl:23.94384313593477
filename: 3_hidden Epoch 143 loss:23.949100205118622 ael:0.012217122243557895 cl:23.936883078267524
filename: 3_hidden Epoch 144 loss:23.96062907369681 ael:0.012189244396324057 cl:23.948439833909845
filename: 3_hidden Epoch 145 loss:23.96247841808701 ael:0.012171891645679226 cl:23.95030651778473
filename: 3_hidden Epoch 146 loss:23.951015016179845 ael:0.012115161691213057 cl:23.938899852453847
filename: 3_hidden Epoch 147 loss:23.950293690107443 ael:0.012161548347307143 cl:23.938132141704575
filename: 3_hidden Epoch 148 loss:23.9462182725875 ael:0.012101487150654126 cl:23.93411676711547
filename: 3_hidden Epoch 149 loss:23.951345422456015 ael:0.012118576311046512 cl:23.93922684124196
filename: 3_hidden Epoch 150 loss:23.94217919040464 ael:0.012078474593305442 cl:23.930100710304927
filename: 3_hidden Epoch 151 loss:23.937485985480745 ael:0.012125156525650212 cl:23.925360834628453
filename: 3_hidden Epoch 152 loss:23.93401376869408 ael:0.012051548173737818 cl:23.92196220948831
filename: 3_hidden Epoch 153 loss:23.91220864539762 ael:0.012066287078391236 cl:23.900142349570714
filename: 3_hidden Epoch 154 loss:23.94056515604598 ael:0.012067354740411384 cl:23.928497798867568
filename: 3_hidden Epoch 155 loss:23.936273501980825 ael:0.012048820463630493 cl:23.924224671129068
filename: 3_hidden Epoch 156 loss:23.908476007194082 ael:0.012041374550291613 cl:23.896434645683346
filename: 3_hidden Epoch 157 loss:23.91973733808923 ael:0.012039914448359466 cl:23.907697428226605
filename: 3_hidden Epoch 158 loss:23.97510620183123 ael:0.01200655409388591 cl:23.96309963999467
filename: 3_hidden Epoch 159 loss:23.975706343468698 ael:0.01195619189641811 cl:23.963750141059784
filename: 3_hidden Epoch 160 loss:23.899039857394854 ael:0.012009257111092913 cl:23.88703060548951
filename: 3_hidden Epoch 161 loss:23.894943225606426 ael:0.011975866035437032 cl:23.882967360012373
filename: 3_hidden Epoch 162 loss:23.911468147467133 ael:0.011962511802337813 cl:23.89950563171829
filename: 3_hidden Epoch 163 loss:23.90581102001657 ael:0.012000028602726984 cl:23.89381099272346
filename: 3_hidden Epoch 164 loss:23.89488047931332 ael:0.011953616580490468 cl:23.882926854776212
filename: 3_hidden Epoch 165 loss:23.887482337643252 ael:0.011922824331529382 cl:23.875559503466498
filename: 3_hidden Epoch 166 loss:23.8894714613894 ael:0.011876818196651229 cl:23.877594632759447
filename: 3_hidden Epoch 167 loss:23.87608982933774 ael:0.011951002511469758 cl:23.86413883265593
filename: 3_hidden Epoch 168 loss:23.887694094285415 ael:0.011984844459675134 cl:23.875709236980914
filename: 3_hidden Epoch 169 loss:23.88095788235182 ael:0.011982979810118243 cl:23.86897488347594
filename: 3_hidden Epoch 170 loss:24.0356971154746 ael:0.011978117207749111 cl:24.023719008599677
filename: 3_hidden Epoch 171 loss:23.977219547306824 ael:0.011928210526981044 cl:23.965291339905107
filename: 3_hidden Epoch 172 loss:23.869443708919103 ael:0.011859702089178819 cl:23.857584011863793
filename: 3_hidden Epoch 173 loss:23.871427327037225 ael:0.01192011473067406 cl:23.85950720154013
filename: 3_hidden Epoch 174 loss:23.935237634604043 ael:0.011920121463614401 cl:23.92331750857521
filename: 3_hidden Epoch 175 loss:23.86426931614659 ael:0.011919840378673803 cl:23.852349479915638
filename: 3_hidden Epoch 176 loss:23.855584865896557 ael:0.011898280657539137 cl:23.84368659700894
filename: 3_hidden Epoch 177 loss:23.866602181657164 ael:0.011862121483221221 cl:23.854740060934425
filename: 3_hidden Epoch 178 loss:23.853208244627886 ael:0.011835154733517508 cl:23.841373083084314
filename: 3_hidden Epoch 179 loss:23.860753346260523 ael:0.011791043262643122 cl:23.84896230737512
filename: 3_hidden Epoch 180 loss:23.85146207891868 ael:0.011773572721112761 cl:23.839688501286247
filename: 3_hidden Epoch 181 loss:23.839363309776747 ael:0.011743754091103212 cl:23.82761956909622
filename: 3_hidden Epoch 182 loss:23.869735905477388 ael:0.011937806086008732 cl:23.85779808954771
filename: 3_hidden Epoch 183 loss:23.853037281956286 ael:0.011815837832130876 cl:23.841221444879963
filename: 3_hidden Epoch 184 loss:23.864321338322824 ael:0.011894256533426031 cl:23.852427100018602
filename: 3_hidden Epoch 185 loss:23.84629835496216 ael:0.011896294707306205 cl:23.834402062549277
filename: 3_hidden Epoch 186 loss:23.842993038891084 ael:0.011846041913368358 cl:23.83114698626452
filename: 3_hidden Epoch 187 loss:23.832267285855593 ael:0.011807444885503973 cl:23.82045983696569
filename: 3_hidden Epoch 188 loss:23.90485805025465 ael:0.011814466443672 cl:23.893043598359032
filename: 3_hidden Epoch 189 loss:23.83420631232154 ael:0.011766343961976384 cl:23.822439957834867
filename: 3_hidden Epoch 190 loss:23.835662635482052 ael:0.011799072211954649 cl:23.823863560421607
filename: 3_hidden Epoch 191 loss:23.824571501022266 ael:0.011820464219730778 cl:23.812751030901996
filename: 3_hidden Epoch 192 loss:23.82593763323258 ael:0.011831502600463695 cl:23.81410613165016
filename: 3_hidden Epoch 193 loss:23.843763675269624 ael:0.01179065876922087 cl:23.831973027744297
filename: 3_hidden Epoch 194 loss:23.830186285545874 ael:0.011861966269369624 cl:23.818324315837078
filename: 3_hidden Epoch 195 loss:23.818174814160965 ael:0.011776658047145377 cl:23.806398146591846
filename: 3_hidden Epoch 196 loss:23.799272084721355 ael:0.01173346216216837 cl:23.787538617774572
filename: 3_hidden Epoch 197 loss:23.908720874174875 ael:0.011923168961904842 cl:23.89679770021675
filename: 3_hidden Epoch 198 loss:23.821818197807097 ael:0.011867462132922663 cl:23.80995072140679
filename: 3_hidden Epoch 199 loss:23.813012238229454 ael:0.011871689921730502 cl:23.80114055949398
filename: 3_hidden Epoch 200 loss:23.824402525460187 ael:0.01176464706238703 cl:23.812637863499493
filename: 3_hidden Epoch 201 loss:23.805858274406134 ael:0.011806611413593607 cl:23.79405166619596
filename: 3_hidden Epoch 202 loss:23.8286671719579 ael:0.01182264070760574 cl:23.816844535531988

C:\Users\linco\AppData\Local\Temp\ipykernel_38868\726915545.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
C:\Users\linco\AppData\Local\Temp\ipykernel_38868\726915545.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3         4  Label
0       -0.064547 -0.065979 -0.069464 -0.073793 -0.039781      1
1       -0.060939 -0.067023 -0.080130 -0.071029 -0.078212      0
2       -0.067100 -0.052821 -0.043083 -0.044337 -0.075981      2
3       -0.064590 -0.064969 -0.066517 -0.068600 -0.044294      1
4       -0.106647 -0.104227 -0.049149 -0.073898 -0.074412      4
...           ...       ...       ...       ...       ...    ...
1836045 -0.060916 -0.067034 -0.080203 -0.071002 -0.078507      0
1836046 -0.067101 -0.052822 -0.043083 -0.044337 -0.075982      2
1836047 -0.067102 -0.052824 -0.043083 -0.044337 -0.075983      2
1836048 -0.060952 -0.067017 -0.080091 -0.071044 -0.078052      0
1836049 -0.067173 -0.052939 -0.043106 -0.044336 -0.076079      2

[1836050 rows x 6 columns]

Davies-Bouldin Score: 0.3698601404753762

               0         1         2         3         4  Label
0      -0.061702 -0.067335 -0.079272 -0.070381 -0.080036    0.0
1      -0.067095 -0.052812 -0.043082 -0.044336 -0.075973    2.0
2      -0.062564 -0.064614 -0.070536 -0.073114 -0.040648    1.0
3      -0.065547 -0.049125 -0.042069 -0.045499 -0.070960    3.0
4      -0.063565 -0.065489 -0.070623 -0.073346 -0.043198    1.0
...          ...       ...       ...       ...       ...    ...
519951 -0.062611 -0.064620 -0.071301 -0.073360 -0.042670    2.0
519952 -0.101521 -0.100223 -0.053198 -0.074995 -0.071028    1.0
519953 -0.060922 -0.067031 -0.080184 -0.071009 -0.078431    3.0
519954 -0.061767 -0.063324 -0.071240 -0.073739 -0.040892    0.0
519955 -0.055802 -0.050520 -0.062537 -0.058855 -0.062059    0.0

[519956 rows x 6 columns]

               0         1         2         3         4  Label
0      -0.060937 -0.067024 -0.080138 -0.071027 -0.078242    0.0
1      -0.061569 -0.067281 -0.079502 -0.070485 -0.080061    0.0
2      -0.063178 -0.065564 -0.070641 -0.073773 -0.039876    1.0
3      -0.061974 -0.064480 -0.071941 -0.077604 -0.025913    1.0
4      -0.062570 -0.068524 -0.079437 -0.071340 -0.078614    NaN
...          ...       ...       ...       ...       ...    ...
649942 -0.062518 -0.064520 -0.071143 -0.073283 -0.042666    3.0
649943 -0.061673 -0.067470 -0.079613 -0.071148 -0.077932    1.0
649944 -0.062075 -0.068044 -0.079689 -0.071237 -0.078711    0.0
649945 -0.099898 -0.099466 -0.046027 -0.060085 -0.088032    4.0
649946 -0.064411 -0.047030 -0.040306 -0.042151 -0.074692    0.0

[649947 rows x 6 columns]

4_hidden
cuda
[0.0, 1.0, 2.0, 3.0, 5.0]
pick completo
82 5
filename: 4_hidden Epoch 1 loss:33.30122134560033 ael:0.023107541885915718 cl:33.27811381433978
filename: 4_hidden Epoch 2 loss:29.299374423110695 ael:0.016175979772248328 cl:29.28319844285808
filename: 4_hidden Epoch 3 loss:28.66692052936425 ael:0.015554218331801827 cl:28.651366319540543
filename: 4_hidden Epoch 4 loss:28.03638665460543 ael:0.015096132281297936 cl:28.02129048438851
filename: 4_hidden Epoch 5 loss:27.636953283353694 ael:0.014330131439152759 cl:27.622623137295164
filename: 4_hidden Epoch 6 loss:27.37128584960855 ael:0.013993820846684065 cl:27.357292022396194
filename: 4_hidden Epoch 7 loss:27.158877309678214 ael:0.013885607810970018 cl:27.14499170352251
filename: 4_hidden Epoch 8 loss:26.960793077414817 ael:0.013807694198671784 cl:26.946985372422358
filename: 4_hidden Epoch 9 loss:26.819048817952474 ael:0.013740849343358504 cl:26.805307968489714
filename: 4_hidden Epoch 10 loss:26.649043620388838 ael:0.0136480841991792 cl:26.635395548893854
filename: 4_hidden Epoch 11 loss:26.5112381722763 ael:0.013447389003598256 cl:26.497790805337882
filename: 4_hidden Epoch 12 loss:26.346442828262063 ael:0.013181762047132098 cl:26.33326106978814
filename: 4_hidden Epoch 13 loss:26.215812376797118 ael:0.012936826204873532 cl:26.202875554835103
filename: 4_hidden Epoch 14 loss:26.079546498801864 ael:0.01283666685665989 cl:26.066709831433418
filename: 4_hidden Epoch 15 loss:25.95944269466014 ael:0.012793178051740293 cl:25.946649516384934
filename: 4_hidden Epoch 16 loss:25.864999560563348 ael:0.01275633935377947 cl:25.85224323246965
filename: 4_hidden Epoch 17 loss:25.783085581873433 ael:0.012751368293224478 cl:25.77033422009343
filename: 4_hidden Epoch 18 loss:25.711295138936936 ael:0.012755096575569527 cl:25.69854004585791
filename: 4_hidden Epoch 19 loss:25.654984313305896 ael:0.012744975022659932 cl:25.642239339728103
filename: 4_hidden Epoch 20 loss:25.597618903032682 ael:0.012737703970388363 cl:25.584881203634698
filename: 4_hidden Epoch 21 loss:25.55291147528068 ael:0.012738949717267564 cl:25.540172514098217
filename: 4_hidden Epoch 22 loss:25.524965016497614 ael:0.012705375384363407 cl:25.512259643184027
filename: 4_hidden Epoch 23 loss:25.482360031601548 ael:0.012711168541327903 cl:25.46964884666618
filename: 4_hidden Epoch 24 loss:25.418714235540023 ael:0.01274243343706958 cl:25.405971785531193
filename: 4_hidden Epoch 25 loss:25.364802745865425 ael:0.0127592763545522 cl:25.352043471033916
filename: 4_hidden Epoch 26 loss:25.3244518892646 ael:0.01277597003092288 cl:25.311675916252188
filename: 4_hidden Epoch 27 loss:25.28806860405102 ael:0.012798610211987244 cl:25.27526998584248
filename: 4_hidden Epoch 28 loss:25.243169996130323 ael:0.012797360952224647 cl:25.230372645369105
filename: 4_hidden Epoch 29 loss:25.189613831863714 ael:0.01280915168907076 cl:25.176804662233423
filename: 4_hidden Epoch 30 loss:25.15921118063161 ael:0.01281039261996907 cl:25.146400778560665
filename: 4_hidden Epoch 31 loss:25.120574440486358 ael:0.01284449409225933 cl:25.107729931109347
filename: 4_hidden Epoch 32 loss:25.096832993542133 ael:0.012827477238408708 cl:25.08400552108703
filename: 4_hidden Epoch 33 loss:25.068524868510835 ael:0.012833720337795583 cl:25.055691150454212
filename: 4_hidden Epoch 34 loss:25.024338454788353 ael:0.012848503070200986 cl:25.01148994641426
filename: 4_hidden Epoch 35 loss:24.99504666450696 ael:0.012866958515283711 cl:24.98217968702638
filename: 4_hidden Epoch 36 loss:24.960364488197563 ael:0.012875409195056328 cl:24.947489085950348
filename: 4_hidden Epoch 37 loss:24.92733589254732 ael:0.012892038555370893 cl:24.914443855440087
filename: 4_hidden Epoch 38 loss:24.908039658272315 ael:0.012876668571168997 cl:24.895163007625523
filename: 4_hidden Epoch 39 loss:24.87517411132895 ael:0.012873342468349236 cl:24.8623007641791
filename: 4_hidden Epoch 40 loss:24.85304424064523 ael:0.012885439294351419 cl:24.84015881156149
filename: 4_hidden Epoch 41 loss:24.83500032154655 ael:0.012908233976175106 cl:24.82209209076628
filename: 4_hidden Epoch 42 loss:24.801440318489846 ael:0.012895545895825996 cl:24.788544766301246
filename: 4_hidden Epoch 43 loss:24.782085886143157 ael:0.012888069834444526 cl:24.769197807878296
filename: 4_hidden Epoch 44 loss:24.77327715298425 ael:0.012882322048851353 cl:24.7603948250795
filename: 4_hidden Epoch 45 loss:24.742509724543645 ael:0.012868754953578336 cl:24.72964095657493
filename: 4_hidden Epoch 46 loss:24.72010261031137 ael:0.012861793857525314 cl:24.707240828747047
filename: 4_hidden Epoch 47 loss:24.70375111691865 ael:0.012866990878051914 cl:24.69088412656797
filename: 4_hidden Epoch 48 loss:24.692698621556826 ael:0.012842645579584536 cl:24.67985597628492
filename: 4_hidden Epoch 49 loss:24.668329271839056 ael:0.012838586531177304 cl:24.655490688370307
filename: 4_hidden Epoch 50 loss:24.650735709927826 ael:0.01283538134745982 cl:24.637900341409743
filename: 4_hidden Epoch 51 loss:24.636193625260944 ael:0.012814228380207028 cl:24.623379420333222
filename: 4_hidden Epoch 52 loss:24.61734307066471 ael:0.012806249308612263 cl:24.60453682357644
filename: 4_hidden Epoch 53 loss:24.598434408602284 ael:0.012807831057320964 cl:24.58562658724354
filename: 4_hidden Epoch 54 loss:24.57631389139152 ael:0.012794693048626144 cl:24.563519184148586
filename: 4_hidden Epoch 55 loss:24.582764315379936 ael:0.0127950718048231 cl:24.569969245200216
filename: 4_hidden Epoch 56 loss:24.5536982547899 ael:0.01277605318634013 cl:24.54092219683484
filename: 4_hidden Epoch 57 loss:24.540294479905512 ael:0.012758310186939362 cl:24.527536161579743
filename: 4_hidden Epoch 58 loss:24.528881840570737 ael:0.012744303801010253 cl:24.516137531604844
filename: 4_hidden Epoch 59 loss:24.50373865608905 ael:0.012691155065972152 cl:24.491047488275647
filename: 4_hidden Epoch 60 loss:24.492219512568795 ael:0.01266556726856592 cl:24.47955396139992
filename: 4_hidden Epoch 61 loss:24.47640227138916 ael:0.012674332159230745 cl:24.46372792994284
filename: 4_hidden Epoch 62 loss:24.482778585745418 ael:0.01265970646842369 cl:24.470118887897446
filename: 4_hidden Epoch 63 loss:24.463166522851036 ael:0.01263083617973384 cl:24.45053569778257
filename: 4_hidden Epoch 64 loss:24.44035363242372 ael:0.01262410453139891 cl:24.427729521943167
filename: 4_hidden Epoch 65 loss:24.425092940645822 ael:0.012631353753016867 cl:24.41246158275527
filename: 4_hidden Epoch 66 loss:24.413449604791186 ael:0.012584142232572662 cl:24.400865448245153
filename: 4_hidden Epoch 67 loss:24.39957453564272 ael:0.012516705415811133 cl:24.387057821502893
filename: 4_hidden Epoch 68 loss:24.39088394020894 ael:0.012550720091099761 cl:24.378333212457367
filename: 4_hidden Epoch 69 loss:24.37158344181282 ael:0.012512628396020326 cl:24.35907080594988
filename: 4_hidden Epoch 70 loss:24.35549019621773 ael:0.0125001931552965 cl:24.342990007799486
filename: 4_hidden Epoch 71 loss:24.338171167927072 ael:0.012470062514427702 cl:24.325701119735655
filename: 4_hidden Epoch 72 loss:24.34136216167496 ael:0.012474688303414305 cl:24.328887475614767
filename: 4_hidden Epoch 73 loss:24.331786604352324 ael:0.012496461962097086 cl:24.319290141055458
filename: 4_hidden Epoch 74 loss:24.325840747951656 ael:0.012507151526256933 cl:24.313333619461368
filename: 4_hidden Epoch 75 loss:24.31274252825903 ael:0.012463930271083286 cl:24.300278597482947
filename: 4_hidden Epoch 76 loss:24.29370417112281 ael:0.01243141883463874 cl:24.281272745068097
filename: 4_hidden Epoch 77 loss:24.29627626344421 ael:0.012470437125799306 cl:24.28380583069424
filename: 4_hidden Epoch 78 loss:24.27383152167646 ael:0.012424060464025992 cl:24.261407464525476
filename: 4_hidden Epoch 79 loss:24.273756821564174 ael:0.012436788803401344 cl:24.261320020441424
filename: 4_hidden Epoch 80 loss:24.251547981499016 ael:0.012399394855948917 cl:24.23914859220888
filename: 4_hidden Epoch 81 loss:24.24860409828011 ael:0.012418367949976774 cl:24.236185710665026
filename: 4_hidden Epoch 82 loss:24.24925668590304 ael:0.012376245680829453 cl:24.236880434991217
filename: 4_hidden Epoch 83 loss:24.239328637682956 ael:0.012408503697991532 cl:24.22692014202576
filename: 4_hidden Epoch 84 loss:24.225199689877982 ael:0.01237649596880684 cl:24.21282316766448
filename: 4_hidden Epoch 85 loss:24.224177000429304 ael:0.012367499851987429 cl:24.211809519202763
filename: 4_hidden Epoch 86 loss:24.2198218727884 ael:0.012365635291405535 cl:24.207456236104413
filename: 4_hidden Epoch 87 loss:24.204204167560366 ael:0.012335249542556553 cl:24.191868929534788
filename: 4_hidden Epoch 88 loss:24.210570751092373 ael:0.012323239319247675 cl:24.198247519324504
filename: 4_hidden Epoch 89 loss:24.20568189685322 ael:0.012332010718864387 cl:24.19334989231125
filename: 4_hidden Epoch 90 loss:24.201132472935313 ael:0.012305619854947575 cl:24.1888268577586
filename: 4_hidden Epoch 91 loss:24.198601655020564 ael:0.012313091809460427 cl:24.186288573127367
filename: 4_hidden Epoch 92 loss:24.190257478371645 ael:0.012268546526791596 cl:24.1779889306237
filename: 4_hidden Epoch 93 loss:24.185365696957238 ael:0.01231097396835182 cl:24.17305471803817
filename: 4_hidden Epoch 94 loss:24.170128664024446 ael:0.012325534451245136 cl:24.157803115638806
filename: 4_hidden Epoch 95 loss:24.167251416513956 ael:0.012307876028753969 cl:24.154943537229467
filename: 4_hidden Epoch 96 loss:24.1578549934624 ael:0.01227108463745529 cl:24.145583908245793
filename: 4_hidden Epoch 97 loss:24.146249155927446 ael:0.01230694909709507 cl:24.133942201745654
filename: 4_hidden Epoch 98 loss:24.1453800721368 ael:0.012291004437847659 cl:24.13308908151068
filename: 4_hidden Epoch 99 loss:24.13027268537143 ael:0.01226473064985071 cl:24.118007960042814
filename: 4_hidden Epoch 100 loss:24.121315615058105 ael:0.012246932038300835 cl:24.1090686834132
filename: 4_hidden Epoch 101 loss:24.10989291542455 ael:0.012219825509166428 cl:24.097673094385225
filename: 4_hidden Epoch 102 loss:24.09942105147842 ael:0.01224781082347337 cl:24.087173249814835
filename: 4_hidden Epoch 103 loss:24.081671413365 ael:0.012203978507071934 cl:24.06946742151752
filename: 4_hidden Epoch 104 loss:24.09128294930606 ael:0.012150360423664332 cl:24.079132586130406
filename: 4_hidden Epoch 105 loss:24.079062723630834 ael:0.012120476623245498 cl:24.066942254605724
filename: 4_hidden Epoch 106 loss:24.071655546798397 ael:0.012162255625493132 cl:24.059493289592297
filename: 4_hidden Epoch 107 loss:24.063643535557386 ael:0.012080254286587962 cl:24.051563292283276
filename: 4_hidden Epoch 108 loss:24.056375976130063 ael:0.012109789956114714 cl:24.044266184138866
filename: 4_hidden Epoch 109 loss:24.060989521968704 ael:0.012155410388984822 cl:24.048834121951206
filename: 4_hidden Epoch 110 loss:24.039908485052234 ael:0.012095386802134647 cl:24.02781308903868
filename: 4_hidden Epoch 111 loss:24.04949998585319 ael:0.012179349173066506 cl:24.03732063303753
filename: 4_hidden Epoch 112 loss:24.033340013944187 ael:0.01211713522788283 cl:24.02122286797857
filename: 4_hidden Epoch 113 loss:24.036845729482962 ael:0.012122682788674488 cl:24.02472303650479
filename: 4_hidden Epoch 114 loss:24.02284339359093 ael:0.012048513752467398 cl:24.01079488334707
filename: 4_hidden Epoch 115 loss:24.029705978372963 ael:0.01210290412324281 cl:24.017603070340176
filename: 4_hidden Epoch 116 loss:24.018813272494214 ael:0.011987444868514895 cl:24.006825834987296
filename: 4_hidden Epoch 117 loss:24.024846014416653 ael:0.012013823113199349 cl:24.012832187029677
filename: 4_hidden Epoch 118 loss:24.016990667283938 ael:0.012012384620503939 cl:24.004978290099686
filename: 4_hidden Epoch 119 loss:24.002457795548537 ael:0.011897433065280178 cl:23.990560357612477
filename: 4_hidden Epoch 120 loss:24.023338207188246 ael:0.011982959672788538 cl:24.011355257227354
filename: 4_hidden Epoch 121 loss:24.002621615946534 ael:0.011982316490358268 cl:23.990639310005385
filename: 4_hidden Epoch 122 loss:24.001913903116698 ael:0.01194439799815175 cl:23.989969501675542
filename: 4_hidden Epoch 123 loss:24.00415445242816 ael:0.011924728564163933 cl:23.99222972730876
filename: 4_hidden Epoch 124 loss:24.011495318393475 ael:0.011901700333535027 cl:23.999593623028755
filename: 4_hidden Epoch 125 loss:23.998632407864097 ael:0.012002969506811276 cl:23.986629421218687
filename: 4_hidden Epoch 126 loss:23.99831386262428 ael:0.011884341947231617 cl:23.986429529022754
filename: 4_hidden Epoch 127 loss:23.981609074725153 ael:0.011889030179323053 cl:23.9697200579521
filename: 4_hidden Epoch 128 loss:23.99153026112339 ael:0.011920472004484792 cl:23.979609805273142
filename: 4_hidden Epoch 129 loss:23.99664072147426 ael:0.011922213850686184 cl:23.984718502935287
filename: 4_hidden Epoch 130 loss:23.98045897026937 ael:0.011891587582566397 cl:23.968567389772648
filename: 4_hidden Epoch 131 loss:23.980208023421355 ael:0.011832838047009247 cl:23.968375199558604
filename: 4_hidden Epoch 132 loss:23.979701313734378 ael:0.011868521717958927 cl:23.967832805206257
filename: 4_hidden Epoch 133 loss:23.968818349490764 ael:0.011793241468628972 cl:23.957025109418492
filename: 4_hidden Epoch 134 loss:23.962895045621515 ael:0.01180409955491743 cl:23.951090941641496
filename: 4_hidden Epoch 135 loss:23.969491717689916 ael:0.011725429587025955 cl:23.957766288623475
filename: 4_hidden Epoch 136 loss:23.974415112700058 ael:0.011721904081381686 cl:23.962693209525867
filename: 4_hidden Epoch 137 loss:23.964148973678608 ael:0.011763633626253015 cl:23.9523853435851
filename: 4_hidden Epoch 138 loss:23.969526791282995 ael:0.011635557053090348 cl:23.957891234630836
filename: 4_hidden Epoch 139 loss:23.957123871467374 ael:0.01161148473268498 cl:23.94551237572221
filename: 4_hidden Epoch 140 loss:23.973023929158362 ael:0.011546695740911078 cl:23.96147722406426
filename: 4_hidden Epoch 141 loss:23.958737557394464 ael:0.011547074704990294 cl:23.94719047186024
filename: 4_hidden Epoch 142 loss:23.949185122491215 ael:0.011493031314087783 cl:23.937692080560804
filename: 4_hidden Epoch 143 loss:24.367568991348328 ael:0.011522340743617732 cl:24.356046648321524
filename: 4_hidden Epoch 144 loss:24.069592519392046 ael:0.011340222831981385 cl:24.05825228259953
filename: 4_hidden Epoch 145 loss:24.046465117728662 ael:0.011417697817489364 cl:24.035047393675274
filename: 4_hidden Epoch 146 loss:24.034855694069392 ael:0.011331790858344268 cl:24.023523895943214
filename: 4_hidden Epoch 147 loss:24.036639832098956 ael:0.011206386318020572 cl:24.025433443818496
filename: 4_hidden Epoch 148 loss:24.026452062197542 ael:0.01111209519765517 cl:24.015339972615724
filename: 4_hidden Epoch 149 loss:24.02328441583837 ael:0.01098063635098146 cl:24.012303772178576
filename: 4_hidden Epoch 150 loss:24.01723116412658 ael:0.011002244859149581 cl:24.006228935251997
filename: 4_hidden Epoch 151 loss:24.0290699401526 ael:0.010675880243918794 cl:24.01839407484541
filename: 4_hidden Epoch 152 loss:24.01586319412458 ael:0.01066983013279364 cl:24.005193359230855
filename: 4_hidden Epoch 153 loss:24.01046720548519 ael:0.010493992731432642 cl:23.999973202910017
filename: 4_hidden Epoch 154 loss:24.015237960609507 ael:0.010279251933198386 cl:24.004958715709115
filename: 4_hidden Epoch 155 loss:24.009834137683615 ael:0.010163587860401101 cl:23.999670544520082
filename: 4_hidden Epoch 156 loss:24.00584856772069 ael:0.010045102783120596 cl:23.995803476248675
filename: 4_hidden Epoch 157 loss:23.993145234575156 ael:0.00997803918879062 cl:23.983167198891582
filename: 4_hidden Epoch 158 loss:23.99740332784923 ael:0.009988704843851316 cl:23.987414619250174
filename: 4_hidden Epoch 159 loss:23.990289480129555 ael:0.009670877343297567 cl:23.98061860273724
filename: 4_hidden Epoch 160 loss:24.00416081077174 ael:0.00944835499504659 cl:23.99471245275335
filename: 4_hidden Epoch 161 loss:23.99085966153988 ael:0.009365278345440965 cl:23.9814943753756
filename: 4_hidden Epoch 162 loss:23.997437840820808 ael:0.009338248076417588 cl:23.98809959679319
filename: 4_hidden Epoch 163 loss:23.963620950078514 ael:0.009168875213038784 cl:23.954452088905573
filename: 4_hidden Epoch 164 loss:23.954421948678743 ael:0.009201430406687874 cl:23.945220513285896
filename: 4_hidden Epoch 165 loss:23.956521443767265 ael:0.008901986450474714 cl:23.94761945953575
filename: 4_hidden Epoch 166 loss:23.934702022516454 ael:0.008907687036614669 cl:23.925794341979238
filename: 4_hidden Epoch 167 loss:23.937330513669732 ael:0.00884690303895899 cl:23.92848361449042
filename: 4_hidden Epoch 168 loss:23.91891394137693 ael:0.008987027875244536 cl:23.909926902266488
filename: 4_hidden Epoch 169 loss:23.921456266704357 ael:0.008627675130571189 cl:23.912828605023794
filename: 4_hidden Epoch 170 loss:23.956789386867673 ael:0.008616680847216956 cl:23.94817268999643
filename: 4_hidden Epoch 171 loss:23.964569057819816 ael:0.008376937137863897 cl:23.956192125225197
filename: 4_hidden Epoch 172 loss:23.95096406717854 ael:0.00832480165237679 cl:23.94263926466145
filename: 4_hidden Epoch 173 loss:23.94957825201243 ael:0.008387917382630058 cl:23.941190342253197
filename: 4_hidden Epoch 174 loss:23.94370352041062 ael:0.008514615126939518 cl:23.935188909162555
filename: 4_hidden Epoch 175 loss:23.934870964698945 ael:0.008068972757882998 cl:23.9268019873121
filename: 4_hidden Epoch 176 loss:23.918574137308017 ael:0.008074329254643516 cl:23.910499799267644
filename: 4_hidden Epoch 177 loss:23.947041423246766 ael:0.007920547268842315 cl:23.939120871560615
filename: 4_hidden Epoch 178 loss:23.95946126106458 ael:0.0078466528322794 cl:23.951614598159686
filename: 4_hidden Epoch 179 loss:23.94949423034503 ael:0.007830480735764088 cl:23.941663747728274
filename: 4_hidden Epoch 180 loss:23.933085033607224 ael:0.007928061129728914 cl:23.925156979683116
filename: 4_hidden Epoch 181 loss:23.910549551980537 ael:0.007876723054570225 cl:23.902672821436173
filename: 4_hidden Epoch 182 loss:23.942855336630714 ael:0.007900810297251794 cl:23.93495452561681
filename: 4_hidden Epoch 183 loss:23.946279159731226 ael:0.007664961641586502 cl:23.938614202028344
filename: 4_hidden Epoch 184 loss:23.941763359203673 ael:0.007783228633284327 cl:23.93398013095624
filename: 4_hidden Epoch 185 loss:23.938311788685088 ael:0.0076505161908564535 cl:23.930661266084947
filename: 4_hidden Epoch 186 loss:23.93467986175084 ael:0.007527273030783202 cl:23.927152584760616
filename: 4_hidden Epoch 187 loss:23.94019715055602 ael:0.007712468363007835 cl:23.93248468417066
filename: 4_hidden Epoch 188 loss:23.933902301350745 ael:0.007667822798264091 cl:23.92623448442673
filename: 4_hidden Epoch 189 loss:23.93575761257074 ael:0.007272388614266709 cl:23.92848522016394
filename: 4_hidden Epoch 190 loss:23.9328464554389 ael:0.007541220077261952 cl:23.925305245279784
filename: 4_hidden Epoch 191 loss:23.934862670692517 ael:0.007413397815113689 cl:23.927449267306308
filename: 4_hidden Epoch 192 loss:23.931874215747662 ael:0.007616799981578401 cl:23.92425741383582
filename: 4_hidden Epoch 193 loss:23.926023265514296 ael:0.0073755119031096595 cl:23.918647759935634
filename: 4_hidden Epoch 194 loss:23.922964432236316 ael:0.007583618841753637 cl:23.915380824883137
filename: 4_hidden Epoch 195 loss:23.9240020607808 ael:0.0076172419232988725 cl:23.91638482746325
filename: 4_hidden Epoch 196 loss:23.925843605113577 ael:0.007762126068681398 cl:23.91808147044317
filename: 4_hidden Epoch 197 loss:23.924048606779895 ael:0.007619233420885365 cl:23.916429371389782
filename: 4_hidden Epoch 198 loss:23.92312274371725 ael:0.007524969345951571 cl:23.915597764811857
filename: 4_hidden Epoch 199 loss:23.914550024488193 ael:0.0073552662725390695 cl:23.907194742982686
filename: 4_hidden Epoch 200 loss:23.90986091263703 ael:0.007289632937686163 cl:23.902571257309393
filename: 4_hidden Epoch 201 loss:23.91254867831705 ael:0.007178716329598797 cl:23.90536996632935
filename: 4_hidden Epoch 202 loss:23.90988423840398 ael:0.007048765539698172 cl:23.9028354855845

C:\Users\linco\AppData\Local\Temp\ipykernel_38868\726915545.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
C:\Users\linco\AppData\Local\Temp\ipykernel_38868\726915545.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3         4  Label
0        0.040936  0.050504  0.043645  0.055690  0.040488      1
1        0.044410  0.022583  0.027982  0.020554  0.011846      0
2       -0.003166  0.038547  0.037465 -0.005755  0.051931      2
3        0.040678  0.054178  0.045673  0.059343  0.042214      1
4       -0.003159  0.038539  0.037457 -0.005760  0.051908      2
...           ...       ...       ...       ...       ...    ...
1896688  0.044342  0.022553  0.027963  0.020389  0.011839      0
1896689 -0.003167  0.038549  0.037467 -0.005754  0.051939      2
1896690 -0.003169  0.038551  0.037469 -0.005753  0.051945      2
1896691  0.044447  0.022600  0.027992  0.020643  0.011850      0
1896692 -0.003308  0.038717  0.037646 -0.005655  0.052472      2

[1896693 rows x 6 columns]

Davies-Bouldin Score: 0.6661927264756833

               0         1         2         3         4  Label
0       0.044618  0.021382  0.027538  0.020797  0.011985    0.0
1      -0.003156  0.038538  0.037456 -0.005758  0.051905    2.0
2       0.040829  0.051269  0.043903  0.056050  0.039959    1.0
3       0.002131 -0.004353 -0.004319  0.062394  0.038628    3.0
4       0.040810  0.050269  0.044150  0.054283  0.040848    1.0
...          ...       ...       ...       ...       ...    ...
519951  0.041027  0.052795  0.045369  0.055943  0.041370    2.0
519952  0.037461  0.047005  0.040082  0.054668  0.039923    1.0
519953  0.044359  0.022561  0.027968  0.020431  0.011841    3.0
519954  0.041640  0.050329  0.044123  0.054421  0.040214    0.0
519955  0.002556 -0.004904 -0.004486  0.064242  0.039436    0.0

[519956 rows x 6 columns]

               0         1         2         3         4  Label
0       0.044403  0.022580  0.027980  0.020537  0.011846    0.0
1       0.044618  0.021338  0.027524  0.020936  0.012050    0.0
2       0.034601  0.042495  0.036803  0.045112  0.035141    1.0
3       0.038560  0.033794  0.033685  0.039299  0.031168    1.0
4       0.044254  0.021265  0.027556  0.021774  0.013484    NaN
...          ...       ...       ...       ...       ...    ...
649942  0.040880  0.050751  0.044360  0.054760  0.041089    3.0
649943  0.044559  0.021696  0.027956  0.021677  0.013485    1.0
649944  0.044497  0.021470  0.027772  0.021558  0.013378    0.0
649945  0.000816 -0.005546 -0.005280  0.062453  0.039590    4.0
649946 -0.001538  0.037679  0.036484 -0.003386  0.052279    0.0

[649947 rows x 6 columns]

5_hidden
cuda
[0.0, 1.0, 2.0, 3.0, 4.0]
pick completo
82 5
filename: 5_hidden Epoch 1 loss:37.3078647347755 ael:0.022952952018674373 cl:37.28491178350106
filename: 5_hidden Epoch 2 loss:34.34223191905996 ael:0.015959335133160044 cl:34.32627257474358
filename: 5_hidden Epoch 3 loss:34.0305375038609 ael:0.014371933120223526 cl:34.01616561923457
filename: 5_hidden Epoch 4 loss:33.774849486902745 ael:0.013896409805280816 cl:33.760953083817796
filename: 5_hidden Epoch 5 loss:33.553955705925375 ael:0.013364364976106475 cl:33.54059131928467
filename: 5_hidden Epoch 6 loss:33.367965200979214 ael:0.013279428173421507 cl:33.354685756621365
filename: 5_hidden Epoch 7 loss:33.213343391155504 ael:0.013142870443793777 cl:33.200200538691604
filename: 5_hidden Epoch 8 loss:33.07252672797409 ael:0.012950009201180532 cl:33.05957670601526
filename: 5_hidden Epoch 9 loss:32.95249436959323 ael:0.012760535463533016 cl:32.93973384755753
filename: 5_hidden Epoch 10 loss:32.83543850857891 ael:0.012587640925385297 cl:32.822850865017074
filename: 5_hidden Epoch 11 loss:32.73370228395974 ael:0.012444374295972298 cl:32.72125792444662
filename: 5_hidden Epoch 12 loss:32.650561176339494 ael:0.012327156849077099 cl:32.63823400043842
filename: 5_hidden Epoch 13 loss:32.5757377531539 ael:0.012235101006085035 cl:32.563502647441226
filename: 5_hidden Epoch 14 loss:32.51308510046414 ael:0.012088867656406013 cl:32.500996252986845
filename: 5_hidden Epoch 15 loss:32.456416201908446 ael:0.011952312360322796 cl:32.44446388434331
filename: 5_hidden Epoch 16 loss:32.39837522145154 ael:0.011874517977993397 cl:32.38650069055975
filename: 5_hidden Epoch 17 loss:32.352756208648 ael:0.011809353337676829 cl:32.34094685864883
filename: 5_hidden Epoch 18 loss:32.31004453468417 ael:0.011753755425351087 cl:32.298290784226324
filename: 5_hidden Epoch 19 loss:32.27125070882747 ael:0.011689705085669654 cl:32.25956102452919
filename: 5_hidden Epoch 20 loss:32.23652149831527 ael:0.011481152932012406 cl:32.22504035596599
filename: 5_hidden Epoch 21 loss:32.208039748615846 ael:0.011589253132824443 cl:32.1964505090906
filename: 5_hidden Epoch 22 loss:32.17989761591075 ael:0.011618885744027408 cl:32.16827875049991
filename: 5_hidden Epoch 23 loss:32.15808370253067 ael:0.011634731704230704 cl:32.14644896837363
filename: 5_hidden Epoch 24 loss:32.1411881439795 ael:0.011698834471274323 cl:32.12948930703731
filename: 5_hidden Epoch 25 loss:32.12030381372209 ael:0.011770246793932805 cl:32.10853358456092
filename: 5_hidden Epoch 26 loss:32.10807287299768 ael:0.011791787237517722 cl:32.096281087322225
filename: 5_hidden Epoch 27 loss:32.08569725107994 ael:0.011772146560150831 cl:32.07392509860514
filename: 5_hidden Epoch 28 loss:32.07632689051062 ael:0.01177893803514089 cl:32.06454795995174
filename: 5_hidden Epoch 29 loss:32.05659035260545 ael:0.011823686389578116 cl:32.04476666697019
filename: 5_hidden Epoch 30 loss:32.04115913631527 ael:0.01175524872543812 cl:32.02940386026027
filename: 5_hidden Epoch 31 loss:32.0258973571011 ael:0.011781473715382879 cl:32.014115900314835
filename: 5_hidden Epoch 32 loss:32.0115618586012 ael:0.011739751293793035 cl:31.999822100531816
filename: 5_hidden Epoch 33 loss:31.999715804114594 ael:0.011892368023548365 cl:31.987823435615752
filename: 5_hidden Epoch 34 loss:31.99070771770017 ael:0.011804445348184782 cl:31.978903254401445
filename: 5_hidden Epoch 35 loss:31.975519160106813 ael:0.01180200075069447 cl:31.963717170444866
filename: 5_hidden Epoch 36 loss:31.965382792925023 ael:0.011738224946657596 cl:31.953644588626354
filename: 5_hidden Epoch 37 loss:31.952707482699044 ael:0.011808631500776753 cl:31.940898847838213
filename: 5_hidden Epoch 38 loss:31.948525555083343 ael:0.011881598895750408 cl:31.936643985032685
filename: 5_hidden Epoch 39 loss:31.937124443429845 ael:0.01192600118406282 cl:31.92519843196822
filename: 5_hidden Epoch 40 loss:31.92807553120871 ael:0.012000060413979226 cl:31.916075478276262
filename: 5_hidden Epoch 41 loss:31.908313139385335 ael:0.011834197425238094 cl:31.89647893844597
filename: 5_hidden Epoch 42 loss:31.899219695597903 ael:0.011692840873540285 cl:31.887526867602155
filename: 5_hidden Epoch 43 loss:31.88568677578226 ael:0.011703933035915397 cl:31.873982849290137
filename: 5_hidden Epoch 44 loss:31.863749412055792 ael:0.011295870658842978 cl:31.852453548294285
filename: 5_hidden Epoch 45 loss:31.85966172821706 ael:0.01093583169188268 cl:31.848725872518745
filename: 5_hidden Epoch 46 loss:31.851165695885378 ael:0.010956352163915092 cl:31.84020933125889
filename: 5_hidden Epoch 47 loss:31.84898395951542 ael:0.010951176979535468 cl:31.83803279008964
filename: 5_hidden Epoch 48 loss:31.83959524576327 ael:0.010737288765153463 cl:31.828857980180643
filename: 5_hidden Epoch 49 loss:31.82657603099979 ael:0.010746789993218443 cl:31.815829249334595
filename: 5_hidden Epoch 50 loss:31.821355077798938 ael:0.010470647651794793 cl:31.81088443250858
filename: 5_hidden Epoch 51 loss:31.821872914500684 ael:0.010325137520179608 cl:31.811547789768536
filename: 5_hidden Epoch 52 loss:31.806499229517552 ael:0.010354686437306741 cl:31.796144535716444
filename: 5_hidden Epoch 53 loss:31.800426067125027 ael:0.010338225993586879 cl:31.790087840757835
filename: 5_hidden Epoch 54 loss:31.798848151221527 ael:0.01034276275886365 cl:31.788505397366514
filename: 5_hidden Epoch 55 loss:31.785723291319147 ael:0.01031018530212596 cl:31.775413107015066
filename: 5_hidden Epoch 56 loss:31.78366796680415 ael:0.010208824159144614 cl:31.773459153713
filename: 5_hidden Epoch 57 loss:31.780928274612013 ael:0.009907931867337606 cl:31.77102033801997
filename: 5_hidden Epoch 58 loss:31.779752095070805 ael:0.00960758069790588 cl:31.770144506723994
filename: 5_hidden Epoch 59 loss:31.765503343368973 ael:0.009764408568564137 cl:31.755738955656923
filename: 5_hidden Epoch 60 loss:31.754636741517977 ael:0.009456442654016371 cl:31.745180306559064
filename: 5_hidden Epoch 61 loss:31.755347882509817 ael:0.00958669712058081 cl:31.74576118625132
filename: 5_hidden Epoch 62 loss:31.74551690945421 ael:0.009450015964574381 cl:31.7360668778713
filename: 5_hidden Epoch 63 loss:31.753302456767965 ael:0.009398865936633983 cl:31.74390360664582
filename: 5_hidden Epoch 64 loss:31.73459017916538 ael:0.009443971603225637 cl:31.725146223675846
filename: 5_hidden Epoch 65 loss:31.730788277382338 ael:0.009108888515207508 cl:31.721679396373425
filename: 5_hidden Epoch 66 loss:31.734570572729595 ael:0.009285636269819892 cl:31.725284922011436
filename: 5_hidden Epoch 67 loss:31.71834249463591 ael:0.008784119737463403 cl:31.709558376122555
filename: 5_hidden Epoch 68 loss:31.71906510648441 ael:0.00918127529544124 cl:31.709883842017486
filename: 5_hidden Epoch 69 loss:31.717653647835533 ael:0.009124008845813034 cl:31.70852965031393
filename: 5_hidden Epoch 70 loss:31.711588224714347 ael:0.008906076129861561 cl:31.70268214435662
filename: 5_hidden Epoch 71 loss:31.705290967639826 ael:0.008833263925052464 cl:31.69645768676938
filename: 5_hidden Epoch 72 loss:31.71343485514323 ael:0.008960146028667702 cl:31.704474715397666
filename: 5_hidden Epoch 73 loss:31.703164878236667 ael:0.008759084629497465 cl:31.694405808347835
filename: 5_hidden Epoch 74 loss:31.691542769581858 ael:0.008598366301393953 cl:31.682944378085114
filename: 5_hidden Epoch 75 loss:31.688413048541822 ael:0.008575735436701998 cl:31.67983728227564
filename: 5_hidden Epoch 76 loss:31.6848906029157 ael:0.008603414627349674 cl:31.676287186198607
filename: 5_hidden Epoch 77 loss:31.680602268066856 ael:0.008552666162340138 cl:31.672049605042286
filename: 5_hidden Epoch 78 loss:31.671050123837357 ael:0.008301073121152735 cl:31.662749044417396
filename: 5_hidden Epoch 79 loss:31.675376633832396 ael:0.008190931761495178 cl:31.667185697456933
filename: 5_hidden Epoch 80 loss:31.67235775641888 ael:0.008109834096988306 cl:31.664247901612228
filename: 5_hidden Epoch 81 loss:31.674833530630753 ael:0.00808991172538033 cl:31.666743606255597
filename: 5_hidden Epoch 82 loss:31.659373809292305 ael:0.007954691254255485 cl:31.651419112272652
filename: 5_hidden Epoch 83 loss:31.656565741797728 ael:0.00800793786803265 cl:31.64855780711848
filename: 5_hidden Epoch 84 loss:31.653649533458204 ael:0.007937098600970905 cl:31.645712441144347
filename: 5_hidden Epoch 85 loss:31.654180762921573 ael:0.007914623620120624 cl:31.64626614370116
filename: 5_hidden Epoch 86 loss:31.642225797982828 ael:0.007852578993656515 cl:31.634373204218583
filename: 5_hidden Epoch 87 loss:31.64805098861852 ael:0.007854858098885458 cl:31.640196140971106
filename: 5_hidden Epoch 88 loss:31.642334659131276 ael:0.007770133065357841 cl:31.634564531665315
filename: 5_hidden Epoch 89 loss:31.633895470202702 ael:0.007663533531985938 cl:31.62623191619377
filename: 5_hidden Epoch 90 loss:31.62971004765941 ael:0.007670621763674541 cl:31.62203941457909
filename: 5_hidden Epoch 91 loss:31.624021455491487 ael:0.007707125623538496 cl:31.61631432781661
filename: 5_hidden Epoch 92 loss:31.624778546117785 ael:0.007571210207854151 cl:31.617207329476308
filename: 5_hidden Epoch 93 loss:31.622882066367 ael:0.0074839778740879775 cl:31.615398079699805
filename: 5_hidden Epoch 94 loss:31.609335246196466 ael:0.007449404965189218 cl:31.6018858524099
filename: 5_hidden Epoch 95 loss:31.616721859476005 ael:0.007371329628953693 cl:31.609350507333325
filename: 5_hidden Epoch 96 loss:31.60788871149075 ael:0.007253051045910624 cl:31.60063567037127
filename: 5_hidden Epoch 97 loss:31.609033346997876 ael:0.007332059722013152 cl:31.601701296942977
filename: 5_hidden Epoch 98 loss:31.59464781416983 ael:0.007243876864996994 cl:31.587403938372344
filename: 5_hidden Epoch 99 loss:31.594979969402182 ael:0.00725026009008215 cl:31.587729688820023
filename: 5_hidden Epoch 100 loss:31.590114398638878 ael:0.007141345763392838 cl:31.58297307311696
filename: 5_hidden Epoch 101 loss:31.58880749481291 ael:0.007090536595960957 cl:31.5817169506875
filename: 5_hidden Epoch 102 loss:31.586721854630156 ael:0.007008197367836041 cl:31.579713669274017
filename: 5_hidden Epoch 103 loss:31.57524014035802 ael:0.006891907678833594 cl:31.568348231895516
filename: 5_hidden Epoch 104 loss:31.58018538213492 ael:0.006981909296148402 cl:31.573203470013166
filename: 5_hidden Epoch 105 loss:31.5717186737624 ael:0.006916489074733943 cl:31.564802170269363
filename: 5_hidden Epoch 106 loss:31.56698721937802 ael:0.006916638746663217 cl:31.560070584408464
filename: 5_hidden Epoch 107 loss:31.560991230414807 ael:0.006843241801850428 cl:31.554147986576865
filename: 5_hidden Epoch 108 loss:31.558594608823398 ael:0.006825070444275297 cl:31.551769556170434
filename: 5_hidden Epoch 109 loss:31.55702461203233 ael:0.006801769777752756 cl:31.55022284340119
filename: 5_hidden Epoch 110 loss:31.558846690160543 ael:0.006793517508057502 cl:31.552053175437397
filename: 5_hidden Epoch 111 loss:31.550596130592726 ael:0.006832667389482898 cl:31.543763454649497
filename: 5_hidden Epoch 112 loss:31.537835972465242 ael:0.006701201293915547 cl:31.531134763179537
filename: 5_hidden Epoch 113 loss:31.532430675568573 ael:0.006715967757595269 cl:31.525714698182956
filename: 5_hidden Epoch 114 loss:31.530176409238198 ael:0.006681767510821569 cl:31.52349464439043
filename: 5_hidden Epoch 115 loss:31.517676552547602 ael:0.0066411323694751615 cl:31.511035427091628
filename: 5_hidden Epoch 116 loss:31.51591867722061 ael:0.006631000893619709 cl:31.50928766700448
filename: 5_hidden Epoch 117 loss:31.51375624489045 ael:0.006673830472838991 cl:31.50708241652879
filename: 5_hidden Epoch 118 loss:31.497082416322183 ael:0.006688858357183396 cl:31.49039356864655
filename: 5_hidden Epoch 119 loss:31.4796857425346 ael:0.006738253921849982 cl:31.472947485044283
filename: 5_hidden Epoch 120 loss:31.46804278217355 ael:0.00667306134518069 cl:31.461369719662613
filename: 5_hidden Epoch 121 loss:31.441636127301006 ael:0.006780333788116274 cl:31.4348558001422
filename: 5_hidden Epoch 122 loss:31.426058764530485 ael:0.006782366700331964 cl:31.419276388685788
filename: 5_hidden Epoch 123 loss:31.403331160251874 ael:0.0069660428674833815 cl:31.39636511405896
filename: 5_hidden Epoch 124 loss:31.36760699038785 ael:0.006958289372499487 cl:31.360648708822456
filename: 5_hidden Epoch 125 loss:31.35757225925027 ael:0.006976901441569482 cl:31.35059535967077
filename: 5_hidden Epoch 126 loss:31.33404490162386 ael:0.007078535208599628 cl:31.32696636787839
filename: 5_hidden Epoch 127 loss:31.31646627795221 ael:0.007101231188720147 cl:31.309365041498946
filename: 5_hidden Epoch 128 loss:31.287724390691984 ael:0.007064404681183724 cl:31.280659987854875
filename: 5_hidden Epoch 129 loss:31.259905845645847 ael:0.007060133424807195 cl:31.252845707343518
filename: 5_hidden Epoch 130 loss:31.243797455322326 ael:0.007115230053674259 cl:31.236682241976055
filename: 5_hidden Epoch 131 loss:31.223695796326073 ael:0.007070244040710697 cl:31.216625556401112
filename: 5_hidden Epoch 132 loss:31.22898697019621 ael:0.007202165741482607 cl:31.221784796872086
filename: 5_hidden Epoch 133 loss:31.216513116743574 ael:0.007199338198227213 cl:31.20931378847739
filename: 5_hidden Epoch 134 loss:31.199021087732884 ael:0.0072033980762487865 cl:31.191817692146696
filename: 5_hidden Epoch 135 loss:31.197629620558168 ael:0.007024520439871209 cl:31.190605100183756
filename: 5_hidden Epoch 136 loss:31.193157839340742 ael:0.007057579024683396 cl:31.18610026107405
filename: 5_hidden Epoch 137 loss:31.17863199665064 ael:0.007050603967488311 cl:31.171581381943824
filename: 5_hidden Epoch 138 loss:31.178545451293374 ael:0.0069674519591119664 cl:31.17157799689304
filename: 5_hidden Epoch 139 loss:31.183261940363064 ael:0.006914428630265981 cl:31.176347513259895
filename: 5_hidden Epoch 140 loss:31.164733220884095 ael:0.006878527158418242 cl:31.157854686870415
filename: 5_hidden Epoch 141 loss:31.174822557976185 ael:0.006838199326008236 cl:31.167984356732276
filename: 5_hidden Epoch 142 loss:31.164163600277394 ael:0.006841623109335686 cl:31.15732198205269
filename: 5_hidden Epoch 143 loss:31.142285173717596 ael:0.006861150941106705 cl:31.135424008221534
filename: 5_hidden Epoch 144 loss:31.140725524598068 ael:0.006809171797168417 cl:31.13391634538689
filename: 5_hidden Epoch 145 loss:31.136325535663886 ael:0.006653411887427458 cl:31.129672124666396
filename: 5_hidden Epoch 146 loss:31.129262403453414 ael:0.0066352325755504845 cl:31.122627180353987
filename: 5_hidden Epoch 147 loss:31.133819304446995 ael:0.006615225639302468 cl:31.127204068126144
filename: 5_hidden Epoch 148 loss:31.12392436947393 ael:0.00655141140823585 cl:31.117372960776663
filename: 5_hidden Epoch 149 loss:31.13413495515028 ael:0.006589219628813516 cl:31.12754574789313
filename: 5_hidden Epoch 150 loss:31.119163443219303 ael:0.0067076421690603115 cl:31.112455791114645
filename: 5_hidden Epoch 151 loss:31.111134372750623 ael:0.006410410584847969 cl:31.104723978253904
filename: 5_hidden Epoch 152 loss:31.109951856980356 ael:0.006328327051427624 cl:31.10362353200457
filename: 5_hidden Epoch 153 loss:31.096269588761587 ael:0.0063502162789851645 cl:31.08991937717154
filename: 5_hidden Epoch 154 loss:31.100406524173618 ael:0.006331060405459268 cl:31.094075462608018
filename: 5_hidden Epoch 155 loss:31.1087542876183 ael:0.006381673165741466 cl:31.102372625436413
filename: 5_hidden Epoch 156 loss:31.09781525723163 ael:0.006017096272331778 cl:31.091798162061203
filename: 5_hidden Epoch 157 loss:31.098333700134038 ael:0.0060377725942728925 cl:31.092295917133463
filename: 5_hidden Epoch 158 loss:31.081232416518272 ael:0.006019649064307735 cl:31.075212754738384
filename: 5_hidden Epoch 159 loss:31.07790703869758 ael:0.005958048307397854 cl:31.071948989631505
filename: 5_hidden Epoch 160 loss:31.092010888719958 ael:0.005901061214991776 cl:31.086109842237494
filename: 5_hidden Epoch 161 loss:31.09947286246153 ael:0.005715442282238958 cl:31.093757411049598
filename: 5_hidden Epoch 162 loss:31.06626823440319 ael:0.005595768868243611 cl:31.060672467944073
filename: 5_hidden Epoch 163 loss:31.0680621272528 ael:0.005528961720769552 cl:31.062533173403793
filename: 5_hidden Epoch 164 loss:31.075743925506877 ael:0.0054608486367619755 cl:31.070283069920503
filename: 5_hidden Epoch 165 loss:31.06621735252106 ael:0.005399795071758855 cl:31.06081755369065
filename: 5_hidden Epoch 166 loss:31.070035848049386 ael:0.005272995536068866 cl:31.064762863016433
filename: 5_hidden Epoch 167 loss:31.074735310440403 ael:0.005319299878037142 cl:31.06941601327345
filename: 5_hidden Epoch 168 loss:31.065147936138715 ael:0.005402146928252654 cl:31.059745796556722
filename: 5_hidden Epoch 169 loss:31.067120857745895 ael:0.005236378742108173 cl:31.06188447436695
filename: 5_hidden Epoch 170 loss:31.057383556544398 ael:0.005158361959741609 cl:31.05222519227051
filename: 5_hidden Epoch 171 loss:31.05505617048751 ael:0.005170805391556102 cl:31.04988535444822
filename: 5_hidden Epoch 172 loss:31.050376083039698 ael:0.0050481988534038765 cl:31.045327895148993
filename: 5_hidden Epoch 173 loss:31.04955813381133 ael:0.005104403429357899 cl:31.04445372139627
filename: 5_hidden Epoch 174 loss:31.049609755718432 ael:0.005021136798375437 cl:31.044588619121363
filename: 5_hidden Epoch 175 loss:31.049787385659755 ael:0.005051676378193794 cl:31.044735715519554
filename: 5_hidden Epoch 176 loss:31.058214297498875 ael:0.004959257034922376 cl:31.05325504830763
filename: 5_hidden Epoch 177 loss:31.05138606687064 ael:0.004912631138588303 cl:31.046473432678944
filename: 5_hidden Epoch 178 loss:31.04003102224135 ael:0.0048628058427245945 cl:31.035168201685067
filename: 5_hidden Epoch 179 loss:31.051419458619367 ael:0.004805190084194412 cl:31.04661426985575
filename: 5_hidden Epoch 180 loss:31.056346759016673 ael:0.004950275401683852 cl:31.05139648356736
filename: 5_hidden Epoch 181 loss:31.04216089629 ael:0.004844142024149427 cl:31.037316731312544
filename: 5_hidden Epoch 182 loss:31.040007180853 ael:0.0048635554001705585 cl:31.035143618863067
filename: 5_hidden Epoch 183 loss:31.03320085703006 ael:0.004843321065592673 cl:31.028357531624085
filename: 5_hidden Epoch 184 loss:31.041646129564956 ael:0.004794077909389233 cl:31.036852044932424
filename: 5_hidden Epoch 185 loss:31.0414211023388 ael:0.00478152210451846 cl:31.0366395939048
filename: 5_hidden Epoch 186 loss:31.034526128125624 ael:0.0048242939020732185 cl:31.029701826432724
filename: 5_hidden Epoch 187 loss:31.035749132559253 ael:0.004723133976126006 cl:31.031025980917
filename: 5_hidden Epoch 188 loss:31.032052932262186 ael:0.004719570215210476 cl:31.02733336617241
filename: 5_hidden Epoch 189 loss:31.032041737506216 ael:0.0046710885001015395 cl:31.02737063553931
filename: 5_hidden Epoch 190 loss:31.02874094673356 ael:0.004663987104138539 cl:31.024076952481142
filename: 5_hidden Epoch 191 loss:31.028429696737163 ael:0.004645893054247152 cl:31.023783792244984
filename: 5_hidden Epoch 192 loss:31.03534096183007 ael:0.004571425164306875 cl:31.03076954958534
filename: 5_hidden Epoch 193 loss:31.027767693215786 ael:0.004624010536018144 cl:31.023143680033456
filename: 5_hidden Epoch 194 loss:31.026213648752414 ael:0.004589319960060582 cl:31.021624312032213
filename: 5_hidden Epoch 195 loss:31.03814639791604 ael:0.004587824004259766 cl:31.03355856988889
filename: 5_hidden Epoch 196 loss:31.026238795045206 ael:0.004434467396553989 cl:31.021804327802784
filename: 5_hidden Epoch 197 loss:31.018611996236075 ael:0.004448870164897075 cl:31.014163122454164
filename: 5_hidden Epoch 198 loss:31.02415280410188 ael:0.0044076480924627355 cl:31.019745138817264
filename: 5_hidden Epoch 199 loss:31.027924363921862 ael:0.004376681348201619 cl:31.02354770173937
filename: 5_hidden Epoch 200 loss:31.01610837248028 ael:0.004304203423712695 cl:31.01180416982436
filename: 5_hidden Epoch 201 loss:31.01920624709024 ael:0.00424792797478711 cl:31.01495832107972
filename: 5_hidden Epoch 202 loss:31.018619794671846 ael:0.00430288888259086 cl:31.01431690772022

C:\Users\linco\AppData\Local\Temp\ipykernel_38868\726915545.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
C:\Users\linco\AppData\Local\Temp\ipykernel_38868\726915545.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3         4  Label
0        0.028090  0.065904  0.039731  0.047412  0.024816      1
1        0.027743  0.019189  0.040657  0.031953  0.020173      0
2        0.053803  0.025134  0.051216  0.050322  0.067216      2
3        0.029566  0.062612  0.039718  0.045428  0.025543      1
4        0.063340  0.041928  0.026914 -0.022400  0.037240      4
...           ...       ...       ...       ...       ...    ...
2079255  0.027415  0.019021  0.040525  0.032518  0.020109      0
2079256  0.053804  0.025131  0.051217  0.050323  0.067217      2
2079257  0.053804  0.025129  0.051218  0.050324  0.067218      2
2079258  0.027862  0.019271  0.040737  0.031750  0.020196      0
2079259  0.053823  0.024944  0.051297  0.050428  0.067278      2

[2079260 rows x 6 columns]

Davies-Bouldin Score: 0.11737105721729461

               0         1         2         3         4  Label
0       0.027459  0.018930  0.039997  0.031509  0.020446    0.0
1       0.053802  0.025143  0.051211  0.050315  0.067212    2.0
2       0.029741  0.063558  0.038777  0.045672  0.025925    1.0
3       0.015780  0.027502 -0.018497  0.039008  0.052089    3.0
4       0.028780  0.064986  0.039306  0.046604  0.025122    1.0
...          ...       ...       ...       ...       ...    ...
519951  0.029358  0.063938  0.038582  0.046586  0.026220    2.0
519952  0.064677  0.050922  0.025506 -0.022787  0.040094    1.0
519953  0.027579  0.019077  0.040548  0.032231  0.020141    3.0
519954  0.028555  0.063937  0.039471  0.046227  0.024815    0.0
519955  0.016643  0.027590 -0.014911  0.037822  0.050400    0.0

[519956 rows x 6 columns]

               0         1         2         3         4  Label
0       0.027720  0.019174  0.040642  0.031992  0.020168    0.0
1       0.027410  0.018898  0.040043  0.031583  0.020417    0.0
2       0.030512  0.064333  0.038501  0.044341  0.026139    1.0
3       0.029777  0.061040  0.041448  0.052908  0.030505    1.0
4       0.027305  0.019440  0.039714  0.031620  0.020870    NaN
...          ...       ...       ...       ...       ...    ...
649942  0.028899  0.065014  0.039252  0.046553  0.025263    3.0
649943  0.027474  0.019379  0.040063  0.031715  0.020979    1.0
649944  0.027385  0.019455  0.040020  0.031736  0.020854    0.0
649945  0.016651  0.026822 -0.016936  0.038857  0.051887    4.0
649946  0.054495  0.024108  0.054129  0.054860  0.070510    0.0

[649947 rows x 6 columns]