In [1]:
import torch
from torch import nn, optim
import torch.nn.functional as F
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.decomposition import PCA
from scipy.stats import chi2
from sklearn.mixture import GaussianMixture
from collections import deque, defaultdict

# CAE

In [2]:
train = pd.read_csv('../../train_CADE_cod.csv')
val = pd.read_csv('../../val_CADE_cod.csv')
test = pd.read_csv('../../test_CADE_cod.csv')

In [3]:
classes_out = ['Infilteration','DoS attacks-SlowHTTPTest']
train = train.drop(index=train[train['Label'].isin(classes_out)].index)
val = val.drop(index=val[val['Label'].isin(classes_out)].index)
test = test.drop(index=test[test['Label'].isin(classes_out)].index)

In [4]:
train['Label'] = train['Label'].replace('FTP-BruteForce','BruteForce')
train['Label'] = train['Label'].replace('SSH-Bruteforce','BruteForce')
train['Label'] = train['Label'].replace('DoS attacks-GoldenEye','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Slowloris','DoS')
# train['Label'] = train['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Hulk','DoS')
train['Label'] = train['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
train['Label'] = train['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
train['Label'] = train['Label'].replace('DDOS attack-HOIC','DDoS')
train['Label'] = train['Label'].replace('Brute Force -Web','Web')
train['Label'] = train['Label'].replace('Brute Force -XSS','Web')
train['Label'] = train['Label'].replace('SQL Injection','Web')


val['Label'] = val['Label'].replace('FTP-BruteForce','BruteForce')
val['Label'] = val['Label'].replace('SSH-Bruteforce','BruteForce')
val['Label'] = val['Label'].replace('DoS attacks-GoldenEye','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Slowloris','DoS')
# val['Label'] = val['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Hulk','DoS')
val['Label'] = val['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
val['Label'] = val['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
val['Label'] = val['Label'].replace('DDOS attack-HOIC','DDoS')
val['Label'] = val['Label'].replace('Brute Force -Web','Web')
val['Label'] = val['Label'].replace('Brute Force -XSS','Web')
val['Label'] = val['Label'].replace('SQL Injection','Web')


test['Label'] = test['Label'].replace('FTP-BruteForce','BruteForce')
test['Label'] = test['Label'].replace('SSH-Bruteforce','BruteForce')
test['Label'] = test['Label'].replace('DoS attacks-GoldenEye','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Slowloris','DoS')
# test['Label'] = test['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Hulk','DoS')
test['Label'] = test['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
test['Label'] = test['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
test['Label'] = test['Label'].replace('DDOS attack-HOIC','DDoS')
test['Label'] = test['Label'].replace('Brute Force -Web','Web')
test['Label'] = test['Label'].replace('Brute Force -XSS','Web')
test['Label'] = test['Label'].replace('SQL Injection','Web')

In [20]:
len(test['Label'].values)

649947

In [5]:
labels_str = [i for i in train['Label'].value_counts().index]
print(labels_str)

for i, l in enumerate(labels_str):
    train['Label'] = train['Label'].replace(l, i)
    val['Label'] = val['Label'].replace(l, i)
    test['Label'] = test['Label'].replace(l, i)

['DDoS', 'Benign', 'DoS', 'BruteForce', 'Bot', 'Web']

C:\Users\linco\AppData\Local\Temp\ipykernel_50728\2307520911.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train['Label'] = train['Label'].replace(l, i)
C:\Users\linco\AppData\Local\Temp\ipykernel_50728\2307520911.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  val['Label'] = val['Label'].replace(l, i)
C:\Users\linco\AppData\Local\Temp\ipykernel_50728\2307520911.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['Label'] = test['Label'].replace(l, i)

In [16]:
test['Label']

0         0
1         0
2         1
3         1
5         0
         ..
710046    1
710047    0
710048    0
710049    3
710050    2
Name: Label, Length: 649947, dtype: int64

# CAE CADE (margin 10 e lambda 0.1)

In [6]:
def pick_pair(embeddings, labels, pick_embeddings, pick_labels):
    """
    Gera todos os pares entre embeddings e pick_embeddings,
    com labels_pair indicando se os pares são positivos (0) ou negativos (1).
    """
    N, D = embeddings.shape
    M = pick_embeddings.shape[0]

    # Expande para todas as combinações possíveis
    A = embeddings.unsqueeze(0).expand(M, N, D).reshape(M * N, D)
    B = pick_embeddings.unsqueeze(1).expand(M, N, D).reshape(M * N, D)

    labels_exp = labels.unsqueeze(0).expand(M, N)
    pick_labels_exp = pick_labels.unsqueeze(1).expand(M, N)
    labels_pair = (labels_exp != pick_labels_exp).reshape(-1).float()

    return A, B, labels_pair

def ContrastiveLoss(input1, input2, y, margin=1.0):
    # y = 0 quando input1 e input2 são da mesma classe e y = 1 caso contrário
    diff = input1 - input2
    dist_sq = torch.sum(torch.pow(diff,2),1)
    dist = torch.sqrt(dist_sq + 1e-10) # Soma 1e-10 pois se o sqrt der 0 o gradiente da NaN
    mdist = margin - dist
    mdist = F.relu(mdist)
    loss = ((1-y) * dist * dist) + (y * mdist * mdist)
    return torch.mean(loss)

def AEContrastive(input, output, embeddings, labels, pick_encoded, pick_labels, margin=1.0, lambda1=1.0):
    mseloss = nn.MSELoss()
    ae_loss = mseloss(input,output)

    A, B, labels_pair = pick_pair(embeddings, labels, pick_encoded, pick_labels)
    contrastive_loss = ContrastiveLoss(A, B, labels_pair, margin=margin)
    return ae_loss + contrastive_loss * lambda1, ae_loss, contrastive_loss

In [7]:
class contrastive_ae(nn.Module):
    def __init__(self, input_neurons, neurons):
        super().__init__()
        self.encoder0 = nn.Linear(input_neurons,64)
        self.encoder1 = nn.Linear(64,32)
        self.encoder2 = nn.Linear(32,16)
        self.encoder3 = nn.Linear(16,neurons)

        self.decoder0 = nn.Linear(neurons,16)
        self.decoder1 = nn.Linear(16,32)
        self.decoder2 = nn.Linear(32,64)
        self.decoder3 = nn.Linear(64,input_neurons)

        self.activation0 = nn.ReLU()
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X)
        encoded = X
        X = self.activation0(self.decoder0(X))
        X = self.activation0(self.decoder1(X))
        X = self.activation0(self.decoder2(X))
        X = self.decoder3(X)


        return X, encoded

In [8]:
class encoder(nn.Module):
    def __init__(self, model):
        super().__init__()
        self.encoder0 = list(model.children())[0]
        self.encoder1 = list(model.children())[1]
        self.encoder2 = list(model.children())[2]
        self.encoder3 = list(model.children())[3]
        self.activation0 = list(model.children())[8]
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X)
        return X

In [9]:
from torch.utils.data import Dataset, DataLoader,TensorDataset
import random
def build_class_reference_batches(X_train, y_train, batch_size=512):
    classes = torch.unique(y_train).tolist()
    n_classes = len(classes)
    total_samples = len(X_train)
    dataset = TensorDataset(X_train, y_train)
    train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    

    print(classes)

    # Mapeia cada classe para seus índices
    class_to_indices = {
        int(cls.item()): (y_train == cls).nonzero(as_tuple=True)[0].tolist()
        for cls in torch.unique(y_train)
    }

    reference_list = []
    total_batches = len(train_loader)

    for batch_idx in range(total_batches):
        start = batch_idx * batch_size
        end = min(start + batch_size, total_samples)
        batch_indices = set(range(start, end))

        class_samples = []
        for cls in classes:
            candidates = [i for i in class_to_indices[cls] if i not in batch_indices]
            if not candidates:
                raise ValueError(f"Classe {cls} não possui amostras fora do batch {batch_idx}")
            chosen = candidates[torch.randint(len(candidates), (1,)).item()]
            class_samples.append(chosen)

        reference_list.append(class_samples)


    return train_loader, reference_list

In [10]:
def normalize(t):
    t_norm = (t - t.mean()) / t.std()
    return t_norm

In [10]:
array_hidden_classes = [[0],[2],[3],[4],[5]]
filenames = ['0','2','3','4','5']
# array_hidden_classes = [[0]]
# filenames = ['0']
total_classes = len(labels_str)
for i in range(len(array_hidden_classes)):
    filename = f'{filenames[i]}_hidden'
    print(filename)
    hidden_classes = array_hidden_classes[i] #Classes ocultas do treinamento

    hidden_classes_index = list(train[train['Label'].isin(hidden_classes)].index)

    train_hidden = train.loc[hidden_classes_index]

    train_not_hidden = train.drop(hidden_classes_index)

    X_train = train_not_hidden.drop(columns=['Label'])
    y_train = train_not_hidden['Label']
    X_val = val.drop(columns=['Label'])
    y_val = val['Label'].values
    X_test = test.drop(columns=['Label'])
    y_test = test['Label'].values

    torch.manual_seed(123)
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(device)
    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_loader, pick_list = build_class_reference_batches(X_train,y_train, batch_size=512)
    pick_samples = []
    pick_labels = []
    for l in pick_list:
        pick_samples.append(X_train[l])
        pick_labels.append(y_train[l])

    pick_samples = torch.stack(pick_samples)    
    pick_labels = torch.stack(pick_labels)

    print('pick completo')

    neurons = total_classes - len(hidden_classes)
    print(f'{X_train.shape[1]} {neurons}')
    model = contrastive_ae(input_neurons=X_train.shape[1],neurons=neurons)
    model.to(device)

    learning_rate = 0.0001
    opt = optim.Adam(model.parameters(),lr=learning_rate)
    margin = 10 # Parametro de afastamento das classes
    cae_lambda_1 = 0.1 # Parametro de influencia na distancia das classes
    
    
    for epoch in range(250):
        running_loss = 0
        running_ael = 0
        running_cl = 0
        contador = 0
        for data in train_loader:
            inputs, labels = data
            inputs = inputs.to(device)
            labels = labels.to(device)
            ps = pick_samples[contador]
            pl = pick_labels[contador]
            ps = ps.to(device)
            pl = pl.to(device)
            contador += 1
            #print(f'{contador}/{len(train_loader)}')
            opt.zero_grad()
            outputs, encoded = model(inputs)
            _, pick_encoded = model(ps)
            tam_pe = pick_encoded.shape[0]
            enc_total = torch.cat((encoded,pick_encoded), dim=0)
            enc_total_norm = enc_total
            encoded_norm = enc_total_norm[:-tam_pe]
            pick_encoded_norm = enc_total_norm[-tam_pe:]
            loss, ael, cl = AEContrastive(input=inputs, output=outputs, embeddings = encoded_norm, labels=labels, pick_encoded = pick_encoded_norm, pick_labels = pl, margin=margin, lambda1=cae_lambda_1)
            #loss = dummyMSELoss(inputs,outputs)
            loss.backward()
            opt.step()
            running_loss += loss.item()
            running_ael += ael.item()
            running_cl += cl.item()
            #print(f'loss = {loss.item()} batch_size = {size}')
        print(f'filename: {filename} Epoch {epoch+1} loss:{running_loss/len(train_loader)} ael:{running_ael/len(train_loader)} cl:{running_cl/len(train_loader)}')

    model_e = encoder(model=model)
    model_e.to(device)

    model_e.eval()

    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_encoded = model_e(X_train.to(device))

    train_encoded = train_encoded.detach().cpu().numpy()

    train_encoded_df = pd.DataFrame(train_encoded)
    train_encoded_df['Label'] = y_train.detach().cpu().numpy().astype(int)
    display(train_encoded_df)

    score = davies_bouldin_score(train_encoded_df.drop(columns=['Label']), train_encoded_df['Label'])
    print("Davies-Bouldin Score:", score)

    X_val = torch.tensor(np.array(X_val), dtype=torch.float)

    val_encoded = model_e(X_val.to(device))

    val_encoded = val_encoded.detach().cpu().numpy()

    val_encoded_df = pd.DataFrame(val_encoded)

    val_encoded_df['Label'] = y_val

    display(val_encoded_df)

    X_test = torch.tensor(np.array(X_test), dtype=torch.float)

    test_encoded = model_e(X_test.to(device))

    test_encoded = test_encoded.detach().cpu().numpy()

    test_encoded_df = pd.DataFrame(test_encoded)

    test_encoded_df['Label'] = y_test

    display(test_encoded_df)

    train_encoded_df.to_csv(f'train_encoded_CADE_cod_joined_attacks_pick_class_squared_normalized_{filename}.csv',index=False)
    val_encoded_df.to_csv(f'val_encoded_CADE_cod_joined_attacks_pick_class_squared_normalized_{filename}.csv',index=False)
    test_encoded_df.to_csv(f'test_encoded_CADE_cod_joined_attacks_pick_class_squared_normalized_{filename}.csv',index=False)

0_hidden
cuda
[1.0, 2.0, 3.0, 4.0, 5.0]
pick completo
82 5
filename: 0_hidden Epoch 1 loss:3.7306455969090333 ael:0.021364391333919784 cl:37.09281147616168
filename: 0_hidden Epoch 2 loss:1.5497389359191882 ael:0.0062059268673812125 cl:15.435329832859784
filename: 0_hidden Epoch 3 loss:0.7593025748306256 ael:0.004646793432628261 cl:7.546557675913558
filename: 0_hidden Epoch 4 loss:0.6299241629342518 ael:0.00453544401115859 cl:6.253887071467387
filename: 0_hidden Epoch 5 loss:0.5573538263394763 ael:0.004298306134031682 cl:5.530555097220455
filename: 0_hidden Epoch 6 loss:0.5067604924767813 ael:0.004174075386082987 cl:5.025864078976481
filename: 0_hidden Epoch 7 loss:0.47315727904637017 ael:0.004199272008804792 cl:4.689579984424482
filename: 0_hidden Epoch 8 loss:0.44938533435089184 ael:0.004228557836402401 cl:4.451567684504663
filename: 0_hidden Epoch 9 loss:0.43195265767690016 ael:0.004207709813554274 cl:4.2774494072625675
filename: 0_hidden Epoch 10 loss:0.42040831469332457 ael:0.003970801560515767 cl:4.164375064500724
filename: 0_hidden Epoch 11 loss:0.41105004298293296 ael:0.0036987454881362747 cl:4.073512900610197
filename: 0_hidden Epoch 12 loss:0.4032785463485562 ael:0.003437408875389699 cl:3.9984113140255992
filename: 0_hidden Epoch 13 loss:0.39681309197237546 ael:0.0032300354167969056 cl:3.935830493728048
filename: 0_hidden Epoch 14 loss:0.3912194530587258 ael:0.0030738729779149826 cl:3.8814557383149753
filename: 0_hidden Epoch 15 loss:0.3850648017855983 ael:0.002953116710932023 cl:3.821116782151736
filename: 0_hidden Epoch 16 loss:0.3787418006770418 ael:0.002845672807838892 cl:3.758961216125381
filename: 0_hidden Epoch 17 loss:0.3727011987808199 ael:0.0027461716963561116 cl:3.6995502063885266
filename: 0_hidden Epoch 18 loss:0.3669274397527456 ael:0.0026459268801945005 cl:3.6428150652254776
filename: 0_hidden Epoch 19 loss:0.36102085896931585 ael:0.002544394810121406 cl:3.584764582756494
filename: 0_hidden Epoch 20 loss:0.3548979878581631 ael:0.0024330790146290387 cl:3.5246490301550084
filename: 0_hidden Epoch 21 loss:0.34844679136370826 ael:0.0023382556409227346 cl:3.4610853001469333
filename: 0_hidden Epoch 22 loss:0.3418904505204972 ael:0.0022748458241211925 cl:3.3961559869183966
filename: 0_hidden Epoch 23 loss:0.33500462564618366 ael:0.0022259497060656153 cl:3.327786702712217
filename: 0_hidden Epoch 24 loss:0.32811750252245414 ael:0.0021847175515155174 cl:3.2593277937886795
filename: 0_hidden Epoch 25 loss:0.3214604710373147 ael:0.0021400171681541682 cl:3.1932044858371738
filename: 0_hidden Epoch 26 loss:0.31510791614609673 ael:0.0020970756870117213 cl:3.1301083504025415
filename: 0_hidden Epoch 27 loss:0.3091735297718741 ael:0.0020594768392306947 cl:3.071140480099116
filename: 0_hidden Epoch 28 loss:0.3037948150021195 ael:0.002024129075097596 cl:3.017706801297921
filename: 0_hidden Epoch 29 loss:0.2985692618807093 ael:0.0019795530819061405 cl:2.96589703764879
filename: 0_hidden Epoch 30 loss:0.2941034058685798 ael:0.0019313077571000295 cl:2.921720932699527
filename: 0_hidden Epoch 31 loss:0.2902210091259083 ael:0.0018914723766486053 cl:2.883295318147035
filename: 0_hidden Epoch 32 loss:0.2870388301363214 ael:0.0018581847580632872 cl:2.8518063992537943
filename: 0_hidden Epoch 33 loss:0.2839792383698941 ael:0.001824051069676729 cl:2.82155182178684
filename: 0_hidden Epoch 34 loss:0.28129285989547514 ael:0.0017937917012981605 cl:2.7949906316343163
filename: 0_hidden Epoch 35 loss:0.27900709187221107 ael:0.001766989250971958 cl:2.7724009746992437
filename: 0_hidden Epoch 36 loss:0.2766086731407607 ael:0.0017455211731609358 cl:2.748631466625681
filename: 0_hidden Epoch 37 loss:0.2744566788218024 ael:0.001725665288992328 cl:2.727310088964609
filename: 0_hidden Epoch 38 loss:0.27228500208533485 ael:0.0017092014573183642 cl:2.7057579559421425
filename: 0_hidden Epoch 39 loss:0.27008402442534846 ael:0.0016955075055706617 cl:2.6838851194203115
filename: 0_hidden Epoch 40 loss:0.2676411195689279 ael:0.0016783849784942734 cl:2.659627299946352
filename: 0_hidden Epoch 41 loss:0.26552774898326786 ael:0.001663087406227582 cl:2.6386465721921577
filename: 0_hidden Epoch 42 loss:0.2630807051477872 ael:0.0016397260623103353 cl:2.6144097415468552
filename: 0_hidden Epoch 43 loss:0.2609601468552974 ael:0.001622242049343713 cl:2.5933790029031445
filename: 0_hidden Epoch 44 loss:0.2585416828138522 ael:0.0016037423909451261 cl:2.5693793558469475
filename: 0_hidden Epoch 45 loss:0.25683034800872223 ael:0.0015806295652339326 cl:2.5524971410002
filename: 0_hidden Epoch 46 loss:0.2547991574020622 ael:0.0015576401850312912 cl:2.532415130231537
filename: 0_hidden Epoch 47 loss:0.2532518688338781 ael:0.0015390119394630664 cl:2.5171285240437973
filename: 0_hidden Epoch 48 loss:0.25153777601165106 ael:0.0015247925433157325 cl:2.500129796399544
filename: 0_hidden Epoch 49 loss:0.2498782941718232 ael:0.0015062640121122624 cl:2.4837202611970075
filename: 0_hidden Epoch 50 loss:0.24850621455969035 ael:0.001499222650430291 cl:2.470069873467406
filename: 0_hidden Epoch 51 loss:0.2469921060449598 ael:0.001486670798300441 cl:2.455054312524323
filename: 0_hidden Epoch 52 loss:0.2457774359383292 ael:0.0014793778555829676 cl:2.4429805320306888
filename: 0_hidden Epoch 53 loss:0.24454663141487684 ael:0.0014691971403665157 cl:2.4307743012064944
filename: 0_hidden Epoch 54 loss:0.2434302458072256 ael:0.0014632287694929312 cl:2.4196701310019892
filename: 0_hidden Epoch 55 loss:0.24212162582518063 ael:0.0014573120240791973 cl:2.406643096569129
filename: 0_hidden Epoch 56 loss:0.2410064478132137 ael:0.001454540035900995 cl:2.3955190363690777
filename: 0_hidden Epoch 57 loss:0.23978607233072113 ael:0.0014487696381903167 cl:2.383372986275872
filename: 0_hidden Epoch 58 loss:0.23864035988605364 ael:0.0014370559635077031 cl:2.3720329967396805
filename: 0_hidden Epoch 59 loss:0.2375663730000422 ael:0.0014284865104469936 cl:2.361378822867255
filename: 0_hidden Epoch 60 loss:0.23656655785613034 ael:0.0014161264978272692 cl:2.351504269814808
filename: 0_hidden Epoch 61 loss:0.23557204414388608 ael:0.0014066224536547934 cl:2.341654178323738
filename: 0_hidden Epoch 62 loss:0.23465184387130167 ael:0.0013912211821779858 cl:2.3326061893340038
filename: 0_hidden Epoch 63 loss:0.23358145354827997 ael:0.001374317406664707 cl:2.3220713213116135
filename: 0_hidden Epoch 64 loss:0.23269541698432575 ael:0.0013639823507292153 cl:2.3133143061622707
filename: 0_hidden Epoch 65 loss:0.23174974288861933 ael:0.0013467280974657026 cl:2.3040301090183632
filename: 0_hidden Epoch 66 loss:0.2306820132825531 ael:0.0013328517029591526 cl:2.2934915780348977
filename: 0_hidden Epoch 67 loss:0.22975782054749122 ael:0.001310496669587279 cl:2.2844732002270014
filename: 0_hidden Epoch 68 loss:0.22888249055637355 ael:0.0012996900090880233 cl:2.275827963782855
filename: 0_hidden Epoch 69 loss:0.2279051959010511 ael:0.0012773526115590528 cl:2.2662783901248784
filename: 0_hidden Epoch 70 loss:0.22671138286362527 ael:0.0012608765354593808 cl:2.254505021241803
filename: 0_hidden Epoch 71 loss:0.22566856558356274 ael:0.001243222596889352 cl:2.244253391646782
filename: 0_hidden Epoch 72 loss:0.22459674068920515 ael:0.001228826482494467 cl:2.2336791010931334
filename: 0_hidden Epoch 73 loss:0.22332502312079053 ael:0.0012158323453958333 cl:2.2210918681255714
filename: 0_hidden Epoch 74 loss:0.2221208568609894 ael:0.0012051441543416746 cl:2.209157089192302
filename: 0_hidden Epoch 75 loss:0.22092205022420078 ael:0.0011901295197626145 cl:2.197319167602749
filename: 0_hidden Epoch 76 loss:0.21962513208413287 ael:0.0011793841415921702 cl:2.184457440098783
filename: 0_hidden Epoch 77 loss:0.21832403793264865 ael:0.0011686074390029966 cl:2.1715542669503667
filename: 0_hidden Epoch 78 loss:0.2169432275288296 ael:0.0011621338258905503 cl:2.157810902300257
filename: 0_hidden Epoch 79 loss:0.21565107258274532 ael:0.0011519022067266872 cl:2.144991663918109
filename: 0_hidden Epoch 80 loss:0.21431960128442779 ael:0.0011704489068080158 cl:2.131491487046859
filename: 0_hidden Epoch 81 loss:0.2127464553037455 ael:0.0011436893747038494 cl:2.1160276189380434
filename: 0_hidden Epoch 82 loss:0.2109519924519886 ael:0.0011875337738559877 cl:2.0976445478774632
filename: 0_hidden Epoch 83 loss:0.20930401229367493 ael:0.0011532742306841384 cl:2.081507342432086
filename: 0_hidden Epoch 84 loss:0.20769127826962172 ael:0.0011410760333222583 cl:2.0655019868298785
filename: 0_hidden Epoch 85 loss:0.20594937293263293 ael:0.00113878234572209 cl:2.0481058698098025
filename: 0_hidden Epoch 86 loss:0.20419792945418347 ael:0.00114136666569696 cl:2.030565591478751
filename: 0_hidden Epoch 87 loss:0.20214319398962005 ael:0.0011510381204236646 cl:2.0099215248492377
filename: 0_hidden Epoch 88 loss:0.20034786862738663 ael:0.0011596531523333467 cl:1.9918821178709745
filename: 0_hidden Epoch 89 loss:0.19845930533127298 ael:0.0011554042696375196 cl:1.973038975540976
filename: 0_hidden Epoch 90 loss:0.1968147445108518 ael:0.001162077623897315 cl:1.9565266334525626
filename: 0_hidden Epoch 91 loss:0.1951074153289913 ael:0.0011621338553108541 cl:1.9394527809470112
filename: 0_hidden Epoch 92 loss:0.19317016446459595 ael:0.0011595925187749807 cl:1.9201056886549877
filename: 0_hidden Epoch 93 loss:0.19126059220105326 ael:0.0011585957112456168 cl:1.9010199343682872
filename: 0_hidden Epoch 94 loss:0.1895467929963654 ael:0.0011593590796350505 cl:1.8838743068880963
filename: 0_hidden Epoch 95 loss:0.18762417953120836 ael:0.001158638948425943 cl:1.8646553748985284
filename: 0_hidden Epoch 96 loss:0.18598828592723624 ael:0.0011631621857229252 cl:1.8482512045221082
filename: 0_hidden Epoch 97 loss:0.18411985373231754 ael:0.0011700429142572051 cl:1.8294980743396585
filename: 0_hidden Epoch 98 loss:0.18217050829437942 ael:0.0011706961513141736 cl:1.8099980894003576
filename: 0_hidden Epoch 99 loss:0.1800500892704346 ael:0.0011774247159505886 cl:1.7887266164182705
filename: 0_hidden Epoch 100 loss:0.17774134789650906 ael:0.00117640693882421 cl:1.7656493751850524
filename: 0_hidden Epoch 101 loss:0.17552951866317507 ael:0.0011640153091299215 cl:1.743655004846536
filename: 0_hidden Epoch 102 loss:0.1733066261705856 ael:0.001155879350532517 cl:1.7215074378362454
filename: 0_hidden Epoch 103 loss:0.1711722204556964 ael:0.0011559032337476382 cl:1.7001631406469302
filename: 0_hidden Epoch 104 loss:0.16921759654471125 ael:0.0011496411295993268 cl:1.6806795241200918
filename: 0_hidden Epoch 105 loss:0.1671154648433145 ael:0.0011369536967771416 cl:1.659785081422766
filename: 0_hidden Epoch 106 loss:0.16541346635983037 ael:0.0011326260915839241 cl:1.642808376464496
filename: 0_hidden Epoch 107 loss:0.1632646405698069 ael:0.0011301367670977266 cl:1.621345009215167
filename: 0_hidden Epoch 108 loss:0.16166775323603597 ael:0.0011195574972521255 cl:1.6054819274875265
filename: 0_hidden Epoch 109 loss:0.15985088706829714 ael:0.0011173480656513726 cl:1.587335360311857
filename: 0_hidden Epoch 110 loss:0.1581097010806641 ael:0.0011115360244031375 cl:1.5699816238685715
filename: 0_hidden Epoch 111 loss:0.15653507956545581 ael:0.001113330350801134 cl:1.5542174641446533
filename: 0_hidden Epoch 112 loss:0.1550048403149344 ael:0.0011305741743207881 cl:1.5387426324779834
filename: 0_hidden Epoch 113 loss:0.15368417388730674 ael:0.001135167918911416 cl:1.5254900345831592
filename: 0_hidden Epoch 114 loss:0.15248886946449225 ael:0.0011424563884533689 cl:1.5134641019221615
filename: 0_hidden Epoch 115 loss:0.15116748368675867 ael:0.0011389637225282395 cl:1.500285175218248
filename: 0_hidden Epoch 116 loss:0.1503064044958646 ael:0.001134636691581845 cl:1.4917176525726272
filename: 0_hidden Epoch 117 loss:0.14903739119339413 ael:0.0011319094641103011 cl:1.4790547886564038
filename: 0_hidden Epoch 118 loss:0.14797998486485062 ael:0.0011234303481203207 cl:1.4685655181032489
filename: 0_hidden Epoch 119 loss:0.1472490346925637 ael:0.0011199540727035912 cl:1.4612907798382433
filename: 0_hidden Epoch 120 loss:0.14638906353248182 ael:0.0011136052706472027 cl:1.4527545578108647
filename: 0_hidden Epoch 121 loss:0.14553456798276856 ael:0.001108674100348692 cl:1.4442589118074516
filename: 0_hidden Epoch 122 loss:0.1447021845050015 ael:0.0010976388315702824 cl:1.436045431839906
filename: 0_hidden Epoch 123 loss:0.14398994020580574 ael:0.0010878734376024196 cl:1.4290206431382326
filename: 0_hidden Epoch 124 loss:0.14303090576152983 ael:0.0010829250736563776 cl:1.4194797810123565
filename: 0_hidden Epoch 125 loss:0.14200477833337136 ael:0.0010610343121364263 cl:1.4094374142392143
filename: 0_hidden Epoch 126 loss:0.14114652644952386 ael:0.0010456420733961733 cl:1.4010088210006515
filename: 0_hidden Epoch 127 loss:0.1404193613919768 ael:0.0010389144990635955 cl:1.3938044444224644
filename: 0_hidden Epoch 128 loss:0.13985498686798556 ael:0.0010377891045286907 cl:1.3881719558770935
filename: 0_hidden Epoch 129 loss:0.13925214247283704 ael:0.0010307891543506766 cl:1.3822135104918931
filename: 0_hidden Epoch 130 loss:0.13855048092746033 ael:0.0010101398706717092 cl:1.3754033877443412
filename: 0_hidden Epoch 131 loss:0.13786255289581795 ael:0.001003039095213579 cl:1.3685951144751454
filename: 0_hidden Epoch 132 loss:0.13715403620341204 ael:0.0009908718228810124 cl:1.3616316206888281
filename: 0_hidden Epoch 133 loss:0.1364243056061008 ael:0.0009756405919460573 cl:1.3544866278305487
filename: 0_hidden Epoch 134 loss:0.13574019015252445 ael:0.0009589083987626499 cl:1.347812794379971
filename: 0_hidden Epoch 135 loss:0.13498165550860386 ael:0.000948392321994964 cl:1.3403326062679868
filename: 0_hidden Epoch 136 loss:0.1344913279489913 ael:0.0009418741783223396 cl:1.3354945155194438
filename: 0_hidden Epoch 137 loss:0.1337045574432484 ael:0.000927123317255969 cl:1.3277743172907224
filename: 0_hidden Epoch 138 loss:0.13332430633745918 ael:0.0009208157504513032 cl:1.324034883053707
filename: 0_hidden Epoch 139 loss:0.13282338869872348 ael:0.0009157883560909854 cl:1.3190759769608982
filename: 0_hidden Epoch 140 loss:0.13214812092363018 ael:0.0009081422352613495 cl:1.3123997627272512
filename: 0_hidden Epoch 141 loss:0.13168787173521745 ael:0.000903049603850437 cl:1.3078481992837934
filename: 0_hidden Epoch 142 loss:0.13095026393880466 ael:0.0009058708572651264 cl:1.3004439078628465
filename: 0_hidden Epoch 143 loss:0.13027722492102914 ael:0.0009023220609869595 cl:1.2937490063067938
filename: 0_hidden Epoch 144 loss:0.12960220125897295 ael:0.0008920767288319347 cl:1.2871012240828308
filename: 0_hidden Epoch 145 loss:0.12902421502083647 ael:0.0008841765318085573 cl:1.2814003624805173
filename: 0_hidden Epoch 146 loss:0.1282528032913678 ael:0.0008738644782958632 cl:1.273789364624014
filename: 0_hidden Epoch 147 loss:0.12848938491752057 ael:0.0008784375900640466 cl:1.276109451476816
filename: 0_hidden Epoch 148 loss:0.12724850729161868 ael:0.0008648306695881112 cl:1.2638367446641312
filename: 0_hidden Epoch 149 loss:0.126708646953418 ael:0.0008585644315237512 cl:1.2585008032694969
filename: 0_hidden Epoch 150 loss:0.12618274123835865 ael:0.0008556808784941269 cl:1.2532705811365832
filename: 0_hidden Epoch 151 loss:0.12529813851583546 ael:0.0008476471072314154 cl:1.2445048946456663
filename: 0_hidden Epoch 152 loss:0.12472341097576264 ael:0.0008440244870067755 cl:1.2387938441838462
filename: 0_hidden Epoch 153 loss:0.1242110984886768 ael:0.0008411036682394125 cl:1.233699926147046
filename: 0_hidden Epoch 154 loss:0.12364794144296641 ael:0.0008407061769842893 cl:1.2280723319459816
filename: 0_hidden Epoch 155 loss:0.12290409622107044 ael:0.0008320644400303826 cl:1.2207202955546324
filename: 0_hidden Epoch 156 loss:0.12235762642646239 ael:0.0008294516856834837 cl:1.2152817282605162
filename: 0_hidden Epoch 157 loss:0.12139746400914363 ael:0.0008264645639011068 cl:1.2057099750672815
filename: 0_hidden Epoch 158 loss:0.12084852267496297 ael:0.0008249126422755155 cl:1.2002360801986278
filename: 0_hidden Epoch 159 loss:0.11999258703649332 ael:0.0008262164747391978 cl:1.191663684285172
filename: 0_hidden Epoch 160 loss:0.11962258488470948 ael:0.0008175588355015587 cl:1.1880502407043345
filename: 0_hidden Epoch 161 loss:0.11858161806046026 ael:0.0008194905597117567 cl:1.177621252933818
filename: 0_hidden Epoch 162 loss:0.11795952930098284 ael:0.000821062139386594 cl:1.1713846509693324
filename: 0_hidden Epoch 163 loss:0.1169907702489385 ael:0.0008172614042352932 cl:1.161735067246808
filename: 0_hidden Epoch 164 loss:0.11626664024676064 ael:0.0008167531407539302 cl:1.1544988502358602
filename: 0_hidden Epoch 165 loss:0.11524390770355708 ael:0.0008159512387054319 cl:1.1442795444221396
filename: 0_hidden Epoch 166 loss:0.11404005093766324 ael:0.0008156594722190414 cl:1.1322438940675903
filename: 0_hidden Epoch 167 loss:0.11305970779987314 ael:0.0008150352338295951 cl:1.1224467069918813
filename: 0_hidden Epoch 168 loss:0.11177765917553567 ael:0.0008145169811236079 cl:1.1096314017181188
filename: 0_hidden Epoch 169 loss:0.11082065565623359 ael:0.0008170234373692075 cl:1.100036302282116
filename: 0_hidden Epoch 170 loss:0.11013186919760594 ael:0.0008239960816372456 cl:1.0930787104898723
filename: 0_hidden Epoch 171 loss:0.10907789072688734 ael:0.0008290095859805652 cl:1.0824887920388568
filename: 0_hidden Epoch 172 loss:0.10793991695768439 ael:0.0008264238587188663 cl:1.071134912634011
filename: 0_hidden Epoch 173 loss:0.10668953714920024 ael:0.0008283246097020261 cl:1.0586121080085438
filename: 0_hidden Epoch 174 loss:0.10588170364881673 ael:0.0008255838178997643 cl:1.0505611807185942
filename: 0_hidden Epoch 175 loss:0.10441641126876751 ael:0.0008263930002896193 cl:1.0359001655493154
filename: 0_hidden Epoch 176 loss:0.10356938440324172 ael:0.0008352093679740038 cl:1.0273417326840382
filename: 0_hidden Epoch 177 loss:0.10284494437866942 ael:0.0008331953084999879 cl:1.0201174709893406
filename: 0_hidden Epoch 178 loss:0.10157658986708257 ael:0.000826250427328759 cl:1.0075033771634054
filename: 0_hidden Epoch 179 loss:0.10017665072696444 ael:0.0008167640204995044 cl:0.9935988487823567
filename: 0_hidden Epoch 180 loss:0.09908619068977072 ael:0.0008102785865199556 cl:0.9827591057205172
filename: 0_hidden Epoch 181 loss:0.09830438871944847 ael:0.0008137208233601322 cl:0.9749066627918593
filename: 0_hidden Epoch 182 loss:0.097137496249688 ael:0.0008071632551089712 cl:0.9633033129713298
filename: 0_hidden Epoch 183 loss:0.09602684275769642 ael:0.0008036774512528705 cl:0.952231636687219
filename: 0_hidden Epoch 184 loss:0.09478850340139851 ael:0.0008011059157127995 cl:0.9398739602127192
filename: 0_hidden Epoch 185 loss:0.09415265542885984 ael:0.0008104669414822611 cl:0.9334218673140975
filename: 0_hidden Epoch 186 loss:0.09270804754015399 ael:0.0008078359120044943 cl:0.9190021006812792
filename: 0_hidden Epoch 187 loss:0.0915508955845364 ael:0.0008177101500551777 cl:0.9073318395159007
filename: 0_hidden Epoch 188 loss:0.09066474610850353 ael:0.0008282937265644124 cl:0.8983645075620829
filename: 0_hidden Epoch 189 loss:0.08972940097014978 ael:0.0008452185415449968 cl:0.8888418095076079
filename: 0_hidden Epoch 190 loss:0.08903480767288541 ael:0.0008519972967392001 cl:0.8818280889149688
filename: 0_hidden Epoch 191 loss:0.08800257496915359 ael:0.0008634607818846351 cl:0.8713911265146814
filename: 0_hidden Epoch 192 loss:0.08717121933393729 ael:0.000870386213726678 cl:0.863008316100676
filename: 0_hidden Epoch 193 loss:0.0863351804717019 ael:0.0008767583443609937 cl:0.8545842052880334
filename: 0_hidden Epoch 194 loss:0.08545899207572867 ael:0.0008792012843507425 cl:0.8457978923523374
filename: 0_hidden Epoch 195 loss:0.0847723494901611 ael:0.0008902520864517993 cl:0.8388209621445623
filename: 0_hidden Epoch 196 loss:0.08417251988520762 ael:0.0008947724414029336 cl:0.8327774595059649
filename: 0_hidden Epoch 197 loss:0.08339248431986779 ael:0.0008943905869924189 cl:0.8249809226074432
filename: 0_hidden Epoch 198 loss:0.08279889198173883 ael:0.0008967073879568892 cl:0.8190218325384768

C:\Users\linco\AppData\Local\Temp\ipykernel_50728\310156585.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
C:\Users\linco\AppData\Local\Temp\ipykernel_50728\310156585.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1          2          3         4  Label
0        2.627134  3.495268  12.167979 -15.949884  4.420605      1
1        1.253443  1.723965   6.202833  -7.987063  2.176383      2
2        2.446810  3.246908  12.590688 -16.675304  4.283470      1
3       -0.087627  0.432573  19.349188 -26.161076  2.376436      4
4        1.253602  1.724164   6.203566  -7.988064  2.176653      2
...           ...       ...        ...        ...       ...    ...
1270932 -0.888324 -0.917520   0.388868  -0.256036 -0.957226      3
1270933  1.253349  1.723847   6.202387  -7.986454  2.176220      2
1270934  1.253399  1.723910   6.202624  -7.986778  2.176306      2
1270935  1.253358  1.723859   6.202437  -7.986522  2.176238      2
1270936  1.250155  1.719857   6.187324  -7.965880  2.170760      2

[1270937 rows x 6 columns]

Davies-Bouldin Score: 1.158241855420865

               0         1          2          3         4  Label
0       2.412533  3.300767  12.190971 -16.070925  4.314942      0
1       1.254101  1.724788   6.205111  -7.990170  2.177426      2
2       2.500060  3.488555  12.417381 -16.266672  4.352566      1
3      -1.168649 -1.183880   0.005369   0.337964 -1.234653      3
4       2.473984  3.479240  12.343463 -16.244940  4.384403      1
...          ...       ...        ...        ...       ...    ...
519951  2.551496  3.496222  12.542336 -16.484617  4.416090      1
519952  0.230693  0.867971  18.620375 -25.150749  2.811499      4
519953  2.909551  3.804221  11.587043 -15.182983  4.614385      0
519954  2.563285  3.421139  12.210402 -15.991514  4.325774      1
519955 -0.888324 -0.917520   0.388868  -0.256036 -0.957226      3

[519956 rows x 6 columns]

               0         1          2          3         4  Label
0       2.899555  3.791455  11.563754 -15.153486  4.601162      0
1       2.322457  3.186617  11.955887 -15.764641  4.188963      0
2       2.549536  3.531653  12.517225 -16.465731  4.407414      1
3       2.131918  2.977582  11.630042 -15.329978  3.830977      1
4       2.863815  3.858864  10.352451 -13.280299  4.556218      0
...          ...       ...        ...        ...       ...    ...
649942  2.414600  3.401603  12.148922 -15.992224  4.299189      1
649943  2.892133  3.888558  10.234257 -13.113320  4.570274      0
649944  2.881614  3.879215  10.313045 -13.222457  4.569723      0
649945 -1.125393 -1.111116   0.229740   0.041172 -1.151976      3
649946  1.020577  1.522557   5.896692  -7.527743  1.937168      2

[649947 rows x 6 columns]

2_hidden
cuda
[0.0, 1.0, 3.0, 4.0, 5.0]
pick completo
82 5
filename: 2_hidden Epoch 1 loss:3.5460965807674922 ael:0.014600690600887072 cl:35.31495835042139
filename: 2_hidden Epoch 2 loss:1.6474316631667099 ael:0.004832602015285268 cl:16.425990334170603
filename: 2_hidden Epoch 3 loss:0.9528283607192904 ael:0.007084466075682631 cl:9.457438777692136
filename: 2_hidden Epoch 4 loss:0.7668824518415315 ael:0.00781262454587683 cl:7.59069814570466
filename: 2_hidden Epoch 5 loss:0.6591377412758724 ael:0.008800261544760818 cl:6.503374681626147
filename: 2_hidden Epoch 6 loss:0.5664004925616652 ael:0.009289677328789573 cl:5.571108060935784
filename: 2_hidden Epoch 7 loss:0.48916786348349167 ael:0.0078464588437676 cl:4.813213960120552
filename: 2_hidden Epoch 8 loss:0.43907227377183955 ael:0.005708505585653522 cl:4.33363761305809
filename: 2_hidden Epoch 9 loss:0.41052854629287944 ael:0.005184240873538132 cl:4.053442982030891
filename: 2_hidden Epoch 10 loss:0.38738227440861234 ael:0.004649835102919119 cl:3.827324328157637
filename: 2_hidden Epoch 11 loss:0.36440516705706455 ael:0.004289584034885013 cl:3.601155771951229
filename: 2_hidden Epoch 12 loss:0.3422406357609563 ael:0.003880597384679213 cl:3.383600332479031
filename: 2_hidden Epoch 13 loss:0.324954077647182 ael:0.0034991248062136446 cl:3.214549475559714
filename: 2_hidden Epoch 14 loss:0.3101604679675653 ael:0.0032521138156965724 cl:3.0690834909851787
filename: 2_hidden Epoch 15 loss:0.29587892231841884 ael:0.0031205218919819733 cl:2.927583956404736
filename: 2_hidden Epoch 16 loss:0.2846228395920922 ael:0.0029742415843270063 cl:2.81648593004684
filename: 2_hidden Epoch 17 loss:0.2754130547593909 ael:0.0028616002874860096 cl:2.725514492061403
filename: 2_hidden Epoch 18 loss:0.26774685304633705 ael:0.0027939429910028386 cl:2.6495290562597633
filename: 2_hidden Epoch 19 loss:0.26124865880878695 ael:0.0027462361100993025 cl:2.5850241840931405
filename: 2_hidden Epoch 20 loss:0.25550689535618526 ael:0.002709446235611621 cl:2.5279744461440203
filename: 2_hidden Epoch 21 loss:0.25036297947473346 ael:0.002677527489515065 cl:2.4768544761758102
filename: 2_hidden Epoch 22 loss:0.24572522987159545 ael:0.0026098053364222054 cl:2.4311542016895196
filename: 2_hidden Epoch 23 loss:0.24119404513301732 ael:0.0025019157613894484 cl:2.3869212479793536
filename: 2_hidden Epoch 24 loss:0.23715787827859672 ael:0.002430801454704113 cl:2.3472707251707714
filename: 2_hidden Epoch 25 loss:0.2330563038271683 ael:0.0023791962065965438 cl:2.306771036494545
filename: 2_hidden Epoch 26 loss:0.22879599817423968 ael:0.00232922860383116 cl:2.264667656669143
filename: 2_hidden Epoch 27 loss:0.22470346828977092 ael:0.0022882644835946677 cl:2.224151999342163
filename: 2_hidden Epoch 28 loss:0.2212273076318248 ael:0.0022599965692375245 cl:2.1896730684571795
filename: 2_hidden Epoch 29 loss:0.2179811302409099 ael:0.0022321074288433732 cl:2.157490190828753
filename: 2_hidden Epoch 30 loss:0.21522807771808397 ael:0.0021929161737833654 cl:2.13035157819589
filename: 2_hidden Epoch 31 loss:0.21224564290796108 ael:0.0021683020309929066 cl:2.100773370823665
filename: 2_hidden Epoch 32 loss:0.20932603854010676 ael:0.0021438212470254966 cl:2.0718221368758303
filename: 2_hidden Epoch 33 loss:0.20656937275582934 ael:0.0021116054831998563 cl:2.0445776373757956
filename: 2_hidden Epoch 34 loss:0.20384810168666448 ael:0.002074007339107025 cl:2.0177409090493854
filename: 2_hidden Epoch 35 loss:0.20102712479882945 ael:0.0020286390551077257 cl:1.9899848224911076
filename: 2_hidden Epoch 36 loss:0.19847510883159805 ael:0.001969357580797507 cl:1.9650574800040987
filename: 2_hidden Epoch 37 loss:0.19458139558480672 ael:0.001910491143074159 cl:1.926709015223018
filename: 2_hidden Epoch 38 loss:0.19135846159371891 ael:0.001857815808102581 cl:1.8950064243716107
filename: 2_hidden Epoch 39 loss:0.18938700029768094 ael:0.0018055363804849454 cl:1.8758146046546467
filename: 2_hidden Epoch 40 loss:0.1873931994106163 ael:0.0017522471076305084 cl:1.8564094926181594
filename: 2_hidden Epoch 41 loss:0.18489838084805083 ael:0.001712315230445163 cl:1.8318606259965757
filename: 2_hidden Epoch 42 loss:0.18264916811835522 ael:0.0016911380380332166 cl:1.8095802693687684
filename: 2_hidden Epoch 43 loss:0.1800189108713067 ael:0.001663473582052495 cl:1.7835543443933566
filename: 2_hidden Epoch 44 loss:0.17779810820973058 ael:0.0016437481657352723 cl:1.7615435691256272
filename: 2_hidden Epoch 45 loss:0.17546866506621328 ael:0.001604105004522002 cl:1.7386455696315792
filename: 2_hidden Epoch 46 loss:0.17292275088812 ael:0.0015833786294396628 cl:1.7133936942756525
filename: 2_hidden Epoch 47 loss:0.16976982241943042 ael:0.0015656639878843688 cl:1.6820415562879272
filename: 2_hidden Epoch 48 loss:0.1660202880297401 ael:0.0015519892367805294 cl:1.6446829607612208
filename: 2_hidden Epoch 49 loss:0.1630453074383631 ael:0.0015387174104747488 cl:1.6150658730874983
filename: 2_hidden Epoch 50 loss:0.16020709424121687 ael:0.0015356613144384729 cl:1.586714302430376
filename: 2_hidden Epoch 51 loss:0.1570247690552813 ael:0.0015286548785478618 cl:1.5549611133790155
filename: 2_hidden Epoch 52 loss:0.15413225910501085 ael:0.0015209751982651705 cl:1.5261128122433585
filename: 2_hidden Epoch 53 loss:0.15053170644106312 ael:0.0015164850824492117 cl:1.490152186808879
filename: 2_hidden Epoch 54 loss:0.147643393045019 ael:0.0015057062242065735 cl:1.4613768433443983
filename: 2_hidden Epoch 55 loss:0.14531736157899885 ael:0.0014893937663975777 cl:1.4382796544342014
filename: 2_hidden Epoch 56 loss:0.14339830111058657 ael:0.0014744827486894623 cl:1.4192381594874706
filename: 2_hidden Epoch 57 loss:0.1407851179173946 ael:0.0014542433033099573 cl:1.3933087228900856
filename: 2_hidden Epoch 58 loss:0.13839137733244058 ael:0.0014343116748655946 cl:1.3695706307626607
filename: 2_hidden Epoch 59 loss:0.1365828444151894 ael:0.0014103374890717597 cl:1.3517250444413278
filename: 2_hidden Epoch 60 loss:0.13484494654320137 ael:0.0013769590760661528 cl:1.3346798505960848
filename: 2_hidden Epoch 61 loss:0.13315345378244045 ael:0.0013477575817323775 cl:1.3180569370849091
filename: 2_hidden Epoch 62 loss:0.13185285969544747 ael:0.0013260117601787084 cl:1.305268458939261
filename: 2_hidden Epoch 63 loss:0.1305785500330099 ael:0.0013042525456890147 cl:1.2927429526826444
filename: 2_hidden Epoch 64 loss:0.12871807833959223 ael:0.0012825812460420304 cl:1.2743549474716536
filename: 2_hidden Epoch 65 loss:0.1267029186607235 ael:0.001260886871142242 cl:1.2544202974534522
filename: 2_hidden Epoch 66 loss:0.1254614618797487 ael:0.0012517774602866661 cl:1.2420968207133096
filename: 2_hidden Epoch 67 loss:0.12385919817630746 ael:0.001238149209036519 cl:1.2262104695521252
filename: 2_hidden Epoch 68 loss:0.12284013512789418 ael:0.001225139455575692 cl:1.2161499380237526
filename: 2_hidden Epoch 69 loss:0.12095086403866434 ael:0.001203445816458181 cl:1.1974741581762045
filename: 2_hidden Epoch 70 loss:0.11958830590136567 ael:0.0011904823964145796 cl:1.183978213748911
filename: 2_hidden Epoch 71 loss:0.11913588758645176 ael:0.0011744332031247463 cl:1.1796145228048165
filename: 2_hidden Epoch 72 loss:0.11771625143895198 ael:0.001158285351815274 cl:1.1655796432355692
filename: 2_hidden Epoch 73 loss:0.11640540478990702 ael:0.0011355415549284468 cl:1.1526986111064403
filename: 2_hidden Epoch 74 loss:0.11569628239995991 ael:0.0011186291373127865 cl:1.1457765133931623
filename: 2_hidden Epoch 75 loss:0.11402066797399295 ael:0.001094406067270497 cl:1.1292626009480646
filename: 2_hidden Epoch 76 loss:0.11259296551695344 ael:0.0010579299388660324 cl:1.1153503359932648
filename: 2_hidden Epoch 77 loss:0.11148854025710396 ael:0.001040295604037731 cl:1.104482425814658
filename: 2_hidden Epoch 78 loss:0.11030624725839548 ael:0.0010161402867766565 cl:1.0929010521119449
filename: 2_hidden Epoch 79 loss:0.1093431339365 ael:0.0009971132831718113 cl:1.0834601863303728
filename: 2_hidden Epoch 80 loss:0.10844226553763824 ael:0.000980472508344761 cl:1.0746179107031975
filename: 2_hidden Epoch 81 loss:0.10754124351630086 ael:0.0009612648884104756 cl:1.0657997672320807
filename: 2_hidden Epoch 82 loss:0.10677359014509888 ael:0.0009470651618767344 cl:1.058265229728487
filename: 2_hidden Epoch 83 loss:0.10545070097204406 ael:0.0009226562440914799 cl:1.0452804289671065
filename: 2_hidden Epoch 84 loss:0.10434019709310946 ael:0.0009050739742883574 cl:1.0343512145050786
filename: 2_hidden Epoch 85 loss:0.1033401050359795 ael:0.0008926718093608697 cl:1.0244743152015041
filename: 2_hidden Epoch 86 loss:0.10296975330923472 ael:0.0008765208674118206 cl:1.020932307055122
filename: 2_hidden Epoch 87 loss:0.101827357873887 ael:0.0008533560989097126 cl:1.0097400017474827
filename: 2_hidden Epoch 88 loss:0.10047557572344024 ael:0.0008258856053134612 cl:0.9964968844071815
filename: 2_hidden Epoch 89 loss:0.0997515657717874 ael:0.0008053190554053065 cl:0.9894624498286094
filename: 2_hidden Epoch 90 loss:0.09897087909313931 ael:0.0007828986803488397 cl:0.9818797860664931
filename: 2_hidden Epoch 91 loss:0.09821320966142094 ael:0.0007710383206432991 cl:0.9744216986000538
filename: 2_hidden Epoch 92 loss:0.09729550229331031 ael:0.0007509832388135245 cl:0.9654451733139174
filename: 2_hidden Epoch 93 loss:0.09630949929525412 ael:0.0007297905718183352 cl:0.955797071929215
filename: 2_hidden Epoch 94 loss:0.09570091503906494 ael:0.0007109243647237608 cl:0.9498998913805039
filename: 2_hidden Epoch 95 loss:0.09476532333486914 ael:0.0006908822010716489 cl:0.9407443959897722
filename: 2_hidden Epoch 96 loss:0.0944223119583177 ael:0.0006742478000175083 cl:0.9374806257672825
filename: 2_hidden Epoch 97 loss:0.09344775435509302 ael:0.0006597004033417825 cl:0.9278805245324011
filename: 2_hidden Epoch 98 loss:0.0925771196503519 ael:0.0006424917784025579 cl:0.9193462619089592
filename: 2_hidden Epoch 99 loss:0.09180819727289789 ael:0.0006300454800819151 cl:0.9117815024627928
filename: 2_hidden Epoch 100 loss:0.09101221499724957 ael:0.0006157973851945267 cl:0.9039641609578802
filename: 2_hidden Epoch 101 loss:0.0901443846245999 ael:0.0006061544399745953 cl:0.8953822852836715
filename: 2_hidden Epoch 102 loss:0.08972686041604008 ael:0.0005995989411477713 cl:0.8912726010604386
filename: 2_hidden Epoch 103 loss:0.08884039473480257 ael:0.0005901689944385105 cl:0.882502243103601
filename: 2_hidden Epoch 104 loss:0.08829106098934136 ael:0.0005813075926017672 cl:0.8770975188945818
filename: 2_hidden Epoch 105 loss:0.08767234032499817 ael:0.0005741820852775998 cl:0.8709815647039149
filename: 2_hidden Epoch 106 loss:0.08683276519026847 ael:0.000567962399326307 cl:0.8626480148658592
filename: 2_hidden Epoch 107 loss:0.08619131619241416 ael:0.0005587356085228674 cl:0.8563257931072635
filename: 2_hidden Epoch 108 loss:0.08590515904449884 ael:0.0005577202727718617 cl:0.8534743737560092
filename: 2_hidden Epoch 109 loss:0.084789720071447 ael:0.0005472516591195358 cl:0.8424246686548866
filename: 2_hidden Epoch 110 loss:0.084126049074023 ael:0.0005393795555812165 cl:0.8358666816475796
filename: 2_hidden Epoch 111 loss:0.08333166066981983 ael:0.0005325151571354826 cl:0.8279914395415295
filename: 2_hidden Epoch 112 loss:0.08260852014128532 ael:0.0005247416031114247 cl:0.8208377717335148
filename: 2_hidden Epoch 113 loss:0.08181753232013107 ael:0.0005160333555828636 cl:0.813014975957006
filename: 2_hidden Epoch 114 loss:0.08118961809981853 ael:0.000509960778678457 cl:0.8067965604452013
filename: 2_hidden Epoch 115 loss:0.08046661064747655 ael:0.0005011789055731099 cl:0.7996543027351648
filename: 2_hidden Epoch 116 loss:0.07963483036544762 ael:0.0004938086842687812 cl:0.791410203095068
filename: 2_hidden Epoch 117 loss:0.0788263338939314 ael:0.00048493536923006474 cl:0.7834139715226596
filename: 2_hidden Epoch 118 loss:0.07831281962401468 ael:0.0004750928253370095 cl:0.7783772555011058
filename: 2_hidden Epoch 119 loss:0.07760173382607904 ael:0.0004668971885780992 cl:0.7713483535581165
filename: 2_hidden Epoch 120 loss:0.0771747524398025 ael:0.000459144595311444 cl:0.767156066301099
filename: 2_hidden Epoch 121 loss:0.0764947627967888 ael:0.00044745435606863905 cl:0.7604730712652904
filename: 2_hidden Epoch 122 loss:0.07600199837531699 ael:0.0004417141340196416 cl:0.7556028286311013
filename: 2_hidden Epoch 123 loss:0.07526262675722441 ael:0.00043276162874750104 cl:0.7482986383793647
filename: 2_hidden Epoch 124 loss:0.0748511064405504 ael:0.0004286276383064374 cl:0.7442247754910536
filename: 2_hidden Epoch 125 loss:0.0743385146598043 ael:0.00042281179415788473 cl:0.7391570159958468
filename: 2_hidden Epoch 126 loss:0.07368681198258323 ael:0.00041340848644419264 cl:0.7327340219256996
filename: 2_hidden Epoch 127 loss:0.0736198069424265 ael:0.00040935726478865726 cl:0.7321044841617869
filename: 2_hidden Epoch 128 loss:0.07278440647911041 ael:0.0004025189357565318 cl:0.7238188627061614
filename: 2_hidden Epoch 129 loss:0.07246605777562928 ael:0.00039791858102385927 cl:0.7206813799620372
filename: 2_hidden Epoch 130 loss:0.07213344060494538 ael:0.0003923610256117161 cl:0.7174107835786036
filename: 2_hidden Epoch 131 loss:0.0716819028397314 ael:0.0003886017480153524 cl:0.7129329983624275
filename: 2_hidden Epoch 132 loss:0.0713876460490977 ael:0.00038387362807968696 cl:0.7100377122800775
filename: 2_hidden Epoch 133 loss:0.0708962334992571 ael:0.0003793191322271354 cl:0.7051691308639377
filename: 2_hidden Epoch 134 loss:0.07071377127690034 ael:0.00037441042148745045 cl:0.7033935969466703
filename: 2_hidden Epoch 135 loss:0.07047659909810151 ael:0.0003691386518341609 cl:0.7010745929020364
filename: 2_hidden Epoch 136 loss:0.07021272903368182 ael:0.0003653681307600652 cl:0.6984735964138431
filename: 2_hidden Epoch 137 loss:0.0701417095866599 ael:0.0003615958874753121 cl:0.6978011246705265
filename: 2_hidden Epoch 138 loss:0.06963553999629613 ael:0.0003566001305273735 cl:0.6927893854786604
filename: 2_hidden Epoch 139 loss:0.06942169292113738 ael:0.00035418125661055975 cl:0.6906751047384146
filename: 2_hidden Epoch 140 loss:0.06900690963249435 ael:0.00034844656708484857 cl:0.6865846187290218
filename: 2_hidden Epoch 141 loss:0.0688379603563345 ael:0.0003451465027881153 cl:0.6849281260384279
filename: 2_hidden Epoch 142 loss:0.06860959964099052 ael:0.0003404866520543304 cl:0.6826911190753443
filename: 2_hidden Epoch 143 loss:0.06840606091356134 ael:0.00033549874388610765 cl:0.6807056126081281
filename: 2_hidden Epoch 144 loss:0.06819335189062492 ael:0.00033190932931973833 cl:0.6786144140737447
filename: 2_hidden Epoch 145 loss:0.06784855642530262 ael:0.0003288564101388822 cl:0.6751969898718665
filename: 2_hidden Epoch 146 loss:0.06771950673459 ael:0.00032412134811419336 cl:0.673953843807355
filename: 2_hidden Epoch 147 loss:0.06766977280157765 ael:0.00032013953035676577 cl:0.6734963204864173
filename: 2_hidden Epoch 148 loss:0.06749502241676837 ael:0.0003156189130031475 cl:0.6717940240913228
filename: 2_hidden Epoch 149 loss:0.06719384131291391 ael:0.0003112311142199599 cl:0.668826090445339
filename: 2_hidden Epoch 150 loss:0.06713960653140988 ael:0.000308516914691614 cl:0.6683108852097862
filename: 2_hidden Epoch 151 loss:0.06686699098188495 ael:0.0003030985827519959 cl:0.6656389123471508
filename: 2_hidden Epoch 152 loss:0.06662447799898531 ael:0.0003000723550621044 cl:0.6632440442491693
filename: 2_hidden Epoch 153 loss:0.06655662512523802 ael:0.0002961159769033098 cl:0.6626050808461524
filename: 2_hidden Epoch 154 loss:0.06654035626346931 ael:0.00029450128192275393 cl:0.6624585388718467
filename: 2_hidden Epoch 155 loss:0.06610301429697187 ael:0.00028760745617706054 cl:0.6581540576645244
filename: 2_hidden Epoch 156 loss:0.06632157631820253 ael:0.0002854155671634039 cl:0.6603615962851205
filename: 2_hidden Epoch 157 loss:0.06597996901677192 ael:0.0002820641628715206 cl:0.6569790363671225
filename: 2_hidden Epoch 158 loss:0.06584566022427371 ael:0.0002780555083528903 cl:0.6556760355743051
filename: 2_hidden Epoch 159 loss:0.06607548094202073 ael:0.0002751371403266805 cl:0.658003425747374
filename: 2_hidden Epoch 160 loss:0.06533928447054449 ael:0.00027128838995190427 cl:0.6506799499792923
filename: 2_hidden Epoch 161 loss:0.06526695144300115 ael:0.000268092317338941 cl:0.6499885802402308
filename: 2_hidden Epoch 162 loss:0.06504225930776338 ael:0.0002647392189871228 cl:0.6477751912287715
filename: 2_hidden Epoch 163 loss:0.06501649999214958 ael:0.00026332925006616875 cl:0.6475316971202778
filename: 2_hidden Epoch 164 loss:0.0648176497341357 ael:0.0002610991230103962 cl:0.6455654953927761
filename: 2_hidden Epoch 165 loss:0.06470941651656091 ael:0.00025802735977585573 cl:0.6445138813884199
filename: 2_hidden Epoch 166 loss:0.0645999124334929 ael:0.00025585378367736 cl:0.6434405741755638
filename: 2_hidden Epoch 167 loss:0.06449612203484391 ael:0.00025423928327122854 cl:0.6424188151792215
filename: 2_hidden Epoch 168 loss:0.06429486224544916 ael:0.000252232437617893 cl:0.6404262876410408
filename: 2_hidden Epoch 169 loss:0.06414088162985679 ael:0.00025104257978593566 cl:0.6388983802161893
filename: 2_hidden Epoch 170 loss:0.06395465696029017 ael:0.0002483087916287821 cl:0.6370634708117846
filename: 2_hidden Epoch 171 loss:0.06402962069539081 ael:0.00024777603488558786 cl:0.6378184351808669
filename: 2_hidden Epoch 172 loss:0.0638431799751897 ael:0.0002457763908219208 cl:0.6359740241860959
filename: 2_hidden Epoch 173 loss:0.06368937638604588 ael:0.0002443410674182729 cl:0.6344503429669298
filename: 2_hidden Epoch 174 loss:0.06358785419547876 ael:0.0002426099148238546 cl:0.6334524328477289
filename: 2_hidden Epoch 175 loss:0.06339178954221156 ael:0.00024013905660669681 cl:0.6315164929005312
filename: 2_hidden Epoch 176 loss:0.06372333981521558 ael:0.0002391834586355985 cl:0.6348415533668901
filename: 2_hidden Epoch 177 loss:0.06328964400641642 ael:0.00023754595845089464 cl:0.6305209685182362
filename: 2_hidden Epoch 178 loss:0.06328915357194863 ael:0.0002351383967270628 cl:0.6305401408434873
filename: 2_hidden Epoch 179 loss:0.0631345730616673 ael:0.0002326351858728922 cl:0.6290193680227238
filename: 2_hidden Epoch 180 loss:0.06304226528719743 ael:0.00023274885356973935 cl:0.6280951530176994
filename: 2_hidden Epoch 181 loss:0.06318745793467007 ael:0.00023032298798527165 cl:0.6295713384161916
filename: 2_hidden Epoch 182 loss:0.06289413287127336 ael:0.00022801533726480387 cl:0.6266611648799731
filename: 2_hidden Epoch 183 loss:0.06265939705248116 ael:0.00022692425798446727 cl:0.6243247177179533
filename: 2_hidden Epoch 184 loss:0.06261773055285891 ael:0.00022541101560398613 cl:0.6239231841377261
filename: 2_hidden Epoch 185 loss:0.06260493770241737 ael:0.0002244289803983472 cl:0.6238050782562871
filename: 2_hidden Epoch 186 loss:0.06255641194722174 ael:0.00022419922235542678 cl:0.6233221163777144
filename: 2_hidden Epoch 187 loss:0.0627201674000921 ael:0.00022262657315750084 cl:0.624975397192726
filename: 2_hidden Epoch 188 loss:0.06267269021526459 ael:0.00021963015459259197 cl:0.6245305895729111
filename: 2_hidden Epoch 189 loss:0.06206172833216447 ael:0.00021839679923511555 cl:0.6184333044044369
filename: 2_hidden Epoch 190 loss:0.06192099798650465 ael:0.0002168681214902923 cl:0.617041288189895
filename: 2_hidden Epoch 191 loss:0.062256237404279366 ael:0.00021474477957010137 cl:0.6204149154325326
filename: 2_hidden Epoch 192 loss:0.061964212171052586 ael:0.00021418281945092562 cl:0.6175002821802832
filename: 2_hidden Epoch 193 loss:0.06192705120785129 ael:0.00021415311328499824 cl:0.6171289713661138
filename: 2_hidden Epoch 194 loss:0.06222671470237209 ael:0.0002110007636511851 cl:0.6201571289046902
filename: 2_hidden Epoch 195 loss:0.06195967836599601 ael:0.0002094011386872265 cl:0.6175027621082134
filename: 2_hidden Epoch 196 loss:0.06177643429071299 ael:0.00020914347422159785 cl:0.6156728970006718
filename: 2_hidden Epoch 197 loss:0.061854906673597616 ael:0.00020682157716867534 cl:0.6164808388538006

C:\Users\linco\AppData\Local\Temp\ipykernel_50728\310156585.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
C:\Users\linco\AppData\Local\Temp\ipykernel_50728\310156585.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                 0         1         2          3         4  Label
0        -9.728436 -3.439696 -0.767168  -7.410339 -0.668419      1
1        -7.966755  1.431511  5.786341  -4.240134 -6.364508      0
2        -9.721034 -3.624488 -0.952733  -7.542887 -0.462198      1
3       -17.721903 -5.340550  0.766456 -12.921812 -3.247771      4
4         3.264348  2.421045  1.280416   2.672033 -0.459594      3
...            ...       ...       ...        ...       ...    ...
1750627  -7.579495  1.514676  5.700517  -3.978048 -6.226617      0
1750628  -7.571639  1.500337  5.618656  -3.996136 -6.131295      0
1750629  -7.917034  1.401869  5.637842  -4.265766 -6.208309      0
1750630  -7.507266  1.536207  5.693968  -3.926549 -6.209620      0
1750631  -8.044336  1.431461  5.829637  -4.285414 -6.416201      0

[1750632 rows x 6 columns]

Davies-Bouldin Score: 0.38979882774471386

                0         1         2          3         4  Label
0       -7.565323  1.506397  5.624033  -3.989495 -6.135075      0
1      -10.109042 -4.324031 -1.824092  -8.059054  0.274110      2
2       -9.768901 -3.483863 -0.784533  -7.507581 -0.620393      1
3        3.199046  2.494155  1.364564   2.675728 -0.594111      3
4       -9.759067 -3.467586 -0.681619  -7.460961 -0.731647      1
...           ...       ...       ...        ...       ...    ...
519951  -9.855269 -3.531363 -0.759258  -7.579683 -0.632504      1
519952 -17.254936 -5.211774  0.713820 -12.626521 -3.070287      4
519953  -7.860659  1.431576  5.727128  -4.178214 -6.293811      0
519954  -9.815589 -3.513919 -0.814042  -7.527496 -0.644084      1
519955   3.246675  2.485764  1.363209   2.726576 -0.576074      3

[519956 rows x 6 columns]

                0         1         2         3         4  Label
0       -7.952002  1.431521  5.778109 -4.231523 -6.354680      0
1       -7.580684  1.492344  5.611934 -4.005294 -6.126744      0
2       -9.708896 -3.382321 -0.618069 -7.447104 -0.751739      1
3      -10.174584 -3.677358 -0.807981 -7.855811 -0.649249      1
4       -7.913317  1.403381  5.638354 -4.263341 -6.208196      0
...           ...       ...       ...       ...       ...    ...
649942  -9.749481 -3.461485 -0.678479 -7.453724 -0.734804      1
649943  -8.046699  1.362182  5.642817 -4.349304 -6.232870      0
649944  -8.023970  1.368098  5.640789 -4.335616 -6.227309      0
649945   3.168465  2.481359  1.367637  2.667709 -0.564579      3
649946  -9.414099 -3.697679 -1.256473 -7.420274 -0.139107      2

[649947 rows x 6 columns]

3_hidden
cuda
[0.0, 1.0, 2.0, 4.0, 5.0]
pick completo
82 5
filename: 3_hidden Epoch 1 loss:3.4348473930079724 ael:0.015225894994717501 cl:34.196214478362194
filename: 3_hidden Epoch 2 loss:1.6737385530607396 ael:0.008639697796723031 cl:16.65098824885219
filename: 3_hidden Epoch 3 loss:1.1941484441024732 ael:0.0061190944125526356 cl:11.880293283284391
filename: 3_hidden Epoch 4 loss:1.1148446677520079 ael:0.004516625514262801 cl:11.103280213007462
filename: 3_hidden Epoch 5 loss:1.0647227548775249 ael:0.0032759278864426585 cl:10.614468081202851
filename: 3_hidden Epoch 6 loss:1.0299792457979504 ael:0.0024892265232321956 cl:10.274900020315416
filename: 3_hidden Epoch 7 loss:1.0054402321385978 ael:0.0020620336945873334 cl:10.033781802451541
filename: 3_hidden Epoch 8 loss:0.9856094029543292 ael:0.0018490948761537606 cl:9.837602919777156
filename: 3_hidden Epoch 9 loss:0.9678691573584349 ael:0.001742630258172305 cl:9.661265112943626
filename: 3_hidden Epoch 10 loss:0.9430266609672454 ael:0.0016904499049183964 cl:9.41336194246567
filename: 3_hidden Epoch 11 loss:0.893884236620833 ael:0.0022061507750883104 cl:8.916780710818543
filename: 3_hidden Epoch 12 loss:0.8160906919686616 ael:0.003095314613956795 cl:8.129953634715658
filename: 3_hidden Epoch 13 loss:0.7302628959125883 ael:0.003714178308648799 cl:7.265487050092882
filename: 3_hidden Epoch 14 loss:0.6328058985903431 ael:0.0029319129156087404 cl:6.298739746948255
filename: 3_hidden Epoch 15 loss:0.5536493809526599 ael:0.0027461854163217166 cl:5.50903186161338
filename: 3_hidden Epoch 16 loss:0.452068831699952 ael:0.0027754681417199254 cl:4.4929335566992075
filename: 3_hidden Epoch 17 loss:0.38278552278946926 ael:0.0025467526999187707 cl:3.802387633860726
filename: 3_hidden Epoch 18 loss:0.34959248344122884 ael:0.002295202149784726 cl:3.472972753904043
filename: 3_hidden Epoch 19 loss:0.32980715104978264 ael:0.002145700038650629 cl:3.2766144517440465
filename: 3_hidden Epoch 20 loss:0.3160021195246843 ael:0.002058636793298925 cl:3.1394347744895983
filename: 3_hidden Epoch 21 loss:0.3047353439998886 ael:0.002032331429221461 cl:3.0270300738852036
filename: 3_hidden Epoch 22 loss:0.29349084286336485 ael:0.002065628508089257 cl:2.9142520923384523
filename: 3_hidden Epoch 23 loss:0.28320571000043615 ael:0.0020771099290903218 cl:2.811285952272806
filename: 3_hidden Epoch 24 loss:0.2736055925249605 ael:0.0020776739178027036 cl:2.715279137794108
filename: 3_hidden Epoch 25 loss:0.2650887999722045 ael:0.00203832591189825 cl:2.6305046962651497
filename: 3_hidden Epoch 26 loss:0.2575834279436985 ael:0.0019871901488321066 cl:2.555962332833069
filename: 3_hidden Epoch 27 loss:0.25070756338360184 ael:0.0019386393019819443 cl:2.4876891958919582
filename: 3_hidden Epoch 28 loss:0.24358960568327442 ael:0.0018771072246102085 cl:2.4171249447824033
filename: 3_hidden Epoch 29 loss:0.23759244726142545 ael:0.0018103581523859745 cl:2.3578208474219595
filename: 3_hidden Epoch 30 loss:0.23228300263435853 ael:0.0017562170878187983 cl:2.3052678124416763
filename: 3_hidden Epoch 31 loss:0.2272694115564622 ael:0.0017577244839054624 cl:2.2551168295909743
filename: 3_hidden Epoch 32 loss:0.22237851395725305 ael:0.0017574440760528636 cl:2.206210659802841
filename: 3_hidden Epoch 33 loss:0.21786233635085986 ael:0.0016665425206629852 cl:2.1619579007956586
filename: 3_hidden Epoch 34 loss:0.21398936796456716 ael:0.0016116422029612738 cl:2.1237772218706485
filename: 3_hidden Epoch 35 loss:0.2105712315661182 ael:0.0015918151659832331 cl:2.089794127621091
filename: 3_hidden Epoch 36 loss:0.20734126830604918 ael:0.0015728122468616898 cl:2.0576845220712556
filename: 3_hidden Epoch 37 loss:0.20445144945843358 ael:0.0015593591490483932 cl:2.0289208658781095
filename: 3_hidden Epoch 38 loss:0.2021888857351677 ael:0.0015470536001460746 cl:2.0064182882941064
filename: 3_hidden Epoch 39 loss:0.19926401436617605 ael:0.001531661619768632 cl:1.9773234944631704
filename: 3_hidden Epoch 40 loss:0.19692568041245054 ael:0.00151451406264997 cl:1.9541116298773775
filename: 3_hidden Epoch 41 loss:0.19505580557405883 ael:0.0014965952949496913 cl:1.9355920688094685
filename: 3_hidden Epoch 42 loss:0.1930093148763229 ael:0.0014686870711060058 cl:1.915406248036586
filename: 3_hidden Epoch 43 loss:0.19110456378811128 ael:0.0014386018631861168 cl:1.8966595891760292
filename: 3_hidden Epoch 44 loss:0.1886942106830582 ael:0.0014017435496265097 cl:1.8729246383071245
filename: 3_hidden Epoch 45 loss:0.18618481178101487 ael:0.0013681416781396551 cl:1.84816667078214
filename: 3_hidden Epoch 46 loss:0.1846414549862496 ael:0.0013429682646182363 cl:1.832984835395482
filename: 3_hidden Epoch 47 loss:0.18307136852218392 ael:0.0013215144245088482 cl:1.8174985126761762
filename: 3_hidden Epoch 48 loss:0.180814254627043 ael:0.0012965656079651524 cl:1.795176858182634
filename: 3_hidden Epoch 49 loss:0.17961501456736886 ael:0.001263408575901917 cl:1.7835160282318194
filename: 3_hidden Epoch 50 loss:0.17760640258971183 ael:0.001224330407820794 cl:1.7638206928760718
filename: 3_hidden Epoch 51 loss:0.17599939390215197 ael:0.0011352423621803548 cl:1.7486414859304529
filename: 3_hidden Epoch 52 loss:0.1749122428456189 ael:0.0010596897617023157 cl:1.7385254993947528
filename: 3_hidden Epoch 53 loss:0.1732376981599312 ael:0.0010255097161525025 cl:1.7221218525723625
filename: 3_hidden Epoch 54 loss:0.1717414723593427 ael:0.001013881341347455 cl:1.707275882608418
filename: 3_hidden Epoch 55 loss:0.17033578526744828 ael:0.0009936388585528768 cl:1.6934214349382264
filename: 3_hidden Epoch 56 loss:0.16873562839458606 ael:0.000979025196412252 cl:1.6775660039963483
filename: 3_hidden Epoch 57 loss:0.16745395310989555 ael:0.0009622340699294823 cl:1.664917163594473
filename: 3_hidden Epoch 58 loss:0.1661578463434608 ael:0.0009539918118939432 cl:1.6520385193623703
filename: 3_hidden Epoch 59 loss:0.16464311324147202 ael:0.0009388010182030354 cl:1.6370430935972875
filename: 3_hidden Epoch 60 loss:0.1633366007427419 ael:0.0009333218223212019 cl:1.6240327619919712
filename: 3_hidden Epoch 61 loss:0.16172953507755755 ael:0.0009283767518184192 cl:1.6080115547511185
filename: 3_hidden Epoch 62 loss:0.16033069757889548 ael:0.0009268902772843798 cl:1.5940380459098322
filename: 3_hidden Epoch 63 loss:0.15872830435984692 ael:0.0009363133573737102 cl:1.5779198852004466
filename: 3_hidden Epoch 64 loss:0.1573680099665886 ael:0.0009402718455620278 cl:1.564277353415856
filename: 3_hidden Epoch 65 loss:0.15586487669212126 ael:0.0009277188937841303 cl:1.5493715493367315
filename: 3_hidden Epoch 66 loss:0.15427072997487187 ael:0.0009204115265566759 cl:1.5335031584972854
filename: 3_hidden Epoch 67 loss:0.15293123547256757 ael:0.0009177970992635112 cl:1.5201343552403905
filename: 3_hidden Epoch 68 loss:0.1511664643166065 ael:0.0009074995980972821 cl:1.5025896203652511
filename: 3_hidden Epoch 69 loss:0.14931349662722718 ael:0.0009009927920275348 cl:1.4841250136000286
filename: 3_hidden Epoch 70 loss:0.1476149479462629 ael:0.0008900077863403468 cl:1.467249376480713
filename: 3_hidden Epoch 71 loss:0.14540172729185274 ael:0.0008622121309647275 cl:1.4453951273957832
filename: 3_hidden Epoch 72 loss:0.1433995329321328 ael:0.0008455142081196669 cl:1.4255401616329797
filename: 3_hidden Epoch 73 loss:0.14109804567935194 ael:0.000832289984086705 cl:1.4026575318312027
filename: 3_hidden Epoch 74 loss:0.13899363302305062 ael:0.0008191515404458999 cl:1.3817447913425827
filename: 3_hidden Epoch 75 loss:0.13683895160895074 ael:0.0008076925232278776 cl:1.3603125660739173
filename: 3_hidden Epoch 76 loss:0.1348682342080027 ael:0.0007979919492593048 cl:1.3407023996197815
filename: 3_hidden Epoch 77 loss:0.13264470552890073 ael:0.0007930350897011041 cl:1.3185166831855026
filename: 3_hidden Epoch 78 loss:0.13015593896439007 ael:0.000788010868828319 cl:1.2936792591919566
filename: 3_hidden Epoch 79 loss:0.12801659924289976 ael:0.00077123221579535 cl:1.272453650769863
filename: 3_hidden Epoch 80 loss:0.12635073350736747 ael:0.0007613869308311506 cl:1.2558934442887972
filename: 3_hidden Epoch 81 loss:0.12452824107507061 ael:0.0007546964207831469 cl:1.2377354276397947
filename: 3_hidden Epoch 82 loss:0.12254164272626944 ael:0.0007517283207848294 cl:1.217899124046405
filename: 3_hidden Epoch 83 loss:0.12099638751183242 ael:0.000755439197092795 cl:1.202409460991081
filename: 3_hidden Epoch 84 loss:0.11945386823907532 ael:0.0007534070505169219 cl:1.1870045907689497
filename: 3_hidden Epoch 85 loss:0.11841078941505959 ael:0.0007479906532406697 cl:1.1766279653558034
filename: 3_hidden Epoch 86 loss:0.11719154493723834 ael:0.0007473587214738127 cl:1.164441840833763
filename: 3_hidden Epoch 87 loss:0.1162367888409795 ael:0.0007398129372088592 cl:1.1549697383129067
filename: 3_hidden Epoch 88 loss:0.11516323077599128 ael:0.0007377332443980787 cl:1.1442549548417968
filename: 3_hidden Epoch 89 loss:0.11160398345074017 ael:0.0007361698921607973 cl:1.108678118246061
filename: 3_hidden Epoch 90 loss:0.10928684742620165 ael:0.0007244753801383757 cl:1.08562370287714
filename: 3_hidden Epoch 91 loss:0.10800956688994755 ael:0.0007158753223171193 cl:1.0729368975672144
filename: 3_hidden Epoch 92 loss:0.10637006497959307 ael:0.0007124485805597775 cl:1.0565761459120508
filename: 3_hidden Epoch 93 loss:0.10541464038300197 ael:0.0006997059153413422 cl:1.0471493261901323
filename: 3_hidden Epoch 94 loss:0.10422254702689582 ael:0.0006889022517028146 cl:1.0353364297480911
filename: 3_hidden Epoch 95 loss:0.10312710023698807 ael:0.0006776632959100555 cl:1.0244943544513707
filename: 3_hidden Epoch 96 loss:0.10221159067950003 ael:0.0006631375737802108 cl:1.0154845107098558
filename: 3_hidden Epoch 97 loss:0.10104750240351958 ael:0.0006460671740439197 cl:1.0040143347709565
filename: 3_hidden Epoch 98 loss:0.09999934405193318 ael:0.0006298916125857015 cl:0.9936945085546949
filename: 3_hidden Epoch 99 loss:0.09914268775507372 ael:0.0006181406762564136 cl:0.9852454542806297
filename: 3_hidden Epoch 100 loss:0.09801859105021958 ael:0.0006144184226185176 cl:0.9740417096062826
filename: 3_hidden Epoch 101 loss:0.09721376543570177 ael:0.0006093453007709255 cl:0.9660441857137685
filename: 3_hidden Epoch 102 loss:0.09594267285770365 ael:0.0006020350328684637 cl:0.9534063621948349
filename: 3_hidden Epoch 103 loss:0.09485266117962217 ael:0.0005972831054577466 cl:0.9425537646655954
filename: 3_hidden Epoch 104 loss:0.09374978985083877 ael:0.0005885340279757645 cl:0.93161254035943
filename: 3_hidden Epoch 105 loss:0.09278676990972136 ael:0.0005837887507132266 cl:0.9220297960956548
filename: 3_hidden Epoch 106 loss:0.09169580734246349 ael:0.0005839761165894684 cl:0.9111182954975546
filename: 3_hidden Epoch 107 loss:0.09063645541005341 ael:0.0005787365675990121 cl:0.9005771724728944
filename: 3_hidden Epoch 108 loss:0.08961554610120832 ael:0.0005733103448428226 cl:0.890422342319674
filename: 3_hidden Epoch 109 loss:0.08880607995139977 ael:0.0005672208690403224 cl:0.8823885751308124
filename: 3_hidden Epoch 110 loss:0.08780748479313377 ael:0.0005576530251676538 cl:0.8724983025675601
filename: 3_hidden Epoch 111 loss:0.08700379665503769 ael:0.0005484213403786748 cl:0.8645537385651086
filename: 3_hidden Epoch 112 loss:0.08581532088321524 ael:0.0005384037490422775 cl:0.8527691569797236
filename: 3_hidden Epoch 113 loss:0.08540123922904579 ael:0.0005305944633252328 cl:0.848706432677658
filename: 3_hidden Epoch 114 loss:0.08450110027904602 ael:0.0005233375771095611 cl:0.8397776120351921
filename: 3_hidden Epoch 115 loss:0.0831841710871301 ael:0.0005145106948898513 cl:0.8266965889826039
filename: 3_hidden Epoch 116 loss:0.08264819472812164 ael:0.0005058007170288162 cl:0.8214239239555599
filename: 3_hidden Epoch 117 loss:0.08245584799964963 ael:0.0005003887135668543 cl:0.8195545813263476
filename: 3_hidden Epoch 118 loss:0.08162895721885273 ael:0.0004899316624961435 cl:0.8113902421579375
filename: 3_hidden Epoch 119 loss:0.08082504765861981 ael:0.0004854980740811536 cl:0.8033954820839482
filename: 3_hidden Epoch 120 loss:0.08010019748522307 ael:0.00048023328734751985 cl:0.7961996272850209
filename: 3_hidden Epoch 121 loss:0.07943683235685632 ael:0.0004758988934237568 cl:0.7896093205136777
filename: 3_hidden Epoch 122 loss:0.07886839456880138 ael:0.0004708649230963733 cl:0.7839752843046308
filename: 3_hidden Epoch 123 loss:0.07828610299759035 ael:0.00046732014814606065 cl:0.7781878152152341
filename: 3_hidden Epoch 124 loss:0.07764935602867835 ael:0.00047069619096583727 cl:0.7717865848602742
filename: 3_hidden Epoch 125 loss:0.07690817839874965 ael:0.0004685915518011011 cl:0.7643958548998347
filename: 3_hidden Epoch 126 loss:0.07635525483516019 ael:0.0004682582132656062 cl:0.7588699535760901
filename: 3_hidden Epoch 127 loss:0.07573786656239055 ael:0.00046571634858250794 cl:0.752721488874604
filename: 3_hidden Epoch 128 loss:0.07534902222448836 ael:0.0004627454437603403 cl:0.7488627541786388
filename: 3_hidden Epoch 129 loss:0.07432767818091218 ael:0.000460938594130814 cl:0.7386673811915561
filename: 3_hidden Epoch 130 loss:0.0742159156752675 ael:0.0004598309586222602 cl:0.7375608338933654
filename: 3_hidden Epoch 131 loss:0.07306390179317016 ael:0.00045923034332140633 cl:0.726046701832455
filename: 3_hidden Epoch 132 loss:0.07266631303549827 ael:0.00045784383150977714 cl:0.7220846786679649
filename: 3_hidden Epoch 133 loss:0.07220117355898596 ael:0.00045519647366247653 cl:0.717459758449214
filename: 3_hidden Epoch 134 loss:0.07171004894105154 ael:0.00045064162468962 cl:0.7125940609828223
filename: 3_hidden Epoch 135 loss:0.07139636245162824 ael:0.00045044957288571864 cl:0.709459116614385
filename: 3_hidden Epoch 136 loss:0.07094952713901705 ael:0.00044864455754802803 cl:0.7050088126952847
filename: 3_hidden Epoch 137 loss:0.07076817926848715 ael:0.00044572546995194423 cl:0.7032245253073843
filename: 3_hidden Epoch 138 loss:0.07022053555912329 ael:0.00044306990138627577 cl:0.6977746443304222
filename: 3_hidden Epoch 139 loss:0.06982335348628879 ael:0.000440468025586533 cl:0.6938288427311912
filename: 3_hidden Epoch 140 loss:0.06944290677395527 ael:0.0004400166796271684 cl:0.6900288878548252
filename: 3_hidden Epoch 141 loss:0.06906762450506611 ael:0.000437603426413882 cl:0.6863002005859624
filename: 3_hidden Epoch 142 loss:0.06872714361617799 ael:0.00043539044380005006 cl:0.682917520912753
filename: 3_hidden Epoch 143 loss:0.0684610533817267 ael:0.00043120208267020407 cl:0.6802985017528799
filename: 3_hidden Epoch 144 loss:0.06826628234815388 ael:0.0004278734208478709 cl:0.6783840764082338
filename: 3_hidden Epoch 145 loss:0.06814424629622548 ael:0.00042500761333683724 cl:0.6771923757296088
filename: 3_hidden Epoch 146 loss:0.06734701791549205 ael:0.00041899768988324894 cl:0.6692801899553708
filename: 3_hidden Epoch 147 loss:0.06747330023702271 ael:0.0004151915778764071 cl:0.6705810745899179
filename: 3_hidden Epoch 148 loss:0.06732954983650113 ael:0.00041114900674215786 cl:0.6691839969819523
filename: 3_hidden Epoch 149 loss:0.06650711334335657 ael:0.0004075114098792298 cl:0.660996008712143
filename: 3_hidden Epoch 150 loss:0.06645504344158147 ael:0.00040447274427475734 cl:0.6605056957841534
filename: 3_hidden Epoch 151 loss:0.06616600243759489 ael:0.00040088973695829385 cl:0.657651115720871
filename: 3_hidden Epoch 152 loss:0.06583725532985744 ael:0.0003972733376840696 cl:0.6543998091847976
filename: 3_hidden Epoch 153 loss:0.06572656952177548 ael:0.0003955794690817794 cl:0.6533098887950224
filename: 3_hidden Epoch 154 loss:0.06577485105373819 ael:0.0003922003640574908 cl:0.6538264971742614
filename: 3_hidden Epoch 155 loss:0.0656254804447285 ael:0.00039053984934958125 cl:0.6523493935769735
filename: 3_hidden Epoch 156 loss:0.06484414840268726 ael:0.00038676270343507903 cl:0.6445738449734268
filename: 3_hidden Epoch 157 loss:0.06472459910380345 ael:0.00038356205123084113 cl:0.6434103576110737
filename: 3_hidden Epoch 158 loss:0.06440114185766034 ael:0.00038151618359446346 cl:0.6401962455718305
filename: 3_hidden Epoch 159 loss:0.06434057194519927 ael:0.00037997821456271606 cl:0.639605927271475
filename: 3_hidden Epoch 160 loss:0.06408268387216773 ael:0.00037673525327347896 cl:0.6370594748016732
filename: 3_hidden Epoch 161 loss:0.06386111729023061 ael:0.00037578496461613636 cl:0.6348533128978384
filename: 3_hidden Epoch 162 loss:0.06386360826784995 ael:0.00037198696631827484 cl:0.6349162029910959
filename: 3_hidden Epoch 163 loss:0.06348498685831729 ael:0.0003701156686000462 cl:0.6311487009879155
filename: 3_hidden Epoch 164 loss:0.06348988852690327 ael:0.0003689158970428531 cl:0.6312097141289149
filename: 3_hidden Epoch 165 loss:0.06289039345487749 ael:0.00036652186752216757 cl:0.625238705269633
filename: 3_hidden Epoch 166 loss:0.06279464579645076 ael:0.00036467831087714955 cl:0.6242996645135354
filename: 3_hidden Epoch 167 loss:0.06246877451429098 ael:0.0003614594101797294 cl:0.6210731403179859
filename: 3_hidden Epoch 168 loss:0.06262279206646462 ael:0.0003598262327537239 cl:0.6226296468703053
filename: 3_hidden Epoch 169 loss:0.06231125214887232 ael:0.0003571973242389569 cl:0.6195405377290576
filename: 3_hidden Epoch 170 loss:0.061992512653281394 ael:0.00035458149236345315 cl:0.6163793010800737
filename: 3_hidden Epoch 171 loss:0.06133825691849936 ael:0.0003521354700007873 cl:0.6098612041540022
filename: 3_hidden Epoch 172 loss:0.06178085377064939 ael:0.000350976375883435 cl:0.6142987626990818
filename: 3_hidden Epoch 173 loss:0.060891668600969354 ael:0.0003469356558982409 cl:0.6054473195078565
filename: 3_hidden Epoch 174 loss:0.060966081228595335 ael:0.0003433865628405145 cl:0.6062269359079283
filename: 3_hidden Epoch 175 loss:0.06071772196651822 ael:0.0003422960599007527 cl:0.6037542496384403
filename: 3_hidden Epoch 176 loss:0.06053410558853582 ael:0.00033637961719196083 cl:0.6019772477572612
filename: 3_hidden Epoch 177 loss:0.0604802212455386 ael:0.0003353656717128989 cl:0.6014485446170724
filename: 3_hidden Epoch 178 loss:0.060894431278513544 ael:0.0003321532145341698 cl:0.6056227687147041
filename: 3_hidden Epoch 179 loss:0.059822798072424584 ael:0.00032898313530949834 cl:0.5949381385159536
filename: 3_hidden Epoch 180 loss:0.06010309317787153 ael:0.0003272784819479396 cl:0.5977581377292547
filename: 3_hidden Epoch 181 loss:0.059424307415428555 ael:0.00032544210446514704 cl:0.5909886422959383
filename: 3_hidden Epoch 182 loss:0.05992694813597159 ael:0.00032441691264570457 cl:0.5960253018357228
filename: 3_hidden Epoch 183 loss:0.05992573994718926 ael:0.0003208346108101076 cl:0.5960490425686701
filename: 3_hidden Epoch 184 loss:0.0590204928785091 ael:0.00031707669068661105 cl:0.5870341508957481
filename: 3_hidden Epoch 185 loss:0.05926408013627494 ael:0.0003168003616330095 cl:0.5894727881687296
filename: 3_hidden Epoch 186 loss:0.05894064350632142 ael:0.00031393820729368026 cl:0.5862670434762965
filename: 3_hidden Epoch 187 loss:0.05893915646691587 ael:0.0003133379707959751 cl:0.5862581748468633
filename: 3_hidden Epoch 188 loss:0.05870449436690366 ael:0.0003114855864863539 cl:0.5839300781752211
filename: 3_hidden Epoch 189 loss:0.058835245172459666 ael:0.000311305778631268 cl:0.5852393821631678
filename: 3_hidden Epoch 190 loss:0.058419407842691715 ael:0.0003082825750249688 cl:0.5811112420636032
filename: 3_hidden Epoch 191 loss:0.058524955308377945 ael:0.0003080581543771474 cl:0.5821689602942031
filename: 3_hidden Epoch 192 loss:0.058203750864166695 ael:0.00030490439993074157 cl:0.5789884552079172
filename: 3_hidden Epoch 193 loss:0.05798980154658938 ael:0.00031006668112561225 cl:0.576797339374603
filename: 3_hidden Epoch 194 loss:0.057997011689270336 ael:0.0003021155835717012 cl:0.5769489517667548
filename: 3_hidden Epoch 195 loss:0.05785417984244171 ael:0.00030615214316656277 cl:0.5754802659058391
filename: 3_hidden Epoch 196 loss:0.057805865523354746 ael:0.00030015815647397437 cl:0.5750570653402642
filename: 3_hidden Epoch 197 loss:0.05776645370468535 ael:0.0003053461775798745 cl:0.5746110665993851

C:\Users\linco\AppData\Local\Temp\ipykernel_50728\310156585.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
C:\Users\linco\AppData\Local\Temp\ipykernel_50728\310156585.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                 0         1          2         3         4  Label
0         1.381111 -0.904858  -1.171011 -1.612018  0.651351      1
1        -3.407089 -5.917305   3.381634 -6.149061  5.357071      0
2        10.468386 -6.014584 -11.014531 -7.496965  2.258245      2
3         1.521572 -1.108210  -1.401647 -1.739671  0.672899      1
4        -3.604979  4.214799   4.254261  4.002713 -2.006421      4
...            ...       ...        ...       ...       ...    ...
1836045  -3.379209 -5.923593   3.353206 -6.164467  5.356504      0
1836046  10.467943 -6.014342 -11.014071 -7.496677  2.258157      2
1836047  10.467542 -6.014124 -11.013655 -7.496415  2.258078      2
1836048  -3.422205 -5.913842   3.397049 -6.140644  5.357337      0
1836049  10.434408 -5.996146 -10.979269 -7.474834  2.251543      2

[1836050 rows x 6 columns]

Davies-Bouldin Score: 1.1542411965653567

                0         1          2         3         4  Label
0       -3.358305 -5.821808   3.346322 -6.102762  5.276162      0
1       10.470082 -6.015008 -11.016241 -7.497568  2.258201      2
2        1.328030 -0.915614  -1.150168 -1.623365  0.638835      1
3        7.417990 -4.216784  -7.726343 -5.457052  1.617491      3
4        1.387722 -0.910399  -1.194920 -1.594494  0.625518      1
...           ...       ...        ...       ...       ...    ...
519951   1.390256 -0.942207  -1.213139 -1.640775  0.626021      1
519952  -3.805872  3.732497   4.417546  3.497502 -1.608262      4
519953  -3.386408 -5.922041   3.360544 -6.160568  5.356705      0
519954   1.364722 -0.913072  -1.148851 -1.629834  0.683197      1
519955   5.705399 -3.895726  -5.933657 -4.950553  1.800401      3

[519956 rows x 6 columns]

                0         1          2         3         4  Label
0       -3.404213 -5.917966   3.378702 -6.150663  5.357021      0
1       -3.366796 -5.821136   3.356266 -6.100638  5.276921      0
2        1.512125 -0.949436  -1.348211 -1.663567  0.610290      1
3        1.567043 -1.164921  -1.423951 -1.870731  0.746551      1
4       -3.407255 -5.977012   3.382193 -6.228620  5.371823      0
...           ...       ...        ...       ...       ...    ...
649942   1.360048 -0.913611  -1.164905 -1.596485  0.632818      1
649943  -3.391723 -5.954345   3.369981 -6.212353  5.354677      0
649944  -3.399747 -5.998897   3.372597 -6.254053  5.388623      0
649945   6.580135 -5.293496  -6.973603 -6.491339  2.671436      3
649946  10.430461 -6.030563 -10.971617 -7.558788  2.275868      2

[649947 rows x 6 columns]

4_hidden
cuda
[0.0, 1.0, 2.0, 3.0, 5.0]
pick completo
82 5
filename: 4_hidden Epoch 1 loss:3.407243408976618 ael:0.014690038424070708 cl:33.92553317035258
filename: 4_hidden Epoch 2 loss:1.201011216527859 ael:0.010638837441148465 cl:11.903723573041187
filename: 4_hidden Epoch 3 loss:0.9412700255711873 ael:0.008600542693199055 cl:9.326694669092875
filename: 4_hidden Epoch 4 loss:0.8238240038254644 ael:0.0057325295675369975 cl:8.180914599113619
filename: 4_hidden Epoch 5 loss:0.6094678162201214 ael:0.005396889757324769 cl:6.040709168836977
filename: 4_hidden Epoch 6 loss:0.47533162663340084 ael:0.005255372809779085 cl:4.700762460975029
filename: 4_hidden Epoch 7 loss:0.41006583016411013 ael:0.004574740288764058 cl:4.054910824559478
filename: 4_hidden Epoch 8 loss:0.3717607992622051 ael:0.003999867943943794 cl:3.6776092507578584
filename: 4_hidden Epoch 9 loss:0.3432438682387715 ael:0.0036497645565860388 cl:3.3959409813971013
filename: 4_hidden Epoch 10 loss:0.32049317381240416 ael:0.003434239634829253 cl:3.1705892883653424
filename: 4_hidden Epoch 11 loss:0.30390845197736815 ael:0.0032316737117650497 cl:3.0067677309155947
filename: 4_hidden Epoch 12 loss:0.2913676485901902 ael:0.0030512209823317375 cl:2.8831642226973364
filename: 4_hidden Epoch 13 loss:0.2814169826828114 ael:0.0029246505590560423 cl:2.784923274250005
filename: 4_hidden Epoch 14 loss:0.27280561295457373 ael:0.0028149270175424545 cl:2.6999068123769825
filename: 4_hidden Epoch 15 loss:0.26542887475728666 ael:0.0027368501906488065 cl:2.6269202017108437
filename: 4_hidden Epoch 16 loss:0.25880168635252354 ael:0.002674673293282337 cl:2.561270086967993
filename: 4_hidden Epoch 17 loss:0.2527070427401426 ael:0.0025975250776331775 cl:2.5010951348081454
filename: 4_hidden Epoch 18 loss:0.24555795000571953 ael:0.002519479117075964 cl:2.430384664802577
filename: 4_hidden Epoch 19 loss:0.23911994207504628 ael:0.0024512493745053082 cl:2.366686885294161
filename: 4_hidden Epoch 20 loss:0.23327692534055627 ael:0.002384884801144019 cl:2.308920365089347
filename: 4_hidden Epoch 21 loss:0.22745182022311589 ael:0.002340884754866583 cl:2.2511093164503815
filename: 4_hidden Epoch 22 loss:0.22193364916361777 ael:0.002310416959138152 cl:2.1962322833567014
filename: 4_hidden Epoch 23 loss:0.2163894149586659 ael:0.0022829817793697782 cl:2.1410642971715785
filename: 4_hidden Epoch 24 loss:0.21067701614739603 ael:0.0022614163608640917 cl:2.0841559629610837
filename: 4_hidden Epoch 25 loss:0.20483865234774618 ael:0.002246884439158154 cl:2.0259176449334895
filename: 4_hidden Epoch 26 loss:0.19837519952904198 ael:0.0022492688339311685 cl:1.9612592731249316
filename: 4_hidden Epoch 27 loss:0.19142413981630896 ael:0.0022579729576832673 cl:1.891661635463537
filename: 4_hidden Epoch 28 loss:0.18419960887647674 ael:0.002255605040030119 cl:1.8194400088104963
filename: 4_hidden Epoch 29 loss:0.17740258728826416 ael:0.002255029124383753 cl:1.7514755512619147
filename: 4_hidden Epoch 30 loss:0.171233942205848 ael:0.002247705041492476 cl:1.6898623407450122
filename: 4_hidden Epoch 31 loss:0.16535188158604538 ael:0.002228467171011284 cl:1.6312341156115255
filename: 4_hidden Epoch 32 loss:0.15972134303125615 ael:0.002189527183749767 cl:1.5753181295838916
filename: 4_hidden Epoch 33 loss:0.15438537693880347 ael:0.002147981243970956 cl:1.5223739285740936
filename: 4_hidden Epoch 34 loss:0.1499784304404709 ael:0.0021115374094058787 cl:1.4786689027681363
filename: 4_hidden Epoch 35 loss:0.1459439034972154 ael:0.002061841499397227 cl:1.4388205980643247
filename: 4_hidden Epoch 36 loss:0.1424408885525909 ael:0.0020303860510663004 cl:1.4041050011852654
filename: 4_hidden Epoch 37 loss:0.13925156360303584 ael:0.0019780748328646486 cl:1.37273486411845
filename: 4_hidden Epoch 38 loss:0.13623223207569235 ael:0.0019193291074662958 cl:1.343129005058896
filename: 4_hidden Epoch 39 loss:0.13352030966978887 ael:0.0018641644969391517 cl:1.3165614301497155
filename: 4_hidden Epoch 40 loss:0.13095049056276056 ael:0.001805323941284959 cl:1.2914516444470074
filename: 4_hidden Epoch 41 loss:0.12813535383104394 ael:0.0017294394934811352 cl:1.26405912269304
filename: 4_hidden Epoch 42 loss:0.12537997850642996 ael:0.0016240346043429736 cl:1.2375594177910512
filename: 4_hidden Epoch 43 loss:0.12297447450036704 ael:0.0015165180847043732 cl:1.2145795438775489
filename: 4_hidden Epoch 44 loss:0.12078496074346717 ael:0.0014182429598404319 cl:1.1936671596266801
filename: 4_hidden Epoch 45 loss:0.11875652603443093 ael:0.0013397968078362687 cl:1.174167272605394
filename: 4_hidden Epoch 46 loss:0.11665644739149955 ael:0.001288354864036702 cl:1.1536809061019204
filename: 4_hidden Epoch 47 loss:0.11464929116459993 ael:0.0012544388362953085 cl:1.1339485032074204
filename: 4_hidden Epoch 48 loss:0.11179376947724948 ael:0.0012401200061118514 cl:1.10553647637689
filename: 4_hidden Epoch 49 loss:0.10865543024682323 ael:0.0012085956574905306 cl:1.0744683282779135
filename: 4_hidden Epoch 50 loss:0.10631122097458474 ael:0.0011630283196377548 cl:1.0514819072808332
filename: 4_hidden Epoch 51 loss:0.10438812613115217 ael:0.0011282136488621666 cl:1.0325991066079712
filename: 4_hidden Epoch 52 loss:0.10277039109479118 ael:0.001096817040966771 cl:1.0167357222070257
filename: 4_hidden Epoch 53 loss:0.10116000578119125 ael:0.0010658884546204184 cl:1.000941157139908
filename: 4_hidden Epoch 54 loss:0.09986106393539551 ael:0.0010353097485538004 cl:0.9882575248497539
filename: 4_hidden Epoch 55 loss:0.09842088486943971 ael:0.0010085843766784338 cl:0.9741229882808189
filename: 4_hidden Epoch 56 loss:0.09729296048341493 ael:0.0009841672664928638 cl:0.9630879150107805
filename: 4_hidden Epoch 57 loss:0.09614210362884237 ael:0.0009604222976380152 cl:0.9518167958970656
filename: 4_hidden Epoch 58 loss:0.09507993379891844 ael:0.0009280750248801119 cl:0.9415185711483562
filename: 4_hidden Epoch 59 loss:0.09404791856936195 ael:0.0009002785991538598 cl:0.9314763824466752
filename: 4_hidden Epoch 60 loss:0.09315667460457637 ael:0.000879873607806326 cl:0.922767993578544
filename: 4_hidden Epoch 61 loss:0.09229586108156584 ael:0.0008632045024132429 cl:0.9143265502012049
filename: 4_hidden Epoch 62 loss:0.0914252216124583 ael:0.0008465812377054773 cl:0.9057863889033334
filename: 4_hidden Epoch 63 loss:0.09061599958778514 ael:0.0008309550801582393 cl:0.8978504269812432
filename: 4_hidden Epoch 64 loss:0.08983301723202472 ael:0.0008151277265506426 cl:0.8901788786073767
filename: 4_hidden Epoch 65 loss:0.08903500734050425 ael:0.0008028525101082518 cl:0.8823215327925689
filename: 4_hidden Epoch 66 loss:0.0882557774832354 ael:0.0007882668249552262 cl:0.8746750913670993
filename: 4_hidden Epoch 67 loss:0.0876467663875194 ael:0.0007748175457348688 cl:0.8687194707503042
filename: 4_hidden Epoch 68 loss:0.08696897348889254 ael:0.000761336619543432 cl:0.8620763537935239
filename: 4_hidden Epoch 69 loss:0.08626305808497947 ael:0.0007468642151864891 cl:0.8551619242439386
filename: 4_hidden Epoch 70 loss:0.08560945711974632 ael:0.000733087048763736 cl:0.8487636864446757
filename: 4_hidden Epoch 71 loss:0.08501180035543505 ael:0.0007183727019311868 cl:0.8429342611075734
filename: 4_hidden Epoch 72 loss:0.084397897240423 ael:0.0007038864745666096 cl:0.8369400934852891
filename: 4_hidden Epoch 73 loss:0.08376541419857145 ael:0.0006902622401556591 cl:0.8307515041367245
filename: 4_hidden Epoch 74 loss:0.08325425803123417 ael:0.0006790177385907497 cl:0.825752388654772
filename: 4_hidden Epoch 75 loss:0.08269505197064154 ael:0.0006673171618804411 cl:0.8202773352584697
filename: 4_hidden Epoch 76 loss:0.08210207468926826 ael:0.0006565049762681112 cl:0.814455683143274
filename: 4_hidden Epoch 77 loss:0.08155899085029054 ael:0.0006467217204708344 cl:0.8091226768035155
filename: 4_hidden Epoch 78 loss:0.08099131925225098 ael:0.0006374403268958827 cl:0.8035387757999695
filename: 4_hidden Epoch 79 loss:0.08034242069180275 ael:0.0006292110881301563 cl:0.7971320825268221
filename: 4_hidden Epoch 80 loss:0.07979355145864159 ael:0.0006208025320202449 cl:0.7917274750980289
filename: 4_hidden Epoch 81 loss:0.07924133378776059 ael:0.0006112802926774291 cl:0.7863005216506168
filename: 4_hidden Epoch 82 loss:0.07872969933361941 ael:0.0006026676199947234 cl:0.7812703016456644
filename: 4_hidden Epoch 83 loss:0.07820576226889242 ael:0.000594324299920471 cl:0.7761143669928455
filename: 4_hidden Epoch 84 loss:0.07764475389324661 ael:0.0005849944947590026 cl:0.7705975806886046
filename: 4_hidden Epoch 85 loss:0.07722136937207498 ael:0.0005774733583821806 cl:0.7664389465562245
filename: 4_hidden Epoch 86 loss:0.07668642397019786 ael:0.0005712472077346924 cl:0.7611517546892005
filename: 4_hidden Epoch 87 loss:0.0761180212595544 ael:0.0005627173617373468 cl:0.755553026113272
filename: 4_hidden Epoch 88 loss:0.0755935127224758 ael:0.0005569201545801149 cl:0.7503659112270866
filename: 4_hidden Epoch 89 loss:0.07511307539797907 ael:0.0005515998412569666 cl:0.7456147421086043
filename: 4_hidden Epoch 90 loss:0.07448074225281012 ael:0.0005434914049582478 cl:0.7393724963853233
filename: 4_hidden Epoch 91 loss:0.07392104384457936 ael:0.0005397836703259759 cl:0.7338125899896609
filename: 4_hidden Epoch 92 loss:0.07344448736136058 ael:0.0005360641736182473 cl:0.729084219400458
filename: 4_hidden Epoch 93 loss:0.07289056602523596 ael:0.0005347566288633852 cl:0.7235580820846654
filename: 4_hidden Epoch 94 loss:0.072305914980338 ael:0.0005327373629823319 cl:0.7177317635753215
filename: 4_hidden Epoch 95 loss:0.07177733932037345 ael:0.0005262698384169011 cl:0.7125106814298553
filename: 4_hidden Epoch 96 loss:0.07117763694813135 ael:0.0005222115712766643 cl:0.70655424242158
filename: 4_hidden Epoch 97 loss:0.07064699249369734 ael:0.0005174297896196862 cl:0.7012956145381638
filename: 4_hidden Epoch 98 loss:0.07014775568463522 ael:0.000513218012196923 cl:0.6963453654617111
filename: 4_hidden Epoch 99 loss:0.06961166852514553 ael:0.0005107551492315776 cl:0.6910091212745781
filename: 4_hidden Epoch 100 loss:0.06904657718131015 ael:0.0005073546819027837 cl:0.6853922131975331
filename: 4_hidden Epoch 101 loss:0.06851523691303174 ael:0.0005026373818088462 cl:0.6801259842699999
filename: 4_hidden Epoch 102 loss:0.06810743816400527 ael:0.0004986076147379429 cl:0.6760882936307454
filename: 4_hidden Epoch 103 loss:0.06748679673711439 ael:0.0004948782325194716 cl:0.6699191745234887
filename: 4_hidden Epoch 104 loss:0.06696375753609879 ael:0.0004924599243685862 cl:0.664712964452793
filename: 4_hidden Epoch 105 loss:0.06640926132798095 ael:0.0004891761647942369 cl:0.6592008398008733
filename: 4_hidden Epoch 106 loss:0.06589999480120204 ael:0.00048800021006305315 cl:0.6541199339063544
filename: 4_hidden Epoch 107 loss:0.06543837774924521 ael:0.00048505330484834285 cl:0.6495332337805295
filename: 4_hidden Epoch 108 loss:0.06500180101854156 ael:0.00048337774458856605 cl:0.645184222446923
filename: 4_hidden Epoch 109 loss:0.06443137894793038 ael:0.0004793299964681587 cl:0.6395204785653212
filename: 4_hidden Epoch 110 loss:0.06393999381169335 ael:0.00047781506368535975 cl:0.6346217759888665
filename: 4_hidden Epoch 111 loss:0.0635597959190969 ael:0.00047564537915766904 cl:0.6308414941163439
filename: 4_hidden Epoch 112 loss:0.06297993065020152 ael:0.0004721491776182732 cl:0.6250778038844004
filename: 4_hidden Epoch 113 loss:0.06253736363208567 ael:0.00046997721371471547 cl:0.6206738539281403
filename: 4_hidden Epoch 114 loss:0.06202653110399339 ael:0.00046857218254155224 cl:0.6155795786786176
filename: 4_hidden Epoch 115 loss:0.061535533974211104 ael:0.00046450424837746613 cl:0.6107102867985061
filename: 4_hidden Epoch 116 loss:0.06106263942332805 ael:0.00046176725682974055 cl:0.6060087106448275
filename: 4_hidden Epoch 117 loss:0.06065893656990205 ael:0.00045871287156191786 cl:0.6020022280202543
filename: 4_hidden Epoch 118 loss:0.06027295658007948 ael:0.0004576672809507997 cl:0.5981528836856728
filename: 4_hidden Epoch 119 loss:0.05987468216990532 ael:0.0004567717313356434 cl:0.5941790927105989
filename: 4_hidden Epoch 120 loss:0.05946656439036091 ael:0.0004548325886926017 cl:0.5901173076236699
filename: 4_hidden Epoch 121 loss:0.058994697024178526 ael:0.0004545034555752552 cl:0.5854019254747672
filename: 4_hidden Epoch 122 loss:0.05857078275340389 ael:0.00045223193108899127 cl:0.5811854974933562
filename: 4_hidden Epoch 123 loss:0.058209025427226516 ael:0.00045250248793618156 cl:0.5775652201843728
filename: 4_hidden Epoch 124 loss:0.05778159655230912 ael:0.0004498789095303783 cl:0.5733171681683716
filename: 4_hidden Epoch 125 loss:0.05739700123064431 ael:0.0004497046631692711 cl:0.5694729557052235
filename: 4_hidden Epoch 126 loss:0.057002627678773544 ael:0.00044629036170975954 cl:0.5655633636774161
filename: 4_hidden Epoch 127 loss:0.05675290137562051 ael:0.0004436115091009877 cl:0.5630928894839226
filename: 4_hidden Epoch 128 loss:0.05632025513461164 ael:0.0004386388188453929 cl:0.5588161547998829
filename: 4_hidden Epoch 129 loss:0.05580647571588013 ael:0.0004348033852773114 cl:0.5537167133338619
filename: 4_hidden Epoch 130 loss:0.055404291610018565 ael:0.00043286485444705974 cl:0.5497142590753302
filename: 4_hidden Epoch 131 loss:0.055100348351747 ael:0.0004306425327158944 cl:0.5466970489957393
filename: 4_hidden Epoch 132 loss:0.05474039881720174 ael:0.0004270290905823705 cl:0.543133687716626
filename: 4_hidden Epoch 133 loss:0.05435734435465996 ael:0.00042188230092626557 cl:0.5393546115069093
filename: 4_hidden Epoch 134 loss:0.05404125325301318 ael:0.00042167908200829485 cl:0.5361957329799208
filename: 4_hidden Epoch 135 loss:0.054058794083398004 ael:0.00042197579308538653 cl:0.5363681741481127
filename: 4_hidden Epoch 136 loss:0.05342303943203187 ael:0.00041451243379774823 cl:0.5300852603265229
filename: 4_hidden Epoch 137 loss:0.05331165604884064 ael:0.00041717632900148643 cl:0.5289447872654388
filename: 4_hidden Epoch 138 loss:0.052834030408940094 ael:0.00041354411404501953 cl:0.5242048541926019
filename: 4_hidden Epoch 139 loss:0.05250230525782415 ael:0.0004097716109472102 cl:0.5209253268695956
filename: 4_hidden Epoch 140 loss:0.052265056435712554 ael:0.00040649704286132974 cl:0.5185855860310367
filename: 4_hidden Epoch 141 loss:0.05201051174329943 ael:0.00040329091834779776 cl:0.5160721981010618
filename: 4_hidden Epoch 142 loss:0.05189895679477939 ael:0.0004007379109807835 cl:0.5149821800359509
filename: 4_hidden Epoch 143 loss:0.05163250995005573 ael:0.00039727483346132 cl:0.5123523423345143
filename: 4_hidden Epoch 144 loss:0.05118146197701957 ael:0.0003933691443423282 cl:0.5078809195282328
filename: 4_hidden Epoch 145 loss:0.05096437227415793 ael:0.0003921210277750497 cl:0.5057225038044848
filename: 4_hidden Epoch 146 loss:0.0505463955027784 ael:0.000388505986662941 cl:0.501578885327909
filename: 4_hidden Epoch 147 loss:0.05054808816616141 ael:0.0003869695427598791 cl:0.5016111775870747
filename: 4_hidden Epoch 148 loss:0.05032432404454853 ael:0.00038429463473346596 cl:0.4994002853549122
filename: 4_hidden Epoch 149 loss:0.04991240696962697 ael:0.00038044284858713214 cl:0.49531963249610667
filename: 4_hidden Epoch 150 loss:0.04984611629171601 ael:0.0003801723870952449 cl:0.49465943054571326
filename: 4_hidden Epoch 151 loss:0.04960249968617149 ael:0.00037763065245478855 cl:0.4922486827742716
filename: 4_hidden Epoch 152 loss:0.0493900760952333 ael:0.0003760525237245098 cl:0.4901402271771238
filename: 4_hidden Epoch 153 loss:0.049287044713600424 ael:0.0003732833366809814 cl:0.48913760576372045
filename: 4_hidden Epoch 154 loss:0.049060293693439824 ael:0.0003709976115422989 cl:0.48689295293992024
filename: 4_hidden Epoch 155 loss:0.04890525879717951 ael:0.0003690163563282132 cl:0.48536241550687276
filename: 4_hidden Epoch 156 loss:0.048974889525754045 ael:0.0003688380332038689 cl:0.4860605069761656
filename: 4_hidden Epoch 157 loss:0.0487182191209855 ael:0.00036568001754988517 cl:0.48352538258008226
filename: 4_hidden Epoch 158 loss:0.04863820561841281 ael:0.0003636523651919207 cl:0.48274552437719387
filename: 4_hidden Epoch 159 loss:0.04835671876436514 ael:0.00036163307352196715 cl:0.4799508480704547
filename: 4_hidden Epoch 160 loss:0.04823944302911741 ael:0.0003600134368419211 cl:0.4787942870013547
filename: 4_hidden Epoch 161 loss:0.04801309590998348 ael:0.000357321289204741 cl:0.4765577373179065
filename: 4_hidden Epoch 162 loss:0.04817570911534382 ael:0.00035677834542143926 cl:0.4781893005974179
filename: 4_hidden Epoch 163 loss:0.047970457105456214 ael:0.0003522765144993904 cl:0.4761817977003321
filename: 4_hidden Epoch 164 loss:0.047738579764029614 ael:0.0003520230531538384 cl:0.4738655584036057
filename: 4_hidden Epoch 165 loss:0.047716435835936814 ael:0.0003481627769154583 cl:0.4736827234965064
filename: 4_hidden Epoch 166 loss:0.04737340190709291 ael:0.0003474702449265978 cl:0.4702593083620353
filename: 4_hidden Epoch 167 loss:0.04750183591557548 ael:0.0003468157976446925 cl:0.4715501929337961
filename: 4_hidden Epoch 168 loss:0.04760295376351276 ael:0.00034386079863116633 cl:0.47259092082982124
filename: 4_hidden Epoch 169 loss:0.04716373177964175 ael:0.0003405508308827107 cl:0.46823180186915414
filename: 4_hidden Epoch 170 loss:0.047215755816735074 ael:0.00034046605870251165 cl:0.46875289014456406
filename: 4_hidden Epoch 171 loss:0.047088520383957506 ael:0.00033803898596450533 cl:0.46750480503437086
filename: 4_hidden Epoch 172 loss:0.0468523483275965 ael:0.00033342730798384656 cl:0.46518920224999527
filename: 4_hidden Epoch 173 loss:0.046990841090636434 ael:0.0003356334997162565 cl:0.46655206777929614
filename: 4_hidden Epoch 174 loss:0.0465938794150114 ael:0.00033236452598359146 cl:0.4626151417033915
filename: 4_hidden Epoch 175 loss:0.046628670940142974 ael:0.0003302187344222581 cl:0.4629845141957284
filename: 4_hidden Epoch 176 loss:0.04644681562075087 ael:0.0003285598985470772 cl:0.4611825479101515
filename: 4_hidden Epoch 177 loss:0.04649005280185476 ael:0.00032739190639806696 cl:0.4616266008541893
filename: 4_hidden Epoch 178 loss:0.04630033872379354 ael:0.0003247542406974974 cl:0.45975583665595765
filename: 4_hidden Epoch 179 loss:0.04598911853290984 ael:0.00032360525111691066 cl:0.4566551241782392
filename: 4_hidden Epoch 180 loss:0.04616806846710271 ael:0.0003232777032647854 cl:0.4584479007241536
filename: 4_hidden Epoch 181 loss:0.045897875656907956 ael:0.0003230784376072993 cl:0.4557479638390132
filename: 4_hidden Epoch 182 loss:0.046017125182924605 ael:0.0003214685615959173 cl:0.45695655899079624
filename: 4_hidden Epoch 183 loss:0.045171723186947135 ael:0.0003175693775600862 cl:0.44854153002814645
filename: 4_hidden Epoch 184 loss:0.04606928961695889 ael:0.0003161178591861308 cl:0.4575317105471927
filename: 4_hidden Epoch 185 loss:0.045290700912691766 ael:0.00031508246945187717 cl:0.449756176670694
filename: 4_hidden Epoch 186 loss:0.04573050234611328 ael:0.00031438012525582856 cl:0.4541612140562853
filename: 4_hidden Epoch 187 loss:0.04507333038836044 ael:0.00031263084295505845 cl:0.44760698846788943
filename: 4_hidden Epoch 188 loss:0.04495096172736493 ael:0.00031059309578817726 cl:0.4464036786016303
filename: 4_hidden Epoch 189 loss:0.04482658987791955 ael:0.00030850035528796595 cl:0.4451808879581782
filename: 4_hidden Epoch 190 loss:0.044775784166225616 ael:0.0003075475150928393 cl:0.44468235783982774
filename: 4_hidden Epoch 191 loss:0.04490095402344096 ael:0.00030702126941820556 cl:0.44593932007749876
filename: 4_hidden Epoch 192 loss:0.04473505917912683 ael:0.00030623426601273735 cl:0.44428824138866585
filename: 4_hidden Epoch 193 loss:0.04442951359802432 ael:0.00030421002285429947 cl:0.44125302925293663
filename: 4_hidden Epoch 194 loss:0.04447820301396413 ael:0.0003019338767602757 cl:0.44176268407046876
filename: 4_hidden Epoch 195 loss:0.044374938036080114 ael:0.0003013210152897213 cl:0.4407361625468763
filename: 4_hidden Epoch 196 loss:0.044332810505274454 ael:0.00029930354410363926 cl:0.4403350624639174

C:\Users\linco\AppData\Local\Temp\ipykernel_50728\310156585.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
C:\Users\linco\AppData\Local\Temp\ipykernel_50728\310156585.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                 0          1         2         3         4  Label
0       -10.691791  12.928113 -6.732114  5.491525 -6.881273      1
1        -9.553224  22.842981 -3.203406  4.969112 -8.293387      0
2        -4.417042   2.125370 -3.586645  2.343436 -2.075151      2
3       -10.491217  12.100345 -6.688715  5.366488 -6.586025      1
4        -4.416527   2.126218 -3.585946  2.343184 -2.075090      2
...            ...        ...       ...       ...       ...    ...
1896688  -9.636782  23.032867 -3.233220  5.011168 -8.365960      0
1896689  -4.417189   2.125085 -3.586854  2.343508 -2.075160      2
1896690  -4.417322   2.124831 -3.587044  2.343573 -2.075170      2
1896691  -9.507789  22.739727 -3.187193  4.946244 -8.253923      0
1896692  -4.428161   2.102763 -3.602814  2.348860 -2.075646      2

[1896693 rows x 6 columns]

Davies-Bouldin Score: 1.0989943456355262

                0          1         2         3         4  Label
0       -9.592031  22.903324 -3.224640  5.006342 -8.275304      0
1       -4.416471   2.126111 -3.585925  2.343155 -2.075044      2
2      -10.644738  12.938168 -6.711772  5.524076 -6.861108      1
3       -1.140807  -7.648148 -3.019267  0.713925  1.250194      3
4      -10.659548  12.951090 -6.703245  5.482084 -6.878301      1
...           ...        ...       ...       ...       ...    ...
519951 -10.717790  12.960811 -6.733921  5.523762 -6.853002      1
519952 -11.434449  13.626473 -7.247344  5.865867 -7.231875      4
519953  -9.615361  22.984184 -3.225578  5.000388 -8.347355      0
519954 -10.702963  12.937366 -6.772709  5.502604 -6.881350      1
519955  -1.117601  -7.575580 -2.928914  0.640226  1.244148      3

[519956 rows x 6 columns]

                0          1         2         3         4  Label
0       -9.561868  22.862616 -3.206490  4.973462 -8.300894      0
1       -9.590828  22.927752 -3.216307  5.006137 -8.279896      0
2      -10.646174  12.934541 -6.692239  5.523399 -6.860724      1
3      -11.571479  13.971719 -7.264134  5.949303 -7.416762      1
4       -9.686346  22.752903 -3.373219  5.080415 -8.313513      0
...           ...        ...       ...       ...       ...    ...
649942 -10.648603  12.939505 -6.695281  5.471833 -6.866698      1
649943  -9.637798  22.786406 -3.319647  5.057475 -8.299987      0
649944  -9.641439  22.784243 -3.323341  5.059248 -8.300834      0
649945  -1.164875  -7.309097 -2.930459  0.696710  1.200200      3
649946  -4.360478   1.463742 -3.704998  2.342976 -1.897185      2

[649947 rows x 6 columns]

5_hidden
cuda
[0.0, 1.0, 2.0, 3.0, 4.0]
pick completo
82 5
filename: 5_hidden Epoch 1 loss:3.3403328681215165 ael:0.014945596489428939 cl:33.253872172225584
filename: 5_hidden Epoch 2 loss:2.3646713632307046 ael:0.007068986457977527 cl:23.576023303951786
filename: 5_hidden Epoch 3 loss:1.7744893387348883 ael:0.007575958194316593 cl:17.669133507753465
filename: 5_hidden Epoch 4 loss:1.6182885131537768 ael:0.005998709098862852 cl:16.12289775574166
filename: 5_hidden Epoch 5 loss:1.2911820837440073 ael:0.005429362699711363 cl:12.857526972046161
filename: 5_hidden Epoch 6 loss:0.7649312120596803 ael:0.004574311056801639 cl:7.603568876335505
filename: 5_hidden Epoch 7 loss:0.7029101551019282 ael:0.004035745813935016 cl:6.988743972919188
filename: 5_hidden Epoch 8 loss:0.6614400115889437 ael:0.0038190822932453747 cl:6.576209177001247
filename: 5_hidden Epoch 9 loss:0.6237309889245186 ael:0.003623503755036593 cl:6.2010747458417095
filename: 5_hidden Epoch 10 loss:0.5875692750134238 ael:0.003361133086357077 cl:5.842081315701727
filename: 5_hidden Epoch 11 loss:0.5361786498731724 ael:0.003314806798696316 cl:5.328638345164539
filename: 5_hidden Epoch 12 loss:0.46132115259627177 ael:0.0032925115224349544 cl:4.5802863284263164
filename: 5_hidden Epoch 13 loss:0.37201536411226 ael:0.002911806903906297 cl:3.6910355089921074
filename: 5_hidden Epoch 14 loss:0.29576674195264196 ael:0.0026992870082770135 cl:2.9306744992116704
filename: 5_hidden Epoch 15 loss:0.2489146123975442 ael:0.002609135332500818 cl:2.4630547279151775
filename: 5_hidden Epoch 16 loss:0.22009320466140408 ael:0.002600727299735471 cl:2.174924734923007
filename: 5_hidden Epoch 17 loss:0.1994651715114808 ael:0.0024770163875180956 cl:1.969881518259241
filename: 5_hidden Epoch 18 loss:0.18341729616455582 ael:0.002444205720282326 cl:1.8097308731501704
filename: 5_hidden Epoch 19 loss:0.16910795776190898 ael:0.002398042080961516 cl:1.6670991286290566
filename: 5_hidden Epoch 20 loss:0.15617393687136327 ael:0.0022984829256739807 cl:1.5387545141062673
filename: 5_hidden Epoch 21 loss:0.14604896209961613 ael:0.0022272022822144998 cl:1.4382175724093167
filename: 5_hidden Epoch 22 loss:0.1376020602844307 ael:0.002158319730330433 cl:1.3544373834576295
filename: 5_hidden Epoch 23 loss:0.12973528671395246 ael:0.0021091573872818537 cl:1.2762612707248937
filename: 5_hidden Epoch 24 loss:0.12319292426558696 ael:0.0020615173097821857 cl:1.2113140496177253
filename: 5_hidden Epoch 25 loss:0.11724270027633417 ael:0.001990583510555837 cl:1.1525211463393923
filename: 5_hidden Epoch 26 loss:0.11207582433132528 ael:0.00187914249574805 cl:1.1019667971939773
filename: 5_hidden Epoch 27 loss:0.10850911988688294 ael:0.0017744628859845282 cl:1.0673465499776387
filename: 5_hidden Epoch 28 loss:0.10558075285395163 ael:0.001636308862213027 cl:1.039444418551592
filename: 5_hidden Epoch 29 loss:0.10314377949099414 ael:0.0015448135915098842 cl:1.015989642817727
filename: 5_hidden Epoch 30 loss:0.10112661473771281 ael:0.0014939509575901317 cl:0.9963266215759918
filename: 5_hidden Epoch 31 loss:0.09967154803227748 ael:0.001453724869907293 cl:0.9821782173182594
filename: 5_hidden Epoch 32 loss:0.09819017632936408 ael:0.001417790401896282 cl:0.9677238420205918
filename: 5_hidden Epoch 33 loss:0.09636002339093461 ael:0.0013774844733070754 cl:0.9498253716976698
filename: 5_hidden Epoch 34 loss:0.09555773834084816 ael:0.0013462948604242243 cl:0.9421144193877498
filename: 5_hidden Epoch 35 loss:0.09481118986330805 ael:0.00130257086864978 cl:0.9350861738679416
filename: 5_hidden Epoch 36 loss:0.09381557854441792 ael:0.001258760449719115 cl:0.9255681645890018
filename: 5_hidden Epoch 37 loss:0.09464562473018942 ael:0.0012355387968290689 cl:0.934100844382374
filename: 5_hidden Epoch 38 loss:0.09444060925429147 ael:0.0011965873154277575 cl:0.9324402020724168
filename: 5_hidden Epoch 39 loss:0.0936824260836679 ael:0.0011665624816030041 cl:0.9251586192735511
filename: 5_hidden Epoch 40 loss:0.09290403180977157 ael:0.0011333267080568003 cl:0.9177070352932551
filename: 5_hidden Epoch 41 loss:0.09203036392867887 ael:0.0011028457053861701 cl:0.9092751649845298
filename: 5_hidden Epoch 42 loss:0.09138819375013495 ael:0.0010700884042365055 cl:0.903181038116408
filename: 5_hidden Epoch 43 loss:0.09066467848950323 ael:0.0010277548810281524 cl:0.8963692206531719
filename: 5_hidden Epoch 44 loss:0.09011794559431506 ael:0.000995198938634374 cl:0.8912274526759564
filename: 5_hidden Epoch 45 loss:0.08957293210023806 ael:0.0009706632965062078 cl:0.8860226756136943
filename: 5_hidden Epoch 46 loss:0.08904176291627676 ael:0.0009521967330898223 cl:0.8808956470437703
filename: 5_hidden Epoch 47 loss:0.08851382093321108 ael:0.0009346063124315822 cl:0.8757921333389438
filename: 5_hidden Epoch 48 loss:0.08796898354737226 ael:0.0009137112307678661 cl:0.8705527072461484
filename: 5_hidden Epoch 49 loss:0.08757819938310617 ael:0.0008946944438387053 cl:0.8668350355808794
filename: 5_hidden Epoch 50 loss:0.08708573796051307 ael:0.0008762571724604128 cl:0.8620947927396134
filename: 5_hidden Epoch 51 loss:0.08663692378775129 ael:0.0008592776779020857 cl:0.8577764456975217
filename: 5_hidden Epoch 52 loss:0.08619420980892026 ael:0.0008437177374053233 cl:0.8535049062539561
filename: 5_hidden Epoch 53 loss:0.08579079499092193 ael:0.0008252332415799727 cl:0.849655602830735
filename: 5_hidden Epoch 54 loss:0.08533353420652648 ael:0.0008109181021763895 cl:0.845226145174734
filename: 5_hidden Epoch 55 loss:0.08502566310712827 ael:0.0007987489558869041 cl:0.8422691284296902
filename: 5_hidden Epoch 56 loss:0.08453569954475787 ael:0.00078496733979975 cl:0.8375073072598199
filename: 5_hidden Epoch 57 loss:0.08415487673234952 ael:0.0007711175527974 cl:0.8338375780942374
filename: 5_hidden Epoch 58 loss:0.08380380948532716 ael:0.0007585911889230248 cl:0.8304521682631392
filename: 5_hidden Epoch 59 loss:0.08348171482622029 ael:0.0007469169781971489 cl:0.82734796545156
filename: 5_hidden Epoch 60 loss:0.08307376184126115 ael:0.000734441645166817 cl:0.8233931887049296
filename: 5_hidden Epoch 61 loss:0.0827700965838339 ael:0.0007203198145515116 cl:0.8204977534626987
filename: 5_hidden Epoch 62 loss:0.08235797234423411 ael:0.0007064947518621512 cl:0.8165147622266774
filename: 5_hidden Epoch 63 loss:0.08202433380929286 ael:0.0006947461574703844 cl:0.8132958633184125
filename: 5_hidden Epoch 64 loss:0.08168350639734702 ael:0.0006820088175574459 cl:0.8100149637433929
filename: 5_hidden Epoch 65 loss:0.08138647698281412 ael:0.0006729779927337891 cl:0.8071349774799592
filename: 5_hidden Epoch 66 loss:0.08097560731496924 ael:0.0006626928677766482 cl:0.8031291304654173
filename: 5_hidden Epoch 67 loss:0.08066121345133245 ael:0.0006531686912267136 cl:0.8000804328981921
filename: 5_hidden Epoch 68 loss:0.08040856220736524 ael:0.0006445600655474868 cl:0.797640007777953
filename: 5_hidden Epoch 69 loss:0.08007982841432407 ael:0.000635576432301902 cl:0.794442507428732
filename: 5_hidden Epoch 70 loss:0.07965376317512074 ael:0.0006272265096939045 cl:0.7902653533103268
filename: 5_hidden Epoch 71 loss:0.07933475520986383 ael:0.0006205586321302403 cl:0.7871419511962882
filename: 5_hidden Epoch 72 loss:0.07917709861297834 ael:0.0006146955733369313 cl:0.785624016547261
filename: 5_hidden Epoch 73 loss:0.0788835614469936 ael:0.000607695334374964 cl:0.7827586485338932
filename: 5_hidden Epoch 74 loss:0.07855323045900856 ael:0.0006004565504414478 cl:0.7795277239689682
filename: 5_hidden Epoch 75 loss:0.07834823214998565 ael:0.0005940685714798789 cl:0.7775416231312038
filename: 5_hidden Epoch 76 loss:0.07806812174978667 ael:0.0005893040128543002 cl:0.7747881655154382
filename: 5_hidden Epoch 77 loss:0.07790199868084798 ael:0.0005833615650127276 cl:0.7731863588011254
filename: 5_hidden Epoch 78 loss:0.07754185739743003 ael:0.0005791769944238734 cl:0.7696267912289975
filename: 5_hidden Epoch 79 loss:0.07728252978972515 ael:0.0005706448860609263 cl:0.7671188358607248
filename: 5_hidden Epoch 80 loss:0.07703988718057848 ael:0.0005668064323351372 cl:0.7647307956956257
filename: 5_hidden Epoch 81 loss:0.07679233061243032 ael:0.0005596346878534624 cl:0.76232694565529
filename: 5_hidden Epoch 82 loss:0.07653047918474576 ael:0.0005554484639169831 cl:0.7597502946641785
filename: 5_hidden Epoch 83 loss:0.07628848558952799 ael:0.0005493553205897836 cl:0.7573912904026002
filename: 5_hidden Epoch 84 loss:0.07614315936786908 ael:0.0005434128163568526 cl:0.7559974534411381
filename: 5_hidden Epoch 85 loss:0.0759938095097514 ael:0.0005358653993235515 cl:0.754579427093084
filename: 5_hidden Epoch 86 loss:0.07569912940175247 ael:0.0005299404759106975 cl:0.7516918734292871
filename: 5_hidden Epoch 87 loss:0.07550232691624065 ael:0.0005233121406044666 cl:0.7497901363020414
filename: 5_hidden Epoch 88 loss:0.07523782267031164 ael:0.0005166623800033041 cl:0.7472115904010249
filename: 5_hidden Epoch 89 loss:0.07507213271170962 ael:0.0005132801194661453 cl:0.7455885142114532
filename: 5_hidden Epoch 90 loss:0.0747342878722887 ael:0.0005073352621648777 cl:0.7422695118674375
filename: 5_hidden Epoch 91 loss:0.0745134785415303 ael:0.0005041417074073353 cl:0.7400933595948336
filename: 5_hidden Epoch 92 loss:0.07424164849337134 ael:0.0005009094839443323 cl:0.7374073766613978
filename: 5_hidden Epoch 93 loss:0.0741104277804382 ael:0.0004949197396735171 cl:0.7361550687356925
filename: 5_hidden Epoch 94 loss:0.07364251043733278 ael:0.0004917638838949881 cl:0.731507453715758
filename: 5_hidden Epoch 95 loss:0.07386660767089326 ael:0.0004894304987719681 cl:0.7337717561318128
filename: 5_hidden Epoch 96 loss:0.07357867826380483 ael:0.0004843480514839866 cl:0.7309432900256231
filename: 5_hidden Epoch 97 loss:0.07348501094174904 ael:0.00048338273779203306 cl:0.7300162696197504
filename: 5_hidden Epoch 98 loss:0.0728070980623678 ael:0.00047392301516753456 cl:0.7233317370922224
filename: 5_hidden Epoch 99 loss:0.07280330832681703 ael:0.00047104811507202906 cl:0.7233225905177322
filename: 5_hidden Epoch 100 loss:0.07256902307090829 ael:0.0004671408544600449 cl:0.7210188090167517
filename: 5_hidden Epoch 101 loss:0.07261116813686239 ael:0.0004646189862425514 cl:0.7214654793243824
filename: 5_hidden Epoch 102 loss:0.07197446471154928 ael:0.00045948790688377084 cl:0.7151497572189053
filename: 5_hidden Epoch 103 loss:0.07198264727248352 ael:0.0004581117076026152 cl:0.7152453441666242
filename: 5_hidden Epoch 104 loss:0.07197537190376692 ael:0.0004533540953276805 cl:0.7152201677798667
filename: 5_hidden Epoch 105 loss:0.07161217963482115 ael:0.0004517863457293088 cl:0.7116039206050538
filename: 5_hidden Epoch 106 loss:0.07154214336184427 ael:0.00044897703896488734 cl:0.7109316518862242
filename: 5_hidden Epoch 107 loss:0.07128258392572218 ael:0.00044461774608059104 cl:0.7083796471497663
filename: 5_hidden Epoch 108 loss:0.07100512530468496 ael:0.00044432040745231836 cl:0.7056080350548704
filename: 5_hidden Epoch 109 loss:0.07102563871126456 ael:0.00044026686400267954 cl:0.7058537067792271
filename: 5_hidden Epoch 110 loss:0.07072277235555963 ael:0.00043714351231272525 cl:0.7028562775077064
filename: 5_hidden Epoch 111 loss:0.07066083925205055 ael:0.000433104172682316 cl:0.7022773403181878
filename: 5_hidden Epoch 112 loss:0.07024533385707818 ael:0.0004323625733570864 cl:0.6981297017986268
filename: 5_hidden Epoch 113 loss:0.07012955842866159 ael:0.00042326169772000143 cl:0.6970629554727046
filename: 5_hidden Epoch 114 loss:0.07033832190066057 ael:0.0004272111505569497 cl:0.6991110949697736
filename: 5_hidden Epoch 115 loss:0.06995514523441312 ael:0.00042465272904612726 cl:0.6953049153561833
filename: 5_hidden Epoch 116 loss:0.06968117128077028 ael:0.00041685510880770877 cl:0.6926431485650312
filename: 5_hidden Epoch 117 loss:0.06999102161953281 ael:0.00041828758597308276 cl:0.6957273273822792
filename: 5_hidden Epoch 118 loss:0.0696273862837884 ael:0.0004116935184317896 cl:0.6921569137237434
filename: 5_hidden Epoch 119 loss:0.06967797722625728 ael:0.0004113621486093015 cl:0.6926661386525562
filename: 5_hidden Epoch 120 loss:0.06962165332213364 ael:0.00040867053805408515 cl:0.6921298162473328
filename: 5_hidden Epoch 121 loss:0.06889904977964464 ael:0.00040253165322459673 cl:0.6849651704929817
filename: 5_hidden Epoch 122 loss:0.068885407115712 ael:0.00040616069093302117 cl:0.6847924540142182
filename: 5_hidden Epoch 123 loss:0.06910055981595198 ael:0.00040472758929273263 cl:0.6869583098664477
filename: 5_hidden Epoch 124 loss:0.06886511733264816 ael:0.00040280239949239474 cl:0.6846231363433106
filename: 5_hidden Epoch 125 loss:0.06883131953306883 ael:0.00039893003982561837 cl:0.6843238844770566
filename: 5_hidden Epoch 126 loss:0.06839104263087416 ael:0.00039469340324355654 cl:0.6799634788648498
filename: 5_hidden Epoch 127 loss:0.06843859724531244 ael:0.00038986042953368137 cl:0.680487354977514
filename: 5_hidden Epoch 128 loss:0.06866635518234061 ael:0.0003935167608529986 cl:0.6827283709762587
filename: 5_hidden Epoch 129 loss:0.06821658536709262 ael:0.0003849278693763766 cl:0.678316563451759
filename: 5_hidden Epoch 130 loss:0.06837953517973745 ael:0.00038479524375118797 cl:0.6799473883056805
filename: 5_hidden Epoch 131 loss:0.06815875064320716 ael:0.0003825199999385098 cl:0.6777622949956549
filename: 5_hidden Epoch 132 loss:0.06817498886085366 ael:0.00037988842325583136 cl:0.6779509924080706
filename: 5_hidden Epoch 133 loss:0.06804099086966 ael:0.00037703603537441864 cl:0.6766395348035705
filename: 5_hidden Epoch 134 loss:0.06762756749061094 ael:0.0003742750206453119 cl:0.6725329127743224
filename: 5_hidden Epoch 135 loss:0.06805815482045538 ael:0.0003683197526792703 cl:0.6768983399297387
filename: 5_hidden Epoch 136 loss:0.0676550039006874 ael:0.0003660866865342674 cl:0.6728891608158997
filename: 5_hidden Epoch 137 loss:0.06786606776655768 ael:0.00036049703405372126 cl:0.6750556961837322
filename: 5_hidden Epoch 138 loss:0.06763779849159302 ael:0.0003604046266532375 cl:0.6727739267770232
filename: 5_hidden Epoch 139 loss:0.0676899398181813 ael:0.0003554086249227352 cl:0.6733452988924218
filename: 5_hidden Epoch 140 loss:0.06767272841825472 ael:0.00034824048703401575 cl:0.6732448685725354
filename: 5_hidden Epoch 141 loss:0.06755757502143526 ael:0.00034367238360953276 cl:0.6721390127041572
filename: 5_hidden Epoch 142 loss:0.06736712257708191 ael:0.00034445540631920877 cl:0.6702266605529642
filename: 5_hidden Epoch 143 loss:0.06751566648069203 ael:0.00034053757810423627 cl:0.6717512765426991
filename: 5_hidden Epoch 144 loss:0.06713130576108459 ael:0.00033483371291443033 cl:0.667964708822601
filename: 5_hidden Epoch 145 loss:0.06686445628567991 ael:0.00033239399960859767 cl:0.6653206120664735
filename: 5_hidden Epoch 146 loss:0.06742166712614632 ael:0.000328639110187941 cl:0.6709302695191102
filename: 5_hidden Epoch 147 loss:0.06645033614264488 ael:0.0003251913084013682 cl:0.661251435036611
filename: 5_hidden Epoch 148 loss:0.06684318458293906 ael:0.0003258858152140383 cl:0.6651729746441508
filename: 5_hidden Epoch 149 loss:0.06684004399951379 ael:0.00032262562515884374 cl:0.6651741724047702
filename: 5_hidden Epoch 150 loss:0.06688142674417955 ael:0.0003191172945608665 cl:0.6656230817398067
filename: 5_hidden Epoch 151 loss:0.06634646881239215 ael:0.00031690118910833 cl:0.6602956634212023
filename: 5_hidden Epoch 152 loss:0.06647755410902823 ael:0.00031437981239950655 cl:0.6616317312811386
filename: 5_hidden Epoch 153 loss:0.06646932061911336 ael:0.00031392257507334296 cl:0.6615539696246407
filename: 5_hidden Epoch 154 loss:0.06596935379456688 ael:0.00031013673349076257 cl:0.6565921582480602
filename: 5_hidden Epoch 155 loss:0.06591651538243185 ael:0.00030672929738257033 cl:0.6560978491491157
filename: 5_hidden Epoch 156 loss:0.0659107657871427 ael:0.00030413207430214244 cl:0.6560663269137563
filename: 5_hidden Epoch 157 loss:0.06592893317759776 ael:0.00030685664279229806 cl:0.6562207529636798
filename: 5_hidden Epoch 158 loss:0.0654150265576671 ael:0.00030596826510839893 cl:0.6510905704655007
filename: 5_hidden Epoch 159 loss:0.06558054768917591 ael:0.00030477187124603193 cl:0.6527577451870932
filename: 5_hidden Epoch 160 loss:0.06533361176825127 ael:0.0003054584149225366 cl:0.6502815229063446
filename: 5_hidden Epoch 161 loss:0.0649744272650486 ael:0.0003023982435053995 cl:0.6467202805131234
filename: 5_hidden Epoch 162 loss:0.06487407696989132 ael:0.0003017458039044897 cl:0.6457232994727647
filename: 5_hidden Epoch 163 loss:0.06459827427163074 ael:0.0003016939529622224 cl:0.6429657913122651
filename: 5_hidden Epoch 164 loss:0.06444700524491336 ael:0.0003088336268533663 cl:0.6413817040329677
filename: 5_hidden Epoch 165 loss:0.06435826389097936 ael:0.00030081452038485744 cl:0.6405744810296559
filename: 5_hidden Epoch 166 loss:0.06388555416791021 ael:0.00030028543750815846 cl:0.6358526762174135
filename: 5_hidden Epoch 167 loss:0.06365506421376371 ael:0.00030738808933064067 cl:0.6334767497632082
filename: 5_hidden Epoch 168 loss:0.06314435881926622 ael:0.00030742606701626723 cl:0.6283693148620181
filename: 5_hidden Epoch 169 loss:0.06265157767147805 ael:0.0003160750317786554 cl:0.6233550164154316
filename: 5_hidden Epoch 170 loss:0.06172197835400915 ael:0.00030757394077555013 cl:0.6141440334401067
filename: 5_hidden Epoch 171 loss:0.06119004498889435 ael:0.0003076986906468181 cl:0.608823452570399
filename: 5_hidden Epoch 172 loss:0.06105616018351476 ael:0.00031162158272498593 cl:0.6074453751702854
filename: 5_hidden Epoch 173 loss:0.06044524029505557 ael:0.0003083852012313289 cl:0.6013685408525686
filename: 5_hidden Epoch 174 loss:0.05998190166526128 ael:0.0003103897856452677 cl:0.5967151083768419
filename: 5_hidden Epoch 175 loss:0.05916104974815093 ael:0.0003083705944007119 cl:0.5885267811077626
filename: 5_hidden Epoch 176 loss:0.05818000937154464 ael:0.0003060352786474779 cl:0.5787397308494292
filename: 5_hidden Epoch 177 loss:0.05801949129172324 ael:0.0003054228109840484 cl:0.577140674973113
filename: 5_hidden Epoch 178 loss:0.05750166046657154 ael:0.00030842334126735725 cl:0.5719323613800582
filename: 5_hidden Epoch 179 loss:0.05665832128195099 ael:0.0003092814627484709 cl:0.563490387072474
filename: 5_hidden Epoch 180 loss:0.056019174712820134 ael:0.00030826757417775437 cl:0.5571090605885803
filename: 5_hidden Epoch 181 loss:0.05531721421038702 ael:0.00031085351685047636 cl:0.5500635982132028
filename: 5_hidden Epoch 182 loss:0.054794217781532886 ael:0.00031328523876445835 cl:0.5448093177326085
filename: 5_hidden Epoch 183 loss:0.053786047446233796 ael:0.00031021532049008496 cl:0.5347583125153275
filename: 5_hidden Epoch 184 loss:0.05261185147686289 ael:0.0003157320953231795 cl:0.5229611846731617
filename: 5_hidden Epoch 185 loss:0.052345652800937906 ael:0.00031965541592336705 cl:0.520259964250483
filename: 5_hidden Epoch 186 loss:0.05132831817085647 ael:0.0003193673131551282 cl:0.5100894997053211
filename: 5_hidden Epoch 187 loss:0.050982338810192374 ael:0.0003233195367885084 cl:0.5065901855328718
filename: 5_hidden Epoch 188 loss:0.049621412308945345 ael:0.00032632052276135277 cl:0.492950908386193
filename: 5_hidden Epoch 189 loss:0.048868934952049574 ael:0.00033158819498718385 cl:0.4853734584082265
filename: 5_hidden Epoch 190 loss:0.04782272425106695 ael:0.0003481723731388983 cl:0.47474551068894943
filename: 5_hidden Epoch 191 loss:0.04674894853495291 ael:0.0003390921297585633 cl:0.46409855608689426
filename: 5_hidden Epoch 192 loss:0.04611452515003171 ael:0.00034117343107249075 cl:0.45773351020929426
filename: 5_hidden Epoch 193 loss:0.045785015776163264 ael:0.00034971442230674073 cl:0.45435300622601293
filename: 5_hidden Epoch 194 loss:0.0447377245506943 ael:0.00035230121994478495 cl:0.44385422495616106
filename: 5_hidden Epoch 195 loss:0.0440901604554754 ael:0.0003567377674692677 cl:0.43733421989575816
filename: 5_hidden Epoch 196 loss:0.042579513250374165 ael:0.00035905169624635955 cl:0.4222046082526636

C:\Users\linco\AppData\Local\Temp\ipykernel_50728\310156585.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
C:\Users\linco\AppData\Local\Temp\ipykernel_50728\310156585.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                 0         1         2          3         4  Label
0       -23.714449  8.807453  9.138328 -19.004087  3.780637      1
1       -22.709101  3.508615  3.171620 -17.444405 -2.789791      0
2        -7.825279  4.658035  4.985006  -6.610040  3.668217      2
3       -23.862188  8.838615  9.208631 -19.059681  3.833048      1
4       -15.927458  6.346906  6.601358 -12.859289  3.158356      4
...            ...       ...       ...        ...       ...    ...
2079255 -22.707651  3.479950  3.140583 -17.437237 -2.825277      0
2079256  -7.823956  4.658403  4.985418  -6.609132  3.669116      2
2079257  -7.822762  4.658734  4.985790  -6.608313  3.669927      2
2079258 -22.673147  3.509168  3.172979 -17.418961 -2.777680      0
2079259  -7.801080  4.663365  4.987548  -6.594034  3.681217      2

[2079260 rows x 6 columns]

Davies-Bouldin Score: 0.035277358125125904

                0         1         2          3         4  Label
0      -22.751348  3.504588  3.124305 -17.439400 -2.854688      0
1       -7.829831  4.657374  4.984282  -6.613243  3.665909      2
2      -23.888180  8.823393  9.132940 -19.044310  3.730878      1
3       -1.421076  0.359308  0.295145  -1.316149  0.103529      3
4      -23.708405  8.736197  9.083659 -18.970789  3.756942      1
...           ...       ...       ...        ...       ...    ...
519951 -23.876476  8.832364  9.187076 -19.041460  3.770055      1
519952 -16.094866  6.348246  6.614672 -12.959662  3.054944      4
519953 -22.712402  3.489101  3.150401 -17.442572 -2.815310      0
519954 -23.803226  8.814026  9.114130 -19.050419  3.742764      1
519955  -1.524927  0.379668  0.296032  -1.397609  0.133900      3

[519956 rows x 6 columns]

                0         1         2          3         4  Label
0      -22.715939  3.508509  3.171360 -17.449242 -2.792096      0
1      -22.753258  3.512852  3.134067 -17.441826 -2.844079      0
2      -23.617523  8.736773  9.066226 -18.830179  3.722422      1
3      -24.208742  8.956999  9.303881 -19.296675  3.826121      1
4      -22.751255  3.523521  3.176878 -17.450157 -2.851921      0
...           ...       ...       ...        ...       ...    ...
649942 -23.812614  8.770892  9.115119 -19.051184  3.764956      1
649943 -22.757195  3.545540  3.196683 -17.461575 -2.831181      0
649944 -22.748598  3.531909  3.186722 -17.449286 -2.840628      0
649945  -1.502956  0.385110  0.296889  -1.386206  0.078232      3
649946  -7.777789  4.537820  4.857102  -6.575325  3.460378      2

[649947 rows x 6 columns]