In [1]:
import torch
from torch import nn, optim
import torch.nn.functional as F
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.decomposition import PCA
from scipy.stats import chi2
from sklearn.mixture import GaussianMixture
from collections import deque, defaultdict

# CAE

In [2]:
train = pd.read_csv('../../../train_CADE_cod.csv')
val = pd.read_csv('../../../val_CADE_cod.csv')
test = pd.read_csv('../../../test_CADE_cod.csv')

In [3]:
classes_out = ['Infilteration','DoS attacks-SlowHTTPTest']
train = train.drop(index=train[train['Label'].isin(classes_out)].index)
val = val.drop(index=val[val['Label'].isin(classes_out)].index)
test = test.drop(index=test[test['Label'].isin(classes_out)].index)

# CAE CADE (margin 1 e lambda 1.0)

In [4]:
def pick_pair(embeddings, labels, pick_embeddings, pick_labels):
    """
    Gera todos os pares entre embeddings e pick_embeddings,
    com labels_pair indicando se os pares são positivos (0) ou negativos (1).
    """
    N, D = embeddings.shape
    M = pick_embeddings.shape[0]

    # Expande para todas as combinações possíveis
    A = embeddings.unsqueeze(0).expand(M, N, D).reshape(M * N, D)
    B = pick_embeddings.unsqueeze(1).expand(M, N, D).reshape(M * N, D)

    labels_exp = labels.unsqueeze(0).expand(M, N)
    pick_labels_exp = pick_labels.unsqueeze(1).expand(M, N)
    labels_pair = (labels_exp != pick_labels_exp).reshape(-1).float()

    return A, B, labels_pair

def ContrastiveLoss(input1, input2, y, margin=1.0):
    # y = 0 quando input1 e input2 são da mesma classe e y = 1 caso contrário
    diff = input1 - input2
    dist_sq = torch.sum(torch.pow(diff,2),1)
    dist = torch.sqrt(dist_sq + 1e-10) # Soma 1e-10 pois se o sqrt der 0 o gradiente da NaN
    mdist = margin - dist
    mdist = F.relu(mdist)
    loss = ((1-y) * dist * dist) + (y * mdist * mdist)
    return torch.mean(loss)

def AEContrastive(input, output, embeddings, labels, pick_encoded, pick_labels, margin=1.0, lambda1=1.0):
    mseloss = nn.MSELoss()
    ae_loss = mseloss(input,output)

    A, B, labels_pair = pick_pair(embeddings, labels, pick_encoded, pick_labels)
    contrastive_loss = ContrastiveLoss(A, B, labels_pair, margin=margin)
    return ae_loss + contrastive_loss * lambda1, ae_loss, contrastive_loss

In [5]:
class contrastive_ae(nn.Module):
    def __init__(self, input_neurons, neurons):
        super().__init__()
        self.encoder0 = nn.Linear(input_neurons,64)
        self.encoder1 = nn.Linear(64,32)
        self.encoder2 = nn.Linear(32,16)
        self.encoder3 = nn.Linear(16,neurons)

        self.decoder0 = nn.Linear(neurons,16)
        self.decoder1 = nn.Linear(16,32)
        self.decoder2 = nn.Linear(32,64)
        self.decoder3 = nn.Linear(64,input_neurons)

        self.activation0 = nn.ReLU()
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X)
        encoded = X
        X = self.activation0(self.decoder0(X))
        X = self.activation0(self.decoder1(X))
        X = self.activation0(self.decoder2(X))
        X = self.decoder3(X)


        return X, encoded

In [6]:
class encoder(nn.Module):
    def __init__(self, model):
        super().__init__()
        self.encoder0 = list(model.children())[0]
        self.encoder1 = list(model.children())[1]
        self.encoder2 = list(model.children())[2]
        self.encoder3 = list(model.children())[3]
        self.activation0 = list(model.children())[8]
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X)
        return X

In [7]:
from torch.utils.data import Dataset, DataLoader,TensorDataset
import random
def build_class_reference_batches(X_train, y_train, batch_size=512):
    classes = torch.unique(y_train).tolist()
    n_classes = len(classes)
    total_samples = len(X_train)
    dataset = TensorDataset(X_train, y_train)
    train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    

    print(classes)

    # Mapeia cada classe para seus índices
    class_to_indices = {
        int(cls.item()): (y_train == cls).nonzero(as_tuple=True)[0].tolist()
        for cls in torch.unique(y_train)
    }

    reference_list = []
    total_batches = len(train_loader)

    for batch_idx in range(total_batches):
        start = batch_idx * batch_size
        end = min(start + batch_size, total_samples)
        batch_indices = set(range(start, end))

        class_samples = []
        for cls in classes:
            candidates = [i for i in class_to_indices[cls] if i not in batch_indices]
            if not candidates:
                raise ValueError(f"Classe {cls} não possui amostras fora do batch {batch_idx}")
            chosen = candidates[torch.randint(len(candidates), (1,)).item()]
            class_samples.append(chosen)

        reference_list.append(class_samples)


    return train_loader, reference_list

In [8]:
def normalize(t):
    t_norm = (t - t.mean()) / t.std()
    return t_norm

In [9]:
train['Label'] = train['Label'].replace('FTP-BruteForce','BruteForce')
train['Label'] = train['Label'].replace('SSH-Bruteforce','BruteForce')
train['Label'] = train['Label'].replace('DoS attacks-GoldenEye','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Slowloris','DoS')
## train['Label'] = train['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Hulk','DoS')
# train['Label'] = train['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
train['Label'] = train['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
train['Label'] = train['Label'].replace('DDOS attack-HOIC','DDoS')
train['Label'] = train['Label'].replace('Brute Force -Web','Web')
train['Label'] = train['Label'].replace('Brute Force -XSS','Web')
train['Label'] = train['Label'].replace('SQL Injection','Web')


val['Label'] = val['Label'].replace('FTP-BruteForce','BruteForce')
val['Label'] = val['Label'].replace('SSH-Bruteforce','BruteForce')
val['Label'] = val['Label'].replace('DoS attacks-GoldenEye','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Slowloris','DoS')
## val['Label'] = val['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Hulk','DoS')
# val['Label'] = val['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
val['Label'] = val['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
val['Label'] = val['Label'].replace('DDOS attack-HOIC','DDoS')
val['Label'] = val['Label'].replace('Brute Force -Web','Web')
val['Label'] = val['Label'].replace('Brute Force -XSS','Web')
val['Label'] = val['Label'].replace('SQL Injection','Web')


test['Label'] = test['Label'].replace('FTP-BruteForce','BruteForce')
test['Label'] = test['Label'].replace('SSH-Bruteforce','BruteForce')
test['Label'] = test['Label'].replace('DoS attacks-GoldenEye','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Slowloris','DoS')
## test['Label'] = test['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Hulk','DoS')
# test['Label'] = test['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
test['Label'] = test['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
test['Label'] = test['Label'].replace('DDOS attack-HOIC','DDoS')
test['Label'] = test['Label'].replace('Brute Force -Web','Web')
test['Label'] = test['Label'].replace('Brute Force -XSS','Web')
test['Label'] = test['Label'].replace('SQL Injection','Web')

In [10]:
labels_str = [i for i in train['Label'].value_counts().index]
print(labels_str)

for i, l in enumerate(labels_str):
    train['Label'] = train['Label'].replace(l, i)
    val['Label'] = val['Label'].replace(l, i)
    test['Label'] = test['Label'].replace(l, i)

['Benign', 'DDoS', 'DDoS attacks-LOIC-HTTP', 'DoS', 'BruteForce', 'Bot', 'Web']

/tmp/ipykernel_776206/2307520911.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train['Label'] = train['Label'].replace(l, i)
/tmp/ipykernel_776206/2307520911.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  val['Label'] = val['Label'].replace(l, i)
/tmp/ipykernel_776206/2307520911.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['Label'] = test['Label'].replace(l, i)

In [11]:
array_hidden_classes = [[2]]
filenames = ['2']
# array_hidden_classes = [[0]]
# filenames = ['0']
total_classes = len(labels_str)
for i in range(len(array_hidden_classes)):
    filename = f'{filenames[i]}_hidden'
    print(filename)
    hidden_classes = array_hidden_classes[i] #Classes ocultas do treinamento

    hidden_classes_index = list(train[train['Label'].isin(hidden_classes)].index)

    train_hidden = train.loc[hidden_classes_index]

    train_not_hidden = train.drop(hidden_classes_index)

    X_train = train_not_hidden.drop(columns=['Label'])
    y_train = train_not_hidden['Label']
    X_val = val.drop(columns=['Label'])
    y_val = val['Label'].values
    X_test = test.drop(columns=['Label'])
    y_test = test['Label'].values

    torch.manual_seed(123)
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(device)
    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_loader, pick_list = build_class_reference_batches(X_train,y_train, batch_size=512)
    pick_samples = []
    pick_labels = []
    for l in pick_list:
        pick_samples.append(X_train[l])
        pick_labels.append(y_train[l])

    pick_samples = torch.stack(pick_samples)    
    pick_labels = torch.stack(pick_labels)

    print('pick completo')

    neurons = total_classes - len(hidden_classes)
    print(f'{X_train.shape[1]} {neurons}')
    model = contrastive_ae(input_neurons=X_train.shape[1],neurons=neurons)
    model.to(device)

    learning_rate = 0.0001
    opt = optim.Adam(model.parameters(),lr=learning_rate)
    margin = 10 # Parametro de afastamento das classes
    cae_lambda_1 = 0.1 # Parametro de influencia na distancia das classes
    
    
    for epoch in range(250):
        running_loss = 0
        running_ael = 0
        running_cl = 0
        contador = 0
        for data in train_loader:
            inputs, labels = data
            inputs = inputs.to(device)
            labels = labels.to(device)
            ps = pick_samples[contador]
            pl = pick_labels[contador]
            ps = ps.to(device)
            pl = pl.to(device)
            contador += 1
            #print(f'{contador}/{len(train_loader)}')
            opt.zero_grad()
            outputs, encoded = model(inputs)
            _, pick_encoded = model(ps)
            tam_pe = pick_encoded.shape[0]
            enc_total = torch.cat((encoded,pick_encoded), dim=0)
            enc_total_norm = normalize(enc_total)
            encoded_norm = enc_total_norm[:-tam_pe]
            pick_encoded_norm = enc_total_norm[-tam_pe:]
            loss, ael, cl = AEContrastive(input=inputs, output=outputs, embeddings = encoded_norm, labels=labels, pick_encoded = pick_encoded_norm, pick_labels = pl, margin=margin, lambda1=cae_lambda_1)
            #loss = dummyMSELoss(inputs,outputs)
            loss.backward()
            opt.step()
            running_loss += loss.item()
            running_ael += ael.item()
            running_cl += cl.item()
            #print(f'loss = {loss.item()} batch_size = {size}')
        print(f'filename: {filename} Epoch {epoch+1} loss:{running_loss/len(train_loader)} ael:{running_ael/len(train_loader)} cl:{running_cl/len(train_loader)}')

    model_e = encoder(model=model)
    model_e.to(device)

    model_e.eval()

    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_encoded = model_e(X_train.to(device))

    train_encoded = train_encoded.detach().cpu().numpy()

    train_encoded_df = pd.DataFrame(train_encoded)
    train_encoded_df['Label'] = y_train.detach().cpu().numpy().astype(int)
    display(train_encoded_df)

    score = davies_bouldin_score(train_encoded_df.drop(columns=['Label']), train_encoded_df['Label'])
    print("Davies-Bouldin Score:", score)

    X_val = torch.tensor(np.array(X_val), dtype=torch.float)

    val_encoded = model_e(X_val.to(device))

    val_encoded = val_encoded.detach().cpu().numpy()

    val_encoded_df = pd.DataFrame(val_encoded)

    val_encoded_df['Label'] = y_val

    display(val_encoded_df)

    X_test = torch.tensor(np.array(X_test), dtype=torch.float)

    test_encoded = model_e(X_test.to(device))

    test_encoded = test_encoded.detach().cpu().numpy()

    test_encoded_df = pd.DataFrame(test_encoded)

    test_encoded_df['Label'] = y_test

    display(test_encoded_df)

    train_encoded_df.to_csv(f'train_encoded_CADE_cod_pick_class_squared_normalized_{filename}.csv',index=False)
    val_encoded_df.to_csv(f'val_encoded_CADE_cod_pick_class_squared_normalized_{filename}.csv',index=False)
    test_encoded_df.to_csv(f'test_encoded_CADE_cod_pick_class_squared_normalized_{filename}.csv',index=False)

2_hidden

cuda

[0.0, 1.0, 3.0, 4.0, 5.0, 6.0]

pick completo
82 6

filename: 2_hidden Epoch 1 loss:3.3092190643615313 ael:0.02366287424020081 cl:32.85556140764968

filename: 2_hidden Epoch 2 loss:2.9533546461736564 ael:0.016490570214347952 cl:29.368640271865416

filename: 2_hidden Epoch 3 loss:2.9060944918741516 ael:0.016152012370357356 cl:28.899424332619283

filename: 2_hidden Epoch 4 loss:2.8746590086402186 ael:0.014661250625392015 cl:28.59997710177172

filename: 2_hidden Epoch 5 loss:2.8460731010534035 ael:0.013476768880859597 cl:28.32596286109363

filename: 2_hidden Epoch 6 loss:2.819339374023451 ael:0.0132916797368265 cl:28.06047648059473

filename: 2_hidden Epoch 7 loss:2.796518700269794 ael:0.013251013119712267 cl:27.83267642009194

filename: 2_hidden Epoch 8 loss:2.7797998850535377 ael:0.013171760554864048 cl:27.666280782986085

filename: 2_hidden Epoch 9 loss:2.7670962937501717 ael:0.013022345658793002 cl:27.540739028629325

filename: 2_hidden Epoch 10 loss:2.7568952129816022 ael:0.012834537515995266 cl:27.440606283328265

filename: 2_hidden Epoch 11 loss:2.749237345907233 ael:0.012540554530240867 cl:27.36696744949642

filename: 2_hidden Epoch 12 loss:2.7423573361407634 ael:0.012183720611575334 cl:27.30173566967766

filename: 2_hidden Epoch 13 loss:2.7347941181746735 ael:0.011801039647335495 cl:27.229930313242757

filename: 2_hidden Epoch 14 loss:2.728951403582474 ael:0.011406457895732957 cl:27.175448958706813

filename: 2_hidden Epoch 15 loss:2.720942081269356 ael:0.011045847650737748 cl:27.098961827285557

filename: 2_hidden Epoch 16 loss:2.7155493061960563 ael:0.010730209613507609 cl:27.048190499835925

filename: 2_hidden Epoch 17 loss:2.7105376550639053 ael:0.010403754785969043 cl:27.001338523280328

filename: 2_hidden Epoch 18 loss:2.70642945967628 ael:0.010130683952643754 cl:26.962987277694694

filename: 2_hidden Epoch 19 loss:2.702887505774438 ael:0.00982833672066864 cl:26.930591202010515

filename: 2_hidden Epoch 20 loss:2.700641214312514 ael:0.009566664082800188 cl:26.910745012909977

filename: 2_hidden Epoch 21 loss:2.6973737780738207 ael:0.009281543409953453 cl:26.8809218826157

filename: 2_hidden Epoch 22 loss:2.6943681550411176 ael:0.009045593237519968 cl:26.85322515783304

filename: 2_hidden Epoch 23 loss:2.6908062669347674 ael:0.00882561685253249 cl:26.81980599849114

filename: 2_hidden Epoch 24 loss:2.6870381539628436 ael:0.008594795567987298 cl:26.784433120028975

filename: 2_hidden Epoch 25 loss:2.6844586085445648 ael:0.00839706768592756 cl:26.760614939609166

filename: 2_hidden Epoch 26 loss:2.6812230235156296 ael:0.008194669947933287 cl:26.7302830534592

filename: 2_hidden Epoch 27 loss:2.678174881718246 ael:0.007998264847542891 cl:26.701765704197772

filename: 2_hidden Epoch 28 loss:2.6755642906624995 ael:0.007787709686328852 cl:26.67776532061866

filename: 2_hidden Epoch 29 loss:2.672498308492235 ael:0.00761699735397113 cl:26.64881261532211

filename: 2_hidden Epoch 30 loss:2.670002744199272 ael:0.007466776936745827 cl:26.62535919620918

filename: 2_hidden Epoch 31 loss:2.6674171268832962 ael:0.007312768579247218 cl:26.601043102485843

filename: 2_hidden Epoch 32 loss:2.6642470518177244 ael:0.00718726018928036 cl:26.570597454575562

filename: 2_hidden Epoch 33 loss:2.661969321135059 ael:0.007042616412638815 cl:26.549266574341406

filename: 2_hidden Epoch 34 loss:2.658653589724638 ael:0.006905502862509347 cl:26.51748039992108

filename: 2_hidden Epoch 35 loss:2.656662621232723 ael:0.0067543535304374494 cl:26.499082204041404

filename: 2_hidden Epoch 36 loss:2.6531412393871285 ael:0.006605863461230799 cl:26.465353263772798

filename: 2_hidden Epoch 37 loss:2.6509398184159356 ael:0.006484251093584208 cl:26.44455520212115

filename: 2_hidden Epoch 38 loss:2.6480435424047912 ael:0.006329574983930388 cl:26.417139208010042

filename: 2_hidden Epoch 39 loss:2.6467289790502213 ael:0.006161160711901299 cl:26.405677729206552

filename: 2_hidden Epoch 40 loss:2.6449927978355823 ael:0.005990968034410418 cl:26.390017817649635

filename: 2_hidden Epoch 41 loss:2.6432248550143376 ael:0.005838849992262236 cl:26.373859556187845

filename: 2_hidden Epoch 42 loss:2.6401379375240888 ael:0.005611104327786261 cl:26.345267849436496

filename: 2_hidden Epoch 43 loss:2.6374685357674235 ael:0.005486246200505798 cl:26.319822444950013

filename: 2_hidden Epoch 44 loss:2.636115300020438 ael:0.005276551389554543 cl:26.30838702582514

filename: 2_hidden Epoch 45 loss:2.6354084107634694 ael:0.005110462295866272 cl:26.302979005303374

filename: 2_hidden Epoch 46 loss:2.6321165521725574 ael:0.004931706290250117 cl:26.27184799600689

filename: 2_hidden Epoch 47 loss:2.6314278847439283 ael:0.004793473463162739 cl:26.26634363097962

filename: 2_hidden Epoch 48 loss:2.6297193880497804 ael:0.0046549818377088 cl:26.25064360118069

filename: 2_hidden Epoch 49 loss:2.62973287503638 ael:0.004557436497498555 cl:26.251753929202103

filename: 2_hidden Epoch 50 loss:2.6275805877683265 ael:0.004425699079525169 cl:26.231548442874818

filename: 2_hidden Epoch 51 loss:2.625900835423039 ael:0.004336509730498 cl:26.215642779548322

filename: 2_hidden Epoch 52 loss:2.6264200870467116 ael:0.004234957705206727 cl:26.22185081354092

filename: 2_hidden Epoch 53 loss:2.62443125783006 ael:0.004133015582622222 cl:26.202981952276865

filename: 2_hidden Epoch 54 loss:2.623744577008903 ael:0.004036904519236017 cl:26.19707625244707

filename: 2_hidden Epoch 55 loss:2.6226008556903584 ael:0.003952613923119583 cl:26.18648192384584

filename: 2_hidden Epoch 56 loss:2.621305035660183 ael:0.0038521478273351255 cl:26.17452842214734

filename: 2_hidden Epoch 57 loss:2.621878763146917 ael:0.003782248334668773 cl:26.180964682788495

filename: 2_hidden Epoch 58 loss:2.6205584563444217 ael:0.00369389633722503 cl:26.1686451191106

filename: 2_hidden Epoch 59 loss:2.6206139274730718 ael:0.003608128933399305 cl:26.170057537026352

filename: 2_hidden Epoch 60 loss:2.618721698302127 ael:0.003551948724388697 cl:26.15169701670402

filename: 2_hidden Epoch 61 loss:2.617949247003529 ael:0.0034890420808591158 cl:26.144601583338154

filename: 2_hidden Epoch 62 loss:2.616220167338099 ael:0.003415818788283429 cl:26.128043017795456

filename: 2_hidden Epoch 63 loss:2.6157012933175197 ael:0.0033533220345328294 cl:26.12347923703425

filename: 2_hidden Epoch 64 loss:2.6151150168236823 ael:0.0032967250769231123 cl:26.118182463677325

filename: 2_hidden Epoch 65 loss:2.6130082971817146 ael:0.0032410807492359714 cl:26.097671665166537

filename: 2_hidden Epoch 66 loss:2.613859518497451 ael:0.0031873677318825437 cl:26.10672101226843

filename: 2_hidden Epoch 67 loss:2.6123204366808377 ael:0.0031374794150825828 cl:26.091829092755138

filename: 2_hidden Epoch 68 loss:2.611085021231861 ael:0.00309562257851654 cl:26.07989349513622

filename: 2_hidden Epoch 69 loss:2.6106856402917082 ael:0.0030479231607703963 cl:26.076376705523526

filename: 2_hidden Epoch 70 loss:2.610318596244643 ael:0.002996369282994252 cl:26.073221784805124

filename: 2_hidden Epoch 71 loss:2.6098412391598678 ael:0.002965444516538816 cl:26.068757483518315

filename: 2_hidden Epoch 72 loss:2.6097163779517265 ael:0.0029349843536702583 cl:26.06781342984102

filename: 2_hidden Epoch 73 loss:2.6086605702382517 ael:0.0028990488618883714 cl:26.057614776775697

filename: 2_hidden Epoch 74 loss:2.608204033901276 ael:0.002859129059757705 cl:26.053448542372898

filename: 2_hidden Epoch 75 loss:2.6081253093277743 ael:0.0028239317393481604 cl:26.053013299911196

filename: 2_hidden Epoch 76 loss:2.6070269044468604 ael:0.002798612077928353 cl:26.042282453773264

filename: 2_hidden Epoch 77 loss:2.606252079592145 ael:0.0027629914815801813 cl:26.034890392310317

filename: 2_hidden Epoch 78 loss:2.6050709095064 ael:0.0027275397935182743 cl:26.02343322815544

filename: 2_hidden Epoch 79 loss:2.6057605624270255 ael:0.002704012556549692 cl:26.03056499988001

filename: 2_hidden Epoch 80 loss:2.6047120381799878 ael:0.002677995436654868 cl:26.020339964678872

filename: 2_hidden Epoch 81 loss:2.6042086682870385 ael:0.002648576160839618 cl:26.015600449306962

filename: 2_hidden Epoch 82 loss:2.6042859961642684 ael:0.002604127453583254 cl:26.01681822006892

filename: 2_hidden Epoch 83 loss:2.603045742787122 ael:0.0025770653557268663 cl:26.00468626085118

filename: 2_hidden Epoch 84 loss:2.602432377177181 ael:0.0025610312617304195 cl:25.99871298426429

filename: 2_hidden Epoch 85 loss:2.601505692243433 ael:0.002539734196774483 cl:25.989659093084057

filename: 2_hidden Epoch 86 loss:2.601819970806083 ael:0.002506930174215188 cl:25.993129899157942

filename: 2_hidden Epoch 87 loss:2.600402780309685 ael:0.00248538856414096 cl:25.979173439980123

filename: 2_hidden Epoch 88 loss:2.599640724831609 ael:0.002461493993045641 cl:25.97179183526213

filename: 2_hidden Epoch 89 loss:2.5989864732889556 ael:0.0024471482708099904 cl:25.965392762212108

filename: 2_hidden Epoch 90 loss:2.598123146273432 ael:0.002416600443929699 cl:25.957065001281702

filename: 2_hidden Epoch 91 loss:2.597371826123364 ael:0.002414101384187765 cl:25.949576779085316

filename: 2_hidden Epoch 92 loss:2.598422846560133 ael:0.00239876499076283 cl:25.960240353231015

filename: 2_hidden Epoch 93 loss:2.5960807927991727 ael:0.0023671725096335978 cl:25.937135719810684

filename: 2_hidden Epoch 94 loss:2.5963667848736565 ael:0.0023584451561516127 cl:25.940082930148826

filename: 2_hidden Epoch 95 loss:2.5950984387680274 ael:0.0023394007427909955 cl:25.927589942708405

filename: 2_hidden Epoch 96 loss:2.5941362172668385 ael:0.0023238094572874063 cl:25.91812362134421

filename: 2_hidden Epoch 97 loss:2.5928933671817744 ael:0.0023242764602421397 cl:25.905690428883926

filename: 2_hidden Epoch 98 loss:2.593819463131743 ael:0.0023059944600203504 cl:25.91513418280957

filename: 2_hidden Epoch 99 loss:2.5924493147184005 ael:0.0022980320758678417 cl:25.901512331480326

filename: 2_hidden Epoch 100 loss:2.590449179952406 ael:0.002276911483059026 cl:25.881722231670313

filename: 2_hidden Epoch 101 loss:2.5904611996160445 ael:0.0022728387443006 cl:25.88188313667393

filename: 2_hidden Epoch 102 loss:2.589793763497431 ael:0.002260591921624786 cl:25.87533121148959

filename: 2_hidden Epoch 103 loss:2.5892378546961905 ael:0.002256773319220776 cl:25.86981033094624

filename: 2_hidden Epoch 104 loss:2.5888490469993624 ael:0.002232511339628069 cl:25.866164854085067

filename: 2_hidden Epoch 105 loss:2.5889207005572135 ael:0.00222521147820714 cl:25.866954413093826

filename: 2_hidden Epoch 106 loss:2.588602257160139 ael:0.0022114767825143454 cl:25.8639073214939

filename: 2_hidden Epoch 107 loss:2.5873717540470444 ael:0.002190292487917206 cl:25.851814182128543

filename: 2_hidden Epoch 108 loss:2.587637306401146 ael:0.002187225027997738 cl:25.854500308855787

filename: 2_hidden Epoch 109 loss:2.586227150394273 ael:0.0021697386284080127 cl:25.840573639016462

filename: 2_hidden Epoch 110 loss:2.585508187754578 ael:0.0021608804430540054 cl:25.83347257663218

filename: 2_hidden Epoch 111 loss:2.584221587860249 ael:0.002156546166093372 cl:25.82064995060846

filename: 2_hidden Epoch 112 loss:2.5839509222765726 ael:0.0021473325989688433 cl:25.818035392258995

filename: 2_hidden Epoch 113 loss:2.5843142551408422 ael:0.0021398022060546153 cl:25.82174403934262

filename: 2_hidden Epoch 114 loss:2.5836633934652213 ael:0.002125111050159185 cl:25.815382331377872

filename: 2_hidden Epoch 115 loss:2.584036839857278 ael:0.0021202888760622645 cl:25.81916500322124

filename: 2_hidden Epoch 116 loss:2.5822499837795467 ael:0.0021094290781300796 cl:25.801405061439866

filename: 2_hidden Epoch 117 loss:2.583787732178547 ael:0.002100692424833449 cl:25.81686990122678

filename: 2_hidden Epoch 118 loss:2.5832713021267537 ael:0.002091020057610454 cl:25.811802361269756

filename: 2_hidden Epoch 119 loss:2.583030741276105 ael:0.0020744229055481853 cl:25.809562697373487

filename: 2_hidden Epoch 120 loss:2.5821092858562777 ael:0.0020718292497184277 cl:25.80037409213401

filename: 2_hidden Epoch 121 loss:2.582503741048611 ael:0.002053749947242978 cl:25.804499462362823

filename: 2_hidden Epoch 122 loss:2.5815375322071397 ael:0.0020530369968913198 cl:25.79484448298803

filename: 2_hidden Epoch 123 loss:2.581050703298682 ael:0.0020426299145979163 cl:25.790080220595154

filename: 2_hidden Epoch 124 loss:2.5815851690525213 ael:0.002035887537380309 cl:25.795492341174544

filename: 2_hidden Epoch 125 loss:2.5794599295233196 ael:0.0020358274558925234 cl:25.77424053943207

filename: 2_hidden Epoch 126 loss:2.580085977332311 ael:0.002035839355126846 cl:25.780500904519283

filename: 2_hidden Epoch 127 loss:2.579821039858441 ael:0.002013224152713526 cl:25.77807766202679

filename: 2_hidden Epoch 128 loss:2.5792705922123917 ael:0.0020084600813922602 cl:25.77262084773741

filename: 2_hidden Epoch 129 loss:2.578790277153485 ael:0.0020065083665737602 cl:25.767837197961814

filename: 2_hidden Epoch 130 loss:2.5790288740828107 ael:0.0019952725067794354 cl:25.77033551819377

filename: 2_hidden Epoch 131 loss:2.5781487671648367 ael:0.0019982814343151804 cl:25.761504379879707

filename: 2_hidden Epoch 132 loss:2.578694805422634 ael:0.0019901700773558404 cl:25.767045887411175

filename: 2_hidden Epoch 133 loss:2.577028601630443 ael:0.0019801118360126737 cl:25.750484413475707

filename: 2_hidden Epoch 134 loss:2.577512333380256 ael:0.001984901205163654 cl:25.755273849217925

filename: 2_hidden Epoch 135 loss:2.5764847343229094 ael:0.001984963145255842 cl:25.744997241980727

filename: 2_hidden Epoch 136 loss:2.5769013107215337 ael:0.001969918817913473 cl:25.749313410993537

filename: 2_hidden Epoch 137 loss:2.576261517032758 ael:0.0019619353313764243 cl:25.742995327208156

filename: 2_hidden Epoch 138 loss:2.5757761001586914 ael:0.0019509163393233839 cl:25.73825135165385

filename: 2_hidden Epoch 139 loss:2.5752359324768586 ael:0.0019486533813493439 cl:25.732872295779142

filename: 2_hidden Epoch 140 loss:2.575414570629204 ael:0.0019501031696615837 cl:25.734644227795513

filename: 2_hidden Epoch 141 loss:2.5756564359333898 ael:0.0019420951796848302 cl:25.737142924132424

filename: 2_hidden Epoch 142 loss:2.574640716855787 ael:0.0019343820826416887 cl:25.72706286511972

filename: 2_hidden Epoch 143 loss:2.5742219197115164 ael:0.0019360585293213138 cl:25.722858139599676

filename: 2_hidden Epoch 144 loss:2.5738805013099593 ael:0.0019374513129309658 cl:25.7194300194403

filename: 2_hidden Epoch 145 loss:2.5741751380911277 ael:0.0019273448631739805 cl:25.72247748657446

filename: 2_hidden Epoch 146 loss:2.5740251008940627 ael:0.0019186737580084978 cl:25.72106380451232

filename: 2_hidden Epoch 147 loss:2.5744153352500008 ael:0.0019106766260421335 cl:25.72504609905268

filename: 2_hidden Epoch 148 loss:2.5727515981840843 ael:0.0019002725180522174 cl:25.708512796462475

filename: 2_hidden Epoch 149 loss:2.5725398523803245 ael:0.0019020483519963894 cl:25.70637758929597

filename: 2_hidden Epoch 150 loss:2.572375785512599 ael:0.0018945053665113442 cl:25.704812312967974

filename: 2_hidden Epoch 151 loss:2.571712822060896 ael:0.0018852610241848573 cl:25.69827513292405

filename: 2_hidden Epoch 152 loss:2.5714845006013616 ael:0.0018910133189779224 cl:25.69593435386781

filename: 2_hidden Epoch 153 loss:2.5703327169966226 ael:0.0018748869649680773 cl:25.684577794648586

filename: 2_hidden Epoch 154 loss:2.570939141358536 ael:0.001883188215172713 cl:25.690559079588564

filename: 2_hidden Epoch 155 loss:2.5708747891021444 ael:0.0018713045226441242 cl:25.690034369235264

filename: 2_hidden Epoch 156 loss:2.570401718557987 ael:0.0018708449148142155 cl:25.685308269795225

filename: 2_hidden Epoch 157 loss:2.5701259696362335 ael:0.0018534885682076447 cl:25.68272434202659

filename: 2_hidden Epoch 158 loss:2.570551572339682 ael:0.0018467817272721186 cl:25.68704742018439

filename: 2_hidden Epoch 159 loss:2.5692005327260117 ael:0.0018424565684666745 cl:25.673580296377732

filename: 2_hidden Epoch 160 loss:2.5691639640814956 ael:0.0018380609330027862 cl:25.673258573120044

filename: 2_hidden Epoch 161 loss:2.569034246682122 ael:0.0018213849143670757 cl:25.67212810893033

filename: 2_hidden Epoch 162 loss:2.56825921729537 ael:0.0018170310820010895 cl:25.664421403429454

filename: 2_hidden Epoch 163 loss:2.5682206676079082 ael:0.0018208210159999941 cl:25.66399799600324

filename: 2_hidden Epoch 164 loss:2.5672613998717853 ael:0.001814588806009503 cl:25.654467630643175

filename: 2_hidden Epoch 165 loss:2.5673411952600302 ael:0.0018059040064728952 cl:25.65535243837367

filename: 2_hidden Epoch 166 loss:2.567119875116879 ael:0.0018019266669356438 cl:25.653179019172345

filename: 2_hidden Epoch 167 loss:2.5677324368666916 ael:0.0017883940013950408 cl:25.659439949843787

filename: 2_hidden Epoch 168 loss:2.5668219400693526 ael:0.0017818525704688419 cl:25.650400391743613

filename: 2_hidden Epoch 169 loss:2.56601160604179 ael:0.0017835406758538255 cl:25.642280201366887

filename: 2_hidden Epoch 170 loss:2.566434791814346 ael:0.0017656786914888095 cl:25.64669065914919

filename: 2_hidden Epoch 171 loss:2.5664151412580343 ael:0.0017607601253660803 cl:25.646543317894107

filename: 2_hidden Epoch 172 loss:2.56763735558015 ael:0.0017604893770120159 cl:25.65876815277684

filename: 2_hidden Epoch 173 loss:2.5654174553142344 ael:0.001742117211869447 cl:25.63675292247359

filename: 2_hidden Epoch 174 loss:2.566184017916485 ael:0.0017459990961724064 cl:25.64437967628009

filename: 2_hidden Epoch 175 loss:2.5665214215118253 ael:0.001732083702581711 cl:25.64789290174191

filename: 2_hidden Epoch 176 loss:2.565106912832072 ael:0.0017219384062997908 cl:25.633849256984636

filename: 2_hidden Epoch 177 loss:2.5651167672526545 ael:0.0017307810641419453 cl:25.633859396408877

filename: 2_hidden Epoch 178 loss:2.564118062857737 ael:0.001717371508918863 cl:25.624006428881223

filename: 2_hidden Epoch 179 loss:2.5649083862755555 ael:0.0017213019015566227 cl:25.631870355383498

filename: 2_hidden Epoch 180 loss:2.565513634881454 ael:0.0017007661742388974 cl:25.63812822756262

filename: 2_hidden Epoch 181 loss:2.564479409827935 ael:0.0016924287272815914 cl:25.627869344057256

filename: 2_hidden Epoch 182 loss:2.564538271251658 ael:0.0016713853920102097 cl:25.628668377029904

filename: 2_hidden Epoch 183 loss:2.56350858257175 ael:0.0016591865149254725 cl:25.61849346195132

filename: 2_hidden Epoch 184 loss:2.5634627473489884 ael:0.001655152678914103 cl:25.61807546381605

filename: 2_hidden Epoch 185 loss:2.563078366376054 ael:0.0016485246394472202 cl:25.61429794729291

filename: 2_hidden Epoch 186 loss:2.5637885125221285 ael:0.0016443270635091655 cl:25.62144135544216

filename: 2_hidden Epoch 187 loss:2.562605965429976 ael:0.0016304659363877794 cl:25.609754487613515

filename: 2_hidden Epoch 188 loss:2.5631145081214743 ael:0.0016178271457269221 cl:25.614966343435107

filename: 2_hidden Epoch 189 loss:2.56180873343789 ael:0.0016140107751390904 cl:25.60194673144411

filename: 2_hidden Epoch 190 loss:2.561633625835234 ael:0.0016079016126603677 cl:25.600256789736516

filename: 2_hidden Epoch 191 loss:2.561731702335433 ael:0.0016052119662495578 cl:25.601264423413735

filename: 2_hidden Epoch 192 loss:2.5614791590606716 ael:0.001604875362127627 cl:25.598742380033777

filename: 2_hidden Epoch 193 loss:2.5609451552339118 ael:0.0015834807528710669 cl:25.59361627671192

filename: 2_hidden Epoch 194 loss:2.5610679561402683 ael:0.0015850621170056666 cl:25.59482844927438

filename: 2_hidden Epoch 195 loss:2.5604963337568947 ael:0.0015838657224037807 cl:25.58912421671093

filename: 2_hidden Epoch 196 loss:2.5607975736340673 ael:0.0015741046474719023 cl:25.592234225704026

filename: 2_hidden Epoch 197 loss:2.559843202895707 ael:0.001557936101651236 cl:25.58285222490129

filename: 2_hidden Epoch 198 loss:2.560470582338809 ael:0.0015553780391094464 cl:25.58915153539944

filename: 2_hidden Epoch 199 loss:2.559965119113614 ael:0.0015376448152632242 cl:25.584274284572817

filename: 2_hidden Epoch 200 loss:2.560283752774707 ael:0.0015417159192084614 cl:25.58741983862283

filename: 2_hidden Epoch 201 loss:2.5597624002567385 ael:0.0015175599283292133 cl:25.582447944609154

filename: 2_hidden Epoch 202 loss:2.558474602919007 ael:0.0015124969034542662 cl:25.569620567335473

filename: 2_hidden Epoch 203 loss:2.5593238957694444 ael:0.0015099533719795393 cl:25.578138956404388

filename: 2_hidden Epoch 204 loss:2.5592109927297853 ael:0.0014928006800274765 cl:25.57718145483486

filename: 2_hidden Epoch 205 loss:2.5598196270649907 ael:0.001491166189907064 cl:25.58328414805131

filename: 2_hidden Epoch 206 loss:2.5587358346319284 ael:0.001480985971902403 cl:25.572547986220627

filename: 2_hidden Epoch 207 loss:2.5584902353161185 ael:0.0014705414313594194 cl:25.570196450220333

filename: 2_hidden Epoch 208 loss:2.5588944457663096 ael:0.0014717504472527786 cl:25.574226492397234

filename: 2_hidden Epoch 209 loss:2.5587326047093764 ael:0.0014593875378271079 cl:25.572731672112347

filename: 2_hidden Epoch 210 loss:2.5594733405584065 ael:0.0014501463229519124 cl:25.58023148336359

filename: 2_hidden Epoch 211 loss:2.558997362334881 ael:0.001435521213209729 cl:25.57561793575595

filename: 2_hidden Epoch 212 loss:2.558712447210388 ael:0.0014360455462865405 cl:25.572763553142263

filename: 2_hidden Epoch 213 loss:2.556987612993684 ael:0.0014241224028103785 cl:25.55563441641241

filename: 2_hidden Epoch 214 loss:2.5572152946752964 ael:0.0014185233551161425 cl:25.557967228778175

filename: 2_hidden Epoch 215 loss:2.5572243124193093 ael:0.0014127346605751084 cl:25.55811528857064

filename: 2_hidden Epoch 216 loss:2.5569663850366533 ael:0.0014181420692818976 cl:25.55548194494881

filename: 2_hidden Epoch 217 loss:2.557154010684814 ael:0.0014126037860314018 cl:25.557413624547184

filename: 2_hidden Epoch 218 loss:2.557064833504079 ael:0.001393265090778276 cl:25.55671520164668

filename: 2_hidden Epoch 219 loss:2.5561969616254743 ael:0.0013876798838625853 cl:25.548092342721425

filename: 2_hidden Epoch 220 loss:2.556158048674277 ael:0.001382978415629564 cl:25.54775021962246

filename: 2_hidden Epoch 221 loss:2.556774021336449 ael:0.001381029802781264 cl:25.553929429936023

filename: 2_hidden Epoch 222 loss:2.5556814602076257 ael:0.0013758366361834758 cl:25.543055775206934

filename: 2_hidden Epoch 223 loss:2.555178898597891 ael:0.0013711810285159465 cl:25.538076716365392

filename: 2_hidden Epoch 224 loss:2.556064755812439 ael:0.0013727708346249993 cl:25.54691937695999

filename: 2_hidden Epoch 225 loss:2.5555634524992024 ael:0.0013753060660739377 cl:25.541880996836507

filename: 2_hidden Epoch 226 loss:2.5551795632735046 ael:0.0013678716934019369 cl:25.538116433390737

filename: 2_hidden Epoch 227 loss:2.5556316081811254 ael:0.0013552651187132727 cl:25.542762924710267

filename: 2_hidden Epoch 228 loss:2.5555618908646434 ael:0.0013613752385878402 cl:25.542004666879176

filename: 2_hidden Epoch 229 loss:2.5544119270742476 ael:0.0013468202826274946 cl:25.530650588582905

filename: 2_hidden Epoch 230 loss:2.5547484415580524 ael:0.0013634508750780432 cl:25.533849396582923

filename: 2_hidden Epoch 231 loss:2.554759268558075 ael:0.0013391653277747108 cl:25.534200607838564

filename: 2_hidden Epoch 232 loss:2.5552308084292727 ael:0.0013431963870786175 cl:25.538875622067316

filename: 2_hidden Epoch 233 loss:2.554610766385716 ael:0.0013398041234125692 cl:25.53270912912347

filename: 2_hidden Epoch 234 loss:2.5539803978642044 ael:0.0013473803163507484 cl:25.526329694002563

filename: 2_hidden Epoch 235 loss:2.554742453770321 ael:0.001329567678479499 cl:25.534128372288265

filename: 2_hidden Epoch 236 loss:2.554664952964714 ael:0.0013332581935671423 cl:25.53331646785131

filename: 2_hidden Epoch 237 loss:2.553791160714762 ael:0.0013220552053214187 cl:25.524690595520678

filename: 2_hidden Epoch 238 loss:2.5530066341072555 ael:0.0013258384465888412 cl:25.51680747967577

filename: 2_hidden Epoch 239 loss:2.5535780234938965 ael:0.0013335632784496926 cl:25.52244412463843

filename: 2_hidden Epoch 240 loss:2.5535510086428257 ael:0.001315189877134552 cl:25.522357715239146

filename: 2_hidden Epoch 241 loss:2.5533005126859525 ael:0.0013258630693176753 cl:25.51974600136173

filename: 2_hidden Epoch 242 loss:2.5530563592197364 ael:0.0013180593800795656 cl:25.51738255955658

filename: 2_hidden Epoch 243 loss:2.5527412409842336 ael:0.00132354847855327 cl:25.514176491418333

filename: 2_hidden Epoch 244 loss:2.552513341215968 ael:0.0013151515929179154 cl:25.51198142192665

filename: 2_hidden Epoch 245 loss:2.552255216934665 ael:0.0013152150386935497 cl:25.50939953505529

filename: 2_hidden Epoch 246 loss:2.5520745103477647 ael:0.0013086283156583626 cl:25.507658358036867

filename: 2_hidden Epoch 247 loss:2.55184049730455 ael:0.001315985256692457 cl:25.505244656853304

filename: 2_hidden Epoch 248 loss:2.551301260539545 ael:0.0012959139486721854 cl:25.500052957745957

filename: 2_hidden Epoch 249 loss:2.5524110187676623 ael:0.0013034637670434246 cl:25.511075043806695

filename: 2_hidden Epoch 250 loss:2.551321993396355 ael:0.0013044839533137014 cl:25.500174637685486

/tmp/ipykernel_776206/775940180.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
/tmp/ipykernel_776206/775940180.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3         4         5  Label
0       -0.089919 -0.096427 -0.090080 -0.072012 -0.072005 -0.073633      0
1       -0.091263 -0.069573 -0.075672 -0.081091 -0.104401 -0.079564      1
2       -0.053573 -0.068667 -0.080397 -0.082585 -0.075255 -0.058829      3
3       -0.087867 -0.095344 -0.088023 -0.068918 -0.074882 -0.071806      0
4       -0.090250 -0.076230 -0.083614 -0.122893 -0.057831 -0.100551      5
...           ...       ...       ...       ...       ...       ...    ...
1711088 -0.091318 -0.069574 -0.075687 -0.081129 -0.104440 -0.079540      1
1711089 -0.053577 -0.068670 -0.080398 -0.082580 -0.075260 -0.058825      3
1711090 -0.053580 -0.068673 -0.080399 -0.082575 -0.075265 -0.058822      3
1711091 -0.091233 -0.069572 -0.075664 -0.081070 -0.104380 -0.079577      1
1711092 -0.053866 -0.068890 -0.080481 -0.082168 -0.075654 -0.058574      3

[1711093 rows x 7 columns]

Davies-Bouldin Score: 0.723211801292227

               0         1         2         3         4         5  Label
0      -0.095232 -0.116997 -0.092246 -0.035714 -0.081262 -0.062000      2
1      -0.053561 -0.068658 -0.080394 -0.082605 -0.075235 -0.058841      3
2      -0.091553 -0.099775 -0.089056 -0.068791 -0.073355 -0.072392      0
3      -0.066241 -0.076682 -0.062796 -0.058205 -0.072155 -0.111649      4
4      -0.090403 -0.099144 -0.089511 -0.069095 -0.073257 -0.072288      0
...          ...       ...       ...       ...       ...       ...    ...
519951 -0.089577 -0.097037 -0.088007 -0.071075 -0.073065 -0.073324      0
519952 -0.090053 -0.077536 -0.082630 -0.121387 -0.058328 -0.101108      5
519953 -0.091304 -0.069574 -0.075683 -0.081120 -0.104430 -0.079546      1
519954 -0.089782 -0.096598 -0.089365 -0.071380 -0.071588 -0.072641      0
519955 -0.067050 -0.077018 -0.063796 -0.057187 -0.071848 -0.112569      4

[519956 rows x 7 columns]

               0         1         2         3         4         5  Label
0      -0.091269 -0.069573 -0.075673 -0.081095 -0.104405 -0.079561      1
1      -0.095450 -0.117289 -0.092246 -0.035487 -0.081220 -0.062447      2
2      -0.089952 -0.099437 -0.089079 -0.067146 -0.072995 -0.069843      0
3      -0.089982 -0.098973 -0.088248 -0.067915 -0.072353 -0.072656      0
4      -0.090903 -0.069362 -0.074746 -0.081843 -0.105543 -0.079578      1
...          ...       ...       ...       ...       ...       ...    ...
649942 -0.090272 -0.098792 -0.089353 -0.069344 -0.073223 -0.072355      0
649943 -0.090843 -0.069088 -0.074701 -0.082195 -0.105493 -0.079393      1
649944 -0.090888 -0.069198 -0.074736 -0.082076 -0.105544 -0.079398      1
649945 -0.067365 -0.078022 -0.063194 -0.057313 -0.072076 -0.111074      4
649946 -0.054411 -0.068578 -0.079311 -0.083075 -0.076395 -0.059655      3

[649947 rows x 7 columns]