In [1]:
import torch
from torch import nn, optim
import torch.nn.functional as F
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.decomposition import PCA
from scipy.stats import chi2
from sklearn.mixture import GaussianMixture
from collections import deque, defaultdict

# CAE

In [2]:
train = pd.read_csv('../../train_CADE_cod.csv')
val = pd.read_csv('../../val_CADE_cod.csv')
test = pd.read_csv('../../test_CADE_cod.csv')

In [3]:
classes_out = ['Infilteration','DoS attacks-SlowHTTPTest']
train = train.drop(index=train[train['Label'].isin(classes_out)].index)
val = val.drop(index=val[val['Label'].isin(classes_out)].index)
test = test.drop(index=test[test['Label'].isin(classes_out)].index)

In [4]:
train['Label'] = train['Label'].replace('FTP-BruteForce','BruteForce')
train['Label'] = train['Label'].replace('SSH-Bruteforce','BruteForce')
train['Label'] = train['Label'].replace('DoS attacks-GoldenEye','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Slowloris','DoS')
# train['Label'] = train['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Hulk','DoS')
train['Label'] = train['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
train['Label'] = train['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
train['Label'] = train['Label'].replace('DDOS attack-HOIC','DDoS')
train['Label'] = train['Label'].replace('Brute Force -Web','Web')
train['Label'] = train['Label'].replace('Brute Force -XSS','Web')
train['Label'] = train['Label'].replace('SQL Injection','Web')


val['Label'] = val['Label'].replace('FTP-BruteForce','BruteForce')
val['Label'] = val['Label'].replace('SSH-Bruteforce','BruteForce')
val['Label'] = val['Label'].replace('DoS attacks-GoldenEye','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Slowloris','DoS')
# val['Label'] = val['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Hulk','DoS')
val['Label'] = val['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
val['Label'] = val['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
val['Label'] = val['Label'].replace('DDOS attack-HOIC','DDoS')
val['Label'] = val['Label'].replace('Brute Force -Web','Web')
val['Label'] = val['Label'].replace('Brute Force -XSS','Web')
val['Label'] = val['Label'].replace('SQL Injection','Web')


test['Label'] = test['Label'].replace('FTP-BruteForce','BruteForce')
test['Label'] = test['Label'].replace('SSH-Bruteforce','BruteForce')
test['Label'] = test['Label'].replace('DoS attacks-GoldenEye','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Slowloris','DoS')
# test['Label'] = test['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Hulk','DoS')
test['Label'] = test['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
test['Label'] = test['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
test['Label'] = test['Label'].replace('DDOS attack-HOIC','DDoS')
test['Label'] = test['Label'].replace('Brute Force -Web','Web')
test['Label'] = test['Label'].replace('Brute Force -XSS','Web')
test['Label'] = test['Label'].replace('SQL Injection','Web')

In [5]:
labels_str = [i for i in train['Label'].value_counts().index]
print(labels_str)

for i, l in enumerate(labels_str):
    train['Label'] = train['Label'].replace(l, i)
    val['Label'] = val['Label'].replace(l, i)
    test['Label'] = test['Label'].replace(l, i)

['DDoS', 'Benign', 'DoS', 'BruteForce', 'Bot', 'Web']

/tmp/ipykernel_336185/2307520911.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train['Label'] = train['Label'].replace(l, i)
/tmp/ipykernel_336185/2307520911.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  val['Label'] = val['Label'].replace(l, i)
/tmp/ipykernel_336185/2307520911.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['Label'] = test['Label'].replace(l, i)

# CAE CADE (margin 10 e lambda 0.1)

In [6]:
def pick_pair(embeddings, labels, pick_embeddings, pick_labels):
    """
    Gera todos os pares entre embeddings e pick_embeddings,
    com labels_pair indicando se os pares são positivos (0) ou negativos (1).
    """
    N, D = embeddings.shape
    M = pick_embeddings.shape[0]

    # Expande para todas as combinações possíveis
    A = embeddings.unsqueeze(0).expand(M, N, D).reshape(M * N, D)
    B = pick_embeddings.unsqueeze(1).expand(M, N, D).reshape(M * N, D)

    labels_exp = labels.unsqueeze(0).expand(M, N)
    pick_labels_exp = pick_labels.unsqueeze(1).expand(M, N)
    labels_pair = (labels_exp != pick_labels_exp).reshape(-1).float()

    return A, B, labels_pair

def ContrastiveLoss(input1, input2, y, margin=1.0):
    # y = 0 quando input1 e input2 são da mesma classe e y = 1 caso contrário
    diff = input1 - input2
    dist_sq = torch.sum(torch.pow(diff,2),1)
    dist = torch.sqrt(dist_sq + 1e-10) # Soma 1e-10 pois se o sqrt der 0 o gradiente da NaN
    mdist = margin - dist
    mdist = F.relu(mdist)
    loss = ((1-y) * dist * dist) + (y * mdist * mdist)
    return torch.mean(loss)

def AEContrastive(input, output, embeddings, labels, pick_encoded, pick_labels, margin=1.0, lambda1=1.0):
    mseloss = nn.MSELoss()
    ae_loss = mseloss(input,output)

    A, B, labels_pair = pick_pair(embeddings, labels, pick_encoded, pick_labels)
    contrastive_loss = ContrastiveLoss(A, B, labels_pair, margin=margin)
    return ae_loss + contrastive_loss * lambda1, ae_loss, contrastive_loss

In [7]:
class contrastive_ae(nn.Module):
    def __init__(self, input_neurons, neurons):
        super().__init__()
        self.encoder0 = nn.Linear(input_neurons,64)
        self.encoder1 = nn.Linear(64,32)
        self.encoder2 = nn.Linear(32,16)
        self.encoder3 = nn.Linear(16,neurons)

        self.decoder0 = nn.Linear(neurons,16)
        self.decoder1 = nn.Linear(16,32)
        self.decoder2 = nn.Linear(32,64)
        self.decoder3 = nn.Linear(64,input_neurons)

        self.activation0 = nn.ReLU()
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X)
        encoded = X
        X = self.activation0(self.decoder0(X))
        X = self.activation0(self.decoder1(X))
        X = self.activation0(self.decoder2(X))
        X = self.decoder3(X)


        return X, encoded

In [8]:
class encoder(nn.Module):
    def __init__(self, model):
        super().__init__()
        self.encoder0 = list(model.children())[0]
        self.encoder1 = list(model.children())[1]
        self.encoder2 = list(model.children())[2]
        self.encoder3 = list(model.children())[3]
        self.activation0 = list(model.children())[8]
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X)
        return X

In [9]:
from torch.utils.data import Dataset, DataLoader,TensorDataset
import random
def build_class_reference_batches(X_train, y_train, batch_size=512):
    classes = torch.unique(y_train).tolist()
    n_classes = len(classes)
    total_samples = len(X_train)
    dataset = TensorDataset(X_train, y_train)
    train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    

    print(classes)

    # Mapeia cada classe para seus índices
    class_to_indices = {
        int(cls.item()): (y_train == cls).nonzero(as_tuple=True)[0].tolist()
        for cls in torch.unique(y_train)
    }

    reference_list = []
    total_batches = len(train_loader)

    for batch_idx in range(total_batches):
        start = batch_idx * batch_size
        end = min(start + batch_size, total_samples)
        batch_indices = set(range(start, end))

        class_samples = []
        for cls in classes:
            candidates = [i for i in class_to_indices[cls] if i not in batch_indices]
            if not candidates:
                raise ValueError(f"Classe {cls} não possui amostras fora do batch {batch_idx}")
            chosen = candidates[torch.randint(len(candidates), (1,)).item()]
            class_samples.append(chosen)

        reference_list.append(class_samples)


    return train_loader, reference_list

In [10]:
def normalize(t):
    t_norm = (t - t.mean()) / t.std()
    return t_norm

In [11]:
array_hidden_classes = [[0,2],[0,3],[0,4],[0,5],[2,3],[2,4],[2,5],[3,4],[3,5],[4,5]]
filenames = ['0_2','0_3','0_4','0_5','2_3','2_4','2_5','3_4','3_5','4_5']
# array_hidden_classes = [[0]]
# filenames = ['0']
total_classes = len(labels_str)
for i in range(len(array_hidden_classes)):
    filename = f'{filenames[i]}_hidden'
    print(filename)
    hidden_classes = array_hidden_classes[i] #Classes ocultas do treinamento

    hidden_classes_index = list(train[train['Label'].isin(hidden_classes)].index)

    train_hidden = train.loc[hidden_classes_index]

    train_not_hidden = train.drop(hidden_classes_index)

    X_train = train_not_hidden.drop(columns=['Label'])
    y_train = train_not_hidden['Label']
    X_val = val.drop(columns=['Label'])
    y_val = val['Label'].values
    X_test = test.drop(columns=['Label'])
    y_test = test['Label'].values

    torch.manual_seed(123)
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(device)
    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_loader, pick_list = build_class_reference_batches(X_train,y_train, batch_size=512)
    pick_samples = []
    pick_labels = []
    for l in pick_list:
        pick_samples.append(X_train[l])
        pick_labels.append(y_train[l])

    pick_samples = torch.stack(pick_samples)    
    pick_labels = torch.stack(pick_labels)

    print('pick completo')

    neurons = total_classes - len(hidden_classes)
    print(f'{X_train.shape[1]} {neurons}')
    model = contrastive_ae(input_neurons=X_train.shape[1],neurons=neurons)
    model.to(device)

    learning_rate = 0.0001
    opt = optim.Adam(model.parameters(),lr=learning_rate)
    margin = 10 # Parametro de afastamento das classes
    cae_lambda_1 = 0.1 # Parametro de influencia na distancia das classes
    
    
    for epoch in range(250):
        running_loss = 0
        running_ael = 0
        running_cl = 0
        contador = 0
        for data in train_loader:
            inputs, labels = data
            inputs = inputs.to(device)
            labels = labels.to(device)
            ps = pick_samples[contador]
            pl = pick_labels[contador]
            ps = ps.to(device)
            pl = pl.to(device)
            contador += 1
            #print(f'{contador}/{len(train_loader)}')
            opt.zero_grad()
            outputs, encoded = model(inputs)
            _, pick_encoded = model(ps)
            tam_pe = pick_encoded.shape[0]
            enc_total = torch.cat((encoded,pick_encoded), dim=0)
            enc_total_norm = normalize(enc_total)
            encoded_norm = enc_total_norm[:-tam_pe]
            pick_encoded_norm = enc_total_norm[-tam_pe:]
            loss, ael, cl = AEContrastive(input=inputs, output=outputs, embeddings = encoded_norm, labels=labels, pick_encoded = pick_encoded_norm, pick_labels = pl, margin=margin, lambda1=cae_lambda_1)
            #loss = dummyMSELoss(inputs,outputs)
            loss.backward()
            opt.step()
            running_loss += loss.item()
            running_ael += ael.item()
            running_cl += cl.item()
            #print(f'loss = {loss.item()} batch_size = {size}')
        print(f'filename: {filename} Epoch {epoch+1} loss:{running_loss/len(train_loader)} ael:{running_ael/len(train_loader)} cl:{running_cl/len(train_loader)}')

    model_e = encoder(model=model)
    model_e.to(device)

    model_e.eval()

    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_encoded = model_e(X_train.to(device))

    train_encoded = train_encoded.detach().cpu().numpy()

    train_encoded_df = pd.DataFrame(train_encoded)
    train_encoded_df['Label'] = y_train.detach().cpu().numpy().astype(int)
    display(train_encoded_df)

    score = davies_bouldin_score(train_encoded_df.drop(columns=['Label']), train_encoded_df['Label'])
    print("Davies-Bouldin Score:", score)

    X_val = torch.tensor(np.array(X_val), dtype=torch.float)

    val_encoded = model_e(X_val.to(device))

    val_encoded = val_encoded.detach().cpu().numpy()

    val_encoded_df = pd.DataFrame(val_encoded)

    val_encoded_df['Label'] = y_val

    display(val_encoded_df)

    X_test = torch.tensor(np.array(X_test), dtype=torch.float)

    test_encoded = model_e(X_test.to(device))

    test_encoded = test_encoded.detach().cpu().numpy()

    test_encoded_df = pd.DataFrame(test_encoded)

    test_encoded_df['Label'] = y_test

    display(test_encoded_df)

    train_encoded_df.to_csv(f'train_encoded_CADE_cod_joined_attacks_pick_class_squared_normalized_2_hidden_{filename}.csv',index=False)
    val_encoded_df.to_csv(f'val_encoded_CADE_cod_joined_attacks_pick_class_squared_normalized_2_hidden_{filename}.csv',index=False)
    test_encoded_df.to_csv(f'test_encoded_CADE_cod_joined_attacks_pick_class_squared_normalized_2_hidden_{filename}.csv',index=False)

0_2_hidden

cuda
[1.0, 3.0, 4.0, 5.0]

pick completo
82 4

filename: 0_2_hidden Epoch 1 loss:3.650869241097699 ael:0.034645244148154945 cl:36.16223941263945

filename: 0_2_hidden Epoch 2 loss:2.9987848297409387 ael:0.020247758696179674 cl:29.785370207869487

filename: 0_2_hidden Epoch 3 loss:2.935417018312475 ael:0.02024504954562239 cl:29.151719216678455

filename: 0_2_hidden Epoch 4 loss:2.899010161925917 ael:0.020238490130387893 cl:28.78771623943163

filename: 0_2_hidden Epoch 5 loss:2.870725783381773 ael:0.020225754033004785 cl:28.504999862546505

filename: 0_2_hidden Epoch 6 loss:2.840805353289065 ael:0.020200505974176136 cl:28.20604798897453

filename: 0_2_hidden Epoch 7 loss:2.8030549494468646 ael:0.020132094890932026 cl:27.829228065324866

filename: 0_2_hidden Epoch 8 loss:2.769958095576452 ael:0.019865873181666046 cl:27.50092174799546

filename: 0_2_hidden Epoch 9 loss:2.7413915956797807 ael:0.01928830626319446 cl:27.221032417338826

filename: 0_2_hidden Epoch 10 loss:2.718197511266107 ael:0.01869522920080825 cl:26.99502235184545

filename: 0_2_hidden Epoch 11 loss:2.6988926801344624 ael:0.018445867265615125 cl:26.80446760550789

filename: 0_2_hidden Epoch 12 loss:2.68262056650027 ael:0.01838337640359026 cl:26.642371386030447

filename: 0_2_hidden Epoch 13 loss:2.6698933254765427 ael:0.018354177848516923 cl:26.515391010823457

filename: 0_2_hidden Epoch 14 loss:2.6581677188691883 ael:0.01834275699119367 cl:26.39824914206629

filename: 0_2_hidden Epoch 15 loss:2.6482425241366676 ael:0.018333664230759376 cl:26.29908809558205

filename: 0_2_hidden Epoch 16 loss:2.639654621222745 ael:0.018313704327801647 cl:26.213408708572388

filename: 0_2_hidden Epoch 17 loss:2.6294521324660467 ael:0.018277883532700007 cl:26.111741995811464

filename: 0_2_hidden Epoch 18 loss:2.6220695283101954 ael:0.01822804261363395 cl:26.03841435701951

filename: 0_2_hidden Epoch 19 loss:2.613290241619815 ael:0.018178287012826488 cl:25.951119093272997

filename: 0_2_hidden Epoch 20 loss:2.6070143070557843 ael:0.018095704933385488 cl:25.889185539535855

filename: 0_2_hidden Epoch 21 loss:2.601333936465823 ael:0.01797730967645412 cl:25.833565787647082

filename: 0_2_hidden Epoch 22 loss:2.5958316348817037 ael:0.017814936468620663 cl:25.780166519206503

filename: 0_2_hidden Epoch 23 loss:2.5912058352776195 ael:0.017606741359011958 cl:25.735990478681483

filename: 0_2_hidden Epoch 24 loss:2.5858980279901753 ael:0.017401495058615893 cl:25.68496484445489

filename: 0_2_hidden Epoch 25 loss:2.582299196590548 ael:0.0172657394680478 cl:25.650334086625474

filename: 0_2_hidden Epoch 26 loss:2.5787008746810582 ael:0.017180802817861347 cl:25.615200270777162

filename: 0_2_hidden Epoch 27 loss:2.5749533426502476 ael:0.01711247182937096 cl:25.578408241271973

filename: 0_2_hidden Epoch 28 loss:2.5695094093032504 ael:0.01704081198119599 cl:25.524685428453527

filename: 0_2_hidden Epoch 29 loss:2.5654782431929006 ael:0.016939374451201573 cl:25.485388214691824

filename: 0_2_hidden Epoch 30 loss:2.5620160739059035 ael:0.01680659894710002 cl:25.452094261542612

filename: 0_2_hidden Epoch 31 loss:2.5598696794846783 ael:0.01664969568727943 cl:25.432199368269547

filename: 0_2_hidden Epoch 32 loss:2.554466122907141 ael:0.016473731581810053 cl:25.379923430733058

filename: 0_2_hidden Epoch 33 loss:2.5510505970405495 ael:0.016259055138241663 cl:25.347914976659027

filename: 0_2_hidden Epoch 34 loss:2.548480772777744 ael:0.016028038612263196 cl:25.324526901867078

filename: 0_2_hidden Epoch 35 loss:2.5454905795014424 ael:0.015769529334046756 cl:25.297210021640943

filename: 0_2_hidden Epoch 36 loss:2.542361261728017 ael:0.015483875523078377 cl:25.268773414777673

filename: 0_2_hidden Epoch 37 loss:2.539864117814147 ael:0.015211275638506303 cl:25.246527973465298

filename: 0_2_hidden Epoch 38 loss:2.5373970703586286 ael:0.015049779034503129 cl:25.223472418992415

filename: 0_2_hidden Epoch 39 loss:2.5333199804891713 ael:0.014927231797280357 cl:25.183927011489867

filename: 0_2_hidden Epoch 40 loss:2.532608951628208 ael:0.014882185689740531 cl:25.1772672134897

filename: 0_2_hidden Epoch 41 loss:2.527443500187086 ael:0.01482961959934429 cl:25.126138344018354

filename: 0_2_hidden Epoch 42 loss:2.5257066364521568 ael:0.014785550581797471 cl:25.109210415508436

filename: 0_2_hidden Epoch 43 loss:2.5226054154012516 ael:0.014762419562928541 cl:25.078429501989614

filename: 0_2_hidden Epoch 44 loss:2.5208190187163977 ael:0.014745190776580864 cl:25.06073781511058

filename: 0_2_hidden Epoch 45 loss:2.5172647550702094 ael:0.014724650665732992 cl:25.025400580530583

filename: 0_2_hidden Epoch 46 loss:2.5155935729975285 ael:0.01464006327872124 cl:25.00953463056813

filename: 0_2_hidden Epoch 47 loss:2.513635381537935 ael:0.014664127775366702 cl:24.98971204239389

filename: 0_2_hidden Epoch 48 loss:2.512082618151022 ael:0.014629061072659882 cl:24.974535110722417

filename: 0_2_hidden Epoch 49 loss:2.511175157648066 ael:0.014589335955173264 cl:24.965857727631278

filename: 0_2_hidden Epoch 50 loss:2.5078029973351437 ael:0.01452831568085062 cl:24.932746320185455

filename: 0_2_hidden Epoch 51 loss:2.506938198079234 ael:0.014519117339817889 cl:24.924190330505372

filename: 0_2_hidden Epoch 52 loss:2.5049502929915555 ael:0.014463197521399707 cl:24.904870481076447

filename: 0_2_hidden Epoch 53 loss:2.5058074970608173 ael:0.01443392505828777 cl:24.91373522799948

filename: 0_2_hidden Epoch 54 loss:2.5038233667612078 ael:0.014416141671877679 cl:24.89407181739807

filename: 0_2_hidden Epoch 55 loss:2.503039453405401 ael:0.014399134566116592 cl:24.886402736539427

filename: 0_2_hidden Epoch 56 loss:2.500607638320197 ael:0.014257066641205355 cl:24.86350525358449

filename: 0_2_hidden Epoch 57 loss:2.4985861931806026 ael:0.014247533987762163 cl:24.84338614836983

filename: 0_2_hidden Epoch 58 loss:2.4972964455899986 ael:0.01416788331091242 cl:24.831285160520803

filename: 0_2_hidden Epoch 59 loss:2.496581885153833 ael:0.014119134376169708 cl:24.824627045963123

filename: 0_2_hidden Epoch 60 loss:2.4972656150874886 ael:0.014074787622540379 cl:24.831907822774806

filename: 0_2_hidden Epoch 61 loss:2.4933604398499365 ael:0.014005167015484007 cl:24.793552271179532

filename: 0_2_hidden Epoch 62 loss:2.493042606504067 ael:0.013971641141435374 cl:24.79070917419765

filename: 0_2_hidden Epoch 63 loss:2.493902928414552 ael:0.013990519191745831 cl:24.799123612694117

filename: 0_2_hidden Epoch 64 loss:2.49137353391751 ael:0.013913330495478991 cl:24.774601546577784

filename: 0_2_hidden Epoch 65 loss:2.4901365346234776 ael:0.01386085166140338 cl:24.76275636527849

filename: 0_2_hidden Epoch 66 loss:2.4887794942959496 ael:0.013795900274493286 cl:24.749835490143816

filename: 0_2_hidden Epoch 67 loss:2.488162526747455 ael:0.013804927286590734 cl:24.74357550766157

filename: 0_2_hidden Epoch 68 loss:2.4867230622016865 ael:0.013761257665717732 cl:24.729617586343185

filename: 0_2_hidden Epoch 69 loss:2.4853676613906157 ael:0.013766691505240843 cl:24.716009242638297

filename: 0_2_hidden Epoch 70 loss:2.4838847641711648 ael:0.013794605093299533 cl:24.700901110275932

filename: 0_2_hidden Epoch 71 loss:2.4827581050603285 ael:0.013717493593044902 cl:24.69040568185889

filename: 0_2_hidden Epoch 72 loss:2.4827460379056308 ael:0.013630103685326226 cl:24.69115886895553

filename: 0_2_hidden Epoch 73 loss:2.4802540513484375 ael:0.013554641439923612 cl:24.666993639780127

filename: 0_2_hidden Epoch 74 loss:2.4799561699447423 ael:0.013569975734951542 cl:24.663861498625383

filename: 0_2_hidden Epoch 75 loss:2.4793356232021164 ael:0.013615204638335853 cl:24.65720369608506

filename: 0_2_hidden Epoch 76 loss:2.476440483007742 ael:0.013490822730565687 cl:24.629496143175206

filename: 0_2_hidden Epoch 77 loss:2.476188242176305 ael:0.013504519461876835 cl:24.62683674356212

filename: 0_2_hidden Epoch 78 loss:2.475282772403696 ael:0.013547654476765867 cl:24.617350693370984

filename: 0_2_hidden Epoch 79 loss:2.4738438550544823 ael:0.013558380606928435 cl:24.602854276740032

filename: 0_2_hidden Epoch 80 loss:2.471468127356923 ael:0.013487488592711643 cl:24.57980592250824

filename: 0_2_hidden Epoch 81 loss:2.4719037498468936 ael:0.013548153630741265 cl:24.583555514916128

filename: 0_2_hidden Epoch 82 loss:2.469748850685099 ael:0.013550681470002494 cl:24.561981193915656

filename: 0_2_hidden Epoch 83 loss:2.4683029572600903 ael:0.0134948365213147 cl:24.548080769829127

filename: 0_2_hidden Epoch 84 loss:2.4675501735961958 ael:0.013448514209797039 cl:24.541016102873762

filename: 0_2_hidden Epoch 85 loss:2.46509856607603 ael:0.013439038333624764 cl:24.51659481421761

filename: 0_2_hidden Epoch 86 loss:2.463622927017834 ael:0.01344588384254957 cl:24.501769948005677

filename: 0_2_hidden Epoch 87 loss:2.4643053742854493 ael:0.01345777578915105 cl:24.508475530665855

filename: 0_2_hidden Epoch 88 loss:2.4610243026977 ael:0.01344481829057812 cl:24.475794361985248

filename: 0_2_hidden Epoch 89 loss:2.459787574669589 ael:0.013558248583348873 cl:24.462292796632518

filename: 0_2_hidden Epoch 90 loss:2.4570356362539787 ael:0.013612527426069035 cl:24.434230622001316

filename: 0_2_hidden Epoch 91 loss:2.4552220520118007 ael:0.013674042635070889 cl:24.415479628936104

filename: 0_2_hidden Epoch 92 loss:2.454279948382274 ael:0.013632862839807311 cl:24.4064703848051

filename: 0_2_hidden Epoch 93 loss:2.452676299214363 ael:0.013604956393069386 cl:24.390713000297545

filename: 0_2_hidden Epoch 94 loss:2.4500779588585315 ael:0.013624462873533206 cl:24.364534537688545

filename: 0_2_hidden Epoch 95 loss:2.448470830399057 ael:0.013600923254093884 cl:24.34869862743046

filename: 0_2_hidden Epoch 96 loss:2.446143729660822 ael:0.013620511959205665 cl:24.325231703467992

filename: 0_2_hidden Epoch 97 loss:2.4457487417304 ael:0.013641766786231134 cl:24.32106926233872

filename: 0_2_hidden Epoch 98 loss:2.4431220300819563 ael:0.013678363657495736 cl:24.29443620391514

filename: 0_2_hidden Epoch 99 loss:2.442202493418818 ael:0.01356300884027682 cl:24.2863943680473

filename: 0_2_hidden Epoch 100 loss:2.4401158739691193 ael:0.013565301156157384 cl:24.265505253750344

filename: 0_2_hidden Epoch 101 loss:2.438125518353089 ael:0.013592603978822412 cl:24.2453286388646

filename: 0_2_hidden Epoch 102 loss:2.4363778710365294 ael:0.013671556532220996 cl:24.22706268352011

filename: 0_2_hidden Epoch 103 loss:2.4345509144922963 ael:0.013610685136898056 cl:24.209401844895403

filename: 0_2_hidden Epoch 104 loss:2.4316418102901913 ael:0.013666443545472525 cl:24.179753184318542

filename: 0_2_hidden Epoch 105 loss:2.4307182864650434 ael:0.013823010594300602 cl:24.16895225048065

filename: 0_2_hidden Epoch 106 loss:2.4281713494788044 ael:0.013727034794915792 cl:24.144442670241645

filename: 0_2_hidden Epoch 107 loss:2.4262444089936173 ael:0.013623821124960871 cl:24.126205405981644

filename: 0_2_hidden Epoch 108 loss:2.423317383942397 ael:0.013620189992893163 cl:24.09697145068127

filename: 0_2_hidden Epoch 109 loss:2.420724712441797 ael:0.013877751497025399 cl:24.068469140840612

filename: 0_2_hidden Epoch 110 loss:2.4176757898667582 ael:0.013663888303562998 cl:24.04011852948562

filename: 0_2_hidden Epoch 111 loss:2.4170344578183216 ael:0.013806155626155923 cl:24.032282530743142

filename: 0_2_hidden Epoch 112 loss:2.4127413382996683 ael:0.013685871186949637 cl:23.990554242548736

filename: 0_2_hidden Epoch 113 loss:2.4097577534292056 ael:0.013661558748445594 cl:23.960961451737777

filename: 0_2_hidden Epoch 114 loss:2.4091742755926173 ael:0.013720018182294038 cl:23.95454207088636

filename: 0_2_hidden Epoch 115 loss:2.405872203409672 ael:0.013695337268037965 cl:23.92176817396413

filename: 0_2_hidden Epoch 116 loss:2.4034650159918742 ael:0.013664168666582554 cl:23.898007970270903

filename: 0_2_hidden Epoch 117 loss:2.4023089058373284 ael:0.013767084439851992 cl:23.885417742314544

filename: 0_2_hidden Epoch 118 loss:2.397051802277565 ael:0.013740584822675294 cl:23.833111731902413

filename: 0_2_hidden Epoch 119 loss:2.394317807905052 ael:0.01378758542249789 cl:23.80530177924944

filename: 0_2_hidden Epoch 120 loss:2.393377523124218 ael:0.013795315211071916 cl:23.79582160244817

filename: 0_2_hidden Epoch 121 loss:2.3890651064722435 ael:0.013844709656120318 cl:23.752203499752543

filename: 0_2_hidden Epoch 122 loss:2.3868711383446404 ael:0.013731092489425742 cl:23.731399991201318

filename: 0_2_hidden Epoch 123 loss:2.3870876772248226 ael:0.013708253471565473 cl:23.73379374068716

filename: 0_2_hidden Epoch 124 loss:2.386292197717273 ael:0.013758257246556004 cl:23.725338908900387

filename: 0_2_hidden Epoch 125 loss:2.3816190802532695 ael:0.013765445975688002 cl:23.67853587295698

filename: 0_2_hidden Epoch 126 loss:2.380035849304303 ael:0.013955835616418525 cl:23.660799682658652

filename: 0_2_hidden Epoch 127 loss:2.3818777700481206 ael:0.013937861260289893 cl:23.679398613390717

filename: 0_2_hidden Epoch 128 loss:2.3806068700940712 ael:0.014021073515101781 cl:23.665857458114623

filename: 0_2_hidden Epoch 129 loss:2.3699309788320377 ael:0.013690131361110379 cl:23.562407938293788

filename: 0_2_hidden Epoch 130 loss:2.3735694742073186 ael:0.013732866103679913 cl:23.59836563649385

filename: 0_2_hidden Epoch 131 loss:2.3678699810867725 ael:0.013720816994369354 cl:23.54149115500243

filename: 0_2_hidden Epoch 132 loss:2.365766138874966 ael:0.013719612838821891 cl:23.52046477380006

filename: 0_2_hidden Epoch 133 loss:2.3630115540779157 ael:0.013419840888261958 cl:23.49591668792393

filename: 0_2_hidden Epoch 134 loss:2.3645050177107687 ael:0.013469796260798594 cl:23.510351776040117

filename: 0_2_hidden Epoch 135 loss:2.3602417749555213 ael:0.013418265168413358 cl:23.46823462403339

filename: 0_2_hidden Epoch 136 loss:2.3589531571320865 ael:0.013376792275306323 cl:23.455763179322947

filename: 0_2_hidden Epoch 137 loss:2.35827070409837 ael:0.013475499978369993 cl:23.447951563544894

filename: 0_2_hidden Epoch 138 loss:2.3561794868629913 ael:0.013193371989663043 cl:23.42986066652381

filename: 0_2_hidden Epoch 139 loss:2.356043879104697 ael:0.013329884663993574 cl:23.427139438753542

filename: 0_2_hidden Epoch 140 loss:2.356584049178206 ael:0.013164056039354562 cl:23.43419943270476

filename: 0_2_hidden Epoch 141 loss:2.3594729385946107 ael:0.013187518423301695 cl:23.46285373127979

filename: 0_2_hidden Epoch 142 loss:2.356818875346495 ael:0.012987123311335303 cl:23.438317040775132

filename: 0_2_hidden Epoch 143 loss:2.3655206921307936 ael:0.0130677388530508 cl:23.524529042451277

filename: 0_2_hidden Epoch 144 loss:2.3545034321106 ael:0.012661143438384422 cl:23.418422422201736

filename: 0_2_hidden Epoch 145 loss:2.3470574450881583 ael:0.012518134367976176 cl:23.3453926594361

filename: 0_2_hidden Epoch 146 loss:2.3493892209685368 ael:0.012571003725853465 cl:23.368181672303574

filename: 0_2_hidden Epoch 147 loss:2.346106503320777 ael:0.012356474388734964 cl:23.33749978127687

filename: 0_2_hidden Epoch 148 loss:2.3471282924646917 ael:0.012405154552897844 cl:23.347230933023535

filename: 0_2_hidden Epoch 149 loss:2.349109673370486 ael:0.012401877498031472 cl:23.367077478118564

filename: 0_2_hidden Epoch 150 loss:2.347347757025905 ael:0.012228581605924537 cl:23.351191271906313

filename: 0_2_hidden Epoch 151 loss:2.3488488221298094 ael:0.011945733324239921 cl:23.36903042689614

filename: 0_2_hidden Epoch 152 loss:2.34774423526681 ael:0.012157279659953455 cl:23.355869069306745

filename: 0_2_hidden Epoch 153 loss:2.3457600175038626 ael:0.011904074531048536 cl:23.338558950631516

filename: 0_2_hidden Epoch 154 loss:2.3465962056232534 ael:0.011777062014595645 cl:23.34819099177485

filename: 0_2_hidden Epoch 155 loss:2.3420137696939967 ael:0.011745879680687642 cl:23.302678397427435

filename: 0_2_hidden Epoch 156 loss:2.343597597207712 ael:0.011767764248298077 cl:23.31829784123794

filename: 0_2_hidden Epoch 157 loss:2.3389314888612085 ael:0.011661635094787926 cl:23.272698018861853

filename: 0_2_hidden Epoch 158 loss:2.3400247431319694 ael:0.011438773156892831 cl:23.28585921785106

filename: 0_2_hidden Epoch 159 loss:2.3390176051336784 ael:0.011406464598384564 cl:23.27611090618631

filename: 0_2_hidden Epoch 160 loss:2.3409217384198437 ael:0.011519708826064902 cl:23.29401984836744

filename: 0_2_hidden Epoch 161 loss:2.339382302177989 ael:0.011406904835577892 cl:23.27975352017776

filename: 0_2_hidden Epoch 162 loss:2.3371665513385897 ael:0.011308578833552968 cl:23.258579290431477

filename: 0_2_hidden Epoch 163 loss:2.337467163282892 ael:0.011295308932439303 cl:23.26171806998875

filename: 0_2_hidden Epoch 164 loss:2.338905274738436 ael:0.011232674399228848 cl:23.276725579344706

filename: 0_2_hidden Epoch 165 loss:2.3357749136893644 ael:0.011118062526372301 cl:23.246568043335625

filename: 0_2_hidden Epoch 166 loss:2.3363295770857646 ael:0.01106960670668227 cl:23.252599251788595

filename: 0_2_hidden Epoch 167 loss:2.3362449764557507 ael:0.0109966722676409 cl:23.252482595651045

filename: 0_2_hidden Epoch 168 loss:2.334462219411912 ael:0.010969529143514355 cl:23.234926416562953

filename: 0_2_hidden Epoch 169 loss:2.3336978570274685 ael:0.01097821290706001 cl:23.22719597609147

filename: 0_2_hidden Epoch 170 loss:2.3362944766879084 ael:0.011050654872340838 cl:23.252437742896703

filename: 0_2_hidden Epoch 171 loss:2.334310433268547 ael:0.010934360814280808 cl:23.233760260499043

filename: 0_2_hidden Epoch 172 loss:2.331732063125009 ael:0.010818101013200762 cl:23.209139101401618

filename: 0_2_hidden Epoch 173 loss:2.3332780412357788 ael:0.010988969653439911 cl:23.22289020911507

filename: 0_2_hidden Epoch 174 loss:2.336970068514347 ael:0.010819579200798889 cl:23.261504405477773

filename: 0_2_hidden Epoch 175 loss:2.331718584117682 ael:0.010706417765164667 cl:23.21012118588323

filename: 0_2_hidden Epoch 176 loss:2.3306419807283776 ael:0.010655614521111483 cl:23.199863188163093

filename: 0_2_hidden Epoch 177 loss:2.3323747933558794 ael:0.010663130463343924 cl:23.217116127843443

filename: 0_2_hidden Epoch 178 loss:2.331790234990742 ael:0.010698087735648227 cl:23.210921009727148

filename: 0_2_hidden Epoch 179 loss:2.330690242868403 ael:0.010692112865027689 cl:23.199980849805087

filename: 0_2_hidden Epoch 180 loss:2.335292992643688 ael:0.010824032148609504 cl:23.244689145295517

filename: 0_2_hidden Epoch 181 loss:2.333733972971854 ael:0.010641525392218128 cl:23.230923993691153

filename: 0_2_hidden Epoch 182 loss:2.331637921670209 ael:0.010668678972465189 cl:23.20969196195188

filename: 0_2_hidden Epoch 183 loss:2.3341467773136886 ael:0.01046561188692146 cl:23.236811189029527

filename: 0_2_hidden Epoch 184 loss:2.3296768210504366 ael:0.010574721811723935 cl:23.191020509471063

filename: 0_2_hidden Epoch 185 loss:2.3269806550896686 ael:0.010465540956584331 cl:23.16515067141989

filename: 0_2_hidden Epoch 186 loss:2.332172567364962 ael:0.010433710896936448 cl:23.217388089843418

filename: 0_2_hidden Epoch 187 loss:2.328877213726873 ael:0.010350014483201844 cl:23.18527148184569

filename: 0_2_hidden Epoch 188 loss:2.3261743299987003 ael:0.010219296988646459 cl:23.159549874844757

filename: 0_2_hidden Epoch 189 loss:2.3271569307731546 ael:0.010050811368020494 cl:23.171060734209806

filename: 0_2_hidden Epoch 190 loss:2.327555175255174 ael:0.010144656023982426 cl:23.174104725796244

filename: 0_2_hidden Epoch 191 loss:2.3229786106425783 ael:0.01002282062596034 cl:23.12955743437228

filename: 0_2_hidden Epoch 192 loss:2.3237607975368912 ael:0.010132158187005426 cl:23.1362859259481

filename: 0_2_hidden Epoch 193 loss:2.324384971934816 ael:0.010031460983800176 cl:23.143534607472628

filename: 0_2_hidden Epoch 194 loss:2.324858659505844 ael:0.009992923523026073 cl:23.14865688863008

filename: 0_2_hidden Epoch 195 loss:2.32588416474021 ael:0.00993522532947321 cl:23.15948891536049

filename: 0_2_hidden Epoch 196 loss:2.3258662649470825 ael:0.009928920731434355 cl:23.15937296203945

filename: 0_2_hidden Epoch 197 loss:2.324188846608867 ael:0.009924733312800527 cl:23.142640674632528

filename: 0_2_hidden Epoch 198 loss:2.324494938617167 ael:0.009952041477663442 cl:23.145428494785143

filename: 0_2_hidden Epoch 199 loss:2.3214834608461548 ael:0.009731978277989623 cl:23.117514344920284

filename: 0_2_hidden Epoch 200 loss:2.318180859283261 ael:0.009475223932405123 cl:23.087055826187132

filename: 0_2_hidden Epoch 201 loss:2.323440459241038 ael:0.009254569759966967 cl:23.141858437786933

filename: 0_2_hidden Epoch 202 loss:2.3227913020097692 ael:0.009037333564407637 cl:23.137539204307224

filename: 0_2_hidden Epoch 203 loss:2.3196795449956604 ael:0.008926600532646736 cl:23.107528953966888

filename: 0_2_hidden Epoch 204 loss:2.317893043613952 ael:0.008616200687981251 cl:23.09276797460473

filename: 0_2_hidden Epoch 205 loss:2.318484160951946 ael:0.008456527352910083 cl:23.100275851332622

filename: 0_2_hidden Epoch 206 loss:2.3166454588589462 ael:0.008379105772853465 cl:23.082663066490838

filename: 0_2_hidden Epoch 207 loss:2.318869473623193 ael:0.008205766905777399 cl:23.10663659365281

filename: 0_2_hidden Epoch 208 loss:2.320388605283654 ael:0.00814751752869874 cl:23.122410410383473

filename: 0_2_hidden Epoch 209 loss:2.3164369875970094 ael:0.007968321258364164 cl:23.08468615905098

filename: 0_2_hidden Epoch 210 loss:2.31452042531708 ael:0.007842921224200045 cl:23.066774600485097

filename: 0_2_hidden Epoch 211 loss:2.3140917394472207 ael:0.00772257627028486 cl:23.063691119525743

filename: 0_2_hidden Epoch 212 loss:2.3146578639097837 ael:0.007668413954746464 cl:23.069894037039383

filename: 0_2_hidden Epoch 213 loss:2.314031176528205 ael:0.007555769446417285 cl:23.064753564544347

filename: 0_2_hidden Epoch 214 loss:2.313330179841622 ael:0.007484200523164042 cl:23.058459319239077

filename: 0_2_hidden Epoch 215 loss:2.3130997815209886 ael:0.007402363740434141 cl:23.05697366983994

filename: 0_2_hidden Epoch 216 loss:2.3170330676047697 ael:0.007471580751260499 cl:23.095614420849344

filename: 0_2_hidden Epoch 217 loss:2.3134707196899083 ael:0.007289695934362143 cl:23.061809746078822

filename: 0_2_hidden Epoch 218 loss:2.312622502640538 ael:0.0072124856524169445 cl:23.05409969039585

filename: 0_2_hidden Epoch 219 loss:2.3091479343564614 ael:0.007053015785008345 cl:23.020948704429294

filename: 0_2_hidden Epoch 220 loss:2.3116715119584748 ael:0.0070300976958368785 cl:23.046413678708284

filename: 0_2_hidden Epoch 221 loss:2.312387299926385 ael:0.006949656992725542 cl:23.05437595947929

filename: 0_2_hidden Epoch 222 loss:2.308642586029094 ael:0.006949470889673609 cl:23.01693065373794

filename: 0_2_hidden Epoch 223 loss:2.306380334107772 ael:0.006861975474495683 cl:22.99518311852994

filename: 0_2_hidden Epoch 224 loss:2.3125747625594553 ael:0.006831178581595178 cl:23.057435360162156

filename: 0_2_hidden Epoch 225 loss:2.3052889755886534 ael:0.006709596067009008 cl:22.985793307553166

filename: 0_2_hidden Epoch 226 loss:2.305968438607195 ael:0.006703092825710369 cl:22.992653003982877

filename: 0_2_hidden Epoch 227 loss:2.3059254433149876 ael:0.006698060852384356 cl:22.99227334520091

filename: 0_2_hidden Epoch 228 loss:2.3061527839821316 ael:0.006671589941960638 cl:22.99481145091679

filename: 0_2_hidden Epoch 229 loss:2.3053159229781315 ael:0.006587730283828695 cl:22.987281436505526

filename: 0_2_hidden Epoch 230 loss:2.3028306500419324 ael:0.006547665523375263 cl:22.96282942606055

filename: 0_2_hidden Epoch 231 loss:2.3041862561650897 ael:0.006615389304731608 cl:22.975708195437555

filename: 0_2_hidden Epoch 232 loss:2.3034164831690167 ael:0.006547603401375691 cl:22.96868829830833

filename: 0_2_hidden Epoch 233 loss:2.2996941439483476 ael:0.006468916761830611 cl:22.93225179547849

filename: 0_2_hidden Epoch 234 loss:2.3016738325357435 ael:0.006498337061012812 cl:22.951754509884378

filename: 0_2_hidden Epoch 235 loss:2.3047303907897163 ael:0.006508353207280616 cl:22.982219877450362

filename: 0_2_hidden Epoch 236 loss:2.301224207100661 ael:0.006387067887851078 cl:22.94837089828823

filename: 0_2_hidden Epoch 237 loss:2.3028665819245835 ael:0.006300961442605552 cl:22.965655735264654

filename: 0_2_hidden Epoch 238 loss:2.3038898848321128 ael:0.006429361548456971 cl:22.97460475589918

filename: 0_2_hidden Epoch 239 loss:2.3026268440096276 ael:0.0063428408157525824 cl:22.962839555740356

filename: 0_2_hidden Epoch 240 loss:2.299632089358309 ael:0.0063695450462704604 cl:22.932624967201896

filename: 0_2_hidden Epoch 241 loss:2.3009643958962482 ael:0.006283535359872748 cl:22.946808101819908

filename: 0_2_hidden Epoch 242 loss:2.2992118556214414 ael:0.006414887908360233 cl:22.92796916650689

filename: 0_2_hidden Epoch 243 loss:2.2993915868194206 ael:0.006260586303972598 cl:22.931309526899586

filename: 0_2_hidden Epoch 244 loss:2.2989339941221734 ael:0.006212681290217797 cl:22.927212650879568

filename: 0_2_hidden Epoch 245 loss:2.2961686208844183 ael:0.006276799772572501 cl:22.898917716482412

filename: 0_2_hidden Epoch 246 loss:2.2988404907610107 ael:0.006290550380388437 cl:22.925498950999717

filename: 0_2_hidden Epoch 247 loss:2.2923151719181436 ael:0.006167001621645835 cl:22.861481214606243

filename: 0_2_hidden Epoch 248 loss:2.2968570341882497 ael:0.0061862872080857174 cl:22.90670698829319

filename: 0_2_hidden Epoch 249 loss:2.294651452484338 ael:0.006099002612704087 cl:22.885524023097496

filename: 0_2_hidden Epoch 250 loss:2.2900246874793715 ael:0.006101518889393091 cl:22.83923118321792

/tmp/ipykernel_336185/680421385.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
/tmp/ipykernel_336185/680421385.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

               0         1         2         3  Label
0       0.013824  0.009989  0.003841  0.013718      1
1       0.015400  0.009737  0.003389  0.014256      1
2       0.006957  0.025654  0.017974 -0.000463      4
3       0.000981 -0.002360  0.016953  0.010507      3
4       0.001041 -0.002637  0.017255  0.012028      3
...          ...       ...       ...       ...    ...
941708  0.002049 -0.001771  0.017154  0.010940      3
941709  0.014143  0.008979  0.004348  0.012159      1
941710  0.013226  0.008582  0.004464  0.011886      1
941711  0.008082  0.025685  0.018976  0.000323      4
941712  0.001290 -0.002282  0.016988  0.011914      3

[941713 rows x 5 columns]

Davies-Bouldin Score: 4.008950035383172

               0         1         2         3  Label
0       0.021095  0.012164  0.006553  0.015589      0
1       0.005539  0.010428  0.002377  0.006976      2
2       0.014985  0.009524  0.004059  0.012941      1
3       0.002025 -0.002525  0.017786  0.011463      3
4       0.014775  0.009662  0.004154  0.013743      1
...          ...       ...       ...       ...    ...
519951  0.015165  0.010158  0.004609  0.013032      1
519952  0.010103  0.024099  0.019096  0.000473      4
519953  0.015042  0.011374  0.001796  0.012842      0
519954  0.014090  0.010044  0.003608  0.013804      1
519955  0.001290 -0.002282  0.016988  0.011914      3

[519956 rows x 5 columns]

               0         1         2         3  Label
0       0.015009  0.011362  0.001768  0.012806      0
1       0.021260  0.012149  0.006734  0.015778      0
2       0.014553  0.009046  0.004706  0.012863      1
3       0.012804  0.010194  0.005123  0.011772      1
4       0.014599  0.012460 -0.000090  0.010338      0
...          ...       ...       ...       ...    ...
649942  0.014861  0.009658  0.004047  0.013741      1
649943  0.015294  0.012256 -0.000244  0.010839      0
649944  0.015062  0.012395 -0.000065  0.010689      0
649945  0.002049 -0.001771  0.017154  0.010940      3
649946  0.002149  0.000079  0.012812  0.008873      2

[649947 rows x 5 columns]

0_3_hidden

cuda
[1.0, 2.0, 4.0, 5.0]

pick completo
82 4

filename: 0_3_hidden Epoch 1 loss:3.6011383613069436 ael:0.030577330909925548 cl:35.70560971836457

filename: 0_3_hidden Epoch 2 loss:2.930873074933077 ael:0.018257322351345685 cl:29.12615704025626

filename: 0_3_hidden Epoch 3 loss:2.854392907960414 ael:0.018243030358642325 cl:28.36149829338009

filename: 0_3_hidden Epoch 4 loss:2.808378073250885 ael:0.018188426162496277 cl:27.90189597733768

filename: 0_3_hidden Epoch 5 loss:2.7682140874933947 ael:0.01776269647257062 cl:27.504513430250896

filename: 0_3_hidden Epoch 6 loss:2.732435645543941 ael:0.01643768313893511 cl:27.159979173539583

filename: 0_3_hidden Epoch 7 loss:2.6996043872405595 ael:0.01576135390334659 cl:26.83842984300736

filename: 0_3_hidden Epoch 8 loss:2.670131458829871 ael:0.015576324109164381 cl:26.545550860037658

filename: 0_3_hidden Epoch 9 loss:2.6424281934511025 ael:0.015492530823158547 cl:26.269356168320243

filename: 0_3_hidden Epoch 10 loss:2.6210455056381985 ael:0.015400036024212778 cl:26.056454242731007

filename: 0_3_hidden Epoch 11 loss:2.6055683091795143 ael:0.01530980923703552 cl:25.90258455300248

filename: 0_3_hidden Epoch 12 loss:2.5923392422827667 ael:0.015236072323466483 cl:25.77103120055909

filename: 0_3_hidden Epoch 13 loss:2.5820043391117005 ael:0.015154686576849676 cl:25.668496073450566

filename: 0_3_hidden Epoch 14 loss:2.574429812749702 ael:0.015054411463175892 cl:25.59375353244388

filename: 0_3_hidden Epoch 15 loss:2.5666798799858794 ael:0.014968144572346912 cl:25.517116848841553

filename: 0_3_hidden Epoch 16 loss:2.560342690097674 ael:0.014878372222326202 cl:25.45464269450843

filename: 0_3_hidden Epoch 17 loss:2.555097062075738 ael:0.014772071747186324 cl:25.403249364262738

filename: 0_3_hidden Epoch 18 loss:2.549312461414442 ael:0.014686710751087854 cl:25.346257045842783

filename: 0_3_hidden Epoch 19 loss:2.5455880014826304 ael:0.014597861994638868 cl:25.309900922447397

filename: 0_3_hidden Epoch 20 loss:2.5409668507003405 ael:0.014496147216357547 cl:25.26470653513028

filename: 0_3_hidden Epoch 21 loss:2.538059486045609 ael:0.01432855513158445 cl:25.237308845272928

filename: 0_3_hidden Epoch 22 loss:2.534124540819359 ael:0.014202818973337944 cl:25.19921674191447

filename: 0_3_hidden Epoch 23 loss:2.528053016999971 ael:0.014095186173273636 cl:25.139577839941186

filename: 0_3_hidden Epoch 24 loss:2.525732477446605 ael:0.013968770134698471 cl:25.11763658699374

filename: 0_3_hidden Epoch 25 loss:2.5214696653933446 ael:0.013875536938018329 cl:25.075940833973185

filename: 0_3_hidden Epoch 26 loss:2.5185435136040466 ael:0.01383550083807632 cl:25.047079673618835

filename: 0_3_hidden Epoch 27 loss:2.516036024245684 ael:0.013733362383661605 cl:25.02302614942854

filename: 0_3_hidden Epoch 28 loss:2.5178062421027025 ael:0.013619302436486666 cl:25.041868950160037

filename: 0_3_hidden Epoch 29 loss:2.5146019832970317 ael:0.013566231578736978 cl:25.010357064635347

filename: 0_3_hidden Epoch 30 loss:2.5109421636669804 ael:0.013536217194616677 cl:24.97405901511154

filename: 0_3_hidden Epoch 31 loss:2.509333303394042 ael:0.01345955301865037 cl:24.9587370117446

filename: 0_3_hidden Epoch 32 loss:2.5056346951875748 ael:0.013378651488774679 cl:24.922559961490983

filename: 0_3_hidden Epoch 33 loss:2.50374643524666 ael:0.013291192198321632 cl:24.904551957933002

filename: 0_3_hidden Epoch 34 loss:2.50007005122745 ael:0.013194999927640942 cl:24.868750037633784

filename: 0_3_hidden Epoch 35 loss:2.4991027942390422 ael:0.013128253642430665 cl:24.859744955309008

filename: 0_3_hidden Epoch 36 loss:2.496079582448141 ael:0.013071173135660807 cl:24.83008363131688

filename: 0_3_hidden Epoch 37 loss:2.4936192742496446 ael:0.013000876010280969 cl:24.806183537975972

filename: 0_3_hidden Epoch 38 loss:2.49242295871995 ael:0.012915341019274051 cl:24.79507569834315

filename: 0_3_hidden Epoch 39 loss:2.489658331954188 ael:0.012875596126314117 cl:24.76782688241606

filename: 0_3_hidden Epoch 40 loss:2.4840019334295107 ael:0.012780791765712778 cl:24.712210947444444

filename: 0_3_hidden Epoch 41 loss:2.480936429663327 ael:0.012702767414239936 cl:24.682336142957656

filename: 0_3_hidden Epoch 42 loss:2.479736968956602 ael:0.012642634577778184 cl:24.670942847266623

filename: 0_3_hidden Epoch 43 loss:2.4768756410644373 ael:0.012552512058358051 cl:24.643230816470965

filename: 0_3_hidden Epoch 44 loss:2.4770030298218777 ael:0.012536807107313629 cl:24.64466173849595

filename: 0_3_hidden Epoch 45 loss:2.4745111427440176 ael:0.012528553867260645 cl:24.61982539357032

filename: 0_3_hidden Epoch 46 loss:2.471930724682354 ael:0.012425939203994037 cl:24.595047386713034

filename: 0_3_hidden Epoch 47 loss:2.4686614867758263 ael:0.012348111031654022 cl:24.563133290114543

filename: 0_3_hidden Epoch 48 loss:2.4686317473546033 ael:0.012297285450172323 cl:24.563344158102282

filename: 0_3_hidden Epoch 49 loss:2.464950180493247 ael:0.012226029895023291 cl:24.527241064888003

filename: 0_3_hidden Epoch 50 loss:2.462025805379718 ael:0.012188118640713924 cl:24.498376412954745

filename: 0_3_hidden Epoch 51 loss:2.46169022909135 ael:0.012242891156593988 cl:24.494472880950305

filename: 0_3_hidden Epoch 52 loss:2.4584510278868095 ael:0.012184600402866957 cl:24.462663789263516

filename: 0_3_hidden Epoch 53 loss:2.4531296965015073 ael:0.012146816709587897 cl:24.409828326686675

filename: 0_3_hidden Epoch 54 loss:2.4520507712951036 ael:0.012153230734191757 cl:24.398974912345974

filename: 0_3_hidden Epoch 55 loss:2.4506856301677837 ael:0.012099905372014911 cl:24.38585678332471

filename: 0_3_hidden Epoch 56 loss:2.445088746836367 ael:0.012144980986482418 cl:24.329437195037098

filename: 0_3_hidden Epoch 57 loss:2.444603631849246 ael:0.012046553127701507 cl:24.325570329362975

filename: 0_3_hidden Epoch 58 loss:2.4393648185359345 ael:0.012071965075750878 cl:24.2729280573489

filename: 0_3_hidden Epoch 59 loss:2.440523061576505 ael:0.012081179874575607 cl:24.28441833036125

filename: 0_3_hidden Epoch 60 loss:2.434817079411969 ael:0.012104013291111946 cl:24.227130193287422

filename: 0_3_hidden Epoch 61 loss:2.4327566044569373 ael:0.012099393446223024 cl:24.206571636950727

filename: 0_3_hidden Epoch 62 loss:2.4322827649342225 ael:0.012145738832014055 cl:24.201369774537593

filename: 0_3_hidden Epoch 63 loss:2.427163135251063 ael:0.012184097690532827 cl:24.149789889059555

filename: 0_3_hidden Epoch 64 loss:2.4264173400776268 ael:0.012349328810398295 cl:24.14067967447643

filename: 0_3_hidden Epoch 65 loss:2.4196135848686358 ael:0.012059385712872439 cl:24.075541528113515

filename: 0_3_hidden Epoch 66 loss:2.4158134739613972 ael:0.012152834840891042 cl:24.03660592334331

filename: 0_3_hidden Epoch 67 loss:2.4151220807520737 ael:0.012282076671786372 cl:24.028399562978244

filename: 0_3_hidden Epoch 68 loss:2.413864563101848 ael:0.012254657921268534 cl:24.01609857461318

filename: 0_3_hidden Epoch 69 loss:2.4125927552454614 ael:0.012151809985594899 cl:24.00440897749144

filename: 0_3_hidden Epoch 70 loss:2.408225352513475 ael:0.012236759809505214 cl:23.959885411435952

filename: 0_3_hidden Epoch 71 loss:2.408983085306355 ael:0.012288700750234059 cl:23.96694338446419

filename: 0_3_hidden Epoch 72 loss:2.4048610392885537 ael:0.012098250584885678 cl:23.92762743327887

filename: 0_3_hidden Epoch 73 loss:2.4027869975204545 ael:0.012067153429455673 cl:23.90719798648304

filename: 0_3_hidden Epoch 74 loss:2.4040025973355643 ael:0.011692759786942704 cl:23.923097878471797

filename: 0_3_hidden Epoch 75 loss:2.401874347593158 ael:0.011855684941440568 cl:23.900186155706006

filename: 0_3_hidden Epoch 76 loss:2.399244863950143 ael:0.011629762462566282 cl:23.876150537024223

filename: 0_3_hidden Epoch 77 loss:2.3971465360957946 ael:0.011702477330584162 cl:23.854440096069702

filename: 0_3_hidden Epoch 78 loss:2.3969655333316084 ael:0.011660291772478692 cl:23.853051935907732

filename: 0_3_hidden Epoch 79 loss:2.3958124321494223 ael:0.011525392663207111 cl:23.842869901633346

filename: 0_3_hidden Epoch 80 loss:2.392824722868801 ael:0.011210525745742198 cl:23.81614149822545

filename: 0_3_hidden Epoch 81 loss:2.3899369602721308 ael:0.011368871753730017 cl:23.785680448706017

filename: 0_3_hidden Epoch 82 loss:2.387861872764743 ael:0.01143700840145602 cl:23.764248192696414

filename: 0_3_hidden Epoch 83 loss:2.391160280121222 ael:0.011265139581796152 cl:23.79895092613019

filename: 0_3_hidden Epoch 84 loss:2.3855862425047185 ael:0.011280853904070964 cl:23.7430533849605

filename: 0_3_hidden Epoch 85 loss:2.3836628593612086 ael:0.011067763184845507 cl:23.72595050528564

filename: 0_3_hidden Epoch 86 loss:2.382120621340989 ael:0.011099945398824364 cl:23.710206304074045

filename: 0_3_hidden Epoch 87 loss:2.3801109964240528 ael:0.01094893711829288 cl:23.691620092577285

filename: 0_3_hidden Epoch 88 loss:2.3805016484733357 ael:0.010961982345010847 cl:23.695396238021964

filename: 0_3_hidden Epoch 89 loss:2.378152943928561 ael:0.010982276478064894 cl:23.671706178263165

filename: 0_3_hidden Epoch 90 loss:2.3766368927501835 ael:0.011062845667080762 cl:23.655739962430992

filename: 0_3_hidden Epoch 91 loss:2.374730460490525 ael:0.01073185797441077 cl:23.639985522168992

filename: 0_3_hidden Epoch 92 loss:2.3745835789650545 ael:0.010735981644553054 cl:23.63847550837389

filename: 0_3_hidden Epoch 93 loss:2.3711213851723434 ael:0.010667977210293897 cl:23.604533652137867

filename: 0_3_hidden Epoch 94 loss:2.373425159516118 ael:0.010763096806881407 cl:23.626620145834792

filename: 0_3_hidden Epoch 95 loss:2.370594164299977 ael:0.010650475691367307 cl:23.599436399291626

filename: 0_3_hidden Epoch 96 loss:2.369920469007506 ael:0.010593672087402133 cl:23.593267465504947

filename: 0_3_hidden Epoch 97 loss:2.3659863040764413 ael:0.010412475258700354 cl:23.555737801909626

filename: 0_3_hidden Epoch 98 loss:2.3679514319135233 ael:0.01049143076128608 cl:23.57459951266758

filename: 0_3_hidden Epoch 99 loss:2.364911632746918 ael:0.01046022336037229 cl:23.54451363111647

filename: 0_3_hidden Epoch 100 loss:2.3629441680632604 ael:0.010362912251557886 cl:23.525812081573136

filename: 0_3_hidden Epoch 101 loss:2.3629272725965826 ael:0.010380597750544474 cl:23.525466289814872

filename: 0_3_hidden Epoch 102 loss:2.3612907927726474 ael:0.01031624783047646 cl:23.509744986290354

filename: 0_3_hidden Epoch 103 loss:2.361960759196165 ael:0.010299539723673461 cl:23.516611733125345

filename: 0_3_hidden Epoch 104 loss:2.355659961819233 ael:0.010125802001091278 cl:23.455341073013862

filename: 0_3_hidden Epoch 105 loss:2.3543062797516927 ael:0.010147552541213497 cl:23.44158676196879

filename: 0_3_hidden Epoch 106 loss:2.3579300620630717 ael:0.010173152085564434 cl:23.4775686430349

filename: 0_3_hidden Epoch 107 loss:2.35449048756484 ael:0.009926574717460949 cl:23.445638644261685

filename: 0_3_hidden Epoch 108 loss:2.3510675827068184 ael:0.00990071710116519 cl:23.41166814833538

filename: 0_3_hidden Epoch 109 loss:2.3497879468331484 ael:0.009766404986832575 cl:23.400214982614862

filename: 0_3_hidden Epoch 110 loss:2.351930031980753 ael:0.009925278510636635 cl:23.420047069106698

filename: 0_3_hidden Epoch 111 loss:2.3469907786635895 ael:0.009708934595347133 cl:23.372817939944568

filename: 0_3_hidden Epoch 112 loss:2.35252132021377 ael:0.010036433392167685 cl:23.42484842346982

filename: 0_3_hidden Epoch 113 loss:2.3476404815273733 ael:0.009690236136888948 cl:23.379501944343783

filename: 0_3_hidden Epoch 114 loss:2.3465879595451944 ael:0.009607930145424564 cl:23.369799841561008

filename: 0_3_hidden Epoch 115 loss:2.3447077960355043 ael:0.00955900400352637 cl:23.351487471918354

filename: 0_3_hidden Epoch 116 loss:2.345494848492731 ael:0.009513018315441732 cl:23.3598178346536

filename: 0_3_hidden Epoch 117 loss:2.3428019044645163 ael:0.009472367306173545 cl:23.333294907908684

filename: 0_3_hidden Epoch 118 loss:2.342611039284752 ael:0.009375956541277175 cl:23.33235037213959

filename: 0_3_hidden Epoch 119 loss:2.341336714965999 ael:0.009236347823768972 cl:23.321003187338274

filename: 0_3_hidden Epoch 120 loss:2.3446202120735804 ael:0.009266642465218567 cl:23.353535248737877

filename: 0_3_hidden Epoch 121 loss:2.339926596773639 ael:0.009070542301540878 cl:23.30856007061375

filename: 0_3_hidden Epoch 122 loss:2.341035246611473 ael:0.009132974121235144 cl:23.319022236145962

filename: 0_3_hidden Epoch 123 loss:2.339650632614037 ael:0.008925527072728319 cl:23.307250569813515

filename: 0_3_hidden Epoch 124 loss:2.3369944009486274 ael:0.008934172459910046 cl:23.280601820781804

filename: 0_3_hidden Epoch 125 loss:2.3384572320395463 ael:0.008739468852020002 cl:23.297177176482652

filename: 0_3_hidden Epoch 126 loss:2.3365803953421667 ael:0.008781177756261947 cl:23.27799168592908

filename: 0_3_hidden Epoch 127 loss:2.3361394910831383 ael:0.008736304103294281 cl:23.274031404838315

filename: 0_3_hidden Epoch 128 loss:2.3350921527746604 ael:0.0087571022117916 cl:23.263349987347446

filename: 0_3_hidden Epoch 129 loss:2.3357870129726392 ael:0.008597021033837983 cl:23.27189943382974

filename: 0_3_hidden Epoch 130 loss:2.3327280247930156 ael:0.008634644618520525 cl:23.240933306608024

filename: 0_3_hidden Epoch 131 loss:2.332826390454112 ael:0.008507334950877011 cl:23.243190089683363

filename: 0_3_hidden Epoch 132 loss:2.3290358066083665 ael:0.008489074775513854 cl:23.20546686583986

filename: 0_3_hidden Epoch 133 loss:2.330339092547821 ael:0.00842910907641944 cl:23.219099375520944

filename: 0_3_hidden Epoch 134 loss:2.328513746838933 ael:0.008287366113973958 cl:23.202263330783662

filename: 0_3_hidden Epoch 135 loss:2.326788313304481 ael:0.008329467804091795 cl:23.184587979471143

filename: 0_3_hidden Epoch 136 loss:2.3292350972179876 ael:0.008184088189637463 cl:23.210509609570238

filename: 0_3_hidden Epoch 137 loss:2.3278011059844204 ael:0.008105522108426216 cl:23.196955390515825

filename: 0_3_hidden Epoch 138 loss:2.329344178172683 ael:0.00812363950698068 cl:23.212204905131234

filename: 0_3_hidden Epoch 139 loss:2.3268090677784046 ael:0.008015122769032032 cl:23.18793897338928

filename: 0_3_hidden Epoch 140 loss:2.3255329269286587 ael:0.007980026240916724 cl:23.175528563844903

filename: 0_3_hidden Epoch 141 loss:2.3230911711287487 ael:0.007781030408115561 cl:23.153100947449918

filename: 0_3_hidden Epoch 142 loss:2.323427604809292 ael:0.007780939122029929 cl:23.156466196589523

filename: 0_3_hidden Epoch 143 loss:2.3210305688864685 ael:0.00761665247462404 cl:23.13413871077085

filename: 0_3_hidden Epoch 144 loss:2.32069543534152 ael:0.007579043621033074 cl:23.131163448377457

filename: 0_3_hidden Epoch 145 loss:2.3220233888131916 ael:0.007632498664658018 cl:23.143908405161405

filename: 0_3_hidden Epoch 146 loss:2.3210986705935888 ael:0.007555188748736805 cl:23.13543438210556

filename: 0_3_hidden Epoch 147 loss:2.316531880613459 ael:0.007327544927043914 cl:23.0920429381792

filename: 0_3_hidden Epoch 148 loss:2.3173050343485455 ael:0.007296167867880929 cl:23.10008821834304

filename: 0_3_hidden Epoch 149 loss:2.319158584131907 ael:0.007199638413880661 cl:23.119588970722223

filename: 0_3_hidden Epoch 150 loss:2.3190116289544593 ael:0.007064931985597796 cl:23.119466456597163

filename: 0_3_hidden Epoch 151 loss:2.3187334795881993 ael:0.007177783456117316 cl:23.115556477431223

filename: 0_3_hidden Epoch 152 loss:2.316837452452279 ael:0.007056656105635947 cl:23.097807527360597

filename: 0_3_hidden Epoch 153 loss:2.3153580723559615 ael:0.006971881624430003 cl:23.083861429416903

filename: 0_3_hidden Epoch 154 loss:2.3133435426330946 ael:0.006745266930423361 cl:23.06598228830928

filename: 0_3_hidden Epoch 155 loss:2.31427492160493 ael:0.006749051789635738 cl:23.075258233146876

filename: 0_3_hidden Epoch 156 loss:2.3139193245113696 ael:0.00674506423272857 cl:23.07174217611863

filename: 0_3_hidden Epoch 157 loss:2.3161809856640976 ael:0.00668008500750965 cl:23.09500857354636

filename: 0_3_hidden Epoch 158 loss:2.310132234264026 ael:0.006577227181116027 cl:23.035549619985446

filename: 0_3_hidden Epoch 159 loss:2.3138903777992543 ael:0.006640687529656592 cl:23.072496436992925

filename: 0_3_hidden Epoch 160 loss:2.310598705084572 ael:0.006441372054836452 cl:23.041572855905212

filename: 0_3_hidden Epoch 161 loss:2.3096972570291014 ael:0.006398511488328437 cl:23.0329869901831

filename: 0_3_hidden Epoch 162 loss:2.308776864734644 ael:0.006344634270426359 cl:23.02432183881987

filename: 0_3_hidden Epoch 163 loss:2.3097571186836405 ael:0.0064188444638447525 cl:23.033382315034586

filename: 0_3_hidden Epoch 164 loss:2.3068277483623185 ael:0.006245773580987016 cl:23.005819252253648

filename: 0_3_hidden Epoch 165 loss:2.3100889337318242 ael:0.00634089535762109 cl:23.03747989766682

filename: 0_3_hidden Epoch 166 loss:2.308345558813216 ael:0.006177387176862049 cl:23.021681218700856

filename: 0_3_hidden Epoch 167 loss:2.308311668865468 ael:0.006211695982413353 cl:23.020999264111254

filename: 0_3_hidden Epoch 168 loss:2.306154929884762 ael:0.0060693604292048255 cl:23.00085522775693

filename: 0_3_hidden Epoch 169 loss:2.3074098501742393 ael:0.006114532980454439 cl:23.012952678169132

filename: 0_3_hidden Epoch 170 loss:2.3060919707487875 ael:0.0061080742274250005 cl:22.999838552964405

filename: 0_3_hidden Epoch 171 loss:2.3075767703833243 ael:0.006040405859547984 cl:23.015363198105945

filename: 0_3_hidden Epoch 172 loss:2.3033069449986874 ael:0.005980935165942584 cl:22.973259617454328

filename: 0_3_hidden Epoch 173 loss:2.30770841824456 ael:0.005949478833571885 cl:23.017588910500564

filename: 0_3_hidden Epoch 174 loss:2.3078409131629347 ael:0.00602169954412866 cl:23.01819164407271

filename: 0_3_hidden Epoch 175 loss:2.302564228121535 ael:0.005936522788531042 cl:22.966276589827448

filename: 0_3_hidden Epoch 176 loss:2.303866840739362 ael:0.00595128358985373 cl:22.979155118986927

filename: 0_3_hidden Epoch 177 loss:2.3032793510476925 ael:0.005953595081787866 cl:22.973257050564115

filename: 0_3_hidden Epoch 178 loss:2.303628446275343 ael:0.005992033588456377 cl:22.97636365866744

filename: 0_3_hidden Epoch 179 loss:2.3055578013469047 ael:0.005932422166882342 cl:22.996253343856804

filename: 0_3_hidden Epoch 180 loss:2.30383904074102 ael:0.005885149844711917 cl:22.97953847135307

filename: 0_3_hidden Epoch 181 loss:2.301594125672128 ael:0.005824593813207295 cl:22.95769483246017

filename: 0_3_hidden Epoch 182 loss:2.301394228324643 ael:0.005855984018542946 cl:22.955381946535212

filename: 0_3_hidden Epoch 183 loss:2.300841947307501 ael:0.005785783169736346 cl:22.95056113949687

filename: 0_3_hidden Epoch 184 loss:2.2995083836934196 ael:0.00577797957762842 cl:22.937303596310315

filename: 0_3_hidden Epoch 185 loss:2.30189145300361 ael:0.0057982886595234805 cl:22.960931155476096

filename: 0_3_hidden Epoch 186 loss:2.298542716162206 ael:0.005755845423672751 cl:22.92786822867857

filename: 0_3_hidden Epoch 187 loss:2.299831350228652 ael:0.00571807652633446 cl:22.94113225894124

filename: 0_3_hidden Epoch 188 loss:2.303211627400925 ael:0.005701965956350553 cl:22.97509614804757

filename: 0_3_hidden Epoch 189 loss:2.299001243141794 ael:0.005601398587318747 cl:22.933997989116644

filename: 0_3_hidden Epoch 190 loss:2.298801245413791 ael:0.005621054987611057 cl:22.931801456210028

filename: 0_3_hidden Epoch 191 loss:2.3001983638539145 ael:0.005665050874388576 cl:22.945332639776893

filename: 0_3_hidden Epoch 192 loss:2.2950703463984414 ael:0.005548550491766493 cl:22.895217481156042

filename: 0_3_hidden Epoch 193 loss:2.297654969215868 ael:0.005566436002136769 cl:22.920884875082294

filename: 0_3_hidden Epoch 194 loss:2.2957864910675982 ael:0.005520625061164812 cl:22.902658211632517

filename: 0_3_hidden Epoch 195 loss:2.2932837042692116 ael:0.005543785160787934 cl:22.877398707109954

filename: 0_3_hidden Epoch 196 loss:2.2974742653955555 ael:0.00557824009790456 cl:22.918959782500142

filename: 0_3_hidden Epoch 197 loss:2.29469832723035 ael:0.005458753736639571 cl:22.892395252366533

filename: 0_3_hidden Epoch 198 loss:2.293606908332072 ael:0.005451931126854708 cl:22.881549298258403

filename: 0_3_hidden Epoch 199 loss:2.2977171317225498 ael:0.005506231321006137 cl:22.922108525236744

filename: 0_3_hidden Epoch 200 loss:2.296399261741182 ael:0.005449836824263767 cl:22.909493780397455

filename: 0_3_hidden Epoch 201 loss:2.2951301310747847 ael:0.005386136628025665 cl:22.897439493845514

filename: 0_3_hidden Epoch 202 loss:2.29467398329166 ael:0.005376657509923864 cl:22.89297279696234

filename: 0_3_hidden Epoch 203 loss:2.2938337160332853 ael:0.005390000693856423 cl:22.884436681963166

filename: 0_3_hidden Epoch 204 loss:2.2912600150913756 ael:0.005387691126632405 cl:22.858722794156915

filename: 0_3_hidden Epoch 205 loss:2.2894508095006176 ael:0.005328099496359136 cl:22.841226616723063

filename: 0_3_hidden Epoch 206 loss:2.29253480484311 ael:0.0053493204516394405 cl:22.8718543534975

filename: 0_3_hidden Epoch 207 loss:2.290729756074933 ael:0.005323454209937012 cl:22.854062580741573

filename: 0_3_hidden Epoch 208 loss:2.2918379373911546 ael:0.005276745823191087 cl:22.865611437962432

filename: 0_3_hidden Epoch 209 loss:2.290832574770233 ael:0.005287317596013993 cl:22.855452122709675

filename: 0_3_hidden Epoch 210 loss:2.290013821789086 ael:0.005270586580624613 cl:22.847431854757435

filename: 0_3_hidden Epoch 211 loss:2.2911069223877205 ael:0.005227279940533754 cl:22.858795953854198

filename: 0_3_hidden Epoch 212 loss:2.292051346966088 ael:0.005216811866906444 cl:22.86834487382844

filename: 0_3_hidden Epoch 213 loss:2.2904253291085874 ael:0.0051748696025544485 cl:22.85250414481018

filename: 0_3_hidden Epoch 214 loss:2.292574670698492 ael:0.005216035465688984 cl:22.873585889632867

filename: 0_3_hidden Epoch 215 loss:2.2905215118794993 ael:0.005157503808811901 cl:22.853639654930276

filename: 0_3_hidden Epoch 216 loss:2.2941215549111664 ael:0.0051386534596232335 cl:22.889828542719805

filename: 0_3_hidden Epoch 217 loss:2.2895864415774607 ael:0.0051639121568492164 cl:22.8442248395265

filename: 0_3_hidden Epoch 218 loss:2.292943107173047 ael:0.005258958940902343 cl:22.876841036193575

filename: 0_3_hidden Epoch 219 loss:2.2882842423610565 ael:0.005062134825431022 cl:22.83222059640471

filename: 0_3_hidden Epoch 220 loss:2.291011371717087 ael:0.005060169740019002 cl:22.859511564071344

filename: 0_3_hidden Epoch 221 loss:2.2946363098299436 ael:0.005075549740343358 cl:22.895607102018243

filename: 0_3_hidden Epoch 222 loss:2.2889481561957274 ael:0.0050348984555531094 cl:22.83913209418129

filename: 0_3_hidden Epoch 223 loss:2.289884410275116 ael:0.004989749796184612 cl:22.848946127062362

filename: 0_3_hidden Epoch 224 loss:2.2874658179627643 ael:0.004973725622842821 cl:22.82492041670985

filename: 0_3_hidden Epoch 225 loss:2.288055881791051 ael:0.004928742267430853 cl:22.831270924004144

filename: 0_3_hidden Epoch 226 loss:2.2867183810035923 ael:0.004945562146515894 cl:22.817727715682793

filename: 0_3_hidden Epoch 227 loss:2.289085974667164 ael:0.004942074904146854 cl:22.841438537696494

filename: 0_3_hidden Epoch 228 loss:2.2871266326087 ael:0.004931043901011593 cl:22.82195541807592

filename: 0_3_hidden Epoch 229 loss:2.287179368493803 ael:0.004825805192075458 cl:22.823535144655754

filename: 0_3_hidden Epoch 230 loss:2.285563152110808 ael:0.005050566540701537 cl:22.805125387141405

filename: 0_3_hidden Epoch 231 loss:2.28570491583358 ael:0.00484811828931581 cl:22.80856748237857

filename: 0_3_hidden Epoch 232 loss:2.282625157736877 ael:0.004761637145802787 cl:22.77863471235989

filename: 0_3_hidden Epoch 233 loss:2.284492663976026 ael:0.004790044638505052 cl:22.797025682442687

filename: 0_3_hidden Epoch 234 loss:2.286827984293361 ael:0.004839615975114492 cl:22.81988319545227

filename: 0_3_hidden Epoch 235 loss:2.284823489058475 ael:0.004747242675365636 cl:22.800761965536395

filename: 0_3_hidden Epoch 236 loss:2.282653600823897 ael:0.004707529877535683 cl:22.779460235086315

filename: 0_3_hidden Epoch 237 loss:2.286579415105621 ael:0.0047694408261937824 cl:22.818099271377996

filename: 0_3_hidden Epoch 238 loss:2.282431792072473 ael:0.004658512056744404 cl:22.777732334982772

filename: 0_3_hidden Epoch 239 loss:2.2853988488040042 ael:0.004680762105024182 cl:22.8071803733016

filename: 0_3_hidden Epoch 240 loss:2.2827598467714227 ael:0.004669991679518383 cl:22.780898055688148

filename: 0_3_hidden Epoch 241 loss:2.283736169724305 ael:0.004638117039228145 cl:22.79098007817974

filename: 0_3_hidden Epoch 242 loss:2.281735294246531 ael:0.004550361720098931 cl:22.77184885630396

filename: 0_3_hidden Epoch 243 loss:2.2846450313264954 ael:0.004545791325561691 cl:22.800991900358024

filename: 0_3_hidden Epoch 244 loss:2.282111386309587 ael:0.004454078384330306 cl:22.77657257292956

filename: 0_3_hidden Epoch 245 loss:2.2841654687481374 ael:0.004453753873053428 cl:22.797116641209502

filename: 0_3_hidden Epoch 246 loss:2.280849854864169 ael:0.0043751504185215555 cl:22.76474659230261

filename: 0_3_hidden Epoch 247 loss:2.280634607316014 ael:0.004336485057543939 cl:22.76298072199116

filename: 0_3_hidden Epoch 248 loss:2.278884533156075 ael:0.004361324008451204 cl:22.745231587553

filename: 0_3_hidden Epoch 249 loss:2.2788319849053247 ael:0.004363968513518995 cl:22.744679709958625

filename: 0_3_hidden Epoch 250 loss:2.2801621807827304 ael:0.004249378466188878 cl:22.759127562237307

/tmp/ipykernel_336185/680421385.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
/tmp/ipykernel_336185/680421385.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3  Label
0        0.034629  0.023495  0.027975  0.025160      1
1        0.016511  0.036618  0.036762  0.024156      2
2        0.035454  0.021802  0.028574  0.022282      1
3        0.031991  0.038875  0.023981  0.057944      4
4        0.016509  0.036616  0.036762  0.024151      2
...           ...       ...       ...       ...    ...
1027126  0.016518  0.036622  0.036761  0.024170      2
1027127  0.016513  0.036619  0.036761  0.024159      2
1027128  0.016512  0.036619  0.036762  0.024157      2
1027129  0.016513  0.036619  0.036761  0.024159      2
1027130  0.016569  0.036655  0.036753  0.024273      2

[1027131 rows x 5 columns]

Davies-Bouldin Score: 1.013427200897425

               0         1         2         3  Label
0       0.036505  0.020426  0.027374  0.018399      0
1       0.016509  0.036618  0.036762  0.024152      2
2       0.036177  0.022735  0.027259  0.024097      1
3       0.017446  0.035305  0.036483  0.024551      3
4       0.036082  0.021977  0.027653  0.024866      1
...          ...       ...       ...       ...    ...
519951  0.035627  0.023667  0.027405  0.025188      1
519952  0.033058  0.034448  0.026625  0.050692      4
519953  0.030653  0.027301  0.029778  0.026740      0
519954  0.035938  0.022654  0.027465  0.025126      1
519955  0.017598  0.037108  0.035878  0.027792      3

[519956 rows x 5 columns]

               0         1         2         3  Label
0       0.030633  0.027320  0.029797  0.026748      0
1       0.036356  0.020876  0.027390  0.019091      0
2       0.036905  0.022439  0.027147  0.024309      1
3       0.036112  0.023187  0.027985  0.024349      1
4       0.031965  0.026913  0.028859  0.026131      0
...          ...       ...       ...       ...    ...
649942  0.035965  0.022143  0.027780  0.024925      1
649943  0.032057  0.026891  0.028813  0.026115      0
649944  0.032055  0.026847  0.028802  0.026105      0
649945  0.026408  0.030394  0.033343  0.025185      3
649946  0.017012  0.035447  0.036177  0.024775      2

[649947 rows x 5 columns]

0_4_hidden

cuda
[1.0, 2.0, 3.0, 5.0]

pick completo
82 4

filename: 0_4_hidden Epoch 1 loss:3.6045982450597425 ael:0.029749900049146485 cl:35.748482892204734

filename: 0_4_hidden Epoch 2 loss:2.8358689038893754 ael:0.01759301666652455 cl:28.182758426441865

filename: 0_4_hidden Epoch 3 loss:2.733272730995627 ael:0.017591991655090275 cl:27.15680691797593

filename: 0_4_hidden Epoch 4 loss:2.643740202735452 ael:0.0175817341006854 cl:26.261584185431985

filename: 0_4_hidden Epoch 5 loss:2.576054375368006 ael:0.017535825856468255 cl:25.585185006534353

filename: 0_4_hidden Epoch 6 loss:2.535107007082771 ael:0.01732538136401597 cl:25.177815811157227

filename: 0_4_hidden Epoch 7 loss:2.50869977350796 ael:0.016629361698294386 cl:24.920703627642464

filename: 0_4_hidden Epoch 8 loss:2.492080270318424 ael:0.01594611496697454 cl:24.761341098561008

filename: 0_4_hidden Epoch 9 loss:2.478277184598586 ael:0.01582772180131253 cl:24.624494150498332

filename: 0_4_hidden Epoch 10 loss:2.473712186757256 ael:0.015809115475591492 cl:24.579030255485982

filename: 0_4_hidden Epoch 11 loss:2.4615393920225257 ael:0.01577720056956305 cl:24.457621443804573

filename: 0_4_hidden Epoch 12 loss:2.4546839073405544 ael:0.015743354039595408 cl:24.389405043658087

filename: 0_4_hidden Epoch 13 loss:2.4500220532136803 ael:0.01567039572096923 cl:24.343516123154583

filename: 0_4_hidden Epoch 14 loss:2.443465214224423 ael:0.015465121964759687 cl:24.280000381469726

filename: 0_4_hidden Epoch 15 loss:2.438234366304734 ael:0.015017430004389848 cl:24.232168870813705

filename: 0_4_hidden Epoch 16 loss:2.4331135885014255 ael:0.014351049866308184 cl:24.18762488331514

filename: 0_4_hidden Epoch 17 loss:2.427677863289328 ael:0.013963022417005371 cl:24.137147932164808

filename: 0_4_hidden Epoch 18 loss:2.4246280573676615 ael:0.013866572579478516 cl:24.10761436103372

filename: 0_4_hidden Epoch 19 loss:2.420908069554497 ael:0.01384187134092345 cl:24.070661490945255

filename: 0_4_hidden Epoch 20 loss:2.4155445103925817 ael:0.013806917160749435 cl:24.01737547302246

filename: 0_4_hidden Epoch 21 loss:2.4125296178144566 ael:0.013784981667995452 cl:23.987445870792165

filename: 0_4_hidden Epoch 22 loss:2.4091750662186566 ael:0.013759001758168726 cl:23.954160180484546

filename: 0_4_hidden Epoch 23 loss:2.4060172926397883 ael:0.013740101535530652 cl:23.92277141795439

filename: 0_4_hidden Epoch 24 loss:2.403487951446982 ael:0.01371835758580881 cl:23.897695465985468

filename: 0_4_hidden Epoch 25 loss:2.4012777906866636 ael:0.013700860206256894 cl:23.875768820369945

filename: 0_4_hidden Epoch 26 loss:2.3978938024184284 ael:0.013689439146834261 cl:23.842043166216683

filename: 0_4_hidden Epoch 27 loss:2.395138219833374 ael:0.013677430462311296 cl:23.814607437133787

filename: 0_4_hidden Epoch 28 loss:2.392778024449068 ael:0.013665891848942813 cl:23.79112084422392

filename: 0_4_hidden Epoch 29 loss:2.3909082223106832 ael:0.0136541306236211 cl:23.772540425020107

filename: 0_4_hidden Epoch 30 loss:2.389020185021793 ael:0.013635041065075819 cl:23.75385095573874

filename: 0_4_hidden Epoch 31 loss:2.386247806324678 ael:0.01362892830196549 cl:23.726188295252182

filename: 0_4_hidden Epoch 32 loss:2.384650786960826 ael:0.013607769913094885 cl:23.710429710836973

filename: 0_4_hidden Epoch 33 loss:2.383078093921437 ael:0.01359790407515624 cl:23.69480147417854

filename: 0_4_hidden Epoch 34 loss:2.3809883123846616 ael:0.013575394022990676 cl:23.67412872583726

filename: 0_4_hidden Epoch 35 loss:2.3794936606463266 ael:0.013559975225697546 cl:23.659336380004884

filename: 0_4_hidden Epoch 36 loss:2.3773549208921545 ael:0.01354391426899854 cl:23.63810962273093

filename: 0_4_hidden Epoch 37 loss:2.375709857379689 ael:0.01352311578787425 cl:23.621866924510282

filename: 0_4_hidden Epoch 38 loss:2.374240238133599 ael:0.013515449479222298 cl:23.607247423957375

filename: 0_4_hidden Epoch 39 loss:2.3724960557713226 ael:0.01350818535860847 cl:23.589878218706918

filename: 0_4_hidden Epoch 40 loss:2.3705952987109913 ael:0.013501494269598933 cl:23.570937614889704

filename: 0_4_hidden Epoch 41 loss:2.370185419587528 ael:0.013489665250129559 cl:23.566957034840303

filename: 0_4_hidden Epoch 42 loss:2.369064395175261 ael:0.013478313466643585 cl:23.5558603515625

filename: 0_4_hidden Epoch 43 loss:2.3669761140486774 ael:0.01348185903272208 cl:23.534942058787628

filename: 0_4_hidden Epoch 44 loss:2.3663114263871137 ael:0.013470980823916548 cl:23.5284040258071

filename: 0_4_hidden Epoch 45 loss:2.3650665054882274 ael:0.013471229505889555 cl:23.515952313591452

filename: 0_4_hidden Epoch 46 loss:2.3623751134872437 ael:0.013473259147037477 cl:23.48901811128504

filename: 0_4_hidden Epoch 47 loss:2.3605253747491277 ael:0.013456845087163589 cl:23.4706848153507

filename: 0_4_hidden Epoch 48 loss:2.3593708399604347 ael:0.013443246114341651 cl:23.459275466918946

filename: 0_4_hidden Epoch 49 loss:2.3583429209204283 ael:0.01343876577300184 cl:23.44904105870864

filename: 0_4_hidden Epoch 50 loss:2.355756249539992 ael:0.013437944521360538 cl:23.423182548074163

filename: 0_4_hidden Epoch 51 loss:2.354492857652552 ael:0.013431180889992154 cl:23.410616289026596

filename: 0_4_hidden Epoch 52 loss:2.3530326253105613 ael:0.01341498961957062 cl:23.39617588447122

filename: 0_4_hidden Epoch 53 loss:2.3509536522136014 ael:0.013426943515591762 cl:23.37526658450856

filename: 0_4_hidden Epoch 54 loss:2.350497148513794 ael:0.013493537442649112 cl:23.370035641838523

filename: 0_4_hidden Epoch 55 loss:2.3481147461498484 ael:0.013476392219610073 cl:23.346383061128503

filename: 0_4_hidden Epoch 56 loss:2.3467227835935707 ael:0.013478221955544809 cl:23.332445161707263

filename: 0_4_hidden Epoch 57 loss:2.3449772043789134 ael:0.013475849376005286 cl:23.315013099221623

filename: 0_4_hidden Epoch 58 loss:2.3436708755493165 ael:0.013470136000829585 cl:23.302006910436294

filename: 0_4_hidden Epoch 59 loss:2.342743369102478 ael:0.013479211010038853 cl:23.292641104305492

filename: 0_4_hidden Epoch 60 loss:2.340735704758588 ael:0.013480388620320489 cl:23.272552711935603

filename: 0_4_hidden Epoch 61 loss:2.33789922282275 ael:0.013483874956036316 cl:23.244153024112478

filename: 0_4_hidden Epoch 62 loss:2.3377040791792028 ael:0.013473626344957773 cl:23.24230404214298

filename: 0_4_hidden Epoch 63 loss:2.3356293580111336 ael:0.013474466130575713 cl:23.221548433191636

filename: 0_4_hidden Epoch 64 loss:2.3338599016526165 ael:0.013476672715562231 cl:23.203831767362708

filename: 0_4_hidden Epoch 65 loss:2.3320715722476737 ael:0.013485299982130527 cl:23.185862253525677

filename: 0_4_hidden Epoch 66 loss:2.3295284671783447 ael:0.013489856993889108 cl:23.160385627297796

filename: 0_4_hidden Epoch 67 loss:2.327349994939916 ael:0.013492466531255666 cl:23.138574809354893

filename: 0_4_hidden Epoch 68 loss:2.325291176964255 ael:0.013491200013634037 cl:23.11799930258358

filename: 0_4_hidden Epoch 69 loss:2.322125885514652 ael:0.013496639549732209 cl:23.08629201552447

filename: 0_4_hidden Epoch 70 loss:2.3207942457199096 ael:0.013498904523165788 cl:23.072952922147863

filename: 0_4_hidden Epoch 71 loss:2.3179297126882217 ael:0.013497653150821434 cl:23.044320106057558

filename: 0_4_hidden Epoch 72 loss:2.3160835051256066 ael:0.013502825187409626 cl:23.025806355195886

filename: 0_4_hidden Epoch 73 loss:2.313834601626677 ael:0.013511372579371229 cl:23.003231837553137

filename: 0_4_hidden Epoch 74 loss:2.309694759873783 ael:0.01351556151710889 cl:22.96179150390625

filename: 0_4_hidden Epoch 75 loss:2.3082744357726153 ael:0.01352104266119354 cl:22.947533459831686

filename: 0_4_hidden Epoch 76 loss:2.305254062428194 ael:0.013515165734817 cl:22.917388483384077

filename: 0_4_hidden Epoch 77 loss:2.3012636249205647 ael:0.013524610382669113 cl:22.877389667286593

filename: 0_4_hidden Epoch 78 loss:2.3177710143818575 ael:0.013514383684186374 cl:23.042565867704504

filename: 0_4_hidden Epoch 79 loss:2.3233971433639526 ael:0.013465001657166902 cl:23.09932097311581

filename: 0_4_hidden Epoch 80 loss:2.32342594315024 ael:0.013467509409960578 cl:23.099583863202263

filename: 0_4_hidden Epoch 81 loss:2.3207644607319553 ael:0.013474559867645012 cl:23.072898503920612

filename: 0_4_hidden Epoch 82 loss:2.3216431833716 ael:0.013458958613521912 cl:23.081841774435603

filename: 0_4_hidden Epoch 83 loss:2.321004803938024 ael:0.013467811760656975 cl:23.075369462854724

filename: 0_4_hidden Epoch 84 loss:2.3174235990748686 ael:0.01345408416933873 cl:23.039694685094496

filename: 0_4_hidden Epoch 85 loss:2.316265768612132 ael:0.013467059034196769 cl:23.02798660368078

filename: 0_4_hidden Epoch 86 loss:2.3147637871573954 ael:0.013462602218722596 cl:23.013011391134825

filename: 0_4_hidden Epoch 87 loss:2.312991811471827 ael:0.013468560194706216 cl:22.995232038610123

filename: 0_4_hidden Epoch 88 loss:2.312306158177993 ael:0.013443053780671428 cl:22.988630547916188

filename: 0_4_hidden Epoch 89 loss:2.3091429974051083 ael:0.013447551271056428 cl:22.956953988467944

filename: 0_4_hidden Epoch 90 loss:2.3089436214110433 ael:0.013446459748289164 cl:22.954971121395335

filename: 0_4_hidden Epoch 91 loss:2.304021522802465 ael:0.013453703971031834 cl:22.905677785536824

filename: 0_4_hidden Epoch 92 loss:2.303350725847132 ael:0.013458029766731402 cl:22.898926485847024

filename: 0_4_hidden Epoch 93 loss:2.303028270889731 ael:0.013454091562506031 cl:22.895741311465994

filename: 0_4_hidden Epoch 94 loss:2.3013685746473422 ael:0.01345209064246977 cl:22.879164364983055

filename: 0_4_hidden Epoch 95 loss:2.297320013775545 ael:0.013473927231395946 cl:22.83846038459329

filename: 0_4_hidden Epoch 96 loss:2.2978443200167487 ael:0.013443441056591622 cl:22.84400832232307

filename: 0_4_hidden Epoch 97 loss:2.2948920524260576 ael:0.013482547410270747 cl:22.814094590130974

filename: 0_4_hidden Epoch 98 loss:2.2949753542507394 ael:0.013439759367967354 cl:22.815355456183937

filename: 0_4_hidden Epoch 99 loss:2.2893721177157236 ael:0.013486395896795919 cl:22.758856756771312

filename: 0_4_hidden Epoch 100 loss:2.2883820285236136 ael:0.013509302091072588 cl:22.74872682459214

filename: 0_4_hidden Epoch 101 loss:2.284181660820456 ael:0.013485549035756028 cl:22.706960662841798

filename: 0_4_hidden Epoch 102 loss:2.2846751276465023 ael:0.01345888880070518 cl:22.71216190293256

filename: 0_4_hidden Epoch 103 loss:2.2825384502971873 ael:0.013489577484919744 cl:22.69048826599121

filename: 0_4_hidden Epoch 104 loss:2.279867205956403 ael:0.013463944620507606 cl:22.66403213231704

filename: 0_4_hidden Epoch 105 loss:2.2767165610930498 ael:0.013500070568393259 cl:22.632164446662454

filename: 0_4_hidden Epoch 106 loss:2.2759266592474545 ael:0.013473873381229007 cl:22.624527394014248

filename: 0_4_hidden Epoch 107 loss:2.2710530857198377 ael:0.01351519406104789 cl:22.575378432329963

filename: 0_4_hidden Epoch 108 loss:2.2679020348717183 ael:0.013489099485032699 cl:22.544128917918485

filename: 0_4_hidden Epoch 109 loss:2.2679739329955155 ael:0.013488809951088008 cl:22.544850786994484

filename: 0_4_hidden Epoch 110 loss:2.2762177112242754 ael:0.013488482446354979 cl:22.627291817160213

filename: 0_4_hidden Epoch 111 loss:2.265090129179113 ael:0.013494313812431167 cl:22.515957662245807

filename: 0_4_hidden Epoch 112 loss:2.2672945506151985 ael:0.013451014593681868 cl:22.538434896132525

filename: 0_4_hidden Epoch 113 loss:2.2650366895900054 ael:0.013461663215037655 cl:22.515749829460592

filename: 0_4_hidden Epoch 114 loss:2.266769599129172 ael:0.013447153788279084 cl:22.533224029541017

filename: 0_4_hidden Epoch 115 loss:2.262625266748316 ael:0.01344905033576138 cl:22.491761689129998

filename: 0_4_hidden Epoch 116 loss:2.289083020266365 ael:0.01338821105659008 cl:22.75694764619715

filename: 0_4_hidden Epoch 117 loss:2.289286570773405 ael:0.013427953946678077 cl:22.758585705027862

filename: 0_4_hidden Epoch 118 loss:2.2861554833580464 ael:0.013394705091767451 cl:22.72760734199075

filename: 0_4_hidden Epoch 119 loss:2.2794461593066946 ael:0.013440721727907657 cl:22.660053924560547

filename: 0_4_hidden Epoch 120 loss:2.282054948245778 ael:0.013426965677562882 cl:22.686279386632584

filename: 0_4_hidden Epoch 121 loss:2.2753998779970055 ael:0.013489186309278011 cl:22.619106439927045

filename: 0_4_hidden Epoch 122 loss:2.2739256263620713 ael:0.013462916781797129 cl:22.604626646154067

filename: 0_4_hidden Epoch 123 loss:2.270416493359734 ael:0.013468671040061643 cl:22.569477755378273

filename: 0_4_hidden Epoch 124 loss:2.2644464340770947 ael:0.013473201725412817 cl:22.50973183665556

filename: 0_4_hidden Epoch 125 loss:2.264724228297963 ael:0.013449238539618604 cl:22.512749439015106

filename: 0_4_hidden Epoch 126 loss:2.263324565663057 ael:0.013467389012084288 cl:22.498571294447956

filename: 0_4_hidden Epoch 127 loss:2.2632548992493575 ael:0.013440676319248536 cl:22.49814176940918

filename: 0_4_hidden Epoch 128 loss:2.2978887123781093 ael:0.01352341905367725 cl:22.84365244517607

filename: 0_4_hidden Epoch 129 loss:2.3485731342540066 ael:0.01350000807379975 cl:23.35073084932215

filename: 0_4_hidden Epoch 130 loss:2.342361543150509 ael:0.013429620991296628 cl:23.289318702248966

filename: 0_4_hidden Epoch 131 loss:2.3399412562987383 ael:0.013409649703432532 cl:23.26531559573903

filename: 0_4_hidden Epoch 132 loss:2.336436779695399 ael:0.013338292803834466 cl:23.23098442436667

filename: 0_4_hidden Epoch 133 loss:2.33601788593741 ael:0.013310648562715334 cl:23.22707193262437

filename: 0_4_hidden Epoch 134 loss:2.333811351439532 ael:0.013250788786832024 cl:23.205605151008157

filename: 0_4_hidden Epoch 135 loss:2.333509318407844 ael:0.013199662031496272 cl:23.20309606933594

filename: 0_4_hidden Epoch 136 loss:2.333518066518447 ael:0.013119420993854018 cl:23.203985972684972

filename: 0_4_hidden Epoch 137 loss:2.3327196439294253 ael:0.013078215798472657 cl:23.196413831823012

filename: 0_4_hidden Epoch 138 loss:2.333167911866132 ael:0.012978557280319578 cl:23.20189305563534

filename: 0_4_hidden Epoch 139 loss:2.332282890600317 ael:0.012926513325203868 cl:23.19356331051097

filename: 0_4_hidden Epoch 140 loss:2.331315723587485 ael:0.012846485202365062 cl:23.18469193941004

filename: 0_4_hidden Epoch 141 loss:2.3304934662650614 ael:0.01280729936501559 cl:23.176861190795897

filename: 0_4_hidden Epoch 142 loss:2.3327521693285775 ael:0.012730075249777121 cl:23.200220467062557

filename: 0_4_hidden Epoch 143 loss:2.330218563304228 ael:0.012677511124926455 cl:23.17541003148696

filename: 0_4_hidden Epoch 144 loss:2.3275161692675423 ael:0.012551440358600195 cl:23.149646827248965

filename: 0_4_hidden Epoch 145 loss:2.327944623161765 ael:0.012469422442948117 cl:23.1547515186983

filename: 0_4_hidden Epoch 146 loss:2.3278281945621266 ael:0.012367298119208392 cl:23.15460846934599

filename: 0_4_hidden Epoch 147 loss:2.3251910452001234 ael:0.012256488146150813 cl:23.129345101749195

filename: 0_4_hidden Epoch 148 loss:2.3268111908295577 ael:0.012177990819163181 cl:23.146331512451173

filename: 0_4_hidden Epoch 149 loss:2.3234432314704447 ael:0.012121141306179412 cl:23.113220420388615

filename: 0_4_hidden Epoch 150 loss:2.3248643111060647 ael:0.012030767549048452 cl:23.128334967220532

filename: 0_4_hidden Epoch 151 loss:2.3232013470705817 ael:0.011926661648732774 cl:23.112746356739716

filename: 0_4_hidden Epoch 152 loss:2.323152882295496 ael:0.011816759691080626 cl:23.11336080124799

filename: 0_4_hidden Epoch 153 loss:2.3230190100950354 ael:0.011788697625784312 cl:23.112302633846507

filename: 0_4_hidden Epoch 154 loss:2.322432703410878 ael:0.011705435024464831 cl:23.107272215001725

filename: 0_4_hidden Epoch 155 loss:2.322114210128784 ael:0.011608967139440424 cl:23.105051948996152

filename: 0_4_hidden Epoch 156 loss:2.3203649414286893 ael:0.011611167859505205 cl:23.08753724490895

filename: 0_4_hidden Epoch 157 loss:2.319782775710611 ael:0.011529080453164437 cl:23.08253647927677

filename: 0_4_hidden Epoch 158 loss:2.321037206369288 ael:0.011457275027299629 cl:23.095798842486214

filename: 0_4_hidden Epoch 159 loss:2.320399567379671 ael:0.011389526341767871 cl:23.09009996840533

filename: 0_4_hidden Epoch 160 loss:2.3198490196676813 ael:0.01132615673235234 cl:23.08522814133588

filename: 0_4_hidden Epoch 161 loss:2.3174743046480066 ael:0.011277809590101242 cl:23.061964447021484

filename: 0_4_hidden Epoch 162 loss:2.3180293770958396 ael:0.011247573481324841 cl:23.067817588357364

filename: 0_4_hidden Epoch 163 loss:2.319420949094436 ael:0.01117889254496378 cl:23.082420088824104

filename: 0_4_hidden Epoch 164 loss:2.3166355621113497 ael:0.011110904506900731 cl:23.055246086569394

filename: 0_4_hidden Epoch 165 loss:2.316706572813146 ael:0.011040931031984441 cl:23.05665593136058

filename: 0_4_hidden Epoch 166 loss:2.316481876148897 ael:0.010967801509972881 cl:23.05514026148179

filename: 0_4_hidden Epoch 167 loss:2.316304301261902 ael:0.010907513533883235 cl:23.053967450310203

filename: 0_4_hidden Epoch 168 loss:2.3144575418584488 ael:0.010821998556747156 cl:23.036354956234202

filename: 0_4_hidden Epoch 169 loss:2.3159298987108117 ael:0.010763861507615623 cl:23.051659920187557

filename: 0_4_hidden Epoch 170 loss:2.312372155189514 ael:0.010683422032524557 cl:23.016886899162742

filename: 0_4_hidden Epoch 171 loss:2.315893632440006 ael:0.010593484416165772 cl:23.053000997206745

filename: 0_4_hidden Epoch 172 loss:2.3111267154918 ael:0.010515325569931198 cl:23.006113431145163

filename: 0_4_hidden Epoch 173 loss:2.3118908196617576 ael:0.010413854891324745 cl:23.014769194659063

filename: 0_4_hidden Epoch 174 loss:2.310692728659686 ael:0.010402292784084293 cl:23.002903889375574

filename: 0_4_hidden Epoch 175 loss:2.3085985350889318 ael:0.010380745825083817 cl:22.982177410350126

filename: 0_4_hidden Epoch 176 loss:2.310250039100647 ael:0.010303076610626544 cl:22.99946916737276

filename: 0_4_hidden Epoch 177 loss:2.3088619636647842 ael:0.010238649614812696 cl:22.986232625624712

filename: 0_4_hidden Epoch 178 loss:2.309423980488497 ael:0.010152828066883718 cl:22.99271102815516

filename: 0_4_hidden Epoch 179 loss:2.30868447674022 ael:0.010099387065233553 cl:22.98585041988597

filename: 0_4_hidden Epoch 180 loss:2.3083565425872803 ael:0.010077529153622249 cl:22.982789651309744

filename: 0_4_hidden Epoch 181 loss:2.306657492693733 ael:0.010000383032157141 cl:22.966570619470932

filename: 0_4_hidden Epoch 182 loss:2.305135411823497 ael:0.009938069649478968 cl:22.951972935396082

filename: 0_4_hidden Epoch 183 loss:2.3069460532244515 ael:0.0099068596945966 cl:22.970391460643096

filename: 0_4_hidden Epoch 184 loss:2.301054959184983 ael:0.009831792234717047 cl:22.91223118322036

filename: 0_4_hidden Epoch 185 loss:2.3020046248716466 ael:0.00976728077473886 cl:22.922372970581055

filename: 0_4_hidden Epoch 186 loss:2.3022321019453162 ael:0.009753660890985937 cl:22.92478395529354

filename: 0_4_hidden Epoch 187 loss:2.300134345110725 ael:0.009732414921855226 cl:22.904018806906308

filename: 0_4_hidden Epoch 188 loss:2.29749074790057 ael:0.009647272122476031 cl:22.87843431181066

filename: 0_4_hidden Epoch 189 loss:2.29842386711345 ael:0.009630978040835436 cl:22.88792840935202

filename: 0_4_hidden Epoch 190 loss:2.294558231690351 ael:0.009570462663384046 cl:22.849877214319566

filename: 0_4_hidden Epoch 191 loss:2.2920601946325863 ael:0.009585767711567527 cl:22.824743816600126

filename: 0_4_hidden Epoch 192 loss:2.2920201513626997 ael:0.00960191116788808 cl:22.824181914385626

filename: 0_4_hidden Epoch 193 loss:2.2939702353196987 ael:0.009541221231660423 cl:22.844289693495806

filename: 0_4_hidden Epoch 194 loss:2.285863682522493 ael:0.009576757800491418 cl:22.762868780697094

filename: 0_4_hidden Epoch 195 loss:2.288651143803316 ael:0.009671796821057796 cl:22.789792995677274

filename: 0_4_hidden Epoch 196 loss:2.2851038859872257 ael:0.009756223694585703 cl:22.753476133458754

filename: 0_4_hidden Epoch 197 loss:2.2786580471151017 ael:0.009603488894508166 cl:22.690545065487132

filename: 0_4_hidden Epoch 198 loss:2.2782348181780647 ael:0.009780306733268148 cl:22.684544624777402

filename: 0_4_hidden Epoch 199 loss:2.2748817934709438 ael:0.00972203180938959 cl:22.651597168866324

filename: 0_4_hidden Epoch 200 loss:2.275529794244205 ael:0.009805474287008538 cl:22.65724273143095

filename: 0_4_hidden Epoch 201 loss:2.2713756078271303 ael:0.009847569651901722 cl:22.615279884787167

filename: 0_4_hidden Epoch 202 loss:2.2947220453935513 ael:0.009707929689656286 cl:22.85014067436667

filename: 0_4_hidden Epoch 203 loss:2.2891291940913483 ael:0.00951218085911344 cl:22.79616967414407

filename: 0_4_hidden Epoch 204 loss:2.2931131307377535 ael:0.009483007974922656 cl:22.83630075791303

filename: 0_4_hidden Epoch 205 loss:2.298896013259888 ael:0.0092362577866982 cl:22.89659707372329

filename: 0_4_hidden Epoch 206 loss:2.3018178663253783 ael:0.009070631772498875 cl:22.927471877154183

filename: 0_4_hidden Epoch 207 loss:2.302831319360172 ael:0.008988571766106521 cl:22.938426978616153

filename: 0_4_hidden Epoch 208 loss:2.3007238950168385 ael:0.008783903205657707 cl:22.919399425730987

filename: 0_4_hidden Epoch 209 loss:2.299726051386665 ael:0.008809103616896798 cl:22.90916895428826

filename: 0_4_hidden Epoch 210 loss:2.296672260957606 ael:0.008631584269378115 cl:22.880406285005456

filename: 0_4_hidden Epoch 211 loss:2.2951369485855104 ael:0.008622717401560615 cl:22.86514187711828

filename: 0_4_hidden Epoch 212 loss:2.299426885436563 ael:0.008586658469675218 cl:22.908401766608744

filename: 0_4_hidden Epoch 213 loss:2.2977498156603646 ael:0.008387724984656363 cl:22.893620421465705

filename: 0_4_hidden Epoch 214 loss:2.292115575061125 ael:0.008246213135473869 cl:22.838693155625286

filename: 0_4_hidden Epoch 215 loss:2.2940841183942906 ael:0.008325735299902803 cl:22.85758337133071

filename: 0_4_hidden Epoch 216 loss:2.2911082431007834 ael:0.00828773182082702 cl:22.828204655366786

filename: 0_4_hidden Epoch 217 loss:2.2910696714064653 ael:0.008243710596333532 cl:22.82825915078556

filename: 0_4_hidden Epoch 218 loss:2.2897385128806618 ael:0.00819418367787319 cl:22.815442835190716

filename: 0_4_hidden Epoch 219 loss:2.2898364700990563 ael:0.00826313983627102 cl:22.81573284822352

filename: 0_4_hidden Epoch 220 loss:2.2851690351261813 ael:0.00820614026552614 cl:22.76962845656451

filename: 0_4_hidden Epoch 221 loss:2.288758061128504 ael:0.00813028946102542 cl:22.80627722706514

filename: 0_4_hidden Epoch 222 loss:2.288983904501971 ael:0.008184724909198634 cl:22.807991333905388

filename: 0_4_hidden Epoch 223 loss:2.28584023178325 ael:0.008037318804684807 cl:22.778028699987075

filename: 0_4_hidden Epoch 224 loss:2.2845430111043594 ael:0.008103359958485646 cl:22.76439601584042

filename: 0_4_hidden Epoch 225 loss:2.281675252914429 ael:0.008156903449226828 cl:22.735183007632983

filename: 0_4_hidden Epoch 226 loss:2.2806266287635353 ael:0.008227973319151823 cl:22.72398609565286

filename: 0_4_hidden Epoch 227 loss:2.2773929582483627 ael:0.008190860550631495 cl:22.69202046293371

filename: 0_4_hidden Epoch 228 loss:2.2803790306203506 ael:0.008268742722404354 cl:22.72110239275764

filename: 0_4_hidden Epoch 229 loss:2.270901799482458 ael:0.00822156323865056 cl:22.62680190142463

filename: 0_4_hidden Epoch 230 loss:2.273235403621898 ael:0.008205036828623098 cl:22.65030318136776

filename: 0_4_hidden Epoch 231 loss:2.266898822896621 ael:0.008230000015786465 cl:22.586687741447896

filename: 0_4_hidden Epoch 232 loss:2.2681520821627448 ael:0.008289711436585469 cl:22.598623261395623

filename: 0_4_hidden Epoch 233 loss:2.2609194583331838 ael:0.008381540718762313 cl:22.525378729427562

filename: 0_4_hidden Epoch 234 loss:2.2655788453606998 ael:0.008273933235117617 cl:22.573048630658317

filename: 0_4_hidden Epoch 235 loss:2.2595701256359324 ael:0.008351144704529467 cl:22.512189333747415

filename: 0_4_hidden Epoch 236 loss:2.2528122461543365 ael:0.008238407845444539 cl:22.44573792221967

filename: 0_4_hidden Epoch 237 loss:2.249983039070578 ael:0.00821702498635825 cl:22.41765967066148

filename: 0_4_hidden Epoch 238 loss:2.253940690096687 ael:0.008261994411621024 cl:22.456786497228286

filename: 0_4_hidden Epoch 239 loss:2.2486040391921995 ael:0.008171671623692794 cl:22.40432317127901

filename: 0_4_hidden Epoch 240 loss:2.2481202983856203 ael:0.008151056038544458 cl:22.39969196813247

filename: 0_4_hidden Epoch 241 loss:2.249992401796229 ael:0.008204150603755431 cl:22.41788204058479

filename: 0_4_hidden Epoch 242 loss:2.2484827697417313 ael:0.00810748816785567 cl:22.403752319335936

filename: 0_4_hidden Epoch 243 loss:2.245724255954518 ael:0.00796091198614415 cl:22.377632955214555

filename: 0_4_hidden Epoch 244 loss:2.2480624485576852 ael:0.007976422379779465 cl:22.400859804938822

filename: 0_4_hidden Epoch 245 loss:2.241928447611192 ael:0.007858200352858094 cl:22.340701980590822

filename: 0_4_hidden Epoch 246 loss:2.242061951132382 ael:0.007815397032262647 cl:22.342465061860928

filename: 0_4_hidden Epoch 247 loss:2.2431465141632976 ael:0.00764180262715501 cl:22.35504664522059

filename: 0_4_hidden Epoch 248 loss:2.2406999374838437 ael:0.007678814178223119 cl:22.33021076516544

filename: 0_4_hidden Epoch 249 loss:2.2390714543286494 ael:0.007575165218509296 cl:22.31496241760254

filename: 0_4_hidden Epoch 250 loss:2.2441742466197296 ael:0.007680785818135037 cl:22.364934115241557

/tmp/ipykernel_336185/680421385.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
/tmp/ipykernel_336185/680421385.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3  Label
0       -0.050426 -0.047793 -0.045416 -0.048696      1
1       -0.043343 -0.049127 -0.051280 -0.049148      2
2       -0.050390 -0.048376 -0.045313 -0.048612      1
3       -0.043343 -0.049127 -0.051280 -0.049148      2
4       -0.054112 -0.050984 -0.054508 -0.049644      3
...           ...       ...       ...       ...    ...
1087769 -0.054442 -0.050392 -0.054420 -0.049418      3
1087770 -0.043343 -0.049127 -0.051280 -0.049149      2
1087771 -0.043343 -0.049127 -0.051280 -0.049148      2
1087772 -0.043343 -0.049127 -0.051280 -0.049149      2
1087773 -0.043338 -0.049140 -0.051279 -0.049155      2

[1087774 rows x 5 columns]

Davies-Bouldin Score: 0.21875114492574887

               0         1         2         3  Label
0      -0.049677 -0.048798 -0.045450 -0.048758      0
1      -0.043341 -0.049125 -0.051283 -0.049147      2
2      -0.050056 -0.048396 -0.045700 -0.048315      1
3      -0.054063 -0.050683 -0.054552 -0.049634      3
4      -0.050032 -0.047941 -0.045395 -0.048419      1
...          ...       ...       ...       ...    ...
519951 -0.050060 -0.048217 -0.045600 -0.048287      1
519952 -0.049590 -0.047998 -0.045524 -0.048044      4
519953 -0.049651 -0.051994 -0.045420 -0.050931      0
519954 -0.050438 -0.047885 -0.045661 -0.048696      1
519955 -0.054442 -0.050392 -0.054420 -0.049418      3

[519956 rows x 5 columns]

               0         1         2         3  Label
0      -0.049636 -0.051992 -0.045414 -0.050929      0
1      -0.049653 -0.048785 -0.045445 -0.048750      0
2      -0.049679 -0.048769 -0.045509 -0.048667      1
3      -0.049830 -0.048660 -0.045775 -0.048515      1
4      -0.048706 -0.047321 -0.048871 -0.048047      0
...          ...       ...       ...       ...    ...
649942 -0.050088 -0.047976 -0.045326 -0.048388      1
649943 -0.048657 -0.047117 -0.048918 -0.047920      0
649944 -0.048685 -0.047171 -0.048879 -0.047956      0
649945 -0.054153 -0.050904 -0.054553 -0.049562      3
649946 -0.043410 -0.048868 -0.051069 -0.049019      2

[649947 rows x 5 columns]

0_5_hidden

cuda
[1.0, 2.0, 3.0, 4.0]

pick completo
82 4

filename: 0_5_hidden Epoch 1 loss:4.367918936309077 ael:0.02678826910959171 cl:43.411305935511564

filename: 0_5_hidden Epoch 2 loss:3.5174114471669164 ael:0.016101891507366843 cl:35.01309505573307

filename: 0_5_hidden Epoch 3 loss:3.462240327470827 ael:0.015028317999635056 cl:34.472119601093695

filename: 0_5_hidden Epoch 4 loss:3.445138357897904 ael:0.014601771999675838 cl:34.305365381847935

filename: 0_5_hidden Epoch 5 loss:3.434786003698369 ael:0.013753642492434558 cl:34.21032310012461

filename: 0_5_hidden Epoch 6 loss:3.4260915513004053 ael:0.013470502182282958 cl:34.12621001290468

filename: 0_5_hidden Epoch 7 loss:3.420447631865908 ael:0.013185388923417791 cl:34.07262196337187

filename: 0_5_hidden Epoch 8 loss:3.4139558726217745 ael:0.012915523122398725 cl:34.01040302525596

filename: 0_5_hidden Epoch 9 loss:3.4091710576503917 ael:0.012785641112162955 cl:33.963853707724674

filename: 0_5_hidden Epoch 10 loss:3.4045511595574625 ael:0.012640927764035515 cl:33.919101834969595

filename: 0_5_hidden Epoch 11 loss:3.399596186341248 ael:0.012401328207121969 cl:33.87194811077871

filename: 0_5_hidden Epoch 12 loss:3.395710501912906 ael:0.01217435962294651 cl:33.835360949698426

filename: 0_5_hidden Epoch 13 loss:3.391228876797832 ael:0.01200783184011325 cl:33.79220994339174

filename: 0_5_hidden Epoch 14 loss:3.3866196524030636 ael:0.011871374267739552 cl:33.74748231747955

filename: 0_5_hidden Epoch 15 loss:3.382658710986928 ael:0.011811135365274238 cl:33.70847525124008

filename: 0_5_hidden Epoch 16 loss:3.379182121236895 ael:0.011754683285312222 cl:33.674273895122276

filename: 0_5_hidden Epoch 17 loss:3.37647033544628 ael:0.011693822555048848 cl:33.647764637814134

filename: 0_5_hidden Epoch 18 loss:3.373496525331815 ael:0.011708130652128473 cl:33.617883469384104

filename: 0_5_hidden Epoch 19 loss:3.370873851318882 ael:0.011660048287469927 cl:33.592137541913104

filename: 0_5_hidden Epoch 20 loss:3.3688883013921243 ael:0.01164385753981679 cl:33.57244395441244

filename: 0_5_hidden Epoch 21 loss:3.36664605246351 ael:0.011597123537002482 cl:33.55048881088121

filename: 0_5_hidden Epoch 22 loss:3.3648253783979887 ael:0.011560722923252992 cl:33.532646044716536

filename: 0_5_hidden Epoch 23 loss:3.3630276598534596 ael:0.01149578649050869 cl:33.515318232712296

filename: 0_5_hidden Epoch 24 loss:3.361756148115461 ael:0.011422658500867227 cl:33.50333442119319

filename: 0_5_hidden Epoch 25 loss:3.3596926255153132 ael:0.011283828469412064 cl:33.48408749601132

filename: 0_5_hidden Epoch 26 loss:3.35811408684198 ael:0.011111767981336493 cl:33.470022699508235

filename: 0_5_hidden Epoch 27 loss:3.3565005289749403 ael:0.01094428215875297 cl:33.45556200981908

filename: 0_5_hidden Epoch 28 loss:3.3553479180808607 ael:0.01069519072838614 cl:33.446526807128755

filename: 0_5_hidden Epoch 29 loss:3.353615612199862 ael:0.010453072366793246 cl:33.431624901285105

filename: 0_5_hidden Epoch 30 loss:3.3526583665998397 ael:0.010097520700959815 cl:33.42560799557965

filename: 0_5_hidden Epoch 31 loss:3.350590378022021 ael:0.009794514539211052 cl:33.40795815135086

filename: 0_5_hidden Epoch 32 loss:3.349385049341188 ael:0.009447947034378155 cl:33.39937054236794

filename: 0_5_hidden Epoch 33 loss:3.3477858611405806 ael:0.009080506830816184 cl:33.38705306318285

filename: 0_5_hidden Epoch 34 loss:3.3464001219278376 ael:0.008795081020545253 cl:33.376049877077605

filename: 0_5_hidden Epoch 35 loss:3.3453777180286686 ael:0.008475497949794896 cl:33.36902169850831

filename: 0_5_hidden Epoch 36 loss:3.343888746260828 ael:0.008212686461936097 cl:33.35676010725096

filename: 0_5_hidden Epoch 37 loss:3.3430149504294997 ael:0.007999316261635492 cl:33.350155881870954

filename: 0_5_hidden Epoch 38 loss:3.3413923140209976 ael:0.00778751238905896 cl:33.33604752911761

filename: 0_5_hidden Epoch 39 loss:3.340597535217125 ael:0.007603729703958168 cl:33.32993758060969

filename: 0_5_hidden Epoch 40 loss:3.3398892897737307 ael:0.00739831688001866 cl:33.32490928320996

filename: 0_5_hidden Epoch 41 loss:3.338833787381697 ael:0.007053765570174521 cl:33.31779974415646

filename: 0_5_hidden Epoch 42 loss:3.3373153627543175 ael:0.006694217412308531 cl:33.30621097589288

filename: 0_5_hidden Epoch 43 loss:3.336099742306134 ael:0.006396044266697599 cl:33.29703651139277

filename: 0_5_hidden Epoch 44 loss:3.3354265067387163 ael:0.006114467274169471 cl:33.29311992159589

filename: 0_5_hidden Epoch 45 loss:3.3351489900101776 ael:0.0058269757510288215 cl:33.2932196393501

filename: 0_5_hidden Epoch 46 loss:3.333740719281119 ael:0.005542435967359665 cl:33.28198236193415

filename: 0_5_hidden Epoch 47 loss:3.332541110436826 ael:0.005281293056274882 cl:33.27259768717333

filename: 0_5_hidden Epoch 48 loss:3.3320188854703203 ael:0.005064156703710238 cl:33.26954683538985

filename: 0_5_hidden Epoch 49 loss:3.331092612576235 ael:0.004879334287385484 cl:33.262132301914605

filename: 0_5_hidden Epoch 50 loss:3.3302539995271867 ael:0.004700141006838275 cl:33.2555381450607

filename: 0_5_hidden Epoch 51 loss:3.329616344810781 ael:0.004572238764101992 cl:33.2504405829332

filename: 0_5_hidden Epoch 52 loss:3.328556689881779 ael:0.004464442445840281 cl:33.24092201875353

filename: 0_5_hidden Epoch 53 loss:3.3273199291405997 ael:0.004370184476888085 cl:33.22949695126075

filename: 0_5_hidden Epoch 54 loss:3.327203667423208 ael:0.004313778804050793 cl:33.228898404203626

filename: 0_5_hidden Epoch 55 loss:3.326456416431307 ael:0.0042347790904892465 cl:33.22221591989423

filename: 0_5_hidden Epoch 56 loss:3.3255316757752373 ael:0.004177732857681156 cl:33.2135389129737

filename: 0_5_hidden Epoch 57 loss:3.324904052986434 ael:0.004150061736143765 cl:33.207539429307275

filename: 0_5_hidden Epoch 58 loss:3.3240868094272904 ael:0.004116455213099982 cl:33.19970311741979

filename: 0_5_hidden Epoch 59 loss:3.3244651256310758 ael:0.004105498834335268 cl:33.20359582309277

filename: 0_5_hidden Epoch 60 loss:3.323049580925996 ael:0.00407165760196157 cl:33.18977874752785

filename: 0_5_hidden Epoch 61 loss:3.322222290550097 ael:0.004033094108135475 cl:33.181891488222035

filename: 0_5_hidden Epoch 62 loss:3.322131591588619 ael:0.0039963644385520945 cl:33.18135178156383

filename: 0_5_hidden Epoch 63 loss:3.3219498361338538 ael:0.003966871837017447 cl:33.17982914561134

filename: 0_5_hidden Epoch 64 loss:3.3211761303816374 ael:0.003956634182528736 cl:33.17219449396003

filename: 0_5_hidden Epoch 65 loss:3.320359333112872 ael:0.0039267102033155015 cl:33.16432575022954

filename: 0_5_hidden Epoch 66 loss:3.32010337616723 ael:0.00391192545462925 cl:33.16191401393254

filename: 0_5_hidden Epoch 67 loss:3.3200203121717085 ael:0.0038823196622239102 cl:33.16137944297575

filename: 0_5_hidden Epoch 68 loss:3.319670184402097 ael:0.0038608065678750816 cl:33.15809331950788

filename: 0_5_hidden Epoch 69 loss:3.319038718674665 ael:0.0038386500905073524 cl:33.15200022974867

filename: 0_5_hidden Epoch 70 loss:3.3189645183364966 ael:0.0038213984809829394 cl:33.15143073556118

filename: 0_5_hidden Epoch 71 loss:3.318792325752959 ael:0.00379712703327463 cl:33.14995151599697

filename: 0_5_hidden Epoch 72 loss:3.3179015516754506 ael:0.00377371999090665 cl:33.14127784962619

filename: 0_5_hidden Epoch 73 loss:3.3178758477127235 ael:0.0037533180578217798 cl:33.14122482733223

filename: 0_5_hidden Epoch 74 loss:3.3179677050503678 ael:0.003720510589753598 cl:33.142471467171056

filename: 0_5_hidden Epoch 75 loss:3.3176510054483037 ael:0.003710226579077728 cl:33.13940734079439

filename: 0_5_hidden Epoch 76 loss:3.3165696327192564 ael:0.003672087368537356 cl:33.12897494990052

filename: 0_5_hidden Epoch 77 loss:3.316914011450375 ael:0.0036510367341951963 cl:33.132629300009135

filename: 0_5_hidden Epoch 78 loss:3.316064250747779 ael:0.003629444803502996 cl:33.12434755612726

filename: 0_5_hidden Epoch 79 loss:3.3162747892422795 ael:0.0036069503016312103 cl:33.12667790196962

filename: 0_5_hidden Epoch 80 loss:3.3162685205242886 ael:0.0035886959940882508 cl:33.12679774678589

filename: 0_5_hidden Epoch 81 loss:3.3156151313343707 ael:0.003572781991639822 cl:33.12042302647298

filename: 0_5_hidden Epoch 82 loss:3.3154131832092064 ael:0.00355743237714434 cl:33.118557060081855

filename: 0_5_hidden Epoch 83 loss:3.315899798026688 ael:0.0035381181658816724 cl:33.12361630847817

filename: 0_5_hidden Epoch 84 loss:3.314859481226716 ael:0.0035117831995589155 cl:33.11347648273256

filename: 0_5_hidden Epoch 85 loss:3.3150586973362444 ael:0.003490620804819264 cl:33.11568031111232

filename: 0_5_hidden Epoch 86 loss:3.3144166803859494 ael:0.003460858814289987 cl:33.10955773275961

filename: 0_5_hidden Epoch 87 loss:3.313978182126398 ael:0.00342905803434971 cl:33.10549074445013

filename: 0_5_hidden Epoch 88 loss:3.3143961985777888 ael:0.003405244635342261 cl:33.10990903072065

filename: 0_5_hidden Epoch 89 loss:3.3143347807222563 ael:0.0033653315439434554 cl:33.10969402365489

filename: 0_5_hidden Epoch 90 loss:3.314020828313159 ael:0.003337739004436835 cl:33.106830420175164

filename: 0_5_hidden Epoch 91 loss:3.313752978295688 ael:0.0033037177278411834 cl:33.104492112189696

filename: 0_5_hidden Epoch 92 loss:3.313153119552145 ael:0.0032797438268137736 cl:33.09873328258874

filename: 0_5_hidden Epoch 93 loss:3.3131337120684763 ael:0.0032385505147137224 cl:33.09895113453953

filename: 0_5_hidden Epoch 94 loss:3.312964015291354 ael:0.003204546803980015 cl:33.09759417817441

filename: 0_5_hidden Epoch 95 loss:3.3126428741106193 ael:0.0031798796790729273 cl:33.094629478300895

filename: 0_5_hidden Epoch 96 loss:3.3127539501758854 ael:0.0031461087295651963 cl:33.09607796050386

filename: 0_5_hidden Epoch 97 loss:3.3125898826516127 ael:0.0030912039971270275 cl:33.09498631694834

filename: 0_5_hidden Epoch 98 loss:3.3122819374877537 ael:0.0030649858499681285 cl:33.09216906081084

filename: 0_5_hidden Epoch 99 loss:3.312310460495622 ael:0.003029310355176076 cl:33.09281101042373

filename: 0_5_hidden Epoch 100 loss:3.3124905285769946 ael:0.002988937765747867 cl:33.09501541362089

filename: 0_5_hidden Epoch 101 loss:3.311726457836357 ael:0.0029618631355880216 cl:33.087645463075106

filename: 0_5_hidden Epoch 102 loss:3.3117679728316647 ael:0.002924831292354093 cl:33.08843090954949

filename: 0_5_hidden Epoch 103 loss:3.31152512007044 ael:0.002893360869547744 cl:33.08631713691976

filename: 0_5_hidden Epoch 104 loss:3.311198971715308 ael:0.0028696771283160468 cl:33.083292473140595

filename: 0_5_hidden Epoch 105 loss:3.310911766662413 ael:0.0028411489945148194 cl:33.08070573952772

filename: 0_5_hidden Epoch 106 loss:3.3111883750565103 ael:0.0028265481025819563 cl:33.08361780749128

filename: 0_5_hidden Epoch 107 loss:3.310632575240277 ael:0.0027894793243592457 cl:33.0784304923919

filename: 0_5_hidden Epoch 108 loss:3.3106507132074507 ael:0.0027724096892903635 cl:33.07878256266776

filename: 0_5_hidden Epoch 109 loss:3.3106595367121177 ael:0.0027452583782529454 cl:33.07914227463371

filename: 0_5_hidden Epoch 110 loss:3.310557835818682 ael:0.002719930309718242 cl:33.07837855594951

filename: 0_5_hidden Epoch 111 loss:3.309915709745298 ael:0.0026941660637415698 cl:33.07221495576869

filename: 0_5_hidden Epoch 112 loss:3.30960769926128 ael:0.002706512423672343 cl:33.069011389296634

filename: 0_5_hidden Epoch 113 loss:3.3096247623276076 ael:0.002701446220374799 cl:33.06923271781682

filename: 0_5_hidden Epoch 114 loss:3.309033151118627 ael:0.0026928442921981027 cl:33.06340260855331

filename: 0_5_hidden Epoch 115 loss:3.3092092983574757 ael:0.002663405464410911 cl:33.065458474478156

filename: 0_5_hidden Epoch 116 loss:3.309087931293331 ael:0.002660766563584276 cl:33.06427117761924

filename: 0_5_hidden Epoch 117 loss:3.3092441969010062 ael:0.0026425806040771297 cl:33.06601568693888

filename: 0_5_hidden Epoch 118 loss:3.308634845217229 ael:0.0026383290817682675 cl:33.05996467258352

filename: 0_5_hidden Epoch 119 loss:3.308918648050448 ael:0.002619049357442451 cl:33.062995514881216

filename: 0_5_hidden Epoch 120 loss:3.308442020397048 ael:0.002603775083594321 cl:33.058381982814105

filename: 0_5_hidden Epoch 121 loss:3.308651560934007 ael:0.0025960097592125147 cl:33.06055502772427

filename: 0_5_hidden Epoch 122 loss:3.308567333471189 ael:0.0025871165821330262 cl:33.05980169725072

filename: 0_5_hidden Epoch 123 loss:3.3083405168089146 ael:0.0025795896216404476 cl:33.05760880500247

filename: 0_5_hidden Epoch 124 loss:3.308357486313721 ael:0.002559076871910177 cl:33.05798362821076

filename: 0_5_hidden Epoch 125 loss:3.30817052897285 ael:0.0025534825377004173 cl:33.056170001710065

filename: 0_5_hidden Epoch 126 loss:3.307935042404341 ael:0.0025392710577863916 cl:33.05395721601537

filename: 0_5_hidden Epoch 127 loss:3.307910055426414 ael:0.002545694573446553 cl:33.05364313901767

filename: 0_5_hidden Epoch 128 loss:3.3078952411026075 ael:0.002536718259270226 cl:33.05358474202736

filename: 0_5_hidden Epoch 129 loss:3.3078507752691326 ael:0.002518155296435572 cl:33.053325736071194

filename: 0_5_hidden Epoch 130 loss:3.3077110862847205 ael:0.002511470029507685 cl:33.051995671631154

filename: 0_5_hidden Epoch 131 loss:3.307568821476699 ael:0.0025193621774540283 cl:33.0504941148781

filename: 0_5_hidden Epoch 132 loss:3.3073429135331023 ael:0.002503024946821675 cl:33.048398423636755

filename: 0_5_hidden Epoch 133 loss:3.307386621556678 ael:0.0024914334833585957 cl:33.048951409498976

filename: 0_5_hidden Epoch 134 loss:3.3070211438379586 ael:0.002487522248851509 cl:33.045335747367616

filename: 0_5_hidden Epoch 135 loss:3.3068028264810345 ael:0.0024899821586818354 cl:33.04312799209361

filename: 0_5_hidden Epoch 136 loss:3.30698441690634 ael:0.0024765613610802954 cl:33.045078062415605

filename: 0_5_hidden Epoch 137 loss:3.306919197993928 ael:0.002492138708616689 cl:33.04427011660469

filename: 0_5_hidden Epoch 138 loss:3.3067695850522933 ael:0.002476831581257809 cl:33.04292708188655

filename: 0_5_hidden Epoch 139 loss:3.306200067426388 ael:0.002449213876482775 cl:33.03750809309081

filename: 0_5_hidden Epoch 140 loss:3.306665600835076 ael:0.0024582005413039004 cl:33.04207351340295

filename: 0_5_hidden Epoch 141 loss:3.3072321018223607 ael:0.0024626389169584476 cl:33.04769415705555

filename: 0_5_hidden Epoch 142 loss:3.306649618913434 ael:0.002448982191699843 cl:33.042005851708716

filename: 0_5_hidden Epoch 143 loss:3.3061937779596406 ael:0.0024397762211907947 cl:33.03753954820533

filename: 0_5_hidden Epoch 144 loss:3.306136126099432 ael:0.00243654236747935 cl:33.03699534060396

filename: 0_5_hidden Epoch 145 loss:3.30660305178809 ael:0.0024412653390089266 cl:33.04161739349365

filename: 0_5_hidden Epoch 146 loss:3.3062594830269396 ael:0.002436254275861398 cl:33.038231833532485

filename: 0_5_hidden Epoch 147 loss:3.3056922862839064 ael:0.0024245304875766243 cl:33.032677074865795

filename: 0_5_hidden Epoch 148 loss:3.305864626222037 ael:0.0024169141803883124 cl:33.034476637552096

filename: 0_5_hidden Epoch 149 loss:3.305426976356076 ael:0.002413602705705704 cl:33.03013324199618

filename: 0_5_hidden Epoch 150 loss:3.3058600689882622 ael:0.0024098114036515167 cl:33.03450211471939

filename: 0_5_hidden Epoch 151 loss:3.3056945944869836 ael:0.002390314072823057 cl:33.03304228986299

filename: 0_5_hidden Epoch 152 loss:3.3055386994751492 ael:0.0024001659177889855 cl:33.031384875369014

filename: 0_5_hidden Epoch 153 loss:3.3056207175796595 ael:0.002394546796027406 cl:33.03226121292299

filename: 0_5_hidden Epoch 154 loss:3.304875041187818 ael:0.0023871327319432358 cl:33.024878597951144

filename: 0_5_hidden Epoch 155 loss:3.3049933387808603 ael:0.002394559601618999 cl:33.02598734078726

filename: 0_5_hidden Epoch 156 loss:3.3049977576895935 ael:0.002382312180312301 cl:33.0261539809652

filename: 0_5_hidden Epoch 157 loss:3.3050174509489567 ael:0.002375277261513133 cl:33.0264212718229

filename: 0_5_hidden Epoch 158 loss:3.3042367424914953 ael:0.0023711432210724325 cl:33.0186554880319

filename: 0_5_hidden Epoch 159 loss:3.304393842756316 ael:0.0023689884824699315 cl:33.02024809109598

filename: 0_5_hidden Epoch 160 loss:3.3042388194804224 ael:0.002386103425800461 cl:33.0185266828268

filename: 0_5_hidden Epoch 161 loss:3.304011845281295 ael:0.0023608147155881488 cl:33.01650983224849

filename: 0_5_hidden Epoch 162 loss:3.3048426665960062 ael:0.0023733659637649148 cl:33.02469256613929

filename: 0_5_hidden Epoch 163 loss:3.303796173967151 ael:0.0023410948403618666 cl:33.01455028973502

filename: 0_5_hidden Epoch 164 loss:3.303832015618502 ael:0.002347976825215781 cl:33.01483993315101

filename: 0_5_hidden Epoch 165 loss:3.3043104745417615 ael:0.002338124781612106 cl:33.01972302614346

filename: 0_5_hidden Epoch 166 loss:3.3035749888631436 ael:0.0023233798171819835 cl:33.012515642103125

filename: 0_5_hidden Epoch 167 loss:3.303816516009384 ael:0.0023161365450690085 cl:33.0150033411338

filename: 0_5_hidden Epoch 168 loss:3.303879625080671 ael:0.002312035733275941 cl:33.01567543254179

filename: 0_5_hidden Epoch 169 loss:3.303627335093465 ael:0.002322424649025293 cl:33.01304865152388

filename: 0_5_hidden Epoch 170 loss:3.3028790192869186 ael:0.002304845425115687 cl:33.0057412746162

filename: 0_5_hidden Epoch 171 loss:3.3032068941114794 ael:0.0023021229849449127 cl:33.00904723312661

filename: 0_5_hidden Epoch 172 loss:3.3027335815521903 ael:0.002278839868281748 cl:33.00454695161363

filename: 0_5_hidden Epoch 173 loss:3.303183306233716 ael:0.0022788053471520004 cl:33.009044498901616

filename: 0_5_hidden Epoch 174 loss:3.3025843179773458 ael:0.002280237107066022 cl:33.003040343691126

filename: 0_5_hidden Epoch 175 loss:3.3024951744041164 ael:0.0022681133964569528 cl:33.002270128340804

filename: 0_5_hidden Epoch 176 loss:3.3030021532613554 ael:0.002257863819669695 cl:33.00744243978397

filename: 0_5_hidden Epoch 177 loss:3.3025467896250156 ael:0.0022654076542864394 cl:33.00281337612007

filename: 0_5_hidden Epoch 178 loss:3.3027748644688164 ael:0.0022551840709486345 cl:33.005196305458625

filename: 0_5_hidden Epoch 179 loss:3.302764498735992 ael:0.0022415202379764765 cl:33.00522932364612

filename: 0_5_hidden Epoch 180 loss:3.3019689136123964 ael:0.002226910746647353 cl:32.99741953712236

filename: 0_5_hidden Epoch 181 loss:3.302400565550848 ael:0.002226397129845874 cl:33.001741208730444

filename: 0_5_hidden Epoch 182 loss:3.302371274838997 ael:0.0022248044640698606 cl:33.00146424972079

filename: 0_5_hidden Epoch 183 loss:3.3021241641640184 ael:0.0022162606632078067 cl:32.99907857155627

filename: 0_5_hidden Epoch 184 loss:3.3017960709972214 ael:0.002212556595206756 cl:32.99583462877297

filename: 0_5_hidden Epoch 185 loss:3.302061709447026 ael:0.002216429655900935 cl:32.998452327214935

filename: 0_5_hidden Epoch 186 loss:3.3014579161245146 ael:0.0021794231981958363 cl:32.99278446246692

filename: 0_5_hidden Epoch 187 loss:3.3019671818597196 ael:0.0021790004486655612 cl:32.997881326052955

filename: 0_5_hidden Epoch 188 loss:3.3015112565660747 ael:0.0021735208584063243 cl:32.9933768786508

filename: 0_5_hidden Epoch 189 loss:3.3016813748503386 ael:0.002183788745841544 cl:32.99497537589861

filename: 0_5_hidden Epoch 190 loss:3.301628631992171 ael:0.00217392130328626 cl:32.994546611303285

filename: 0_5_hidden Epoch 191 loss:3.301443204872076 ael:0.0021750686512351947 cl:32.99268088467557

filename: 0_5_hidden Epoch 192 loss:3.301941577222057 ael:0.002179640583687602 cl:32.99761888271949

filename: 0_5_hidden Epoch 193 loss:3.3017231782149348 ael:0.0021541167658379965 cl:32.99569014058201

filename: 0_5_hidden Epoch 194 loss:3.3014738021792183 ael:0.0021502371190009243 cl:32.99323520537445

filename: 0_5_hidden Epoch 195 loss:3.301355161078989 ael:0.0021488302608495646 cl:32.99206281073337

filename: 0_5_hidden Epoch 196 loss:3.302176343155522 ael:0.002124598092008547 cl:33.000516980622294

filename: 0_5_hidden Epoch 197 loss:3.302167128786553 ael:0.0021409519103702417 cl:33.000261300614916

filename: 0_5_hidden Epoch 198 loss:3.3016640134245807 ael:0.0021281797897767076 cl:32.995357873841314

filename: 0_5_hidden Epoch 199 loss:3.301345977833154 ael:0.0021487738424292965 cl:32.991971539259914

filename: 0_5_hidden Epoch 200 loss:3.301161517355348 ael:0.002125146956527103 cl:32.99036322016566

filename: 0_5_hidden Epoch 201 loss:3.3012276923435526 ael:0.002121052362588005 cl:32.99106589293499

filename: 0_5_hidden Epoch 202 loss:3.300703662427369 ael:0.002117997120842968 cl:32.98585618147439

filename: 0_5_hidden Epoch 203 loss:3.3003523637939134 ael:0.0021025389214804264 cl:32.98249779085686

filename: 0_5_hidden Epoch 204 loss:3.301352406201297 ael:0.0021072794570896015 cl:32.99245079556941

filename: 0_5_hidden Epoch 205 loss:3.3013830555724484 ael:0.0020975555873650074 cl:32.99285450719423

filename: 0_5_hidden Epoch 206 loss:3.300696999963304 ael:0.0020990869215907985 cl:32.98597867752063

filename: 0_5_hidden Epoch 207 loss:3.300382336717186 ael:0.002093277448583034 cl:32.982890088360314

filename: 0_5_hidden Epoch 208 loss:3.301095624396534 ael:0.002092669324209804 cl:32.99002907988912

filename: 0_5_hidden Epoch 209 loss:3.3000699535288414 ael:0.0020773191429283634 cl:32.97992587877223

filename: 0_5_hidden Epoch 210 loss:3.30103016735372 ael:0.00209323091200372 cl:32.98936890518348

filename: 0_5_hidden Epoch 211 loss:3.3002554148459606 ael:0.002085488050385085 cl:32.981698795444636

filename: 0_5_hidden Epoch 212 loss:3.299966021279574 ael:0.0020839965259780136 cl:32.9788197894715

filename: 0_5_hidden Epoch 213 loss:3.299862248104105 ael:0.002081405665139359 cl:32.97780795869666

filename: 0_5_hidden Epoch 214 loss:3.299824865665482 ael:0.002094004552041786 cl:32.977308178793315

filename: 0_5_hidden Epoch 215 loss:3.2997683644967153 ael:0.0020836792179603973 cl:32.97684637679869

filename: 0_5_hidden Epoch 216 loss:3.299929566291145 ael:0.0020873521339811693 cl:32.97842166848378

filename: 0_5_hidden Epoch 217 loss:3.299061262636392 ael:0.0020711441324235036 cl:32.969900667619356

filename: 0_5_hidden Epoch 218 loss:3.2995005297526343 ael:0.002080283533959251 cl:32.974201975475864

filename: 0_5_hidden Epoch 219 loss:3.300441381049483 ael:0.002080658012312536 cl:32.9836067534761

filename: 0_5_hidden Epoch 220 loss:3.299604654984547 ael:0.002069941742775705 cl:32.97534667129578

filename: 0_5_hidden Epoch 221 loss:3.299435598441039 ael:0.002071068528786341 cl:32.973644841399334

filename: 0_5_hidden Epoch 222 loss:3.2985816090266424 ael:0.002060430482137606 cl:32.96521135187265

filename: 0_5_hidden Epoch 223 loss:3.2992061902014695 ael:0.002048324381714607 cl:32.9715782007222

filename: 0_5_hidden Epoch 224 loss:3.299341988505902 ael:0.0020670784276829077 cl:32.972748648822545

filename: 0_5_hidden Epoch 225 loss:3.2988992912167987 ael:0.0020435239919791514 cl:32.96855719487193

filename: 0_5_hidden Epoch 226 loss:3.298694937196496 ael:0.002018657976138202 cl:32.96676228144398

filename: 0_5_hidden Epoch 227 loss:3.2996273017717312 ael:0.0020398441756535905 cl:32.97587408393165

filename: 0_5_hidden Epoch 228 loss:3.2985820354327955 ael:0.0020343773873743513 cl:32.96547608141165

filename: 0_5_hidden Epoch 229 loss:3.29937850266671 ael:0.0020328524268639785 cl:32.97345601695858

filename: 0_5_hidden Epoch 230 loss:3.299038695962462 ael:0.0020419922175139524 cl:32.96996657796486

filename: 0_5_hidden Epoch 231 loss:3.29889244989077 ael:0.002016289445346838 cl:32.96876114438754

filename: 0_5_hidden Epoch 232 loss:3.2993274389208564 ael:0.002005388040833271 cl:32.97322006287064

filename: 0_5_hidden Epoch 233 loss:3.2986340774440843 ael:0.0020003561213789663 cl:32.96633672829504

filename: 0_5_hidden Epoch 234 loss:3.298914265671053 ael:0.0019899000570656076 cl:32.969243187946624

filename: 0_5_hidden Epoch 235 loss:3.2987814138821303 ael:0.0020151871196399567 cl:32.967661824560665

filename: 0_5_hidden Epoch 236 loss:3.298145094194497 ael:0.0019872568083471507 cl:32.96157789729854

filename: 0_5_hidden Epoch 237 loss:3.2988692293428397 ael:0.0019814017768926754 cl:32.96887781618104

filename: 0_5_hidden Epoch 238 loss:3.298221789762726 ael:0.0019893947879274995 cl:32.962323442377645

filename: 0_5_hidden Epoch 239 loss:3.2981639259962376 ael:0.0019782774086488527 cl:32.96185600747993

filename: 0_5_hidden Epoch 240 loss:3.298031740953229 ael:0.0020035412984297555 cl:32.96028150732146

filename: 0_5_hidden Epoch 241 loss:3.2986910851322575 ael:0.002013200108452695 cl:32.96677839861677

filename: 0_5_hidden Epoch 242 loss:3.2980603483009494 ael:0.001978526189176577 cl:32.96081776430682

filename: 0_5_hidden Epoch 243 loss:3.298080795623908 ael:0.001978685947442405 cl:32.96102062259155

filename: 0_5_hidden Epoch 244 loss:3.2976337699137033 ael:0.0019794420913645306 cl:32.95654278585356

filename: 0_5_hidden Epoch 245 loss:3.2973393101926582 ael:0.0019455954991018372 cl:32.95393668442941

filename: 0_5_hidden Epoch 246 loss:3.29761502081881 ael:0.001972137907068534 cl:32.95642835953657

filename: 0_5_hidden Epoch 247 loss:3.297112106700562 ael:0.0019500604097575315 cl:32.95161997897312

filename: 0_5_hidden Epoch 248 loss:3.297376825673075 ael:0.001964132448365292 cl:32.954126467923786

filename: 0_5_hidden Epoch 249 loss:3.2963612738585493 ael:0.0019549358197402337 cl:32.94406288540431

filename: 0_5_hidden Epoch 250 loss:3.2974889664569274 ael:0.0019503651042078606 cl:32.955385546257766

/tmp/ipykernel_336185/680421385.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
/tmp/ipykernel_336185/680421385.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3  Label
0        0.022105  0.082611  0.016367 -0.008482      1
1       -0.021102 -0.016627 -0.019215  0.065030      2
2        0.024379  0.078914  0.021165 -0.000082      1
3        0.081803 -0.063346  0.083219 -0.039764      4
4       -0.021111 -0.016659 -0.019223  0.064993      2
...           ...       ...       ...       ...    ...
1270336  0.078161  0.064338  0.077068  0.120919      3
1270337 -0.021096 -0.016606 -0.019210  0.065053      2
1270338 -0.021099 -0.016617 -0.019213  0.065041      2
1270339 -0.021096 -0.016608 -0.019211  0.065051      2
1270340 -0.020886 -0.015872 -0.019040  0.065880      2

[1270341 rows x 5 columns]

Davies-Bouldin Score: 0.08936578093614549

               0         1         2         3  Label
0       0.011881  0.087082  0.010946 -0.016945      0
1      -0.021103 -0.016639 -0.019216  0.065000      2
2       0.020190  0.079851  0.018867 -0.007949      1
3       0.073208  0.064386  0.073602  0.114104      3
4       0.020900  0.079577  0.018351 -0.006431      1
...          ...       ...       ...       ...    ...
519951  0.020511  0.081092  0.018907 -0.008044      1
519952  0.080000 -0.054742  0.083529 -0.042371      4
519953  0.015863  0.052291  0.014124  0.005364      0
519954  0.022214  0.078429  0.017312 -0.005911      1
519955  0.078161  0.064338  0.077068  0.120919      3

[519956 rows x 5 columns]

               0         1         2         3  Label
0       0.015812  0.051996  0.014075  0.005650      0
1       0.011784  0.087089  0.010847 -0.017110      0
2       0.019690  0.081692  0.018359 -0.010074      1
3       0.020907  0.069500  0.020198  0.007770      1
4       0.016099  0.057165  0.018325  0.007545      0
...          ...       ...       ...       ...    ...
649942  0.021177  0.079235  0.018633 -0.005763      1
649943  0.015318  0.055628  0.017774  0.008965      0
649944  0.015170  0.055840  0.017612  0.008528      0
649945  0.078668  0.065932  0.079394  0.120629      3
649946 -0.026759 -0.029997 -0.022332  0.064348      2

[649947 rows x 5 columns]

2_3_hidden

cuda

[0.0, 1.0, 4.0, 5.0]

pick completo
82 4

filename: 2_3_hidden Epoch 1 loss:3.654777131083867 ael:0.025485415009113596 cl:36.29291654799295

filename: 2_3_hidden Epoch 2 loss:3.0528434958794843 ael:0.017913751181723732 cl:30.349296928099964

filename: 2_3_hidden Epoch 3 loss:2.9411237241457338 ael:0.016901941595437085 cl:29.24221729389999

filename: 2_3_hidden Epoch 4 loss:2.7924623940463946 ael:0.016607993470287234 cl:27.758543531531874

filename: 2_3_hidden Epoch 5 loss:2.695767977112985 ael:0.016825926964647017 cl:26.78941999764546

filename: 2_3_hidden Epoch 6 loss:2.657001261437393 ael:0.016724725940667155 cl:26.40276489439218

filename: 2_3_hidden Epoch 7 loss:2.630346550727668 ael:0.01652591950013353 cl:26.138205870985985

filename: 2_3_hidden Epoch 8 loss:2.6089994050157457 ael:0.016248563458920336 cl:25.927507915574573

filename: 2_3_hidden Epoch 9 loss:2.591693005322114 ael:0.015867964323463282 cl:25.758249954037044

filename: 2_3_hidden Epoch 10 loss:2.5753290349536617 ael:0.015482175910501215 cl:25.598468128105868

filename: 2_3_hidden Epoch 11 loss:2.560475929275803 ael:0.015150478259032674 cl:25.45325406414011

filename: 2_3_hidden Epoch 12 loss:2.5422526965241716 ael:0.014818386908344743 cl:25.274342645769533

filename: 2_3_hidden Epoch 13 loss:2.5258999982362855 ael:0.01455438643967247 cl:25.113455670035403

filename: 2_3_hidden Epoch 14 loss:2.5041717838334 ael:0.014386781847228438 cl:24.897849568206333

filename: 2_3_hidden Epoch 15 loss:2.4890499283438143 ael:0.014257785831274383 cl:24.747920943990998

filename: 2_3_hidden Epoch 16 loss:2.4740918121584086 ael:0.01413084780980843 cl:24.59960917480614

filename: 2_3_hidden Epoch 17 loss:2.4616718507250366 ael:0.013998293267871739 cl:24.476735096910726

filename: 2_3_hidden Epoch 18 loss:2.4526485360591956 ael:0.0139092809049939 cl:24.38739208293998

filename: 2_3_hidden Epoch 19 loss:2.4408897773322202 ael:0.013776792527452293 cl:24.271129398890164

filename: 2_3_hidden Epoch 20 loss:2.43259941154848 ael:0.013670634956013047 cl:24.189287279611047

filename: 2_3_hidden Epoch 21 loss:2.4254978135552094 ael:0.013547999975107023 cl:24.11949764775193

filename: 2_3_hidden Epoch 22 loss:2.4182750912707136 ael:0.013370627132446869 cl:24.049044168513753

filename: 2_3_hidden Epoch 23 loss:2.41082392681552 ael:0.013224084681892038 cl:23.975997961085774

filename: 2_3_hidden Epoch 24 loss:2.40361020916506 ael:0.012985594482059874 cl:23.906245689677156

filename: 2_3_hidden Epoch 25 loss:2.3980530403230502 ael:0.01278739858959022 cl:23.85265596340532

filename: 2_3_hidden Epoch 26 loss:2.390174847379651 ael:0.012613522570577714 cl:23.77561281297518

filename: 2_3_hidden Epoch 27 loss:2.385800603169786 ael:0.012374218733938229 cl:23.734263414274093

filename: 2_3_hidden Epoch 28 loss:2.379901328974444 ael:0.01216908684696334 cl:23.677321948434997

filename: 2_3_hidden Epoch 29 loss:2.37241024710238 ael:0.01196488464737068 cl:23.604453139978908

filename: 2_3_hidden Epoch 30 loss:2.364657341948022 ael:0.011779117088261282 cl:23.528781802757926

filename: 2_3_hidden Epoch 31 loss:2.356573689931437 ael:0.0116875805251766 cl:23.44886066408261

filename: 2_3_hidden Epoch 32 loss:2.3467608009991436 ael:0.011655050311515957 cl:23.351057048725046

filename: 2_3_hidden Epoch 33 loss:2.336176822974306 ael:0.011501004581235897 cl:23.246757739264034

filename: 2_3_hidden Epoch 34 loss:2.330332737699475 ael:0.011331779832329155 cl:23.19000914433728

filename: 2_3_hidden Epoch 35 loss:2.323312690117113 ael:0.01094500665773091 cl:23.123676408568155

filename: 2_3_hidden Epoch 36 loss:2.3173732241291716 ael:0.010642321692379799 cl:23.067308589816093

filename: 2_3_hidden Epoch 37 loss:2.3147736234671394 ael:0.010509146648552774 cl:23.04264431576366

filename: 2_3_hidden Epoch 38 loss:2.3104091695226403 ael:0.010070169653930783 cl:23.003389579770356

filename: 2_3_hidden Epoch 39 loss:2.3052891682347525 ael:0.009912438951489647 cl:22.95376683642035

filename: 2_3_hidden Epoch 40 loss:2.3026674892348438 ael:0.0095261951762001 cl:22.931412495672703

filename: 2_3_hidden Epoch 41 loss:2.2989548594974307 ael:0.009344207229688713 cl:22.896106063023858

filename: 2_3_hidden Epoch 42 loss:2.296024318460537 ael:0.008978186496476512 cl:22.870460907078307

filename: 2_3_hidden Epoch 43 loss:2.2937693480078294 ael:0.008840099133838363 cl:22.849292066434156

filename: 2_3_hidden Epoch 44 loss:2.2899091916725687 ael:0.008569485484654053 cl:22.813396621657454

filename: 2_3_hidden Epoch 45 loss:2.286829652831606 ael:0.008463473732579429 cl:22.783661336354587

filename: 2_3_hidden Epoch 46 loss:2.283211611494746 ael:0.008442405991366326 cl:22.747691635852274

filename: 2_3_hidden Epoch 47 loss:2.2789137657407834 ael:0.008127836266794475 cl:22.70785887668962

filename: 2_3_hidden Epoch 48 loss:2.2767644414840187 ael:0.008010412713622867 cl:22.687539862225886

filename: 2_3_hidden Epoch 49 loss:2.2740699365411117 ael:0.00780362868048858 cl:22.662662623369176

filename: 2_3_hidden Epoch 50 loss:2.270169638623686 ael:0.007434727093704682 cl:22.627348709365595

filename: 2_3_hidden Epoch 51 loss:2.2629227786851316 ael:0.007067536043430901 cl:22.558551993059076

filename: 2_3_hidden Epoch 52 loss:2.2605588534927885 ael:0.006807535034449361 cl:22.53751275850379

filename: 2_3_hidden Epoch 53 loss:2.257918682637746 ael:0.006603284283340579 cl:22.513153549121775

filename: 2_3_hidden Epoch 54 loss:2.254113000655628 ael:0.006369451337377541 cl:22.477435045916103

filename: 2_3_hidden Epoch 55 loss:2.251575180531844 ael:0.00614013105856113 cl:22.45435005426407

filename: 2_3_hidden Epoch 56 loss:2.2476105274146665 ael:0.005946764469468769 cl:22.416637198432632

filename: 2_3_hidden Epoch 57 loss:2.244921159323143 ael:0.005752642733964224 cl:22.39168476054202

filename: 2_3_hidden Epoch 58 loss:2.2413745908390568 ael:0.00560786654481806 cl:22.35766679275295

filename: 2_3_hidden Epoch 59 loss:2.2384739455402545 ael:0.0054327993842415035 cl:22.330411017588947

filename: 2_3_hidden Epoch 60 loss:2.2357490872964263 ael:0.005293003856027296 cl:22.304560401517413

filename: 2_3_hidden Epoch 61 loss:2.2327525049609984 ael:0.005123148570182029 cl:22.276293155615743

filename: 2_3_hidden Epoch 62 loss:2.2306187740000696 ael:0.004945602244729146 cl:22.25673127660285

filename: 2_3_hidden Epoch 63 loss:2.2275683600455523 ael:0.004826440339852327 cl:22.22741877352414

filename: 2_3_hidden Epoch 64 loss:2.2257946306110723 ael:0.004734498045566042 cl:22.210600908683695

filename: 2_3_hidden Epoch 65 loss:2.223660419776064 ael:0.004608652708908346 cl:22.1905172376529

filename: 2_3_hidden Epoch 66 loss:2.2210998673639866 ael:0.004520564266346375 cl:22.16579262977061

filename: 2_3_hidden Epoch 67 loss:2.2192164307217235 ael:0.004403722968203036 cl:22.14812667084777

filename: 2_3_hidden Epoch 68 loss:2.2164929577189945 ael:0.004300354684702419 cl:22.121925620929055

filename: 2_3_hidden Epoch 69 loss:2.2156245653396067 ael:0.004224474537335007 cl:22.114000475924946

filename: 2_3_hidden Epoch 70 loss:2.2140561388400584 ael:0.004155404136564239 cl:22.099006948911626

filename: 2_3_hidden Epoch 71 loss:2.212799087369248 ael:0.00410338071750353 cl:22.086956660708655

filename: 2_3_hidden Epoch 72 loss:2.2106942601258988 ael:0.004045456253310397 cl:22.06648761066406

filename: 2_3_hidden Epoch 73 loss:2.209002731408438 ael:0.0039851945539735225 cl:22.05017494151126

filename: 2_3_hidden Epoch 74 loss:2.2078067785857813 ael:0.00393180833262981 cl:22.03874927467626

filename: 2_3_hidden Epoch 75 loss:2.207297751072632 ael:0.003896124924247725 cl:22.034015861866266

filename: 2_3_hidden Epoch 76 loss:2.2049672645314233 ael:0.0038499509205987283 cl:22.011172732257325

filename: 2_3_hidden Epoch 77 loss:2.2040478802569536 ael:0.0037954895165255393 cl:22.002523496747017

filename: 2_3_hidden Epoch 78 loss:2.202938979410607 ael:0.003778767945771941 cl:21.991601732114088

filename: 2_3_hidden Epoch 79 loss:2.2025398275936428 ael:0.00373396690314542 cl:21.988058226911917

filename: 2_3_hidden Epoch 80 loss:2.200517805495664 ael:0.003702710446463164 cl:21.968150555763554

filename: 2_3_hidden Epoch 81 loss:2.1999226440878017 ael:0.0036560086802795845 cl:21.962665934601556

filename: 2_3_hidden Epoch 82 loss:2.1978379513906394 ael:0.003615971649038408 cl:21.942219366845876

filename: 2_3_hidden Epoch 83 loss:2.1975197225566143 ael:0.003592770418080086 cl:21.939269095983196

filename: 2_3_hidden Epoch 84 loss:2.196570748179827 ael:0.00359339547732974 cl:21.929773125635542

filename: 2_3_hidden Epoch 85 loss:2.1955786345364605 ael:0.0035444815984310876 cl:21.920341131479844

filename: 2_3_hidden Epoch 86 loss:2.1947319099031715 ael:0.0035058072909400243 cl:21.91226059684287

filename: 2_3_hidden Epoch 87 loss:2.1937137987950575 ael:0.003486565443460637 cl:21.90227192802274

filename: 2_3_hidden Epoch 88 loss:2.1915216564160325 ael:0.003460001502627046 cl:21.880616142697956

filename: 2_3_hidden Epoch 89 loss:2.1919769450779194 ael:0.00343323403783712 cl:21.885436697174672

filename: 2_3_hidden Epoch 90 loss:2.1913676958774095 ael:0.0034016649985025415 cl:21.87965992157874

filename: 2_3_hidden Epoch 91 loss:2.189721574925858 ael:0.0033821226686046903 cl:21.86339412694392

filename: 2_3_hidden Epoch 92 loss:2.1893715500507667 ael:0.003390506537154737 cl:21.859809997936953

filename: 2_3_hidden Epoch 93 loss:2.188433307061053 ael:0.0033451799716441083 cl:21.850880850916322

filename: 2_3_hidden Epoch 94 loss:2.187128930190659 ael:0.0033439033181228137 cl:21.837849880042285

filename: 2_3_hidden Epoch 95 loss:2.187214960263151 ael:0.003317131608523398 cl:21.838977873973224

filename: 2_3_hidden Epoch 96 loss:2.1868491278475393 ael:0.00332138162000616 cl:21.83527705721233

filename: 2_3_hidden Epoch 97 loss:2.1860404975469345 ael:0.0032931942515342203 cl:21.827472647571046

filename: 2_3_hidden Epoch 98 loss:2.185397867113352 ael:0.0032707065667004235 cl:21.82127119957105

filename: 2_3_hidden Epoch 99 loss:2.1844777555164434 ael:0.003256850834789119 cl:21.81220864083456

filename: 2_3_hidden Epoch 100 loss:2.183940185841335 ael:0.0032165019858202077 cl:21.807236429141916

filename: 2_3_hidden Epoch 101 loss:2.1828147319105007 ael:0.003225753723872122 cl:21.795889370143414

filename: 2_3_hidden Epoch 102 loss:2.181614553920277 ael:0.0032134895097798385 cl:21.78401023732579

filename: 2_3_hidden Epoch 103 loss:2.1794207466604267 ael:0.003196742555899065 cl:21.762239634342816

filename: 2_3_hidden Epoch 104 loss:2.179897802638943 ael:0.003184875013254856 cl:21.767128867947537

filename: 2_3_hidden Epoch 105 loss:2.1785964341429263 ael:0.003158016379925159 cl:21.754383784597334

filename: 2_3_hidden Epoch 106 loss:2.1782918795133415 ael:0.0031384408311683014 cl:21.75153400198273

filename: 2_3_hidden Epoch 107 loss:2.1773778541499507 ael:0.0031356104434013578 cl:21.742422028728154

filename: 2_3_hidden Epoch 108 loss:2.1769784325328856 ael:0.0031362390601988527 cl:21.738421555446543

filename: 2_3_hidden Epoch 109 loss:2.1755941542189405 ael:0.0030951576110332417 cl:21.724989576508168

filename: 2_3_hidden Epoch 110 loss:2.1748432469675723 ael:0.003102954934428967 cl:21.71740252395039

filename: 2_3_hidden Epoch 111 loss:2.1748314770748434 ael:0.003072747682223132 cl:21.717586870102778

filename: 2_3_hidden Epoch 112 loss:2.1745583768529086 ael:0.003064238095644016 cl:21.71494099918915

filename: 2_3_hidden Epoch 113 loss:2.174240648139106 ael:0.0030597895911341766 cl:21.71180816642616

filename: 2_3_hidden Epoch 114 loss:2.174458159579207 ael:0.0030380317982591173 cl:21.714200880864393

filename: 2_3_hidden Epoch 115 loss:2.172163110145408 ael:0.00301548242350691 cl:21.69147587373205

filename: 2_3_hidden Epoch 116 loss:2.1714975239061145 ael:0.0030094163410704705 cl:21.684880660927814

filename: 2_3_hidden Epoch 117 loss:2.1712573438315936 ael:0.00299318793678021 cl:21.68264114111662

filename: 2_3_hidden Epoch 118 loss:2.170128854315566 ael:0.0029700393313206682 cl:21.671587742541146

filename: 2_3_hidden Epoch 119 loss:2.1698083704256494 ael:0.0029614522392638837 cl:21.668468774336837

filename: 2_3_hidden Epoch 120 loss:2.1690851192840417 ael:0.0029581158448664887 cl:21.661269639497217

filename: 2_3_hidden Epoch 121 loss:2.1690552537127035 ael:0.002938870844366687 cl:21.661163442160774

filename: 2_3_hidden Epoch 122 loss:2.1688035807936736 ael:0.002921593902378252 cl:21.658819492420424

filename: 2_3_hidden Epoch 123 loss:2.168532883464966 ael:0.0028893157889441404 cl:21.65643528913674

filename: 2_3_hidden Epoch 124 loss:2.1680475145011493 ael:0.0028653815990527737 cl:21.65182094146376

filename: 2_3_hidden Epoch 125 loss:2.1671350933611393 ael:0.002846021938002314 cl:21.642890324087247

filename: 2_3_hidden Epoch 126 loss:2.1675473474694984 ael:0.0028239771383358975 cl:21.64723326816507

filename: 2_3_hidden Epoch 127 loss:2.167306931446428 ael:0.0027983554112364327 cl:21.645085341256596

filename: 2_3_hidden Epoch 128 loss:2.1648978840802675 ael:0.002776514426722829 cl:21.621213288086913

filename: 2_3_hidden Epoch 129 loss:2.165930711178352 ael:0.0027414491473198564 cl:21.631892237650312

filename: 2_3_hidden Epoch 130 loss:2.1651827458130275 ael:0.002720361374841836 cl:21.624623444741186

filename: 2_3_hidden Epoch 131 loss:2.1644678756027766 ael:0.0026865209253984453 cl:21.617813171899837

filename: 2_3_hidden Epoch 132 loss:2.1656211335211992 ael:0.002669971813979235 cl:21.62951122191937

filename: 2_3_hidden Epoch 133 loss:2.163597648355948 ael:0.002627005489004027 cl:21.60970601407082

filename: 2_3_hidden Epoch 134 loss:2.1642284976804387 ael:0.0025984652479367114 cl:21.616299899699897

filename: 2_3_hidden Epoch 135 loss:2.1634830310940742 ael:0.002594373085151386 cl:21.608886190082718

filename: 2_3_hidden Epoch 136 loss:2.162790865353916 ael:0.0025614608296208367 cl:21.60229365300873

filename: 2_3_hidden Epoch 137 loss:2.1632250736912955 ael:0.00252937738111106 cl:21.606956574256007

filename: 2_3_hidden Epoch 138 loss:2.1611470004705633 ael:0.0025213216771906286 cl:21.586256380314413

filename: 2_3_hidden Epoch 139 loss:2.1615196754750996 ael:0.0025006783476862397 cl:21.590189597528912

filename: 2_3_hidden Epoch 140 loss:2.1614171646373426 ael:0.002464190669382768 cl:21.5895293523436

filename: 2_3_hidden Epoch 141 loss:2.1610617459063297 ael:0.002429090877186631 cl:21.586326114509415

filename: 2_3_hidden Epoch 142 loss:2.1594949914547414 ael:0.0024042389762578987 cl:21.570907122415043

filename: 2_3_hidden Epoch 143 loss:2.159895784019128 ael:0.0023822581811739087 cl:21.575134877277456

filename: 2_3_hidden Epoch 144 loss:2.159069867561693 ael:0.002375841611074461 cl:21.566939856695093

filename: 2_3_hidden Epoch 145 loss:2.158884868349718 ael:0.0023502766318178265 cl:21.565345511488292

filename: 2_3_hidden Epoch 146 loss:2.1597215011310964 ael:0.0023309418108866616 cl:21.573905172231406

filename: 2_3_hidden Epoch 147 loss:2.1594580732204993 ael:0.0023299136170032357 cl:21.571281224489212

filename: 2_3_hidden Epoch 148 loss:2.1588374660957768 ael:0.0023141993968080064 cl:21.565232277240444

filename: 2_3_hidden Epoch 149 loss:2.1588227799486206 ael:0.002293471203578836 cl:21.56529270404059

filename: 2_3_hidden Epoch 150 loss:2.1588708490295256 ael:0.002282708470256298 cl:21.56588098018066

filename: 2_3_hidden Epoch 151 loss:2.1575014261204912 ael:0.0022745543517727206 cl:21.55226833016976

filename: 2_3_hidden Epoch 152 loss:2.1578420639928915 ael:0.0022578371669980065 cl:21.55584188485923

filename: 2_3_hidden Epoch 153 loss:2.155960554823927 ael:0.0022705931272787934 cl:21.536899218092795

filename: 2_3_hidden Epoch 154 loss:2.1564354629296325 ael:0.0022529808968260036 cl:21.541824409819167

filename: 2_3_hidden Epoch 155 loss:2.1565286015038905 ael:0.0022107867278701515 cl:21.543177754010845

filename: 2_3_hidden Epoch 156 loss:2.1566677836134382 ael:0.0022205329492151022 cl:21.544472135279488

filename: 2_3_hidden Epoch 157 loss:2.155994288947271 ael:0.0021936227986256913 cl:21.538006266174108

filename: 2_3_hidden Epoch 158 loss:2.15548381484721 ael:0.002184324483926542 cl:21.532994532066844

filename: 2_3_hidden Epoch 159 loss:2.154278923838359 ael:0.002176399909251853 cl:21.521024824808475

filename: 2_3_hidden Epoch 160 loss:2.154763200239319 ael:0.002188762659186424 cl:21.52574398174234

filename: 2_3_hidden Epoch 161 loss:2.1550222084979 ael:0.002158071134030963 cl:21.52864097803831

filename: 2_3_hidden Epoch 162 loss:2.1558217952918746 ael:0.0021641041976972306 cl:21.536576518869918

filename: 2_3_hidden Epoch 163 loss:2.1542571927623255 ael:0.002139288661806938 cl:21.52117864528428

filename: 2_3_hidden Epoch 164 loss:2.1535567225402463 ael:0.0021469925201096844 cl:21.51409692187672

filename: 2_3_hidden Epoch 165 loss:2.153412077859368 ael:0.0021157956864993575 cl:21.51296240091324

filename: 2_3_hidden Epoch 166 loss:2.1532547809183598 ael:0.0021150497132507357 cl:21.511396939663783

filename: 2_3_hidden Epoch 167 loss:2.1533147113235747 ael:0.0021110049614356326 cl:21.512036696076393

filename: 2_3_hidden Epoch 168 loss:2.153687367418214 ael:0.002086827179680214 cl:21.516004987384964

filename: 2_3_hidden Epoch 169 loss:2.153451081203378 ael:0.0020872576245813475 cl:21.5136378582405

filename: 2_3_hidden Epoch 170 loss:2.1525794770163684 ael:0.002060765823167141 cl:21.505186694795672

filename: 2_3_hidden Epoch 171 loss:2.1525841294990284 ael:0.0020434031530385255 cl:21.505406878888607

filename: 2_3_hidden Epoch 172 loss:2.151608332141262 ael:0.002050701827853197 cl:21.49557590452225

filename: 2_3_hidden Epoch 173 loss:2.1525786097930824 ael:0.002035346490589765 cl:21.50543224034102

filename: 2_3_hidden Epoch 174 loss:2.1513229869306087 ael:0.0020265855209800065 cl:21.492963630220164

filename: 2_3_hidden Epoch 175 loss:2.151582720932429 ael:0.0020117976984455827 cl:21.49570881769709

filename: 2_3_hidden Epoch 176 loss:2.1505056616404783 ael:0.001983486772192207 cl:21.485221336393252

filename: 2_3_hidden Epoch 177 loss:2.1508537625650996 ael:0.0019715599392325007 cl:21.488821636723436

filename: 2_3_hidden Epoch 178 loss:2.1511564164867867 ael:0.001956380224249227 cl:21.491999976336956

filename: 2_3_hidden Epoch 179 loss:2.1494662245006664 ael:0.0019358827235998394 cl:21.475303009152412

filename: 2_3_hidden Epoch 180 loss:2.150368370439695 ael:0.001933276621062048 cl:21.484350548814174

filename: 2_3_hidden Epoch 181 loss:2.1497059029162577 ael:0.0019385790987460337 cl:21.477672868772693

filename: 2_3_hidden Epoch 182 loss:2.1487692220379477 ael:0.0019215550699933058 cl:21.46847626890825

filename: 2_3_hidden Epoch 183 loss:2.1502135685523567 ael:0.0019158727237363169 cl:21.4829765635988

filename: 2_3_hidden Epoch 184 loss:2.14869430653103 ael:0.0018950592608313816 cl:21.467992083210014

filename: 2_3_hidden Epoch 185 loss:2.1485782773841335 ael:0.0018862898653463597 cl:21.4669194859655

filename: 2_3_hidden Epoch 186 loss:2.1479483862690953 ael:0.0018864976288529326 cl:21.460618508574754

filename: 2_3_hidden Epoch 187 loss:2.1476895920932293 ael:0.0018729405675280166 cl:21.458166134098303

filename: 2_3_hidden Epoch 188 loss:2.1481985795595078 ael:0.0018759646162953172 cl:21.46322575988977

filename: 2_3_hidden Epoch 189 loss:2.147957273637471 ael:0.0018599567887102476 cl:21.460972777203374

filename: 2_3_hidden Epoch 190 loss:2.1472207772666994 ael:0.0018615986489195443 cl:21.453591368768524

filename: 2_3_hidden Epoch 191 loss:2.1484712557462244 ael:0.0018463311221437282 cl:21.46624886924806

filename: 2_3_hidden Epoch 192 loss:2.146744746633846 ael:0.001829150668092315 cl:21.44915556486534

filename: 2_3_hidden Epoch 193 loss:2.1467267437635558 ael:0.0018303007409881304 cl:21.448964021128155

filename: 2_3_hidden Epoch 194 loss:2.1460270848044236 ael:0.001832778177468635 cl:21.441942684676338

filename: 2_3_hidden Epoch 195 loss:2.1461904315358917 ael:0.0018155733099300287 cl:21.44374818322451

filename: 2_3_hidden Epoch 196 loss:2.1456798127973857 ael:0.0018410563480242474 cl:21.4383871662228

filename: 2_3_hidden Epoch 197 loss:2.1445355817027716 ael:0.001866224288515577 cl:21.426693172558494

filename: 2_3_hidden Epoch 198 loss:2.145246067367818 ael:0.0018052726858830124 cl:21.434407570115898

filename: 2_3_hidden Epoch 199 loss:2.144525208469966 ael:0.0018050244692384022 cl:21.42720144663168

filename: 2_3_hidden Epoch 200 loss:2.1452428404565738 ael:0.0017801648787296829 cl:21.434626330176126

filename: 2_3_hidden Epoch 201 loss:2.1444178039370025 ael:0.001791118452571106 cl:21.426266463554423

filename: 2_3_hidden Epoch 202 loss:2.1445191114655007 ael:0.0017884385537320707 cl:21.4273063712146

filename: 2_3_hidden Epoch 203 loss:2.1433491569579295 ael:0.0017866923450207612 cl:21.41562423919854

filename: 2_3_hidden Epoch 204 loss:2.1441426522138975 ael:0.001761038109100849 cl:21.423815760923468

filename: 2_3_hidden Epoch 205 loss:2.143226062838474 ael:0.0017822734328586628 cl:21.41443751298863

filename: 2_3_hidden Epoch 206 loss:2.1432097927545724 ael:0.0017728451270277615 cl:21.414369097870328

filename: 2_3_hidden Epoch 207 loss:2.1436350657807095 ael:0.0017216877513024172 cl:21.419133399167787

filename: 2_3_hidden Epoch 208 loss:2.14294376110901 ael:0.0017652900864564087 cl:21.41178432042184

filename: 2_3_hidden Epoch 209 loss:2.143545934727982 ael:0.0017088874519686215 cl:21.418370093664397

filename: 2_3_hidden Epoch 210 loss:2.142301486886066 ael:0.0017243033096786783 cl:21.405771421997443

filename: 2_3_hidden Epoch 211 loss:2.1426553830261463 ael:0.0017464316114969931 cl:21.40908913411524

filename: 2_3_hidden Epoch 212 loss:2.1425823223898592 ael:0.0017230399176973467 cl:21.40859243273735

filename: 2_3_hidden Epoch 213 loss:2.1412426545892074 ael:0.0017365510708338622 cl:21.39506066299003

filename: 2_3_hidden Epoch 214 loss:2.1420899190656515 ael:0.0017196363972921656 cl:21.403702449539434

filename: 2_3_hidden Epoch 215 loss:2.142278908346982 ael:0.0016935968647569257 cl:21.40585275415493

filename: 2_3_hidden Epoch 216 loss:2.141179066758765 ael:0.001707150678829867 cl:21.39471876686034

filename: 2_3_hidden Epoch 217 loss:2.1406563884862093 ael:0.0017251992508926892 cl:21.389311513499074

filename: 2_3_hidden Epoch 218 loss:2.1398898374856166 ael:0.0016793636719818967 cl:21.38210434531388

filename: 2_3_hidden Epoch 219 loss:2.141023495760949 ael:0.0016955147845059716 cl:21.393279405067798

filename: 2_3_hidden Epoch 220 loss:2.139718167524299 ael:0.0017191392022022742 cl:21.379989911680635

filename: 2_3_hidden Epoch 221 loss:2.13829360222039 ael:0.0016689245409472041 cl:21.366246384447035

filename: 2_3_hidden Epoch 222 loss:2.139381224370521 ael:0.0016728892183377668 cl:21.377082973070767

filename: 2_3_hidden Epoch 223 loss:2.1385161674217037 ael:0.0017490225252953203 cl:21.367671069567617

filename: 2_3_hidden Epoch 224 loss:2.13878881542579 ael:0.001683192738354315 cl:21.37105583626291

filename: 2_3_hidden Epoch 225 loss:2.138989889467864 ael:0.00169364006953164 cl:21.372962113631807

filename: 2_3_hidden Epoch 226 loss:2.137943333176815 ael:0.0016614949049851377 cl:21.3628180001093

filename: 2_3_hidden Epoch 227 loss:2.138102125943355 ael:0.0016572013393630662 cl:21.364448864174925

filename: 2_3_hidden Epoch 228 loss:2.137286048827936 ael:0.0016592515448199106 cl:21.356267587322257

filename: 2_3_hidden Epoch 229 loss:2.136962369448789 ael:0.001695254359852381 cl:21.352670780342557

filename: 2_3_hidden Epoch 230 loss:2.1368862916512983 ael:0.0016409986366022129 cl:21.352452564498652

filename: 2_3_hidden Epoch 231 loss:2.136720789839392 ael:0.0016802499650388515 cl:21.350405037403107

filename: 2_3_hidden Epoch 232 loss:2.1357550125002214 ael:0.0016422063356557096 cl:21.341127635668155

filename: 2_3_hidden Epoch 233 loss:2.1361249041865054 ael:0.0016424026963526874 cl:21.344824639027532

filename: 2_3_hidden Epoch 234 loss:2.1358100006194864 ael:0.0016681995329354718 cl:21.341417629109777

filename: 2_3_hidden Epoch 235 loss:2.1356178017576104 ael:0.0017334780419807194 cl:21.33884282734083

filename: 2_3_hidden Epoch 236 loss:2.134914906007116 ael:0.001650518120265548 cl:21.332643485587575

filename: 2_3_hidden Epoch 237 loss:2.1351634340117807 ael:0.0017615191104794023 cl:21.334018751654934

filename: 2_3_hidden Epoch 238 loss:2.135045764684353 ael:0.0017140059678200962 cl:21.333317176479362

filename: 2_3_hidden Epoch 239 loss:2.1338666088717138 ael:0.0016910585297765742 cl:21.32175511154144

filename: 2_3_hidden Epoch 240 loss:2.1339623059510537 ael:0.001628137348135446 cl:21.323341298362482

filename: 2_3_hidden Epoch 241 loss:2.1344587272033095 ael:0.00164479667568151 cl:21.328138910233974

filename: 2_3_hidden Epoch 242 loss:2.133591885516501 ael:0.0016240811081566474 cl:21.319677673928116

filename: 2_3_hidden Epoch 243 loss:2.13326696270024 ael:0.0016411113493711089 cl:21.316258105246916

filename: 2_3_hidden Epoch 244 loss:2.1332893267921778 ael:0.0016570215093649851 cl:21.31632267521775

filename: 2_3_hidden Epoch 245 loss:2.133235921840305 ael:0.0016177759964351856 cl:21.31618108794741

filename: 2_3_hidden Epoch 246 loss:2.132468336423778 ael:0.0016312315396451436 cl:21.308370669574842

filename: 2_3_hidden Epoch 247 loss:2.1320969444983033 ael:0.00162184104303141 cl:21.304750622290634

filename: 2_3_hidden Epoch 248 loss:2.132455315683847 ael:0.0016147726031427421 cl:21.308405044286147

filename: 2_3_hidden Epoch 249 loss:2.1322188295585955 ael:0.0017051207764186825 cl:21.30513669582813

filename: 2_3_hidden Epoch 250 loss:2.132151337866874 ael:0.0016804282013649556 cl:21.3047087121269

/tmp/ipykernel_336185/680421385.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
/tmp/ipykernel_336185/680421385.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3  Label
0       -0.038899 -0.015251 -0.012395 -0.008615      1
1       -0.005748 -0.016921 -0.016905 -0.019331      0
2       -0.042550 -0.014997 -0.009903 -0.004537      1
3       -0.036816 -0.041898 -0.051817 -0.056025      4
4       -0.006220 -0.017604 -0.017042 -0.019077      0
...           ...       ...       ...       ...    ...
1506821 -0.005985 -0.016722 -0.016546 -0.018870      0
1506822 -0.005106 -0.017266 -0.017017 -0.019385      0
1506823 -0.006003 -0.017412 -0.016783 -0.018795      0
1506824 -0.005998 -0.016703 -0.016514 -0.018830      0
1506825 -0.005625 -0.016882 -0.016868 -0.019308      0

[1506826 rows x 5 columns]

Davies-Bouldin Score: 0.9281617315416393

               0         1         2         3  Label
0      -0.005076 -0.017271 -0.017025 -0.019405      0
1      -0.035247 -0.019979 -0.018830 -0.016359      2
2      -0.039052 -0.016817 -0.012365 -0.007549      1
3      -0.037801 -0.013955 -0.008191 -0.003061      3
4      -0.039878 -0.017101 -0.013101 -0.008520      1
...          ...       ...       ...       ...    ...
519951 -0.038960 -0.017794 -0.013777 -0.009514      1
519952 -0.033858 -0.040549 -0.048197 -0.052028      4
519953 -0.005930 -0.016802 -0.016682 -0.019039      0
519954 -0.036816 -0.014810 -0.010950 -0.007321      1
519955 -0.089317 -0.028779 -0.024179 -0.014263      3

[519956 rows x 5 columns]

               0         1         2         3  Label
0      -0.005772 -0.016928 -0.016912 -0.019336      0
1      -0.005145 -0.017261 -0.017006 -0.019359      0
2      -0.034837 -0.015125 -0.010305 -0.006227      1
3      -0.029073 -0.020538 -0.018717 -0.017412      1
4      -0.005987 -0.017393 -0.016755 -0.018764      0
...          ...       ...       ...       ...    ...
649942 -0.038813 -0.017183 -0.013334 -0.009004      1
649943 -0.006287 -0.017623 -0.017060 -0.019091      0
649944 -0.006102 -0.017573 -0.017015 -0.019056      0
649945 -0.115147 -0.037493 -0.034337 -0.022216      3
649946 -0.039109 -0.012800 -0.006070 -0.000516      2

[649947 rows x 5 columns]

2_4_hidden

cuda

[0.0, 1.0, 3.0, 5.0]

pick completo
82 4

filename: 2_4_hidden Epoch 1 loss:3.728383027206909 ael:0.0259247423879009 cl:37.0245822274864

filename: 2_4_hidden Epoch 2 loss:2.840869597871657 ael:0.017427314406505388 cl:28.23442237226111

filename: 2_4_hidden Epoch 3 loss:2.7483397684480377 ael:0.016802005978042028 cl:27.315377153811465

filename: 2_4_hidden Epoch 4 loss:2.6850117842875454 ael:0.016783568624268358 cl:26.682281676030176

filename: 2_4_hidden Epoch 5 loss:2.632725667128136 ael:0.016795536384879472 cl:26.159300827808742

filename: 2_4_hidden Epoch 6 loss:2.5895447846645627 ael:0.01672485959670518 cl:25.72819877465047

filename: 2_4_hidden Epoch 7 loss:2.5497901071760873 ael:0.016642630257498372 cl:25.3314742898723

filename: 2_4_hidden Epoch 8 loss:2.5216368284979183 ael:0.016514201001899837 cl:25.051225799271517

filename: 2_4_hidden Epoch 9 loss:2.5006618211660254 ael:0.016313067937584913 cl:24.843487048133536

filename: 2_4_hidden Epoch 10 loss:2.482854562402161 ael:0.016082519213081983 cl:24.66771996371657

filename: 2_4_hidden Epoch 11 loss:2.466584986794781 ael:0.015778164858038637 cl:24.508067757689354

filename: 2_4_hidden Epoch 12 loss:2.4474934218445297 ael:0.015477075873844321 cl:24.32016298056116

filename: 2_4_hidden Epoch 13 loss:2.4317168713706057 ael:0.015320784800426195 cl:24.163960403900845

filename: 2_4_hidden Epoch 14 loss:2.4197491388317807 ael:0.015267423083087166 cl:24.044816684909772

filename: 2_4_hidden Epoch 15 loss:2.409276702527047 ael:0.015237563312513563 cl:23.940390919486656

filename: 2_4_hidden Epoch 16 loss:2.3981058003075524 ael:0.015216373822059918 cl:23.8288938053911

filename: 2_4_hidden Epoch 17 loss:2.3880578420817815 ael:0.015201081980778979 cl:23.72856711967563

filename: 2_4_hidden Epoch 18 loss:2.381213400038452 ael:0.01518227562069854 cl:23.660310760811992

filename: 2_4_hidden Epoch 19 loss:2.3707319148454222 ael:0.015171307470627582 cl:23.555605603697096

filename: 2_4_hidden Epoch 20 loss:2.3617335701596107 ael:0.015161268845879412 cl:23.465722518213273

filename: 2_4_hidden Epoch 21 loss:2.357309291247524 ael:0.01515528190106027 cl:23.42153961996406

filename: 2_4_hidden Epoch 22 loss:2.3492490843103884 ael:0.015143697378776145 cl:23.341053400220318

filename: 2_4_hidden Epoch 23 loss:2.3461146742047085 ael:0.01514154950559509 cl:23.30973079203002

filename: 2_4_hidden Epoch 24 loss:2.3364028143462288 ael:0.015133345866141503 cl:23.21269423038176

filename: 2_4_hidden Epoch 25 loss:2.334159210217225 ael:0.015135976622473622 cl:23.19023186392756

filename: 2_4_hidden Epoch 26 loss:2.326142082955618 ael:0.015134625291058844 cl:23.110074108679413

filename: 2_4_hidden Epoch 27 loss:2.319030450069383 ael:0.015129849158658127 cl:23.039005534310967

filename: 2_4_hidden Epoch 28 loss:2.31917017974704 ael:0.015119337043369093 cl:23.040507966906787

filename: 2_4_hidden Epoch 29 loss:2.3144778767728402 ael:0.015110942443855871 cl:22.993668880126275

filename: 2_4_hidden Epoch 30 loss:2.315100444250836 ael:0.015109234342897819 cl:22.999911620989103

filename: 2_4_hidden Epoch 31 loss:2.3118946124415705 ael:0.01509429190178894 cl:22.968002737931066

filename: 2_4_hidden Epoch 32 loss:2.3058111309460143 ael:0.015098303349616869 cl:22.90712777903312

filename: 2_4_hidden Epoch 33 loss:2.3012520341527454 ael:0.015067184556538396 cl:22.86184799523232

filename: 2_4_hidden Epoch 34 loss:2.299090319058227 ael:0.01506436438434152 cl:22.84025907547625

filename: 2_4_hidden Epoch 35 loss:2.299302821958244 ael:0.015043983961973196 cl:22.842587916388535

filename: 2_4_hidden Epoch 36 loss:2.2949895376788487 ael:0.015015710935125567 cl:22.799737808830514

filename: 2_4_hidden Epoch 37 loss:2.29334156794302 ael:0.015000012711452102 cl:22.783415053110353

filename: 2_4_hidden Epoch 38 loss:2.2919006308335095 ael:0.014935564354687424 cl:22.7696502045196

filename: 2_4_hidden Epoch 39 loss:2.2878861960673316 ael:0.014878025580779117 cl:22.730081254247743

filename: 2_4_hidden Epoch 40 loss:2.2850821514210615 ael:0.014789400576017091 cl:22.70292704623949

filename: 2_4_hidden Epoch 41 loss:2.2824655877539413 ael:0.01467708556272289 cl:22.677884546936454

filename: 2_4_hidden Epoch 42 loss:2.284723948334495 ael:0.014571003070810431 cl:22.701528993017295

filename: 2_4_hidden Epoch 43 loss:2.282705214660515 ael:0.014418640429157688 cl:22.68286528266543

filename: 2_4_hidden Epoch 44 loss:2.277916068076153 ael:0.014220324792040866 cl:22.63695696270754

filename: 2_4_hidden Epoch 45 loss:2.2783666755310623 ael:0.013963763856351532 cl:22.644028663635254

filename: 2_4_hidden Epoch 46 loss:2.2758951458488705 ael:0.013521416843056699 cl:22.623736851204463

filename: 2_4_hidden Epoch 47 loss:2.2764149665988245 ael:0.01271545355239242 cl:22.636994630662855

filename: 2_4_hidden Epoch 48 loss:2.272111597441132 ael:0.011704602877346034 cl:22.604069494251174

filename: 2_4_hidden Epoch 49 loss:2.2728680317344265 ael:0.010696927166880296 cl:22.62171058916407

filename: 2_4_hidden Epoch 50 loss:2.269885084506034 ael:0.00986876490113467 cl:22.60016274592364

filename: 2_4_hidden Epoch 51 loss:2.2667782026751224 ael:0.009217462822238918 cl:22.575606969039786

filename: 2_4_hidden Epoch 52 loss:2.2655858899704544 ael:0.008736888476714959 cl:22.568489565559652

filename: 2_4_hidden Epoch 53 loss:2.2636370621110626 ael:0.008328013624089565 cl:22.55309001018143

filename: 2_4_hidden Epoch 54 loss:2.258274321070222 ael:0.00794958176014058 cl:22.50324690910354

filename: 2_4_hidden Epoch 55 loss:2.2576050914867807 ael:0.0076784363031998076 cl:22.499266099026592

filename: 2_4_hidden Epoch 56 loss:2.2572075456750698 ael:0.0074136335795695375 cl:22.497938633276544

filename: 2_4_hidden Epoch 57 loss:2.2544652626531563 ael:0.007184121039483737 cl:22.47281094457027

filename: 2_4_hidden Epoch 58 loss:2.2532534981225534 ael:0.00695913476467371 cl:22.46294313190343

filename: 2_4_hidden Epoch 59 loss:2.251231049494678 ael:0.006686951300971195 cl:22.44544049168941

filename: 2_4_hidden Epoch 60 loss:2.251595314112775 ael:0.006365634618688358 cl:22.45229632616199

filename: 2_4_hidden Epoch 61 loss:2.2498568327967283 ael:0.005941902102378168 cl:22.439148844962492

filename: 2_4_hidden Epoch 62 loss:2.246942817113666 ael:0.005472641358861321 cl:22.414701288000266

filename: 2_4_hidden Epoch 63 loss:2.2445470746789082 ael:0.005065790950433198 cl:22.39481238085487

filename: 2_4_hidden Epoch 64 loss:2.244437692953355 ael:0.00480848016464629 cl:22.396291638105854

filename: 2_4_hidden Epoch 65 loss:2.2435411797248794 ael:0.004583037823650336 cl:22.389580948379287

filename: 2_4_hidden Epoch 66 loss:2.2423946312406655 ael:0.004422016181769537 cl:22.379725690451732

filename: 2_4_hidden Epoch 67 loss:2.239905301610447 ael:0.004311914921474809 cl:22.35593336879

filename: 2_4_hidden Epoch 68 loss:2.238576338386162 ael:0.004233608290368775 cl:22.34342686511737

filename: 2_4_hidden Epoch 69 loss:2.2381895045140925 ael:0.0041592480605808805 cl:22.340302101698363

filename: 2_4_hidden Epoch 70 loss:2.2365144555043894 ael:0.004095203923818836 cl:22.32419202998913

filename: 2_4_hidden Epoch 71 loss:2.235383703808314 ael:0.004031865888109137 cl:22.31351789690014

filename: 2_4_hidden Epoch 72 loss:2.2344371238072505 ael:0.0039830086212897225 cl:22.30454069146294

filename: 2_4_hidden Epoch 73 loss:2.2343147942865698 ael:0.003946199764894197 cl:22.303685461439237

filename: 2_4_hidden Epoch 74 loss:2.2326741338866274 ael:0.0038815588643348574 cl:22.287925309406084

filename: 2_4_hidden Epoch 75 loss:2.2302890051275512 ael:0.003831325401278282 cl:22.264576329505964

filename: 2_4_hidden Epoch 76 loss:2.2309445257984213 ael:0.0038074069316690554 cl:22.271370728914448

filename: 2_4_hidden Epoch 77 loss:2.229172216646816 ael:0.003766486676185374 cl:22.254056842711766

filename: 2_4_hidden Epoch 78 loss:2.22782268296808 ael:0.003715375319407957 cl:22.241072621087014

filename: 2_4_hidden Epoch 79 loss:2.2266260908367896 ael:0.003681871288542403 cl:22.229441736197643

filename: 2_4_hidden Epoch 80 loss:2.2268376670033225 ael:0.003646369524142546 cl:22.231912514806805

filename: 2_4_hidden Epoch 81 loss:2.2247024857865525 ael:0.003559436695087533 cl:22.211429996166565

filename: 2_4_hidden Epoch 82 loss:2.224542082913322 ael:0.0035244146829433278 cl:22.21017623243575

filename: 2_4_hidden Epoch 83 loss:2.2226889426220793 ael:0.003487990874596972 cl:22.192009050654555

filename: 2_4_hidden Epoch 84 loss:2.2200347270006295 ael:0.003417333955575416 cl:22.166173472737736

filename: 2_4_hidden Epoch 85 loss:2.2195678941180392 ael:0.0033794915823540865 cl:22.16188356909076

filename: 2_4_hidden Epoch 86 loss:2.2194448275397916 ael:0.00334782082857266 cl:22.160969575972903

filename: 2_4_hidden Epoch 87 loss:2.2164819597964347 ael:0.0033047589935589847 cl:22.13177152243726

filename: 2_4_hidden Epoch 88 loss:2.2155317608084575 ael:0.003277193818327738 cl:22.122545213655737

filename: 2_4_hidden Epoch 89 loss:2.213442713742471 ael:0.0032206292682072446 cl:22.102220414433894

filename: 2_4_hidden Epoch 90 loss:2.211147377920805 ael:0.0032061542908081346 cl:22.079411763914422

filename: 2_4_hidden Epoch 91 loss:2.2101476879232 ael:0.0031854425578096493 cl:22.069622013009816

filename: 2_4_hidden Epoch 92 loss:2.2098414062830765 ael:0.0031417388372259503 cl:22.066996241768226

filename: 2_4_hidden Epoch 93 loss:2.209304496480467 ael:0.0031031504036021645 cl:22.062013003189218

filename: 2_4_hidden Epoch 94 loss:2.2077390241280326 ael:0.0030946870486371846 cl:22.04644292075209

filename: 2_4_hidden Epoch 95 loss:2.2091252421881156 ael:0.0030593087647753816 cl:22.06065883985304

filename: 2_4_hidden Epoch 96 loss:2.205076721585085 ael:0.003053854709533107 cl:22.020228194692102

filename: 2_4_hidden Epoch 97 loss:2.2068955750733243 ael:0.003039096837731323 cl:22.03856433442338

filename: 2_4_hidden Epoch 98 loss:2.2036222542212105 ael:0.003002378004520966 cl:22.006198302505066

filename: 2_4_hidden Epoch 99 loss:2.2029156663852296 ael:0.0029871374473449 cl:21.999284819011827

filename: 2_4_hidden Epoch 100 loss:2.2030039064483966 ael:0.0029637835886247898 cl:22.00040074752718

filename: 2_4_hidden Epoch 101 loss:2.2013235972801275 ael:0.0029373249448294454 cl:21.98386223529539

filename: 2_4_hidden Epoch 102 loss:2.1996770481281542 ael:0.0029397067066572807 cl:21.96737298834643

filename: 2_4_hidden Epoch 103 loss:2.2002425600235016 ael:0.0029188606861138087 cl:21.973236525004243

filename: 2_4_hidden Epoch 104 loss:2.1981466505980665 ael:0.0028953556403892443 cl:21.952512508120744

filename: 2_4_hidden Epoch 105 loss:2.197566142314248 ael:0.002892620408035216 cl:21.946734723664825

filename: 2_4_hidden Epoch 106 loss:2.1938018403280646 ael:0.002861013016923544 cl:21.909407823713366

filename: 2_4_hidden Epoch 107 loss:2.1948009102582775 ael:0.0028858737885321785 cl:21.91914990336034

filename: 2_4_hidden Epoch 108 loss:2.191304097994724 ael:0.0028691618875305368 cl:21.88434889112556

filename: 2_4_hidden Epoch 109 loss:2.191730548516354 ael:0.002835455726513397 cl:21.88895046812191

filename: 2_4_hidden Epoch 110 loss:2.189331313428499 ael:0.002800170076170913 cl:21.86531098226875

filename: 2_4_hidden Epoch 111 loss:2.189986256428749 ael:0.0027647867619657947 cl:21.872214252539198

filename: 2_4_hidden Epoch 112 loss:2.1869381287766 ael:0.0027345252755355967 cl:21.842035569527972

filename: 2_4_hidden Epoch 113 loss:2.1837914785398214 ael:0.002699699487689527 cl:21.810917347883727

filename: 2_4_hidden Epoch 114 loss:2.1859013537111665 ael:0.0026816397153022367 cl:21.832196686643154

filename: 2_4_hidden Epoch 115 loss:2.1827524411063193 ael:0.0026471087372065523 cl:21.801052858438624

filename: 2_4_hidden Epoch 116 loss:2.181729391888806 ael:0.0026238448835743905 cl:21.791055012808215

filename: 2_4_hidden Epoch 117 loss:2.1807571903776295 ael:0.0025958003655941653 cl:21.781613434007323

filename: 2_4_hidden Epoch 118 loss:2.1790076670578147 ael:0.002558791683857517 cl:21.764488293718156

filename: 2_4_hidden Epoch 119 loss:2.1798618933408576 ael:0.00254790405152003 cl:21.77313943348392

filename: 2_4_hidden Epoch 120 loss:2.1779588963921594 ael:0.0025041852473201634 cl:21.754546637008737

filename: 2_4_hidden Epoch 121 loss:2.175995823879167 ael:0.0024758911383877236 cl:21.73519884442131

filename: 2_4_hidden Epoch 122 loss:2.1746518852117402 ael:0.0024760810030711867 cl:21.721757582945422

filename: 2_4_hidden Epoch 123 loss:2.1741597794536514 ael:0.002471710104383662 cl:21.716880235852642

filename: 2_4_hidden Epoch 124 loss:2.1724632279612828 ael:0.0024348242936584707 cl:21.700283566306105

filename: 2_4_hidden Epoch 125 loss:2.1713355350229646 ael:0.00240023508075604 cl:21.68935252948963

filename: 2_4_hidden Epoch 126 loss:2.170897430489065 ael:0.0023867355234623517 cl:21.685106475551013

filename: 2_4_hidden Epoch 127 loss:2.1703304351349426 ael:0.0023515547935502356 cl:21.679788358378147

filename: 2_4_hidden Epoch 128 loss:2.168823834807946 ael:0.0023279348294406393 cl:21.66495855270376

filename: 2_4_hidden Epoch 129 loss:2.169445288562837 ael:0.002330799446931531 cl:21.67114442131396

filename: 2_4_hidden Epoch 130 loss:2.167178076906659 ael:0.0022950425171028702 cl:21.64882988870572

filename: 2_4_hidden Epoch 131 loss:2.167290320628457 ael:0.0022834863641529248 cl:21.65006788005866

filename: 2_4_hidden Epoch 132 loss:2.163808702137796 ael:0.002261060874358338 cl:21.615475939271654

filename: 2_4_hidden Epoch 133 loss:2.166345604411299 ael:0.002264929966816154 cl:21.640806297162715

filename: 2_4_hidden Epoch 134 loss:2.1630368163039058 ael:0.0022542069857401114 cl:21.60782560813201

filename: 2_4_hidden Epoch 135 loss:2.1630565992061954 ael:0.0022128121604976275 cl:21.60843740827036

filename: 2_4_hidden Epoch 136 loss:2.1627194212979544 ael:0.0021676942184482286 cl:21.605516801232376

filename: 2_4_hidden Epoch 137 loss:2.1625338401535927 ael:0.0021729346382301507 cl:21.603608611671852

filename: 2_4_hidden Epoch 138 loss:2.1613737103753743 ael:0.0021392541999805774 cl:21.592344106528433

filename: 2_4_hidden Epoch 139 loss:2.1606410760103993 ael:0.0021086780698531976 cl:21.58532355051271

filename: 2_4_hidden Epoch 140 loss:2.160645971572298 ael:0.0020361241663560993 cl:21.586098030608593

filename: 2_4_hidden Epoch 141 loss:2.1583254939197016 ael:0.002003422207821034 cl:21.5632202763872

filename: 2_4_hidden Epoch 142 loss:2.15903571756115 ael:0.001986766743804021 cl:21.57048904934714

filename: 2_4_hidden Epoch 143 loss:2.158153775235082 ael:0.0019464885799173486 cl:21.562072419403894

filename: 2_4_hidden Epoch 144 loss:2.1564597635390634 ael:0.0019061159332110081 cl:21.54553602911303

filename: 2_4_hidden Epoch 145 loss:2.1563121023168756 ael:0.0018628185784433872 cl:21.54449238705526

filename: 2_4_hidden Epoch 146 loss:2.156635759703713 ael:0.0018138708398482142 cl:21.548218440573486

filename: 2_4_hidden Epoch 147 loss:2.154948898657407 ael:0.0017821188013684942 cl:21.53166734432567

filename: 2_4_hidden Epoch 148 loss:2.1544514283255607 ael:0.0017625877642929542 cl:21.526887977146618

filename: 2_4_hidden Epoch 149 loss:2.155949140280232 ael:0.0017368941967649924 cl:21.542122009920185

filename: 2_4_hidden Epoch 150 loss:2.151792333921835 ael:0.0016956621251039505 cl:21.500966257086617

filename: 2_4_hidden Epoch 151 loss:2.153717243266526 ael:0.0017109842290268429 cl:21.520062131402074

filename: 2_4_hidden Epoch 152 loss:2.152204195788139 ael:0.001652767697395118 cl:21.50551384652385

filename: 2_4_hidden Epoch 153 loss:2.152371602460187 ael:0.0016643685613374714 cl:21.50707191427419

filename: 2_4_hidden Epoch 154 loss:2.152546285998969 ael:0.0016347283338455716 cl:21.509115149350357

filename: 2_4_hidden Epoch 155 loss:2.1504719200124933 ael:0.0015869314684345528 cl:21.48884943370956

filename: 2_4_hidden Epoch 156 loss:2.1495410548480485 ael:0.0015777693739184315 cl:21.479632392574338

filename: 2_4_hidden Epoch 157 loss:2.149139078593114 ael:0.0015521858977407866 cl:21.475868478621788

filename: 2_4_hidden Epoch 158 loss:2.1506827959899106 ael:0.0015370657512094462 cl:21.491456856531382

filename: 2_4_hidden Epoch 159 loss:2.1476824983983627 ael:0.0014839676675443907 cl:21.461984860826988

filename: 2_4_hidden Epoch 160 loss:2.1498407151168037 ael:0.0014916334149650049 cl:21.483490344046924

filename: 2_4_hidden Epoch 161 loss:2.1481122902450336 ael:0.0014560446747658368 cl:21.466562012610755

filename: 2_4_hidden Epoch 162 loss:2.1477309450614226 ael:0.0014633504329345072 cl:21.46267545962941

filename: 2_4_hidden Epoch 163 loss:2.1468408395853174 ael:0.0014105194969410545 cl:21.454302760372748

filename: 2_4_hidden Epoch 164 loss:2.1455302899137654 ael:0.0014261559781403683 cl:21.441040900234768

filename: 2_4_hidden Epoch 165 loss:2.1454756008807854 ael:0.0014045657922130853 cl:21.44070991139876

filename: 2_4_hidden Epoch 166 loss:2.14497803209032 ael:0.001371838429341717 cl:21.43606145299392

filename: 2_4_hidden Epoch 167 loss:2.143587220306882 ael:0.0013595316694615376 cl:21.422276458266822

filename: 2_4_hidden Epoch 168 loss:2.1435213876580352 ael:0.0013303584679623592 cl:21.421909875763856

filename: 2_4_hidden Epoch 169 loss:2.1424747826148294 ael:0.001332629729902699 cl:21.411421076913506

filename: 2_4_hidden Epoch 170 loss:2.1423545814198968 ael:0.0013116164968466444 cl:21.410429193333503

filename: 2_4_hidden Epoch 171 loss:2.1438122225461793 ael:0.001315430586448622 cl:21.424967466811587

filename: 2_4_hidden Epoch 172 loss:2.140329157075876 ael:0.001287631706204168 cl:21.390414844066935

filename: 2_4_hidden Epoch 173 loss:2.1454215167707122 ael:0.0012566901457012076 cl:21.441647821123656

filename: 2_4_hidden Epoch 174 loss:2.141438164872955 ael:0.0012505536856655041 cl:21.401875693061474

filename: 2_4_hidden Epoch 175 loss:2.1415835851006535 ael:0.0012553446797823142 cl:21.4032819443945

filename: 2_4_hidden Epoch 176 loss:2.1391470922822657 ael:0.0012270382153138561 cl:21.37920010128806

filename: 2_4_hidden Epoch 177 loss:2.1400553500784683 ael:0.0012191030657678359 cl:21.388362011513937

filename: 2_4_hidden Epoch 178 loss:2.1376955149066283 ael:0.0011894795862662196 cl:21.36505990617031

filename: 2_4_hidden Epoch 179 loss:2.139578178768295 ael:0.0011752533181310417 cl:21.3840288172198

filename: 2_4_hidden Epoch 180 loss:2.1398009342901227 ael:0.001187015249153446 cl:21.386138744092626

filename: 2_4_hidden Epoch 181 loss:2.138494743115757 ael:0.0011827350599578127 cl:21.37311964016347

filename: 2_4_hidden Epoch 182 loss:2.139936478834071 ael:0.0011804231070795667 cl:21.387560114060097

filename: 2_4_hidden Epoch 183 loss:2.138253603512598 ael:0.0011575020836816175 cl:21.37096056947515

filename: 2_4_hidden Epoch 184 loss:2.1409828610314334 ael:0.0011525091640715098 cl:21.39830309483524

filename: 2_4_hidden Epoch 185 loss:2.1364829214393195 ael:0.0011292888525261159 cl:21.35353589198077

filename: 2_4_hidden Epoch 186 loss:2.136237820482659 ael:0.001114160791159608 cl:21.35123613844659

filename: 2_4_hidden Epoch 187 loss:2.1371686641567287 ael:0.001158791183997256 cl:21.360098258254578

filename: 2_4_hidden Epoch 188 loss:2.135805202028784 ael:0.0011236875465201793 cl:21.346814678822522

filename: 2_4_hidden Epoch 189 loss:2.138055235011215 ael:0.0011164743495959994 cl:21.3693871339266

filename: 2_4_hidden Epoch 190 loss:2.136051874975221 ael:0.0011275655773897479 cl:21.349242671341152

filename: 2_4_hidden Epoch 191 loss:2.1345748944581526 ael:0.0010907991407680916 cl:21.334840507307995

filename: 2_4_hidden Epoch 192 loss:2.1330448606293 ael:0.001091420743629643 cl:21.319533934241257

filename: 2_4_hidden Epoch 193 loss:2.1335766800161595 ael:0.00107225601897915 cl:21.325043786047022

filename: 2_4_hidden Epoch 194 loss:2.137780648325877 ael:0.0011138675793444836 cl:21.366667358802083

filename: 2_4_hidden Epoch 195 loss:2.1343938065930024 ael:0.0010899834241398692 cl:21.333037787524024

filename: 2_4_hidden Epoch 196 loss:2.1357962696245494 ael:0.0011183315977810959 cl:21.346778937526032

filename: 2_4_hidden Epoch 197 loss:2.132375903218342 ael:0.0010598831866744048 cl:21.313159754196853

filename: 2_4_hidden Epoch 198 loss:2.1334353345893398 ael:0.001087651338387502 cl:21.32347639334272

filename: 2_4_hidden Epoch 199 loss:2.1300477489468945 ael:0.0010567926752125842 cl:21.28990914602049

filename: 2_4_hidden Epoch 200 loss:2.130988551774576 ael:0.0010897194895805738 cl:21.29898784769508

filename: 2_4_hidden Epoch 201 loss:2.130136346949385 ael:0.0010547503333952117 cl:21.290815530299827

filename: 2_4_hidden Epoch 202 loss:2.1315110588213884 ael:0.0010538980127216433 cl:21.304571157339584

filename: 2_4_hidden Epoch 203 loss:2.128038779416947 ael:0.0010401906969358325 cl:21.269985418238726

filename: 2_4_hidden Epoch 204 loss:2.128637142776275 ael:0.0010518308646317235 cl:21.275852676780296

filename: 2_4_hidden Epoch 205 loss:2.1300882292603607 ael:0.0010909780260837916 cl:21.289972041807168

filename: 2_4_hidden Epoch 206 loss:2.1275596976046622 ael:0.0010696598932492698 cl:21.264899911949012

filename: 2_4_hidden Epoch 207 loss:2.1283089145190726 ael:0.0010578701535548837 cl:21.272510003451814

filename: 2_4_hidden Epoch 208 loss:2.1281350211019534 ael:0.0010397520568157174 cl:21.270952212273258

filename: 2_4_hidden Epoch 209 loss:2.1290920944793172 ael:0.0010479888925241407 cl:21.28044062483007

filename: 2_4_hidden Epoch 210 loss:2.126607587063414 ael:0.0010348317463200808 cl:21.255727089907435

filename: 2_4_hidden Epoch 211 loss:2.1266781968824384 ael:0.0010461795113576701 cl:21.256319741810326

filename: 2_4_hidden Epoch 212 loss:2.1238685525919703 ael:0.0010384797152498454 cl:21.228300289263686

filename: 2_4_hidden Epoch 213 loss:2.12743161929191 ael:0.0010415379368862202 cl:21.263900374369555

filename: 2_4_hidden Epoch 214 loss:2.128874039509809 ael:0.0010381822351517294 cl:21.27835811687248

filename: 2_4_hidden Epoch 215 loss:2.125535038816314 ael:0.0010396423210701062 cl:21.24495355511397

filename: 2_4_hidden Epoch 216 loss:2.125978697366297 ael:0.0010151076977545576 cl:21.249635479015748

filename: 2_4_hidden Epoch 217 loss:2.123747745422971 ael:0.0010481802733631922 cl:21.22699521959879

filename: 2_4_hidden Epoch 218 loss:2.1227774429290145 ael:0.001040410205258323 cl:21.217369835801875

filename: 2_4_hidden Epoch 219 loss:2.124004130072254 ael:0.0010259859083685111 cl:21.229781035891083

filename: 2_4_hidden Epoch 220 loss:2.121642673000022 ael:0.0009907554191660231 cl:21.206518700510593

filename: 2_4_hidden Epoch 221 loss:2.122196119646089 ael:0.00100401774805809 cl:21.211920545741204

filename: 2_4_hidden Epoch 222 loss:2.12209248889279 ael:0.0009902338019152008 cl:21.21102208798419

filename: 2_4_hidden Epoch 223 loss:2.1197497036860398 ael:0.0010252032229340143 cl:21.18724454609418

filename: 2_4_hidden Epoch 224 loss:2.121499680561773 ael:0.001007729882056488 cl:21.204919051999443

filename: 2_4_hidden Epoch 225 loss:2.119592632521686 ael:0.0009854004550621809 cl:21.186071890152647

filename: 2_4_hidden Epoch 226 loss:2.1200213315127177 ael:0.0009922445404609748 cl:21.190290421773064

filename: 2_4_hidden Epoch 227 loss:2.1197781914748997 ael:0.0009788927044872295 cl:21.18799253354113

filename: 2_4_hidden Epoch 228 loss:2.1187377629678754 ael:0.0009952570218634703 cl:21.177424605573258

filename: 2_4_hidden Epoch 229 loss:2.1192148839391813 ael:0.0009711148045529902 cl:21.18243721775725

filename: 2_4_hidden Epoch 230 loss:2.118414346919505 ael:0.001020932907341179 cl:21.173933702228428

filename: 2_4_hidden Epoch 231 loss:2.118224516403901 ael:0.0009941886035854132 cl:21.172302854053342

filename: 2_4_hidden Epoch 232 loss:2.1171598790285246 ael:0.0009769726900708058 cl:21.161828622874054

filename: 2_4_hidden Epoch 233 loss:2.116660263552376 ael:0.0009653926147797384 cl:21.156948270554796

filename: 2_4_hidden Epoch 234 loss:2.1162497795617012 ael:0.0009881887353253645 cl:21.152615456235402

filename: 2_4_hidden Epoch 235 loss:2.1148856616658684 ael:0.000998341023220433 cl:21.13887280315297

filename: 2_4_hidden Epoch 236 loss:2.115540782623553 ael:0.0009796194379122266 cl:21.145611168744907

filename: 2_4_hidden Epoch 237 loss:2.116077050167622 ael:0.000977622995477831 cl:21.150993812481303

filename: 2_4_hidden Epoch 238 loss:2.117152157676991 ael:0.001037858708322965 cl:21.161142542345083

filename: 2_4_hidden Epoch 239 loss:2.115106515990294 ael:0.0009640127511462805 cl:21.141424580542267

filename: 2_4_hidden Epoch 240 loss:2.1134001555822786 ael:0.0009675974879743243 cl:21.124325146790348

filename: 2_4_hidden Epoch 241 loss:2.1122023318033447 ael:0.0009685000926056197 cl:21.112337859918057

filename: 2_4_hidden Epoch 242 loss:2.1120197684215145 ael:0.0009629349116294369 cl:21.110567892088287

filename: 2_4_hidden Epoch 243 loss:2.1148314328072195 ael:0.0009774743367046887 cl:21.138539137986655

filename: 2_4_hidden Epoch 244 loss:2.1122022133337603 ael:0.0010020082820967875 cl:21.112001596908023

filename: 2_4_hidden Epoch 245 loss:2.112973693186438 ael:0.0010053828114622858 cl:21.119682682019913

filename: 2_4_hidden Epoch 246 loss:2.11227649088236 ael:0.0009745339325541426 cl:21.113019132209246

filename: 2_4_hidden Epoch 247 loss:2.1123546367373676 ael:0.000946557241212379 cl:21.114080354016565

filename: 2_4_hidden Epoch 248 loss:2.112292918132692 ael:0.0009812355568984694 cl:21.113116426299708

filename: 2_4_hidden Epoch 249 loss:2.109280350588257 ael:0.0009579290396266706 cl:21.08322374373772

filename: 2_4_hidden Epoch 250 loss:2.1106572324041446 ael:0.0009592870858996427 cl:21.096979016653467

/tmp/ipykernel_336185/680421385.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
/tmp/ipykernel_336185/680421385.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3  Label
0        0.013804  0.042378  0.033120  0.037517      1
1        0.042790  0.035628  0.031723  0.024558      0
2        0.014564  0.042404  0.033757  0.036795      1
3        0.038733  0.003783  0.035246  0.054310      3
4        0.036826  0.004608  0.034795  0.054379      3
...           ...       ...       ...       ...    ...
1567464  0.042813  0.035622  0.031721  0.024547      0
1567465  0.042510  0.035501  0.031493  0.024597      0
1567466  0.043377  0.035580  0.031411  0.024580      0
1567467  0.042814  0.035622  0.031721  0.024547      0
1567468  0.042778  0.035631  0.031724  0.024564      0

[1567469 rows x 5 columns]

Davies-Bouldin Score: 0.22976294151917614

               0         1         2         3  Label
0       0.042343  0.035543  0.031509  0.024677      0
1       0.048601  0.033930  0.031395  0.021584      2
2       0.015315  0.041700  0.034415  0.036450      1
3       0.037639  0.004401  0.034987  0.054444      3
4       0.014275  0.041986  0.034048  0.037105      1
...          ...       ...       ...       ...    ...
519951  0.014136  0.042269  0.034227  0.037350      1
519952  0.013447  0.042905  0.033814  0.038127      4
519953  0.042808  0.035624  0.031721  0.024550      0
519954  0.013307  0.042468  0.033474  0.037718      1
519955  0.037003  0.004541  0.034745  0.054333      3

[519956 rows x 5 columns]

               0         1         2         3  Label
0       0.042793  0.035627  0.031723  0.024557      0
1       0.042696  0.035455  0.031475  0.024509      0
2       0.016683  0.041542  0.034110  0.035996      1
3       0.019090  0.041043  0.033875  0.035136      1
4       0.043368  0.035582  0.031411  0.024583      0
...          ...       ...       ...       ...    ...
649942  0.016246  0.041586  0.033900  0.036260      1
649943  0.043521  0.035538  0.031412  0.024519      0
649944  0.043445  0.035562  0.031407  0.024550      0
649945  0.037731  0.005296  0.035054  0.053655      3
649946  0.030156  0.012221  0.035033  0.052605      2

[649947 rows x 5 columns]

2_5_hidden

cuda

[0.0, 1.0, 3.0, 4.0]

pick completo
82 4

filename: 2_5_hidden Epoch 1 loss:3.8746821364313235 ael:0.024497024552053825 cl:38.501850527049015

filename: 2_5_hidden Epoch 2 loss:3.489710957657423 ael:0.017674764567067066 cl:34.72036144293411

filename: 2_5_hidden Epoch 3 loss:3.457361124523483 ael:0.017562623937407512 cl:34.39798455741818

filename: 2_5_hidden Epoch 4 loss:3.4364042818354528 ael:0.01675853721495651 cl:34.19645695046187

filename: 2_5_hidden Epoch 5 loss:3.42924330819591 ael:0.015705818520397444 cl:34.135374429038336

filename: 2_5_hidden Epoch 6 loss:3.4220948015677717 ael:0.015051040005752761 cl:34.07043713817613

filename: 2_5_hidden Epoch 7 loss:3.418269711999595 ael:0.014601777389952839 cl:34.03667885757183

filename: 2_5_hidden Epoch 8 loss:3.4153918589580545 ael:0.014199393801935916 cl:34.011924168491056

filename: 2_5_hidden Epoch 9 loss:3.4130450822205947 ael:0.013706191301533234 cl:33.99338842616788

filename: 2_5_hidden Epoch 10 loss:3.4098609037725645 ael:0.013230735159599754 cl:33.96630120200698

filename: 2_5_hidden Epoch 11 loss:3.4070972638996277 ael:0.0129541553035008 cl:33.941430639404764

filename: 2_5_hidden Epoch 12 loss:3.403961077737822 ael:0.012849532785539687 cl:33.91111498696304

filename: 2_5_hidden Epoch 13 loss:3.4015870121495353 ael:0.012803710696924044 cl:33.88783256461586

filename: 2_5_hidden Epoch 14 loss:3.3984270858708863 ael:0.012748006924673039 cl:33.85679030662463

filename: 2_5_hidden Epoch 15 loss:3.3949631164212715 ael:0.012782309240568675 cl:33.821807588530966

filename: 2_5_hidden Epoch 16 loss:3.3914336308850013 ael:0.0128781811159042 cl:33.78555401559112

filename: 2_5_hidden Epoch 17 loss:3.3854713466440107 ael:0.01298472776618939 cl:33.72486569665963

filename: 2_5_hidden Epoch 18 loss:3.3787789321775565 ael:0.013179046316516351 cl:33.655998376141724

filename: 2_5_hidden Epoch 19 loss:3.3482592450348596 ael:0.013873058684229084 cl:33.343861381015294

filename: 2_5_hidden Epoch 20 loss:3.3006076793916117 ael:0.013791011482135058 cl:32.868166179048906

filename: 2_5_hidden Epoch 21 loss:3.285193772997972 ael:0.013583009172656986 cl:32.71610716512657

filename: 2_5_hidden Epoch 22 loss:3.2745465832029947 ael:0.013456871764939773 cl:32.610896656965785

filename: 2_5_hidden Epoch 23 loss:3.265558412947408 ael:0.013406011370740968 cl:32.52152352557611

filename: 2_5_hidden Epoch 24 loss:3.258199101339554 ael:0.013363439384079722 cl:32.44835615032561

filename: 2_5_hidden Epoch 25 loss:3.251730509339874 ael:0.013350667826925046 cl:32.38379793147589

filename: 2_5_hidden Epoch 26 loss:3.245620287590886 ael:0.013395628246851102 cl:32.32224611916644

filename: 2_5_hidden Epoch 27 loss:3.239378291704948 ael:0.013379320500919207 cl:32.25998920876926

filename: 2_5_hidden Epoch 28 loss:3.2343028387363697 ael:0.013369102796425803 cl:32.20933690981825

filename: 2_5_hidden Epoch 29 loss:3.2292045606232134 ael:0.01328143413399536 cl:32.15923077699628

filename: 2_5_hidden Epoch 30 loss:3.2244522637810475 ael:0.013244752016797787 cl:32.11207465980443

filename: 2_5_hidden Epoch 31 loss:3.2204540670528226 ael:0.012998905867767478 cl:32.07455111791182

filename: 2_5_hidden Epoch 32 loss:3.215796700553191 ael:0.012688498246982262 cl:32.03108159656865

filename: 2_5_hidden Epoch 33 loss:3.211206688034357 ael:0.012648449103944777 cl:31.98558190985359

filename: 2_5_hidden Epoch 34 loss:3.207530949610163 ael:0.01245963088999186 cl:31.950712708849487

filename: 2_5_hidden Epoch 35 loss:3.2036060830869673 ael:0.012290075787978584 cl:31.913159578785837

filename: 2_5_hidden Epoch 36 loss:3.2007747362426375 ael:0.012082544041012474 cl:31.886921438288013

filename: 2_5_hidden Epoch 37 loss:3.1977312187592024 ael:0.012082912278440341 cl:31.85648259254672

filename: 2_5_hidden Epoch 38 loss:3.1975128161136643 ael:0.01198917585194904 cl:31.855235931851706

filename: 2_5_hidden Epoch 39 loss:3.1934568379210533 ael:0.0116632021486903 cl:31.817935868291418

filename: 2_5_hidden Epoch 40 loss:3.1885425465676684 ael:0.01148555106185126 cl:31.77056945238451

filename: 2_5_hidden Epoch 41 loss:3.1839546197058337 ael:0.011638585701568472 cl:31.723159873719172

filename: 2_5_hidden Epoch 42 loss:3.1802074727903302 ael:0.011526594181855882 cl:31.686808276783132

filename: 2_5_hidden Epoch 43 loss:3.177655875386464 ael:0.011555684826430233 cl:31.66100142747556

filename: 2_5_hidden Epoch 44 loss:3.1744895505082296 ael:0.014030045492759257 cl:31.604594545568002

filename: 2_5_hidden Epoch 45 loss:3.170066861738131 ael:0.014771706147626604 cl:31.55295107133837

filename: 2_5_hidden Epoch 46 loss:3.1658012316777158 ael:0.01478470322267681 cl:31.510164799764166

filename: 2_5_hidden Epoch 47 loss:3.163672960163662 ael:0.014750728438139555 cl:31.48922182726351

filename: 2_5_hidden Epoch 48 loss:3.161209057283248 ael:0.014691590084976256 cl:31.465174208331714

filename: 2_5_hidden Epoch 49 loss:3.1581340477668114 ael:0.014681384202205112 cl:31.434526156179736

filename: 2_5_hidden Epoch 50 loss:3.1569467698248133 ael:0.014748182971467396 cl:31.421985400842274

filename: 2_5_hidden Epoch 51 loss:3.1540106310764924 ael:0.014655401826430025 cl:31.393551850744284

filename: 2_5_hidden Epoch 52 loss:3.151883269025764 ael:0.014646737046352375 cl:31.37236484640277

filename: 2_5_hidden Epoch 53 loss:3.1498493678251114 ael:0.01467149465939487 cl:31.351778258563275

filename: 2_5_hidden Epoch 54 loss:3.1491597140173564 ael:0.014718253399199407 cl:31.344414109896412

filename: 2_5_hidden Epoch 55 loss:3.1482507845713195 ael:0.014698229812665288 cl:31.335525080905946

filename: 2_5_hidden Epoch 56 loss:3.1465854526925905 ael:0.014573527240167413 cl:31.320118776083202

filename: 2_5_hidden Epoch 57 loss:3.1449646476278112 ael:0.014593678906300624 cl:31.303709214247608

filename: 2_5_hidden Epoch 58 loss:3.143926333042222 ael:0.014593093700404054 cl:31.29333194287488

filename: 2_5_hidden Epoch 59 loss:3.1430694410486435 ael:0.014564181647488739 cl:31.285052132976094

filename: 2_5_hidden Epoch 60 loss:3.1422155397821845 ael:0.014531499209630452 cl:31.276839938279515

filename: 2_5_hidden Epoch 61 loss:3.140953418280375 ael:0.014621652458456915 cl:31.263317208012563

filename: 2_5_hidden Epoch 62 loss:3.140168861605055 ael:0.014409491525372938 cl:31.257593235240133

filename: 2_5_hidden Epoch 63 loss:3.1386234661960293 ael:0.014402002326350928 cl:31.242214176103225

filename: 2_5_hidden Epoch 64 loss:3.1392412883700525 ael:0.014500982384953313 cl:31.24740260007891

filename: 2_5_hidden Epoch 65 loss:3.137883473432842 ael:0.014540961743083202 cl:31.233424655594092

filename: 2_5_hidden Epoch 66 loss:3.13611641324867 ael:0.014491875999713109 cl:31.216244900913466

filename: 2_5_hidden Epoch 67 loss:3.1348158347393973 ael:0.014453172274304347 cl:31.20362616352395

filename: 2_5_hidden Epoch 68 loss:3.134366283294017 ael:0.01439382322377744 cl:31.19972412151773

filename: 2_5_hidden Epoch 69 loss:3.1347417477872437 ael:0.01419764832228762 cl:31.205440523471704

filename: 2_5_hidden Epoch 70 loss:3.13427684752695 ael:0.013872877716730478 cl:31.204039238112195

filename: 2_5_hidden Epoch 71 loss:3.1319533943885878 ael:0.013898987627039878 cl:31.180543603308546

filename: 2_5_hidden Epoch 72 loss:3.1314886629529153 ael:0.013559266964900334 cl:31.17929350336102

filename: 2_5_hidden Epoch 73 loss:3.1333486099416104 ael:0.013355078087407582 cl:31.199934862621628

filename: 2_5_hidden Epoch 74 loss:3.1310112558634318 ael:0.012957168948401062 cl:31.180540383855792

filename: 2_5_hidden Epoch 75 loss:3.129994136124684 ael:0.012621273139546701 cl:31.173728164646075

filename: 2_5_hidden Epoch 76 loss:3.1296486212308383 ael:0.012193488547947278 cl:31.174550845003086

filename: 2_5_hidden Epoch 77 loss:3.1293603633362914 ael:0.011850782500922627 cl:31.175095329719806

filename: 2_5_hidden Epoch 78 loss:3.1284466528969226 ael:0.011316801710901431 cl:31.17129805297941

filename: 2_5_hidden Epoch 79 loss:3.127355640064941 ael:0.010866647276511996 cl:31.16488947482024

filename: 2_5_hidden Epoch 80 loss:3.1274797637478655 ael:0.010499256838038977 cl:31.169804592863375

filename: 2_5_hidden Epoch 81 loss:3.1250037907089676 ael:0.010240928782980958 cl:31.14762815100019

filename: 2_5_hidden Epoch 82 loss:3.1252378542962287 ael:0.009819299016397366 cl:31.154185073910558

filename: 2_5_hidden Epoch 83 loss:3.124377819277732 ael:0.009653549117825296 cl:31.147242223355253

filename: 2_5_hidden Epoch 84 loss:3.1237132438409745 ael:0.00929252001731764 cl:31.14420674188195

filename: 2_5_hidden Epoch 85 loss:3.122511406605897 ael:0.008951890647343792 cl:31.135594671181888

filename: 2_5_hidden Epoch 86 loss:3.122894908992057 ael:0.008772229540844686 cl:31.141226333078148

filename: 2_5_hidden Epoch 87 loss:3.121906435186314 ael:0.008544534200878171 cl:31.133618544193343

filename: 2_5_hidden Epoch 88 loss:3.121640413607307 ael:0.008282470524896174 cl:31.1335789802375

filename: 2_5_hidden Epoch 89 loss:3.1206850885612707 ael:0.008190021905056537 cl:31.12495018299925

filename: 2_5_hidden Epoch 90 loss:3.120989574609217 ael:0.007752436873211293 cl:31.13237089272583

filename: 2_5_hidden Epoch 91 loss:3.1192482305082114 ael:0.00757325596156203 cl:31.116749276749466

filename: 2_5_hidden Epoch 92 loss:3.11837789781542 ael:0.007496029085447806 cl:31.108818207054885

filename: 2_5_hidden Epoch 93 loss:3.117742289922223 ael:0.00729139922208524 cl:31.10450843929303

filename: 2_5_hidden Epoch 94 loss:3.117669257548651 ael:0.0071124522385638805 cl:31.105567539948126

filename: 2_5_hidden Epoch 95 loss:3.118172983915424 ael:0.007026207305487702 cl:31.111467273307145

filename: 2_5_hidden Epoch 96 loss:3.118752348593851 ael:0.0067034027458564354 cl:31.12048897655361

filename: 2_5_hidden Epoch 97 loss:3.1183689601521074 ael:0.00652029418867843 cl:31.11848618461919

filename: 2_5_hidden Epoch 98 loss:3.1168785852519836 ael:0.006388935986138133 cl:31.104896027151344

filename: 2_5_hidden Epoch 99 loss:3.115832413243564 ael:0.006284500088986161 cl:31.095478654221576

filename: 2_5_hidden Epoch 100 loss:3.115166354088729 ael:0.006174852436614877 cl:31.089914535562627

filename: 2_5_hidden Epoch 101 loss:3.1148051431075143 ael:0.00609043076605533 cl:31.08714664188105

filename: 2_5_hidden Epoch 102 loss:3.1145166144380796 ael:0.0060134884587680565 cl:31.08503078361393

filename: 2_5_hidden Epoch 103 loss:3.114703560544929 ael:0.005918442123398211 cl:31.08785070958769

filename: 2_5_hidden Epoch 104 loss:3.1136477943330036 ael:0.005729033831742863 cl:31.07918711425478

filename: 2_5_hidden Epoch 105 loss:3.113490028317193 ael:0.005688706694705274 cl:31.078012723607536

filename: 2_5_hidden Epoch 106 loss:3.1144850432576403 ael:0.005468091361088998 cl:31.09016903188013

filename: 2_5_hidden Epoch 107 loss:3.112871088037438 ael:0.005547832738966051 cl:31.07323206890114

filename: 2_5_hidden Epoch 108 loss:3.1128352838986517 ael:0.005460013110412905 cl:31.073752233388653

filename: 2_5_hidden Epoch 109 loss:3.112066386421719 ael:0.0053213175532467166 cl:31.067450171083202

filename: 2_5_hidden Epoch 110 loss:3.1114189865366693 ael:0.005327600104836178 cl:31.060913384396557

filename: 2_5_hidden Epoch 111 loss:3.111555212525186 ael:0.0051360075868956 cl:31.064191582817262

filename: 2_5_hidden Epoch 112 loss:3.1116591607244715 ael:0.005061758960520674 cl:31.06597353122708

filename: 2_5_hidden Epoch 113 loss:3.1106410882876747 ael:0.004989445015352789 cl:31.05651597399292

filename: 2_5_hidden Epoch 114 loss:3.1116429352209423 ael:0.004926949189011575 cl:31.067159397206694

filename: 2_5_hidden Epoch 115 loss:3.110932482582465 ael:0.004826473540624559 cl:31.06105961036738

filename: 2_5_hidden Epoch 116 loss:3.10991745875153 ael:0.004833214605484799 cl:31.050841960477424

filename: 2_5_hidden Epoch 117 loss:3.1096852488181645 ael:0.004715209529370409 cl:31.049699906056023

filename: 2_5_hidden Epoch 118 loss:3.109210677229197 ael:0.004676443204116463 cl:31.04534188388

filename: 2_5_hidden Epoch 119 loss:3.1088451265974957 ael:0.0046028042858797195 cl:31.042422723337793

filename: 2_5_hidden Epoch 120 loss:3.1090956861145074 ael:0.004472282572201872 cl:31.04623358024425

filename: 2_5_hidden Epoch 121 loss:3.109756816720084 ael:0.004425854966740126 cl:31.053309145222006

filename: 2_5_hidden Epoch 122 loss:3.1071865738536504 ael:0.004370469395528894 cl:31.02816058948536

filename: 2_5_hidden Epoch 123 loss:3.1083842132760267 ael:0.0043305184436228175 cl:31.040536502816934

filename: 2_5_hidden Epoch 124 loss:3.1089440231680276 ael:0.004294012691858316 cl:31.04649961604888

filename: 2_5_hidden Epoch 125 loss:3.1084080220802934 ael:0.004274736326413938 cl:31.04133235756226

filename: 2_5_hidden Epoch 126 loss:3.1086496438642595 ael:0.004203910721410377 cl:31.044456867419967

filename: 2_5_hidden Epoch 127 loss:3.1077241614465305 ael:0.004064406285459586 cl:31.0365970574753

filename: 2_5_hidden Epoch 128 loss:3.10710242945885 ael:0.00401444689511793 cl:31.030879357363894

filename: 2_5_hidden Epoch 129 loss:3.1070398306002844 ael:0.004035516860155303 cl:31.030042637158083

filename: 2_5_hidden Epoch 130 loss:3.106431394684695 ael:0.003961545608215346 cl:31.024698033183594

filename: 2_5_hidden Epoch 131 loss:3.1069211774347956 ael:0.003965325838305725 cl:31.0295580328121

filename: 2_5_hidden Epoch 132 loss:3.105818991285906 ael:0.003922872731538937 cl:31.018960722359555

filename: 2_5_hidden Epoch 133 loss:3.105606666047798 ael:0.0038746357136810513 cl:31.01731982737405

filename: 2_5_hidden Epoch 134 loss:3.1056749808854547 ael:0.0038099574094295555 cl:31.018649753125377

filename: 2_5_hidden Epoch 135 loss:3.103657824214211 ael:0.003752568982441864 cl:30.999052085664474

filename: 2_5_hidden Epoch 136 loss:3.106123964003423 ael:0.0036987530122859482 cl:31.024251635502083

filename: 2_5_hidden Epoch 137 loss:3.1048296929521495 ael:0.0036555107121262398 cl:31.01174134307174

filename: 2_5_hidden Epoch 138 loss:3.1047776139385697 ael:0.0036441425477710516 cl:31.011334232085975

filename: 2_5_hidden Epoch 139 loss:3.103290686937897 ael:0.00362132570399045 cl:30.99669312552145

filename: 2_5_hidden Epoch 140 loss:3.1043031760983104 ael:0.003552396205216036 cl:31.007507303577658

filename: 2_5_hidden Epoch 141 loss:3.104926150875086 ael:0.003538514330681347 cl:31.013875877065733

filename: 2_5_hidden Epoch 142 loss:3.1039956751257467 ael:0.003484263762618674 cl:31.005113655797707

filename: 2_5_hidden Epoch 143 loss:3.104821335470931 ael:0.0034464472678984925 cl:31.01374841440697

filename: 2_5_hidden Epoch 144 loss:3.1040206130536268 ael:0.0034473238710497085 cl:31.005732426694973

filename: 2_5_hidden Epoch 145 loss:3.1037399509421006 ael:0.0033956646251743624 cl:31.003442388279602

filename: 2_5_hidden Epoch 146 loss:3.1036907261873274 ael:0.0033699768487392384 cl:31.003207007846346

filename: 2_5_hidden Epoch 147 loss:3.102249148855017 ael:0.0033044327914215784 cl:30.989446670697355

filename: 2_5_hidden Epoch 148 loss:3.103787847484333 ael:0.003320245253320965 cl:31.00467554858359

filename: 2_5_hidden Epoch 149 loss:3.1028719760061323 ael:0.003286580806494557 cl:30.99585347037526

filename: 2_5_hidden Epoch 150 loss:3.1028627432309666 ael:0.0032537394820495408 cl:30.996089565994517

filename: 2_5_hidden Epoch 151 loss:3.1042090640077817 ael:0.0032194980248426417 cl:31.009895171293497

filename: 2_5_hidden Epoch 152 loss:3.103084590428752 ael:0.0032019597765861304 cl:30.998825839194126

filename: 2_5_hidden Epoch 153 loss:3.102452751139027 ael:0.0032400610060225403 cl:30.992126395668194

filename: 2_5_hidden Epoch 154 loss:3.101270448328215 ael:0.0031747718810987216 cl:30.98095630936959

filename: 2_5_hidden Epoch 155 loss:3.1024680949331342 ael:0.0031841495512208635 cl:30.99283898201

filename: 2_5_hidden Epoch 156 loss:3.1021768055174146 ael:0.0031274557165402736 cl:30.990493009019993

filename: 2_5_hidden Epoch 157 loss:3.1016808044983653 ael:0.003106793587437348 cl:30.98573965913338

filename: 2_5_hidden Epoch 158 loss:3.101363592658276 ael:0.0030817570059995256 cl:30.98281791008645

filename: 2_5_hidden Epoch 159 loss:3.102154880910284 ael:0.003110045177219738 cl:30.99044784295974

filename: 2_5_hidden Epoch 160 loss:3.1020517828311793 ael:0.003057702733540178 cl:30.989940326999733

filename: 2_5_hidden Epoch 161 loss:3.100201335487466 ael:0.0029975717967162556 cl:30.97203715665538

filename: 2_5_hidden Epoch 162 loss:3.1014054195334877 ael:0.0029830519835151127 cl:30.98422317248264

filename: 2_5_hidden Epoch 163 loss:3.1006930232849967 ael:0.0030518690096301582 cl:30.97641104513806

filename: 2_5_hidden Epoch 164 loss:3.1012310368793683 ael:0.0029626457078456465 cl:30.982683417740606

filename: 2_5_hidden Epoch 165 loss:3.100413517423386 ael:0.0029659644076050432 cl:30.974475068424

filename: 2_5_hidden Epoch 166 loss:3.0992597984130983 ael:0.0030087454073021037 cl:30.962510075196775

filename: 2_5_hidden Epoch 167 loss:3.1017685881411343 ael:0.0029971935364024663 cl:30.987713464835682

filename: 2_5_hidden Epoch 168 loss:3.1000829782008985 ael:0.0029333053072903587 cl:30.97149625010015

filename: 2_5_hidden Epoch 169 loss:3.0987651146584416 ael:0.002938635637320395 cl:30.958264293709703

filename: 2_5_hidden Epoch 170 loss:3.0992175304739753 ael:0.002907709217574213 cl:30.963097752238895

filename: 2_5_hidden Epoch 171 loss:3.0999147567040533 ael:0.002873006844800483 cl:30.97041702493655

filename: 2_5_hidden Epoch 172 loss:3.099022357915012 ael:0.002845828177823605 cl:30.961764812887882

filename: 2_5_hidden Epoch 173 loss:3.202325410541647 ael:0.004035656683196802 cl:31.982897063660044

filename: 2_5_hidden Epoch 174 loss:3.0987990740692104 ael:0.0030590779240725007 cl:30.95739946479719

filename: 2_5_hidden Epoch 175 loss:3.1002195257302367 ael:0.0029829215597425066 cl:30.972365577655356

filename: 2_5_hidden Epoch 176 loss:3.098918539977764 ael:0.002900944028149677 cl:30.96017547656514

filename: 2_5_hidden Epoch 177 loss:3.0984100317111243 ael:0.0028715525150710937 cl:30.955384284301473

filename: 2_5_hidden Epoch 178 loss:3.098958620728021 ael:0.002860918683788496 cl:30.960976539002626

filename: 2_5_hidden Epoch 179 loss:3.0973984175657243 ael:0.002843841403909627 cl:30.945545253993544

filename: 2_5_hidden Epoch 180 loss:3.098945133795547 ael:0.002799324811115898 cl:30.961457623205327

filename: 2_5_hidden Epoch 181 loss:3.097819207390347 ael:0.0027892243072965856 cl:30.95029936034835

filename: 2_5_hidden Epoch 182 loss:3.0977695401769942 ael:0.00279733516999367 cl:30.94972157875813

filename: 2_5_hidden Epoch 183 loss:3.0977318238082354 ael:0.0027325847905614606 cl:30.949991921856935

filename: 2_5_hidden Epoch 184 loss:3.2369275366433636 ael:0.0040770214432090494 cl:32.328504655541785

filename: 2_5_hidden Epoch 185 loss:3.1081971989001542 ael:0.003276057450049569 cl:31.049210943649932

filename: 2_5_hidden Epoch 186 loss:3.098045274785263 ael:0.002901657776412415 cl:30.95143566538835

filename: 2_5_hidden Epoch 187 loss:3.0984413381137497 ael:0.0028432070033632397 cl:30.95598083701389

filename: 2_5_hidden Epoch 188 loss:3.0985429203276675 ael:0.002807082555122765 cl:30.95735789921312

filename: 2_5_hidden Epoch 189 loss:3.0977488823472563 ael:0.0027441954013501173 cl:30.950046418249414

filename: 2_5_hidden Epoch 190 loss:3.096717575970851 ael:0.002752617148899847 cl:30.93964910604829

filename: 2_5_hidden Epoch 191 loss:3.0986575426920075 ael:0.0027621037197501147 cl:30.958953904840605

filename: 2_5_hidden Epoch 192 loss:3.0977067558275184 ael:0.0027188459108154605 cl:30.94987864186102

filename: 2_5_hidden Epoch 193 loss:3.0962624597981785 ael:0.0026604474785921015 cl:30.936019641399803

filename: 2_5_hidden Epoch 194 loss:3.097517981031339 ael:0.002714867343066212 cl:30.948030644182783

filename: 2_5_hidden Epoch 195 loss:3.0956755354586454 ael:0.002640776231354601 cl:30.930347094517696

filename: 2_5_hidden Epoch 196 loss:3.0963421048529494 ael:0.002635384790941748 cl:30.937066707739394

filename: 2_5_hidden Epoch 197 loss:3.0959578900003892 ael:0.002658472477266923 cl:30.93299369276459

filename: 2_5_hidden Epoch 198 loss:3.0978899379333025 ael:0.0026530216916326164 cl:30.95236870474758

filename: 2_5_hidden Epoch 199 loss:3.0965472227929456 ael:0.0027525787511156747 cl:30.93794595529267

filename: 2_5_hidden Epoch 200 loss:3.0950927922655245 ael:0.002633494303326669 cl:30.924592496498736

filename: 2_5_hidden Epoch 201 loss:3.0957768667717014 ael:0.0026207540964197805 cl:30.931560646340525

filename: 2_5_hidden Epoch 202 loss:3.0958232535155554 ael:0.0026286801227751676 cl:30.93194526690215

filename: 2_5_hidden Epoch 203 loss:3.0949566109063995 ael:0.002590905461129663 cl:30.923656577985863

filename: 2_5_hidden Epoch 204 loss:3.0949702992290042 ael:0.0026171829767128044 cl:30.92353068405022

filename: 2_5_hidden Epoch 205 loss:3.0957640077189836 ael:0.002599500820663673 cl:30.931644598131605

filename: 2_5_hidden Epoch 206 loss:3.0958413521983394 ael:0.0026154881960563374 cl:30.932258157431644

filename: 2_5_hidden Epoch 207 loss:3.0944613721434155 ael:0.0026208000133943403 cl:30.918405253345348

filename: 2_5_hidden Epoch 208 loss:3.096197866075532 ael:0.0026250249831442853 cl:30.935727906317766

filename: 2_5_hidden Epoch 209 loss:3.095735699993088 ael:0.0025907975248883486 cl:30.931448533961074

filename: 2_5_hidden Epoch 210 loss:3.0942723762922797 ael:0.002552307030842804 cl:30.917200208442466

filename: 2_5_hidden Epoch 211 loss:3.095093184934439 ael:0.0025389760825401658 cl:30.92554161526997

filename: 2_5_hidden Epoch 212 loss:3.0958629963376363 ael:0.002581905173762933 cl:30.932810457312737

filename: 2_5_hidden Epoch 213 loss:3.118275500417767 ael:0.0027895303807812725 cl:31.154859235461743

filename: 2_5_hidden Epoch 214 loss:3.2453506261363088 ael:0.00323350669643301 cl:32.42117071137787

filename: 2_5_hidden Epoch 215 loss:3.096487783346653 ael:0.002801301217767072 cl:30.936864365887036

filename: 2_5_hidden Epoch 216 loss:3.0953182066766516 ael:0.00265435713636012 cl:30.926638026096626

filename: 2_5_hidden Epoch 217 loss:3.0951293175873893 ael:0.002658392576007464 cl:30.92470875996949

filename: 2_5_hidden Epoch 218 loss:3.220130911275078 ael:0.003057573232339419 cl:32.17073288923399

filename: 2_5_hidden Epoch 219 loss:3.2397115659420863 ael:0.002952381472703114 cl:32.367591370891915

filename: 2_5_hidden Epoch 220 loss:3.2006269254402726 ael:0.0029562601850142813 cl:31.97670615810719

filename: 2_5_hidden Epoch 221 loss:3.0963338876056477 ael:0.002735911220107549 cl:30.935979318186426

filename: 2_5_hidden Epoch 222 loss:3.0951149379973453 ael:0.0026302273629974704 cl:30.92484662350802

filename: 2_5_hidden Epoch 223 loss:3.0937220628375233 ael:0.0025463748125222675 cl:30.91175640839239

filename: 2_5_hidden Epoch 224 loss:3.094948683819878 ael:0.0025560566274619207 cl:30.923925771877826

filename: 2_5_hidden Epoch 225 loss:3.0943768657624076 ael:0.0024746725223762367 cl:30.91902145470538

filename: 2_5_hidden Epoch 226 loss:3.0936547688972045 ael:0.002523534734265971 cl:30.911311875103717

filename: 2_5_hidden Epoch 227 loss:3.0936173990338336 ael:0.0024425788670105458 cl:30.91174774750104

filename: 2_5_hidden Epoch 228 loss:3.093545490763068 ael:0.0024988279915865567 cl:30.91046615649678

filename: 2_5_hidden Epoch 229 loss:3.0937109574409702 ael:0.002439723578614024 cl:30.912711848916977

filename: 2_5_hidden Epoch 230 loss:3.0932496064725274 ael:0.002452294671376576 cl:30.907972664399328

filename: 2_5_hidden Epoch 231 loss:3.093744065406623 ael:0.0023993503130862338 cl:30.913446697515155

filename: 2_5_hidden Epoch 232 loss:3.093360755484716 ael:0.002382323314105091 cl:30.90978385008159

filename: 2_5_hidden Epoch 233 loss:3.114027446457851 ael:0.00250167996151649 cl:31.115257183966424

filename: 2_5_hidden Epoch 234 loss:3.2394641198830216 ael:0.002876493389746564 cl:32.365875799218685

filename: 2_5_hidden Epoch 235 loss:3.149276212001621 ael:0.002612767011062309 cl:31.46663394703716

filename: 2_5_hidden Epoch 236 loss:3.2182847316866905 ael:0.0028900562227630357 cl:32.15394630275926

filename: 2_5_hidden Epoch 237 loss:3.0951186801021158 ael:0.002537232006583488 cl:30.92581399179544

filename: 2_5_hidden Epoch 238 loss:3.0933171991508375 ael:0.002452988204437042 cl:30.908641624952764

filename: 2_5_hidden Epoch 239 loss:3.0936273548748803 ael:0.002403276395367289 cl:30.912240279142743

filename: 2_5_hidden Epoch 240 loss:3.093434013864317 ael:0.0023759614902870737 cl:30.910580060746316

filename: 2_5_hidden Epoch 241 loss:3.094084878036173 ael:0.002343520428924068 cl:30.91741309064144

filename: 2_5_hidden Epoch 242 loss:3.092702263312997 ael:0.0024148021174924903 cl:30.90287413461824

filename: 2_5_hidden Epoch 243 loss:3.093091817444687 ael:0.0023595364411579706 cl:30.907322360047406

filename: 2_5_hidden Epoch 244 loss:3.0925058856209873 ael:0.002324308177200752 cl:30.901815310665373

filename: 2_5_hidden Epoch 245 loss:3.092859693632101 ael:0.0022997915104037555 cl:30.905598555924986

filename: 2_5_hidden Epoch 246 loss:3.0925235307575774 ael:0.002311534445507288 cl:30.902119481169574

filename: 2_5_hidden Epoch 247 loss:3.0922850095308743 ael:0.00232175481505692 cl:30.89963207428969

filename: 2_5_hidden Epoch 248 loss:3.092918126476407 ael:0.00232387002394487 cl:30.905942068911674

filename: 2_5_hidden Epoch 249 loss:3.0918845495099596 ael:0.002268394639759953 cl:30.896161055697373

filename: 2_5_hidden Epoch 250 loss:3.0930792934610745 ael:0.0022887554326543867 cl:30.9079048801633

/tmp/ipykernel_336185/680421385.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
/tmp/ipykernel_336185/680421385.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3  Label
0        0.100521  0.059717  0.060466  0.096047      1
1        0.081513  0.098577  0.093533  0.061050      0
2        0.095930  0.054248  0.056595  0.092101      1
3        0.157353  0.129947  0.114899  0.128611      4
4        0.036044  0.090534  0.111186  0.134700      3
...           ...       ...       ...       ...    ...
1750031  0.081583  0.098660  0.093612  0.061013      0
1750032  0.082843  0.097445  0.093398  0.063390      0
1750033  0.081666  0.098098  0.094506  0.061141      0
1750034  0.081586  0.098664  0.093616  0.061011      0
1750035  0.081473  0.098530  0.093488  0.061072      0

[1750036 rows x 5 columns]

Davies-Bouldin Score: 0.0802958662819304

               0         1         2         3  Label
0       0.082624  0.097331  0.093312  0.063199      0
1       0.091995  0.063457  0.064556  0.084053      2
2       0.098868  0.059990  0.061843  0.094200      1
3       0.031484  0.089271  0.112747  0.137670      3
4       0.098756  0.059877  0.059926  0.093643      1
...          ...       ...       ...       ...    ...
519951  0.100279  0.058896  0.061061  0.094787      1
519952  0.153825  0.126066  0.114577  0.126659      4
519953  0.081567  0.098642  0.093595  0.061021      0
519954  0.098829  0.057515  0.058514  0.095925      1
519955  0.033434  0.088234  0.110401  0.138172      3

[519956 rows x 5 columns]

               0         1         2         3  Label
0       0.081521  0.098586  0.093542  0.061046      0
1       0.083122  0.097591  0.093507  0.063633      0
2       0.099011  0.062924  0.064069  0.093507      1
3       0.096352  0.037159  0.043849  0.096507      1
4       0.081645  0.098085  0.094495  0.061130      0
...          ...       ...       ...       ...    ...
649942  0.099148  0.059996  0.060008  0.094164      1
649943  0.082203  0.098499  0.094832  0.061422      0
649944  0.082057  0.098445  0.094776  0.061380      0
649945  0.034755  0.090115  0.111861  0.136192      3
649946  0.056752  0.087235  0.099617  0.112505      2

[649947 rows x 5 columns]

3_4_hidden

cuda

[0.0, 1.0, 2.0, 5.0]

pick completo
82 4

filename: 3_4_hidden Epoch 1 loss:3.247055772880018 ael:0.02304342615577635 cl:32.24012289877165

filename: 3_4_hidden Epoch 2 loss:2.7637433585606703 ael:0.016626485249332763 cl:27.471168264658985

filename: 3_4_hidden Epoch 3 loss:2.670577384879915 ael:0.01661843052534828 cl:26.539589089481925

filename: 3_4_hidden Epoch 4 loss:2.6280836304041135 ael:0.016594526850866178 cl:26.114890550156797

filename: 3_4_hidden Epoch 5 loss:2.604998958336011 ael:0.01650604113737988 cl:25.88492870891969

filename: 3_4_hidden Epoch 6 loss:2.5877484866582634 ael:0.01565082902108951 cl:25.72097610031794

filename: 3_4_hidden Epoch 7 loss:2.56891579825873 ael:0.014757334899022303 cl:25.541584177923927

filename: 3_4_hidden Epoch 8 loss:2.551622735010503 ael:0.014640202787616796 cl:25.369824848074632

filename: 3_4_hidden Epoch 9 loss:2.5355986289174686 ael:0.01438025252523807 cl:25.212183303454964

filename: 3_4_hidden Epoch 10 loss:2.51841119403402 ael:0.013981884847559236 cl:25.044292633066092

filename: 3_4_hidden Epoch 11 loss:2.4988096149833847 ael:0.01366150303469488 cl:24.851480626365873

filename: 3_4_hidden Epoch 12 loss:2.4809455869736117 ael:0.013424273333998241 cl:24.675212669904184

filename: 3_4_hidden Epoch 13 loss:2.466954398428408 ael:0.01324263720788447 cl:24.53711714616092

filename: 3_4_hidden Epoch 14 loss:2.4533488204804836 ael:0.01311260656811027 cl:24.402361686401747

filename: 3_4_hidden Epoch 15 loss:2.4414497051640685 ael:0.012942085134026416 cl:24.28507572787212

filename: 3_4_hidden Epoch 16 loss:2.4328036193472564 ael:0.012775674114478525 cl:24.20027898597658

filename: 3_4_hidden Epoch 17 loss:2.4240389324334726 ael:0.012552248640519504 cl:24.114866363038658

filename: 3_4_hidden Epoch 18 loss:2.419253487747939 ael:0.01241925686739729 cl:24.068341816051266

filename: 3_4_hidden Epoch 19 loss:2.408859098980249 ael:0.012405964507256713 cl:23.964530869806172

filename: 3_4_hidden Epoch 20 loss:2.4002798372616003 ael:0.012477240538742012 cl:23.87802550563062

filename: 3_4_hidden Epoch 21 loss:2.3953045417591308 ael:0.012628515180893711 cl:23.826759790259274

filename: 3_4_hidden Epoch 22 loss:2.3894225733684067 ael:0.012760612258751646 cl:23.76661914921132

filename: 3_4_hidden Epoch 23 loss:2.3817636212094646 ael:0.012871903990337394 cl:23.688916692795786

filename: 3_4_hidden Epoch 24 loss:2.3749713335438902 ael:0.013053882444844449 cl:23.619174049970496

filename: 3_4_hidden Epoch 25 loss:2.3669102295296374 ael:0.013305454053730003 cl:23.536047299604512

filename: 3_4_hidden Epoch 26 loss:2.3615422360702873 ael:0.013454996717972038 cl:23.480871919435256

filename: 3_4_hidden Epoch 27 loss:2.355853846251097 ael:0.013568965886590022 cl:23.422848314868293

filename: 3_4_hidden Epoch 28 loss:2.351051754241168 ael:0.0135531954068694 cl:23.374985119845338

filename: 3_4_hidden Epoch 29 loss:2.347007390477407 ael:0.013572756650105705 cl:23.33434584739593

filename: 3_4_hidden Epoch 30 loss:2.3430051879640628 ael:0.013590581714241691 cl:23.29414557997159

filename: 3_4_hidden Epoch 31 loss:2.3411621949959924 ael:0.01362621448022657 cl:23.27535931825564

filename: 3_4_hidden Epoch 32 loss:2.336070516708282 ael:0.013625269577763202 cl:23.22445199717749

filename: 3_4_hidden Epoch 33 loss:2.332323180259511 ael:0.01363717060196959 cl:23.186859673706508

filename: 3_4_hidden Epoch 34 loss:2.3304943053040867 ael:0.0135901877137415 cl:23.169040723642944

filename: 3_4_hidden Epoch 35 loss:2.328059493738566 ael:0.013620353282217864 cl:23.144390937306632

filename: 3_4_hidden Epoch 36 loss:2.324639292020257 ael:0.013628051278506428 cl:23.11011192472995

filename: 3_4_hidden Epoch 37 loss:2.322704856002172 ael:0.013625903385317835 cl:23.090789058327342

filename: 3_4_hidden Epoch 38 loss:2.319048412040351 ael:0.01371637596202205 cl:23.053319858965693

filename: 3_4_hidden Epoch 39 loss:2.3159295151794095 ael:0.013616671745044393 cl:23.02312795781395

filename: 3_4_hidden Epoch 40 loss:2.3129003370609325 ael:0.013659772446702677 cl:22.992405166342444

filename: 3_4_hidden Epoch 41 loss:2.310697663934211 ael:0.013719584138128882 cl:22.96978032622185

filename: 3_4_hidden Epoch 42 loss:2.3085442031267887 ael:0.013817091081920202 cl:22.94727066125099

filename: 3_4_hidden Epoch 43 loss:2.3056321648039217 ael:0.013784344011289522 cl:22.9184777267801

filename: 3_4_hidden Epoch 44 loss:2.3039591246324633 ael:0.013823501530085215 cl:22.901355752268604

filename: 3_4_hidden Epoch 45 loss:2.2987882561194857 ael:0.01379737332457496 cl:22.849908361496958

filename: 3_4_hidden Epoch 46 loss:2.2966055163808488 ael:0.013828614797326628 cl:22.827768543771487

filename: 3_4_hidden Epoch 47 loss:2.292922134626831 ael:0.013849073596997835 cl:22.790730136435407

filename: 3_4_hidden Epoch 48 loss:2.2882569363036738 ael:0.013860985114951277 cl:22.743959042338552

filename: 3_4_hidden Epoch 49 loss:2.284592891448273 ael:0.013836108144636898 cl:22.707567372680927

filename: 3_4_hidden Epoch 50 loss:2.2807043894188586 ael:0.013806717092452236 cl:22.668976233521644

filename: 3_4_hidden Epoch 51 loss:2.2775880447959485 ael:0.013818050680763399 cl:22.63769947452492

filename: 3_4_hidden Epoch 52 loss:2.2751696914222155 ael:0.013818409254087425 cl:22.61351237824252

filename: 3_4_hidden Epoch 53 loss:2.2710606496966856 ael:0.013892652150203142 cl:22.571679481229904

filename: 3_4_hidden Epoch 54 loss:2.270917108938324 ael:0.01385729847122278 cl:22.570597641827632

filename: 3_4_hidden Epoch 55 loss:2.268600775494816 ael:0.013893378129850215 cl:22.54707351665668

filename: 3_4_hidden Epoch 56 loss:2.2659606106623142 ael:0.01388599644231931 cl:22.52074566519493

filename: 3_4_hidden Epoch 57 loss:2.2653531363299106 ael:0.013923009655638242 cl:22.514300807410624

filename: 3_4_hidden Epoch 58 loss:2.2646419747616346 ael:0.013879140337122118 cl:22.5076279201608

filename: 3_4_hidden Epoch 59 loss:2.262643201833319 ael:0.013865606558499654 cl:22.487775497223875

filename: 3_4_hidden Epoch 60 loss:2.2590937171790135 ael:0.013844528197423062 cl:22.452491428284276

filename: 3_4_hidden Epoch 61 loss:2.2583820778506207 ael:0.013880657578408073 cl:22.445013732059557

filename: 3_4_hidden Epoch 62 loss:2.256402852698427 ael:0.01389870971681238 cl:22.4250409760391

filename: 3_4_hidden Epoch 63 loss:2.2546806015367293 ael:0.013929997142502383 cl:22.407505610144963

filename: 3_4_hidden Epoch 64 loss:2.2563465427562304 ael:0.013916287535715579 cl:22.424302066579695

filename: 3_4_hidden Epoch 65 loss:2.254366604415726 ael:0.013900406423871936 cl:22.40466150583295

filename: 3_4_hidden Epoch 66 loss:2.251202983249264 ael:0.013917580677543069 cl:22.372853564713974

filename: 3_4_hidden Epoch 67 loss:2.2481676794936982 ael:0.01387527629216229 cl:22.342923558655446

filename: 3_4_hidden Epoch 68 loss:2.2485058262976527 ael:0.013887375294377686 cl:22.34618401549556

filename: 3_4_hidden Epoch 69 loss:2.246505897936344 ael:0.013874157330730209 cl:22.326316939820884

filename: 3_4_hidden Epoch 70 loss:2.265256528590035 ael:0.013873059190371321 cl:22.513834226460013

filename: 3_4_hidden Epoch 71 loss:2.2465500305517794 ael:0.013872966009081703 cl:22.326770182917013

filename: 3_4_hidden Epoch 72 loss:2.24052991332488 ael:0.01387372122400868 cl:22.266561423118876

filename: 3_4_hidden Epoch 73 loss:2.241143025160205 ael:0.013904636210945691 cl:22.27238339778254

filename: 3_4_hidden Epoch 74 loss:2.240869447224352 ael:0.01392681589427979 cl:22.26942581006638

filename: 3_4_hidden Epoch 75 loss:2.2412934474584745 ael:0.013845206716537162 cl:22.274481936112466

filename: 3_4_hidden Epoch 76 loss:2.2395952382889575 ael:0.013864628778820751 cl:22.257305639673955

filename: 3_4_hidden Epoch 77 loss:2.2389293922363476 ael:0.013875377401951832 cl:22.25053967806384

filename: 3_4_hidden Epoch 78 loss:2.2389108862585974 ael:0.013917967829404508 cl:22.249928709817546

filename: 3_4_hidden Epoch 79 loss:2.237084362151712 ael:0.013901465647983991 cl:22.231828503506808

filename: 3_4_hidden Epoch 80 loss:2.247975989774714 ael:0.013897926962541312 cl:22.34078018965829

filename: 3_4_hidden Epoch 81 loss:2.236479709450399 ael:0.013726053145688434 cl:22.227536091903445

filename: 3_4_hidden Epoch 82 loss:2.2354304406177006 ael:0.013820525316752841 cl:22.216098701521943

filename: 3_4_hidden Epoch 83 loss:2.2337052287904795 ael:0.0138975916999704 cl:22.19807590438545

filename: 3_4_hidden Epoch 84 loss:2.2337873987680474 ael:0.013891978331254008 cl:22.198953766171577

filename: 3_4_hidden Epoch 85 loss:2.23260102057169 ael:0.013849929485328151 cl:22.187510471810644

filename: 3_4_hidden Epoch 86 loss:2.230645153610357 ael:0.013884370084292436 cl:22.167607364435984

filename: 3_4_hidden Epoch 87 loss:2.2317009920599884 ael:0.013831382219040216 cl:22.178695613734675

filename: 3_4_hidden Epoch 88 loss:2.230601827254344 ael:0.013834678522374893 cl:22.167671001005484

filename: 3_4_hidden Epoch 89 loss:2.229136031749781 ael:0.01381838065161078 cl:22.153176046887136

filename: 3_4_hidden Epoch 90 loss:2.2308818318593535 ael:0.013520163075508681 cl:22.17361621023812

filename: 3_4_hidden Epoch 91 loss:2.2378733786461558 ael:0.013151750053902386 cl:22.24721581797808

filename: 3_4_hidden Epoch 92 loss:2.2278304868676266 ael:0.012895029393818199 cl:22.149354116582177

filename: 3_4_hidden Epoch 93 loss:2.230216047386519 ael:0.013905767529058397 cl:22.163102333373644

filename: 3_4_hidden Epoch 94 loss:2.2256254774381885 ael:0.013882080474323294 cl:22.11743350071817

filename: 3_4_hidden Epoch 95 loss:2.226718611523772 ael:0.013864236110264707 cl:22.128543287875594

filename: 3_4_hidden Epoch 96 loss:2.2261845399514555 ael:0.013819308288697674 cl:22.12365183825831

filename: 3_4_hidden Epoch 97 loss:2.2284858172136994 ael:0.013806264577840146 cl:22.14679508498668

filename: 3_4_hidden Epoch 98 loss:2.2253014591686053 ael:0.013759942510424568 cl:22.115414714842768

filename: 3_4_hidden Epoch 99 loss:2.223560077777105 ael:0.013758012085527726 cl:22.098020193856655

filename: 3_4_hidden Epoch 100 loss:2.2257713041426634 ael:0.013624834569362008 cl:22.121464251733556

filename: 3_4_hidden Epoch 101 loss:2.223203634913029 ael:0.01366152583147561 cl:22.095420621799292

filename: 3_4_hidden Epoch 102 loss:2.2230943647395276 ael:0.013599920709559463 cl:22.09494399226978

filename: 3_4_hidden Epoch 103 loss:2.2222433179921506 ael:0.013481228592462051 cl:22.087620421805667

filename: 3_4_hidden Epoch 104 loss:2.222792482331797 ael:0.01333845936318011 cl:22.094539756928484

filename: 3_4_hidden Epoch 105 loss:2.2224489049521643 ael:0.013189110182428755 cl:22.09259748355491

filename: 3_4_hidden Epoch 106 loss:2.220335188942747 ael:0.013109085183520275 cl:22.072260573390984

filename: 3_4_hidden Epoch 107 loss:2.2228996031939263 ael:0.012872450949826655 cl:22.10027101055392

filename: 3_4_hidden Epoch 108 loss:2.221770356261867 ael:0.012744803152073922 cl:22.090255054463245

filename: 3_4_hidden Epoch 109 loss:2.219843303762231 ael:0.012548715440333166 cl:22.072945445046848

filename: 3_4_hidden Epoch 110 loss:2.219484656763062 ael:0.01238451261718268 cl:22.071000964252452

filename: 3_4_hidden Epoch 111 loss:2.2252405034236844 ael:0.012276001286987975 cl:22.12964455399878

filename: 3_4_hidden Epoch 112 loss:2.217306415153827 ael:0.01215849809242443 cl:22.05147867861382

filename: 3_4_hidden Epoch 113 loss:2.2196193978158116 ael:0.01200245245316286 cl:22.07616900600269

filename: 3_4_hidden Epoch 114 loss:2.222806725534502 ael:0.01173666731150721 cl:22.11070008217347

filename: 3_4_hidden Epoch 115 loss:2.2175154546053646 ael:0.011575125377324112 cl:22.05940281728282

filename: 3_4_hidden Epoch 116 loss:2.218756072511611 ael:0.011260754941622608 cl:22.074952717719338

filename: 3_4_hidden Epoch 117 loss:2.216311134912533 ael:0.011016382449028217 cl:22.052947039351665

filename: 3_4_hidden Epoch 118 loss:2.2176958905096282 ael:0.010518516029686096 cl:22.07177326619422

filename: 3_4_hidden Epoch 119 loss:2.215689134952194 ael:0.010022342391802445 cl:22.05666745724269

filename: 3_4_hidden Epoch 120 loss:2.2141031675126097 ael:0.0094918439236287 cl:22.046112771741598

filename: 3_4_hidden Epoch 121 loss:2.214848607160167 ael:0.008974311863798757 cl:22.058742480368096

filename: 3_4_hidden Epoch 122 loss:2.214347417046685 ael:0.008561733738049408 cl:22.05785638165939

filename: 3_4_hidden Epoch 123 loss:2.2128220823904647 ael:0.008172272495001314 cl:22.046497620529124

filename: 3_4_hidden Epoch 124 loss:2.22491364207346 ael:0.007958331857033514 cl:22.169552630852458

filename: 3_4_hidden Epoch 125 loss:2.2128544512382784 ael:0.007676438246609931 cl:22.051779657519244

filename: 3_4_hidden Epoch 126 loss:2.2101310996973837 ael:0.007526449519378292 cl:22.02604603110249

filename: 3_4_hidden Epoch 127 loss:2.2105725401139695 ael:0.007430205278250872 cl:22.03142287111681

filename: 3_4_hidden Epoch 128 loss:2.2112937176253413 ael:0.007175113453182801 cl:22.041185566868787

filename: 3_4_hidden Epoch 129 loss:2.2109330415578037 ael:0.007057826946001787 cl:22.038751712632497

filename: 3_4_hidden Epoch 130 loss:2.210029187494847 ael:0.006802528495382611 cl:22.03226611945754

filename: 3_4_hidden Epoch 131 loss:2.208325077926976 ael:0.006570370512509464 cl:22.017546592610802

filename: 3_4_hidden Epoch 132 loss:2.211338381938574 ael:0.006307169437822625 cl:22.05031165651361

filename: 3_4_hidden Epoch 133 loss:2.208962165043058 ael:0.006204972043345036 cl:22.027571489435115

filename: 3_4_hidden Epoch 134 loss:2.2100654013867937 ael:0.0059802957682689485 cl:22.040850574071655

filename: 3_4_hidden Epoch 135 loss:2.207320748412155 ael:0.005842280443486654 cl:22.014784214259596

filename: 3_4_hidden Epoch 136 loss:2.209324820006953 ael:0.005728251324042438 cl:22.03596519146515

filename: 3_4_hidden Epoch 137 loss:2.2061897035204763 ael:0.005635835856519993 cl:22.005538215058326

filename: 3_4_hidden Epoch 138 loss:2.2088172510335524 ael:0.005469154734028917 cl:22.033480492122553

filename: 3_4_hidden Epoch 139 loss:2.2085238998244145 ael:0.005379993934761162 cl:22.031438556977122

filename: 3_4_hidden Epoch 140 loss:2.2064092909820903 ael:0.0053744723881341315 cl:22.010347753237113

filename: 3_4_hidden Epoch 141 loss:2.2039251505830184 ael:0.005269343585693692 cl:21.986557622338346

filename: 3_4_hidden Epoch 142 loss:2.2065494146166884 ael:0.005322963754006467 cl:22.01226404437564

filename: 3_4_hidden Epoch 143 loss:2.20567689432231 ael:0.005169926294736788 cl:22.005069210493147

filename: 3_4_hidden Epoch 144 loss:2.2064733857449896 ael:0.005212437696700132 cl:22.01260907541454

filename: 3_4_hidden Epoch 145 loss:2.2053066318564536 ael:0.00517189564669638 cl:22.001346882300023

filename: 3_4_hidden Epoch 146 loss:2.2051994056663267 ael:0.005124931614794075 cl:22.000744253461594

filename: 3_4_hidden Epoch 147 loss:2.205935930533836 ael:0.005052752526763673 cl:22.00883129293537

filename: 3_4_hidden Epoch 148 loss:2.2039515375168044 ael:0.0049601866877079705 cl:21.989913039622422

filename: 3_4_hidden Epoch 149 loss:2.2050468035990627 ael:0.004984159679528466 cl:22.00062597244655

filename: 3_4_hidden Epoch 150 loss:2.202677653204291 ael:0.004947965662982967 cl:21.97729641928249

filename: 3_4_hidden Epoch 151 loss:2.2016556450145908 ael:0.0049654148694545435 cl:21.966901850058

filename: 3_4_hidden Epoch 152 loss:2.2064347149381405 ael:0.004936671368322041 cl:22.014979975332082

filename: 3_4_hidden Epoch 153 loss:2.202532667314796 ael:0.004890295197741905 cl:21.976423256461484

filename: 3_4_hidden Epoch 154 loss:2.2058270956274524 ael:0.004884217935419602 cl:22.009428290694665

filename: 3_4_hidden Epoch 155 loss:2.2037429310065297 ael:0.0047996396105275015 cl:21.989432434431723

filename: 3_4_hidden Epoch 156 loss:2.2062213458524615 ael:0.004811779604564237 cl:22.014095195346147

filename: 3_4_hidden Epoch 157 loss:2.2032880839566102 ael:0.004771059756096569 cl:21.985169784319073

filename: 3_4_hidden Epoch 158 loss:2.2051338198458903 ael:0.00476366869794345 cl:22.00370105260221

filename: 3_4_hidden Epoch 159 loss:2.2059952888595094 ael:0.004770151920790835 cl:22.012250894066277

filename: 3_4_hidden Epoch 160 loss:2.20197309171057 ael:0.004736608548448085 cl:21.972364334397067

filename: 3_4_hidden Epoch 161 loss:2.203987493054274 ael:0.004712773184414599 cl:21.992746734737278

filename: 3_4_hidden Epoch 162 loss:2.201359678289402 ael:0.004642711836958899 cl:21.9671691423158

filename: 3_4_hidden Epoch 163 loss:2.2023856196842093 ael:0.004655303139344536 cl:21.97730268181275

filename: 3_4_hidden Epoch 164 loss:2.2052228694066947 ael:0.004664251682215586 cl:22.00558570325467

filename: 3_4_hidden Epoch 165 loss:2.1997773202073283 ael:0.004599061623038582 cl:21.951782098382058

filename: 3_4_hidden Epoch 166 loss:2.2011954375338205 ael:0.004576433610924444 cl:21.966189560782396

filename: 3_4_hidden Epoch 167 loss:2.2011917169044617 ael:0.004565537581119321 cl:21.966261338286813

filename: 3_4_hidden Epoch 168 loss:2.1983010909180036 ael:0.004562963960884377 cl:21.937380797208075

filename: 3_4_hidden Epoch 169 loss:2.19960543757882 ael:0.004549750721701627 cl:21.950556407442917

filename: 3_4_hidden Epoch 170 loss:2.1970811190712967 ael:0.004488531649504959 cl:21.92592539038589

filename: 3_4_hidden Epoch 171 loss:2.201684252770555 ael:0.004442476554401392 cl:21.9724172811901

filename: 3_4_hidden Epoch 172 loss:2.198068307109867 ael:0.004428729073084792 cl:21.936395311104548

filename: 3_4_hidden Epoch 173 loss:2.202456053989005 ael:0.004497807007282972 cl:21.979582018363434

filename: 3_4_hidden Epoch 174 loss:2.1969324300886495 ael:0.0044130968390284735 cl:21.925192892016106

filename: 3_4_hidden Epoch 175 loss:2.196946723094183 ael:0.004402395409781956 cl:21.925442789242563

filename: 3_4_hidden Epoch 176 loss:2.197383677859763 ael:0.004392999361150057 cl:21.929906330598918

filename: 3_4_hidden Epoch 177 loss:2.2001224557989407 ael:0.004390547560373902 cl:21.957318619332028

filename: 3_4_hidden Epoch 178 loss:2.1976391895890197 ael:0.004411657430813035 cl:21.932274846478343

filename: 3_4_hidden Epoch 179 loss:2.1991691477123743 ael:0.004337972434631011 cl:21.94831126848955

filename: 3_4_hidden Epoch 180 loss:2.1964436818586854 ael:0.004308571898257005 cl:21.921350615576127

filename: 3_4_hidden Epoch 181 loss:2.1956075462404514 ael:0.004339010926576711 cl:21.912684876839787

filename: 3_4_hidden Epoch 182 loss:2.1955722795990313 ael:0.004297698760124258 cl:21.912745329572452

filename: 3_4_hidden Epoch 183 loss:2.196626309825747 ael:0.004316383877944475 cl:21.923098770595253

filename: 3_4_hidden Epoch 184 loss:2.1968958792800173 ael:0.004320884874429739 cl:21.9257494535709

filename: 3_4_hidden Epoch 185 loss:2.197087759460669 ael:0.0042981179019354904 cl:21.92789592931942

filename: 3_4_hidden Epoch 186 loss:2.196528332821907 ael:0.004301648713029937 cl:21.922266383332044

filename: 3_4_hidden Epoch 187 loss:2.196636707024443 ael:0.004292722149833127 cl:21.923439396243598

filename: 3_4_hidden Epoch 188 loss:2.1962775768750813 ael:0.004273484108338496 cl:21.920040444273372

filename: 3_4_hidden Epoch 189 loss:2.19508412575419 ael:0.004238988001077799 cl:21.90845093796518

filename: 3_4_hidden Epoch 190 loss:2.1969929671427826 ael:0.004230374734045187 cl:21.927625457654983

filename: 3_4_hidden Epoch 191 loss:2.199257691898151 ael:0.004246104251796402 cl:21.9501154170977

filename: 3_4_hidden Epoch 192 loss:2.199700769458108 ael:0.004236425601491648 cl:21.954642976316073

filename: 3_4_hidden Epoch 193 loss:2.201685797913446 ael:0.004296329514835619 cl:21.973894185420345

filename: 3_4_hidden Epoch 194 loss:2.2005497548704955 ael:0.0042282102262378015 cl:21.963214971731972

filename: 3_4_hidden Epoch 195 loss:2.1962757541801805 ael:0.004221452005307333 cl:21.920542587913495

filename: 3_4_hidden Epoch 196 loss:2.1969635354065975 ael:0.004246476061135119 cl:21.927170114644213

filename: 3_4_hidden Epoch 197 loss:2.199163159337639 ael:0.004279789910774324 cl:21.948833232252323

filename: 3_4_hidden Epoch 198 loss:2.197007871515871 ael:0.004225988582122152 cl:21.927818364497494

filename: 3_4_hidden Epoch 199 loss:2.1981102728408053 ael:0.004205120068514179 cl:21.939051057798423

filename: 3_4_hidden Epoch 200 loss:2.1979081476388167 ael:0.004194828889169175 cl:21.93713271341002

filename: 3_4_hidden Epoch 201 loss:2.1983936424778134 ael:0.004180983725338759 cl:21.94212615744696

filename: 3_4_hidden Epoch 202 loss:2.198665652344492 ael:0.0041744817677364975 cl:21.94491124972724

filename: 3_4_hidden Epoch 203 loss:2.20168214510306 ael:0.00415847267929295 cl:21.97523623555391

filename: 3_4_hidden Epoch 204 loss:2.1968886523322078 ael:0.004125944182484968 cl:21.927626605372048

filename: 3_4_hidden Epoch 205 loss:2.198949237067694 ael:0.004180666992164509 cl:21.947685219843567

filename: 3_4_hidden Epoch 206 loss:2.198446369606779 ael:0.004114323743359731 cl:21.943320033645513

filename: 3_4_hidden Epoch 207 loss:2.1974618424568875 ael:0.004152248354386982 cl:21.933095481307856

filename: 3_4_hidden Epoch 208 loss:2.1960178756905844 ael:0.0040472601509381045 cl:21.919705667669984

filename: 3_4_hidden Epoch 209 loss:2.1968030166463537 ael:0.0041044067875382634 cl:21.926985622227615

filename: 3_4_hidden Epoch 210 loss:2.1942482851503358 ael:0.004036451390802805 cl:21.902117853527947

filename: 3_4_hidden Epoch 211 loss:2.1953781014368903 ael:0.003991113670995778 cl:21.913869388777613

filename: 3_4_hidden Epoch 212 loss:2.1955231033120226 ael:0.004057232391743348 cl:21.914658234857043

filename: 3_4_hidden Epoch 213 loss:2.195610352144333 ael:0.0040064484805973945 cl:21.916038580522628

filename: 3_4_hidden Epoch 214 loss:2.196479652274242 ael:0.0040241744829017006 cl:21.924554320967726

filename: 3_4_hidden Epoch 215 loss:2.1970744110475424 ael:0.0040291542662223975 cl:21.930452105798896

filename: 3_4_hidden Epoch 216 loss:2.1943308815346225 ael:0.003947154864032582 cl:21.903836793743004

filename: 3_4_hidden Epoch 217 loss:2.194956255608869 ael:0.003925025096156232 cl:21.9103118155755

filename: 3_4_hidden Epoch 218 loss:2.1938060095303564 ael:0.0038968605542692163 cl:21.899091017951385

filename: 3_4_hidden Epoch 219 loss:2.1997646445569403 ael:0.0039018045466384004 cl:21.958627934720205

filename: 3_4_hidden Epoch 220 loss:2.2030728262768107 ael:0.0038662201373212872 cl:21.992065573816664

filename: 3_4_hidden Epoch 221 loss:2.195551615117245 ael:0.0038726554328928184 cl:21.916789129002613

filename: 3_4_hidden Epoch 222 loss:2.195668484486083 ael:0.0038758477782464295 cl:21.917925897564597

filename: 3_4_hidden Epoch 223 loss:2.194736675235575 ael:0.003837640286279342 cl:21.90898988977162

filename: 3_4_hidden Epoch 224 loss:2.193503522954145 ael:0.003812078427068818 cl:21.896913989478495

filename: 3_4_hidden Epoch 225 loss:2.1932783031212577 ael:0.0038322200711681568 cl:21.894460377437703

filename: 3_4_hidden Epoch 226 loss:2.194208985292051 ael:0.003785316062847152 cl:21.904236228519935

filename: 3_4_hidden Epoch 227 loss:2.192296070999389 ael:0.0037580824028221804 cl:21.88537941321606

filename: 3_4_hidden Epoch 228 loss:2.1930188086055757 ael:0.0037903877206062497 cl:21.8922837547711

filename: 3_4_hidden Epoch 229 loss:2.19472074663724 ael:0.0037222942030221712 cl:21.909984068222258

filename: 3_4_hidden Epoch 230 loss:2.192552303780561 ael:0.0038134808377090225 cl:21.88738775031786

filename: 3_4_hidden Epoch 231 loss:2.192099343626519 ael:0.003783149646967765 cl:21.88316148454909

filename: 3_4_hidden Epoch 232 loss:2.195252065726499 ael:0.0037544368484745956 cl:21.914975834099565

filename: 3_4_hidden Epoch 233 loss:2.192081259514533 ael:0.0037402562984833873 cl:21.88340955978209

filename: 3_4_hidden Epoch 234 loss:2.1928328698026243 ael:0.0037339963282081515 cl:21.890988290549874

filename: 3_4_hidden Epoch 235 loss:2.2030579374832575 ael:0.0036695449653125723 cl:21.993883457225188

filename: 3_4_hidden Epoch 236 loss:2.192573170131779 ael:0.0037738549890508313 cl:21.887992685813586

filename: 3_4_hidden Epoch 237 loss:2.1914922851052734 ael:0.0036999022625052143 cl:21.87792336796784

filename: 3_4_hidden Epoch 238 loss:2.1932804204244367 ael:0.003676185306518135 cl:21.89604190142393

filename: 3_4_hidden Epoch 239 loss:2.192377689010996 ael:0.003664643272192795 cl:21.887129988305595

filename: 3_4_hidden Epoch 240 loss:2.1907876800110038 ael:0.003643570499772713 cl:21.871440618685725

filename: 3_4_hidden Epoch 241 loss:2.191553394910388 ael:0.0036527877362729382 cl:21.879005609336893

filename: 3_4_hidden Epoch 242 loss:2.191382745981733 ael:0.0037244560765047705 cl:21.876582416523792

filename: 3_4_hidden Epoch 243 loss:2.1920070714646354 ael:0.003651913538902246 cl:21.883551125926623

filename: 3_4_hidden Epoch 244 loss:2.1894367119593308 ael:0.0036384358106699615 cl:21.85798228049138

filename: 3_4_hidden Epoch 245 loss:2.191565317980606 ael:0.0035790543722467004 cl:21.879862164816053

filename: 3_4_hidden Epoch 246 loss:2.1904098931463483 ael:0.0036344134276770296 cl:21.86775433755061

filename: 3_4_hidden Epoch 247 loss:2.190788983264993 ael:0.003596335639611819 cl:21.87192598663642

filename: 3_4_hidden Epoch 248 loss:2.189480415731438 ael:0.0035552429059100997 cl:21.859251234397757

filename: 3_4_hidden Epoch 249 loss:2.1907277303275103 ael:0.0035796575998145014 cl:21.871480228214967

filename: 3_4_hidden Epoch 250 loss:2.1919524288650045 ael:0.003637018835532011 cl:21.883153619467937

/tmp/ipykernel_336185/680421385.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
/tmp/ipykernel_336185/680421385.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3  Label
0       -0.061066 -0.062066 -0.059632 -0.057274      1
1       -0.049778 -0.045010 -0.039313 -0.034974      0
2       -0.023087 -0.032005 -0.054075 -0.062451      2
3       -0.057615 -0.062337 -0.056680 -0.058423      1
4       -0.023093 -0.032012 -0.054075 -0.062451      2
...           ...       ...       ...       ...    ...
1652882 -0.049787 -0.044973 -0.039221 -0.034810      0
1652883 -0.023085 -0.032003 -0.054075 -0.062451      2
1652884 -0.023083 -0.032001 -0.054075 -0.062450      2
1652885 -0.049772 -0.045030 -0.039363 -0.035062      0
1652886 -0.022937 -0.031835 -0.054066 -0.062442      2

[1652887 rows x 5 columns]

Davies-Bouldin Score: 0.625077428665206

               0         1         2         3  Label
0      -0.050414 -0.046971 -0.039124 -0.037086      0
1      -0.023093 -0.032012 -0.054075 -0.062451      2
2      -0.059681 -0.063659 -0.057020 -0.059436      1
3      -0.027853 -0.035282 -0.055789 -0.062094      3
4      -0.059082 -0.061548 -0.056380 -0.057483      1
...          ...       ...       ...       ...    ...
519951 -0.058993 -0.062492 -0.055747 -0.058064      1
519952 -0.058050 -0.060235 -0.050279 -0.053575      4
519953 -0.049785 -0.044983 -0.039245 -0.034852      0
519954 -0.061765 -0.062612 -0.060868 -0.058324      1
519955 -0.058249 -0.003849 -0.049203 -0.093224      3

[519956 rows x 5 columns]

               0         1         2         3  Label
0      -0.049779 -0.045006 -0.039303 -0.034957      0
1      -0.050655 -0.047331 -0.039605 -0.037551      0
2      -0.060313 -0.062960 -0.056864 -0.057753      1
3      -0.053768 -0.057990 -0.046493 -0.050363      1
4      -0.050005 -0.045595 -0.037508 -0.034614      0
...          ...       ...       ...       ...    ...
649942 -0.058930 -0.061535 -0.056275 -0.057424      1
649943 -0.049733 -0.045519 -0.037374 -0.034737      0
649944 -0.049904 -0.045575 -0.037460 -0.034665      0
649945 -0.019691 -0.041605 -0.047803 -0.071150      3
649946 -0.026751 -0.035489 -0.054923 -0.062711      2

[649947 rows x 5 columns]

3_5_hidden

cuda

[0.0, 1.0, 2.0, 4.0]

pick completo
82 4

filename: 3_5_hidden Epoch 1 loss:3.9690633163292537 ael:0.02380236731257648 cl:39.45260886081925

filename: 3_5_hidden Epoch 2 loss:3.5139810941209353 ael:0.016456295593772888 cl:34.975247481278295

filename: 3_5_hidden Epoch 3 loss:3.4831159908236153 ael:0.016337244766485078 cl:34.66778695706377

filename: 3_5_hidden Epoch 4 loss:3.453084059639456 ael:0.015426891996957766 cl:34.37657116314025

filename: 3_5_hidden Epoch 5 loss:3.4282113794169833 ael:0.014843834974287361 cl:34.133674948252064

filename: 3_5_hidden Epoch 6 loss:3.413461382252734 ael:0.014734075595384446 cl:33.98727257168609

filename: 3_5_hidden Epoch 7 loss:3.4045571252059403 ael:0.014518826104170608 cl:33.90038251624114

filename: 3_5_hidden Epoch 8 loss:3.395683402961933 ael:0.014100944195228475 cl:33.81582412240894

filename: 3_5_hidden Epoch 9 loss:3.386880136234491 ael:0.01369746027922198 cl:33.73182627094008

filename: 3_5_hidden Epoch 10 loss:3.376869482641606 ael:0.013472880695061954 cl:33.63396556380736

filename: 3_5_hidden Epoch 11 loss:3.364133262700782 ael:0.013311173110898984 cl:33.50822040339727

filename: 3_5_hidden Epoch 12 loss:3.3504800777222488 ael:0.013080036219058759 cl:33.373999939071254

filename: 3_5_hidden Epoch 13 loss:3.3379668635470763 ael:0.012834855033710827 cl:33.2513195990186

filename: 3_5_hidden Epoch 14 loss:3.327317800747966 ael:0.012583388904346 cl:33.14734363050474

filename: 3_5_hidden Epoch 15 loss:3.3176603585273816 ael:0.012289454108636666 cl:33.05370856887626

filename: 3_5_hidden Epoch 16 loss:3.3111960218873815 ael:0.01188542715311466 cl:32.9931054672603

filename: 3_5_hidden Epoch 17 loss:3.302915330977287 ael:0.011585658016605523 cl:32.91329626245645

filename: 3_5_hidden Epoch 18 loss:3.2972165629122214 ael:0.011323501432582091 cl:32.85893013128177

filename: 3_5_hidden Epoch 19 loss:3.290463168783999 ael:0.011008397891151107 cl:32.794547240338396

filename: 3_5_hidden Epoch 20 loss:3.2847685035801333 ael:0.01071814307163637 cl:32.74050311323988

filename: 3_5_hidden Epoch 21 loss:3.2799861183060095 ael:0.010508154439148876 cl:32.69477914413814

filename: 3_5_hidden Epoch 22 loss:3.2750590607045917 ael:0.010278099860133528 cl:32.64780914061904

filename: 3_5_hidden Epoch 23 loss:3.270810611809979 ael:0.009939024818611735 cl:32.60871539202362

filename: 3_5_hidden Epoch 24 loss:3.2662273039212617 ael:0.009668546693329408 cl:32.5655870940396

filename: 3_5_hidden Epoch 25 loss:3.261721455668472 ael:0.00953578902941036 cl:32.521856216473225

filename: 3_5_hidden Epoch 26 loss:3.25822300352312 ael:0.009439822312865297 cl:32.48783133864569

filename: 3_5_hidden Epoch 27 loss:3.2529099602080787 ael:0.009388266728653194 cl:32.43521647007728

filename: 3_5_hidden Epoch 28 loss:3.248300174955211 ael:0.00933567673380966 cl:32.38964450628688

filename: 3_5_hidden Epoch 29 loss:3.24745140215343 ael:0.00919356430702774 cl:32.38257789984242

filename: 3_5_hidden Epoch 30 loss:3.2444235986579244 ael:0.009196502841344023 cl:32.35227049823585

filename: 3_5_hidden Epoch 31 loss:3.240472419225355 ael:0.009183543840114085 cl:32.3128882792538

filename: 3_5_hidden Epoch 32 loss:3.2384480460418317 ael:0.009106654922557135 cl:32.293413427185314

filename: 3_5_hidden Epoch 33 loss:3.2346378091655184 ael:0.00907320646735394 cl:32.255645568932785

filename: 3_5_hidden Epoch 34 loss:3.2316947402980705 ael:0.009013440552319568 cl:32.22681250791669

filename: 3_5_hidden Epoch 35 loss:3.2278380569553775 ael:0.009029232759828806 cl:32.18808776344714

filename: 3_5_hidden Epoch 36 loss:3.2261393785809207 ael:0.008947510402026161 cl:32.171918212486275

filename: 3_5_hidden Epoch 37 loss:3.2242745346936554 ael:0.008974359887736528 cl:32.15300127558795

filename: 3_5_hidden Epoch 38 loss:3.2217140659960077 ael:0.008958699780995626 cl:32.12755316357899

filename: 3_5_hidden Epoch 39 loss:3.2212163229533983 ael:0.008895617546033078 cl:32.12320658472293

filename: 3_5_hidden Epoch 40 loss:3.2163289433243882 ael:0.008885823961508407 cl:32.07443071947936

filename: 3_5_hidden Epoch 41 loss:3.214623668370054 ael:0.008887546607312672 cl:32.0573607589743

filename: 3_5_hidden Epoch 42 loss:3.2138251953045196 ael:0.00892891582215888 cl:32.04896231030154

filename: 3_5_hidden Epoch 43 loss:3.211145511398422 ael:0.008889224686668964 cl:32.022562370672716

filename: 3_5_hidden Epoch 44 loss:3.2092392904821634 ael:0.008901477653424111 cl:32.003377663839814

filename: 3_5_hidden Epoch 45 loss:3.2092332954353533 ael:0.008809626642406776 cl:32.00423624525509

filename: 3_5_hidden Epoch 46 loss:3.206847911898561 ael:0.008689362095796205 cl:31.981585006501053

filename: 3_5_hidden Epoch 47 loss:3.2059146029846106 ael:0.008652241113809985 cl:31.97262317705354

filename: 3_5_hidden Epoch 48 loss:3.203893574644166 ael:0.008583164907669754 cl:31.953103616945914

filename: 3_5_hidden Epoch 49 loss:3.2022982236896764 ael:0.00853575492976558 cl:31.937624246339254

filename: 3_5_hidden Epoch 50 loss:3.200570200211167 ael:0.008530490229495981 cl:31.920396621789227

filename: 3_5_hidden Epoch 51 loss:3.1999024985724414 ael:0.008485264379292144 cl:31.914171831777406

filename: 3_5_hidden Epoch 52 loss:3.1995179329290884 ael:0.008455666352967463 cl:31.910622188403185

filename: 3_5_hidden Epoch 53 loss:3.1972583933022896 ael:0.008373188817512499 cl:31.88885155734989

filename: 3_5_hidden Epoch 54 loss:3.195742000728804 ael:0.0082747209957454 cl:31.87467232708153

filename: 3_5_hidden Epoch 55 loss:3.1956022099637256 ael:0.00835117569655658 cl:31.872509864583673

filename: 3_5_hidden Epoch 56 loss:3.193911197295249 ael:0.008293248268657441 cl:31.85617901790092

filename: 3_5_hidden Epoch 57 loss:3.1921619311536205 ael:0.008058082613823845 cl:31.84103803328723

filename: 3_5_hidden Epoch 58 loss:3.1910361880537854 ael:0.0077983598513178 cl:31.832377828813495

filename: 3_5_hidden Epoch 59 loss:3.1901731179182833 ael:0.007673703340457615 cl:31.824993653343977

filename: 3_5_hidden Epoch 60 loss:3.1905984565303913 ael:0.007484857517202363 cl:31.83113552024341

filename: 3_5_hidden Epoch 61 loss:3.1882834957899577 ael:0.007291825187250951 cl:31.80991622839679

filename: 3_5_hidden Epoch 62 loss:3.1873762120096587 ael:0.007171111435056605 cl:31.80205055034643

filename: 3_5_hidden Epoch 63 loss:3.1869625464642897 ael:0.0071994447571483945 cl:31.797630546282527

filename: 3_5_hidden Epoch 64 loss:3.186043543995175 ael:0.006961648810441857 cl:31.79081846686753

filename: 3_5_hidden Epoch 65 loss:3.184569154656914 ael:0.006857404458197548 cl:31.77711700375609

filename: 3_5_hidden Epoch 66 loss:3.185286232218084 ael:0.006714413588609406 cl:31.785717709593193

filename: 3_5_hidden Epoch 67 loss:3.1832554446769725 ael:0.006585520862457518 cl:31.76669874204585

filename: 3_5_hidden Epoch 68 loss:3.1851176985470655 ael:0.00651962747303782 cl:31.78598022514141

filename: 3_5_hidden Epoch 69 loss:3.182531149051512 ael:0.006404372786575697 cl:31.761267282440738

filename: 3_5_hidden Epoch 70 loss:3.1824215491280228 ael:0.006233610912788571 cl:31.761878910889354

filename: 3_5_hidden Epoch 71 loss:3.1833219498271226 ael:0.006142505397305744 cl:31.771793994344925

filename: 3_5_hidden Epoch 72 loss:3.1805828608562092 ael:0.005963898919044761 cl:31.74618913924511

filename: 3_5_hidden Epoch 73 loss:3.181161994814374 ael:0.005883408214434504 cl:31.752785400433186

filename: 3_5_hidden Epoch 74 loss:3.179029776627715 ael:0.005730517620202596 cl:31.732992108396907

filename: 3_5_hidden Epoch 75 loss:3.1788402234826294 ael:0.0056071997409741 cl:31.732329774800704

filename: 3_5_hidden Epoch 76 loss:3.178639507825737 ael:0.005298857609553047 cl:31.733406046677167

filename: 3_5_hidden Epoch 77 loss:3.1778335143665224 ael:0.004883964451788464 cl:31.729495006758132

filename: 3_5_hidden Epoch 78 loss:3.175860092463686 ael:0.004643155338899902 cl:31.712168886937523

filename: 3_5_hidden Epoch 79 loss:3.1753372384580776 ael:0.004405515642208015 cl:31.70931677665338

filename: 3_5_hidden Epoch 80 loss:3.1764116666972053 ael:0.004228366564990461 cl:31.721832533428028

filename: 3_5_hidden Epoch 81 loss:3.1749993369502834 ael:0.004055213019631107 cl:31.70944078198038

filename: 3_5_hidden Epoch 82 loss:3.1741141296663375 ael:0.003880643099416541 cl:31.702334391488858

filename: 3_5_hidden Epoch 83 loss:3.1759276987951006 ael:0.003787354794376357 cl:31.721402968721907

filename: 3_5_hidden Epoch 84 loss:3.1721531572035997 ael:0.003644121086583414 cl:31.68508985351818

filename: 3_5_hidden Epoch 85 loss:3.173198616022512 ael:0.0035870390229779223 cl:31.69611530809389

filename: 3_5_hidden Epoch 86 loss:3.17391139852452 ael:0.0035348391407812366 cl:31.703765104073028

filename: 3_5_hidden Epoch 87 loss:3.1715230923151205 ael:0.0034738639693686446 cl:31.68049182226801

filename: 3_5_hidden Epoch 88 loss:3.1701819836178915 ael:0.003435108968416538 cl:31.667468275551684

filename: 3_5_hidden Epoch 89 loss:3.170268736524063 ael:0.0034238592933894577 cl:31.668448280855866

filename: 3_5_hidden Epoch 90 loss:3.1715632783817944 ael:0.0033837277879302016 cl:31.68179501808837

filename: 3_5_hidden Epoch 91 loss:3.1712606716022997 ael:0.003354527240858064 cl:31.679060939432354

filename: 3_5_hidden Epoch 92 loss:3.1705979067245122 ael:0.003298833270815709 cl:31.672990272766707

filename: 3_5_hidden Epoch 93 loss:3.1697801361855436 ael:0.003280776340937868 cl:31.66499311588133

filename: 3_5_hidden Epoch 94 loss:3.170431746931089 ael:0.003246788398104212 cl:31.67184911858254

filename: 3_5_hidden Epoch 95 loss:3.225788116056051 ael:0.0034512415398405853 cl:32.22336826670286

filename: 3_5_hidden Epoch 96 loss:3.1710708775114647 ael:0.0031763920050005283 cl:31.67894436664661

filename: 3_5_hidden Epoch 97 loss:3.208135965113194 ael:0.003206687004109286 cl:32.04929230396053

filename: 3_5_hidden Epoch 98 loss:3.171114289976729 ael:0.003061281522343681 cl:31.68052961064848

filename: 3_5_hidden Epoch 99 loss:3.1672994312382143 ael:0.003052691176970135 cl:31.642466937481444

filename: 3_5_hidden Epoch 100 loss:3.1682872977715655 ael:0.0030232049135758827 cl:31.652640463750565

filename: 3_5_hidden Epoch 101 loss:3.1660595259407076 ael:0.0029992308721564598 cl:31.630602466577933

filename: 3_5_hidden Epoch 102 loss:3.165085035653959 ael:0.002981662090524844 cl:31.621033241027238

filename: 3_5_hidden Epoch 103 loss:3.164372845706913 ael:0.0029625419653287076 cl:31.614102568686256

filename: 3_5_hidden Epoch 104 loss:3.164659086996209 ael:0.0029329485633388433 cl:31.617260901266228

filename: 3_5_hidden Epoch 105 loss:3.1630456541372642 ael:0.002922001618156768 cl:31.60123606193681

filename: 3_5_hidden Epoch 106 loss:3.1825124900211352 ael:0.0029503019025219368 cl:31.795621417057564

filename: 3_5_hidden Epoch 107 loss:3.1654708398768427 ael:0.0028820762599102707 cl:31.625887144825615

filename: 3_5_hidden Epoch 108 loss:3.164551848380968 ael:0.0028708135957908887 cl:31.616809851355132

filename: 3_5_hidden Epoch 109 loss:3.1766497679834087 ael:0.002893385405176822 cl:31.737563360685087

filename: 3_5_hidden Epoch 110 loss:3.1766135826935495 ael:0.0028711787594490096 cl:31.737423552296317

filename: 3_5_hidden Epoch 111 loss:3.1861007034695463 ael:0.0028717866825002194 cl:31.83228865055526

filename: 3_5_hidden Epoch 112 loss:3.1643566025849665 ael:0.002765877942997583 cl:31.615906789080036

filename: 3_5_hidden Epoch 113 loss:3.1640251652466205 ael:0.0027183485518416164 cl:31.613067675900425

filename: 3_5_hidden Epoch 114 loss:3.164202740867434 ael:0.0026670098210901873 cl:31.615356826250192

filename: 3_5_hidden Epoch 115 loss:3.1613901049189654 ael:0.002629125630547977 cl:31.587609331245368

filename: 3_5_hidden Epoch 116 loss:3.1890210554024496 ael:0.002674266535917367 cl:31.863467416803207

filename: 3_5_hidden Epoch 117 loss:3.175732535398156 ael:0.002556948216256622 cl:31.73175539790836

filename: 3_5_hidden Epoch 118 loss:3.1707148798672558 ael:0.0025018172801018926 cl:31.682130165046893

filename: 3_5_hidden Epoch 119 loss:3.161088165245961 ael:0.0024221687008739766 cl:31.58665949982413

filename: 3_5_hidden Epoch 120 loss:3.15993438259162 ael:0.002391418778289478 cl:31.575429168339387

filename: 3_5_hidden Epoch 121 loss:3.161959314545827 ael:0.0023350028349398383 cl:31.596242640241254

filename: 3_5_hidden Epoch 122 loss:3.1604594494674663 ael:0.002267345442563929 cl:31.58192055887092

filename: 3_5_hidden Epoch 123 loss:3.160693387905424 ael:0.002207263877597148 cl:31.584860763124176

filename: 3_5_hidden Epoch 124 loss:3.159147246545661 ael:0.002158379713703347 cl:31.569888183827846

filename: 3_5_hidden Epoch 125 loss:3.160876249568732 ael:0.002138199514710712 cl:31.587380046126235

filename: 3_5_hidden Epoch 126 loss:3.1617357625788394 ael:0.002101811733209844 cl:31.596339045142862

filename: 3_5_hidden Epoch 127 loss:3.1583606129410877 ael:0.0020691986994251527 cl:31.562913664281783

filename: 3_5_hidden Epoch 128 loss:3.1579535400518313 ael:0.002028312232745409 cl:31.559251792726823

filename: 3_5_hidden Epoch 129 loss:3.1599265040712874 ael:0.0019900928755424594 cl:31.579363615709035

filename: 3_5_hidden Epoch 130 loss:3.156617858918641 ael:0.0019426817947938893 cl:31.546751268139445

filename: 3_5_hidden Epoch 131 loss:3.1624949763176997 ael:0.0018739643964898283 cl:31.606209671148196

filename: 3_5_hidden Epoch 132 loss:3.156488191067258 ael:0.0018379814079163839 cl:31.546501594341283

filename: 3_5_hidden Epoch 133 loss:3.1543951041196348 ael:0.0017939635570650735 cl:31.52601095010712

filename: 3_5_hidden Epoch 134 loss:3.1638437821110257 ael:0.001772947310479137 cl:31.620707851606767

filename: 3_5_hidden Epoch 135 loss:3.157733852327951 ael:0.001728423695778799 cl:31.560053812875577

filename: 3_5_hidden Epoch 136 loss:3.1619388543079756 ael:0.0016988452936352505 cl:31.60239963930521

filename: 3_5_hidden Epoch 137 loss:3.1573724467385262 ael:0.0016774728284068043 cl:31.556949283488127

filename: 3_5_hidden Epoch 138 loss:3.1547724778349595 ael:0.0016599959225427603 cl:31.531124345893808

filename: 3_5_hidden Epoch 139 loss:3.156020449660978 ael:0.0016474214293331563 cl:31.543729806578142

filename: 3_5_hidden Epoch 140 loss:3.1549004192964136 ael:0.0016369539106977815 cl:31.532634165296994

filename: 3_5_hidden Epoch 141 loss:3.1543989436895776 ael:0.001612078477862334 cl:31.52786817297942

filename: 3_5_hidden Epoch 142 loss:3.1609901059122762 ael:0.0016091659817892689 cl:31.593808936806735

filename: 3_5_hidden Epoch 143 loss:3.163156280424472 ael:0.0015816599007071135 cl:31.6157457269219

filename: 3_5_hidden Epoch 144 loss:3.1556472242294165 ael:0.0015542799325866398 cl:31.540928984552913

filename: 3_5_hidden Epoch 145 loss:3.1544005879464674 ael:0.0015419781001186 cl:31.528585638793775

filename: 3_5_hidden Epoch 146 loss:3.1543644442219114 ael:0.001528244305709234 cl:31.528361461751132

filename: 3_5_hidden Epoch 147 loss:3.1531170362874223 ael:0.0015088923921194213 cl:31.51608096379449

filename: 3_5_hidden Epoch 148 loss:3.1541547930224003 ael:0.0014805979784149443 cl:31.52674147474217

filename: 3_5_hidden Epoch 149 loss:3.1554808841423343 ael:0.0014778521921027146 cl:31.54002983274154

filename: 3_5_hidden Epoch 150 loss:3.1544761728209596 ael:0.0014547716562195864 cl:31.530213561117897

filename: 3_5_hidden Epoch 151 loss:3.1538892674146837 ael:0.001439579991436066 cl:31.524496401969028

filename: 3_5_hidden Epoch 152 loss:3.1549775950911987 ael:0.0014281116715162171 cl:31.535494342841197

filename: 3_5_hidden Epoch 153 loss:3.151706809545328 ael:0.001405187657689403 cl:31.503015752284263

filename: 3_5_hidden Epoch 154 loss:3.151193947373075 ael:0.0013908822325998697 cl:31.498030163752983

filename: 3_5_hidden Epoch 155 loss:3.1570535371160573 ael:0.0013709065514438718 cl:31.556825828818265

filename: 3_5_hidden Epoch 156 loss:3.151976012651558 ael:0.0013546731257895617 cl:31.50621292561168

filename: 3_5_hidden Epoch 157 loss:3.15169772603023 ael:0.0013538749403231927 cl:31.50343803288714

filename: 3_5_hidden Epoch 158 loss:3.1500991996860903 ael:0.0013341953447822486 cl:31.48764957763161

filename: 3_5_hidden Epoch 159 loss:3.1538574858523147 ael:0.0013249095724155214 cl:31.525325293654014

filename: 3_5_hidden Epoch 160 loss:3.1625311075394125 ael:0.0013226695852990638 cl:31.612083918147174

filename: 3_5_hidden Epoch 161 loss:3.1568161372526586 ael:0.0012836307116895862 cl:31.555324579981082

filename: 3_5_hidden Epoch 162 loss:3.1500806625584348 ael:0.0012816785997094137 cl:31.48798935596248

filename: 3_5_hidden Epoch 163 loss:3.149802303979254 ael:0.0012830796562079366 cl:31.485191770311513

filename: 3_5_hidden Epoch 164 loss:3.1517282233909913 ael:0.0012634916104878996 cl:31.504646827985052

filename: 3_5_hidden Epoch 165 loss:3.1522573558855256 ael:0.0012627858998815074 cl:31.50994522222415

filename: 3_5_hidden Epoch 166 loss:3.1494616338232406 ael:0.0012466870744828255 cl:31.482148985816178

filename: 3_5_hidden Epoch 167 loss:3.149759637428294 ael:0.001242436190422188 cl:31.485171531666605

filename: 3_5_hidden Epoch 168 loss:3.1509791795179933 ael:0.0012357743486672422 cl:31.49743356425393

filename: 3_5_hidden Epoch 169 loss:3.1530796962136836 ael:0.0012350866507584257 cl:31.518445608439638

filename: 3_5_hidden Epoch 170 loss:3.149198628136969 ael:0.0012276538314539393 cl:31.479709242178306

filename: 3_5_hidden Epoch 171 loss:3.159041166970587 ael:0.0012182571875052255 cl:31.57822860919947

filename: 3_5_hidden Epoch 172 loss:3.1495207803851226 ael:0.0012014963349614505 cl:31.4831923629782

filename: 3_5_hidden Epoch 173 loss:3.1491150314671557 ael:0.0011970497257007362 cl:31.47917934188949

filename: 3_5_hidden Epoch 174 loss:3.1522975797267474 ael:0.0012047411399020592 cl:31.510927887175704

filename: 3_5_hidden Epoch 175 loss:3.148331248444327 ael:0.0011946455991665886 cl:31.47136553520937

filename: 3_5_hidden Epoch 176 loss:3.1489336580412157 ael:0.00120076457601277 cl:31.47732848801872

filename: 3_5_hidden Epoch 177 loss:3.1498142935408375 ael:0.001186225746028941 cl:31.486280238046472

filename: 3_5_hidden Epoch 178 loss:3.1552931010806247 ael:0.0011874207418874384 cl:31.541056322020633

filename: 3_5_hidden Epoch 179 loss:3.148878372995757 ael:0.0011679631332844765 cl:31.477103627309972

filename: 3_5_hidden Epoch 180 loss:3.1485426878164335 ael:0.001165311042813005 cl:31.4737732960423

filename: 3_5_hidden Epoch 181 loss:3.153830824470254 ael:0.0011690465444562544 cl:31.52661731086848

filename: 3_5_hidden Epoch 182 loss:3.151701113569188 ael:0.0011504468243085939 cl:31.505506192025113

filename: 3_5_hidden Epoch 183 loss:3.1697614243506056 ael:0.0011610079277274321 cl:31.686003671430644

filename: 3_5_hidden Epoch 184 loss:3.1502893486448578 ael:0.0011291708960067975 cl:31.49160126136769

filename: 3_5_hidden Epoch 185 loss:3.152041627306652 ael:0.0011347752194195684 cl:31.509068029129686

filename: 3_5_hidden Epoch 186 loss:3.1593560476183393 ael:0.0011370537447973027 cl:31.582189454061382

filename: 3_5_hidden Epoch 187 loss:3.1474391839494267 ael:0.0011372880443198037 cl:31.463018492907494

filename: 3_5_hidden Epoch 188 loss:3.148800074139732 ael:0.001138488977311005 cl:31.476615374257875

filename: 3_5_hidden Epoch 189 loss:3.1548474147562535 ael:0.0011120083496510994 cl:31.53735361245553

filename: 3_5_hidden Epoch 190 loss:3.15046319429512 ael:0.0011156833238186604 cl:31.493474600670893

filename: 3_5_hidden Epoch 191 loss:3.147589727159657 ael:0.0011075170947897352 cl:31.464821638056755

filename: 3_5_hidden Epoch 192 loss:3.1494435451353278 ael:0.0011488426447491392 cl:31.48294655654886

filename: 3_5_hidden Epoch 193 loss:3.170178276524883 ael:0.0011516862735931595 cl:31.690265447491548

filename: 3_5_hidden Epoch 194 loss:3.184858203632562 ael:0.0011963577694428444 cl:31.836617955270338

filename: 3_5_hidden Epoch 195 loss:3.153271467549365 ael:0.0011361440560537569 cl:31.521352770604516

filename: 3_5_hidden Epoch 196 loss:3.147003752616659 ael:0.0011130193287033894 cl:31.458906853115874

filename: 3_5_hidden Epoch 197 loss:3.1476285151690453 ael:0.0011188376195971675 cl:31.465096342547003

filename: 3_5_hidden Epoch 198 loss:3.150103025356596 ael:0.00110649282719636 cl:31.48996482221319

filename: 3_5_hidden Epoch 199 loss:3.14751481391396 ael:0.00110749131524182 cl:31.464072744350887

filename: 3_5_hidden Epoch 200 loss:3.1515338871103284 ael:0.0010951672235634984 cl:31.504386729475844

filename: 3_5_hidden Epoch 201 loss:3.146288336204518 ael:0.0011128394097652198 cl:31.4517545266464

filename: 3_5_hidden Epoch 202 loss:3.1543833980001663 ael:0.001080791513413461 cl:31.533025635169974

filename: 3_5_hidden Epoch 203 loss:3.1495585794063126 ael:0.0010749243412847467 cl:31.484836070274874

filename: 3_5_hidden Epoch 204 loss:3.149899313140614 ael:0.0010968418050371631 cl:31.48802425538812

filename: 3_5_hidden Epoch 205 loss:3.1479236802961705 ael:0.0010698097897628568 cl:31.46853825557182

filename: 3_5_hidden Epoch 206 loss:3.14876520922992 ael:0.001104745830521585 cl:31.476604157877436

filename: 3_5_hidden Epoch 207 loss:3.146060456325153 ael:0.0010477884523856298 cl:31.450126205295366

filename: 3_5_hidden Epoch 208 loss:3.146952687147771 ael:0.001055214122328076 cl:31.458974270042514

filename: 3_5_hidden Epoch 209 loss:3.147025031524722 ael:0.0010453391689651307 cl:31.459796467652048

filename: 3_5_hidden Epoch 210 loss:3.1528052050698254 ael:0.0010521301828231274 cl:31.51753031040335

filename: 3_5_hidden Epoch 211 loss:3.151991068335923 ael:0.0010442038414794615 cl:31.50946818342435

filename: 3_5_hidden Epoch 212 loss:3.1520321155691744 ael:0.001045187944244344 cl:31.5098687883534

filename: 3_5_hidden Epoch 213 loss:3.145863917482448 ael:0.0010514802215659843 cl:31.448123886661715

filename: 3_5_hidden Epoch 214 loss:3.1478231751935417 ael:0.0010320142264487 cl:31.467911145411108

filename: 3_5_hidden Epoch 215 loss:3.1531121232020807 ael:0.0010154233277402558 cl:31.520966520535563

filename: 3_5_hidden Epoch 216 loss:3.1466575699703796 ael:0.001049488682119303 cl:31.456080370468076

filename: 3_5_hidden Epoch 217 loss:3.149609935300287 ael:0.0010229601526393906 cl:31.485869263206066

filename: 3_5_hidden Epoch 218 loss:3.1466254516958028 ael:0.0010094207493462333 cl:31.456159864609212

filename: 3_5_hidden Epoch 219 loss:3.146017911410897 ael:0.0010247953904882292 cl:31.449930672000477

filename: 3_5_hidden Epoch 220 loss:3.14829987349038 ael:0.0009977661273240877 cl:31.473020607324493

filename: 3_5_hidden Epoch 221 loss:3.145770983981953 ael:0.0010093945295470694 cl:31.447615425290756

filename: 3_5_hidden Epoch 222 loss:3.1466227986323783 ael:0.0009959196385594977 cl:31.45626829831005

filename: 3_5_hidden Epoch 223 loss:3.1482893379828587 ael:0.001003882261720516 cl:31.472854112547978

filename: 3_5_hidden Epoch 224 loss:3.151087716899324 ael:0.0010012328258268742 cl:31.50086433963962

filename: 3_5_hidden Epoch 225 loss:3.1458950778929258 ael:0.0009840050903736708 cl:31.44911027001204

filename: 3_5_hidden Epoch 226 loss:3.1459402765356512 ael:0.0009905497141418176 cl:31.449496844090845

filename: 3_5_hidden Epoch 227 loss:3.1508160759381836 ael:0.0009996796808204895 cl:31.498163480771968

filename: 3_5_hidden Epoch 228 loss:3.150165924700068 ael:0.000980487250157267 cl:31.491853885836846

filename: 3_5_hidden Epoch 229 loss:3.147697580542358 ael:0.0009998321578989905 cl:31.466976987234883

filename: 3_5_hidden Epoch 230 loss:3.1465730740269193 ael:0.0009773511254953446 cl:31.45595671362458

filename: 3_5_hidden Epoch 231 loss:3.151604298401411 ael:0.0009889395781688788 cl:31.506153106689453

filename: 3_5_hidden Epoch 232 loss:3.1465527156739386 ael:0.0009890539653799296 cl:31.45563614817344

filename: 3_5_hidden Epoch 233 loss:3.1462328027648074 ael:0.0009579588083119744 cl:31.4527479706449

filename: 3_5_hidden Epoch 234 loss:3.1505997488854485 ael:0.0009580351374140646 cl:31.49641663885183

filename: 3_5_hidden Epoch 235 loss:3.1531561553561374 ael:0.0009555767216743068 cl:31.522005315272544

filename: 3_5_hidden Epoch 236 loss:3.1458299997960175 ael:0.0009421548373673132 cl:31.448877940583596

filename: 3_5_hidden Epoch 237 loss:3.1459224770092398 ael:0.0009543920486481572 cl:31.449680352310754

filename: 3_5_hidden Epoch 238 loss:3.1508159519738235 ael:0.0009680467748506621 cl:31.498478576894254

filename: 3_5_hidden Epoch 239 loss:3.148537795280978 ael:0.0009359067104022296 cl:31.47601839169299

filename: 3_5_hidden Epoch 240 loss:3.1447573182971906 ael:0.0009220223028178364 cl:31.438352481623905

filename: 3_5_hidden Epoch 241 loss:3.147826650651429 ael:0.000932026195745445 cl:31.46894575674996

filename: 3_5_hidden Epoch 242 loss:3.1483427358305436 ael:0.0009515523243366872 cl:31.473911336475837

filename: 3_5_hidden Epoch 243 loss:3.146263154813269 ael:0.0009223414051951776 cl:31.453407672791634

filename: 3_5_hidden Epoch 244 loss:3.1463714658798367 ael:0.0009227046375685713 cl:31.454487165613322

filename: 3_5_hidden Epoch 245 loss:3.144840139059176 ael:0.0009068462814609007 cl:31.4393324470254

filename: 3_5_hidden Epoch 246 loss:3.1474332262781375 ael:0.0009037413406075398 cl:31.465294374814427

filename: 3_5_hidden Epoch 247 loss:3.1480475056620323 ael:0.0009590144780941173 cl:31.47088442207879

filename: 3_5_hidden Epoch 248 loss:3.143767957674077 ael:0.000890834709922322 cl:31.428770750037796

filename: 3_5_hidden Epoch 249 loss:3.14790148981113 ael:0.000893367370808136 cl:31.470080742510127

filename: 3_5_hidden Epoch 250 loss:3.143892898985199 ael:0.0008971563886560115 cl:31.42995696127664

/tmp/ipykernel_336185/680421385.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
/tmp/ipykernel_336185/680421385.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3  Label
0        0.062136  0.013906 -0.010055 -0.012184      1
1        0.057364  0.077176  0.045793  0.056897      0
2        0.035088 -0.038477  0.102809  0.062032      2
3        0.062934  0.015536  0.000918 -0.001173      1
4       -0.107031  0.056915  0.014631  0.030554      4
...           ...       ...       ...       ...    ...
1835449  0.057349  0.077514  0.046153  0.057287      0
1835450  0.035081 -0.038468  0.102798  0.062028      2
1835451  0.035076 -0.038460  0.102789  0.062023      2
1835452  0.057371  0.076990  0.045597  0.056686      0
1835453  0.034598 -0.037778  0.102001  0.061678      2

[1835454 rows x 5 columns]

Davies-Bouldin Score: 0.09220055636201248

               0         1         2         3  Label
0       0.058176  0.077724  0.043895  0.057230      0
1       0.035114 -0.038508  0.102847  0.062050      2
2       0.060781  0.015032 -0.006221 -0.005822      1
3       0.036286 -0.032969  0.098719  0.061702      3
4       0.062609  0.014172 -0.012732 -0.009765      1
...          ...       ...       ...       ...    ...
519951  0.061141  0.013020 -0.008636 -0.008887      1
519952 -0.109402  0.060619  0.008510  0.028700      4
519953  0.057353  0.077428  0.046061  0.057187      0
519954  0.062235  0.012586 -0.009083 -0.011626      1
519955  0.044121 -0.022276  0.042861  0.021075      3

[519956 rows x 5 columns]

               0         1         2         3  Label
0       0.057362  0.077211  0.045830  0.056938      0
1       0.058105  0.078013  0.043877  0.057318      0
2       0.061069  0.018455 -0.008220 -0.006209      1
3       0.055156  0.027808  0.011712  0.013005      1
4       0.057220  0.071950  0.045423  0.055751      0
...          ...       ...       ...       ...    ...
649942  0.063782  0.015732 -0.013062 -0.009541      1
649943  0.057416  0.073694  0.044799  0.055816      0
649944  0.057173  0.073533  0.044962  0.055901      0
649945  0.035334 -0.035133  0.077700  0.043984      3
649946  0.034474 -0.037628  0.101895  0.062697      2

[649947 rows x 5 columns]

4_5_hidden

cuda

[0.0, 1.0, 2.0, 3.0]

pick completo
82 4

filename: 4_5_hidden Epoch 1 loss:3.6029312270120206 ael:0.023163470806207984 cl:35.797677027741464

filename: 4_5_hidden Epoch 2 loss:3.3618178670787398 ael:0.01642362522434033 cl:33.45394195130268

filename: 4_5_hidden Epoch 3 loss:3.3399794393301523 ael:0.01639032011904973 cl:33.235890719082136

filename: 4_5_hidden Epoch 4 loss:3.3273580823552273 ael:0.01622556850714428 cl:33.11132465685933

filename: 4_5_hidden Epoch 5 loss:3.3188545486968226 ael:0.015675820628498916 cl:33.03178679865843

filename: 4_5_hidden Epoch 6 loss:3.31139155179584 ael:0.015299959515058486 cl:32.96091546147225

filename: 4_5_hidden Epoch 7 loss:3.3033784861569786 ael:0.014919233243142056 cl:32.88459207635719

filename: 4_5_hidden Epoch 8 loss:3.2946868534350755 ael:0.014438619789391852 cl:32.80248186964196

filename: 4_5_hidden Epoch 9 loss:3.2858046075695277 ael:0.01435027557644454 cl:32.71454281992325

filename: 4_5_hidden Epoch 10 loss:3.2778926700289253 ael:0.014334948773427463 cl:32.635576732215306

filename: 4_5_hidden Epoch 11 loss:3.272532226779291 ael:0.014307448691507444 cl:32.582247323660305

filename: 4_5_hidden Epoch 12 loss:3.2681659286918188 ael:0.01426041061028468 cl:32.53905468007658

filename: 4_5_hidden Epoch 13 loss:3.265172131440037 ael:0.014176828043231615 cl:32.50995254568096

filename: 4_5_hidden Epoch 14 loss:3.2634502644157823 ael:0.014038315690806453 cl:32.49411901541971

filename: 4_5_hidden Epoch 15 loss:3.2608595522639563 ael:0.013861390530960494 cl:32.469981148227504

filename: 4_5_hidden Epoch 16 loss:3.258852334825833 ael:0.013645385085508534 cl:32.45206903896373

filename: 4_5_hidden Epoch 17 loss:3.2571973907509837 ael:0.013450317092332386 cl:32.43747026873974

filename: 4_5_hidden Epoch 18 loss:3.255635664285388 ael:0.01330510079614279 cl:32.423305144320295

filename: 4_5_hidden Epoch 19 loss:3.2546685657928625 ael:0.013241107029977132 cl:32.414274112709656

filename: 4_5_hidden Epoch 20 loss:3.2535361160984824 ael:0.013224016099094089 cl:32.403120507946795

filename: 4_5_hidden Epoch 21 loss:3.2525060076435492 ael:0.013214491787477202 cl:32.39291468243362

filename: 4_5_hidden Epoch 22 loss:3.251798125052298 ael:0.013213647078404899 cl:32.38584431252778

filename: 4_5_hidden Epoch 23 loss:3.250920632359276 ael:0.01320422983318004 cl:32.377163520384556

filename: 4_5_hidden Epoch 24 loss:3.2505203414684236 ael:0.013202102528482708 cl:32.37318194813656

filename: 4_5_hidden Epoch 25 loss:3.249349471688528 ael:0.013192545396545359 cl:32.361568817567104

filename: 4_5_hidden Epoch 26 loss:3.2487247716273395 ael:0.013201227329910751 cl:32.35523496796709

filename: 4_5_hidden Epoch 27 loss:3.2479480709035764 ael:0.013205159952377268 cl:32.347428621535165

filename: 4_5_hidden Epoch 28 loss:3.2471216084117764 ael:0.013208013568244489 cl:32.33913547740384

filename: 4_5_hidden Epoch 29 loss:3.246851168428075 ael:0.013206016553161549 cl:32.336451095329764

filename: 4_5_hidden Epoch 30 loss:3.245976043507038 ael:0.013195155961609991 cl:32.327808400209726

filename: 4_5_hidden Epoch 31 loss:3.24562013194319 ael:0.013202889032659903 cl:32.32417196691937

filename: 4_5_hidden Epoch 32 loss:3.2450416223920446 ael:0.01320127423497653 cl:32.318402994786176

filename: 4_5_hidden Epoch 33 loss:3.2449233018940005 ael:0.01320528356860277 cl:32.31717970716258

filename: 4_5_hidden Epoch 34 loss:3.2436794033575778 ael:0.013201262425735882 cl:32.304780953903695

filename: 4_5_hidden Epoch 35 loss:3.243242315223871 ael:0.013197732361920629 cl:32.30044533367033

filename: 4_5_hidden Epoch 36 loss:3.2420921657821786 ael:0.013195795619047648 cl:32.28896320715836

filename: 4_5_hidden Epoch 37 loss:3.242267629562135 ael:0.013199744762432386 cl:32.29067837445319

filename: 4_5_hidden Epoch 38 loss:3.2419955785794596 ael:0.01320559804686838 cl:32.28789935668138

filename: 4_5_hidden Epoch 39 loss:3.2414860676483253 ael:0.013190417972918334 cl:32.28295600028069

filename: 4_5_hidden Epoch 40 loss:3.241050301630605 ael:0.013193788417246893 cl:32.278564650348144

filename: 4_5_hidden Epoch 41 loss:3.240531952347663 ael:0.01319412446050798 cl:32.273377770224094

filename: 4_5_hidden Epoch 42 loss:3.2401131582054155 ael:0.01320009653106509 cl:32.26913012541654

filename: 4_5_hidden Epoch 43 loss:3.240116875578466 ael:0.013194826636242139 cl:32.26922001437028

filename: 4_5_hidden Epoch 44 loss:3.239464115053737 ael:0.01319536251256335 cl:32.26268702912794

filename: 4_5_hidden Epoch 45 loss:3.238969865100173 ael:0.013197921527012555 cl:32.25771893898818

filename: 4_5_hidden Epoch 46 loss:3.238794724640012 ael:0.01318136597887993 cl:32.256133114029986

filename: 4_5_hidden Epoch 47 loss:3.2384636910636275 ael:0.013189212457562513 cl:32.25274429053519

filename: 4_5_hidden Epoch 48 loss:3.238163007322707 ael:0.013187674073337478 cl:32.24975287940023

filename: 4_5_hidden Epoch 49 loss:3.2378748940468864 ael:0.01319782099798201 cl:32.24677027378947

filename: 4_5_hidden Epoch 50 loss:3.2374729409846066 ael:0.013200220734144502 cl:32.242726710136196

filename: 4_5_hidden Epoch 51 loss:3.236776440498896 ael:0.0131822906909249 cl:32.235941051149474

filename: 4_5_hidden Epoch 52 loss:3.2373341285899184 ael:0.013190096370688766 cl:32.24143982551525

filename: 4_5_hidden Epoch 53 loss:3.236734794682097 ael:0.013174662286552478 cl:32.23560082320261

filename: 4_5_hidden Epoch 54 loss:3.2364483835501496 ael:0.013180515981082186 cl:32.2326782032944

filename: 4_5_hidden Epoch 55 loss:3.236232531315307 ael:0.013164979999092434 cl:32.23067502172153

filename: 4_5_hidden Epoch 56 loss:3.2362310529141394 ael:0.01318640934155558 cl:32.230445955021075

filename: 4_5_hidden Epoch 57 loss:3.23570394129784 ael:0.013155837102036834 cl:32.22548059459381

filename: 4_5_hidden Epoch 58 loss:3.235184891628138 ael:0.013154373148186675 cl:32.22030469099337

filename: 4_5_hidden Epoch 59 loss:3.2352181208957607 ael:0.013152144916685496 cl:32.220659302841256

filename: 4_5_hidden Epoch 60 loss:3.234288884226241 ael:0.013143109539865675 cl:32.211457290608216

filename: 4_5_hidden Epoch 61 loss:3.234545825173994 ael:0.013142565935628878 cl:32.21403211084864

filename: 4_5_hidden Epoch 62 loss:3.2344482118187403 ael:0.013120645387641298 cl:32.213275169965776

filename: 4_5_hidden Epoch 63 loss:3.2341911020984404 ael:0.013097287965314884 cl:32.21093766220702

filename: 4_5_hidden Epoch 64 loss:3.2341620925950694 ael:0.013052057434621692 cl:32.21109989034434

filename: 4_5_hidden Epoch 65 loss:3.2334341227235854 ael:0.013001159590077596 cl:32.204329171397

filename: 4_5_hidden Epoch 66 loss:3.2337363758818376 ael:0.012933307110339999 cl:32.208030213032636

filename: 4_5_hidden Epoch 67 loss:3.2334045661577138 ael:0.012808199685779008 cl:32.205963203253035

filename: 4_5_hidden Epoch 68 loss:3.232846366985828 ael:0.01253914792160051 cl:32.203071703921125

filename: 4_5_hidden Epoch 69 loss:3.232611521273916 ael:0.011977088772923108 cl:32.20634384031687

filename: 4_5_hidden Epoch 70 loss:3.231098837265443 ael:0.01082458292143158 cl:32.202742060111355

filename: 4_5_hidden Epoch 71 loss:3.229402708955769 ael:0.009049871788218368 cl:32.203527889807845

filename: 4_5_hidden Epoch 72 loss:3.2283571409483964 ael:0.007994640459151653 cl:32.20362452605888

filename: 4_5_hidden Epoch 73 loss:3.227615989438916 ael:0.0075183529428158105 cl:32.20097587536015

filename: 4_5_hidden Epoch 74 loss:3.226944310425682 ael:0.007207462347120642 cl:32.19736802809697

filename: 4_5_hidden Epoch 75 loss:3.226641605018797 ael:0.007020921394209826 cl:32.196206381202515

filename: 4_5_hidden Epoch 76 loss:3.226358375204305 ael:0.006930415105470909 cl:32.1942791042781

filename: 4_5_hidden Epoch 77 loss:3.2260209547263243 ael:0.006830971302830696 cl:32.19189935935496

filename: 4_5_hidden Epoch 78 loss:3.225631043218382 ael:0.006771727289212968 cl:32.18859268213194

filename: 4_5_hidden Epoch 79 loss:3.225771529113242 ael:0.006705350009975935 cl:32.19066130831741

filename: 4_5_hidden Epoch 80 loss:3.2257659937985257 ael:0.006669144859973977 cl:32.19096798670215

filename: 4_5_hidden Epoch 81 loss:3.22541976174577 ael:0.006607542528150318 cl:32.18812170193468

filename: 4_5_hidden Epoch 82 loss:3.2255155971318032 ael:0.00656146663578014 cl:32.18954084037962

filename: 4_5_hidden Epoch 83 loss:3.224920027778679 ael:0.00650534006180121 cl:32.184146398087044

filename: 4_5_hidden Epoch 84 loss:3.224534343179822 ael:0.006441964676978819 cl:32.18092331773004

filename: 4_5_hidden Epoch 85 loss:3.22476874301552 ael:0.006386345436697982 cl:32.183823488186036

filename: 4_5_hidden Epoch 86 loss:3.2246329752209375 ael:0.006319976297607464 cl:32.18312951504026

filename: 4_5_hidden Epoch 87 loss:3.2243899157829987 ael:0.0062926743133295306 cl:32.180971937097176

filename: 4_5_hidden Epoch 88 loss:3.2240092946180257 ael:0.006217972931882556 cl:32.17791273835926

filename: 4_5_hidden Epoch 89 loss:3.2242274209696067 ael:0.006171162963842824 cl:32.180562114612584

filename: 4_5_hidden Epoch 90 loss:3.224168819176198 ael:0.0061567516260243324 cl:32.18012019624978

filename: 4_5_hidden Epoch 91 loss:3.224014683624581 ael:0.006063706915776324 cl:32.179509286489136

filename: 4_5_hidden Epoch 92 loss:3.223520295022631 ael:0.006023314839066056 cl:32.174969336899004

filename: 4_5_hidden Epoch 93 loss:3.2237871743690376 ael:0.005940940595668445 cl:32.17846187865502

filename: 4_5_hidden Epoch 94 loss:3.2237883676849224 ael:0.00591070312035087 cl:32.17877618591935

filename: 4_5_hidden Epoch 95 loss:3.223235557712695 ael:0.005837088363415101 cl:32.173984207808324

filename: 4_5_hidden Epoch 96 loss:3.223409725188179 ael:0.005744613122851759 cl:32.17665063279237

filename: 4_5_hidden Epoch 97 loss:3.2233804722455357 ael:0.005671364678543656 cl:32.177090590252476

filename: 4_5_hidden Epoch 98 loss:3.2228399309174804 ael:0.005582327988540822 cl:32.17257556699007

filename: 4_5_hidden Epoch 99 loss:3.222988744598228 ael:0.005458680007050566 cl:32.17530016559247

filename: 4_5_hidden Epoch 100 loss:3.2227007818788485 ael:0.005327547587842538 cl:32.173731882680315

filename: 4_5_hidden Epoch 101 loss:3.222601558554507 ael:0.005167081587699988 cl:32.17434430379847

filename: 4_5_hidden Epoch 102 loss:3.222229513249181 ael:0.004991798013696129 cl:32.172376681095066

filename: 4_5_hidden Epoch 103 loss:3.2218658826263624 ael:0.0048184515342627274 cl:32.17047381401062

filename: 4_5_hidden Epoch 104 loss:3.221918770484224 ael:0.0046091888880746374 cl:32.17309533339597

filename: 4_5_hidden Epoch 105 loss:3.2212798746049276 ael:0.004338872837283413 cl:32.169409536645944

filename: 4_5_hidden Epoch 106 loss:3.2212041425910933 ael:0.004108150009006527 cl:32.17095947162636

filename: 4_5_hidden Epoch 107 loss:3.2210306881184714 ael:0.003940376739299777 cl:32.170902660547014

filename: 4_5_hidden Epoch 108 loss:3.221010464507097 ael:0.003780097199290122 cl:32.172303208522095

filename: 4_5_hidden Epoch 109 loss:3.220572311342664 ael:0.0036708751009962245 cl:32.16901388333117

filename: 4_5_hidden Epoch 110 loss:3.2202108187629133 ael:0.003606457044543964 cl:32.16604313994587

filename: 4_5_hidden Epoch 111 loss:3.2202099328035927 ael:0.003541563962096928 cl:32.16668321041

filename: 4_5_hidden Epoch 112 loss:3.220251107705077 ael:0.003504150649987777 cl:32.16746908233181

filename: 4_5_hidden Epoch 113 loss:3.2200659664737996 ael:0.003467884844585903 cl:32.16598031587786

filename: 4_5_hidden Epoch 114 loss:3.2198531344436416 ael:0.0034036238784157543 cl:32.16449464629072

filename: 4_5_hidden Epoch 115 loss:3.2195552857854195 ael:0.0033854702486330744 cl:32.1616976801829

filename: 4_5_hidden Epoch 116 loss:3.219402725766081 ael:0.003378767656782425 cl:32.16023909762405

filename: 4_5_hidden Epoch 117 loss:3.2197373092303265 ael:0.0033576421055074813 cl:32.16379614937125

filename: 4_5_hidden Epoch 118 loss:3.2190935586621388 ael:0.0033150976467812253 cl:32.15778414683002

filename: 4_5_hidden Epoch 119 loss:3.219208646026595 ael:0.00329639785652769 cl:32.15912202264526

filename: 4_5_hidden Epoch 120 loss:3.2190477820374794 ael:0.0032679469094709264 cl:32.157797865939706

filename: 4_5_hidden Epoch 121 loss:3.2189914222412437 ael:0.003250809264677068 cl:32.15740566377249

filename: 4_5_hidden Epoch 122 loss:3.2189561369995836 ael:0.00322163330430525 cl:32.15734456115871

filename: 4_5_hidden Epoch 123 loss:3.218798495330254 ael:0.0031919402688124154 cl:32.15606509995512

filename: 4_5_hidden Epoch 124 loss:3.218830506757835 ael:0.003188028706455921 cl:32.15642430097444

filename: 4_5_hidden Epoch 125 loss:3.2193498428645455 ael:0.0031644545065427146 cl:32.16185340922543

filename: 4_5_hidden Epoch 126 loss:3.218895519848261 ael:0.0031368287117270748 cl:32.15758642110145

filename: 4_5_hidden Epoch 127 loss:3.218771684440114 ael:0.0031221261920335 cl:32.15649512262118

filename: 4_5_hidden Epoch 128 loss:3.2185744958613913 ael:0.003088969350204105 cl:32.1548548105211

filename: 4_5_hidden Epoch 129 loss:3.2183383958772245 ael:0.003075495635216641 cl:32.152628526831805

filename: 4_5_hidden Epoch 130 loss:3.2184364164879717 ael:0.003040626726679496 cl:32.153957418952594

filename: 4_5_hidden Epoch 131 loss:3.218892317225042 ael:0.003040581924192603 cl:32.15851690805241

filename: 4_5_hidden Epoch 132 loss:3.2184641171995043 ael:0.002996904425437162 cl:32.1546716684914

filename: 4_5_hidden Epoch 133 loss:3.2183471504220695 ael:0.0029872635560593977 cl:32.15359836005753

filename: 4_5_hidden Epoch 134 loss:3.218214594519679 ael:0.002978878607671732 cl:32.15235666013434

filename: 4_5_hidden Epoch 135 loss:3.217841180367295 ael:0.002933104228344997 cl:32.149080265160514

filename: 4_5_hidden Epoch 136 loss:3.2175933134221104 ael:0.0029244985048368483 cl:32.14668768579965

filename: 4_5_hidden Epoch 137 loss:3.2179820874854763 ael:0.002905856998303913 cl:32.15076183654835

filename: 4_5_hidden Epoch 138 loss:3.21804793652139 ael:0.0028789359543142643 cl:32.15168956134541

filename: 4_5_hidden Epoch 139 loss:3.217685816354937 ael:0.0028502373511351837 cl:32.1483552934799

filename: 4_5_hidden Epoch 140 loss:3.2178989365600357 ael:0.0028509154343664784 cl:32.150479735874974

filename: 4_5_hidden Epoch 141 loss:3.2180426449677855 ael:0.00280802918427833 cl:32.152345689275094

filename: 4_5_hidden Epoch 142 loss:3.2176671117608544 ael:0.0027819495190153217 cl:32.14885113718185

filename: 4_5_hidden Epoch 143 loss:3.217367904618801 ael:0.0027813756498749533 cl:32.145864834280815

filename: 4_5_hidden Epoch 144 loss:3.2172672744059923 ael:0.0027524851421666177 cl:32.14514742041767

filename: 4_5_hidden Epoch 145 loss:3.2175923444282417 ael:0.002757237597630655 cl:32.14835060389459

filename: 4_5_hidden Epoch 146 loss:3.2174116328004625 ael:0.002726021549669718 cl:32.14685564164724

filename: 4_5_hidden Epoch 147 loss:3.2172940033558377 ael:0.0027012986407090244 cl:32.145926594991664

filename: 4_5_hidden Epoch 148 loss:3.217195698046015 ael:0.002682185669251834 cl:32.145134640563896

filename: 4_5_hidden Epoch 149 loss:3.217221205808689 ael:0.0026873416934523444 cl:32.14533816712464

filename: 4_5_hidden Epoch 150 loss:3.216900903578711 ael:0.0026554415351585496 cl:32.142454132405526

filename: 4_5_hidden Epoch 151 loss:3.217145941877983 ael:0.0026482842214150077 cl:32.14497610096283

filename: 4_5_hidden Epoch 152 loss:3.2170127814969542 ael:0.002648744728621377 cl:32.14363988841327

filename: 4_5_hidden Epoch 153 loss:3.2172510126368272 ael:0.002624427736409966 cl:32.14626534968679

filename: 4_5_hidden Epoch 154 loss:3.21667958850737 ael:0.0026100000428987795 cl:32.14069540248319

filename: 4_5_hidden Epoch 155 loss:3.2167085223141294 ael:0.002597895459156055 cl:32.14110577801649

filename: 4_5_hidden Epoch 156 loss:3.2165637849216586 ael:0.0025820858003966387 cl:32.13981651281435

filename: 4_5_hidden Epoch 157 loss:3.2168145841450206 ael:0.0025681084555035185 cl:32.14246429325952

filename: 4_5_hidden Epoch 158 loss:3.216955725562238 ael:0.0025611371102078552 cl:32.14394538242925

filename: 4_5_hidden Epoch 159 loss:3.216830549242687 ael:0.0025378612163222693 cl:32.142926381937116

filename: 4_5_hidden Epoch 160 loss:3.216563943974658 ael:0.0025457163909528117 cl:32.140181807153425

filename: 4_5_hidden Epoch 161 loss:3.2167132147316284 ael:0.0025171996807738873 cl:32.14195966051155

filename: 4_5_hidden Epoch 162 loss:3.2166673596425395 ael:0.002512913371147648 cl:32.1415439929097

filename: 4_5_hidden Epoch 163 loss:3.216883517238543 ael:0.0024803191647572204 cl:32.14403150766508

filename: 4_5_hidden Epoch 164 loss:3.216753255342562 ael:0.0024808010478784607 cl:32.14272406806699

filename: 4_5_hidden Epoch 165 loss:3.2166110566187625 ael:0.002470882285258594 cl:32.14140126154181

filename: 4_5_hidden Epoch 166 loss:3.216638458470289 ael:0.002458194971579171 cl:32.14180212453426

filename: 4_5_hidden Epoch 167 loss:3.21609740998781 ael:0.002428005858624684 cl:32.13669356362608

filename: 4_5_hidden Epoch 168 loss:3.2164521738082237 ael:0.0024223361393390526 cl:32.14029789537385

filename: 4_5_hidden Epoch 169 loss:3.215798647820821 ael:0.0024268364397503164 cl:32.13371763528037

filename: 4_5_hidden Epoch 170 loss:3.216253951159718 ael:0.002390842806739224 cl:32.13863060232372

filename: 4_5_hidden Epoch 171 loss:3.2163905373273605 ael:0.002355298521469868 cl:32.140351900014196

filename: 4_5_hidden Epoch 172 loss:3.2161632648812 ael:0.002349328227943618 cl:32.13813887250089

filename: 4_5_hidden Epoch 173 loss:3.2159634557578785 ael:0.0023410653779192647 cl:32.136223429480076

filename: 4_5_hidden Epoch 174 loss:3.2161268996111003 ael:0.0022882712625528307 cl:32.13838579484762

filename: 4_5_hidden Epoch 175 loss:3.2155019327451035 ael:0.002278295362167831 cl:32.13223590500669

filename: 4_5_hidden Epoch 176 loss:3.2162070130169007 ael:0.0022902836663961272 cl:32.13916680879778

filename: 4_5_hidden Epoch 177 loss:3.216217131838685 ael:0.002257236858480861 cl:32.13959845456397

filename: 4_5_hidden Epoch 178 loss:3.216058519823762 ael:0.0022323987306612112 cl:32.13826074044081

filename: 4_5_hidden Epoch 179 loss:3.215908106794625 ael:0.0021959529098334015 cl:32.13712107285568

filename: 4_5_hidden Epoch 180 loss:3.216111259056219 ael:0.002200499931007139 cl:32.139107122792026

filename: 4_5_hidden Epoch 181 loss:3.215962460051345 ael:0.0022058065362892177 cl:32.13756607315195

filename: 4_5_hidden Epoch 182 loss:3.2162894450176354 ael:0.0021590835689961787 cl:32.141303134016034

filename: 4_5_hidden Epoch 183 loss:3.2156982656174034 ael:0.002144431481934927 cl:32.13553782621676

filename: 4_5_hidden Epoch 184 loss:3.215732441350142 ael:0.0021344040456435644 cl:32.135979864046334

filename: 4_5_hidden Epoch 185 loss:3.2154793726445274 ael:0.002113502761225878 cl:32.13365822682886

filename: 4_5_hidden Epoch 186 loss:3.215730817477595 ael:0.0020729200580719555 cl:32.13657848417888

filename: 4_5_hidden Epoch 187 loss:3.2153241906644974 ael:0.0020379246573731277 cl:32.13286214719324

filename: 4_5_hidden Epoch 188 loss:3.21537233660597 ael:0.0020335925274431003 cl:32.133386957465184

filename: 4_5_hidden Epoch 189 loss:3.215401642008425 ael:0.0020147464674350364 cl:32.13386850274665

filename: 4_5_hidden Epoch 190 loss:3.2154804541534276 ael:0.0020121050043485165 cl:32.134683020429016

filename: 4_5_hidden Epoch 191 loss:3.2150997905056626 ael:0.0019978059050121664 cl:32.1310193816735

filename: 4_5_hidden Epoch 192 loss:3.2154291118324188 ael:0.0019600436835802214 cl:32.134690218301365

filename: 4_5_hidden Epoch 193 loss:3.2150071711957326 ael:0.001990572422929913 cl:32.13016551668649

filename: 4_5_hidden Epoch 194 loss:3.2151987852597084 ael:0.0019565946425345966 cl:32.132421428132524

filename: 4_5_hidden Epoch 195 loss:3.2153295602319565 ael:0.001943474770974937 cl:32.13386033678158

filename: 4_5_hidden Epoch 196 loss:3.2155232627113746 ael:0.00191409561768492 cl:32.13609118492506

filename: 4_5_hidden Epoch 197 loss:3.2154079929927515 ael:0.0019454603255288896 cl:32.13462484063134

filename: 4_5_hidden Epoch 198 loss:3.215180474082028 ael:0.0019166995316128334 cl:32.13263728809151

filename: 4_5_hidden Epoch 199 loss:3.215460105475288 ael:0.0019070499160625724 cl:32.135530066026725

filename: 4_5_hidden Epoch 200 loss:3.2146628385099945 ael:0.0018752036838665038 cl:32.12787585845519

filename: 4_5_hidden Epoch 201 loss:3.214782112167412 ael:0.0018573242430306154 cl:32.1292474522189

filename: 4_5_hidden Epoch 202 loss:3.215027143321851 ael:0.0018706773114518904 cl:32.13156416091754

filename: 4_5_hidden Epoch 203 loss:3.215005142771142 ael:0.001831201912589335 cl:32.13173894696823

filename: 4_5_hidden Epoch 204 loss:3.214473291491329 ael:0.0018359990536534986 cl:32.12637246401727

filename: 4_5_hidden Epoch 205 loss:3.2148806052383025 ael:0.001787659617689776 cl:32.13092899528487

filename: 4_5_hidden Epoch 206 loss:3.2146354961987447 ael:0.0018141896780238327 cl:32.12821254925903

filename: 4_5_hidden Epoch 207 loss:3.2145158974192314 ael:0.00176535128184205 cl:32.127504989858835

filename: 4_5_hidden Epoch 208 loss:3.2144634120536417 ael:0.001763455455937447 cl:32.12699908520182

filename: 4_5_hidden Epoch 209 loss:3.214322313569792 ael:0.0017592502976908524 cl:32.125630162962054

filename: 4_5_hidden Epoch 210 loss:3.2143853731598244 ael:0.0017232541612474666 cl:32.12662070152827

filename: 4_5_hidden Epoch 211 loss:3.2143942565691392 ael:0.0017453072895346204 cl:32.12648903216451

filename: 4_5_hidden Epoch 212 loss:3.2141603612487826 ael:0.00172661442464126 cl:32.124337001186724

filename: 4_5_hidden Epoch 213 loss:3.2140016405809004 ael:0.001723014888741236 cl:32.12278577627425

filename: 4_5_hidden Epoch 214 loss:3.2138384027048525 ael:0.001707184007757803 cl:32.12131170268707

filename: 4_5_hidden Epoch 215 loss:3.2140791560995914 ael:0.001690781449190151 cl:32.12388329320541

filename: 4_5_hidden Epoch 216 loss:3.214109533999445 ael:0.0016689424433309955 cl:32.12440543452813

filename: 4_5_hidden Epoch 217 loss:3.2139329874232314 ael:0.001669654471921804 cl:32.12263288044775

filename: 4_5_hidden Epoch 218 loss:3.2139972296440833 ael:0.001674184053112299 cl:32.12322994648252

filename: 4_5_hidden Epoch 219 loss:3.2140783594828704 ael:0.0016469501124270769 cl:32.12431360784411

filename: 4_5_hidden Epoch 220 loss:3.2143301652265674 ael:0.0016734512162727472 cl:32.12656667062582

filename: 4_5_hidden Epoch 221 loss:3.213904136329181 ael:0.0016434293958601355 cl:32.1226066142385

filename: 4_5_hidden Epoch 222 loss:3.2141242219098958 ael:0.0016321599789991669 cl:32.1249201261714

filename: 4_5_hidden Epoch 223 loss:3.213752555731306 ael:0.0016073024942564525 cl:32.121452070981846

filename: 4_5_hidden Epoch 224 loss:3.2139827085751436 ael:0.0016224389861161331 cl:32.12360221057422

filename: 4_5_hidden Epoch 225 loss:3.2136364836028535 ael:0.0016281969344023903 cl:32.1200824221576

filename: 4_5_hidden Epoch 226 loss:3.2136514604606585 ael:0.0015851394211267198 cl:32.12066271238142

filename: 4_5_hidden Epoch 227 loss:3.213451561415427 ael:0.0015828532904463711 cl:32.11868656634255

filename: 4_5_hidden Epoch 228 loss:3.2134972852584354 ael:0.0015858987303358678 cl:32.11911335722674

filename: 4_5_hidden Epoch 229 loss:3.2135649015785037 ael:0.0016076989848219255 cl:32.11957157250357

filename: 4_5_hidden Epoch 230 loss:3.2133151938410607 ael:0.001575467805217848 cl:32.117396843871084

filename: 4_5_hidden Epoch 231 loss:3.213381844256918 ael:0.0015623544231052138 cl:32.11819442044582

filename: 4_5_hidden Epoch 232 loss:3.213824453029468 ael:0.001589661361225961 cl:32.1223474506683

filename: 4_5_hidden Epoch 233 loss:3.213666465897797 ael:0.001557528090333369 cl:32.12108890747663

filename: 4_5_hidden Epoch 234 loss:3.213562595084728 ael:0.0015493703749107266 cl:32.12013177068393

filename: 4_5_hidden Epoch 235 loss:3.213272693283357 ael:0.0015622561942987378 cl:32.11710390725352

filename: 4_5_hidden Epoch 236 loss:3.213501359229469 ael:0.001531000892153602 cl:32.1197031167362

filename: 4_5_hidden Epoch 237 loss:3.213540425761472 ael:0.001522742930127003 cl:32.12017634517431

filename: 4_5_hidden Epoch 238 loss:3.2131974339871374 ael:0.0015432869364563064 cl:32.1165410087124

filename: 4_5_hidden Epoch 239 loss:3.2133928138288 ael:0.0015057981165962496 cl:32.118869695498674

filename: 4_5_hidden Epoch 240 loss:3.213426341956429 ael:0.001499323861958981 cl:32.119269693901934

filename: 4_5_hidden Epoch 241 loss:3.213044014849879 ael:0.0014962444268625892 cl:32.115477209214774

filename: 4_5_hidden Epoch 242 loss:3.213034811854105 ael:0.0014992473004199766 cl:32.11535518215748

filename: 4_5_hidden Epoch 243 loss:3.213297914866495 ael:0.001470165443669534 cl:32.11827701471794

filename: 4_5_hidden Epoch 244 loss:3.2131293971517945 ael:0.001478407092669151 cl:32.11650941747826

filename: 4_5_hidden Epoch 245 loss:3.212849754558526 ael:0.0014571597671488774 cl:32.11392548686742

filename: 4_5_hidden Epoch 246 loss:3.2128686958976234 ael:0.001437404220547883 cl:32.11431244485579

filename: 4_5_hidden Epoch 247 loss:3.212843937505656 ael:0.0014584324752660992 cl:32.11385456841141

filename: 4_5_hidden Epoch 248 loss:3.212961043575155 ael:0.00146216617973024 cl:32.114988320847054

filename: 4_5_hidden Epoch 249 loss:3.2127722349846595 ael:0.0014301233989796069 cl:32.11342063784342

filename: 4_5_hidden Epoch 250 loss:3.2126511818775607 ael:0.0014419998829597487 cl:32.11209134149242

/tmp/ipykernel_336185/680421385.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
/tmp/ipykernel_336185/680421385.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3  Label
0        0.107071  0.163419  0.181711  0.196098      1
1        0.218040  0.244552  0.187217  0.153868      0
2        0.223544  0.226174  0.294698  0.290629      2
3        0.108844  0.170357  0.179945  0.193039      1
4        0.223545  0.226176  0.294698  0.290629      2
...           ...       ...       ...       ...    ...
1896092  0.217946  0.244494  0.187148  0.153823      0
1896093  0.223544  0.226174  0.294698  0.290629      2
1896094  0.223544  0.226173  0.294698  0.290629      2
1896095  0.218091  0.244584  0.187254  0.153893      0
1896096  0.223530  0.226141  0.294702  0.290642      2

[1896097 rows x 5 columns]

Davies-Bouldin Score: 0.0728871137665506

               0         1         2         3  Label
0       0.218095  0.244053  0.186225  0.156033      0
1       0.223543  0.226174  0.294697  0.290628      2
2       0.107555  0.165033  0.182693  0.203914      1
3       0.292210  0.080872  0.144376  0.216097      3
4       0.107639  0.164739  0.182299  0.200583      1
...          ...       ...       ...       ...    ...
519951  0.102363  0.165837  0.180993  0.200152      1
519952  0.091516  0.161189  0.175495  0.198869      4
519953  0.217970  0.244509  0.187165  0.153834      0
519954  0.115294  0.167738  0.185312  0.198889      1
519955  0.296440  0.075525  0.144218  0.214901      3

[519956 rows x 5 columns]

               0         1         2         3  Label
0       0.218030  0.244546  0.187210  0.153863      0
1       0.218255  0.244139  0.186207  0.155917      0
2       0.124428  0.175457  0.185959  0.200869      1
3       0.118782  0.176710  0.182547  0.195646      1
4       0.215659  0.242332  0.186687  0.159383      0
...          ...       ...       ...       ...    ...
649942  0.110653  0.166453  0.182877  0.200362      1
649943  0.216380  0.243031  0.187258  0.159671      0
649944  0.215920  0.242645  0.186911  0.159478      0
649945  0.299886  0.080099  0.142775  0.214863      3
649946  0.219673  0.226741  0.285305  0.282501      2

[649947 rows x 5 columns]