In [1]:
import torch
from torch import nn, optim
import torch.nn.functional as F
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.decomposition import PCA
from scipy.stats import chi2
from sklearn.mixture import GaussianMixture
from collections import deque, defaultdict

# CAE

In [2]:
train = pd.read_csv('../../../train_CADE_cod.csv')
val = pd.read_csv('../../../val_CADE_cod.csv')
test = pd.read_csv('../../../test_CADE_cod.csv')

In [3]:
classes_out = ['Infilteration','DoS attacks-SlowHTTPTest']
train = train.drop(index=train[train['Label'].isin(classes_out)].index)
val = val.drop(index=val[val['Label'].isin(classes_out)].index)
test = test.drop(index=test[test['Label'].isin(classes_out)].index)

# CAE CADE (margin 1 e lambda 1.0)

In [4]:
def pick_pair(embeddings, labels, pick_embeddings, pick_labels):
    """
    Gera todos os pares entre embeddings e pick_embeddings,
    com labels_pair indicando se os pares são positivos (0) ou negativos (1).
    """
    N, D = embeddings.shape
    M = pick_embeddings.shape[0]

    # Expande para todas as combinações possíveis
    A = embeddings.unsqueeze(0).expand(M, N, D).reshape(M * N, D)
    B = pick_embeddings.unsqueeze(1).expand(M, N, D).reshape(M * N, D)

    labels_exp = labels.unsqueeze(0).expand(M, N)
    pick_labels_exp = pick_labels.unsqueeze(1).expand(M, N)
    labels_pair = (labels_exp != pick_labels_exp).reshape(-1).float()

    return A, B, labels_pair

def ContrastiveLoss(input1, input2, y, margin=1.0):
    # y = 0 quando input1 e input2 são da mesma classe e y = 1 caso contrário
    diff = input1 - input2
    dist_sq = torch.sum(torch.pow(diff,2),1)
    dist = torch.sqrt(dist_sq + 1e-10) # Soma 1e-10 pois se o sqrt der 0 o gradiente da NaN
    mdist = margin - dist
    mdist = F.relu(mdist)
    loss = ((1-y) * dist * dist) + (y * mdist * mdist)
    return torch.mean(loss)

def AEContrastive(input, output, embeddings, labels, pick_encoded, pick_labels, margin=1.0, lambda1=1.0):
    mseloss = nn.MSELoss()
    ae_loss = mseloss(input,output)

    A, B, labels_pair = pick_pair(embeddings, labels, pick_encoded, pick_labels)
    contrastive_loss = ContrastiveLoss(A, B, labels_pair, margin=margin)
    return ae_loss + contrastive_loss * lambda1, ae_loss, contrastive_loss

In [5]:
class contrastive_ae(nn.Module):
    def __init__(self, input_neurons, neurons):
        super().__init__()
        self.encoder0 = nn.Linear(input_neurons,64)
        self.encoder1 = nn.Linear(64,32)
        self.encoder2 = nn.Linear(32,16)
        self.encoder3 = nn.Linear(16,neurons)

        self.decoder0 = nn.Linear(neurons,16)
        self.decoder1 = nn.Linear(16,32)
        self.decoder2 = nn.Linear(32,64)
        self.decoder3 = nn.Linear(64,input_neurons)

        self.activation0 = nn.ReLU()
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X)
        encoded = X
        X = self.activation0(self.decoder0(X))
        X = self.activation0(self.decoder1(X))
        X = self.activation0(self.decoder2(X))
        X = self.decoder3(X)


        return X, encoded

In [6]:
class encoder(nn.Module):
    def __init__(self, model):
        super().__init__()
        self.encoder0 = list(model.children())[0]
        self.encoder1 = list(model.children())[1]
        self.encoder2 = list(model.children())[2]
        self.encoder3 = list(model.children())[3]
        self.activation0 = list(model.children())[8]
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X)
        return X

In [7]:
from torch.utils.data import Dataset, DataLoader,TensorDataset
import random
def build_class_reference_batches(X_train, y_train, batch_size=512):
    classes = torch.unique(y_train).tolist()
    n_classes = len(classes)
    total_samples = len(X_train)
    dataset = TensorDataset(X_train, y_train)
    train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    

    print(classes)

    # Mapeia cada classe para seus índices
    class_to_indices = {
        int(cls.item()): (y_train == cls).nonzero(as_tuple=True)[0].tolist()
        for cls in torch.unique(y_train)
    }

    reference_list = []
    total_batches = len(train_loader)

    for batch_idx in range(total_batches):
        start = batch_idx * batch_size
        end = min(start + batch_size, total_samples)
        batch_indices = set(range(start, end))

        class_samples = []
        for cls in classes:
            candidates = [i for i in class_to_indices[cls] if i not in batch_indices]
            if not candidates:
                raise ValueError(f"Classe {cls} não possui amostras fora do batch {batch_idx}")
            chosen = candidates[torch.randint(len(candidates), (1,)).item()]
            class_samples.append(chosen)

        reference_list.append(class_samples)


    return train_loader, reference_list

In [8]:
def normalize(t):
    t_norm = (t - t.mean()) / t.std()
    return t_norm

In [9]:
train['Label'] = train['Label'].replace('FTP-BruteForce','BruteForce')
train['Label'] = train['Label'].replace('SSH-Bruteforce','BruteForce')
# train['Label'] = train['Label'].replace('DoS attacks-GoldenEye','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Slowloris','DoS')
## train['Label'] = train['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Hulk','DoS')
train['Label'] = train['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
train['Label'] = train['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
train['Label'] = train['Label'].replace('DDOS attack-HOIC','DDoS')
train['Label'] = train['Label'].replace('Brute Force -Web','Web')
train['Label'] = train['Label'].replace('Brute Force -XSS','Web')
train['Label'] = train['Label'].replace('SQL Injection','Web')


val['Label'] = val['Label'].replace('FTP-BruteForce','BruteForce')
val['Label'] = val['Label'].replace('SSH-Bruteforce','BruteForce')
# val['Label'] = val['Label'].replace('DoS attacks-GoldenEye','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Slowloris','DoS')
## val['Label'] = val['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Hulk','DoS')
val['Label'] = val['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
val['Label'] = val['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
val['Label'] = val['Label'].replace('DDOS attack-HOIC','DDoS')
val['Label'] = val['Label'].replace('Brute Force -Web','Web')
val['Label'] = val['Label'].replace('Brute Force -XSS','Web')
val['Label'] = val['Label'].replace('SQL Injection','Web')


test['Label'] = test['Label'].replace('FTP-BruteForce','BruteForce')
test['Label'] = test['Label'].replace('SSH-Bruteforce','BruteForce')
# test['Label'] = test['Label'].replace('DoS attacks-GoldenEye','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Slowloris','DoS')
## test['Label'] = test['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Hulk','DoS')
test['Label'] = test['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
test['Label'] = test['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
test['Label'] = test['Label'].replace('DDOS attack-HOIC','DDoS')
test['Label'] = test['Label'].replace('Brute Force -Web','Web')
test['Label'] = test['Label'].replace('Brute Force -XSS','Web')
test['Label'] = test['Label'].replace('SQL Injection','Web')

In [10]:
labels_str = [i for i in train['Label'].value_counts().index]
print(labels_str)

for i, l in enumerate(labels_str):
    train['Label'] = train['Label'].replace(l, i)
    val['Label'] = val['Label'].replace(l, i)
    test['Label'] = test['Label'].replace(l, i)

['DDoS', 'Benign', 'DoS', 'BruteForce', 'Bot', 'DoS attacks-GoldenEye', 'Web']

/tmp/ipykernel_887182/2307520911.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train['Label'] = train['Label'].replace(l, i)
/tmp/ipykernel_887182/2307520911.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  val['Label'] = val['Label'].replace(l, i)
/tmp/ipykernel_887182/2307520911.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['Label'] = test['Label'].replace(l, i)

In [11]:
array_hidden_classes = [[5]]
filenames = ['5']
# array_hidden_classes = [[0]]
# filenames = ['0']
total_classes = len(labels_str)
for i in range(len(array_hidden_classes)):
    filename = f'{filenames[i]}_hidden'
    print(filename)
    hidden_classes = array_hidden_classes[i] #Classes ocultas do treinamento

    hidden_classes_index = list(train[train['Label'].isin(hidden_classes)].index)

    train_hidden = train.loc[hidden_classes_index]

    train_not_hidden = train.drop(hidden_classes_index)

    X_train = train_not_hidden.drop(columns=['Label'])
    y_train = train_not_hidden['Label']
    X_val = val.drop(columns=['Label'])
    y_val = val['Label'].values
    X_test = test.drop(columns=['Label'])
    y_test = test['Label'].values

    torch.manual_seed(123)
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(device)
    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_loader, pick_list = build_class_reference_batches(X_train,y_train, batch_size=512)
    pick_samples = []
    pick_labels = []
    for l in pick_list:
        pick_samples.append(X_train[l])
        pick_labels.append(y_train[l])

    pick_samples = torch.stack(pick_samples)    
    pick_labels = torch.stack(pick_labels)

    print('pick completo')

    neurons = total_classes - len(hidden_classes)
    print(f'{X_train.shape[1]} {neurons}')
    model = contrastive_ae(input_neurons=X_train.shape[1],neurons=neurons)
    model.to(device)

    learning_rate = 0.0001
    opt = optim.Adam(model.parameters(),lr=learning_rate)
    margin = 10 # Parametro de afastamento das classes
    cae_lambda_1 = 0.1 # Parametro de influencia na distancia das classes
    
    
    for epoch in range(250):
        running_loss = 0
        running_ael = 0
        running_cl = 0
        contador = 0
        for data in train_loader:
            inputs, labels = data
            inputs = inputs.to(device)
            labels = labels.to(device)
            ps = pick_samples[contador]
            pl = pick_labels[contador]
            ps = ps.to(device)
            pl = pl.to(device)
            contador += 1
            #print(f'{contador}/{len(train_loader)}')
            opt.zero_grad()
            outputs, encoded = model(inputs)
            _, pick_encoded = model(ps)
            tam_pe = pick_encoded.shape[0]
            enc_total = torch.cat((encoded,pick_encoded), dim=0)
            enc_total_norm = normalize(enc_total)
            encoded_norm = enc_total_norm[:-tam_pe]
            pick_encoded_norm = enc_total_norm[-tam_pe:]
            loss, ael, cl = AEContrastive(input=inputs, output=outputs, embeddings = encoded_norm, labels=labels, pick_encoded = pick_encoded_norm, pick_labels = pl, margin=margin, lambda1=cae_lambda_1)
            #loss = dummyMSELoss(inputs,outputs)
            loss.backward()
            opt.step()
            running_loss += loss.item()
            running_ael += ael.item()
            running_cl += cl.item()
            #print(f'loss = {loss.item()} batch_size = {size}')
        print(f'filename: {filename} Epoch {epoch+1} loss:{running_loss/len(train_loader)} ael:{running_ael/len(train_loader)} cl:{running_cl/len(train_loader)}')

    model_e = encoder(model=model)
    model_e.to(device)

    model_e.eval()

    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_encoded = model_e(X_train.to(device))

    train_encoded = train_encoded.detach().cpu().numpy()

    train_encoded_df = pd.DataFrame(train_encoded)
    train_encoded_df['Label'] = y_train.detach().cpu().numpy().astype(int)
    display(train_encoded_df)

    score = davies_bouldin_score(train_encoded_df.drop(columns=['Label']), train_encoded_df['Label'])
    print("Davies-Bouldin Score:", score)

    X_val = torch.tensor(np.array(X_val), dtype=torch.float)

    val_encoded = model_e(X_val.to(device))

    val_encoded = val_encoded.detach().cpu().numpy()

    val_encoded_df = pd.DataFrame(val_encoded)

    val_encoded_df['Label'] = y_val

    display(val_encoded_df)

    X_test = torch.tensor(np.array(X_test), dtype=torch.float)

    test_encoded = model_e(X_test.to(device))

    test_encoded = test_encoded.detach().cpu().numpy()

    test_encoded_df = pd.DataFrame(test_encoded)

    test_encoded_df['Label'] = y_test

    display(test_encoded_df)

    train_encoded_df.to_csv(f'train_encoded_CADE_cod_pick_class_squared_normalized_{filename}.csv',index=False)
    val_encoded_df.to_csv(f'val_encoded_CADE_cod_pick_class_squared_normalized_{filename}.csv',index=False)
    test_encoded_df.to_csv(f'test_encoded_CADE_cod_pick_class_squared_normalized_{filename}.csv',index=False)

5_hidden

cuda

[0.0, 1.0, 2.0, 3.0, 4.0, 6.0]

pick completo
82 6

filename: 5_hidden Epoch 1 loss:3.704752619621374 ael:0.02503904212907986 cl:36.79713515122613

filename: 5_hidden Epoch 2 loss:3.0533280970597914 ael:0.015172590050921569 cl:30.381554580037953

filename: 5_hidden Epoch 3 loss:3.0099728837390103 ael:0.014251539190407779 cl:29.95721297310463

filename: 5_hidden Epoch 4 loss:2.9515898894027295 ael:0.014350337395920506 cl:29.37239504775868

filename: 5_hidden Epoch 5 loss:2.8817777176564308 ael:0.014157835258311671 cl:28.67619835875689

filename: 5_hidden Epoch 6 loss:2.8224355433831874 ael:0.013858405915438401 cl:28.08577091537548

filename: 5_hidden Epoch 7 loss:2.7951448558720826 ael:0.013186508291606459 cl:27.819582990267364

filename: 5_hidden Epoch 8 loss:2.778991839024409 ael:0.012580581321918556 cl:27.664112081553863

filename: 5_hidden Epoch 9 loss:2.766033304685727 ael:0.012240307726480515 cl:27.537929486883634

filename: 5_hidden Epoch 10 loss:2.7553875382123105 ael:0.012040497169290523 cl:27.433469913095585

filename: 5_hidden Epoch 11 loss:2.745961857210576 ael:0.011902675007538914 cl:27.340591344593232

filename: 5_hidden Epoch 12 loss:2.7382698037683206 ael:0.011754671873060864 cl:27.265150836743906

filename: 5_hidden Epoch 13 loss:2.7318626408326123 ael:0.011679646432747109 cl:27.201829458525342

filename: 5_hidden Epoch 14 loss:2.726091294358776 ael:0.011570441566558141 cl:27.145208081055447

filename: 5_hidden Epoch 15 loss:2.719966559480236 ael:0.011446897155015257 cl:27.08519614577977

filename: 5_hidden Epoch 16 loss:2.7128339994878017 ael:0.011317805358752278 cl:27.015161482897284

filename: 5_hidden Epoch 17 loss:2.700756700399718 ael:0.011232940209841407 cl:26.895237090254152

filename: 5_hidden Epoch 18 loss:2.6914331221693444 ael:0.011131369920015127 cl:26.803017045398864

filename: 5_hidden Epoch 19 loss:2.683177622557578 ael:0.010973803667670635 cl:26.722037698407625

filename: 5_hidden Epoch 20 loss:2.6743588360192265 ael:0.010797680502121688 cl:26.63561107166626

filename: 5_hidden Epoch 21 loss:2.66789314087654 ael:0.010573472901045667 cl:26.573196189060557

filename: 5_hidden Epoch 22 loss:2.6626894708227797 ael:0.010312630830932156 cl:26.52376791973775

filename: 5_hidden Epoch 23 loss:2.657200716998743 ael:0.01007654238770881 cl:26.47124127692577

filename: 5_hidden Epoch 24 loss:2.6515719292616198 ael:0.009830979491500181 cl:26.41740900808604

filename: 5_hidden Epoch 25 loss:2.6454753015618526 ael:0.009582371900020188 cl:26.358928834966992

filename: 5_hidden Epoch 26 loss:2.6401879760696536 ael:0.009337262185701436 cl:26.30850666486483

filename: 5_hidden Epoch 27 loss:2.6349705805715495 ael:0.009118139778401558 cl:26.258523911557212

filename: 5_hidden Epoch 28 loss:2.6296430797952572 ael:0.008870245955468368 cl:26.207727851192423

filename: 5_hidden Epoch 29 loss:2.625915782108654 ael:0.008661572126255119 cl:26.172541612403048

filename: 5_hidden Epoch 30 loss:2.6218255253927096 ael:0.008463216347169903 cl:26.13362263289808

filename: 5_hidden Epoch 31 loss:2.616827806015319 ael:0.008279822854897761 cl:26.085479346869505

filename: 5_hidden Epoch 32 loss:2.6131559632657266 ael:0.00806144745792888 cl:26.050944681388724

filename: 5_hidden Epoch 33 loss:2.6071060964574366 ael:0.007929033348562042 cl:25.991770155380504

filename: 5_hidden Epoch 34 loss:2.6001324082990145 ael:0.007730010364156349 cl:25.924023492946734

filename: 5_hidden Epoch 35 loss:2.596153944693608 ael:0.007567204766619112 cl:25.88586692220402

filename: 5_hidden Epoch 36 loss:2.592665382823692 ael:0.007417318331993925 cl:25.852480192904874

filename: 5_hidden Epoch 37 loss:2.5889862352878605 ael:0.007263602155563288 cl:25.81722582929065

filename: 5_hidden Epoch 38 loss:2.587013808487954 ael:0.007091141770131992 cl:25.79922618642468

filename: 5_hidden Epoch 39 loss:2.5838321536237 ael:0.006877006217326511 cl:25.769550993982854

filename: 5_hidden Epoch 40 loss:2.58090897707296 ael:0.006697237174433236 cl:25.74211690051988

filename: 5_hidden Epoch 41 loss:2.5784469890166504 ael:0.006546299353592995 cl:25.71900644114534

filename: 5_hidden Epoch 42 loss:2.5756936888836233 ael:0.00641876656960996 cl:25.692748742875125

filename: 5_hidden Epoch 43 loss:2.572717029178746 ael:0.006301795379510621 cl:25.664151841997953

filename: 5_hidden Epoch 44 loss:2.5704819026714962 ael:0.006234809877483276 cl:25.642470440880018

filename: 5_hidden Epoch 45 loss:2.568853775719638 ael:0.006219657068564555 cl:25.626340698226972

filename: 5_hidden Epoch 46 loss:2.5668841823025317 ael:0.006166652200348365 cl:25.607174821757106

filename: 5_hidden Epoch 47 loss:2.564930454687833 ael:0.006102333625727938 cl:25.5882807769433

filename: 5_hidden Epoch 48 loss:2.5629756933909884 ael:0.006035892551983571 cl:25.56939751095559

filename: 5_hidden Epoch 49 loss:2.5610959181551385 ael:0.006028333716456714 cl:25.5506753529197

filename: 5_hidden Epoch 50 loss:2.559023690324744 ael:0.006016313129716964 cl:25.530073281447212

filename: 5_hidden Epoch 51 loss:2.5577922109296214 ael:0.006006506205949959 cl:25.517856557480386

filename: 5_hidden Epoch 52 loss:2.556559328306527 ael:0.005987731780396179 cl:25.50571548073882

filename: 5_hidden Epoch 53 loss:2.554375700806775 ael:0.005945153445947188 cl:25.484304974959457

filename: 5_hidden Epoch 54 loss:2.553180202347654 ael:0.005982753320691614 cl:25.471974014076796

filename: 5_hidden Epoch 55 loss:2.5511956529348634 ael:0.005979998842461303 cl:25.452156098279474

filename: 5_hidden Epoch 56 loss:2.549921239887619 ael:0.0059863234464031774 cl:25.43934870966947

filename: 5_hidden Epoch 57 loss:2.5484097631041234 ael:0.00596421827684983 cl:25.424454932734722

filename: 5_hidden Epoch 58 loss:2.54686624122302 ael:0.005996973314504802 cl:25.408692180411947

filename: 5_hidden Epoch 59 loss:2.5457397122479413 ael:0.005967234046324044 cl:25.3977242819064

filename: 5_hidden Epoch 60 loss:2.5444747382225583 ael:0.006019938854294929 cl:25.384547503920036

filename: 5_hidden Epoch 61 loss:2.5426365392994508 ael:0.006041706880200231 cl:25.365947861292213

filename: 5_hidden Epoch 62 loss:2.5418202565572887 ael:0.006066400962815569 cl:25.357538063488704

filename: 5_hidden Epoch 63 loss:2.5404555110436844 ael:0.006053645463882799 cl:25.344018191002576

filename: 5_hidden Epoch 64 loss:2.5396117765212174 ael:0.006094943126582299 cl:25.335167859861365

filename: 5_hidden Epoch 65 loss:2.537665695301228 ael:0.006068407436003859 cl:25.315972411165923

filename: 5_hidden Epoch 66 loss:2.5373909076352095 ael:0.006083537485451435 cl:25.313073236013224

filename: 5_hidden Epoch 67 loss:2.5358817746175015 ael:0.00607660847126962 cl:25.298051203078863

filename: 5_hidden Epoch 68 loss:2.534453044357338 ael:0.006095228162140204 cl:25.2835776962208

filename: 5_hidden Epoch 69 loss:2.5335217798418963 ael:0.006081896915110499 cl:25.274398335314427

filename: 5_hidden Epoch 70 loss:2.5323169441242164 ael:0.0060577221393327005 cl:25.26259174123425

filename: 5_hidden Epoch 71 loss:2.531303596211264 ael:0.006108648427447471 cl:25.251948999782

filename: 5_hidden Epoch 72 loss:2.5306044908807452 ael:0.006106424727041773 cl:25.24498016891917

filename: 5_hidden Epoch 73 loss:2.529873409344947 ael:0.0061789831188160255 cl:25.23694377300954

filename: 5_hidden Epoch 74 loss:2.5282466017495544 ael:0.006147012877740324 cl:25.220995410604388

filename: 5_hidden Epoch 75 loss:2.5271379960739413 ael:0.006088065880445271 cl:25.210498813143158

filename: 5_hidden Epoch 76 loss:2.526107724186667 ael:0.006080630318034367 cl:25.20027044472686

filename: 5_hidden Epoch 77 loss:2.5255555658380873 ael:0.006042293763534442 cl:25.195132240099493

filename: 5_hidden Epoch 78 loss:2.5247788905978528 ael:0.006017909273347321 cl:25.18760935132624

filename: 5_hidden Epoch 79 loss:2.5235336408802946 ael:0.0059720279722737125 cl:25.17561566969368

filename: 5_hidden Epoch 80 loss:2.522674874277431 ael:0.005874123009248205 cl:25.16800704200914

filename: 5_hidden Epoch 81 loss:2.5222569069521175 ael:0.005763310672168726 cl:25.16493548267472

filename: 5_hidden Epoch 82 loss:2.520759030310955 ael:0.005709384404340162 cl:25.15049599281602

filename: 5_hidden Epoch 83 loss:2.5194478244800513 ael:0.005590907528363048 cl:25.13856868415781

filename: 5_hidden Epoch 84 loss:2.5189818863380107 ael:0.005542235385451946 cl:25.134396013075857

filename: 5_hidden Epoch 85 loss:2.5181920914779545 ael:0.005377821788206656 cl:25.128142231570546

filename: 5_hidden Epoch 86 loss:2.5172292181037363 ael:0.005199192495778857 cl:25.120299766082116

filename: 5_hidden Epoch 87 loss:2.5168887298025715 ael:0.005172972099047978 cl:25.117157074674587

filename: 5_hidden Epoch 88 loss:2.5156350452030307 ael:0.0050551400223746434 cl:25.10579857770358

filename: 5_hidden Epoch 89 loss:2.515154369689972 ael:0.005013405902176999 cl:25.101409166954724

filename: 5_hidden Epoch 90 loss:2.5147285524433434 ael:0.004995462127952628 cl:25.0973304229257

filename: 5_hidden Epoch 91 loss:2.5137002620278555 ael:0.004935976555879775 cl:25.08764238103136

filename: 5_hidden Epoch 92 loss:2.5127939012870324 ael:0.004906538540773267 cl:25.078873181396574

filename: 5_hidden Epoch 93 loss:2.5123266752923525 ael:0.00487893729283059 cl:25.074476897345015

filename: 5_hidden Epoch 94 loss:2.511497645388812 ael:0.004868810181999386 cl:25.06628786932052

filename: 5_hidden Epoch 95 loss:2.510683113427211 ael:0.004809488798892188 cl:25.05873577828361

filename: 5_hidden Epoch 96 loss:2.5102707836224356 ael:0.004797895598078783 cl:25.054728403616892

filename: 5_hidden Epoch 97 loss:2.509717082477989 ael:0.004752915505307295 cl:25.049641187159505

filename: 5_hidden Epoch 98 loss:2.50893089462771 ael:0.004707851977956188 cl:25.042229985037636

filename: 5_hidden Epoch 99 loss:2.5088088607526546 ael:0.00469899798165965 cl:25.0410981445769

filename: 5_hidden Epoch 100 loss:2.5076488958157617 ael:0.004655331112404928 cl:25.029935175330525

filename: 5_hidden Epoch 101 loss:2.5077200694976973 ael:0.004652192539655506 cl:25.03067826713537

filename: 5_hidden Epoch 102 loss:2.507253907262402 ael:0.00463344272327331 cl:25.02620416078684

filename: 5_hidden Epoch 103 loss:2.506344377474427 ael:0.004628227125993544 cl:25.017161030508994

filename: 5_hidden Epoch 104 loss:2.50573271047858 ael:0.004567041820622433 cl:25.011656190771856

filename: 5_hidden Epoch 105 loss:2.5057225740333355 ael:0.004692914737068067 cl:25.010296137545122

filename: 5_hidden Epoch 106 loss:2.5051084044448637 ael:0.004688952772011337 cl:25.004194050410597

filename: 5_hidden Epoch 107 loss:2.5038982704969097 ael:0.00466103396652212 cl:24.99237188083874

filename: 5_hidden Epoch 108 loss:2.504416484958779 ael:0.0046578219239499 cl:24.997586157339168

filename: 5_hidden Epoch 109 loss:2.503364189578779 ael:0.004594211369321935 cl:24.987699316553094

filename: 5_hidden Epoch 110 loss:2.502247260413958 ael:0.00455797252296794 cl:24.97689240901912

filename: 5_hidden Epoch 111 loss:2.5017937872065654 ael:0.004535228473268314 cl:24.97258510128336

filename: 5_hidden Epoch 112 loss:2.5003887012218247 ael:0.0044957661494028495 cl:24.958928873104455

filename: 5_hidden Epoch 113 loss:2.500189293355188 ael:0.004506846881726753 cl:24.956823988110607

filename: 5_hidden Epoch 114 loss:2.4994867536915235 ael:0.004425672295358662 cl:24.95061034366871

filename: 5_hidden Epoch 115 loss:2.498853750699656 ael:0.004404564624758146 cl:24.94449137571416

filename: 5_hidden Epoch 116 loss:2.4979480451195353 ael:0.004387748332025924 cl:24.9356025005332

filename: 5_hidden Epoch 117 loss:2.497387419671853 ael:0.004369744116626634 cl:24.930176276751688

filename: 5_hidden Epoch 118 loss:2.497153892448138 ael:0.00434838143302482 cl:24.928054609847944

filename: 5_hidden Epoch 119 loss:2.4963943762720984 ael:0.004313814200749293 cl:24.92080515574054

filename: 5_hidden Epoch 120 loss:2.496670153039377 ael:0.004365907373938666 cl:24.923041966394784

filename: 5_hidden Epoch 121 loss:2.4959903741174134 ael:0.004250311859837162 cl:24.917400111881047

filename: 5_hidden Epoch 122 loss:2.4954192999205187 ael:0.004241415587045128 cl:24.911778358948318

filename: 5_hidden Epoch 123 loss:2.4951774177037698 ael:0.004190567956911829 cl:24.90986800924913

filename: 5_hidden Epoch 124 loss:2.49422110651711 ael:0.004137204764773073 cl:24.900838533323977

filename: 5_hidden Epoch 125 loss:2.4940641609934673 ael:0.004137419806075859 cl:24.89926692940772

filename: 5_hidden Epoch 126 loss:2.494105846321336 ael:0.004096009136170402 cl:24.900097887167103

filename: 5_hidden Epoch 127 loss:2.4927723947471288 ael:0.00409684973141739 cl:24.88675496584755

filename: 5_hidden Epoch 128 loss:2.4928052335033923 ael:0.004087738483149035 cl:24.88717447032182

filename: 5_hidden Epoch 129 loss:2.4925351115540355 ael:0.004058650747959497 cl:24.884764129459874

filename: 5_hidden Epoch 130 loss:2.4915015178557733 ael:0.0040337191988107785 cl:24.874677496876572

filename: 5_hidden Epoch 131 loss:2.490978129276817 ael:0.004017353377880111 cl:24.86960728249922

filename: 5_hidden Epoch 132 loss:2.4904990932704267 ael:0.003968747186062826 cl:24.865302984389366

filename: 5_hidden Epoch 133 loss:2.4911583550580865 ael:0.004025329840995281 cl:24.871329752889483

filename: 5_hidden Epoch 134 loss:2.4904074975600774 ael:0.003952258855231688 cl:24.864551923186426

filename: 5_hidden Epoch 135 loss:2.48937645828715 ael:0.00393592497807324 cl:24.854404856991632

filename: 5_hidden Epoch 136 loss:2.4888003696321817 ael:0.003944106869273235 cl:24.84856213360646

filename: 5_hidden Epoch 137 loss:2.489456849513105 ael:0.003926799856267945 cl:24.855300007422823

filename: 5_hidden Epoch 138 loss:2.4881641266203913 ael:0.00393648687341443 cl:24.84227592004145

filename: 5_hidden Epoch 139 loss:2.487404943552733 ael:0.0039035834934993394 cl:24.835013112115966

filename: 5_hidden Epoch 140 loss:2.4874329640662634 ael:0.0039033604770359206 cl:24.8352955575894

filename: 5_hidden Epoch 141 loss:2.487150782571116 ael:0.0038938209689281483 cl:24.8325691408601

filename: 5_hidden Epoch 142 loss:2.486468063747755 ael:0.0038596180636120895 cl:24.826083984317936

filename: 5_hidden Epoch 143 loss:2.4861886720055804 ael:0.003844175946510301 cl:24.82344446013438

filename: 5_hidden Epoch 144 loss:2.4856450962503187 ael:0.0038362851754045455 cl:24.8180876379743

filename: 5_hidden Epoch 145 loss:2.4856278934374143 ael:0.0038406258565983225 cl:24.81787219555174

filename: 5_hidden Epoch 146 loss:2.4850160182191083 ael:0.003818251633850848 cl:24.811977207675536

filename: 5_hidden Epoch 147 loss:2.484410759160953 ael:0.0038188100987276777 cl:24.80591901190945

filename: 5_hidden Epoch 148 loss:2.4842986641486546 ael:0.0038023077919628777 cl:24.80496309119191

filename: 5_hidden Epoch 149 loss:2.484119047639495 ael:0.003788254940947339 cl:24.803307428409916

filename: 5_hidden Epoch 150 loss:2.483101867494129 ael:0.0037952608729468168 cl:24.79306561249624

filename: 5_hidden Epoch 151 loss:2.4831028863754216 ael:0.003740320591210977 cl:24.793625168478183

filename: 5_hidden Epoch 152 loss:2.4812587495160443 ael:0.003724643195928447 cl:24.775340584560215

filename: 5_hidden Epoch 153 loss:2.4820310420985234 ael:0.0037241936585840608 cl:24.78306800758592

filename: 5_hidden Epoch 154 loss:2.4805179381721247 ael:0.003730085627664632 cl:24.76787806567751

filename: 5_hidden Epoch 155 loss:2.4802178872906637 ael:0.0037362144729301307 cl:24.76481623805333

filename: 5_hidden Epoch 156 loss:2.4801486268420376 ael:0.003713892169152318 cl:24.764346876218116

filename: 5_hidden Epoch 157 loss:2.4796586982985738 ael:0.003702565545204129 cl:24.759560853933877

filename: 5_hidden Epoch 158 loss:2.478725652033716 ael:0.003707459869166932 cl:24.75018145871026

filename: 5_hidden Epoch 159 loss:2.477854538308626 ael:0.0036858985452684965 cl:24.74168591153381

filename: 5_hidden Epoch 160 loss:2.4779513470700363 ael:0.003699630032760437 cl:24.742516692871764

filename: 5_hidden Epoch 161 loss:2.477334709067619 ael:0.0036728544215521024 cl:24.736618080510073

filename: 5_hidden Epoch 162 loss:2.4757433315667985 ael:0.0036629609400473813 cl:24.72080324867722

filename: 5_hidden Epoch 163 loss:2.4758527205787493 ael:0.003698100351743127 cl:24.72154572467143

filename: 5_hidden Epoch 164 loss:2.4747329831747487 ael:0.003680389452162815 cl:24.710525457058367

filename: 5_hidden Epoch 165 loss:2.4757235459751157 ael:0.0036666406174818422 cl:24.72056857013726

filename: 5_hidden Epoch 166 loss:2.4742567358513896 ael:0.0036628698337241744 cl:24.705938194196914

filename: 5_hidden Epoch 167 loss:2.4738141864471324 ael:0.003681465413649405 cl:24.70132669978117

filename: 5_hidden Epoch 168 loss:2.4704678255374577 ael:0.0037135718873537366 cl:24.667542068359708

filename: 5_hidden Epoch 169 loss:2.4682026674431836 ael:0.003676260154897719 cl:24.645263598643464

filename: 5_hidden Epoch 170 loss:2.4665748559456757 ael:0.003681819472783293 cl:24.628929910443425

filename: 5_hidden Epoch 171 loss:2.4666812347373117 ael:0.003667495794103434 cl:24.630136913089377

filename: 5_hidden Epoch 172 loss:2.465516664000468 ael:0.0036509442567473314 cl:24.61865672718049

filename: 5_hidden Epoch 173 loss:2.464116938718683 ael:0.003632432002213379 cl:24.604844580978206

filename: 5_hidden Epoch 174 loss:2.4635340824474334 ael:0.0036268858289556466 cl:24.5990715083919

filename: 5_hidden Epoch 175 loss:2.461609687272583 ael:0.0036399159465534034 cl:24.57969720878972

filename: 5_hidden Epoch 176 loss:2.4616294084300248 ael:0.0036156073329184036 cl:24.58013753717423

filename: 5_hidden Epoch 177 loss:2.460785027128061 ael:0.003605107288636737 cl:24.571798712141465

filename: 5_hidden Epoch 178 loss:2.4606181885708125 ael:0.0036107069936705642 cl:24.570074339157863

filename: 5_hidden Epoch 179 loss:2.459940483195025 ael:0.003570718186605853 cl:24.563697148724643

filename: 5_hidden Epoch 180 loss:2.458698832581567 ael:0.003559509386631006 cl:24.551392771364952

filename: 5_hidden Epoch 181 loss:2.4582991107269225 ael:0.0035302585917421666 cl:24.54768802411715

filename: 5_hidden Epoch 182 loss:2.457753513614842 ael:0.0035398347775550056 cl:24.542136320476963

filename: 5_hidden Epoch 183 loss:2.457517541753654 ael:0.0035212108559699367 cl:24.539962804694927

filename: 5_hidden Epoch 184 loss:2.4572586659569597 ael:0.003519464451417966 cl:24.53739152088988

filename: 5_hidden Epoch 185 loss:2.456710239385197 ael:0.0035028439700697292 cl:24.532073468646036

filename: 5_hidden Epoch 186 loss:2.455545863555988 ael:0.003473597466265325 cl:24.520722167862232

filename: 5_hidden Epoch 187 loss:2.4553659557850396 ael:0.0034684078502964493 cl:24.51897502129763

filename: 5_hidden Epoch 188 loss:2.4546989353777198 ael:0.0034812581967478846 cl:24.51217627495609

filename: 5_hidden Epoch 189 loss:2.453423855222095 ael:0.0035110223907522248 cl:24.49912786994959

filename: 5_hidden Epoch 190 loss:2.452574488409913 ael:0.0034805561300451635 cl:24.49093884287615

filename: 5_hidden Epoch 191 loss:2.4527536751593297 ael:0.0034734476218963653 cl:24.49280180321225

filename: 5_hidden Epoch 192 loss:2.4523749306326166 ael:0.0034159277290049164 cl:24.48958958036375

filename: 5_hidden Epoch 193 loss:2.453207574916641 ael:0.0034304743701054794 cl:24.497770532471556

filename: 5_hidden Epoch 194 loss:2.451537533193953 ael:0.003468447575929366 cl:24.4806903995085

filename: 5_hidden Epoch 195 loss:2.4500289762801764 ael:0.003446376516500674 cl:24.46582552002303

filename: 5_hidden Epoch 196 loss:2.4500950487199136 ael:0.003388396573999009 cl:24.467066038460306

filename: 5_hidden Epoch 197 loss:2.4493455023160453 ael:0.0034186617798436405 cl:24.459267956513294

filename: 5_hidden Epoch 198 loss:2.4504529025244968 ael:0.003423793018825503 cl:24.470290625550092

filename: 5_hidden Epoch 199 loss:2.449362512063992 ael:0.0033896694280141216 cl:24.459727931397122

filename: 5_hidden Epoch 200 loss:2.4491441637403915 ael:0.0033904909740458235 cl:24.457536238026243

filename: 5_hidden Epoch 201 loss:2.447970808013007 ael:0.0033832427803974956 cl:24.44587517640621

filename: 5_hidden Epoch 202 loss:2.447951996900054 ael:0.003361354077574329 cl:24.445905964085064

filename: 5_hidden Epoch 203 loss:2.4479636122418946 ael:0.003388487973116474 cl:24.44575075983139

filename: 5_hidden Epoch 204 loss:2.447354948511744 ael:0.0033402331900761755 cl:24.440146661405105

filename: 5_hidden Epoch 205 loss:2.446392623779632 ael:0.003323180750532508 cl:24.430693964743014

filename: 5_hidden Epoch 206 loss:2.445817199736514 ael:0.0033343015519014673 cl:24.424828531973322

filename: 5_hidden Epoch 207 loss:2.445341681578129 ael:0.0033160237957890848 cl:24.420256082329836

filename: 5_hidden Epoch 208 loss:2.4457721097960907 ael:0.003335690233269922 cl:24.424363729038966

filename: 5_hidden Epoch 209 loss:2.4454290747969445 ael:0.0033339217468994946 cl:24.42095104342118

filename: 5_hidden Epoch 210 loss:2.4455501051265323 ael:0.003304503443336281 cl:24.42245553111055

filename: 5_hidden Epoch 211 loss:2.4452596007960303 ael:0.003338365800719596 cl:24.419211844855845

filename: 5_hidden Epoch 212 loss:2.4448115703204243 ael:0.003339602612713605 cl:24.414719221865973

filename: 5_hidden Epoch 213 loss:2.4437287524286813 ael:0.003272625931780818 cl:24.40456077958009

filename: 5_hidden Epoch 214 loss:2.4437242481542687 ael:0.003300418956711428 cl:24.404237821374977

filename: 5_hidden Epoch 215 loss:2.443362208085594 ael:0.00330614802183556 cl:24.400560114158417

filename: 5_hidden Epoch 216 loss:2.442662468339344 ael:0.003260655449603493 cl:24.394017651086436

filename: 5_hidden Epoch 217 loss:2.4429664170168426 ael:0.003282118187632158 cl:24.39684251192293

filename: 5_hidden Epoch 218 loss:2.4426974975625884 ael:0.0032591485400152225 cl:24.39438298086786

filename: 5_hidden Epoch 219 loss:2.443044731486798 ael:0.0032457483920650208 cl:24.397989337743294

filename: 5_hidden Epoch 220 loss:2.442497991558561 ael:0.0032396857373414565 cl:24.392582598305555

filename: 5_hidden Epoch 221 loss:2.4408417687811954 ael:0.003236491502859618 cl:24.376052283907853

filename: 5_hidden Epoch 222 loss:2.4427608642991836 ael:0.0032529174533053374 cl:24.395078980991055

filename: 5_hidden Epoch 223 loss:2.441575813935422 ael:0.0032364285439094964 cl:24.38339338965976

filename: 5_hidden Epoch 224 loss:2.4415854540468005 ael:0.0032121691680637547 cl:24.383732380815886

filename: 5_hidden Epoch 225 loss:2.440867852463267 ael:0.003227542163662536 cl:24.376402606930824

filename: 5_hidden Epoch 226 loss:2.44182089824862 ael:0.003230776506749162 cl:24.385900731397015

filename: 5_hidden Epoch 227 loss:2.4399241165935295 ael:0.0032379042324235064 cl:24.366861624897226

filename: 5_hidden Epoch 228 loss:2.4409813254410357 ael:0.0032879982897220028 cl:24.376932787556388

filename: 5_hidden Epoch 229 loss:2.4401112821921838 ael:0.003199369967962717 cl:24.3691186360426

filename: 5_hidden Epoch 230 loss:2.43843038906572 ael:0.0032256099783098667 cl:24.35204735315818

filename: 5_hidden Epoch 231 loss:2.43955407467188 ael:0.0032125692110465958 cl:24.36341458180099

filename: 5_hidden Epoch 232 loss:2.4401262378906616 ael:0.003190683015956323 cl:24.36935506595753

filename: 5_hidden Epoch 233 loss:2.439267349730582 ael:0.0032183786591654727 cl:24.360489244919947

filename: 5_hidden Epoch 234 loss:2.4391886003889427 ael:0.003174492401536206 cl:24.360140572459702

filename: 5_hidden Epoch 235 loss:2.439151986642123 ael:0.003179816576289777 cl:24.359721233945212

filename: 5_hidden Epoch 236 loss:2.4389785700859616 ael:0.003168900673259333 cl:24.35809621475665

filename: 5_hidden Epoch 237 loss:2.4392286208881995 ael:0.0031648050072516786 cl:24.36063769237563

filename: 5_hidden Epoch 238 loss:2.4384737815443223 ael:0.0031504542831534894 cl:24.35323278531265

filename: 5_hidden Epoch 239 loss:2.4385353053665257 ael:0.00313720673911749 cl:24.3539805368306

filename: 5_hidden Epoch 240 loss:2.436856700428345 ael:0.0031377473441831444 cl:24.33718906403539

filename: 5_hidden Epoch 241 loss:2.438281018369604 ael:0.00311577584353821 cl:24.351651915705016

filename: 5_hidden Epoch 242 loss:2.4372152718663127 ael:0.003086810173949529 cl:24.341284130137332

filename: 5_hidden Epoch 243 loss:2.4365874378795906 ael:0.0030886844943858716 cl:24.33498704977328

filename: 5_hidden Epoch 244 loss:2.4372915429862116 ael:0.003083253385585263 cl:24.34208242377864

filename: 5_hidden Epoch 245 loss:2.4369537105170367 ael:0.0030819052630711307 cl:24.338717560731276

filename: 5_hidden Epoch 246 loss:2.4380576670006366 ael:0.0030602028881513347 cl:24.349974157447026

filename: 5_hidden Epoch 247 loss:2.43628211515974 ael:0.0030653044733266912 cl:24.332167647063837

filename: 5_hidden Epoch 248 loss:2.434788254840331 ael:0.003051181249205572 cl:24.317370274214934

filename: 5_hidden Epoch 249 loss:2.4359638242167567 ael:0.0030361553598058323 cl:24.329276225894386

filename: 5_hidden Epoch 250 loss:2.4347187900923637 ael:0.0030081123440732845 cl:24.31710629355013

/tmp/ipykernel_887182/3449680296.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
/tmp/ipykernel_887182/3449680296.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3         4         5  Label
0       -0.040691 -0.032932 -0.037882 -0.051103 -0.024731 -0.024219      1
1       -0.028289 -0.042353 -0.042344 -0.035388 -0.046168 -0.034631      0
2       -0.051200 -0.030225 -0.045836 -0.028097 -0.031909 -0.061703      2
3       -0.034350 -0.027865 -0.035685 -0.044547 -0.018331 -0.023210      1
4       -0.012465 -0.022401 -0.023921 -0.011339 -0.017951 -0.028282      4
...           ...       ...       ...       ...       ...       ...    ...
2053285 -0.028301 -0.042359 -0.042351 -0.035405 -0.046173 -0.034630      0
2053286 -0.051205 -0.030228 -0.045841 -0.028098 -0.031914 -0.061707      2
2053287 -0.051209 -0.030230 -0.045845 -0.028099 -0.031917 -0.061710      2
2053288 -0.028283 -0.042350 -0.042341 -0.035378 -0.046165 -0.034631      0
2053289 -0.051528 -0.030447 -0.046205 -0.028192 -0.032239 -0.061988      2

[2053290 rows x 7 columns]

Davies-Bouldin Score: 0.5761587876070596

               0         1         2         3         4         5  Label
0      -0.029239 -0.043300 -0.041827 -0.035562 -0.047909 -0.035280      0
1      -0.051187 -0.030215 -0.045821 -0.028092 -0.031895 -0.061693      2
2      -0.039754 -0.032127 -0.039756 -0.054188 -0.024070 -0.023774      1
3      -0.053348 -0.039008 -0.002470 -0.034627 -0.045890 -0.036343      3
4      -0.039762 -0.031931 -0.038041 -0.052815 -0.024251 -0.024112      1
...          ...       ...       ...       ...       ...       ...    ...
519951 -0.040344 -0.032203 -0.041154 -0.056125 -0.023594 -0.023259      1
519952 -0.011878 -0.020736 -0.021588 -0.009574 -0.015656 -0.027774      4
519953 -0.028298 -0.042357 -0.042349 -0.035401 -0.046172 -0.034630      0
519954 -0.038885 -0.032603 -0.038591 -0.048861 -0.024001 -0.023705      1
519955 -0.055087 -0.038761 -0.000432 -0.035223 -0.045602 -0.036237      3

[519956 rows x 7 columns]

               0         1         2         3         4         5  Label
0      -0.028290 -0.042354 -0.042345 -0.035389 -0.046168 -0.034631      0
1      -0.029595 -0.043577 -0.042220 -0.036191 -0.048219 -0.035290      0
2      -0.039301 -0.032382 -0.038830 -0.052636 -0.024991 -0.024381      1
3      -0.046672 -0.030900 -0.045177 -0.067724 -0.018224 -0.019842      1
4      -0.028782 -0.042655 -0.041153 -0.034787 -0.047007 -0.035082      0
...          ...       ...       ...       ...       ...       ...    ...
649942 -0.039611 -0.031827 -0.037831 -0.052503 -0.024159 -0.024131      1
649943 -0.028669 -0.042659 -0.041099 -0.034591 -0.047065 -0.035134      0
649944 -0.028718 -0.042648 -0.041127 -0.034686 -0.047021 -0.035103      0
649945 -0.052678 -0.038841 -0.002546 -0.033938 -0.045726 -0.036377      3
649946 -0.044897 -0.029440 -0.073437 -0.029381 -0.025295 -0.060764      5

[649947 rows x 7 columns]