# DDoS attack-HOIC - encoder generator

## Import libraries

In [6]:
import torch
from torch import nn, optim
import torch.nn.functional as F
import numpy as np
import pandas as pd

## Import training, validation and test data

In [11]:
train = pd.read_csv('../../train.csv')
val = pd.read_csv('../../val.csv')
test = pd.read_csv('../../test.csv')

'Infilteration' and 'DoS attacks-SlowHTTPTest' classes were aparently mislabeled, so we will exclude them, remaining 12 attack classes

In [12]:
classes_out = ['Infilteration','DoS attacks-SlowHTTPTest']
train = train.drop(index=train[train['Label'].isin(classes_out)].index)
val = val.drop(index=val[val['Label'].isin(classes_out)].index)
test = test.drop(index=test[test['Label'].isin(classes_out)].index)

11 attack classes will be joined into major attack classes
* FTP-BruteForce and SSH-Bruteforce -> BruteForce
* DoS attacks-GoldenEye, DoS attacks-Slowloris and DoS attacks-Hulk -> DoS
* DDoS attacks-LOIC-HTTP, DDOS attack-LOIC-UDP and DDOS attack-HOIC -> DDoS
* Brute Force -Web, Brute Force -XSS and SQL Injection -> DDoS

Resulting in 5 major attack classes: BruteForce, DoS, DDoS, Web and Bot, and Benign class

In [13]:
train['Label'] = train['Label'].replace('FTP-BruteForce','BruteForce')
train['Label'] = train['Label'].replace('SSH-Bruteforce','BruteForce')
train['Label'] = train['Label'].replace('DoS attacks-GoldenEye','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Slowloris','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Hulk','DoS')
train['Label'] = train['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
train['Label'] = train['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
# train['Label'] = train['Label'].replace('DDOS attack-HOIC','DDoS')
train['Label'] = train['Label'].replace('Brute Force -Web','Web')
train['Label'] = train['Label'].replace('Brute Force -XSS','Web')
train['Label'] = train['Label'].replace('SQL Injection','Web')


val['Label'] = val['Label'].replace('FTP-BruteForce','BruteForce')
val['Label'] = val['Label'].replace('SSH-Bruteforce','BruteForce')
val['Label'] = val['Label'].replace('DoS attacks-GoldenEye','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Slowloris','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Hulk','DoS')
val['Label'] = val['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
val['Label'] = val['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
# val['Label'] = val['Label'].replace('DDOS attack-HOIC','DDoS')
val['Label'] = val['Label'].replace('Brute Force -Web','Web')
val['Label'] = val['Label'].replace('Brute Force -XSS','Web')
val['Label'] = val['Label'].replace('SQL Injection','Web')


test['Label'] = test['Label'].replace('FTP-BruteForce','BruteForce')
test['Label'] = test['Label'].replace('SSH-Bruteforce','BruteForce')
test['Label'] = test['Label'].replace('DoS attacks-GoldenEye','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Slowloris','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Hulk','DoS')
test['Label'] = test['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
test['Label'] = test['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
# test['Label'] = test['Label'].replace('DDOS attack-HOIC','DDoS')
test['Label'] = test['Label'].replace('Brute Force -Web','Web')
test['Label'] = test['Label'].replace('Brute Force -XSS','Web')
test['Label'] = test['Label'].replace('SQL Injection','Web')

## Labels into numeric

In [14]:
labels_str = [i for i in train['Label'].value_counts().index]
print(labels_str)

for i, l in enumerate(labels_str):
    train['Label'] = train['Label'].replace(l, i)
    val['Label'] = val['Label'].replace(l, i)
    test['Label'] = test['Label'].replace(l, i)

['Benign', 'DDOS attack-HOIC', 'DDoS', 'DoS', 'BruteForce', 'Bot', 'Web']

C:\Users\Lincoln\AppData\Local\Temp\ipykernel_332\2307520911.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train['Label'] = train['Label'].replace(l, i)
C:\Users\Lincoln\AppData\Local\Temp\ipykernel_332\2307520911.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  val['Label'] = val['Label'].replace(l, i)
C:\Users\Lincoln\AppData\Local\Temp\ipykernel_332\2307520911.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['Label'] = test['Label'].replace(l, i)

## Contrastive AutoEncoder Functions

<img src="..\..\img\contrastive_pairs.png" alt="Contrastive Pairs" width="60%"/>

In [ ]:
def pick_pair(embeddings, labels, pick_embeddings, pick_labels):
    """
    Generates all pairs between embeddings (batch) and pick_embeddings (reference samples), with labels_pair indicating whether the pairs are positive (0) or negative (1). 
    """
    N, D = embeddings.shape
    M = pick_embeddings.shape[0]

    # Expands to all possible combinations
    A = embeddings.unsqueeze(0).expand(M, N, D).reshape(M * N, D)
    B = pick_embeddings.unsqueeze(1).expand(M, N, D).reshape(M * N, D)

    labels_exp = labels.unsqueeze(0).expand(M, N)
    pick_labels_exp = pick_labels.unsqueeze(1).expand(M, N)
    labels_pair = (labels_exp != pick_labels_exp).reshape(-1).float()

    return A, B, labels_pair

def ContrastiveLoss(input1, input2, y, margin=1.0):
    # y = 0 when input1 and input2 belong to the same class, and y = 1 otherwise.
    diff = input1 - input2
    dist_sq = torch.sum(torch.pow(diff,2),1)
    dist = torch.sqrt(dist_sq + 1e-10) # Adds 1e-10 because if the sqrt is 0, the gradient becomes NaN.
    mdist = margin - dist
    mdist = F.relu(mdist)
    loss = ((1-y) * dist * dist) + (y * mdist * mdist)
    return torch.mean(loss)

def AEContrastive(input, output, embeddings, labels, pick_encoded, pick_labels, margin=1.0, lambda1=1.0):
    mseloss = nn.MSELoss()
    ae_loss = mseloss(input,output)

    A, B, labels_pair = pick_pair(embeddings, labels, pick_encoded, pick_labels)
    contrastive_loss = ContrastiveLoss(A, B, labels_pair, margin=margin)
    return ae_loss + contrastive_loss * lambda1, ae_loss, contrastive_loss

In [ ]:
class contrastive_ae(nn.Module):
    def __init__(self, input_neurons, neurons):
        super().__init__()
        self.encoder0 = nn.Linear(input_neurons,64)
        self.encoder1 = nn.Linear(64,32)
        self.encoder2 = nn.Linear(32,16)
        self.encoder3 = nn.Linear(16,neurons)

        self.decoder0 = nn.Linear(neurons,16)
        self.decoder1 = nn.Linear(16,32)
        self.decoder2 = nn.Linear(32,64)
        self.decoder3 = nn.Linear(64,input_neurons)

        self.activation0 = nn.ReLU()
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X) # No activation function
        encoded = X
        X = self.activation0(self.decoder0(X))
        X = self.activation0(self.decoder1(X))
        X = self.activation0(self.decoder2(X))
        X = self.decoder3(X) # No activation function


        return X, encoded

In [6]:
class encoder(nn.Module):
    def __init__(self, model):
        super().__init__()
        self.encoder0 = list(model.children())[0]
        self.encoder1 = list(model.children())[1]
        self.encoder2 = list(model.children())[2]
        self.encoder3 = list(model.children())[3]
        self.activation0 = list(model.children())[8]
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X)
        return X

In [ ]:
from torch.utils.data import DataLoader,TensorDataset


# Prepare reference samples for each batch

def build_class_reference_batches(X_train, y_train, batch_size=512):
    classes = torch.unique(y_train).tolist()
    n_classes = len(classes)
    total_samples = len(X_train)
    dataset = TensorDataset(X_train, y_train)
    train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    

    print(classes)

    # Maps each class to its indices
    class_to_indices = {
        int(cls.item()): (y_train == cls).nonzero(as_tuple=True)[0].tolist()
        for cls in torch.unique(y_train)
    }

    reference_list = []
    total_batches = len(train_loader)

    for batch_idx in range(total_batches):
        start = batch_idx * batch_size
        end = min(start + batch_size, total_samples)
        batch_indices = set(range(start, end))

        class_samples = []
        for cls in classes:
            candidates = [i for i in class_to_indices[cls] if i not in batch_indices]
            if not candidates:
                raise ValueError(f"Class {cls} has no samples outside of batch {batch_idx}")
            chosen = candidates[torch.randint(len(candidates), (1,)).item()]
            class_samples.append(chosen)

        reference_list.append(class_samples)


    return train_loader, reference_list

In [ ]:
# Normalization function


def normalize(t):
    t_norm = (t - t.mean()) / t.std()
    return t_norm

In [ ]:
array_hidden_classes = [[1]] # Class 1 correspond to DDoS attack-HOIC class
filenames = ['1']

total_classes = len(labels_str)
for i in range(len(array_hidden_classes)):
    filename = f'{filenames[i]}_hidden'
    print(filename)
    hidden_classes = array_hidden_classes[i] # Classes hidden from training

    hidden_classes_index = list(train[train['Label'].isin(hidden_classes)].index)

    train_hidden = train.loc[hidden_classes_index]

    train_not_hidden = train.drop(hidden_classes_index)

    X_train = train_not_hidden.drop(columns=['Label'])
    y_train = train_not_hidden['Label']
    X_val = val.drop(columns=['Label'])
    y_val = val['Label'].values
    X_test = test.drop(columns=['Label'])
    y_test = test['Label'].values

    torch.manual_seed(123)
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(device)
    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_loader, pick_list = build_class_reference_batches(X_train,y_train, batch_size=512)
    pick_samples = []
    pick_labels = []
    for l in pick_list:
        pick_samples.append(X_train[l])
        pick_labels.append(y_train[l])

    pick_samples = torch.stack(pick_samples)    
    pick_labels = torch.stack(pick_labels)


    neurons = total_classes - len(hidden_classes)
    print(f'{X_train.shape[1]} {neurons}')
    model = contrastive_ae(input_neurons=X_train.shape[1],neurons=neurons)
    model.to(device)

    learning_rate = 0.0001
    opt = optim.Adam(model.parameters(),lr=learning_rate)
    margin = 10 # Class separation parameter
    cae_lambda_1 = 1.0 # Contrastive learning weight 
    
    
    for epoch in range(250):
        running_loss = 0
        running_ael = 0
        running_cl = 0
        counter = 0
        for data in train_loader:
            inputs, labels = data
            inputs = inputs.to(device)
            labels = labels.to(device)
            ps = pick_samples[counter]
            pl = pick_labels[counter]
            ps = ps.to(device)
            pl = pl.to(device)
            counter += 1
            opt.zero_grad()
            outputs, encoded = model(inputs)
            _, pick_encoded = model(ps)
            tam_pe = pick_encoded.shape[0]
            enc_total = torch.cat((encoded,pick_encoded), dim=0)
            enc_total_norm = normalize(enc_total)
            encoded_norm = enc_total_norm[:-tam_pe]
            pick_encoded_norm = enc_total_norm[-tam_pe:]
            loss, ael, cl = AEContrastive(input=inputs, output=outputs, embeddings = encoded_norm, labels=labels, pick_encoded = pick_encoded_norm, pick_labels = pl, margin=margin, lambda1=cae_lambda_1)
            loss.backward()
            opt.step()
            running_loss += loss.item()
            running_ael += ael.item()
            running_cl += cl.item()
        print(f'filename: {filename} Epoch {epoch+1} loss:{running_loss/len(train_loader)} ael:{running_ael/len(train_loader)} cl:{running_cl/len(train_loader)}')

    model_e = encoder(model=model)
    model_e.to(device)

    model_e.eval()

    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_encoded = model_e(X_train.to(device))

    train_encoded = train_encoded.detach().cpu().numpy()

    train_encoded_df = pd.DataFrame(train_encoded)
    train_encoded_df['Label'] = y_train.detach().cpu().numpy().astype(int)
    display(train_encoded_df)


    X_val = torch.tensor(np.array(X_val), dtype=torch.float)

    val_encoded = model_e(X_val.to(device))

    val_encoded = val_encoded.detach().cpu().numpy()

    val_encoded_df = pd.DataFrame(val_encoded)

    val_encoded_df['Label'] = y_val

    display(val_encoded_df)

    X_test = torch.tensor(np.array(X_test), dtype=torch.float)

    test_encoded = model_e(X_test.to(device))

    test_encoded = test_encoded.detach().cpu().numpy()

    test_encoded_df = pd.DataFrame(test_encoded)

    test_encoded_df['Label'] = y_test

    display(test_encoded_df)

    train_encoded_df.to_csv(f'train_encoded_{filename}.csv',index=False)
    val_encoded_df.to_csv(f'val_encoded_{filename}.csv',index=False)
    test_encoded_df.to_csv(f'test_encoded_{filename}.csv',index=False)

1_hidden

cuda

[0.0, 2.0, 3.0, 4.0, 5.0, 6.0]

pick completo
82 6

filename: 1_hidden Epoch 1 loss:3.5873888595241836 ael:0.02484512998549596 cl:35.62543678105156

filename: 1_hidden Epoch 2 loss:3.1929957692597104 ael:0.01710927098024747 cl:31.758864483409294

filename: 1_hidden Epoch 3 loss:3.1364572568170366 ael:0.017006084758805783 cl:31.19451126003414

filename: 1_hidden Epoch 4 loss:3.0799263370204457 ael:0.016308483958546532 cl:30.63617803362342

filename: 1_hidden Epoch 5 loss:3.0262172878997373 ael:0.015791729411659485 cl:30.104255129357394

filename: 1_hidden Epoch 6 loss:2.990741113046774 ael:0.01561233247928147 cl:29.75128733118685

filename: 1_hidden Epoch 7 loss:2.9698750301753862 ael:0.015472632521609435 cl:29.544023495940447

filename: 1_hidden Epoch 8 loss:2.953963134218118 ael:0.015331505608051877 cl:29.386315802516133

filename: 1_hidden Epoch 9 loss:2.9415743267666343 ael:0.015138369656273987 cl:29.264359124551138

filename: 1_hidden Epoch 10 loss:2.9314520437892253 ael:0.01486954929716827 cl:29.165824449750453

filename: 1_hidden Epoch 11 loss:2.9210431983430003 ael:0.014520403466444584 cl:29.06522750497422

filename: 1_hidden Epoch 12 loss:2.910759176813682 ael:0.014183934153800077 cl:28.96575195740984

filename: 1_hidden Epoch 13 loss:2.9002311348729126 ael:0.013962224524543735 cl:28.862688650169908

filename: 1_hidden Epoch 14 loss:2.8911644828486924 ael:0.013844398177823113 cl:28.773200362111776

filename: 1_hidden Epoch 15 loss:2.88278982338035 ael:0.013785475789745122 cl:28.69004301050338

filename: 1_hidden Epoch 16 loss:2.875362623277209 ael:0.013751431809979463 cl:28.616111447100707

filename: 1_hidden Epoch 17 loss:2.868422985448852 ael:0.013694284321063208 cl:28.547286516567475

filename: 1_hidden Epoch 18 loss:2.8602278296549497 ael:0.01360486889702621 cl:28.466229126643093

filename: 1_hidden Epoch 19 loss:2.850230638843245 ael:0.013574786343889285 cl:28.36655808030722

filename: 1_hidden Epoch 20 loss:2.8412427897758303 ael:0.0136141762544231 cl:28.27628566188485

filename: 1_hidden Epoch 21 loss:2.833605819410541 ael:0.013517574969150254 cl:28.200881958602928

filename: 1_hidden Epoch 22 loss:2.8250778155096237 ael:0.013380594665181711 cl:28.116971730962746

filename: 1_hidden Epoch 23 loss:2.81709546112977 ael:0.013221569913737302 cl:28.038738413199248

filename: 1_hidden Epoch 24 loss:2.8092726493960423 ael:0.01305570396044046 cl:27.96216898544716

filename: 1_hidden Epoch 25 loss:2.802359596392294 ael:0.01291114843353141 cl:27.894484019167894

filename: 1_hidden Epoch 26 loss:2.7960235357656495 ael:0.012807606482026916 cl:27.832158827521315

filename: 1_hidden Epoch 27 loss:2.790042427214743 ael:0.012713465376433085 cl:27.773289151719876

filename: 1_hidden Epoch 28 loss:2.7828710924258657 ael:0.012635321447599603 cl:27.702357251409808

filename: 1_hidden Epoch 29 loss:2.7759162860429973 ael:0.01256838465449451 cl:27.63347853185978

filename: 1_hidden Epoch 30 loss:2.768960224559266 ael:0.012482995105480161 cl:27.564771849800383

filename: 1_hidden Epoch 31 loss:2.763102125117262 ael:0.01242363748290284 cl:27.506784408735967

filename: 1_hidden Epoch 32 loss:2.757161307892822 ael:0.01237477479551958 cl:27.44786485799947

filename: 1_hidden Epoch 33 loss:2.7516366129174434 ael:0.0123347059705886 cl:27.393018636242275

filename: 1_hidden Epoch 34 loss:2.74740166931926 ael:0.012279077654184305 cl:27.35122544025296

filename: 1_hidden Epoch 35 loss:2.7433128545883108 ael:0.012252183978310707 cl:27.310606251566348

filename: 1_hidden Epoch 36 loss:2.739649141374133 ael:0.012226991836917288 cl:27.27422099180415

filename: 1_hidden Epoch 37 loss:2.7355649597001337 ael:0.0121701093649204 cl:27.233948028254993

filename: 1_hidden Epoch 38 loss:2.7326780700088475 ael:0.012121282615546318 cl:27.205567394143518

filename: 1_hidden Epoch 39 loss:2.730154491921483 ael:0.012086827950421344 cl:27.180676142771418

filename: 1_hidden Epoch 40 loss:2.7279949302048467 ael:0.012033041129862183 cl:27.159618423509524

filename: 1_hidden Epoch 41 loss:2.7245347210471977 ael:0.011971432591865476 cl:27.125632392300087

filename: 1_hidden Epoch 42 loss:2.721639938175957 ael:0.011888076873516515 cl:27.097518136534788

filename: 1_hidden Epoch 43 loss:2.719015856428935 ael:0.011814479995954799 cl:27.07201331937555

filename: 1_hidden Epoch 44 loss:2.717244075650172 ael:0.01171980502981803 cl:27.055242208162447

filename: 1_hidden Epoch 45 loss:2.7141169155257727 ael:0.011650431365669704 cl:27.0246643524646

filename: 1_hidden Epoch 46 loss:2.7125235875199625 ael:0.011517365247173911 cl:27.01006172941925

filename: 1_hidden Epoch 47 loss:2.709683686597113 ael:0.011378118719225647 cl:26.98305519508683

filename: 1_hidden Epoch 48 loss:2.7080254693857033 ael:0.011230895726675641 cl:26.967945268485177

filename: 1_hidden Epoch 49 loss:2.7056895048495573 ael:0.011060798792938547 cl:26.94628657729317

filename: 1_hidden Epoch 50 loss:2.7032094277755334 ael:0.010868494062395345 cl:26.923408867751196

filename: 1_hidden Epoch 51 loss:2.701617163838165 ael:0.010689903058797447 cl:26.90927211743621

filename: 1_hidden Epoch 52 loss:2.699572041700485 ael:0.010520925788955644 cl:26.89051068465163

filename: 1_hidden Epoch 53 loss:2.698273707328832 ael:0.010231820407923595 cl:26.880418387664463

filename: 1_hidden Epoch 54 loss:2.695795229705001 ael:0.010041695563979854 cl:26.857534863833518

filename: 1_hidden Epoch 55 loss:2.694337889928714 ael:0.009832045822091948 cl:26.845057977566295

filename: 1_hidden Epoch 56 loss:2.693239152896423 ael:0.009622561129161655 cl:26.83616545226384

filename: 1_hidden Epoch 57 loss:2.69012035691236 ael:0.009460546784451618 cl:26.806597615329785

filename: 1_hidden Epoch 58 loss:2.6887986813990077 ael:0.00925072011074368 cl:26.79547915466118

filename: 1_hidden Epoch 59 loss:2.687421162080095 ael:0.009118149437114899 cl:26.78302966458563

filename: 1_hidden Epoch 60 loss:2.6852597479143308 ael:0.009000947382940378 cl:26.762587545814455

filename: 1_hidden Epoch 61 loss:2.6840662248049063 ael:0.008767229466235581 cl:26.752989487194235

filename: 1_hidden Epoch 62 loss:2.6820827758628383 ael:0.008623565692460387 cl:26.73459161707838

filename: 1_hidden Epoch 63 loss:2.6806527656251666 ael:0.008549508084390492 cl:26.72103211794182

filename: 1_hidden Epoch 64 loss:2.6786189172271633 ael:0.008326140124141566 cl:26.70292727727786

filename: 1_hidden Epoch 65 loss:2.6760972979660154 ael:0.008161816797284598 cl:26.679354362666327

filename: 1_hidden Epoch 66 loss:2.6754662800132762 ael:0.008030183790992603 cl:26.674360503198205

filename: 1_hidden Epoch 67 loss:2.673314550402756 ael:0.00783514718738691 cl:26.654793560486315

filename: 1_hidden Epoch 68 loss:2.6721822338431562 ael:0.007680862102593628 cl:26.645013276574765

filename: 1_hidden Epoch 69 loss:2.670978140421851 ael:0.007505960979857795 cl:26.634721314404946

filename: 1_hidden Epoch 70 loss:2.6686992126024456 ael:0.007407926876597723 cl:26.612912387223027

filename: 1_hidden Epoch 71 loss:2.6675249019390708 ael:0.007266173683769432 cl:26.602586825961442

filename: 1_hidden Epoch 72 loss:2.6660705280750294 ael:0.007189016762028293 cl:26.58881465536942

filename: 1_hidden Epoch 73 loss:2.6650042358315122 ael:0.007099550590936136 cl:26.579046380910412

filename: 1_hidden Epoch 74 loss:2.6634676738387895 ael:0.006988309078389276 cl:26.564793173422494

filename: 1_hidden Epoch 75 loss:2.66228885606001 ael:0.006846834684020364 cl:26.554419723129868

filename: 1_hidden Epoch 76 loss:2.6607802004970367 ael:0.00671424481250613 cl:26.540659060902232

filename: 1_hidden Epoch 77 loss:2.6608068857475673 ael:0.006694800348286975 cl:26.541120381585895

filename: 1_hidden Epoch 78 loss:2.659174673047713 ael:0.0065438587352191786 cl:26.526307641920546

filename: 1_hidden Epoch 79 loss:2.6586190076402496 ael:0.006493868836740762 cl:26.521250903029895

filename: 1_hidden Epoch 80 loss:2.657326845445797 ael:0.006402962915918989 cl:26.509238375516468

filename: 1_hidden Epoch 81 loss:2.6560638711158644 ael:0.006271410067296949 cl:26.49792411970832

filename: 1_hidden Epoch 82 loss:2.654979553758261 ael:0.006116427086197805 cl:26.48863079291238

filename: 1_hidden Epoch 83 loss:2.653889238220667 ael:0.006042109960806374 cl:26.47847079129747

filename: 1_hidden Epoch 84 loss:2.6538718512203316 ael:0.005998800704386463 cl:26.47873001753261

filename: 1_hidden Epoch 85 loss:2.6513075668614667 ael:0.005928712025976357 cl:26.45378805627689

filename: 1_hidden Epoch 86 loss:2.6515136604190057 ael:0.005814111057971132 cl:26.456994989546896

filename: 1_hidden Epoch 87 loss:2.6498947087018614 ael:0.005733686830926913 cl:26.441609750709

filename: 1_hidden Epoch 88 loss:2.6498337064258024 ael:0.005635109054311157 cl:26.441985496009195

filename: 1_hidden Epoch 89 loss:2.6485895199262406 ael:0.005594293808262336 cl:26.429951779370004

filename: 1_hidden Epoch 90 loss:2.6477643926504437 ael:0.0054834654958636824 cl:26.42280882836876

filename: 1_hidden Epoch 91 loss:2.6469450078776773 ael:0.00545193072366303 cl:26.414930285901622

filename: 1_hidden Epoch 92 loss:2.6470563187800034 ael:0.005411524186637282 cl:26.41644748503258

filename: 1_hidden Epoch 93 loss:2.6451738565834746 ael:0.005290315645730905 cl:26.39883494027505

filename: 1_hidden Epoch 94 loss:2.645239783151659 ael:0.005259633299788568 cl:26.39980101801118

filename: 1_hidden Epoch 95 loss:2.6448303723298072 ael:0.005194779455025394 cl:26.39635545251522

filename: 1_hidden Epoch 96 loss:2.6438003267773227 ael:0.005136641006199019 cl:26.386636378129076

filename: 1_hidden Epoch 97 loss:2.6434612364181302 ael:0.0050711815011529205 cl:26.38390010649254

filename: 1_hidden Epoch 98 loss:2.6429082125099885 ael:0.005049603801676873 cl:26.378585593451202

filename: 1_hidden Epoch 99 loss:2.642913504732938 ael:0.004961422959912144 cl:26.37952035317741

filename: 1_hidden Epoch 100 loss:2.6415660451243337 ael:0.0048718797737462285 cl:26.36694118541414

filename: 1_hidden Epoch 101 loss:2.6417038609568673 ael:0.004860994808358401 cl:26.36842818594946

filename: 1_hidden Epoch 102 loss:2.640605915057678 ael:0.00479895386760604 cl:26.358069158307103

filename: 1_hidden Epoch 103 loss:2.639914622582065 ael:0.00472813952044408 cl:26.35186437288424

filename: 1_hidden Epoch 104 loss:2.639814005106362 ael:0.0046843984387321 cl:26.35129558188309

filename: 1_hidden Epoch 105 loss:2.6391672819527376 ael:0.00464980819229147 cl:26.345174282389387

filename: 1_hidden Epoch 106 loss:2.638511170909483 ael:0.0046078394164219385 cl:26.33903283879463

filename: 1_hidden Epoch 107 loss:2.6379395446985634 ael:0.00451279964091695 cl:26.33426697860456

filename: 1_hidden Epoch 108 loss:2.6377765476982606 ael:0.004467737617831265 cl:26.333087627750103

filename: 1_hidden Epoch 109 loss:2.637237941307508 ael:0.004386661436362265 cl:26.328512315556708

filename: 1_hidden Epoch 110 loss:2.6367260511877384 ael:0.004323933374749819 cl:26.32402069996374

filename: 1_hidden Epoch 111 loss:2.6362638135782084 ael:0.004288918135161752 cl:26.31974845981449

filename: 1_hidden Epoch 112 loss:2.635775719046035 ael:0.0042325872935168735 cl:26.315430833694528

filename: 1_hidden Epoch 113 loss:2.6352524089366893 ael:0.004138965112362028 cl:26.31113395333848

filename: 1_hidden Epoch 114 loss:2.6352441117469683 ael:0.004068437436749569 cl:26.311756282812347

filename: 1_hidden Epoch 115 loss:2.6349950482432445 ael:0.004008700424811096 cl:26.309862999759858

filename: 1_hidden Epoch 116 loss:2.6343771220369385 ael:0.003946658627125732 cl:26.304304140778303

filename: 1_hidden Epoch 117 loss:2.633830671786518 ael:0.0038875321800240815 cl:26.29943090429916

filename: 1_hidden Epoch 118 loss:2.6332831116436797 ael:0.003828668253650299 cl:26.294543975972907

filename: 1_hidden Epoch 119 loss:2.6328911529130385 ael:0.0038069680179854313 cl:26.290841349871037

filename: 1_hidden Epoch 120 loss:2.632746816983275 ael:0.0037645094547066227 cl:26.28982259301053

filename: 1_hidden Epoch 121 loss:2.631812281020904 ael:0.0037150661392041516 cl:26.280971649098507

filename: 1_hidden Epoch 122 loss:2.631781678192329 ael:0.0036829749417931494 cl:26.28098657045647

filename: 1_hidden Epoch 123 loss:2.6309563902350557 ael:0.00363902530746241 cl:26.273173164689037

filename: 1_hidden Epoch 124 loss:2.630701281388353 ael:0.0036066021266801633 cl:26.270946283682648

filename: 1_hidden Epoch 125 loss:2.630728000783697 ael:0.00358022094570542 cl:26.271477324653898

filename: 1_hidden Epoch 126 loss:2.6299915643266507 ael:0.0035409964572394185 cl:26.26450520484198

filename: 1_hidden Epoch 127 loss:2.6292676569333127 ael:0.003519137336780984 cl:26.25748473061786

filename: 1_hidden Epoch 128 loss:2.6298879055076756 ael:0.0034803761456266348 cl:26.26407480463037

filename: 1_hidden Epoch 129 loss:2.6289561741809577 ael:0.003463239883408299 cl:26.254928869167095

filename: 1_hidden Epoch 130 loss:2.628298848355988 ael:0.0034367319051170496 cl:26.248620697116703

filename: 1_hidden Epoch 131 loss:2.6275794681632387 ael:0.003410989432210646 cl:26.241684320601586

filename: 1_hidden Epoch 132 loss:2.6274868416897776 ael:0.0033769877295499427 cl:26.241098062928863

filename: 1_hidden Epoch 133 loss:2.6273875425460744 ael:0.0033335989548907543 cl:26.240538977088868

filename: 1_hidden Epoch 134 loss:2.6270265281665344 ael:0.003331530301987125 cl:26.236949543350388

filename: 1_hidden Epoch 135 loss:2.6260051516772434 ael:0.003287215707184349 cl:26.227178879498318

filename: 1_hidden Epoch 136 loss:2.6253231101400583 ael:0.00327644987168392 cl:26.220466096613226

filename: 1_hidden Epoch 137 loss:2.62552002231342 ael:0.003235555377711837 cl:26.222844197932346

filename: 1_hidden Epoch 138 loss:2.625407402675349 ael:0.003226231076636943 cl:26.221811246351223

filename: 1_hidden Epoch 139 loss:2.624960228656644 ael:0.003209754457848376 cl:26.217504282339874

filename: 1_hidden Epoch 140 loss:2.6248864075694924 ael:0.0031887446350001044 cl:26.21697615089357

filename: 1_hidden Epoch 141 loss:2.6238083567150667 ael:0.0031720835737326122 cl:26.206362276478973

filename: 1_hidden Epoch 142 loss:2.624336716983694 ael:0.0031439350431933188 cl:26.211927338360624

filename: 1_hidden Epoch 143 loss:2.6228285449529403 ael:0.003114546398601717 cl:26.19713952515315

filename: 1_hidden Epoch 144 loss:2.6225314162636697 ael:0.0030950896128105485 cl:26.19436279689652

filename: 1_hidden Epoch 145 loss:2.622614859641993 ael:0.00308754551529524 cl:26.1952726390916

filename: 1_hidden Epoch 146 loss:2.6222255409972717 ael:0.003064616283659014 cl:26.191608783049443

filename: 1_hidden Epoch 147 loss:2.621221263992619 ael:0.0030445769152788564 cl:26.181766404079013

filename: 1_hidden Epoch 148 loss:2.6214278144509113 ael:0.003042528347450769 cl:26.183852368025995

filename: 1_hidden Epoch 149 loss:2.620415088576199 ael:0.00300560068079763 cl:26.17409439443984

filename: 1_hidden Epoch 150 loss:2.620898271611254 ael:0.002979010485393081 cl:26.179192151145518

filename: 1_hidden Epoch 151 loss:2.62022704207767 ael:0.0029696267963403053 cl:26.17257366686269

filename: 1_hidden Epoch 152 loss:2.6194347009643937 ael:0.0029526640467459043 cl:26.164819883444753

filename: 1_hidden Epoch 153 loss:2.619162076423395 ael:0.002950131304688496 cl:26.162118960542724

filename: 1_hidden Epoch 154 loss:2.6195556191311984 ael:0.0029274998813890816 cl:26.166280705992033

filename: 1_hidden Epoch 155 loss:2.618425841785258 ael:0.002904492870042923 cl:26.15521304090384

filename: 1_hidden Epoch 156 loss:2.6181768819805984 ael:0.0028919617415154456 cl:26.15284870820187

filename: 1_hidden Epoch 157 loss:2.617462612128295 ael:0.002888042578697437 cl:26.145745202122537

filename: 1_hidden Epoch 158 loss:2.6175306859514826 ael:0.0028579513271021046 cl:26.146726883815344

filename: 1_hidden Epoch 159 loss:2.616915837613729 ael:0.002843602165374934 cl:26.140721854032854

filename: 1_hidden Epoch 160 loss:2.616314182266616 ael:0.002846391897651479 cl:26.134677416225678

filename: 1_hidden Epoch 161 loss:2.6167556381820702 ael:0.0028157920194150482 cl:26.139397996375788

filename: 1_hidden Epoch 162 loss:2.615687724320267 ael:0.002805819466867006 cl:26.12881854707477

filename: 1_hidden Epoch 163 loss:2.616142822093041 ael:0.002809583647183888 cl:26.13333191715425

filename: 1_hidden Epoch 164 loss:2.614972135615237 ael:0.0027870932983324608 cl:26.12184993726043

filename: 1_hidden Epoch 165 loss:2.614530597573695 ael:0.002779878711570548 cl:26.117506696132715

filename: 1_hidden Epoch 166 loss:2.613750776894937 ael:0.002767134568611866 cl:26.10983592076532

filename: 1_hidden Epoch 167 loss:2.6131484624562136 ael:0.0027699712461206403 cl:26.1037844094025

filename: 1_hidden Epoch 168 loss:2.612071730082567 ael:0.0027405886689648496 cl:26.093310925369142

filename: 1_hidden Epoch 169 loss:2.6123434138930346 ael:0.0027602302686742823 cl:26.09583133929605

filename: 1_hidden Epoch 170 loss:2.6122482996091083 ael:0.002748809409234818 cl:26.094994442920417

filename: 1_hidden Epoch 171 loss:2.6113978475936674 ael:0.0027332820868564193 cl:26.0866451846642

filename: 1_hidden Epoch 172 loss:2.610924323895792 ael:0.002753962383913559 cl:26.08170314378188

filename: 1_hidden Epoch 173 loss:2.610863543672606 ael:0.0027372019199433614 cl:26.081262945570924

filename: 1_hidden Epoch 174 loss:2.6103600943144323 ael:0.0027381736311157833 cl:26.076218719006327

filename: 1_hidden Epoch 175 loss:2.60992584511196 ael:0.0027443128007764864 cl:26.071814846806518

filename: 1_hidden Epoch 176 loss:2.609468503005791 ael:0.002733624685416216 cl:26.06734829871405

filename: 1_hidden Epoch 177 loss:2.608755622453139 ael:0.002739324517600389 cl:26.060162503485003

filename: 1_hidden Epoch 178 loss:2.609048974235047 ael:0.00273599013771176 cl:26.06312936434694

filename: 1_hidden Epoch 179 loss:2.608339696071821 ael:0.002725888694042279 cl:26.05613758545398

filename: 1_hidden Epoch 180 loss:2.6077931761183715 ael:0.0027287747450870305 cl:26.050643526336145

filename: 1_hidden Epoch 181 loss:2.607598106500325 ael:0.002727247952547523 cl:26.04870811200551

filename: 1_hidden Epoch 182 loss:2.607077535266251 ael:0.0027256676862917133 cl:26.043518236014474

filename: 1_hidden Epoch 183 loss:2.6071372159371697 ael:0.0027230238982559113 cl:26.044141452212042

filename: 1_hidden Epoch 184 loss:2.6058260430411875 ael:0.00271300921680089 cl:26.031129878694294

filename: 1_hidden Epoch 185 loss:2.6055685811779243 ael:0.0026985464393860094 cl:26.028699851073267

filename: 1_hidden Epoch 186 loss:2.6053807492189214 ael:0.002697237461003331 cl:26.026834610509056

filename: 1_hidden Epoch 187 loss:2.6051860825691877 ael:0.0027005774542535315 cl:26.024854591595773

filename: 1_hidden Epoch 188 loss:2.6048277151937977 ael:0.0026918593037861885 cl:26.021358076384214

filename: 1_hidden Epoch 189 loss:2.604294326933981 ael:0.0026828256041587398 cl:26.01611452801923

filename: 1_hidden Epoch 190 loss:2.605977135924579 ael:0.0026847605573888083 cl:26.03292326428775

filename: 1_hidden Epoch 191 loss:2.604169546237416 ael:0.0026669794415718007 cl:26.015025220088393

filename: 1_hidden Epoch 192 loss:2.6036057074244794 ael:0.0026735757343549506 cl:26.00932083129883

filename: 1_hidden Epoch 193 loss:2.603000085030257 ael:0.002658293166927203 cl:26.003417409935533

filename: 1_hidden Epoch 194 loss:2.603164086810512 ael:0.0026612449272473268 cl:26.00502793346292

filename: 1_hidden Epoch 195 loss:2.6024117266704065 ael:0.0026566015499790725 cl:25.997550764991416

filename: 1_hidden Epoch 196 loss:2.602378338324298 ael:0.0026439263209680243 cl:25.997343659066185

filename: 1_hidden Epoch 197 loss:2.602247352570342 ael:0.0026341676878032395 cl:25.996131389933332

filename: 1_hidden Epoch 198 loss:2.601225166424946 ael:0.002613445428089644 cl:25.986116717572145

filename: 1_hidden Epoch 199 loss:2.6012723476392057 ael:0.002606500997447791 cl:25.986658006450874

filename: 1_hidden Epoch 200 loss:2.60061918986197 ael:0.002590211973723181 cl:25.98028931402007

filename: 1_hidden Epoch 201 loss:2.6007906997073644 ael:0.0025801812075572483 cl:25.982104713570866

filename: 1_hidden Epoch 202 loss:2.6000884004762503 ael:0.0025794144562560363 cl:25.9750893603249

filename: 1_hidden Epoch 203 loss:2.6003032795910532 ael:0.0025739244496313252 cl:25.977293089511058

filename: 1_hidden Epoch 204 loss:2.5998193818209883 ael:0.0025519166191510984 cl:25.972674149916436

filename: 1_hidden Epoch 205 loss:2.6003374715677103 ael:0.0025652486383813244 cl:25.977721750196913

filename: 1_hidden Epoch 206 loss:2.5994304255278733 ael:0.0025278940744546943 cl:25.96902483614298

filename: 1_hidden Epoch 207 loss:2.5999122825688024 ael:0.0025475415029576087 cl:25.9736469239043

filename: 1_hidden Epoch 208 loss:2.5991264627429884 ael:0.0025338565601637462 cl:25.965925602905465

filename: 1_hidden Epoch 209 loss:2.600126042194932 ael:0.0025377451485043244 cl:25.9758825031346

filename: 1_hidden Epoch 210 loss:2.5985635517911865 ael:0.0025128788436078664 cl:25.960506255913078

filename: 1_hidden Epoch 211 loss:2.598945069499023 ael:0.002513042369867601 cl:25.964319789725792

filename: 1_hidden Epoch 212 loss:2.5989151625105076 ael:0.002497624223412548 cl:25.96417489014624

filename: 1_hidden Epoch 213 loss:2.5974661978098235 ael:0.00247669883363687 cl:25.9498945036842

filename: 1_hidden Epoch 214 loss:2.5983108238571333 ael:0.002495293182759675 cl:25.958154831289686

filename: 1_hidden Epoch 215 loss:2.597878023986697 ael:0.00248106235228537 cl:25.95396912168601

filename: 1_hidden Epoch 216 loss:2.597732437940172 ael:0.0024752414415920277 cl:25.95257150230467

filename: 1_hidden Epoch 217 loss:2.597454026336789 ael:0.0024472174358186596 cl:25.95006758619954

filename: 1_hidden Epoch 218 loss:2.5977184076948956 ael:0.0024456410201676134 cl:25.952727195513603

filename: 1_hidden Epoch 219 loss:2.596622791677109 ael:0.0024248046286523273 cl:25.941979370474257

filename: 1_hidden Epoch 220 loss:2.596789893047672 ael:0.0024314277400749383 cl:25.943584167194814

filename: 1_hidden Epoch 221 loss:2.5962613778999555 ael:0.002414419280485702 cl:25.93846908962113

filename: 1_hidden Epoch 222 loss:2.5960831098363104 ael:0.0024043652489447206 cl:25.93678697178405

filename: 1_hidden Epoch 223 loss:2.595510266240041 ael:0.002401345276510613 cl:25.931088734119434

filename: 1_hidden Epoch 224 loss:2.5956040159216536 ael:0.002377966263072853 cl:25.93226005447078

filename: 1_hidden Epoch 225 loss:2.595767527995355 ael:0.002383663411856616 cl:25.933838162593275

filename: 1_hidden Epoch 226 loss:2.595782420787722 ael:0.0023638375063881555 cl:25.934185391097284

filename: 1_hidden Epoch 227 loss:2.5958456595118817 ael:0.002358181058108086 cl:25.93487433315997

filename: 1_hidden Epoch 228 loss:2.595870970712623 ael:0.0023377708119068545 cl:25.935331496954337

filename: 1_hidden Epoch 229 loss:2.5954912220632043 ael:0.0023208844293469734 cl:25.931702878955

filename: 1_hidden Epoch 230 loss:2.595407519362832 ael:0.0023027471059282397 cl:25.931047227118576

filename: 1_hidden Epoch 231 loss:2.594516119681729 ael:0.002295446710140908 cl:25.92220624545807

filename: 1_hidden Epoch 232 loss:2.594988130370094 ael:0.0022814429834755296 cl:25.927066392943193

filename: 1_hidden Epoch 233 loss:2.5945979654695983 ael:0.0022641925576365263 cl:25.923337249636837

filename: 1_hidden Epoch 234 loss:2.5946135523910643 ael:0.002248163603997372 cl:25.923653423767565

filename: 1_hidden Epoch 235 loss:2.5943282619095442 ael:0.0022391547741696773 cl:25.9208905974342

filename: 1_hidden Epoch 236 loss:2.5941598262132235 ael:0.0022114131702458874 cl:25.91948363591282

filename: 1_hidden Epoch 237 loss:2.593845288206746 ael:0.0021883407067551093 cl:25.91656899712573

filename: 1_hidden Epoch 238 loss:2.594001581516355 ael:0.0021898889800463913 cl:25.91811644841282

filename: 1_hidden Epoch 239 loss:2.5931672104435295 ael:0.0021678174043861733 cl:25.90999345586006

filename: 1_hidden Epoch 240 loss:2.593160044049696 ael:0.0021560720505131854 cl:25.91003927329029

filename: 1_hidden Epoch 241 loss:2.593910645322755 ael:0.0021505305268213317 cl:25.917600690035293

filename: 1_hidden Epoch 242 loss:2.5934943504898857 ael:0.002132653431057372 cl:25.913616494641474

filename: 1_hidden Epoch 243 loss:2.592795695529527 ael:0.0021292541581808986 cl:25.906663945833348

filename: 1_hidden Epoch 244 loss:2.5936676201693913 ael:0.0021152314904702364 cl:25.915523428478032

filename: 1_hidden Epoch 245 loss:2.5933812324416805 ael:0.0021089038882090736 cl:25.91272281878824

filename: 1_hidden Epoch 246 loss:2.592562106172678 ael:0.0020876930773406407 cl:25.904743654010076

filename: 1_hidden Epoch 247 loss:2.593060944865163 ael:0.0020943120266521545 cl:25.909665842993583

filename: 1_hidden Epoch 248 loss:2.5928343680645116 ael:0.002075952570086313 cl:25.907583675890372

filename: 1_hidden Epoch 249 loss:2.593009552977944 ael:0.0020717913315409153 cl:25.909377110878502

filename: 1_hidden Epoch 250 loss:2.591470321515421 ael:0.0020476118668364637 cl:25.89422661696507

/tmp/ipykernel_739336/512526955.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
/tmp/ipykernel_739336/512526955.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3         4         5  Label
0        0.058388  0.061334  0.052688  0.059286  0.018206  0.056789      0
1        0.053023  0.021907  0.048774  0.056414  0.065297  0.022233      3
2        0.048704  0.058515  0.040151  0.043024  0.014153  0.056211      0
3        0.085507  0.081204  0.097371  0.103960  0.075657  0.045728      5
4        0.053023  0.021906  0.048773  0.056414  0.065294  0.022230      3
...           ...       ...       ...       ...       ...       ...    ...
1640803  0.045622  0.045222  0.064377  0.048756  0.071089  0.091958      2
1640804  0.053023  0.021908  0.048774  0.056414  0.065298  0.022234      3
1640805  0.053023  0.021907  0.048774  0.056414  0.065297  0.022233      3
1640806  0.053023  0.021907  0.048774  0.056414  0.065298  0.022234      3
1640807  0.053023  0.021936  0.048786  0.056409  0.065347  0.022279      3

[1640808 rows x 7 columns]

Davies-Bouldin Score: 1.8121724486195447

               0         1         2         3         4         5  Label
0       0.045873  0.045481  0.064604  0.049166  0.070915  0.091649      2
1       0.053027  0.021909  0.048786  0.056424  0.065306  0.022238      3
2       0.056866  0.061526  0.056227  0.059583  0.027283  0.057446      0
3       0.063447  0.098116  0.023033  0.032556  0.077840  0.045450      4
4       0.055863  0.061792  0.057420  0.058792  0.022750  0.056634      0
...          ...       ...       ...       ...       ...       ...    ...
519951  0.055251  0.061649  0.050665  0.055196  0.017390  0.056058      0
519952  0.085177  0.081428  0.101228  0.106954  0.077557  0.052935      5
519953  0.042423  0.042624  0.055057  0.048819  0.021929  0.078310      1
519954  0.057042  0.059628  0.053075  0.058165  0.023129  0.057145      0
519955  0.064187  0.096441  0.023569  0.034411  0.078200  0.044571      4

[519956 rows x 7 columns]

               0         1         2         3         4         5  Label
0       0.042392  0.042797  0.055168  0.048688  0.023354  0.078836      1
1       0.045308  0.044898  0.064096  0.048245  0.071309  0.092344      2
2       0.056807  0.060230  0.056812  0.060584  0.024277  0.057017      0
3       0.051356  0.054295  0.048205  0.050696  0.018832  0.059108      0
4       0.056940  0.050340  0.070786  0.066723  0.058604  0.060848      1
...          ...       ...       ...       ...       ...       ...    ...
649942  0.056217  0.061969  0.056903  0.058777  0.023097  0.055188      0
649943  0.058325  0.051064  0.073039  0.068674  0.060766  0.060577      1
649944  0.057610  0.050110  0.072318  0.067674  0.060891  0.060806      1
649945  0.063620  0.096664  0.024867  0.034103  0.076641  0.045543      4
649946  0.050497  0.016460  0.048173  0.054257  0.068257  0.019085      3

[649947 rows x 7 columns]