In [1]:
import torch
from torch import nn, optim
import torch.nn.functional as F
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.decomposition import PCA
from scipy.stats import chi2
from sklearn.mixture import GaussianMixture
from collections import deque, defaultdict

# CAE

In [2]:
train = pd.read_csv('../../../train_CADE_cod.csv')
val = pd.read_csv('../../../val_CADE_cod.csv')
test = pd.read_csv('../../../test_CADE_cod.csv')

In [3]:
classes_out = ['Infilteration','DoS attacks-SlowHTTPTest']
train = train.drop(index=train[train['Label'].isin(classes_out)].index)
val = val.drop(index=val[val['Label'].isin(classes_out)].index)
test = test.drop(index=test[test['Label'].isin(classes_out)].index)

# CAE CADE (margin 1 e lambda 1.0)

In [4]:
def pick_pair(embeddings, labels, pick_embeddings, pick_labels):
    """
    Gera todos os pares entre embeddings e pick_embeddings,
    com labels_pair indicando se os pares são positivos (0) ou negativos (1).
    """
    N, D = embeddings.shape
    M = pick_embeddings.shape[0]

    # Expande para todas as combinações possíveis
    A = embeddings.unsqueeze(0).expand(M, N, D).reshape(M * N, D)
    B = pick_embeddings.unsqueeze(1).expand(M, N, D).reshape(M * N, D)

    labels_exp = labels.unsqueeze(0).expand(M, N)
    pick_labels_exp = pick_labels.unsqueeze(1).expand(M, N)
    labels_pair = (labels_exp != pick_labels_exp).reshape(-1).float()

    return A, B, labels_pair

def ContrastiveLoss(input1, input2, y, margin=1.0):
    # y = 0 quando input1 e input2 são da mesma classe e y = 1 caso contrário
    diff = input1 - input2
    dist_sq = torch.sum(torch.pow(diff,2),1)
    dist = torch.sqrt(dist_sq + 1e-10) # Soma 1e-10 pois se o sqrt der 0 o gradiente da NaN
    mdist = margin - dist
    mdist = F.relu(mdist)
    loss = ((1-y) * dist * dist) + (y * mdist * mdist)
    return torch.mean(loss)

def AEContrastive(input, output, embeddings, labels, pick_encoded, pick_labels, margin=1.0, lambda1=1.0):
    mseloss = nn.MSELoss()
    ae_loss = mseloss(input,output)

    A, B, labels_pair = pick_pair(embeddings, labels, pick_encoded, pick_labels)
    contrastive_loss = ContrastiveLoss(A, B, labels_pair, margin=margin)
    return ae_loss + contrastive_loss * lambda1, ae_loss, contrastive_loss

In [5]:
class contrastive_ae(nn.Module):
    def __init__(self, input_neurons, neurons):
        super().__init__()
        self.encoder0 = nn.Linear(input_neurons,64)
        self.encoder1 = nn.Linear(64,32)
        self.encoder2 = nn.Linear(32,16)
        self.encoder3 = nn.Linear(16,neurons)

        self.decoder0 = nn.Linear(neurons,16)
        self.decoder1 = nn.Linear(16,32)
        self.decoder2 = nn.Linear(32,64)
        self.decoder3 = nn.Linear(64,input_neurons)

        self.activation0 = nn.ReLU()
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X)
        encoded = X
        X = self.activation0(self.decoder0(X))
        X = self.activation0(self.decoder1(X))
        X = self.activation0(self.decoder2(X))
        X = self.decoder3(X)


        return X, encoded

In [6]:
class encoder(nn.Module):
    def __init__(self, model):
        super().__init__()
        self.encoder0 = list(model.children())[0]
        self.encoder1 = list(model.children())[1]
        self.encoder2 = list(model.children())[2]
        self.encoder3 = list(model.children())[3]
        self.activation0 = list(model.children())[8]
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X)
        return X

In [7]:
from torch.utils.data import Dataset, DataLoader,TensorDataset
import random
def build_class_reference_batches(X_train, y_train, batch_size=512):
    classes = torch.unique(y_train).tolist()
    n_classes = len(classes)
    total_samples = len(X_train)
    dataset = TensorDataset(X_train, y_train)
    train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    

    print(classes)

    # Mapeia cada classe para seus índices
    class_to_indices = {
        int(cls.item()): (y_train == cls).nonzero(as_tuple=True)[0].tolist()
        for cls in torch.unique(y_train)
    }

    reference_list = []
    total_batches = len(train_loader)

    for batch_idx in range(total_batches):
        start = batch_idx * batch_size
        end = min(start + batch_size, total_samples)
        batch_indices = set(range(start, end))

        class_samples = []
        for cls in classes:
            candidates = [i for i in class_to_indices[cls] if i not in batch_indices]
            if not candidates:
                raise ValueError(f"Classe {cls} não possui amostras fora do batch {batch_idx}")
            chosen = candidates[torch.randint(len(candidates), (1,)).item()]
            class_samples.append(chosen)

        reference_list.append(class_samples)


    return train_loader, reference_list

In [8]:
def normalize(t):
    t_norm = (t - t.mean()) / t.std()
    return t_norm

In [9]:
# train['Label'] = train['Label'].replace('FTP-BruteForce','BruteForce')
train['Label'] = train['Label'].replace('SSH-Bruteforce','BruteForce')
train['Label'] = train['Label'].replace('DoS attacks-GoldenEye','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Slowloris','DoS')
## train['Label'] = train['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Hulk','DoS')
train['Label'] = train['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
train['Label'] = train['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
train['Label'] = train['Label'].replace('DDOS attack-HOIC','DDoS')
train['Label'] = train['Label'].replace('Brute Force -Web','Web')
train['Label'] = train['Label'].replace('Brute Force -XSS','Web')
train['Label'] = train['Label'].replace('SQL Injection','Web')


# val['Label'] = val['Label'].replace('FTP-BruteForce','BruteForce')
val['Label'] = val['Label'].replace('SSH-Bruteforce','BruteForce')
val['Label'] = val['Label'].replace('DoS attacks-GoldenEye','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Slowloris','DoS')
## val['Label'] = val['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Hulk','DoS')
val['Label'] = val['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
val['Label'] = val['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
val['Label'] = val['Label'].replace('DDOS attack-HOIC','DDoS')
val['Label'] = val['Label'].replace('Brute Force -Web','Web')
val['Label'] = val['Label'].replace('Brute Force -XSS','Web')
val['Label'] = val['Label'].replace('SQL Injection','Web')


# test['Label'] = test['Label'].replace('FTP-BruteForce','BruteForce')
test['Label'] = test['Label'].replace('SSH-Bruteforce','BruteForce')
test['Label'] = test['Label'].replace('DoS attacks-GoldenEye','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Slowloris','DoS')
## test['Label'] = test['Label'].replace('DoS attacks-SlowHTTPTest','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Hulk','DoS')
test['Label'] = test['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
test['Label'] = test['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
test['Label'] = test['Label'].replace('DDOS attack-HOIC','DDoS')
test['Label'] = test['Label'].replace('Brute Force -Web','Web')
test['Label'] = test['Label'].replace('Brute Force -XSS','Web')
test['Label'] = test['Label'].replace('SQL Injection','Web')

In [10]:
labels_str = [i for i in train['Label'].value_counts().index]
print(labels_str)

for i, l in enumerate(labels_str):
    train['Label'] = train['Label'].replace(l, i)
    val['Label'] = val['Label'].replace(l, i)
    test['Label'] = test['Label'].replace(l, i)

['DDoS', 'Benign', 'DoS', 'Bot', 'FTP-BruteForce', 'BruteForce', 'Web']

C:\Users\linco\AppData\Local\Temp\ipykernel_28140\2307520911.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train['Label'] = train['Label'].replace(l, i)
C:\Users\linco\AppData\Local\Temp\ipykernel_28140\2307520911.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  val['Label'] = val['Label'].replace(l, i)
C:\Users\linco\AppData\Local\Temp\ipykernel_28140\2307520911.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['Label'] = test['Label'].replace(l, i)

In [11]:
array_hidden_classes = [[4]]
filenames = ['4']
# array_hidden_classes = [[0]]
# filenames = ['0']
total_classes = len(labels_str)
for i in range(len(array_hidden_classes)):
    filename = f'{filenames[i]}_hidden'
    print(filename)
    hidden_classes = array_hidden_classes[i] #Classes ocultas do treinamento

    hidden_classes_index = list(train[train['Label'].isin(hidden_classes)].index)

    train_hidden = train.loc[hidden_classes_index]

    train_not_hidden = train.drop(hidden_classes_index)

    X_train = train_not_hidden.drop(columns=['Label'])
    y_train = train_not_hidden['Label']
    X_val = val.drop(columns=['Label'])
    y_val = val['Label'].values
    X_test = test.drop(columns=['Label'])
    y_test = test['Label'].values

    torch.manual_seed(123)
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(device)
    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_loader, pick_list = build_class_reference_batches(X_train,y_train, batch_size=512)
    pick_samples = []
    pick_labels = []
    for l in pick_list:
        pick_samples.append(X_train[l])
        pick_labels.append(y_train[l])

    pick_samples = torch.stack(pick_samples)    
    pick_labels = torch.stack(pick_labels)

    print('pick completo')

    neurons = total_classes - len(hidden_classes)
    print(f'{X_train.shape[1]} {neurons}')
    model = contrastive_ae(input_neurons=X_train.shape[1],neurons=neurons)
    model.to(device)

    learning_rate = 0.0001
    opt = optim.Adam(model.parameters(),lr=learning_rate)
    margin = 10 # Parametro de afastamento das classes
    cae_lambda_1 = 0.1 # Parametro de influencia na distancia das classes
    
    
    for epoch in range(250):
        running_loss = 0
        running_ael = 0
        running_cl = 0
        contador = 0
        for data in train_loader:
            inputs, labels = data
            inputs = inputs.to(device)
            labels = labels.to(device)
            ps = pick_samples[contador]
            pl = pick_labels[contador]
            ps = ps.to(device)
            pl = pl.to(device)
            contador += 1
            #print(f'{contador}/{len(train_loader)}')
            opt.zero_grad()
            outputs, encoded = model(inputs)
            _, pick_encoded = model(ps)
            tam_pe = pick_encoded.shape[0]
            enc_total = torch.cat((encoded,pick_encoded), dim=0)
            enc_total_norm = normalize(enc_total)
            encoded_norm = enc_total_norm[:-tam_pe]
            pick_encoded_norm = enc_total_norm[-tam_pe:]
            loss, ael, cl = AEContrastive(input=inputs, output=outputs, embeddings = encoded_norm, labels=labels, pick_encoded = pick_encoded_norm, pick_labels = pl, margin=margin, lambda1=cae_lambda_1)
            #loss = dummyMSELoss(inputs,outputs)
            loss.backward()
            opt.step()
            running_loss += loss.item()
            running_ael += ael.item()
            running_cl += cl.item()
            #print(f'loss = {loss.item()} batch_size = {size}')
        print(f'filename: {filename} Epoch {epoch+1} loss:{running_loss/len(train_loader)} ael:{running_ael/len(train_loader)} cl:{running_cl/len(train_loader)}')

    model_e = encoder(model=model)
    model_e.to(device)

    model_e.eval()

    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_encoded = model_e(X_train.to(device))

    train_encoded = train_encoded.detach().cpu().numpy()

    train_encoded_df = pd.DataFrame(train_encoded)
    train_encoded_df['Label'] = y_train.detach().cpu().numpy().astype(int)
    display(train_encoded_df)

    score = davies_bouldin_score(train_encoded_df.drop(columns=['Label']), train_encoded_df['Label'])
    print("Davies-Bouldin Score:", score)

    X_val = torch.tensor(np.array(X_val), dtype=torch.float)

    val_encoded = model_e(X_val.to(device))

    val_encoded = val_encoded.detach().cpu().numpy()

    val_encoded_df = pd.DataFrame(val_encoded)

    val_encoded_df['Label'] = y_val

    display(val_encoded_df)

    X_test = torch.tensor(np.array(X_test), dtype=torch.float)

    test_encoded = model_e(X_test.to(device))

    test_encoded = test_encoded.detach().cpu().numpy()

    test_encoded_df = pd.DataFrame(test_encoded)

    test_encoded_df['Label'] = y_test

    display(test_encoded_df)

    train_encoded_df.to_csv(f'train_encoded_CADE_cod_pick_class_squared_normalized_{filename}.csv',index=False)
    val_encoded_df.to_csv(f'val_encoded_CADE_cod_pick_class_squared_normalized_{filename}.csv',index=False)
    test_encoded_df.to_csv(f'test_encoded_CADE_cod_pick_class_squared_normalized_{filename}.csv',index=False)

4_hidden
cuda
[0.0, 1.0, 2.0, 3.0, 5.0, 6.0]
pick completo
82 6
filename: 4_hidden Epoch 1 loss:3.577476361383789 ael:0.023081608392781797 cl:35.54394693981132
filename: 4_hidden Epoch 2 loss:2.874998865437052 ael:0.016333046763622537 cl:28.586657734511256
filename: 4_hidden Epoch 3 loss:2.766831861556871 ael:0.016043988700923932 cl:27.507878254858245
filename: 4_hidden Epoch 4 loss:2.7060777777871734 ael:0.015275942057603178 cl:26.908017859100767
filename: 4_hidden Epoch 5 loss:2.6658738386378302 ael:0.014903312400802365 cl:26.50970478352375
filename: 4_hidden Epoch 6 loss:2.6356889894575826 ael:0.014725187111882851 cl:26.209637553303132
filename: 4_hidden Epoch 7 loss:2.611093209508014 ael:0.014400568887741504 cl:25.96692592727673
filename: 4_hidden Epoch 8 loss:2.5929220601920213 ael:0.013918082403334468 cl:25.790039298110717
filename: 4_hidden Epoch 9 loss:2.576215302529244 ael:0.01347543764981307 cl:25.62739818715762
filename: 4_hidden Epoch 10 loss:2.559596686829949 ael:0.013154708326508302 cl:25.464419315760438
filename: 4_hidden Epoch 11 loss:2.5463902053331338 ael:0.01289494126792378 cl:25.33495216249827
filename: 4_hidden Epoch 12 loss:2.535709759228768 ael:0.012678984436602593 cl:25.230307268303935
filename: 4_hidden Epoch 13 loss:2.525949757593959 ael:0.012536983590186016 cl:25.13412725772573
filename: 4_hidden Epoch 14 loss:2.5199844447208055 ael:0.012343032510297456 cl:25.076413636555756
filename: 4_hidden Epoch 15 loss:2.511818212790191 ael:0.012150931899630565 cl:24.996672348525628
filename: 4_hidden Epoch 16 loss:2.505773718055709 ael:0.011913737991434277 cl:24.938599313687543
filename: 4_hidden Epoch 17 loss:2.5006267090362893 ael:0.011672518648220836 cl:24.88954141282873
filename: 4_hidden Epoch 18 loss:2.4946295018908677 ael:0.011401726549856406 cl:24.8322772824992
filename: 4_hidden Epoch 19 loss:2.4902625092658908 ael:0.011177408304947798 cl:24.7908505377611
filename: 4_hidden Epoch 20 loss:2.4859729403758104 ael:0.0109290822643813 cl:24.75043810864638
filename: 4_hidden Epoch 21 loss:2.481726819106778 ael:0.010684712885985494 cl:24.710420564093912
filename: 4_hidden Epoch 22 loss:2.4761716402877973 ael:0.010463587228755728 cl:24.657080066544133
filename: 4_hidden Epoch 23 loss:2.472675561187343 ael:0.010176157606733943 cl:24.624993573118648
filename: 4_hidden Epoch 24 loss:2.468730953157151 ael:0.009883664023385594 cl:24.588472416250532
filename: 4_hidden Epoch 25 loss:2.466633300761283 ael:0.009647610444488778 cl:24.569856421044594
filename: 4_hidden Epoch 26 loss:2.4631184004139945 ael:0.009405444635995254 cl:24.53712905797931
filename: 4_hidden Epoch 27 loss:2.459963277009606 ael:0.009206322986618937 cl:24.507569077688185
filename: 4_hidden Epoch 28 loss:2.456684583926257 ael:0.008989983803386177 cl:24.476945530148395
filename: 4_hidden Epoch 29 loss:2.452918564827147 ael:0.008852971168939346 cl:24.44065544949062
filename: 4_hidden Epoch 30 loss:2.4498431005892223 ael:0.008659128381806583 cl:24.41183927027351
filename: 4_hidden Epoch 31 loss:2.4476795936872495 ael:0.00851807669921442 cl:24.391614692805792
filename: 4_hidden Epoch 32 loss:2.4456937804143486 ael:0.008361019534871734 cl:24.37332709800882
filename: 4_hidden Epoch 33 loss:2.4456214585312996 ael:0.008349413210874655 cl:24.37271998160112
filename: 4_hidden Epoch 34 loss:2.4422437525082556 ael:0.008192928870606098 cl:24.340507755913492
filename: 4_hidden Epoch 35 loss:2.4379544251566 ael:0.008101183113351257 cl:24.29853195533862
filename: 4_hidden Epoch 36 loss:2.4353675913729615 ael:0.008018694057191965 cl:24.273488470784844
filename: 4_hidden Epoch 37 loss:2.4326676602951367 ael:0.007914769522225676 cl:24.24752844007063
filename: 4_hidden Epoch 38 loss:2.43123329643553 ael:0.007822271838742295 cl:24.234109784695093
filename: 4_hidden Epoch 39 loss:2.427566163485601 ael:0.007694904200242307 cl:24.198712108585106
filename: 4_hidden Epoch 40 loss:2.425254091140769 ael:0.007558123850831809 cl:24.17695919876478
filename: 4_hidden Epoch 41 loss:2.4230213478827656 ael:0.00735355834083013 cl:24.156677415813334
filename: 4_hidden Epoch 42 loss:2.4206120181351984 ael:0.007242329411468942 cl:24.133696418069352
filename: 4_hidden Epoch 43 loss:2.4178179753946716 ael:0.007044737764581301 cl:24.107731879802625
filename: 4_hidden Epoch 44 loss:2.41499302559453 ael:0.00686368956948389 cl:24.08129288444529
filename: 4_hidden Epoch 45 loss:2.412787170879381 ael:0.006685963992221494 cl:24.061011596675694
filename: 4_hidden Epoch 46 loss:2.410571893794597 ael:0.0065540407911758095 cl:24.040178098281743
filename: 4_hidden Epoch 47 loss:2.4078189250032054 ael:0.006397403047259949 cl:24.014214728584278
filename: 4_hidden Epoch 48 loss:2.40450773133685 ael:0.006245031744949529 cl:23.982626478948447
filename: 4_hidden Epoch 49 loss:2.40188064440418 ael:0.006088444195688746 cl:23.95792153005792
filename: 4_hidden Epoch 50 loss:2.4000940114158325 ael:0.005957573677981806 cl:23.941363891485754
filename: 4_hidden Epoch 51 loss:2.3972510056981116 ael:0.005770697319225448 cl:23.914802602185407
filename: 4_hidden Epoch 52 loss:2.3951922329081756 ael:0.005592790418564084 cl:23.895993957279927
filename: 4_hidden Epoch 53 loss:2.3920753631127565 ael:0.0054519256252480545 cl:23.866233905551635
filename: 4_hidden Epoch 54 loss:2.389686417654527 ael:0.005284800777224947 cl:23.8440156995049
filename: 4_hidden Epoch 55 loss:2.3874887719387723 ael:0.005138247686266915 cl:23.823504781136492
filename: 4_hidden Epoch 56 loss:2.3855523810090897 ael:0.004965998515466244 cl:23.805863341746047
filename: 4_hidden Epoch 57 loss:2.384574265294099 ael:0.004794241458463228 cl:23.79779977107104
filename: 4_hidden Epoch 58 loss:2.3840463843466693 ael:0.004634716533827875 cl:23.79411619316686
filename: 4_hidden Epoch 59 loss:2.3812725268805472 ael:0.004500173473693148 cl:23.767723030583518
filename: 4_hidden Epoch 60 loss:2.37991027353447 ael:0.004363936058532479 cl:23.755462881096744
filename: 4_hidden Epoch 61 loss:2.378101909825141 ael:0.004284714220590876 cl:23.73817145889949
filename: 4_hidden Epoch 62 loss:2.3765281114675587 ael:0.004176255758535882 cl:23.72351808455626
filename: 4_hidden Epoch 63 loss:2.3753996009260097 ael:0.004112311436040817 cl:23.712872425569536
filename: 4_hidden Epoch 64 loss:2.3736325847138535 ael:0.00404814219993613 cl:23.695843953419903
filename: 4_hidden Epoch 65 loss:2.3722242122231836 ael:0.003987036190658429 cl:23.682371277797913
filename: 4_hidden Epoch 66 loss:2.371000681488778 ael:0.003942481419256796 cl:23.670581525110258
filename: 4_hidden Epoch 67 loss:2.3695911417703797 ael:0.003894617857393955 cl:23.656964771038137
filename: 4_hidden Epoch 68 loss:2.3683689029951176 ael:0.0038905871776243376 cl:23.644782698051493
filename: 4_hidden Epoch 69 loss:2.367409474342414 ael:0.003850375006238115 cl:23.63559053656132
filename: 4_hidden Epoch 70 loss:2.365707681834838 ael:0.0038156085409998147 cl:23.618920243619407
filename: 4_hidden Epoch 71 loss:2.364908255416353 ael:0.0037813917630140272 cl:23.61126819152353
filename: 4_hidden Epoch 72 loss:2.364404806695163 ael:0.0037548136662178032 cl:23.606499459037792
filename: 4_hidden Epoch 73 loss:2.362912578690086 ael:0.0037265704758635905 cl:23.591859604856225
filename: 4_hidden Epoch 74 loss:2.3621754433527817 ael:0.0037244664365827873 cl:23.584509301204328
filename: 4_hidden Epoch 75 loss:2.3618372431664967 ael:0.0036911435251130785 cl:23.581460513983743
filename: 4_hidden Epoch 76 loss:2.3603075987941398 ael:0.0036528799406822417 cl:23.566546713422962
filename: 4_hidden Epoch 77 loss:2.3602639553404017 ael:0.0036280439436963147 cl:23.566358625186858
filename: 4_hidden Epoch 78 loss:2.359634677236288 ael:0.0035969860029392954 cl:23.560376456569422
filename: 4_hidden Epoch 79 loss:2.358040913958975 ael:0.0035591788151957343 cl:23.54481688097365
filename: 4_hidden Epoch 80 loss:2.35749065757453 ael:0.0035500267719315182 cl:23.539405814267926
filename: 4_hidden Epoch 81 loss:2.3565762016480583 ael:0.0035215915497358295 cl:23.53054560431945
filename: 4_hidden Epoch 82 loss:2.3568977142809198 ael:0.00350519700237379 cl:23.53392468881495
filename: 4_hidden Epoch 83 loss:2.355290334844302 ael:0.003463422688059616 cl:23.518268655588788
filename: 4_hidden Epoch 84 loss:2.3541455103820046 ael:0.0034651402662513307 cl:23.506803208076338
filename: 4_hidden Epoch 85 loss:2.353917487252292 ael:0.0034486094297871903 cl:23.50468828739904
filename: 4_hidden Epoch 86 loss:2.351914410252934 ael:0.0034085451741672386 cl:23.485058127819823
filename: 4_hidden Epoch 87 loss:2.3517497335544775 ael:0.0033881024701739675 cl:23.48361584479445
filename: 4_hidden Epoch 88 loss:2.352109997848415 ael:0.0033653959687613972 cl:23.487445550762338
filename: 4_hidden Epoch 89 loss:2.351394706856858 ael:0.003349610939119825 cl:23.480450481683352
filename: 4_hidden Epoch 90 loss:2.3499346827374987 ael:0.003350738312591338 cl:23.46583897366757
filename: 4_hidden Epoch 91 loss:2.3495350525161416 ael:0.003330828633682948 cl:23.4620417520283
filename: 4_hidden Epoch 92 loss:2.3495729498075772 ael:0.0033227723939195605 cl:23.46250129426159
filename: 4_hidden Epoch 93 loss:2.348358701205759 ael:0.0033080101945968596 cl:23.450506432460134
filename: 4_hidden Epoch 94 loss:2.347531510815824 ael:0.003275824987491141 cl:23.442556367248677
filename: 4_hidden Epoch 95 loss:2.348217183930248 ael:0.003262075283938765 cl:23.44955064763077
filename: 4_hidden Epoch 96 loss:2.3473073643123064 ael:0.003253577151417428 cl:23.44053739404466
filename: 4_hidden Epoch 97 loss:2.3466651574444066 ael:0.0032319426866824932 cl:23.434331674283786
filename: 4_hidden Epoch 98 loss:2.3451753875966537 ael:0.0031957650895712343 cl:23.419795756376217
filename: 4_hidden Epoch 99 loss:2.345587594444856 ael:0.0031696319392034325 cl:23.424179155518953
filename: 4_hidden Epoch 100 loss:2.345799219605187 ael:0.0031594444407884777 cl:23.42639726969747
filename: 4_hidden Epoch 101 loss:2.345385172485026 ael:0.0031302801111078847 cl:23.4225484792614
filename: 4_hidden Epoch 102 loss:2.3439947362346696 ael:0.0031436940810982664 cl:23.408509992486174
filename: 4_hidden Epoch 103 loss:2.3442690290103125 ael:0.0031054645694608978 cl:23.411635177979697
filename: 4_hidden Epoch 104 loss:2.343527833194328 ael:0.0031120866084107203 cl:23.40415696416404
filename: 4_hidden Epoch 105 loss:2.342988830279131 ael:0.0030503806503193714 cl:23.399384019138363
filename: 4_hidden Epoch 106 loss:2.34325718087259 ael:0.0030346862081895554 cl:23.40222446159117
filename: 4_hidden Epoch 107 loss:2.342358109496146 ael:0.0030068018355715637 cl:23.393512602533793
filename: 4_hidden Epoch 108 loss:2.3419439313112833 ael:0.0029913115929846314 cl:23.38952573223658
filename: 4_hidden Epoch 109 loss:2.3404686829707475 ael:0.002960347310867569 cl:23.375082883557795
filename: 4_hidden Epoch 110 loss:2.340342847535324 ael:0.0029240767986388637 cl:23.37418723636758
filename: 4_hidden Epoch 111 loss:2.3407897165513605 ael:0.0028781527294432447 cl:23.379115147354778
filename: 4_hidden Epoch 112 loss:2.3400452943785406 ael:0.002846961303423233 cl:23.371982837528247
filename: 4_hidden Epoch 113 loss:2.340185596817484 ael:0.0028239283124223795 cl:23.373616219315657
filename: 4_hidden Epoch 114 loss:2.339405472382798 ael:0.002808804330504988 cl:23.365966209844906
filename: 4_hidden Epoch 115 loss:2.3390684005821667 ael:0.002755061733864006 cl:23.363132912586636
filename: 4_hidden Epoch 116 loss:2.339306935625094 ael:0.0027372454945010214 cl:23.36569643257738
filename: 4_hidden Epoch 117 loss:2.338101821056806 ael:0.0027192398965530814 cl:23.353825327302424
filename: 4_hidden Epoch 118 loss:2.33767776647122 ael:0.002652791257587195 cl:23.350249270249712
filename: 4_hidden Epoch 119 loss:2.3368786058011586 ael:0.002615723523850709 cl:23.342628342229887
filename: 4_hidden Epoch 120 loss:2.3372169074136155 ael:0.0026076658580377133 cl:23.346091934100272
filename: 4_hidden Epoch 121 loss:2.3403563247679164 ael:0.0026241200119639643 cl:23.37732159470551
filename: 4_hidden Epoch 122 loss:2.3378180541532947 ael:0.0025632349700571663 cl:23.352547741660082
filename: 4_hidden Epoch 123 loss:2.3367761284604307 ael:0.002535788668813152 cl:23.342402945136374
filename: 4_hidden Epoch 124 loss:2.3392974365072643 ael:0.002513963554840066 cl:23.36783422945807
filename: 4_hidden Epoch 125 loss:2.335016664270642 ael:0.002483293510849391 cl:23.325333240112688
filename: 4_hidden Epoch 126 loss:2.3358732525574166 ael:0.00246775947294635 cl:23.334054451717567
filename: 4_hidden Epoch 127 loss:2.3350426932961117 ael:0.002441636830851293 cl:23.326010092301257
filename: 4_hidden Epoch 128 loss:2.333738067954412 ael:0.0024193190822430935 cl:23.313186985945332
filename: 4_hidden Epoch 129 loss:2.3348680323126803 ael:0.002402060266130318 cl:23.324659257682633
filename: 4_hidden Epoch 130 loss:2.3332483103936084 ael:0.0024077064698077963 cl:23.308405551446167
filename: 4_hidden Epoch 131 loss:2.334940363929647 ael:0.002380497445961964 cl:23.325598197343993
filename: 4_hidden Epoch 132 loss:2.333186619414674 ael:0.002359822909736475 cl:23.308267474080903
filename: 4_hidden Epoch 133 loss:2.3318133948517543 ael:0.002349934535905635 cl:23.294634111449845
filename: 4_hidden Epoch 134 loss:2.3331364337389022 ael:0.002354572257353639 cl:23.307818136986437
filename: 4_hidden Epoch 135 loss:2.331709040924068 ael:0.00233462175438573 cl:23.293743697612957
filename: 4_hidden Epoch 136 loss:2.331424862544158 ael:0.0023352743866013738 cl:23.290895379672218
filename: 4_hidden Epoch 137 loss:2.3311871455870694 ael:0.0023182211716158974 cl:23.288688764494772
filename: 4_hidden Epoch 138 loss:2.33043492517369 ael:0.0023139569695962915 cl:23.28120922287295
filename: 4_hidden Epoch 139 loss:2.330276792475579 ael:0.0023054875486092368 cl:23.27971257766608
filename: 4_hidden Epoch 140 loss:2.330927506381696 ael:0.0023011045028460187 cl:23.28626354450145
filename: 4_hidden Epoch 141 loss:2.330904576454572 ael:0.0022931076872699475 cl:23.28611422471119
filename: 4_hidden Epoch 142 loss:2.3302052146756376 ael:0.002290736878699277 cl:23.279144310071437
filename: 4_hidden Epoch 143 loss:2.3293317591011506 ael:0.0023056058419317015 cl:23.270261076662873
filename: 4_hidden Epoch 144 loss:2.33077599957987 ael:0.002274279562700116 cl:23.285016738005066
filename: 4_hidden Epoch 145 loss:2.3280760686580377 ael:0.0022629982455726447 cl:23.258130243516536
filename: 4_hidden Epoch 146 loss:2.328074669001833 ael:0.00227090809174351 cl:23.258037160310842
filename: 4_hidden Epoch 147 loss:2.3281640417130944 ael:0.00225021344805402 cl:23.2591377928194
filename: 4_hidden Epoch 148 loss:2.327416756770212 ael:0.002260587696357489 cl:23.25156120653709
filename: 4_hidden Epoch 149 loss:2.326634655975915 ael:0.00224767647831935 cl:23.243869320755383
filename: 4_hidden Epoch 150 loss:2.3283326253938412 ael:0.0022376447346780983 cl:23.260949305794185
filename: 4_hidden Epoch 151 loss:2.326471190744593 ael:0.002218129733934203 cl:23.24253013938299
filename: 4_hidden Epoch 152 loss:2.326890053034016 ael:0.002226527838913387 cl:23.246634775105335
filename: 4_hidden Epoch 153 loss:2.326718241530106 ael:0.0022108907894153626 cl:23.24507304493341
filename: 4_hidden Epoch 154 loss:2.3263898726627796 ael:0.002226522777665107 cl:23.241633029609286
filename: 4_hidden Epoch 155 loss:2.327141231499677 ael:0.0021980789301025362 cl:23.249431065008046
filename: 4_hidden Epoch 156 loss:2.325761232567033 ael:0.0021936411804414054 cl:23.23567544786882
filename: 4_hidden Epoch 157 loss:2.325690163801054 ael:0.00220159598903692 cl:23.23488522199897
filename: 4_hidden Epoch 158 loss:2.324021221361557 ael:0.0021839509604477296 cl:23.218372227165343
filename: 4_hidden Epoch 159 loss:2.3246571828919036 ael:0.0021855652221283287 cl:23.22471568784736
filename: 4_hidden Epoch 160 loss:2.3238613994231994 ael:0.0021765913366559708 cl:23.216847636630416
filename: 4_hidden Epoch 161 loss:2.324727502583022 ael:0.00217152433299275 cl:23.225559300510273
filename: 4_hidden Epoch 162 loss:2.323785396497058 ael:0.002158889869364255 cl:23.21626458146815
filename: 4_hidden Epoch 163 loss:2.324479525671427 ael:0.0021618963123862947 cl:23.223175820053886
filename: 4_hidden Epoch 164 loss:2.323138403349664 ael:0.002104206349799647 cl:23.21034151719709
filename: 4_hidden Epoch 165 loss:2.3231279553308815 ael:0.0021124420023614183 cl:23.210154626482414
filename: 4_hidden Epoch 166 loss:2.3228919955954694 ael:0.0021150849286544347 cl:23.207768642662145
filename: 4_hidden Epoch 167 loss:2.3219842137044964 ael:0.0021433229279699275 cl:23.19840843082878
filename: 4_hidden Epoch 168 loss:2.3219274190420007 ael:0.0021153290795836986 cl:23.198120448140692
filename: 4_hidden Epoch 169 loss:2.321395811064959 ael:0.0021313426126678445 cl:23.192644202125788
filename: 4_hidden Epoch 170 loss:2.321646312492988 ael:0.0020991459150560485 cl:23.19547120128992
filename: 4_hidden Epoch 171 loss:2.321627123385192 ael:0.002069965053242001 cl:23.19557113667428
filename: 4_hidden Epoch 172 loss:2.320666878487358 ael:0.002064779102977768 cl:23.18602052043165
filename: 4_hidden Epoch 173 loss:2.3207836370448174 ael:0.002087294163582839 cl:23.186962945334606
filename: 4_hidden Epoch 174 loss:2.320619863229595 ael:0.0020903152515975238 cl:23.185294999155314
filename: 4_hidden Epoch 175 loss:2.319960393290406 ael:0.0020508906350733586 cl:23.179094554179315
filename: 4_hidden Epoch 176 loss:2.320273715580549 ael:0.0021147834929778737 cl:23.181588888979494
filename: 4_hidden Epoch 177 loss:2.3207796313506215 ael:0.0020406394087602486 cl:23.18738944915476
filename: 4_hidden Epoch 178 loss:2.3202733821626795 ael:0.0020217296307396123 cl:23.182516022147823
filename: 4_hidden Epoch 179 loss:2.320990060237464 ael:0.0020166795213129862 cl:23.189733336527787
filename: 4_hidden Epoch 180 loss:2.319337748414214 ael:0.0020131417646423056 cl:23.173245587482466
filename: 4_hidden Epoch 181 loss:2.3187444508933672 ael:0.0020483437919727454 cl:23.166960609174467
filename: 4_hidden Epoch 182 loss:2.318080159358035 ael:0.0019900571832821372 cl:23.160900539766583
filename: 4_hidden Epoch 183 loss:2.3178656184526676 ael:0.001997488722677039 cl:23.158680816247056
filename: 4_hidden Epoch 184 loss:2.317790317928501 ael:0.001991794293533569 cl:23.1579847727668
filename: 4_hidden Epoch 185 loss:2.31685990146616 ael:0.001985238980976204 cl:23.14874614005749
filename: 4_hidden Epoch 186 loss:2.3176899234589032 ael:0.0019929521855818013 cl:23.156969257126114
filename: 4_hidden Epoch 187 loss:2.317846084071591 ael:0.0019542294925442407 cl:23.158918067754424
filename: 4_hidden Epoch 188 loss:2.317171964181153 ael:0.001969289571041711 cl:23.152026266054595
filename: 4_hidden Epoch 189 loss:2.317495243987997 ael:0.0019437920159444085 cl:23.155514027491442
filename: 4_hidden Epoch 190 loss:2.317805582270888 ael:0.0019484600783451257 cl:23.15857076208119
filename: 4_hidden Epoch 191 loss:2.316076007540767 ael:0.0019536156136212538 cl:23.14122344024267
filename: 4_hidden Epoch 192 loss:2.3170187923802783 ael:0.0019275520576185576 cl:23.150911912715923
filename: 4_hidden Epoch 193 loss:2.3168077987702347 ael:0.0019415345504705435 cl:23.148662199745687
filename: 4_hidden Epoch 194 loss:2.316161508492792 ael:0.0019027071583947108 cl:23.142587524969144
filename: 4_hidden Epoch 195 loss:2.3163102414401466 ael:0.0024621902170240805 cl:23.13848002997096
filename: 4_hidden Epoch 196 loss:2.3151582564024737 ael:0.0018827706427383827 cl:23.132754384020615
filename: 4_hidden Epoch 197 loss:2.3161464185185596 ael:0.0018906795533212598 cl:23.142556943995764
filename: 4_hidden Epoch 198 loss:2.3156214678546454 ael:0.0018936518880554973 cl:23.1372776780257
filename: 4_hidden Epoch 199 loss:2.3152552795672223 ael:0.0019100664953221765 cl:23.133451661462093
filename: 4_hidden Epoch 200 loss:2.3149395226745884 ael:0.0018840061351196248 cl:23.130554691405546
filename: 4_hidden Epoch 201 loss:2.3142687141255727 ael:0.0018405496830206478 cl:23.124281164676972

C:\Users\linco\AppData\Local\Temp\ipykernel_28140\1107826620.py:91: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
C:\Users\linco\AppData\Local\Temp\ipykernel_28140\1107826620.py:92: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3         4         5  Label
0       -0.106511 -0.109068 -0.112569 -0.086488 -0.112245 -0.123412      1
1       -0.095923 -0.109047 -0.105694 -0.121957 -0.113417 -0.113334      0
2       -0.123811 -0.128635 -0.097208 -0.105406 -0.122317 -0.084611      2
3       -0.108369 -0.110364 -0.111645 -0.087387 -0.114997 -0.128459      1
4       -0.134426 -0.072776 -0.105382 -0.117417 -0.076523 -0.095585      3
...           ...       ...       ...       ...       ...       ...    ...
1956103 -0.095934 -0.109100 -0.105680 -0.121997 -0.113463 -0.113291      0
1956104 -0.123811 -0.128635 -0.097208 -0.105407 -0.122317 -0.084610      2
1956105 -0.123810 -0.128635 -0.097208 -0.105408 -0.122317 -0.084610      2
1956106 -0.095917 -0.109018 -0.105702 -0.121935 -0.113392 -0.113357      0
1956107 -0.123770 -0.128623 -0.097198 -0.105484 -0.122299 -0.084592      2

[1956108 rows x 7 columns]

Davies-Bouldin Score: 0.9828334312436269

               0         1         2         3         4         5  Label
0      -0.095593 -0.108841 -0.105989 -0.122638 -0.114371 -0.112754      0
1      -0.123811 -0.128635 -0.097210 -0.105405 -0.122318 -0.084614      2
2      -0.106645 -0.108197 -0.112081 -0.086577 -0.110937 -0.124059      1
3      -0.131497 -0.136968 -0.167269 -0.128487 -0.091215 -0.114995      5
4      -0.107317 -0.107452 -0.113135 -0.084627 -0.112027 -0.123610      1
...          ...       ...       ...       ...       ...       ...    ...
519951 -0.107012 -0.106576 -0.113014 -0.082822 -0.110010 -0.125108      1
519952 -0.131649 -0.074144 -0.106688 -0.116322 -0.078558 -0.096216      3
519953 -0.095932 -0.109086 -0.105683 -0.121987 -0.113452 -0.113302      0
519954 -0.105841 -0.107900 -0.112870 -0.085952 -0.111604 -0.125307      1
519955 -0.131209 -0.135127 -0.164500 -0.129553 -0.095288 -0.114662      5

[519956 rows x 7 columns]

               0         1         2         3         4         5  Label
0      -0.095924 -0.109053 -0.105693 -0.121961 -0.113422 -0.113330      0
1      -0.095617 -0.108911 -0.105945 -0.122714 -0.114433 -0.112630      0
2      -0.106167 -0.107958 -0.112025 -0.088941 -0.110943 -0.122717      1
3      -0.109894 -0.109920 -0.112270 -0.087667 -0.113533 -0.121117      1
4      -0.096328 -0.108698 -0.105673 -0.121476 -0.113834 -0.113081      0
...          ...       ...       ...       ...       ...       ...    ...
649942 -0.107497 -0.107480 -0.112908 -0.084326 -0.111918 -0.123516      1
649943 -0.096803 -0.109163 -0.105620 -0.121223 -0.114244 -0.112663      0
649944 -0.096619 -0.108996 -0.105636 -0.121412 -0.114105 -0.112783      0
649945 -0.136563 -0.156444 -0.096437 -0.073392 -0.145051 -0.082622      4
649946 -0.124071 -0.129206 -0.098029 -0.106670 -0.123048 -0.083408      2

[649947 rows x 7 columns]