# 1 class hidden

## Import libraries

In [1]:
import torch
from torch import nn, optim
import torch.nn.functional as F
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import davies_bouldin_score
from sklearn.decomposition import PCA
from scipy.stats import chi2
from sklearn.mixture import GaussianMixture
from collections import deque, defaultdict

# Import training, validation and test data

In [2]:
train = pd.read_csv('../train.csv')
val = pd.read_csv('../val.csv')
test = pd.read_csv('../test.csv')

'Infilteration' and 'DoS attacks-SlowHTTPTest' classes were aparently mislabeled, so we will exclude them, remaining 12 attack classes

In [3]:
classes_out = ['Infilteration','DoS attacks-SlowHTTPTest']
train = train.drop(index=train[train['Label'].isin(classes_out)].index)
val = val.drop(index=val[val['Label'].isin(classes_out)].index)
test = test.drop(index=test[test['Label'].isin(classes_out)].index)

11 attack classes will be joined into major attack classes
* FTP-BruteForce and SSH-Bruteforce -> BruteForce
* DoS attacks-GoldenEye, DoS attacks-Slowloris and DoS attacks-Hulk -> DoS
* DDoS attacks-LOIC-HTTP, DDOS attack-LOIC-UDP and DDOS attack-HOIC -> DDoS
* Brute Force -Web, Brute Force -XSS and SQL Injection -> DDoS

Resulting in 5 major attack classes: BruteForce, DoS, DDoS, Web and Bot, and Benign class

In [4]:
train['Label'] = train['Label'].replace('FTP-BruteForce','BruteForce')
train['Label'] = train['Label'].replace('SSH-Bruteforce','BruteForce')
train['Label'] = train['Label'].replace('DoS attacks-GoldenEye','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Slowloris','DoS')
train['Label'] = train['Label'].replace('DoS attacks-Hulk','DoS')
train['Label'] = train['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
train['Label'] = train['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
train['Label'] = train['Label'].replace('DDOS attack-HOIC','DDoS')
train['Label'] = train['Label'].replace('Brute Force -Web','Web')
train['Label'] = train['Label'].replace('Brute Force -XSS','Web')
train['Label'] = train['Label'].replace('SQL Injection','Web')


val['Label'] = val['Label'].replace('FTP-BruteForce','BruteForce')
val['Label'] = val['Label'].replace('SSH-Bruteforce','BruteForce')
val['Label'] = val['Label'].replace('DoS attacks-GoldenEye','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Slowloris','DoS')
val['Label'] = val['Label'].replace('DoS attacks-Hulk','DoS')
val['Label'] = val['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
val['Label'] = val['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
val['Label'] = val['Label'].replace('DDOS attack-HOIC','DDoS')
val['Label'] = val['Label'].replace('Brute Force -Web','Web')
val['Label'] = val['Label'].replace('Brute Force -XSS','Web')
val['Label'] = val['Label'].replace('SQL Injection','Web')


test['Label'] = test['Label'].replace('FTP-BruteForce','BruteForce')
test['Label'] = test['Label'].replace('SSH-Bruteforce','BruteForce')
test['Label'] = test['Label'].replace('DoS attacks-GoldenEye','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Slowloris','DoS')
test['Label'] = test['Label'].replace('DoS attacks-Hulk','DoS')
test['Label'] = test['Label'].replace('DDoS attacks-LOIC-HTTP','DDoS')
test['Label'] = test['Label'].replace('DDOS attack-LOIC-UDP','DDoS')
test['Label'] = test['Label'].replace('DDOS attack-HOIC','DDoS')
test['Label'] = test['Label'].replace('Brute Force -Web','Web')
test['Label'] = test['Label'].replace('Brute Force -XSS','Web')
test['Label'] = test['Label'].replace('SQL Injection','Web')

## Labels into numeric

In [5]:
labels_str = [i for i in train['Label'].value_counts().index]
print(labels_str)

for i, l in enumerate(labels_str):
    train['Label'] = train['Label'].replace(l, i)
    val['Label'] = val['Label'].replace(l, i)
    test['Label'] = test['Label'].replace(l, i)

['DDoS', 'Benign', 'DoS', 'BruteForce', 'Bot', 'Web']

C:\Users\Lincoln\AppData\Local\Temp\ipykernel_8000\2307520911.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train['Label'] = train['Label'].replace(l, i)
C:\Users\Lincoln\AppData\Local\Temp\ipykernel_8000\2307520911.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  val['Label'] = val['Label'].replace(l, i)
C:\Users\Lincoln\AppData\Local\Temp\ipykernel_8000\2307520911.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['Label'] = test['Label'].replace(l, i)

## Contrastive AutoEncoder Functions

<img src="..\img\contrastive_pairs.png" alt="Contrastive Pairs" width="60%"/>

In [6]:
def pick_pair(embeddings, labels, pick_embeddings, pick_labels):
    """
    Generates all pairs between embeddings (batch) and pick_embeddings (reference samples), with labels_pair indicating whether the pairs are positive (0) or negative (1). 
    """
    N, D = embeddings.shape
    M = pick_embeddings.shape[0]

    # Expands to all possible combinations
    A = embeddings.unsqueeze(0).expand(M, N, D).reshape(M * N, D)
    B = pick_embeddings.unsqueeze(1).expand(M, N, D).reshape(M * N, D)

    labels_exp = labels.unsqueeze(0).expand(M, N)
    pick_labels_exp = pick_labels.unsqueeze(1).expand(M, N)
    labels_pair = (labels_exp != pick_labels_exp).reshape(-1).float()

    return A, B, labels_pair

def ContrastiveLoss(input1, input2, y, margin=1.0):
    # y = 0 when input1 and input2 belong to the same class, and y = 1 otherwise.
    diff = input1 - input2
    dist_sq = torch.sum(torch.pow(diff,2),1)
    dist = torch.sqrt(dist_sq + 1e-10) # "Adds 1e-10 because if the sqrt is 0, the gradient becomes NaN.
    mdist = margin - dist
    mdist = F.relu(mdist)
    loss = ((1-y) * dist * dist) + (y * mdist * mdist)
    return torch.mean(loss)

def AEContrastive(input, output, embeddings, labels, pick_encoded, pick_labels, margin=1.0, lambda1=1.0):
    mseloss = nn.MSELoss()
    ae_loss = mseloss(input,output)

    A, B, labels_pair = pick_pair(embeddings, labels, pick_encoded, pick_labels)
    contrastive_loss = ContrastiveLoss(A, B, labels_pair, margin=margin)
    return ae_loss + contrastive_loss * lambda1, ae_loss, contrastive_loss

In [7]:
class contrastive_ae(nn.Module):
    def __init__(self, input_neurons, neurons):
        super().__init__()
        self.encoder0 = nn.Linear(input_neurons,64)
        self.encoder1 = nn.Linear(64,32)
        self.encoder2 = nn.Linear(32,16)
        self.encoder3 = nn.Linear(16,neurons)

        self.decoder0 = nn.Linear(neurons,16)
        self.decoder1 = nn.Linear(16,32)
        self.decoder2 = nn.Linear(32,64)
        self.decoder3 = nn.Linear(64,input_neurons)

        self.activation0 = nn.ReLU()
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X) # No activation function
        encoded = X
        X = self.activation0(self.decoder0(X))
        X = self.activation0(self.decoder1(X))
        X = self.activation0(self.decoder2(X))
        X = self.decoder3(X) # No activation function


        return X, encoded

In [8]:
class encoder(nn.Module):
    def __init__(self, model):
        super().__init__()
        self.encoder0 = list(model.children())[0]
        self.encoder1 = list(model.children())[1]
        self.encoder2 = list(model.children())[2]
        self.encoder3 = list(model.children())[3]
        self.activation0 = list(model.children())[8]
    
    def forward(self, X):
        X = self.activation0(self.encoder0(X))
        X = self.activation0(self.encoder1(X))
        X = self.activation0(self.encoder2(X))
        X = self.encoder3(X)
        return X

In [9]:
from torch.utils.data import Dataset, DataLoader,TensorDataset
import random

# Prepare reference samples for each batch

def build_class_reference_batches(X_train, y_train, batch_size=512):
    classes = torch.unique(y_train).tolist()
    n_classes = len(classes)
    total_samples = len(X_train)
    dataset = TensorDataset(X_train, y_train)
    train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    

    print(classes)

    # Maps each class to its indices
    class_to_indices = {
        int(cls.item()): (y_train == cls).nonzero(as_tuple=True)[0].tolist()
        for cls in torch.unique(y_train)
    }

    reference_list = []
    total_batches = len(train_loader)

    for batch_idx in range(total_batches):
        start = batch_idx * batch_size
        end = min(start + batch_size, total_samples)
        batch_indices = set(range(start, end))

        class_samples = []
        for cls in classes:
            candidates = [i for i in class_to_indices[cls] if i not in batch_indices]
            if not candidates:
                raise ValueError(f"Class {cls} has no samples outside of batch {batch_idx}")
            chosen = candidates[torch.randint(len(candidates), (1,)).item()]
            class_samples.append(chosen)

        reference_list.append(class_samples)


    return train_loader, reference_list

In [10]:
# Normalization function

def normalize(t):
    t_norm = (t - t.mean()) / t.std()
    return t_norm

In [12]:
array_hidden_classes = [[0],[2],[3],[4],[5]] # Class 1 correspond to benign class
filenames = ['0','2','3','4','5']

total_classes = len(labels_str)
for i in range(len(array_hidden_classes)):
    filename = f'{filenames[i]}_hidden'
    print(filename)
    hidden_classes = array_hidden_classes[i] # Classes hidden from training

    hidden_classes_index = list(train[train['Label'].isin(hidden_classes)].index)

    train_hidden = train.loc[hidden_classes_index]

    train_not_hidden = train.drop(hidden_classes_index)

    X_train = train_not_hidden.drop(columns=['Label'])
    y_train = train_not_hidden['Label']
    X_val = val.drop(columns=['Label'])
    y_val = val['Label'].values
    X_test = test.drop(columns=['Label'])
    y_test = test['Label'].values

    torch.manual_seed(123)
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(device)
    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_loader, pick_list = build_class_reference_batches(X_train,y_train, batch_size=512)
    pick_samples = []
    pick_labels = []
    for l in pick_list:
        pick_samples.append(X_train[l])
        pick_labels.append(y_train[l])

    pick_samples = torch.stack(pick_samples)    
    pick_labels = torch.stack(pick_labels)


    neurons = total_classes - len(hidden_classes)
    print(f'{X_train.shape[1]} {neurons}')
    model = contrastive_ae(input_neurons=X_train.shape[1],neurons=neurons)
    model.to(device)

    learning_rate = 0.0001
    opt = optim.Adam(model.parameters(),lr=learning_rate)
    margin = 10 # Class separation parameter
    cae_lambda_1 = 1.0 # Contrastive learning weight 
    
    
    for epoch in range(250):
        running_loss = 0
        running_ael = 0
        running_cl = 0
        counter = 0
        for data in train_loader:
            inputs, labels = data
            inputs = inputs.to(device)
            labels = labels.to(device)
            ps = pick_samples[counter]
            pl = pick_labels[counter]
            ps = ps.to(device)
            pl = pl.to(device)
            counter += 1
            opt.zero_grad()
            outputs, encoded = model(inputs)
            _, pick_encoded = model(ps)
            tam_pe = pick_encoded.shape[0]
            enc_total = torch.cat((encoded,pick_encoded), dim=0)
            enc_total_norm = normalize(enc_total)
            encoded_norm = enc_total_norm[:-tam_pe]
            pick_encoded_norm = enc_total_norm[-tam_pe:]
            loss, ael, cl = AEContrastive(input=inputs, output=outputs, embeddings = encoded_norm, labels=labels, pick_encoded = pick_encoded_norm, pick_labels = pl, margin=margin, lambda1=cae_lambda_1)
            loss.backward()
            opt.step()
            running_loss += loss.item()
            running_ael += ael.item()
            running_cl += cl.item()
        print(f'filename: {filename} Epoch {epoch+1} loss:{running_loss/len(train_loader)} ael:{running_ael/len(train_loader)} cl:{running_cl/len(train_loader)}')

    model_e = encoder(model=model)
    model_e.to(device)

    model_e.eval()

    X_train = torch.tensor(np.array(X_train), dtype=torch.float)
    y_train = torch.tensor(np.array(y_train), dtype=torch.float)

    train_encoded = model_e(X_train.to(device))

    train_encoded = train_encoded.detach().cpu().numpy()

    train_encoded_df = pd.DataFrame(train_encoded)
    train_encoded_df['Label'] = y_train.detach().cpu().numpy().astype(int)
    display(train_encoded_df)

    X_val = torch.tensor(np.array(X_val), dtype=torch.float)

    val_encoded = model_e(X_val.to(device))

    val_encoded = val_encoded.detach().cpu().numpy()

    val_encoded_df = pd.DataFrame(val_encoded)

    val_encoded_df['Label'] = y_val

    display(val_encoded_df)

    X_test = torch.tensor(np.array(X_test), dtype=torch.float)

    test_encoded = model_e(X_test.to(device))

    test_encoded = test_encoded.detach().cpu().numpy()

    test_encoded_df = pd.DataFrame(test_encoded)

    test_encoded_df['Label'] = y_test

    display(test_encoded_df)

    train_encoded_df.to_csv(f'train_encoded_{filename}.csv',index=False)
    val_encoded_df.to_csv(f'val_encoded_{filename}.csv',index=False)
    test_encoded_df.to_csv(f'test_encoded_{filename}.csv',index=False)

0_hidden
cpu
[1.0, 2.0, 3.0, 4.0, 5.0]
82 5
filename: 0_hidden Epoch 1 loss:36.52888587171206 ael:0.028588073376522662 cl:36.500297817548244
filename: 0_hidden Epoch 2 loss:30.48726175871291 ael:0.017529986894408565 cl:30.469731782167322
filename: 0_hidden Epoch 3 loss:29.772329462568365 ael:0.017433226702677065 cl:29.754896247670192
filename: 0_hidden Epoch 4 loss:29.262142682238736 ael:0.0169204438526815 cl:29.245222233784954
filename: 0_hidden Epoch 5 loss:28.852165898151373 ael:0.016021811215044195 cl:28.83614410741455
filename: 0_hidden Epoch 6 loss:28.551514877122685 ael:0.015354266972703003 cl:28.53616062384001
filename: 0_hidden Epoch 7 loss:28.30608706449339 ael:0.014745508444405855 cl:28.291341557312627
filename: 0_hidden Epoch 8 loss:28.1163141494118 ael:0.01400754875171535 cl:28.10230661638792
filename: 0_hidden Epoch 9 loss:28.00462423578847 ael:0.013790540241884263 cl:27.990833682683604
filename: 0_hidden Epoch 10 loss:27.87828168511823 ael:0.013794924676391299 cl:27.86448677576121
filename: 0_hidden Epoch 11 loss:27.782110762701752 ael:0.013795095353349413 cl:27.76831565439053
filename: 0_hidden Epoch 12 loss:27.70221292554876 ael:0.013733593703885617 cl:27.688479313291563
filename: 0_hidden Epoch 13 loss:27.633748124023143 ael:0.013638409246561919 cl:27.620109704824593
filename: 0_hidden Epoch 14 loss:27.566101275477447 ael:0.013510250620336913 cl:27.552591017355518
filename: 0_hidden Epoch 15 loss:27.509475680353948 ael:0.013371808647935399 cl:27.496103852879266
filename: 0_hidden Epoch 16 loss:27.450350864731494 ael:0.013266550858988547 cl:27.43708430784535
filename: 0_hidden Epoch 17 loss:27.414625931400664 ael:0.013209360670425866 cl:27.401416560406172
filename: 0_hidden Epoch 18 loss:27.3704206387554 ael:0.01305258102742021 cl:27.357368067489052
filename: 0_hidden Epoch 19 loss:27.343677282621435 ael:0.01292414948129685 cl:27.330753136679764
filename: 0_hidden Epoch 20 loss:27.3206165319866 ael:0.012878990214523581 cl:27.307737532518487
filename: 0_hidden Epoch 21 loss:27.27833117125162 ael:0.012804762449038998 cl:27.265526410124735
filename: 0_hidden Epoch 22 loss:27.248310324169193 ael:0.012660356603061725 cl:27.23564998382433
filename: 0_hidden Epoch 23 loss:27.21809109823386 ael:0.012658367142009245 cl:27.205432768171466
filename: 0_hidden Epoch 24 loss:27.198630864899627 ael:0.01255311518667496 cl:27.186077750118038
filename: 0_hidden Epoch 25 loss:27.14346453973568 ael:0.01258500849177736 cl:27.13087955387283
filename: 0_hidden Epoch 26 loss:27.105982527346846 ael:0.012538040359888978 cl:27.093444474704604
filename: 0_hidden Epoch 27 loss:27.078887337981527 ael:0.012562348463085333 cl:27.066325010621544
filename: 0_hidden Epoch 28 loss:27.05197198171074 ael:0.012470985510721472 cl:27.039501000449295
filename: 0_hidden Epoch 29 loss:27.0189660295478 ael:0.012526631220632078 cl:27.006439411011232
filename: 0_hidden Epoch 30 loss:27.005750800542568 ael:0.012486629003521611 cl:26.993264186396697
filename: 0_hidden Epoch 31 loss:26.994189757471165 ael:0.012525040220860819 cl:26.98166473440907
filename: 0_hidden Epoch 32 loss:26.962555145958092 ael:0.012473745850311307 cl:26.950081383178563
filename: 0_hidden Epoch 33 loss:26.94004617138731 ael:0.012441608962534274 cl:26.92760454316894
filename: 0_hidden Epoch 34 loss:26.92293102819018 ael:0.01244113316622188 cl:26.910489883914476
filename: 0_hidden Epoch 35 loss:26.92101971890914 ael:0.012496124211124148 cl:26.90852361871886
filename: 0_hidden Epoch 36 loss:26.885863696285377 ael:0.012430489148406002 cl:26.87343320258913
filename: 0_hidden Epoch 37 loss:26.868128981265723 ael:0.012437535208686316 cl:26.855691420470233
filename: 0_hidden Epoch 38 loss:26.858185869140872 ael:0.012445036662075604 cl:26.84574083719242
filename: 0_hidden Epoch 39 loss:26.842497933549456 ael:0.01243390408624001 cl:26.830064023064356
filename: 0_hidden Epoch 40 loss:26.819481549702775 ael:0.012451054732773964 cl:26.807030503806498
filename: 0_hidden Epoch 41 loss:26.807968668912718 ael:0.012356007093600433 cl:26.795612653992706
filename: 0_hidden Epoch 42 loss:26.796054410684796 ael:0.012361281275362124 cl:26.78369312386238
filename: 0_hidden Epoch 43 loss:26.78161933966524 ael:0.012283517539492188 cl:26.76933584163326
filename: 0_hidden Epoch 44 loss:26.75779492289512 ael:0.012373676005581358 cl:26.745421260199237
filename: 0_hidden Epoch 45 loss:26.749268225686375 ael:0.012297998953264085 cl:26.736970207838105
filename: 0_hidden Epoch 46 loss:26.73413522177246 ael:0.01237055706029043 cl:26.72176466860024
filename: 0_hidden Epoch 47 loss:26.714587573797722 ael:0.01234252157910272 cl:26.702245042442172
filename: 0_hidden Epoch 48 loss:26.72279329795392 ael:0.012368440114192745 cl:26.710424857229846
filename: 0_hidden Epoch 49 loss:26.68817046338687 ael:0.012365728703732938 cl:26.675804723523772
filename: 0_hidden Epoch 50 loss:26.674744670159672 ael:0.012378829200926492 cl:26.66236580085524
filename: 0_hidden Epoch 51 loss:26.66221899723171 ael:0.012305729297461213 cl:26.64991327009996
filename: 0_hidden Epoch 52 loss:26.65087081058055 ael:0.012413196541005884 cl:26.638457616682356
filename: 0_hidden Epoch 53 loss:26.63991609543406 ael:0.012365056408109368 cl:26.627551042308646
filename: 0_hidden Epoch 54 loss:26.629866400698333 ael:0.012352251796561218 cl:26.617514142095203
filename: 0_hidden Epoch 55 loss:26.619817981113123 ael:0.01235759093610332 cl:26.60746040989495
filename: 0_hidden Epoch 56 loss:26.609219429332597 ael:0.01237669654274558 cl:26.596842711652616
filename: 0_hidden Epoch 57 loss:26.59995515587538 ael:0.012359993587811771 cl:26.587595132681038
filename: 0_hidden Epoch 58 loss:26.591666987093042 ael:0.012346395660841412 cl:26.579320589573307
filename: 0_hidden Epoch 59 loss:26.58061029754528 ael:0.012338082820696188 cl:26.568272221534905
filename: 0_hidden Epoch 60 loss:26.566118214238905 ael:0.012344317766528334 cl:26.553773895368142
filename: 0_hidden Epoch 61 loss:26.558202432424274 ael:0.012314189451983319 cl:26.545888211714658
filename: 0_hidden Epoch 62 loss:26.533749257370776 ael:0.012311189685975573 cl:26.521438070904857
filename: 0_hidden Epoch 63 loss:26.491081714054005 ael:0.012353532584897943 cl:26.478728180300358
filename: 0_hidden Epoch 64 loss:26.45971566613912 ael:0.01223975472434293 cl:26.44747590576983
filename: 0_hidden Epoch 65 loss:26.422547531281563 ael:0.012197539133428206 cl:26.41034997762618
filename: 0_hidden Epoch 66 loss:26.401895919443376 ael:0.012133121562118713 cl:26.389762805442487
filename: 0_hidden Epoch 67 loss:26.37850891079482 ael:0.01210493486347611 cl:26.36640395995258
filename: 0_hidden Epoch 68 loss:26.360350103758538 ael:0.012025244466501333 cl:26.34832485366434
filename: 0_hidden Epoch 69 loss:26.336987138610667 ael:0.012041676591855238 cl:26.32494546288787
filename: 0_hidden Epoch 70 loss:26.322938766202952 ael:0.012040452696337989 cl:26.310898293423357
filename: 0_hidden Epoch 71 loss:26.308740153410625 ael:0.012063934411095892 cl:26.296676211716232
filename: 0_hidden Epoch 72 loss:26.297239372723535 ael:0.012036705543776578 cl:26.28520267008775
filename: 0_hidden Epoch 73 loss:26.292383164011373 ael:0.011912270739788592 cl:26.28047090531164
filename: 0_hidden Epoch 74 loss:26.264490901871742 ael:0.011845916404606017 cl:26.252644987870646
filename: 0_hidden Epoch 75 loss:26.243900464227302 ael:0.01187717555180054 cl:26.232023301356943
filename: 0_hidden Epoch 76 loss:26.230685793676543 ael:0.011956336213395065 cl:26.218729450104462
filename: 0_hidden Epoch 77 loss:26.232963512849288 ael:0.011849551818337693 cl:26.22111396697371
filename: 0_hidden Epoch 78 loss:26.2082380493754 ael:0.011780726137873726 cl:26.196457320915034
filename: 0_hidden Epoch 79 loss:26.197976330139923 ael:0.011777700326340576 cl:26.186198628241623
filename: 0_hidden Epoch 80 loss:26.20138785169819 ael:0.01171005859954543 cl:26.189677782707815
filename: 0_hidden Epoch 81 loss:26.162948828093043 ael:0.011568131908756373 cl:26.15138070563179
filename: 0_hidden Epoch 82 loss:26.170652972562056 ael:0.011642292520369654 cl:26.159010692416686
filename: 0_hidden Epoch 83 loss:26.161312930582994 ael:0.01163740341067374 cl:26.149675509836516
filename: 0_hidden Epoch 84 loss:26.152765407708205 ael:0.011636658349988492 cl:26.14112872823899
filename: 0_hidden Epoch 85 loss:26.14697057529654 ael:0.011569237063458453 cl:26.13540134130348
filename: 0_hidden Epoch 86 loss:26.130226950274807 ael:0.011590971258865384 cl:26.118635981110764
filename: 0_hidden Epoch 87 loss:26.10732907323265 ael:0.01147621675562136 cl:26.095852859165223
filename: 0_hidden Epoch 88 loss:26.104244221423453 ael:0.011531452003204793 cl:26.09271276722116
filename: 0_hidden Epoch 89 loss:26.09712488940297 ael:0.011460053109973849 cl:26.085664828266292
filename: 0_hidden Epoch 90 loss:26.103523987221998 ael:0.011439732511453195 cl:26.092084262431555
filename: 0_hidden Epoch 91 loss:26.08690556200867 ael:0.011419058983685674 cl:26.07548649312026
filename: 0_hidden Epoch 92 loss:26.08402369265301 ael:0.01143012801316528 cl:26.072593553
filename: 0_hidden Epoch 93 loss:26.07121099025743 ael:0.011395414565786258 cl:26.059815583092718
filename: 0_hidden Epoch 94 loss:26.061190841373683 ael:0.011497253451182797 cl:26.049693604222334
filename: 0_hidden Epoch 95 loss:26.049264998480144 ael:0.011453125806262043 cl:26.037811870014192
filename: 0_hidden Epoch 96 loss:26.03774531407074 ael:0.011417200726967423 cl:26.026328112586487
filename: 0_hidden Epoch 97 loss:26.030002662360644 ael:0.011350818907829288 cl:26.01865184475134
filename: 0_hidden Epoch 98 loss:26.004262106100782 ael:0.011379617427266082 cl:25.992882486221244
filename: 0_hidden Epoch 99 loss:26.000164847003322 ael:0.011260590163455991 cl:25.9889042547428
filename: 0_hidden Epoch 100 loss:25.99265489950806 ael:0.011328783604169007 cl:25.981326110507997
filename: 0_hidden Epoch 101 loss:25.98590511762947 ael:0.011308025207522051 cl:25.974597103596693
filename: 0_hidden Epoch 102 loss:25.95130839138515 ael:0.011402923036539237 cl:25.939905470050345
filename: 0_hidden Epoch 103 loss:25.946476263813658 ael:0.011293212895927125 cl:25.935183049208494
filename: 0_hidden Epoch 104 loss:25.916693677068764 ael:0.011385444116614012 cl:25.905308226832354
filename: 0_hidden Epoch 105 loss:25.90675539438445 ael:0.01122425322241232 cl:25.89553112547771
filename: 0_hidden Epoch 106 loss:25.897191728644923 ael:0.011389484847331306 cl:25.885802240175824
filename: 0_hidden Epoch 107 loss:25.89139384201732 ael:0.011365246219373714 cl:25.88002859523495
filename: 0_hidden Epoch 108 loss:25.87885480459016 ael:0.011390445243823783 cl:25.867464352076542
filename: 0_hidden Epoch 109 loss:25.868335965848285 ael:0.011316790898861997 cl:25.857019200134893
filename: 0_hidden Epoch 110 loss:25.859164866717457 ael:0.01137590363915774 cl:25.847788967051144
filename: 0_hidden Epoch 111 loss:25.818352213416713 ael:0.011327825674574868 cl:25.807024388461166
filename: 0_hidden Epoch 112 loss:25.825919487377448 ael:0.01134795125759913 cl:25.814571531943336
filename: 0_hidden Epoch 113 loss:25.824764139557193 ael:0.011415809685491142 cl:25.813348339970343
filename: 0_hidden Epoch 114 loss:25.811315758498118 ael:0.01147560612495465 cl:25.79984017355616
filename: 0_hidden Epoch 115 loss:25.7894195129542 ael:0.011335043708463374 cl:25.77808446035335
filename: 0_hidden Epoch 116 loss:25.796601285869155 ael:0.011352459882827497 cl:25.785248826695604
filename: 0_hidden Epoch 117 loss:25.768084639366048 ael:0.0112962178976706 cl:25.75678843507064
filename: 0_hidden Epoch 118 loss:25.764617756303164 ael:0.01141869227589077 cl:25.75319905229216
filename: 0_hidden Epoch 119 loss:25.753779591450133 ael:0.011394224401174824 cl:25.742385347284138
filename: 0_hidden Epoch 120 loss:25.736647245243486 ael:0.011389853644694501 cl:25.725257385751675
filename: 0_hidden Epoch 121 loss:25.76544456159305 ael:0.011437366558280123 cl:25.75400719199025
filename: 0_hidden Epoch 122 loss:25.708821149588687 ael:0.011285704925530292 cl:25.69753545990789
filename: 0_hidden Epoch 123 loss:25.72487039523791 ael:0.01137449664329683 cl:25.713495899005327
filename: 0_hidden Epoch 124 loss:25.723219887268336 ael:0.011392729630693044 cl:25.711827171746638
filename: 0_hidden Epoch 125 loss:25.707660660453733 ael:0.011468608252272052 cl:25.696192075012675
filename: 0_hidden Epoch 126 loss:25.691521320043435 ael:0.01140305944772807 cl:25.680118275802556
filename: 0_hidden Epoch 127 loss:25.689157637290016 ael:0.011440538336716793 cl:25.677717100551327
filename: 0_hidden Epoch 128 loss:25.709280809854913 ael:0.011560922584590584 cl:25.697719890457748
filename: 0_hidden Epoch 129 loss:25.663050882383263 ael:0.011535394568471864 cl:25.651515485200488
filename: 0_hidden Epoch 130 loss:25.6732938415429 ael:0.011347184955407619 cl:25.661946650430938
filename: 0_hidden Epoch 131 loss:25.678443371745498 ael:0.011397222357236099 cl:25.667046123294163
filename: 0_hidden Epoch 132 loss:25.663039009656533 ael:0.011340515965995676 cl:25.65169850386682
filename: 0_hidden Epoch 133 loss:25.645928683609334 ael:0.011447420520794234 cl:25.634481281030098
filename: 0_hidden Epoch 134 loss:25.64193363320285 ael:0.011433021806816612 cl:25.630500621388528
filename: 0_hidden Epoch 135 loss:25.638771702385792 ael:0.011378382687260739 cl:25.627393319248625
filename: 0_hidden Epoch 136 loss:25.62848534355517 ael:0.01137805809133712 cl:25.61710728995991
filename: 0_hidden Epoch 137 loss:25.625828480653304 ael:0.011602666268017904 cl:25.614225828498782
filename: 0_hidden Epoch 138 loss:25.62151954810657 ael:0.011460244352544837 cl:25.610059296465476
filename: 0_hidden Epoch 139 loss:25.62009125739108 ael:0.011362469764490114 cl:25.608728789822305
filename: 0_hidden Epoch 140 loss:25.591388826066815 ael:0.011579033511342346 cl:25.57980980030049
filename: 0_hidden Epoch 141 loss:25.614752002459497 ael:0.011400401221676022 cl:25.603351606076348
filename: 0_hidden Epoch 142 loss:25.586058864370738 ael:0.011456253281987655 cl:25.574602600263578
filename: 0_hidden Epoch 143 loss:25.607249175066723 ael:0.011428393531767738 cl:25.595820766853027
filename: 0_hidden Epoch 144 loss:25.56205311505198 ael:0.011490217449036257 cl:25.550562886619492
filename: 0_hidden Epoch 145 loss:25.574345380127838 ael:0.011391445167701762 cl:25.562953952815423
filename: 0_hidden Epoch 146 loss:25.53659516671373 ael:0.011470331157588798 cl:25.525124846760708
filename: 0_hidden Epoch 147 loss:25.54441718655731 ael:0.011606463606976066 cl:25.532810712792056
filename: 0_hidden Epoch 148 loss:25.53519327699106 ael:0.011789241047824372 cl:25.52340403651692
filename: 0_hidden Epoch 149 loss:25.5412954706076 ael:0.01204079001852391 cl:25.529254700548936
filename: 0_hidden Epoch 150 loss:25.53111537713655 ael:0.011823469467620144 cl:25.519291917306976
filename: 0_hidden Epoch 151 loss:25.52223505149961 ael:0.011786709185142071 cl:25.51044832675917
filename: 0_hidden Epoch 152 loss:25.51440384596334 ael:0.011677704126984061 cl:25.50272615196913
filename: 0_hidden Epoch 153 loss:25.506364667218776 ael:0.011684850366516815 cl:25.494679825468214
filename: 0_hidden Epoch 154 loss:25.534726356816684 ael:0.011616507493727663 cl:25.523109856220294
filename: 0_hidden Epoch 155 loss:25.481128465250716 ael:0.01171123613485263 cl:25.469417240175083
filename: 0_hidden Epoch 156 loss:25.49854790314618 ael:0.011723177190952564 cl:25.486824718541403
filename: 0_hidden Epoch 157 loss:25.50382424169042 ael:0.01160795197447449 cl:25.4922162884433
filename: 0_hidden Epoch 158 loss:25.4887241097741 ael:0.01160781264254104 cl:25.477116294796314
filename: 0_hidden Epoch 159 loss:25.505820413006443 ael:0.011435036626998882 cl:25.494385380923532
filename: 0_hidden Epoch 160 loss:25.490556488774544 ael:0.011564268004801837 cl:25.478992221723196
filename: 0_hidden Epoch 161 loss:25.47599464167619 ael:0.011430796119525122 cl:25.46456387904302
filename: 0_hidden Epoch 162 loss:25.496334952401675 ael:0.0113294125383437 cl:25.485005528899002
filename: 0_hidden Epoch 163 loss:25.48312122054605 ael:0.011282682693006408 cl:25.47183853591876
filename: 0_hidden Epoch 164 loss:25.472068176699704 ael:0.011519439596468242 cl:25.46054873887061
filename: 0_hidden Epoch 165 loss:25.465639237285956 ael:0.011287126579125754 cl:25.454352111908587
filename: 0_hidden Epoch 166 loss:25.461087067473862 ael:0.011284972082311906 cl:25.449802098329922
filename: 0_hidden Epoch 167 loss:25.443432909703954 ael:0.011364500518802717 cl:25.43206843108455
filename: 0_hidden Epoch 168 loss:25.459408320297506 ael:0.011299151761822652 cl:25.44810917009714
filename: 0_hidden Epoch 169 loss:25.459867968273123 ael:0.011454887595140208 cl:25.448413081482155
filename: 0_hidden Epoch 170 loss:25.427782869127743 ael:0.011344698168475375 cl:25.416438155341332
filename: 0_hidden Epoch 171 loss:25.42333103676165 ael:0.011291568958175385 cl:25.412039484461133
filename: 0_hidden Epoch 172 loss:25.435237329139664 ael:0.011179173017911647 cl:25.424058147557936
filename: 0_hidden Epoch 173 loss:25.429794097974135 ael:0.011192566522765054 cl:25.41860154728423
filename: 0_hidden Epoch 174 loss:25.43599713295158 ael:0.011376572007323123 cl:25.424620562679
filename: 0_hidden Epoch 175 loss:25.442191755776438 ael:0.01124421477001243 cl:25.430947521546173
filename: 0_hidden Epoch 176 loss:25.416502535079115 ael:0.011294404198154898 cl:25.405208144416456
filename: 0_hidden Epoch 177 loss:25.45559199913538 ael:0.011272071803343473 cl:25.444319925143073
filename: 0_hidden Epoch 178 loss:25.42159666767343 ael:0.011176261781559949 cl:25.410420402038305
filename: 0_hidden Epoch 179 loss:25.460456446395302 ael:0.011431739970132486 cl:25.449024682845792
filename: 0_hidden Epoch 180 loss:25.428195000078905 ael:0.011129651112130127 cl:25.41706534503594
filename: 0_hidden Epoch 181 loss:25.436644764230753 ael:0.011147381554414344 cl:25.42549737691399
filename: 0_hidden Epoch 182 loss:25.451389993336523 ael:0.011098420760169344 cl:25.440291563349774
filename: 0_hidden Epoch 183 loss:25.43055296001826 ael:0.01123494375309563 cl:25.41931800596473
filename: 0_hidden Epoch 184 loss:25.43187220078344 ael:0.011301994421251156 cl:25.420570215293587
filename: 0_hidden Epoch 185 loss:25.41039174802352 ael:0.01118395490286046 cl:25.39920777617757
filename: 0_hidden Epoch 186 loss:25.42975964279267 ael:0.011110432042604881 cl:25.41864921640495
filename: 0_hidden Epoch 187 loss:25.411855749098756 ael:0.011200094172461735 cl:25.4006556627302
filename: 0_hidden Epoch 188 loss:25.422230770834695 ael:0.01126670586174047 cl:25.410964044792923
filename: 0_hidden Epoch 189 loss:25.417821298046935 ael:0.011287492039030927 cl:25.40653383237337
filename: 0_hidden Epoch 190 loss:25.39991092182579 ael:0.011106630845765793 cl:25.388804300917382
filename: 0_hidden Epoch 191 loss:25.418061283678476 ael:0.011185698222820551 cl:25.406875579625044
filename: 0_hidden Epoch 192 loss:25.384584562844726 ael:0.011311430356529418 cl:25.37327313970473
filename: 0_hidden Epoch 193 loss:25.37935671535558 ael:0.011287321342568674 cl:25.368069384110537
filename: 0_hidden Epoch 194 loss:25.384158942183802 ael:0.011287585377207074 cl:25.372871350531515
filename: 0_hidden Epoch 195 loss:25.380385439961465 ael:0.01124850923887128 cl:25.36913692552718
filename: 0_hidden Epoch 196 loss:25.381893591971057 ael:0.011177734396466554 cl:25.37071585991284
filename: 0_hidden Epoch 197 loss:25.350882118092972 ael:0.011314163654382509 cl:25.33956796490181
filename: 0_hidden Epoch 198 loss:25.365957035828252 ael:0.011297776179625966 cl:25.354659246812652
filename: 0_hidden Epoch 199 loss:25.367361590308235 ael:0.01121421141003829 cl:25.356147372045683
filename: 0_hidden Epoch 200 loss:25.335138544458275 ael:0.011087352666138186 cl:25.32405117985898
filename: 0_hidden Epoch 201 loss:25.375634267548136 ael:0.01132638933286341 cl:25.364307859085088
filename: 0_hidden Epoch 202 loss:25.35236033863278 ael:0.011180302362245416 cl:25.34118005396904

C:\Users\Lincoln\AppData\Local\Temp\ipykernel_8000\4243116071.py:86: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
C:\Users\Lincoln\AppData\Local\Temp\ipykernel_8000\4243116071.py:87: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3         4  Label
0       -0.053386 -0.053189 -0.042977 -0.079077 -0.078581      4
1       -0.058705 -0.051918 -0.074439 -0.072279 -0.040833      3
2       -0.077854 -0.070023 -0.068061 -0.068031 -0.067078      1
3       -0.054707 -0.067067 -0.066772 -0.047801 -0.062801      2
4       -0.078843 -0.070795 -0.068391 -0.068063 -0.067610      1
...           ...       ...       ...       ...       ...    ...
1270932 -0.058806 -0.052559 -0.073643 -0.071532 -0.041911      3
1270933 -0.053714 -0.069320 -0.065408 -0.043749 -0.066245      2
1270934 -0.058806 -0.052559 -0.073643 -0.071532 -0.041911      3
1270935 -0.085444 -0.073906 -0.067905 -0.070930 -0.072181      1
1270936 -0.071814 -0.067486 -0.067072 -0.064917 -0.064484      1

[1270937 rows x 6 columns]

               0         1         2         3         4  Label
0      -0.053725 -0.069329 -0.065424 -0.043750 -0.066246      2
1      -0.057952 -0.051771 -0.074290 -0.071671 -0.040624      3
2      -0.053718 -0.069321 -0.065408 -0.043752 -0.066247      2
3      -0.082984 -0.076963 -0.064629 -0.064164 -0.077915      0
4      -0.082982 -0.076370 -0.064958 -0.064956 -0.077028      0
...          ...       ...       ...       ...       ...    ...
519951 -0.082985 -0.077052 -0.064580 -0.064046 -0.078047      0
519952 -0.082981 -0.075965 -0.065183 -0.065495 -0.076425      0
519953 -0.077936 -0.070029 -0.068020 -0.068109 -0.067109      1
519954 -0.079178 -0.070791 -0.067538 -0.068504 -0.068062      1
519955 -0.082985 -0.077021 -0.064596 -0.064086 -0.078002      0

[519956 rows x 6 columns]

               0         1         2         3         4  Label
0      -0.053720 -0.069321 -0.065408 -0.043754 -0.066247      2
1      -0.078099 -0.070152 -0.067556 -0.068144 -0.067278      1
2      -0.053387 -0.053192 -0.042975 -0.079073 -0.078586      4
3      -0.058728 -0.051679 -0.074319 -0.072646 -0.040469      3
4      -0.079595 -0.071408 -0.068492 -0.067989 -0.068639      0
...          ...       ...       ...       ...       ...    ...
649942 -0.054371 -0.052876 -0.041912 -0.081598 -0.079855      4
649943 -0.054752 -0.054570 -0.041024 -0.079506 -0.082074      4
649944 -0.078664 -0.070900 -0.068478 -0.067734 -0.067688      1
649945 -0.078411 -0.070233 -0.067749 -0.068367 -0.067266      1
649946 -0.082985 -0.077029 -0.064592 -0.064076 -0.078013      0

[649947 rows x 6 columns]

2_hidden
cpu
[0.0, 1.0, 3.0, 4.0, 5.0]
82 5
filename: 2_hidden Epoch 1 loss:33.487650251667404 ael:0.02512181257796392 cl:33.46252843399494
filename: 2_hidden Epoch 2 loss:29.966768932900234 ael:0.017616274009039354 cl:29.949152669850847
filename: 2_hidden Epoch 3 loss:28.933614027012162 ael:0.017361981615053805 cl:28.916252062613506
filename: 2_hidden Epoch 4 loss:27.98896389732584 ael:0.017023638789460324 cl:27.971940243592737
filename: 2_hidden Epoch 5 loss:27.569695825744095 ael:0.016778788932364935 cl:27.55291702928599
filename: 2_hidden Epoch 6 loss:27.29408147823044 ael:0.016714102549652693 cl:27.277367383834214
filename: 2_hidden Epoch 7 loss:27.072784506368357 ael:0.016673850730246707 cl:27.05611065479747
filename: 2_hidden Epoch 8 loss:26.887468914121214 ael:0.01657306185994319 cl:26.870895859790824
filename: 2_hidden Epoch 9 loss:26.73831952134071 ael:0.01637236049387887 cl:26.721947164702833
filename: 2_hidden Epoch 10 loss:26.607109187499823 ael:0.01597159669505792 cl:26.591137604406704
filename: 2_hidden Epoch 11 loss:26.495992082740827 ael:0.015394039947964382 cl:26.480598042025203
filename: 2_hidden Epoch 12 loss:26.392876302150256 ael:0.015037000451607314 cl:26.377839302598385
filename: 2_hidden Epoch 13 loss:26.304125540437756 ael:0.014903718510599077 cl:26.28922182105438
filename: 2_hidden Epoch 14 loss:26.214239543780945 ael:0.014839014386464107 cl:26.199400508612918
filename: 2_hidden Epoch 15 loss:26.14036766688029 ael:0.014763400724364651 cl:26.1256042642203
filename: 2_hidden Epoch 16 loss:26.08122663776777 ael:0.014700868619028588 cl:26.06652577718099
filename: 2_hidden Epoch 17 loss:26.015916494179887 ael:0.014643232325331596 cl:26.0012732595031
filename: 2_hidden Epoch 18 loss:25.95744590090032 ael:0.014600078375705065 cl:25.94284582082291
filename: 2_hidden Epoch 19 loss:25.913052678805347 ael:0.014586114192283468 cl:25.89846657925879
filename: 2_hidden Epoch 20 loss:25.862371367181254 ael:0.01456313218229739 cl:25.847808230550665
filename: 2_hidden Epoch 21 loss:25.82470477756701 ael:0.014572523479290002 cl:25.810132240830807
filename: 2_hidden Epoch 22 loss:25.778111740580776 ael:0.014569024498198638 cl:25.763542730208727
filename: 2_hidden Epoch 23 loss:25.74840120349014 ael:0.014569234199364458 cl:25.733831971151787
filename: 2_hidden Epoch 24 loss:25.70516764099835 ael:0.014573230010549925 cl:25.690594416055067
filename: 2_hidden Epoch 25 loss:25.672242322999832 ael:0.01453052141039213 cl:25.657711802030864
filename: 2_hidden Epoch 26 loss:25.641603015319646 ael:0.014524544561172874 cl:25.627078459555644
filename: 2_hidden Epoch 27 loss:25.607394857573926 ael:0.01447466123081221 cl:25.59292020463107
filename: 2_hidden Epoch 28 loss:25.587200432492974 ael:0.014472037488703578 cl:25.572728384586803
filename: 2_hidden Epoch 29 loss:25.54856768435205 ael:0.014449904482179915 cl:25.534117778421145
filename: 2_hidden Epoch 30 loss:25.52250252606576 ael:0.014410277377073354 cl:25.508092231081243
filename: 2_hidden Epoch 31 loss:25.497983736740917 ael:0.01432777592825175 cl:25.48365597027784
filename: 2_hidden Epoch 32 loss:25.47168290433828 ael:0.014273892192725549 cl:25.457409011550816
filename: 2_hidden Epoch 33 loss:25.45006593849227 ael:0.014216119276185395 cl:25.435849816060205
filename: 2_hidden Epoch 34 loss:25.420863009893406 ael:0.014162548407585475 cl:25.406700464995982
filename: 2_hidden Epoch 35 loss:25.402153093773023 ael:0.014104808778202499 cl:25.388048293018898
filename: 2_hidden Epoch 36 loss:25.38349398060849 ael:0.01404657536022888 cl:25.369447403623347
filename: 2_hidden Epoch 37 loss:25.36480843393426 ael:0.013990397383159364 cl:25.350818017769974
filename: 2_hidden Epoch 38 loss:25.317374802193445 ael:0.01393921369310926 cl:25.303435580493414
filename: 2_hidden Epoch 39 loss:25.2892848466572 ael:0.013902447201387837 cl:25.27538239216944
filename: 2_hidden Epoch 40 loss:25.256810576455635 ael:0.01381432990276674 cl:25.242996242032415
filename: 2_hidden Epoch 41 loss:25.232241675170542 ael:0.013779545209931526 cl:25.21846210580123
filename: 2_hidden Epoch 42 loss:25.202487367217305 ael:0.013738114107944812 cl:25.18874926093029
filename: 2_hidden Epoch 43 loss:25.171779402236492 ael:0.013685139007757457 cl:25.15809425220155
filename: 2_hidden Epoch 44 loss:25.138231817881266 ael:0.013640625123206896 cl:25.12459118380184
filename: 2_hidden Epoch 45 loss:25.112742605265122 ael:0.013597959833633568 cl:25.09914465396725
filename: 2_hidden Epoch 46 loss:25.071610087679144 ael:0.013584415649461468 cl:25.05802566349855
filename: 2_hidden Epoch 47 loss:25.039477182689467 ael:0.013551184774120475 cl:25.025925997683878
filename: 2_hidden Epoch 48 loss:25.010424961960105 ael:0.013507303995575908 cl:24.996917659915677
filename: 2_hidden Epoch 49 loss:24.970649009280734 ael:0.013462360060027642 cl:24.95718663310447
filename: 2_hidden Epoch 50 loss:24.94248175370066 ael:0.013444047471050892 cl:24.929037702013876
filename: 2_hidden Epoch 51 loss:24.906599226053697 ael:0.013398453787143468 cl:24.893200779518885
filename: 2_hidden Epoch 52 loss:24.88026886767114 ael:0.013375899406171768 cl:24.86689295796623
filename: 2_hidden Epoch 53 loss:24.842782787969934 ael:0.013347279935617719 cl:24.82943552307218
filename: 2_hidden Epoch 54 loss:24.812405264447307 ael:0.013334098012780238 cl:24.799071172524613
filename: 2_hidden Epoch 55 loss:24.776330382363838 ael:0.013318570924389083 cl:24.763011827524643
filename: 2_hidden Epoch 56 loss:24.744901211498775 ael:0.013274387401741063 cl:24.731626826838443
filename: 2_hidden Epoch 57 loss:24.705648957079614 ael:0.013250063634232472 cl:24.69239889613369
filename: 2_hidden Epoch 58 loss:24.68220803612157 ael:0.013250920346976197 cl:24.66895712300351
filename: 2_hidden Epoch 59 loss:24.649570583321196 ael:0.013273280162135498 cl:24.636297289530436
filename: 2_hidden Epoch 60 loss:24.627090268943743 ael:0.013255747799265978 cl:24.613834514952543
filename: 2_hidden Epoch 61 loss:24.60157967617637 ael:0.013193764870343676 cl:24.588385910458037
filename: 2_hidden Epoch 62 loss:24.576431651422155 ael:0.01316070315340937 cl:24.563270941951817
filename: 2_hidden Epoch 63 loss:24.556086022114894 ael:0.013150679166238122 cl:24.542935342956007
filename: 2_hidden Epoch 64 loss:24.53523438158091 ael:0.013111085841726315 cl:24.522123294406466
filename: 2_hidden Epoch 65 loss:24.511096218176057 ael:0.01308354154359876 cl:24.4980126849392
filename: 2_hidden Epoch 66 loss:24.493506608371845 ael:0.013028373628342797 cl:24.48047823654978
filename: 2_hidden Epoch 67 loss:24.478739064199882 ael:0.012997166335048993 cl:24.465741893701384
filename: 2_hidden Epoch 68 loss:24.462290938974125 ael:0.012998608311866982 cl:24.449292322348434
filename: 2_hidden Epoch 69 loss:24.456430850112646 ael:0.012915587502569832 cl:24.443515256692095
filename: 2_hidden Epoch 70 loss:24.438698816020587 ael:0.012918705386191345 cl:24.425780103360005
filename: 2_hidden Epoch 71 loss:24.423988816333793 ael:0.012922736551144232 cl:24.41106608095225
filename: 2_hidden Epoch 72 loss:24.413510845697413 ael:0.012899186776689532 cl:24.40061165882133
filename: 2_hidden Epoch 73 loss:24.40462839282744 ael:0.012818922188231035 cl:24.39180948748226
filename: 2_hidden Epoch 74 loss:24.39500504041973 ael:0.012809017264387674 cl:24.382196007555688
filename: 2_hidden Epoch 75 loss:24.383502597697298 ael:0.012865766992095356 cl:24.370636840173376
filename: 2_hidden Epoch 76 loss:24.369727594252915 ael:0.012805881702793185 cl:24.35692171409116
filename: 2_hidden Epoch 77 loss:24.357346760041533 ael:0.012740170118556908 cl:24.344606594732632
filename: 2_hidden Epoch 78 loss:24.345606726930853 ael:0.01280388025082212 cl:24.332802847254346
filename: 2_hidden Epoch 79 loss:24.344880856408015 ael:0.012709905005370578 cl:24.33217094711393
filename: 2_hidden Epoch 80 loss:24.3310254637958 ael:0.01269345773977625 cl:24.31833199171992
filename: 2_hidden Epoch 81 loss:24.324501021981938 ael:0.012683788146170084 cl:24.31181722886381
filename: 2_hidden Epoch 82 loss:24.31575982389394 ael:0.012648166137970766 cl:24.303111651348093
filename: 2_hidden Epoch 83 loss:24.305902525695444 ael:0.012619912663028079 cl:24.293282614256206
filename: 2_hidden Epoch 84 loss:24.29920472875673 ael:0.01256756042075828 cl:24.286637165114197
filename: 2_hidden Epoch 85 loss:24.288844471089323 ael:0.01252000641638729 cl:24.276324472929304
filename: 2_hidden Epoch 86 loss:24.28701662877847 ael:0.012473094901233389 cl:24.274543548048587
filename: 2_hidden Epoch 87 loss:24.278039759920354 ael:0.012560508399929482 cl:24.26547924287138
filename: 2_hidden Epoch 88 loss:24.265128886908816 ael:0.012539356211145894 cl:24.252589530833284
filename: 2_hidden Epoch 89 loss:24.26246562199286 ael:0.012472262104417672 cl:24.249993355511226
filename: 2_hidden Epoch 90 loss:24.256197214963144 ael:0.01254451656060522 cl:24.243652720200387
filename: 2_hidden Epoch 91 loss:24.24432448671575 ael:0.012401013672678617 cl:24.231923478109795
filename: 2_hidden Epoch 92 loss:24.237446928860848 ael:0.012341643197255002 cl:24.225105274490446
filename: 2_hidden Epoch 93 loss:24.2270441858392 ael:0.012268403980728478 cl:24.21477578815661
filename: 2_hidden Epoch 94 loss:24.218145148517095 ael:0.012165986867185834 cl:24.20597916318659
filename: 2_hidden Epoch 95 loss:24.211768086751302 ael:0.012175788806903868 cl:24.199592293633355
filename: 2_hidden Epoch 96 loss:24.21249161101224 ael:0.012094793707807685 cl:24.200396822209942
filename: 2_hidden Epoch 97 loss:24.20317539862025 ael:0.011970046362757945 cl:24.191205345399197
filename: 2_hidden Epoch 98 loss:24.191249832911797 ael:0.011969293721363341 cl:24.179280552668878
filename: 2_hidden Epoch 99 loss:24.1927271642183 ael:0.011925343117998009 cl:24.18080181712993
filename: 2_hidden Epoch 100 loss:24.17901688235545 ael:0.01190166511894231 cl:24.167115226544833
filename: 2_hidden Epoch 101 loss:24.17997003800688 ael:0.011920929706944099 cl:24.16804910514787
filename: 2_hidden Epoch 102 loss:24.1727522771958 ael:0.011937042358685394 cl:24.160815241183453
filename: 2_hidden Epoch 103 loss:24.167765665890876 ael:0.011800424858780675 cl:24.15596524567632
filename: 2_hidden Epoch 104 loss:24.161556043680648 ael:0.01176954225707821 cl:24.1497865169369
filename: 2_hidden Epoch 105 loss:24.160307578594363 ael:0.011665721197356605 cl:24.148641854559468
filename: 2_hidden Epoch 106 loss:24.14809992494639 ael:0.011780340558228393 cl:24.136319575393408
filename: 2_hidden Epoch 107 loss:24.143414425431637 ael:0.011640665282179432 cl:24.131773759607682
filename: 2_hidden Epoch 108 loss:24.133662606401053 ael:0.01165989902066557 cl:24.122002733241747
filename: 2_hidden Epoch 109 loss:24.136979874393397 ael:0.011506491621591324 cl:24.125473360987435
filename: 2_hidden Epoch 110 loss:24.127631813183164 ael:0.011587390610376341 cl:24.11604442038731
filename: 2_hidden Epoch 111 loss:24.12005674406799 ael:0.011482288573231351 cl:24.108574440047057
filename: 2_hidden Epoch 112 loss:24.112725338740656 ael:0.011504147735789245 cl:24.101221195020173
filename: 2_hidden Epoch 113 loss:24.10687040529753 ael:0.011443776448464229 cl:24.095426628045868
filename: 2_hidden Epoch 114 loss:24.107989229793436 ael:0.011422811634430107 cl:24.09656642333806
filename: 2_hidden Epoch 115 loss:24.097096795645374 ael:0.011433276674187367 cl:24.085663507695784
filename: 2_hidden Epoch 116 loss:24.090101765192042 ael:0.011584998675409639 cl:24.07851676829377
filename: 2_hidden Epoch 117 loss:24.080285906094556 ael:0.01155070228875228 cl:24.06873522083662
filename: 2_hidden Epoch 118 loss:24.065579578332734 ael:0.011522786437713525 cl:24.05405679446215
filename: 2_hidden Epoch 119 loss:24.063544300703974 ael:0.01145034634796848 cl:24.052093941984122
filename: 2_hidden Epoch 120 loss:24.04427215453477 ael:0.011590915450101925 cl:24.03268123760558
filename: 2_hidden Epoch 121 loss:24.0455632365935 ael:0.011513682692148313 cl:24.034049556129858
filename: 2_hidden Epoch 122 loss:24.038078155294496 ael:0.011488853558647441 cl:24.026589311633195
filename: 2_hidden Epoch 123 loss:24.032715003253422 ael:0.01139039124977606 cl:24.021324621724805
filename: 2_hidden Epoch 124 loss:24.02763841472871 ael:0.011569484996974294 cl:24.016068937625104
filename: 2_hidden Epoch 125 loss:24.009046127363952 ael:0.011519282361035024 cl:23.9975268280297
filename: 2_hidden Epoch 126 loss:24.00864834590265 ael:0.01150452612112249 cl:23.9971438151354
filename: 2_hidden Epoch 127 loss:24.010426091868975 ael:0.011445153151687823 cl:23.9989809315107
filename: 2_hidden Epoch 128 loss:24.003582099446078 ael:0.011457486863776345 cl:23.99212461772718
filename: 2_hidden Epoch 129 loss:23.997330401794255 ael:0.011403401419302526 cl:23.985927006236295
filename: 2_hidden Epoch 130 loss:23.99142696369461 ael:0.011402176661765453 cl:23.98002479118213
filename: 2_hidden Epoch 131 loss:23.98566453331395 ael:0.011348768622254986 cl:23.974315762101558
filename: 2_hidden Epoch 132 loss:23.972611228764407 ael:0.011299951594971033 cl:23.961311284561603
filename: 2_hidden Epoch 133 loss:23.975395001305476 ael:0.01138595454816908 cl:23.964009050737346
filename: 2_hidden Epoch 134 loss:23.969874037915503 ael:0.011311779657721911 cl:23.95856225699709
filename: 2_hidden Epoch 135 loss:23.969835872538606 ael:0.011383510864889848 cl:23.958452366946037
filename: 2_hidden Epoch 136 loss:23.951436214558562 ael:0.011175135802613756 cl:23.9402610834579
filename: 2_hidden Epoch 137 loss:23.953052746622188 ael:0.011145953618245994 cl:23.941906802974945
filename: 2_hidden Epoch 138 loss:23.944068063769425 ael:0.011105975078838218 cl:23.932962103057324
filename: 2_hidden Epoch 139 loss:23.94372951719496 ael:0.01113113614074254 cl:23.932598364980596
filename: 2_hidden Epoch 140 loss:23.936450711746662 ael:0.011080596304079246 cl:23.925370106501887
filename: 2_hidden Epoch 141 loss:23.92951177742049 ael:0.011245023951816716 cl:23.91826674366555
filename: 2_hidden Epoch 142 loss:23.93499814474095 ael:0.011262811595514111 cl:23.923735334162128
filename: 2_hidden Epoch 143 loss:23.920117871245445 ael:0.01112488364836212 cl:23.908992966992116
filename: 2_hidden Epoch 144 loss:23.913420682204396 ael:0.011104342557097736 cl:23.902316333257662
filename: 2_hidden Epoch 145 loss:23.90297389225653 ael:0.011006695554559038 cl:23.891967195098164
filename: 2_hidden Epoch 146 loss:23.91236165978058 ael:0.011227528196187657 cl:23.901134139055397
filename: 2_hidden Epoch 147 loss:23.907115461672955 ael:0.011012882750334315 cl:23.89610256395842
filename: 2_hidden Epoch 148 loss:23.899254417419435 ael:0.011051930678185969 cl:23.888202494905705
filename: 2_hidden Epoch 149 loss:23.888344942059433 ael:0.011029693516712003 cl:23.877315269715606
filename: 2_hidden Epoch 150 loss:23.88012097118891 ael:0.011178374904131637 cl:23.868942585883783
filename: 2_hidden Epoch 151 loss:23.879311778531438 ael:0.01115982750871856 cl:23.86815196366338
filename: 2_hidden Epoch 152 loss:23.86591109392936 ael:0.011073573453526138 cl:23.854837528027986
filename: 2_hidden Epoch 153 loss:23.873349993410166 ael:0.011041763768945303 cl:23.86230823673003
filename: 2_hidden Epoch 154 loss:23.86020847342865 ael:0.011105889939071273 cl:23.849102595256785
filename: 2_hidden Epoch 155 loss:23.855573641347608 ael:0.01115584145803876 cl:23.844417804584168
filename: 2_hidden Epoch 156 loss:23.848782927529854 ael:0.011073812527571157 cl:23.83770912683498
filename: 2_hidden Epoch 157 loss:23.848754557670905 ael:0.011264027268979807 cl:23.83749053129676
filename: 2_hidden Epoch 158 loss:23.844216697536712 ael:0.011121103812515605 cl:23.833095590134114
filename: 2_hidden Epoch 159 loss:23.831104243986786 ael:0.011213434301589055 cl:23.81989080529464
filename: 2_hidden Epoch 160 loss:23.83667394292285 ael:0.011083140240693519 cl:23.825590790084927
filename: 2_hidden Epoch 161 loss:23.833802302399572 ael:0.011145171455559674 cl:23.822657125038013
filename: 2_hidden Epoch 162 loss:23.821278732143647 ael:0.011110358936739378 cl:23.810168383414286
filename: 2_hidden Epoch 163 loss:23.80733511963783 ael:0.01100329957270657 cl:23.79633182670638
filename: 2_hidden Epoch 164 loss:23.823246704346953 ael:0.01101674407854001 cl:23.812229958472894
filename: 2_hidden Epoch 165 loss:23.81284111647578 ael:0.01106463498245293 cl:23.801776483323838
filename: 2_hidden Epoch 166 loss:23.802155114893328 ael:0.011040546385604038 cl:23.791114562854432
filename: 2_hidden Epoch 167 loss:23.79004768906978 ael:0.010865505615369095 cl:23.779182174749543
filename: 2_hidden Epoch 168 loss:23.793060960825425 ael:0.010872030272747645 cl:23.782188931961507
filename: 2_hidden Epoch 169 loss:23.79044003179896 ael:0.010819800302375391 cl:23.779620229709916
filename: 2_hidden Epoch 170 loss:23.796870270667718 ael:0.010895618975941332 cl:23.785974663740014
filename: 2_hidden Epoch 171 loss:23.772741913934897 ael:0.010788736072074818 cl:23.76195318601285
filename: 2_hidden Epoch 172 loss:23.770582448948197 ael:0.010927599662511844 cl:23.759654845968324
filename: 2_hidden Epoch 173 loss:23.76441281246163 ael:0.010905544992062475 cl:23.753507259993526
filename: 2_hidden Epoch 174 loss:23.753916764398763 ael:0.010659217665364084 cl:23.743257558833786
filename: 2_hidden Epoch 175 loss:23.770306703779433 ael:0.010742830018627277 cl:23.759563872688695
filename: 2_hidden Epoch 176 loss:23.76180952752543 ael:0.010884989074523947 cl:23.7509245281331
filename: 2_hidden Epoch 177 loss:23.7460488971911 ael:0.010687173849069758 cl:23.735361723314252
filename: 2_hidden Epoch 178 loss:23.754003880595604 ael:0.010604604466121144 cl:23.74339928208736
filename: 2_hidden Epoch 179 loss:23.75194977375499 ael:0.010703817183119163 cl:23.741245940693638
filename: 2_hidden Epoch 180 loss:23.735201151329175 ael:0.010422549131925474 cl:23.724778588612875
filename: 2_hidden Epoch 181 loss:23.738443755545813 ael:0.010494584838685454 cl:23.72794919264944
filename: 2_hidden Epoch 182 loss:23.729221269819472 ael:0.010314320942539482 cl:23.718906961407576
filename: 2_hidden Epoch 183 loss:23.716419251202144 ael:0.010398958632940351 cl:23.706020295550253
filename: 2_hidden Epoch 184 loss:23.72491024641963 ael:0.010300680161698869 cl:23.714609568300304
filename: 2_hidden Epoch 185 loss:23.714434165285343 ael:0.010258794669334216 cl:23.704175367411118
filename: 2_hidden Epoch 186 loss:23.72212051313523 ael:0.010383411693217897 cl:23.711737101816993
filename: 2_hidden Epoch 187 loss:23.711871825324163 ael:0.0101021191195111 cl:23.701769703870628
filename: 2_hidden Epoch 188 loss:23.716168082387824 ael:0.010354011619125891 cl:23.705814069892927
filename: 2_hidden Epoch 189 loss:23.704711968159813 ael:0.010159815562077477 cl:23.69455214996784
filename: 2_hidden Epoch 190 loss:23.691526821761105 ael:0.010175511526210745 cl:23.68135132036711
filename: 2_hidden Epoch 191 loss:23.69364266144602 ael:0.010089705054980446 cl:23.683552952816612
filename: 2_hidden Epoch 192 loss:23.697880261962176 ael:0.010216513029926004 cl:23.68766375257258
filename: 2_hidden Epoch 193 loss:23.69598692397625 ael:0.010011139073360122 cl:23.685975765205963
filename: 2_hidden Epoch 194 loss:23.688509337665046 ael:0.010100932877472662 cl:23.678408413602593
filename: 2_hidden Epoch 195 loss:23.684195999234742 ael:0.010137894050060221 cl:23.674058107744184
filename: 2_hidden Epoch 196 loss:23.68374159126951 ael:0.009866845920649275 cl:23.67387475298162
filename: 2_hidden Epoch 197 loss:23.67711986686751 ael:0.010014863828965053 cl:23.667105017210307
filename: 2_hidden Epoch 198 loss:23.678057914867736 ael:0.009918354287585624 cl:23.668139536896643
filename: 2_hidden Epoch 199 loss:23.673124177832353 ael:0.009905808350910046 cl:23.66321837665045
filename: 2_hidden Epoch 200 loss:23.684483420500282 ael:0.009868523392047494 cl:23.674614889579907
filename: 2_hidden Epoch 201 loss:23.674115082255582 ael:0.01020453843146519 cl:23.66391052279556
filename: 2_hidden Epoch 202 loss:23.67906155112194 ael:0.01009957708530019 cl:23.668961982838592

C:\Users\Lincoln\AppData\Local\Temp\ipykernel_8000\4243116071.py:86: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X_train = torch.tensor(np.array(X_train), dtype=torch.float)
C:\Users\Lincoln\AppData\Local\Temp\ipykernel_8000\4243116071.py:87: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  y_train = torch.tensor(np.array(y_train), dtype=torch.float)

                0         1         2         3         4  Label
0        0.020301  0.048565  0.022761  0.021941  0.036099      0
1        0.045506  0.027528  0.062851  0.009310 -0.004456      4
2       -0.000567  0.010168  0.027457  0.065800  0.012319      3
3        0.023616  0.044950  0.022486  0.023244  0.036275      0
4        0.052435  0.017440  0.029375  0.039178  0.047848      1
...           ...       ...       ...       ...       ...    ...
1750627  0.000420  0.010403  0.027593  0.064326  0.012533      3
1750628  0.019939  0.047509  0.021574  0.021271  0.037057      0
1750629  0.048183  0.006340  0.028953  0.022703  0.037529      1
1750630  0.051754  0.024185  0.029759  0.044047  0.048044      1
1750631  0.020293  0.048570  0.022759  0.021928  0.036092      0

[1750632 rows x 6 columns]

               0         1         2         3         4  Label
0       0.025362 -0.010427  0.021430  0.014743  0.032444      2
1      -0.002271  0.010203  0.027721  0.064656  0.010508      3
2       0.025439 -0.010270  0.021344  0.015193  0.032742      2
3       0.020342  0.048539  0.022767  0.022007  0.036130      0
4       0.020755  0.048273  0.022831  0.022671  0.036443      0
...          ...       ...       ...       ...       ...    ...
519951  0.020281  0.048578  0.022758  0.021908  0.036083      0
519952  0.021035  0.048093  0.022874  0.023123  0.036657      0
519953  0.053127  0.017152  0.029682  0.038600  0.047774      1
519954  0.053113  0.018460  0.029799  0.040375  0.049625      1
519955  0.020302  0.048565  0.022761  0.021942  0.036099      0

[519956 rows x 6 columns]

               0         1         2         3         4  Label
0       0.025427 -0.010292  0.021380  0.015080  0.032653      2
1       0.052212  0.018176  0.028776  0.037790  0.046763      1
2       0.045463  0.027508  0.062818  0.009234 -0.004470      4
3       0.001226  0.009195  0.027030  0.064999  0.012225      3
4       0.023387  0.045060  0.022506  0.022906  0.036050      0
...          ...       ...       ...       ...       ...    ...
649942  0.039150  0.027490  0.066858 -0.000318 -0.013639      4
649943  0.033525  0.020132  0.060678 -0.011256 -0.013459      4
649944  0.052261  0.016182  0.029181  0.036825  0.048369      1
649945  0.052181  0.018067  0.028733  0.038030  0.046879      1
649946  0.020296  0.048568  0.022760  0.021933  0.036095      0

[649947 rows x 6 columns]

3_hidden
cpu
[0.0, 1.0, 2.0, 4.0, 5.0]
82 5
filename: 3_hidden Epoch 1 loss:37.35692320409711 ael:0.023719760050552118 cl:37.33320345797511
filename: 3_hidden Epoch 2 loss:30.486987739012108 ael:0.01583741099584317 cl:30.471150334711556
filename: 3_hidden Epoch 3 loss:29.242343649480016 ael:0.014931708561832405 cl:29.22741194332347
filename: 3_hidden Epoch 4 loss:28.45982389872806 ael:0.014926691877634655 cl:28.44489721750728
filename: 3_hidden Epoch 5 loss:27.97543596895684 ael:0.015039717555793839 cl:27.960396261776197
filename: 3_hidden Epoch 6 loss:27.713604138227833 ael:0.014897829325153596 cl:27.698706303860504
filename: 3_hidden Epoch 7 loss:27.507415047787276 ael:0.014772989281385946 cl:27.49264205941125
filename: 3_hidden Epoch 8 loss:27.309465023877728 ael:0.014573546917602764 cl:27.29489148503929
filename: 3_hidden Epoch 9 loss:27.127288985857234 ael:0.014426239902230983 cl:27.112862741977086
filename: 3_hidden Epoch 10 loss:26.953679816185147 ael:0.014338118093234186 cl:26.93934169904349
filename: 3_hidden Epoch 11 loss:26.817993016770732 ael:0.014307082719230571 cl:26.803685918105558
filename: 3_hidden Epoch 12 loss:26.701189632431724 ael:0.014218671202186027 cl:26.686970968382052
filename: 3_hidden Epoch 13 loss:26.587820442865446 ael:0.014070511187767133 cl:26.573749941572494
filename: 3_hidden Epoch 14 loss:26.495859686896964 ael:0.013801437593344313 cl:26.48205824033909
filename: 3_hidden Epoch 15 loss:26.403434582729673 ael:0.013406342637247699 cl:26.39002825723972
filename: 3_hidden Epoch 16 loss:26.328784656551246 ael:0.013032624113745 cl:26.315752025165033
filename: 3_hidden Epoch 17 loss:26.253904004996954 ael:0.012752716664763871 cl:26.24115129869098
filename: 3_hidden Epoch 18 loss:26.18516650597365 ael:0.012627723234219325 cl:26.17253878444292
filename: 3_hidden Epoch 19 loss:26.128071775135968 ael:0.012580330175944015 cl:26.115491452840566
filename: 3_hidden Epoch 20 loss:26.072392787247406 ael:0.012527080063749928 cl:26.059865704279343
filename: 3_hidden Epoch 21 loss:26.033028770363828 ael:0.012507692814664668 cl:26.02052107939389
filename: 3_hidden Epoch 22 loss:25.974701300483577 ael:0.012518310914990179 cl:25.962182985363746
filename: 3_hidden Epoch 23 loss:25.9418534155772 ael:0.012495532413777915 cl:25.92935788601529
filename: 3_hidden Epoch 24 loss:25.894894680473044 ael:0.012515854487179514 cl:25.88237882411543
filename: 3_hidden Epoch 25 loss:25.884182835077223 ael:0.012504996107187583 cl:25.87167782247781
filename: 3_hidden Epoch 26 loss:25.821291543063527 ael:0.012512566614714312 cl:25.808778988274817
filename: 3_hidden Epoch 27 loss:25.788794939983912 ael:0.012495758946894652 cl:25.776299172202823
filename: 3_hidden Epoch 28 loss:25.743474352549203 ael:0.012510684260941164 cl:25.730963656720856

KeyboardInterrupt: